CREATE TABLE "LABPPTO"."GLCOBINY" 
   (	"BIN_KEYBIN" VARCHAR2(8) NOT NULL ENABLE, 
	"BIN_DESBIN" VARCHAR2(36), 
	"BIN_IDEFUN" VARCHAR2(30), 
	"BIN_IDEVER" VARCHAR2(15), 
	"BIN_PERFIL" VARCHAR2(50)
   ) ;
