CREATE TABLE "LABPPTO"."PPLOORDE" 
   (	"ORD_KEYCIA" VARCHAR2(4) NOT NULL ENABLE, 
	"ORD_KEYVER" NUMBER(*,0) NOT NULL ENABLE, 
	"ORD_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"ORD_KEYMES" NUMBER(*,0) NOT NULL ENABLE
   ) ;
