CREATE TABLE "LABPPTO"."PPLOPPTO" 
   (	"PPT_KEYCIA" VARCHAR2(4) NOT NULL ENABLE, 
	"PPT_KEYVER" NUMBER(*,0) NOT NULL ENABLE, 
	"PPT_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"PPT_KEYCON" NUMBER(*,0) NOT NULL ENABLE, 
	"PPT_ENE" NUMBER(20,2) NOT NULL ENABLE, 
	"PPT_FEB" NUMBER(20,2) NOT NULL ENABLE, 
	"PPT_MAR" NUMBER(20,2) NOT NULL ENABLE, 
	"PPT_ABR" NUMBER(20,2) NOT NULL ENABLE, 
	"PPT_MAY" NUMBER(20,2) NOT NULL ENABLE, 
	"PPT_JUN" NUMBER(20,2) NOT NULL ENABLE, 
	"PPT_JUL" NUMBER(20,2) NOT NULL ENABLE, 
	"PPT_AGO" NUMBER(20,2) NOT NULL ENABLE, 
	"PPT_SEP" NUMBER(20,2) NOT NULL ENABLE, 
	"PPT_OCT" NUMBER(20,2) NOT NULL ENABLE, 
	"PPT_NOV" NUMBER(20,2) NOT NULL ENABLE, 
	"PPT_DIC" NUMBER(20,2) NOT NULL ENABLE
   ) ;
