CREATE TABLE "LABPPTO"."PPLOPIRA" 
   (	"PIR_KEYCIA" VARCHAR2(4) NOT NULL ENABLE, 
	"PIR_KEYVER" NUMBER(*,0) NOT NULL ENABLE, 
	"PIR_IMPORTE" NUMBER(20,2) NOT NULL ENABLE, 
	"PIR_313" NUMBER(20,2) NOT NULL ENABLE, 
	"PIR_353" NUMBER(20,2) NOT NULL ENABLE, 
	"PIR_325" NUMBER(20,2) NOT NULL ENABLE, 
	"PIR_103" NUMBER(20,2) NOT NULL ENABLE, 
	"PIR_105" NUMBER(20,2) NOT NULL ENABLE, 
	"PIR_225" NUMBER(20,2) NOT NULL ENABLE
   ) ;
