CREATE TABLE "LABPPTO"."PPLOAUX1" 
   (	"PRU_KEYCIA" VARCHAR2(4), 
	"PRU_KEYVER" NUMBER(*,0), 
	"PRU_KEYEMP" NUMBER(*,0), 
	"PRU_NUMMES" NUMBER(*,0), 
	"PRU_PORCEN" NUMBER(5,2), 
	"PRU_IMPORT" NUMBER(20,2), 
	"PRU_STATUS" NUMBER(*,0)
   ) ;
