CREATE TABLE "LABPPTO"."PPLOPIRA2K6" 
   (	"PIR_KEYCIA" VARCHAR2(4), 
	"PIR_KEYVER" NUMBER(*,0), 
	"PIR_KEYCON" NUMBER(*,0), 
	"PIR_IMPBTO" NUMBER(22,2), 
	"PIR_IMPUESTO" NUMBER(22,2), 
	"PIR_IMPNET" NUMBER(22,2)
   ) ;
