CREATE TABLE "LABPPTO"."TMP_PLZ_PPTOS" 
   (	"TMP_ENE" NUMBER(*,0), 
	"TMP_FEB" NUMBER(*,0), 
	"TMP_MAR" NUMBER(*,0), 
	"TMP_ABR" NUMBER(*,0), 
	"TMP_MAY" NUMBER(*,0), 
	"TMP_JUN" NUMBER(*,0), 
	"TMP_JUL" NUMBER(*,0), 
	"TMP_AGO" NUMBER(*,0), 
	"TMP_SEP" NUMBER(*,0), 
	"TMP_OCT" NUMBER(*,0), 
	"TMP_NOV" NUMBER(*,0), 
	"TMP_DIC" NUMBER(*,0), 
	"FECHA_PROC" VARCHAR2(6), 
	"HORA_PROC" VARCHAR2(6)
   ) ;
