CREATE TABLE "PPPT"."BMB1_PLANTILLAS" 
   (	"IDRESULTADOS" NUMBER(38,0) NOT NULL ENABLE, 
	"IDPARTE" NUMBER(38,0) NOT NULL ENABLE, 
	"IDPREGUNTA" NUMBER(38,0) NOT NULL ENABLE, 
	"CORRECTA1" NUMBER(38,0), 
	"CORRECTA2" NUMBER(38,0)
   ) ;
