CREATE TABLE "PPPT"."BMB2_PERSONALRESULTADOS" 
   (	"IDPERSONAL" NUMBER(38,0) NOT NULL ENABLE, 
	"IDPRUEBAABC" NUMBER(38,0) NOT NULL ENABLE, 
	"IDXRESULTADOS" NUMBER(38,0) NOT NULL ENABLE, 
	"VALOR" NUMBER
   ) ;
