CREATE TABLE "PPPT"."CAPCURSO" 
   (	"IDCURSO" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"CURSO" VARCHAR2(100) NOT NULL ENABLE, 
	"DURACION" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"CUPO" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"FRECUENCIA" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"COSTOPERSONATIPO" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"COSTOPERSONAVALOR" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"COSTOPERSONAOBS" VARCHAR2(255), 
	"CONTACTO" VARCHAR2(255), 
	"IDEMPRESA" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(4000), 
	"OBJETIVO" VARCHAR2(4000)
   ) ;
