CREATE TABLE "PPPT"."CATCOMPETENCIAS360" 
   (	"IDCOMPETENCIA" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"COMPETENCIA" VARCHAR2(255), 
	"TIPO" NUMBER(38,0), 
	"DEFINICION" VARCHAR2(4000), 
	"IDEMPRESA" NUMBER(38,0), 
	"INACTIVA" NUMBER(1,0) DEFAULT 0
   ) ;
