CREATE TABLE "PPPT"."CATCENTROCOSTOS" 
   (	"IDCENTROCOSTOS" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"CENTROCOSTOS" VARCHAR2(100) NOT NULL ENABLE, 
	"IDSECCION" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"IDEMPRESA" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE
   ) ;
