CREATE TABLE "PPPT"."CO_PERSONALESTADISTICA" 
   (	"IDPERSONAL" NUMBER(38,0) NOT NULL ENABLE, 
	"ANIO" NUMBER(38,0) NOT NULL ENABLE, 
	"VALOR1" NUMBER NOT NULL ENABLE, 
	"VALOR2" NUMBER NOT NULL ENABLE
   ) ;
