CREATE TABLE "PPPT"."COMPATIBILIDADCOMPETENCIAS" 
   (	"IDPERSONA" NUMBER(38,0) NOT NULL ENABLE, 
	"IDPERFIL" NUMBER(38,0) NOT NULL ENABLE, 
	"IDCOMPETENCIA" NUMBER(38,0) NOT NULL ENABLE, 
	"COMPATIBILIDAD0" NUMBER NOT NULL ENABLE, 
	"COMPATIBILIDAD1" NUMBER NOT NULL ENABLE, 
	"COMPATIBILIDAD2" NUMBER NOT NULL ENABLE
   ) ;
