CREATE TABLE "PPPT"."COMPARACIONPERSONAL" 
   (	"IDCOMPARACION" NUMBER(38,0) NOT NULL ENABLE, 
	"IDPERSONAL" NUMBER(38,0) NOT NULL ENABLE, 
	"IDPUESTO0" NUMBER, 
	"IDPUESTO1" NUMBER, 
	"IDPUESTO2" NUMBER, 
	"IDPUESTO3" NUMBER, 
	"IDPUESTO4" NUMBER, 
	"IDPUESTO5" NUMBER, 
	"IDPUESTO6" NUMBER, 
	"IDPUESTO7" NUMBER, 
	"IDPUESTO8" NUMBER, 
	"IDPUESTO9" NUMBER
   ) ;
