CREATE TABLE "PPPT"."ECPERSONAPUESTO" 
   (	"IDENTREVISTA" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"IDPERSONAL" NUMBER(38,0) NOT NULL ENABLE, 
	"IDPUESTO" NUMBER(38,0) NOT NULL ENABLE, 
	"FECHA" DATE NOT NULL ENABLE, 
	"RESULTADO" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"COMPATIBILIDAD" NUMBER DEFAULT 0 NOT NULL ENABLE, 
	"ENTREVISTADOR" VARCHAR2(100), 
	"COMENTARIOS" VARCHAR2(4000)
   ) ;
