CREATE TABLE "PPPT"."ECPUESTOCOMPETENCIAPREGUNTA" 
   (	"IDPUESTOPREGUNTA" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"IDPUESTO" NUMBER(38,0) NOT NULL ENABLE, 
	"IDCOMPETENCIAPREGUNTA" NUMBER(38,0) NOT NULL ENABLE
   ) ;
