CREATE TABLE "PPPT"."ECPUESTOCOMPETENCIANIVEL" 
   (	"IDPUESTO" NUMBER(38,0) NOT NULL ENABLE, 
	"IDCOMPETENCIA" NUMBER(38,0) NOT NULL ENABLE, 
	"NIVEL" NUMBER(38,0) NOT NULL ENABLE, 
	"NPNIVEL" NUMBER(38,0) DEFAULT 0, 
	"NPINFERIOR" NUMBER(38,0) DEFAULT 0, 
	"NPSUPERIOR" NUMBER(38,0) DEFAULT 0
   ) ;
