CREATE TABLE "PPPT"."ENTIDADEVALUACION360" 
   (	"IDGRUPOENTIDAD" NUMBER(38,0) NOT NULL ENABLE, 
	"IDPARAMETROEVALUACION" NUMBER(38,0) NOT NULL ENABLE, 
	"TIPOEVALUACION" NUMBER(38,0) NOT NULL ENABLE, 
	"IDENTIDAD1" NUMBER(38,0) NOT NULL ENABLE, 
	"IDENTIDAD2" NUMBER(38,0) NOT NULL ENABLE, 
	"STATUS" NUMBER(38,0), 
	"VALOR" NUMBER(38,0)
   ) ;
