CREATE TABLE "PPPT"."EVACATOPCION" 
   (	"IDOPCION" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"IDPREGUNTA" NUMBER(38,0) NOT NULL ENABLE, 
	"PUNTOS" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"OPCION" VARCHAR2(4000) NOT NULL ENABLE
   ) ;
