CREATE TABLE "PPPT"."EVALUACION" 
   (	"IDEVALUACION" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"EVALUACION" VARCHAR2(100) NOT NULL ENABLE, 
	"IDEMPRESA" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"MINCALIFICACION" NUMBER(38,0) DEFAULT 70 NOT NULL ENABLE, 
	"MAXMINUTOS" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"ACTIVA" NUMBER(1,0) DEFAULT 1 NOT NULL ENABLE, 
	"ORDENPREGUNTAS" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODOPREGUNTAS" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"MODOCALIFICACION" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"NAVEGACION" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"BMUSTANSWER" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"BSHOWCAL" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"BREVISION" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"BSHOWINTRO" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"INTRODUCCION" VARCHAR2(4000)
   ) ;
