CREATE TABLE "PPPT"."EXP_CATALOGO" 
   (	"IDCATALOGO" NUMBER(38,0) NOT NULL ENABLE, 
	"CATALOGO" VARCHAR2(50) NOT NULL ENABLE, 
	"ID" VARCHAR2(50) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(50) NOT NULL ENABLE
   ) ;
