CREATE TABLE "PPPT"."GRUPOENTIDADPREGUNTA360" 
   (	"IDGRUPOENTIDAD" NUMBER(38,0) NOT NULL ENABLE, 
	"IDEVALUADO" NUMBER(38,0) NOT NULL ENABLE, 
	"IDPREGUNTA" NUMBER(38,0) NOT NULL ENABLE, 
	"RESPUESTA" VARCHAR2(4000) NOT NULL ENABLE
   ) ;
