CREATE TABLE "PPPT"."GRUPO360" 
   (	"IDGRUPO" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"TIPO" NUMBER(38,0), 
	"TIPOEVALUACION" NUMBER(38,0), 
	"PERFIL" NUMBER(38,0), 
	"PESOJEFE" NUMBER(38,0), 
	"PESOPARES" NUMBER(38,0), 
	"PESOSUBORDINADOS" NUMBER(38,0), 
	"PESOCLIENTES" NUMBER(38,0), 
	"STATUS" NUMBER(38,0), 
	"FECHA" DATE, 
	"NOMBRE" VARCHAR2(50), 
	"NIVEL" NUMBER(38,0), 
	"PESOCLIENTESEXTERNOS" NUMBER(38,0), 
	"PESOAUTOEVALUACION" NUMBER(38,0)
   ) ;
