CREATE TABLE "PPPT"."HHEMPRESA" 
   (	"IDEMPRESA" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"EMPRESA" VARCHAR2(255) NOT NULL ENABLE, 
	"CONTACTO" VARCHAR2(255), 
	"EMAILCONTACTO" VARCHAR2(50), 
	"TEL" VARCHAR2(50), 
	"NOTAS" VARCHAR2(4000)
   ) ;
