CREATE TABLE "PPPT"."INT_INTERPRETACION" 
   (	"IDCOMPETENCIA" NUMBER(38,0) NOT NULL ENABLE, 
	"IDPRUEBA" NUMBER(38,0) NOT NULL ENABLE, 
	"RESULTADO" VARCHAR2(10) NOT NULL ENABLE, 
	"INTERPRETACION" VARCHAR2(4000)
   ) ;
