CREATE TABLE "PPPT"."INTERPRETACION" 
   (	"IDINTERPRETACION" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"IDPRUEBA" NUMBER(38,0), 
	"PATRON" VARCHAR2(10), 
	"NOMBRE" VARCHAR2(50), 
	"TIPO" NUMBER(38,0), 
	"INTERPRETACION" VARCHAR2(4000)
   ) ;
