CREATE TABLE "PPPT"."LABORAL" 
   (	"IDPERSONAL" NUMBER(38,0) NOT NULL ENABLE, 
	"EMPRESA" VARCHAR2(50), 
	"GIRO" VARCHAR2(50), 
	"DOMICILIO" VARCHAR2(50), 
	"TELEFONO" VARCHAR2(50), 
	"PUESTO" VARCHAR2(50), 
	"FUNCION" NUMBER(38,0), 
	"JEFEINMEDIATO" VARCHAR2(50), 
	"SUELDO" NUMBER, 
	"SUELDOF" NUMBER, 
	"DE" DATE NOT NULL ENABLE, 
	"A" DATE
   ) ;
