CREATE TABLE "PPPT"."NIVELPERFIL" 
   (	"IDNIVEL" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"NIVEL" VARCHAR2(255) NOT NULL ENABLE, 
	"MINIMO" NUMBER NOT NULL ENABLE, 
	"MAXIMO" NUMBER NOT NULL ENABLE
   ) ;
