CREATE TABLE "PPPT"."PERSONALINTERPRETACION" 
   (	"IDPERSONAL" NUMBER(38,0), 
	"IDPRUEBA" NUMBER(38,0), 
	"IDINTERPRETACION1" NUMBER(38,0), 
	"IDINTERPRETACION2" NUMBER(38,0), 
	"IDINTERPRETACION3" NUMBER(38,0), 
	"IDINTERPRETACION4" NUMBER(38,0), 
	"IDINTERPRETACION5" NUMBER(38,0), 
	"IDINTERPRETACION6" NUMBER(38,0)
   ) ;
