CREATE TABLE "PPPT"."PPPESCALAOFFICE" 
   (	"IDPRUEBA" NUMBER(38,0) NOT NULL ENABLE, 
	"TEMA" NUMBER(38,0) NOT NULL ENABLE, 
	"NIVEL" NUMBER(38,0) NOT NULL ENABLE, 
	"MINIMO" NUMBER(38,0) NOT NULL ENABLE, 
	"MAXIMO" NUMBER(38,0) NOT NULL ENABLE
   ) ;
