CREATE TABLE "PPPT"."PRUEBAS" 
   (	"IDPRUEBA" NUMBER(38,0) NOT NULL ENABLE, 
	"PRUEBA" VARCHAR2(50), 
	"BINCLUYE" NUMBER(1,0), 
	"BPONDERA" NUMBER(1,0), 
	"BPERFILA" NUMBER(1,0), 
	"BINTERPRETA" NUMBER(1,0), 
	"SECUENCIA" NUMBER(38,0), 
	"ACTIVA" NUMBER(1,0), 
	"DESCRIPCION" VARCHAR2(4000), 
	"BAUTOSERVICIO" NUMBER(1,0)
   ) ;
