CREATE TABLE "PPPT"."PUESTOCONDUCTA360" 
   (	"IDPUESTOCONDUCTA" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"IDPUESTO" NUMBER(38,0) NOT NULL ENABLE, 
	"IDCONDUCTA" NUMBER(38,0) NOT NULL ENABLE, 
	"PESO" NUMBER(38,0) NOT NULL ENABLE, 
	"IDPUESTOCOMPETENCIA" NUMBER(38,0) NOT NULL ENABLE
   ) ;
