CREATE TABLE "PPPT"."PUESTOS" 
   (	"IDPUESTO" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"PUESTO" VARCHAR2(150), 
	"NIVEL" NUMBER(38,0), 
	"IDEMPRESA" NUMBER(38,0) DEFAULT 0, 
	"BATERIA" NUMBER(1,0) DEFAULT 0, 
	"IDNIVEL" NUMBER(38,0), 
	"NOTAPERFIL" VARCHAR2(4000)
   ) ;
