CREATE TABLE "PPPT"."PUESTOSOPCIONES" 
   (	"IDPUESTO" NUMBER(38,0) NOT NULL ENABLE, 
	"IDPRUEBA" NUMBER(38,0) NOT NULL ENABLE, 
	"IDOPCION" NUMBER(38,0) NOT NULL ENABLE, 
	"VALOR" NUMBER(*,0)
   ) ;
