CREATE TABLE "PPPT"."PUESTOCOMPETENCIA360" 
   (	"IDPUESTO" NUMBER(38,0) NOT NULL ENABLE, 
	"IDCOMPETENCIA" NUMBER(38,0) NOT NULL ENABLE, 
	"PESO" NUMBER(38,0), 
	"IDPUESTOACTIVIDAD" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"IDPUESTOCOMPETENCIA" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE
   ) ;
