CREATE TABLE "PPPT"."PUESTOACTIVIDAD360" 
   (	"IDPUESTOACTIVIDAD" NUMBER(38,0) DEFAULT 0 NOT NULL ENABLE, 
	"IDPUESTO" NUMBER(38,0), 
	"NOMBRE" VARCHAR2(255), 
	"PESO" NUMBER(38,0), 
	"ACTIVIDAD" VARCHAR2(4000), 
	"IDPUESTOOBJETIVO" NUMBER(38,0)
   ) ;
