CREATE TABLE "PPPT"."RESOFFICE" 
   (	"IDPERSONAL" NUMBER(38,0) NOT NULL ENABLE, 
	"IDPRUEBA" NUMBER(38,0) NOT NULL ENABLE, 
	"FECHA" DATE NOT NULL ENABLE, 
	"CALIFICACIONES" VARCHAR2(100) NOT NULL ENABLE, 
	"TIEMPOS" VARCHAR2(100) NOT NULL ENABLE, 
	"STATUS" NUMBER(38,0) NOT NULL ENABLE
   ) ;
