CREATE TABLE "PPPT"."RESTTC" 
   (	"IDPERSONAL" NUMBER(38,0) NOT NULL ENABLE, 
	"IDPRUEBA" NUMBER(38,0) NOT NULL ENABLE, 
	"FECHA" DATE NOT NULL ENABLE, 
	"RESPUESTAS" VARCHAR2(150) NOT NULL ENABLE, 
	"RESULTADOS" VARCHAR2(150) NOT NULL ENABLE, 
	"STATUS" NUMBER(38,0) NOT NULL ENABLE, 
	"TIEMPOS" VARCHAR2(4000) NOT NULL ENABLE
   ) ;
