CREATE TABLE "PPPT"."TTCESTENES" 
   (	"IDPRUEBA" NUMBER(38,0) NOT NULL ENABLE, 
	"CALIFICACION" NUMBER(38,0) NOT NULL ENABLE, 
	"MINPUNTOS" NUMBER(38,0) NOT NULL ENABLE, 
	"MAXPUNTOS" NUMBER(38,0) NOT NULL ENABLE, 
	"IDCOMPETENCIA" NUMBER(38,0) NOT NULL ENABLE
   ) ;
