CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."CFDI2CONF_SEQ_TR" 
 BEFORE INSERT ON LABPROD.cfdi2Conf FOR EACH ROW
     WHEN (NEW.idConfig IS NULL) BEGIN
 SELECT LABPROD.cfdi2Conf_seq.NEXTVAL INTO :NEW.idConfig FROM DUAL;
END;


/
ALTER TRIGGER "LABPROD"."CFDI2CONF_SEQ_TR" ENABLE;
