CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."CFDI2DEDUCCIONESDET_SEQ_TR" 
 BEFORE INSERT ON LABPROD.cfdi2DeduccionesDetalle FOR EACH ROW
     WHEN (NEW.idDeduccion IS NULL) BEGIN
 SELECT LABPROD.cfdi2DeduccionesDetalle_seq.NEXTVAL INTO :NEW.idDeduccion FROM DUAL;
END;


/
ALTER TRIGGER "LABPROD"."CFDI2DEDUCCIONESDET_SEQ_TR" ENABLE;
