CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."CFDICOMPROBANTEPRO_TRG" 
      BEFORE INSERT ON LABPROD.cfdiComprobantePro
      FOR EACH ROW
    BEGIN
      SELECT cfdiComprobantePro_seq.nextval INTO :new.idComprobantePro FROM dual;
    END;


/
ALTER TRIGGER "LABPROD"."CFDICOMPROBANTEPRO_TRG" ENABLE;
