CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."CFDI2COMPROBANTEPRO_SEQ_TR" 
 BEFORE INSERT ON LABPROD.cfdi2ComprobantePro FOR EACH ROW
     WHEN (NEW.idComprobantePro IS NULL) BEGIN
 SELECT LABPROD.cfdi2ComprobantePro_seq.NEXTVAL INTO :NEW.idComprobantePro FROM DUAL;
END;


/
ALTER TRIGGER "LABPROD"."CFDI2COMPROBANTEPRO_SEQ_TR" ENABLE;
