CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."CFDICOMPROBANTEEMP_TRG" 
      BEFORE INSERT ON LABPROD.cfdiComprobanteEmp
      FOR EACH ROW
    BEGIN
      SELECT cfdiComprobanteEmp_seq.nextval INTO :new.idComprobanteEmp FROM dual;
    END;


/
ALTER TRIGGER "LABPROD"."CFDICOMPROBANTEEMP_TRG" ENABLE;
