CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."FUARCHIVO_SEQ_TR" BEFORE
  INSERT ON LABPROD.FUARCHIVO FOR EACH ROW    WHEN (NEW.IDARCHIVO IS NULL) BEGIN
  SELECT LABPROD.FUARCHIVO_SEQ.NEXTVAL
  INTO :NEW.IDARCHIVO
  FROM DUAL;
END;


/
ALTER TRIGGER "LABPROD"."FUARCHIVO_SEQ_TR" ENABLE;
