CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."ISNCONF_TRG" 
      BEFORE INSERT ON LABPROD.ISNCONF            
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDCONFIG IS NULL THEN
      SELECT LABPROD.ISNCONF_SEQ.nextval INTO :new.IDCONFIG FROM dual;
    END IF;
  END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "LABPROD"."ISNCONF_TRG" ENABLE;
