CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."NMPROCHE_TRG" 
      BEFORE INSERT ON LABPROD.NMPROCHE
      FOR EACH ROW
    BEGIN
        SELECT LABPROD.NMPROCHE_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
    END;


/
ALTER TRIGGER "LABPROD"."NMPROCHE_TRG" ENABLE;
