CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."T_COM_SIPS_ORAC_EMPL" 
   BEFORE INSERT
     ON LABPROD.com_sips_orac_empl
     REFERENCING NEW AS NEW
     FOR EACH ROW
   BEGIN
     SELECT s_com_sips_orac_empl.nextval INTO :NEW.ora_ctvo FROM dual;
   END;




/
ALTER TRIGGER "LABPROD"."T_COM_SIPS_ORAC_EMPL" ENABLE;
