CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."TRIGGER_AP_SIPROS" 
   BEFORE INSERT
     ON LABPROD.AP_SIPROS
     REFERENCING NEW AS NEW
     FOR EACH ROW
   BEGIN
     SELECT emp_keypro,emp_status INTO :NEW.SOI_KEYPRO,:NEW.SOI_STATUS FROM nmcoempl WHERE emp_keyemp = :NEW.SOI_KEYEMP;
   END;




/
ALTER TRIGGER "LABPROD"."TRIGGER_AP_SIPROS" ENABLE;
