CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."TRIGGER_TVCAPDES_I" 
before insert on LABPROD.TVCAPDES_I
for each row
begin
select SEQU_CAPDES_I.nextval into :new.ORDERID2 from dual;
end;




/
ALTER TRIGGER "LABPROD"."TRIGGER_TVCAPDES_I" ENABLE;
