CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."TVGASDET_TRG" 
  BEFORE INSERT ON LABPROD.tvgasdet
  FOR EACH ROW
  BEGIN
      SELECT NVL(:new.det_keydet, tvgasdet_seq.nextval) INTO :new.det_keydet FROM dual;
  END;


/
ALTER TRIGGER "LABPROD"."TVGASDET_TRG" ENABLE;
