CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."TVGASCAR_TRG" 
  BEFORE INSERT ON LABPROD.tvgascar
  FOR EACH ROW
  BEGIN
      SELECT NVL(:new.car_keycar, tvgascar_seq.nextval) INTO :new.car_keycar FROM dual;
  END;


/
ALTER TRIGGER "LABPROD"."TVGASCAR_TRG" ENABLE;
