CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."TVLOTIEE_TRG" BEFORE
  INSERT ON LABPROD.TVLOTIEE FOR EACH ROW BEGIN
  SELECT TVLOTIEE_SEQ.NEXTVAL INTO :NEW.TIE_KEYTIE FROM DUAL;
END;


/
ALTER TRIGGER "LABPROD"."TVLOTIEE_TRG" ENABLE;
