CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."TVLOINCT_TRG" BEFORE
  INSERT ON LABPROD.TVLOINCT FOR EACH ROW BEGIN <<COLUMN_SEQUENCES>> BEGIN
  SELECT TVLOINCT_SEQ.NEXTVAL INTO :NEW.INC_KEYINC FROM DUAL;
END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "LABPROD"."TVLOINCT_TRG" ENABLE;
