CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."TVPBVACC_TRG" BEFORE
  INSERT ON LABPROD.TVPBVACC FOR EACH ROW
BEGIN
  SELECT LABPROD.TVPBVACC_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;


/
ALTER TRIGGER "LABPROD"."TVPBVACC_TRG" ENABLE;
