CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."WEBITACC_TRG" 
  BEFORE INSERT ON LABPROD.webitacc
  FOR EACH ROW
  BEGIN
      SELECT NVL(:new.wcc_idbacc, LABPROD.webitacc_seq.nextval) INTO :new.wcc_idbacc FROM dual;
  END;



/
ALTER TRIGGER "LABPROD"."WEBITACC_TRG" ENABLE;
