CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."WEHISPASS_TRG" 
  BEFORE INSERT ON LABPROD.wehispass
  FOR EACH ROW
  BEGIN
      SELECT NVL(:new.weh_id, LABPROD.wehispass_seq.nextval) INTO :new.weh_id FROM dual;
  END;


/
ALTER TRIGGER "LABPROD"."WEHISPASS_TRG" ENABLE;
