CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."WESEND_TRG" 
  BEFORE INSERT ON LABPROD.WESEND
  FOR EACH ROW
BEGIN
      SELECT NVL(:new.Id, LABPROD.WESEND_SEQ.nextval) INTO :new.Id FROM dual;
  END;

/
ALTER TRIGGER "LABPROD"."WESEND_TRG" ENABLE;
