CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."XXHR_TRANSFERENCIAS_LAB_TRG" 
      BEFORE INSERT ON LABPROD.XXHR_TRANSFERENCIAS_LAB
      FOR EACH ROW
    BEGIN
      IF :new.ID_LABORA IS NULL THEN
        SELECT "LABPROD".XXHR_TRANSFERENCIAS_LAB_SEQ.nextval INTO :new.ID_LABORA FROM dual;
      END IF;
    END;


/
ALTER TRIGGER "LABPROD"."XXHR_TRANSFERENCIAS_LAB_TRG" ENABLE;
