CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."XXHR_ACT_PLAZAS_LAB_TRG" 
      BEFORE INSERT ON LABPROD.XXHR_ACT_PLAZAS_LAB
      FOR EACH ROW
    BEGIN
      SELECT "LABPROD".XXHR_ACT_PLAZAS_LAB_seq.nextval INTO :new.ID_LABORA FROM dual;
    END;


/
ALTER TRIGGER "LABPROD"."XXHR_ACT_PLAZAS_LAB_TRG" ENABLE;
