CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."XXHR_CREA_PLAZAS_LAB_TRG" 
    BEFORE INSERT ON LABPROD.XXHR_CREA_PLAZAS_LAB
    FOR EACH ROW
    BEGIN
     <<COLUMN_SEQUENCES>>
    BEGIN
      IF INSERTING AND :NEW.LABORA_ID IS NULL THEN
        SELECT "LABPROD".XXHR_CREA_PLAZAS_LAB_SEQ.NEXTVAL INTO :NEW.LABORA_ID FROM SYS.DUAL;
      END IF;
    END COLUMN_SEQUENCES;
  END;


/
ALTER TRIGGER "LABPROD"."XXHR_CREA_PLAZAS_LAB_TRG" ENABLE;
