CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABPROD"."XXHR_ACT_ASIG_EMPLEADOS_LAB_TR" 
      BEFORE INSERT ON LABPROD.XXHR_ACT_ASIG_EMPLEADOS_LAB
      FOR EACH ROW
    BEGIN
      IF :new.ID_LABORA IS NULL THEN
        SELECT "LABPROD".XXHR_ACT_ASIG_EMPLEADOS_LAB_SE.nextval INTO :new.ID_LABORA FROM dual;
      END IF;
    END;


/
ALTER TRIGGER "LABPROD"."XXHR_ACT_ASIG_EMPLEADOS_LAB_TR" ENABLE;
