CREATE OR REPLACE NONEDITIONABLE PROCEDURE "LABPROD"."SP_TRIG_EMPL_I" (
    new_keyemp in integer,
    new_keydep in varchar2,
    new_keypue in varchar2,
    new_keycen in varchar2,
    new_keycat in varchar2,
    new_nomemp in varchar2,
    new_nomcor in varchar2,
    new_domemp in varchar2,
    new_colemp in varchar2,
    new_cidemp in varchar2,
    new_pobemp in varchar2,
    new_munemp in varchar2,
    new_entemp in varchar2,
    new_codemp in varchar2,
    new_telemp in varchar2,
    new_regrfc in varchar2,
    new_recurp in varchar2,
    new_regims in varchar2,
    new_reginf in varchar2,
    new_cvesex in varchar2,
    new_keyims in varchar2,
    new_cvezon in integer,
    new_keypro in integer,
    new_cvetur in integer,
    new_tipemp in varchar2,
    new_tipsal in varchar2,
    new_status in integer,
    new_salhor in decimal,
    new_saldia in decimal,
    new_salmes in decimal,
    new_salint in decimal,
    new_salivc in decimal,
    new_salinf in decimal,
    new_intsin in decimal,
    new_infsin in decimal,
    new_varims in decimal,
    new_varinf in decimal,
    new_anthor in decimal,
    new_antdia in decimal,
    new_antmes in decimal,
    new_antint in decimal,
    new_antivc in decimal,
    new_antinf in decimal,
    new_antits in decimal,
    new_antifs in decimal,
    new_refcon in varchar2,
    new_cveban in varchar2,
    new_ctaban in varchar2,
    new_forpag in varchar2,
    new_diades in integer,
    new_numliq in varchar2,
    new_keyloc in varchar2,
    new_fecing in date,
    new_fecrei in date,
    new_fecven in date,
    new_fecpla in date,
    new_fecaum in date,
    new_peraum in varchar2,
    new_fecbaj in date,
    new_cvebaj in varchar2,
    new_jorlab in varchar2,
    new_unijor in decimal,
    new_pering in varchar2,
    new_perbaj in varchar2,
    new_perdep in varchar2,
    new_perpue in varchar2,
    new_percat in varchar2,
    new_perpro in varchar2,
    new_fecaux in date,
    new_ca1aux in varchar2,
    new_ca2aux in varchar2,
    new_ca3aux in varchar2,
    new_ca4aux in varchar2,
    new_pctbec in decimal,
    new_fecmod in date,
    new_hormod in varchar2,
    new_fecalt in date,
    new_bajfec in date,
    new_fecsal in date,
    new_perpag in varchar2,
    new_inifec in date,
    new_finfec in date,
    new_cobert in varchar2)
IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
BEGIN
 insert into nmcoempl_sdw (cmd,new_emp_keyemp,new_emp_keydep,new_emp_keypue,new_emp_keycen,new_emp_nomemp,new_emp_regrfc,new_emp_recurp,
 new_emp_regims,new_emp_keypro,new_emp_status,new_emp_keyloc, new_emp_fecing,new_emp_fecbaj,new_emp_fecaux,new_emp_ca2aux,orderid1,orderid2)
 values ('insert' ,new_keyemp ,new_keydep ,new_keypue ,new_keycen ,new_nomemp ,new_regrfc ,new_recurp
 ,new_regims ,new_keypro ,new_status ,new_keyloc ,new_fecing ,new_fecbaj ,new_fecaux ,new_ca2aux,SYSDATE ,0 );
-- Igneos.I (se agrega proceso)
sp_sips_orac_empl2(new_keyemp,new_nomemp,new_cvesex,new_regrfc,new_recurp,new_regims,new_fecing,new_tipemp,
'','','','','','','','','','','','IN', new_keypro);
END;
/
