CREATE OR REPLACE NONEDITIONABLE PROCEDURE "LABPROD"."SP_VAC_RECHAZARSOL" 
(
  KEYSOL IN NUMBER,
  KEYUSU IN NUMBER,
  RESULTADO OUT NUMBER
) AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
NUMDIA DECIMAL(10,2);
NUMANI NUMBER(10,0);
KEYEMP NUMBER(10,0);
KEYCON VARCHAR2(3);
FECPER DATE;
BEGIN
  BEGIN
    SELECT SOL_NUMDIA,SOL_NUMANI,SOL_FECPER,SOL_KEYEMP,SOL_KEYCON INTO NUMDIA,NUMANI,FECPER,KEYEMP,KEYCON
    FROM LABPROD.MOLOSOLI
    WHERE SOL_KEYSOL = KEYSOL;
  EXCEPTION
     WHEN NO_DATA_FOUND THEN
       RESULTADO := 0;
       RETURN;
  END;
  BEGIN
    UPDATE LABPROD.MOLOSOLI SET SOL_STATUS = 3,sol_fecmod = SYSDATE   ,
       sol_hormod = TO_CHAR (SYSDATE,'HH24:MI:SS'),
       sol_keyusu = KEYUSU
    WHERE sol_keysol = KEYSOL;
    UPDATE LABPROD.MOLODIAD SET DIA_DIASAL = DIA_DIASAL + NUMDIA
    WHERE DIA_KEYEMP = KEYEMP
    AND DIA_KEYCON = KEYCON
    AND DIA_NUMANI = NUMANI
    AND DIA_FECINI = FECPER;
    COMMIT;
    RESULTADO := 0;
  EXCEPTION
    WHEN OTHERS THEN
      RESULTADO := 1;
      RETURN;
  END;
END SP_VAC_RECHAZARSOL;
/
