CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "LABPROD"."BLOQUEOS_EMPLEADOS" ("KEYEMP", "NOMBRE", "KEYDEP", "DEPARTAMENTO", "KEYPUE", "PUESTO", "KEYPRO", "PROCESO", "KEYLOC", "UBICACION", "REGIMS", "KEYPLZ", "KEYJEFE", "KEYCIA", "COMPANIA") AS 
  SELECT EMP_KEYEMP KEYEMP,
          EMP_NOMEMP NOMBRE,
          EMP_KEYDEP KEYDEP,
          DEP_DESDEP DEPARTAMENTO,
          EMP_KEYPUE KEYPUE,
          PUE_DESPUE PUESTO,
          EMP_KEYPRO KEYPRO,
          PRO_DESPRO PROCESO,
          EMP_KEYLOC KEYLOC,
          LOC_DESLOC UBICACION,
          EMP_REGIMS REGIMS,
          PLZ_KEYPLZ KEYPLZ,
          PLZ_CVEREM KEYJEFE,
          PRO_KEYCIA KEYCIA,
          CIA_DESCIA COMPANIA
     FROM LABPROD.NMCOEMPL
          INNER JOIN LABPROD.NMCODEPS ON EMP_KEYDEP = DEP_KEYDEP
          INNER JOIN LABPROD.NMCOPUES ON EMP_KEYPUE = PUE_KEYPUE
          INNER JOIN LABPROD.NMLOPROC ON EMP_KEYPRO = PRO_KEYPRO
          INNER JOIN LABPROD.NMLOLOCP ON EMP_KEYLOC = LOC_KEYLOC
          INNER JOIN LABPROD.NMLOCIAS ON PRO_KEYCIA = CIA_KEYCIA
          LEFT JOIN LABPROD.EOCOPLZA ON EMP_KEYEMP = PLZ_KEYEMP
    WHERE EMP_STATUS = 1;
