CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "LABPROD"."BLOQUEOS_MOTIVOSBAJA" ("MOTIVOBAJA", "DESCRIPCION") AS 
  SELECT PAM_CVESEC MOTIVOBAJA,
         PAM_NOMPAR DESCRIPCION
    FROM LABPROD.GLCOPAMS
    WHERE PAM_KEYPAR = 'BA';
