CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "LABPROD"."NOMINA_VIEW" ("EMPRESATELEVISA", "DESCEMPRESATELEVISA", "CVEUBICACION", "DESCUBICACION", "TIPONOMINA", "CVEPROCESONOMINA", "DESCPROCESONOMINA", "NUMEROEMPLEADO", "NOMBRECOMPLETO", "RFC", "CURP", "TELEFONO", "CODIGOPOSTAL", "DOMICILIO", "COLONIA", "CIUDAD", "MUNICIPIO", "DESCMUNICIPIO", "ENTIDAD", "DESCENTIDAD", "CAPACIDADENDEUDAMIENTO", "PER_KEYPER", "PER_FECINI", "PER_FECFIN", "PER_FECPAG") AS 
  SELECT
    PRO_KEYCIA EMPRESATELEVISA,
    CIA_DESCIA DESCEMPRESATELEVISA,
    EMP_KEYLOC CVEUBICACION,
    LOC_DESLOC DESCUBICACION,
    PRO_DIAPER TIPONOMINA,
    PRO_KEYPRO CVEPROCESONOMINA,
    PRO_DESPRO DESCPROCESONOMINA,
    EMP_KEYEMP NUMEROEMPLEADO,
    EMP_NOMEMP NOMBRECOMPLETO,
    EMP_REGRFC RFC,
    EMP_RECURP CURP,
    EMP_TELEMP TELEFONO,
    EMP_CODEMP CODIGOPOSTAL,
    EMP_DOMEMP DOMICILIO,
    EMP_COLEMP COLONIA,
    EMP_CIDEMP CIUDAD,
    EMP_MUNEMP MUNICIPIO,
    A.PAM_NOMPAR DESCMUNICIPIO,
    EMP_ENTEMP ENTIDAD,
    B.PAM_NOMPAR DESCENTIDAD,
    PDE_CAPNEW CAPACIDADENDEUDAMIENTO,
    PER_KEYPER,
    PER_FECINI,
    PER_FECFIN,
    PER_FECPAG
  FROM
    NMCOEMPL,
    NMLOPROC,
    NMLOCIAS,
    NMLOLOCP,
    GLCOPAMS A,
    TVCAPDES,
    GLCOPAMS B,
    NMLOPERI
  WHERE
    EMP_KEYPRO     = PRO_KEYPRO
  AND PRO_KEYCIA   = CIA_KEYCIA
  AND EMP_KEYLOC   = LOC_KEYLOC
  AND EMP_KEYEMP   = PDE_KEYEMP
  AND A.PAM_CVESEC = EMP_MUNEMP
  AND A.PAM_KEYPAR = 'MU'
  AND B.PAM_CVESEC = EMP_ENTEMP
  AND B.PAM_KEYPAR = 'EF'
  AND PER_KEYPRO   = EMP_KEYPRO
  AND EMP_STATUS   = 1
  AND PER_FECPAG BETWEEN SYSDATE-7 AND SYSDATE+7
  AND PER_KEYNOM = 1;
