CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "LABPROD"."PB_VACACIONES" ("FECHA_CAPTURA", "KEYEMP", "NOMBRE", "FECHA_INICIO", "FECHA_FINAL", "DIAS_VACACIONES") AS 
  SELECT SOL_FECMOD AS FECHA_CAPTURA,
          SOL_KEYEMP AS KEYEMP,
          EMP_NOMEMP AS NOMBRE,
          SOL_FECINI AS FECHA_INICIO,
          SOL_FECFIN AS FECHA_FINAL,
          SOL_NUMDIA AS DIAS_VACACIONES
     FROM LABPROD.MOLOSOLI
          INNER JOIN LABPROD.NMCOEMPL
             ON     SOL_KEYEMP = EMP_KEYEMP
                AND SOL_STATUS = 2
                AND SOL_NUMDIA >= 20
                AND EMP_KEYPRO <> 6;
