CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "LABPROD"."R_PLARET" ("RET_KEYEMP", "RET_NOMEMP", "RET_KEYDEP", "RET_DESDEP", "RET_KEYPUE", "RET_DESPUE", "RET_KEYCEN", "RET_DESCEN", "RET_KEYCIA", "RET_DESCIA", "RET_KEYPRO", "RET_DESPRO", "RET_TIPEMP", "RET_STATUS", "RET_KEYLOC", "RET_DESLOC", "RET_FECAUX", "RET_FECBAJ", "RET_CVEBAJ", "RET_NOMPAR", "RET_KEYPAR", "RET_VALPAR") AS 
  SELECT
        EMP_KEYEMP RET_KEYEMP,
        EMP_NOMEMP RET_NOMEMP,
        EMP_KEYDEP RET_KEYDEP,
        DEP_DESDEP RET_DESDEP,
        EMP_KEYPUE RET_KEYPUE,
        PUE_DESPUE RET_DESPUE,
        DEP_KEYCEN RET_KEYCEN,
        CEN_DESCEN RET_DESCEN,
        CIA_KEYCIA RET_KEYCIA,
        CIA_DESCIA RET_DESCIA,
        EMP_KEYPRO RET_KEYPRO,
        PRO_DESPRO RET_DESPRO,
        EMP_TIPEMP RET_TIPEMP,
        EMP_STATUS RET_STATUS,
        EMP_KEYLOC RET_KEYLOC,
        LOC_DESLOC RET_DESLOC,
        EMP_FECAUX RET_FECAUX,
        EMP_FECBAJ RET_FECBAJ,
        EMP_CVEBAJ RET_CVEBAJ,
        PAM_NOMPAR RET_NOMPAR,
        DAT_KEYPAR RET_KEYPAR,
        DAT_VALPAR RET_VALPAR
FROM LABPROD.NMCOEMPL
    INNER JOIN LABPROD.NMLODATA ON DAT_KEYEMP=EMP_KEYEMP AND DAT_KEYPAR='54' AND NOT(DAT_VALPAR IS NULL)
    LEFT JOIN LABPROD.GLCOPAMS ON PAM_KEYPAR='BA' AND PAM_CVESEC=EMP_CVEBAJ
    LEFT JOIN LABPROD.NMCODEPS ON DEP_KEYDEP=EMP_KEYDEP
    LEFT JOIN LABPROD.NMCOPUES ON PUE_KEYPUE=EMP_KEYPUE
    LEFT JOIN LABPROD.NMLOCENC ON CEN_KEYCEN=EMP_KEYCEN
    LEFT JOIN LABPROD.NMLOPROC ON PRO_KEYPRO=EMP_KEYPRO
    LEFT JOIN LABPROD.NMLOCIAS ON CIA_KEYCIA=PRO_KEYCIA
    LEFT JOIN LABPROD.NMLOLOCP ON LOC_KEYLOC=EMP_KEYLOC
WHERE 1=1
AND EXISTS (SELECT PAM_CVESEC FROM LABPROD.GLCOPAMS WHERE PAM_KEYPAR='CTCO' AND PAM_CVESEC=EMP_KEYPRO);
