CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "LABPROD"."SIASA_LABORA_V" ("CVE_CONCEPTO", "IMPORTE", "UNIDAD", "INC_KEYEMP", "INC_KEYPUE", "INC_KEYCCO", "CENTRO_COSTOS_APLICADO", "SEMANA", "CVE_PUESTO", "FECHA_INGRESO", "FECHA_BAJA", "PROCESO", "PERIODO", "CCT_CD", "PERI_INI", "PERI_FIN", "PERI_MES", "FECHA_PAGO", "PER_KEYNOM", "PRO_DIAPER", "PRO_DESPRO", "CONCEPTO", "PLAZA", "CVE_EMPRESA", "NOMBRE_EMPRESA", "NO_EMPLEADO", "NOMBRE", "CENTRO_COSTOS_ORIGEN", "SUBCUENTA", "DESC_PUESTO", "DESC_CENTRO_COSTOS_ORIGEN", "PER_KEYPER") AS 
  SELECT
    INC_KEYCON CVE_CONCEPTO,
    INC_COSTO IMPORTE,
    INC_CANTID UNIDAD,
    INC_KEYEMP,
    INC_KEYPUE,
    INC_KEYCCO,
    INC_KEYCEN CENTRO_COSTOS_APLICADO,
    INC_SEMANA SEMANA,
    HEM_KEYPUE CVE_PUESTO,
    HEM_FECAUX FECHA_INGRESO,
    HEM_FECBAJ FECHA_BAJA,
    HEM_KEYPRO PROCESO,
    PER_KEYPER PERIODO,
    HEM_KEYCEN CCT_CD,
    PER_FECINI PERI_INI,
    PER_FECFIN PERI_FIN,
    PER_NUMMES PERI_MES,
    PER_FECPAG FECHA_PAGO,
    PER_KEYNOM,
    PRO_DIAPER,
    PRO_DESPRO,
    CON_DESCON CONCEPTO,
    HAL_KEYPLZ PLAZA,
    CIA_CA3AUX CVE_EMPRESA,
    CIA_DESCIA NOMBRE_EMPRESA,
    EMP_KEYEMP NO_EMPLEADO,
    EMP_NOMEMP NOMBRE,
    SUBSTR (DEP_REFCON, 15, 8) CENTRO_COSTOS_ORIGEN,
    '000000' SUBCUENTA,
    PUE_DESPUE DESC_PUESTO,
    ORIGEN.CEN_DESCEN DESC_CENTRO_COSTOS_ORIGEN,
    SUBSTR(NMLOPERI.PER_KEYPER,1,4) AS PER_KEYPER
FROM
    LABPROD.NMPASINC NMHISINC,
    LABPROD.NMLOPERI NMLOPERI,
    LABPROD.NMLOPROC NMLOPROC,
    LABPROD.NMLOCONC NMLOCONC,
    LABPROD.NMLOHEMP,
    LABPROD.NMLOCIAS,
    LABPROD.NMCOEMPL,
    LABPROD.NMCODEPS,
    (SELECT * FROM LABPROD.TVLOHALT WHERE HAL_KEYPLZ IS NOT NULL),
    LABPROD.NMLOCEPRO ORIGEN,
    LABPROD.NMCOPUES
WHERE
    (1 = 1)
    AND (NMHISINC.inc_keycon IN ('002','003','004','005','008','010','011','021','035','052','053','054','060','062','074','082','086','091','095','301','303','304','384','386','387','C34','C43','C69','C84','D77','D78'))
    AND (NMHISINC.inc_keypro IN (3, 8, 77, 81, 5, 60))
    AND (NMHISINC.inc_keypro = NMLOPERI.per_keypro)
    AND (NMLOPERI.per_keyper = NMHISINC.inc_keyper)
    AND (NMHISINC.inc_keypro = NMLOPROC.pro_keypro)
    AND (NMLOCONC.con_keycon = NMHISINC.inc_keycon)
    AND INC_KEYEMP = HEM_KEYEMP(+)
    AND INC_KEYPRO = HEM_KEYPRO(+)
    AND INC_KEYPER = HEM_KEYPER(+)
    AND INC_KEYPRO = HAL_KEYPRO(+)
    AND INC_KEYPER = HAL_KEYPER(+)
    AND INC_KEYEMP = HAL_KEYEMP(+)
    AND PRO_KEYCIA = CIA_KEYCIA(+)
    AND HEM_KEYEMP = EMP_KEYEMP(+)
    AND HEM_KEYDEP = DEP_KEYDEP(+)
    AND HEM_KEYPUE = PUE_KEYPUE(+)
    AND SUBSTR (DEP_REFCON, 15, 8) = ORIGEN.CEN_KEYCEN(+)
;
