CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "LABPROD"."SIASA_INT_V" ("NUMERO_ASOCIADO", "NOMBRE", "ANT_REMANENTE_DIS", "ESTATUS", "FECHA_PAGO", "FECHA_PROCESO", "AREA", "SUBCUENTA", "CONCEPTO", "HEM_KEYPRO", "PRO_DESPRO", "CVE_ACTIVIDAD", "ACTIVIDAD", "CENTRO_COSTOS", "DESC_CENTRO_COSTOS", "CVE_EMPRESA", "NOMBRE_EMPRESA", "FECHA_INGRESO", "FECHA_BAJA", "PLAZA", "PERIODO", "PER_FECINI", "PER_FECFIN", "PER_NUMMES", "PER_KEYNOM", "HIS_CA1AUX", "HIS_KEYPUE", "HIS_KEYCON", "PRO_DIAPER", "HIS_CANTID", "HIS_IMPORT") AS 
  SELECT
    HEM_KEYEMP NUMERO_ASOCIADO,
    EMP_NOMEMP NOMBRE,
    HEM_SALMES ANT_REMANENTE_DIS,
    'PAGADO' ESTATUS,
    PER_FECPAG FECHA_PAGO,
    PER_FECACT FECHA_PROCESO,
    LOC_DESLOC AREA,
    '000000' SUBCUENTA,
    CON_DESCON CONCEPTO,
    HEM_KEYPRO,
    PRO_DESPRO,
    HEM_KEYPUE CVE_ACTIVIDAD,
    PUE_DESPUE ACTIVIDAD,
    SUBSTR (DEP_REFCON, 15, 8) CENTRO_COSTOS,
    CEN_DESCEN DESC_CENTRO_COSTOS,
    CIA_CA3AUX CVE_EMPRESA,
    CIA_DESCIA NOMBRE_EMPRESA,
    HEM_FECING FECHA_INGRESO,
    HEM_FECBAJ FECHA_BAJA,
    HAL_KEYPLZ PLAZA,
    PER_KEYPER PERIODO,
    PER_FECINI,
    PER_FECFIN,
    PER_NUMMES,
    PER_KEYNOM,
    HIS_CA1AUX,
    HIS_KEYPUE,
    HIS_KEYCON,
    PRO_DIAPER,
    HIS_CANTID,
    HIS_IMPORT
FROM
    (SELECT
        *
     FROM
        LABPROD.NMLOPERI   NMLOPERI,
        LABPROD.NMLOPROC   NMLOPROC,
        LABPROD.NMLOCONC   NMLOCONC,
        LABPROD.NMLOHISM   NMLOHISM,
        LABPROD.NMLOCIAS   NMLOCIAS
    WHERE
        (1=1) AND
        (NMLOHISM.his_keypro in (3,8,77,10,12,19,5,66,81,60)) AND
        (NMLOHISM.his_keycon in ('250','260','001','F26')) AND
        (NMLOPERI.per_keynom = 1) AND
        (NMLOHISM.his_keyper=NMLOPERI.per_keyper) AND
        (NMLOHISM.his_keypro=NMLOPERI.per_keypro) AND
        (NMLOHISM.his_keypro=NMLOPROC.pro_keypro) AND
        (NMLOHISM.his_keycon=NMLOCONC.con_keycon) AND
        (CIA_KEYCIA = PRO_KEYCIA)),
    LABPROD.NMLOHEMP,
    LABPROD.NMCOEMPL,
    LABPROD.NMLOLOCP,
    LABPROD.NMCOPUES,
    LABPROD.NMCODEPS,
    LABPROD.NMLOCEPRO,
    LABPROD.TVLOHALT
WHERE
    (1=1) AND
    PER_KEYPRO = HEM_KEYPRO(+) AND
    PER_KEYPER = HEM_KEYPER(+) AND
    HIS_KEYPRO = HEM_KEYPRO(+) AND
    HIS_KEYPER = HEM_KEYPER(+) AND
    HIS_KEYEMP = HEM_KEYEMP(+) AND
    HEM_KEYEMP = EMP_KEYEMP(+) AND
    HEM_KEYLOC = LOC_KEYLOC(+) AND
    HEM_KEYPUE = PUE_KEYPUE(+) AND
    HEM_KEYDEP = DEP_KEYDEP(+) AND
    CEN_KEYCEN(+) = SUBSTR (DEP_REFCON, 15, 8) AND
    HAL_KEYPRO(+) = HEM_KEYPRO AND
    HAL_KEYPER(+) = HEM_KEYPER AND
    HAL_KEYEMP(+) = HEM_KEYEMP;
