CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "LABPROD"."SIHO_NMCOEMPL" ("EMP_KEYEMP", "EMP_NOMEMP", "EMP_KEYDEP", "DEP_DESDEP", "EMP_KEYPUE", "PUE_DESPUE", "EMP_KEYCEN", "CEN_DESCEN", "EMP_STATUS") AS 
  SELECT EMP_KEYEMP,
       EMP_NOMEMP,
       EMP_KEYDEP,
       DEP_DESDEP,
       EMP_KEYPUE,
       PUE_DESPUE,
       EMP_KEYCEN,
       CEN_DESCEN,
       EMP_STATUS
FROM LABPROD.NMCOEMPL
LEFT JOIN LABPROD.NMCODEPS ON DEP_KEYDEP=EMP_KEYDEP
LEFT JOIN LABPROD.NMCOPUES ON PUE_KEYPUE=EMP_KEYPUE
LEFT JOIN LABPROD.NMLOCENC ON CEN_KEYCEN=EMP_KEYCEN
WHERE 1=1
AND   EMP_KEYPRO IN (SELECT PAM_CVESEC FROM LABPROD.GLCOPAMS WHERE PAM_KEYPAR='CTCO');
