CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "LABPROD"."SVWNOM_LOCALIDADES_V" ("LOC_KEYLOC", "LOC_DESLOC", "LOC_DOMLOC", "LOC_COLLOC", "LOC_CIULOC", "LOC_ESTLOC", "LOC_CODPOS", "LOC_CVEZON") AS 
  SELECT  LOC_KEYLOC
       ,LOC_DESLOC
       ,LOC_DOMLOC
       ,LOC_COLLOC
       ,  (SELECT PAM_NOMPAR
            FROM LABPROD.GLCOPAMS
            WHERE PAM_KEYPAR ='MU'
             AND PAM_CVESEC=LOC_CIULOC) LOC_CIULOC
       ,(SELECT PAM_NOMPAR
           FROM LABPROD.GLCOPAMS
          WHERE PAM_KEYPAR ='EF'
           AND PAM_CVESEC=LOC_ESTLOC) LOC_ESTLOC
       ,LOC_CODPOS
       ,LOC_CVEZON
  FROM LABPROD.NMLOLOCP CP
      ,LABPROD.NMCOEMPL EMP
   WHERE CP.LOC_KEYLOC =EMP.EMP_KEYLOC
   AND EMP.EMP_STATUS =1
   GROUP BY CP.LOC_KEYLOC
       ,CP.LOC_DESLOC
       ,CP.LOC_DOMLOC
       ,CP.LOC_DOMLOC
       ,CP.LOC_COLLOC
       ,CP.LOC_COLLOC
       ,CP.LOC_CIULOC
       ,CP.LOC_ESTLOC
       ,CP.LOC_CODPOS
       ,CP.LOC_CVEZON;
