CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "LABPROD"."SVWNOM_DEPARTAMENTOS_V" ("DEP_KEYDEP", "DEP_DESDEP") AS 
  SELECT DEP_KEYDEP
      ,DEP_DESDEP
FROM LABPROD.NMCODEPS
WHERE LENGTH (DEP_KEYDEP)=10;
