CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "LABPROD"."TVVICANR" ("CAN_KEYEMP", "EMP_NOMEMP", "CAN_PERCAN", "PRO_KEYCIA", "CIA_DESCIA", "CAN_KEYPRO", "PRO_DESPRO", "CAN_PERORI", "SERIE", "FOLIO", "PER_ANIOA1", "PER_NUMMES") AS 
  SELECT CAN_KEYEMP,emp_nomemp,can_percan,PRO_KEYCIA,CIA_DESCIA,CAN_KEYPRO,PRO_DESPRO,CAN_PERORI,EMP.SERIE,EMP.FOLIO,PER_ANIOA1,PER_NUMMES
from labprod.nmlocanr
INNER JOIN labprod.nmloperi ON can_keypro = per_keypro AND can_percan = per_keyper
INNER JOIN LABPROD.Cfdi2comprobantepro PRO on can_keypro = PRO.com_keypro AND can_perori = PRO.com_keyper
INNER JOIN LABPROD.CFDI2COMPROBANTEEMP EMP ON PRO.IDCOMPROBANTEPRO = EMP.IDCOMPROBANTEPRO AND EMP.COM_KEYEMP = CAN_KEYEMP
LEFT JOIN LABPROD.NMLOPROC ON can_keypro = pro_keypro
LEFT JOIN LABPROD.NMLOCIAS ON PRO_KEYCIA = CIA_KEYCIA
LEFT JOIN LABPROD.NMCOEMPL ON can_keyemp = emp_keyemp;
