CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "LABPROD"."XXHR_TRASP_EMP_CANDIDATOS_V" ("NO_CANDIDATO", "NO_EMPLEADO", "SEXO", "CURP", "RFC", "IMSS", "FECHA_CONTRATACION", "FECHA_NACIMIENTO", "CIUDAD_NACIMIENTO", "PAIS_DE_NACIMIENTO", "NACIONALIDAD", "ESTADO_CIVIL", "CORREO_ELECTRONICO", "CLAVE_INFONAVIT", "PERMISO_MIGRATORIO", "FECHA_DE_ANTIGUEDAD", "FECHA_DE_VENC_DEL_CONTRATO", "FECHA_PLANTA", "FECHA_DE_REINGRESO", "SUBMOVIMIENTO", "DIAS_DE_VENC_DEL_CONTRATO", "FECHA_VENC_PERMISO_MIGRATORIO", "FORMA_DE_PAGO", "CUENTA_BANCARIA", "SUCURSAL", "DESCUENTO_INFONAVIT", "USUARIO_MAM", "ESTATUS_INTERFACE", "FECHA_INTERFACE") AS 
  SELECT
CAND.IDCANDIDATO NO_CANDIDATO,
TRASP.NO_EMPLEADO,
TRASP.SEXO,
TRASP.CURP,
TRASP.RFC,
TRASP.IMSS,
TRASP.FECHA_CONTRATACION,
TRASP.FECHA_NACIMIENTO,
TRASP.CIUDAD_NACIMIENTO,
TRASP.PAIS_DE_NACIMIENTO,
TRASP.NACIONALIDAD,
TRASP.ESTADO_CIVIL,
TRASP.CORREO_ELECTRONICO,
TRASP.CLAVE_INFONAVIT,
TRASP.PERMISO_MIGRATORIO,
TRASP.FECHA_DE_ANTIGUEDAD,
TRASP.FECHA_DE_VENC_DEL_CONTRATO,
TRASP.FECHA_PLANTA,
TRASP.FECHA_DE_REINGRESO,
TRASP.SUBMOVIMIENTO,
TRASP.DIAS_DE_VENC_DEL_CONTRATO,
TRASP.FECHA_VENC_PERMISO_MIGRATORIO,
TRASP.FORMA_DE_PAGO,
TRASP.CUENTA_BANCARIA,
TRASP.SUCURSAL,
TRASP.DESCUENTO_INFONAVIT,
TRASP.USUARIO_MAM,
TRASP.ESTATUS_INTERFACE,
TRASP.FECHA_INTERFACE
FROM labprod.XXHR_TRASP_EMP_CANDIDATOS TRASP
INNER JOIN labprod.XXHR_CREAR_CANDIDATOS_LAB CAND ON TRASP.NO_EMPLEADO = CAND.EMP_KEYEMP
WHERE CAND.IDCANDIDATO IS NOT NULL;
