CREATE OR REPLACE EDITIONABLE TRIGGER "LABCONF"."CFDI2ERRORES_SEQ_TR" 
 BEFORE INSERT ON LABCONF.cfdi2Errores FOR EACH ROW
      WHEN (NEW.idError IS NULL) BEGIN
 SELECT LABCONF.cfdi2Errores_seq.NEXTVAL INTO :NEW.idError FROM DUAL;
END;



/
ALTER TRIGGER "LABCONF"."CFDI2ERRORES_SEQ_TR" ENABLE;
