CREATE OR REPLACE EDITIONABLE TRIGGER "LABCONF"."CFDI2CONF_SEQ_TR" 
 BEFORE INSERT ON LABCONF.cfdi2Conf FOR EACH ROW
      WHEN (NEW.idConfig IS NULL) BEGIN
 SELECT LABCONF.cfdi2Conf_seq.NEXTVAL INTO :NEW.idConfig FROM DUAL;
END;



/
ALTER TRIGGER "LABCONF"."CFDI2CONF_SEQ_TR" ENABLE;
