CREATE OR REPLACE EDITIONABLE TRIGGER "LABCONF"."CFDI2NOMINA_SEQ_TR" 
 BEFORE INSERT ON LABCONF.cfdi2Nomina FOR EACH ROW
      WHEN (NEW.idNomina IS NULL) BEGIN
 SELECT LABCONF.cfdi2Nomina_seq.NEXTVAL INTO :NEW.idNomina FROM DUAL;
END;



/
ALTER TRIGGER "LABCONF"."CFDI2NOMINA_SEQ_TR" ENABLE;
