CREATE OR REPLACE EDITIONABLE TRIGGER "LABCONF"."RECIBOS_INTERFACE_SEQ_TR" 
 BEFORE INSERT ON LABCONF.RECIBOS_INTERFACE FOR EACH ROW
    WHEN (
NEW.ID IS NULL
      ) BEGIN
 SELECT LABCONF.RECIBOS_INTERFACE_seq.NEXTVAL INTO :NEW.ID FROM DUAL;
END;



/
ALTER TRIGGER "LABCONF"."RECIBOS_INTERFACE_SEQ_TR" ENABLE;
