CREATE OR REPLACE EDITIONABLE TRIGGER "LABCONF"."T_COM_SIPS_ORAC_BITA" 
   BEFORE INSERT
     ON LABCONF.com_sips_orac_bita
     REFERENCING NEW AS NEW
     FOR EACH ROW
   BEGIN
     SELECT s_com_sips_orac_bita.nextval INTO :NEW.bit_noctvo FROM dual;
   END;




/
ALTER TRIGGER "LABCONF"."T_COM_SIPS_ORAC_BITA" ENABLE;
