CREATE OR REPLACE EDITIONABLE TRIGGER "LABCONF"."TR_DET_CAPINC" 
BEFORE INSERT ON LABCONF.det_capinc FOR EACH ROW 
BEGIN SELECT det_capinc_seq01.nextval INTO :new.det_numid FROM dual;
END;




/
ALTER TRIGGER "LABCONF"."TR_DET_CAPINC" ENABLE;
