CREATE OR REPLACE EDITIONABLE TRIGGER "LABCONF"."TR_SIPROS_ERP_ENC" AFTER
UPDATE OF APE_STATUS
       ON LABCONF.SIPROS_ERP_ENC
       FOR EACH ROW
DECLARE
  	W_NUM_ERROR    	NUMBER(6);
  	W_MENSAJE      	VARCHAR2(100);
    VAPE_KEYPOL     VARCHAR2(30);
  	VAPE_STATUS     VARCHAR2(1);
BEGIN
  IF UPDATING THEN
    VAPE_KEYPOL:=:NEW.APE_KEYPOL;
    VAPE_STATUS:=:NEW.APE_STATUS;
	END IF;
  -- ACTUALIZA EN LA TABLA TVLOFACE
  UPDATE LABCONF.TVLOFACE
     SET FEN_STATUS = VAPE_STATUS
   WHERE FEN_KEYFAC = VAPE_KEYPOL;
  EXCEPTION
  	WHEN OTHERS THEN
    	W_NUM_ERROR := SQLCODE;
     	W_MENSAJE := SUBSTR(SQLERRM,1,100);
END;






/
ALTER TRIGGER "LABCONF"."TR_SIPROS_ERP_ENC" ENABLE;
