CREATE OR REPLACE EDITIONABLE TRIGGER "LABCONF"."TVPBINCC_TRG" BEFORE
  INSERT ON LABCONF.TVPBINCC FOR EACH ROW
BEGIN
  SELECT LABCONF.TVPBINCC_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;



/
ALTER TRIGGER "LABCONF"."TVPBINCC_TRG" ENABLE;
