CREATE OR REPLACE EDITIONABLE TRIGGER "LABCONF"."WEBITACC_TRG" 
  BEFORE INSERT ON LABCONF.webitacc
  FOR EACH ROW
  BEGIN
      SELECT NVL(:new.wcc_idbacc, webitacc_seq.nextval) INTO :new.wcc_idbacc FROM dual;
  END;



/
ALTER TRIGGER "LABCONF"."WEBITACC_TRG" ENABLE;
