CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECI_OBTENER_TIPO_CAMBIO_RCB_MAN_PR" (
    p_FECHA_TC          VARCHAR2,
    p_CODIGO_MON        VARCHAR2
)
AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
feci_cursor             SYS_REFCURSOR;
SELECT_FEC_ORI          VARCHAR2(250);
SELECT_FEC_OPC          VARCHAR2(250);
SELECT_FEC_ALT          VARCHAR2(250);
SELECT_FEC_DOL          VARCHAR2(250);
SELECT_FEC_DOL_OPC      VARCHAR2(250);
SELECT_FEC_DOL_ALT      VARCHAR2(250);
BEGIN
BEGIN
    SELECT FEC_FECHA_TC INTO SELECT_FEC_OPC
    FROM FECXC.FECI_TIPO_CAMBIO_CAT
    WHERE FEC_FECHA_TC = p_FECHA_TC
    AND COD_MONEDA = p_CODIGO_MON
    FETCH NEXT 1 ROWS ONLY;
    SELECT_FEC_ORI := SELECT_FEC_OPC;
    SELECT FEC_FECHA_TC INTO SELECT_FEC_DOL_OPC
    FROM FECXC.FECI_TIPO_CAMBIO_CAT
    WHERE FEC_FECHA_TC = p_FECHA_TC
    AND COD_MONEDA = 'USD'
    FETCH NEXT 1 ROWS ONLY;
    SELECT_FEC_DOL := SELECT_FEC_DOL_OPC;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('SELECT_FEC_OPC ' || SELECT_FEC_OPC);
        DBMS_OUTPUT.PUT_LINE('SELECT_FEC_DOL_OPC ' || SELECT_FEC_DOL_OPC);
END;
BEGIN
    IF SELECT_FEC_ORI IS NULL THEN
        SELECT FEC_FECHA_TC INTO SELECT_FEC_ALT
        FROM FECXC.FECI_TIPO_CAMBIO_CAT
        WHERE FEC_FECHA_TC = (SELECT MAX(FEC_FECHA_TC) FROM FECXC.FECI_TIPO_CAMBIO_CAT)
        AND COD_MONEDA = p_CODIGO_MON
    	FETCH NEXT 1 ROWS ONLY;
    SELECT_FEC_ORI := SELECT_FEC_ALT;
    DBMS_OUTPUT.PUT_LINE('SELECT_FEC_ALT ' || SELECT_FEC_ALT);
    END IF;
    IF SELECT_FEC_DOL IS NULL THEN
        SELECT FEC_FECHA_TC INTO SELECT_FEC_DOL_ALT
        FROM FECXC.FECI_TIPO_CAMBIO_CAT
        WHERE FEC_FECHA_TC = (SELECT MAX(FEC_FECHA_TC) FROM FECXC.FECI_TIPO_CAMBIO_CAT WHERE COD_MONEDA = 'USD')
        AND COD_MONEDA = 'USD'
    	FETCH NEXT 1 ROWS ONLY;
    SELECT_FEC_DOL := SELECT_FEC_DOL_ALT;
    DBMS_OUTPUT.PUT_LINE('SELECT_FEC_DOL_ALT ' || SELECT_FEC_DOL_ALT);
    END IF;
    EXCEPTION
      WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('SELECT_FEC_ALT ' || SELECT_FEC_ALT);
END;
    OPEN feci_cursor FOR
        SELECT COD_MONEDA AS "CodigoMoneda", FEC_FECHA_TC AS "FechaTCOrigen",
            NUM_VALOR AS "TipoCambioOrigen", NULL, NULL
        FROM FECXC.FECI_TIPO_CAMBIO_CAT
        WHERE FEC_FECHA_TC = SELECT_FEC_ORI
        AND COD_MONEDA = p_CODIGO_MON
        UNION
        SELECT NULL, NULL, NULL, FEC_FECHA_TC AS "FechaTCDolar",
        NUM_VALOR AS "TipoCambioDolar"
        FROM FECXC.FECI_TIPO_CAMBIO_CAT
        WHERE FEC_FECHA_TC = SELECT_FEC_DOL
        AND COD_MONEDA = 'USD'
        fetch next 1 rows only;
    DBMS_SQL.RETURN_RESULT(feci_cursor);
END FECI_OBTENER_TIPO_CAMBIO_RCB_MAN_PR;
/
