CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECI_INSERTA_GRUPO_FORECAST_PR" 
(
        p_CODIGO         VARCHAR2,
        p_DESCRIPCION         VARCHAR2,
        p_Usuario              NUMBER
)
AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
    ID_REGISTRO NUMBER;
    feci_cursors SYS_REFCURSOR;
BEGIN
     INSERT INTO FECXC.FECI_GRUPO_FORECAST_CAT(COD_GRUPO_FORECAST, DES_GRUPO_FORECAST, FEC_CREACION,
                FEC_ULT_MODIFICACION,ID_USUARIO_CREACION , ID_USUARIO_ULT_MODIF, IND_ESTADO)
             VALUES(p_CODIGO, p_DESCRIPCION, sysdate, sysdate,
                    p_Usuario, 0, 1) returning ID_GRUPO_FORECAST INTO ID_REGISTRO;
            open feci_cursors for
               SELECT ID_GRUPO_FORECAST FROM FECXC.FECI_GRUPO_FORECAST_CAT WHERE ID_GRUPO_FORECAST =  ID_REGISTRO;
    DBMS_SQL.RETURN_RESULT(feci_cursors);
END FECI_INSERTA_GRUPO_FORECAST_PR ;
/
