CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECI_OBTENER_REPORTE_FLUJO_EFECTIVO_PR" 
AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
feci_cursor     SYS_REFCURSOR;
BEGIN
    OPEN feci_cursor FOR
        SELECT F.DES_GRUPO_FORECAST AS Grupo_Forecast, S.DES_SEGMENTO AS Segmento, E.COD_EMPRESA || ' - ' || E.DES_EMPRESA AS Empresa,
            CASE WHEN C.TIPO_RECIBO = 'MANUAL' THEN M.FEC_APLICACION ELSE R.FEC_APLICACION END AS Fecha_Registro,
            CASE WHEN C.TIPO_RECIBO = 'MANUAL' THEN M.FEC_OPERATIVA ELSE R.FEC_OPERATIVA END AS Fecha_GL,
            CASE WHEN C.TIPO_RECIBO = 'MANUAL' THEN M.METODO_PAGO ELSE R.METODO_PAGO END AS Metodo_Pago,
            CASE WHEN C.TIPO_RECIBO = 'MANUAL' THEN M.FOLIO_RECIBO_MANUAL ELSE R.FOLIO_RECIBO END AS Numero_Recibo,
            CASE WHEN C.TIPO_RECIBO = 'MANUAL' THEN M.NOM_CLIENTE ELSE R.NOM_CLIENTE END AS Nombre_Cliente,
            CASE WHEN C.TIPO_RECIBO = 'MANUAL' THEN M.REF_CLIENTE ELSE R.REF_CLIENTE END AS Referencia_Cliente,
            CASE WHEN C.TIPO_RECIBO = 'MANUAL' THEN 'N/A' ELSE R.COD_CLIENTE END AS Numero_Cliente,
            CASE WHEN C.TIPO_RECIBO = 'MANUAL' THEN M.CLASE_CLIENTE ELSE R.CLASE_CLIENTE END AS Clase_Cliente,
            C.DESC_CPS AS CPS, CONCEP.DES_CONCEPTO AS Concepto, REG.DES_REGION AS Region, P.DES_PAIS AS Pais, MON.DES_MONEDA AS Moneda,
            CASE WHEN C.TIPO_RECIBO = 'MANUAL' THEN M.TIPO_CAMBIO_ORIGEN ELSE R.TIPO_CAMBIO_ORIGEN END AS TC_Moneda_Origen,
            C.MONTO_BASE_ORG AS Monto_Base_Origen, C.MONTO_IVA_ORG AS Iva_Origen, C.IMPORTE_ORG AS Total_Monto_Origen,
            C.MONTO_BASE_MXN AS Monto_Base_Local, C.MONTO_IVA_MXN AS Iva_Local, C.IMPORTE_MXN AS Total_Monto_Local,
            CASE WHEN C.TIPO_RECIBO = 'MANUAL' THEN M.TIPO_CAMBIO_DOLAR ELSE R.TIPO_CAMBIO_DOLAR END AS TC_Dolares,
            C.MONTO_BASE_USD AS Monto_Base_Dolares, C.MONTO_IVA_USD AS Iva_Dolares, C.IMPORTE_USD AS Total_Monto_Dolares
        FROM FECXC.FECI_CLASIFICACION_TAB C
        INNER JOIN FECXC.FECI_GRUPO_FORECAST_CAT F ON C.COD_GRUPO_FORECAST = F.COD_GRUPO_FORECAST
        INNER JOIN FECXC.FECI_SEGMENTO_CAT S ON C.COD_SEGMENTO = S.COD_SEGMENTO
        LEFT OUTER JOIN FECXC.FECI_RECIBO_TAB R ON C.FOLIO_RECIBO = R.FOLIO_RECIBO
        LEFT OUTER JOIN FECXC.FECI_RECIBO_MANUAL_TAB M ON C.FOLIO_RECIBO = M.FOLIO_RECIBO_MANUAL
        LEFT OUTER JOIN FECXC.FECI_EMPRESA_CAT E ON R.COD_EMPRESA = E.COD_EMPRESA OR M.COD_EMPRESA = E.COD_EMPRESA
        INNER JOIN FECXC.FECI_CONCEPTO_CAT CONCEP ON C.COD_CONCEPTO = CONCEP.COD_CONCEPTO
        LEFT OUTER JOIN FECXC.FECI_REGION_CAT REG ON C.COD_REGION = REG.COD_REGION
        LEFT OUTER JOIN FECXC.FECI_PAIS_CAT P ON C.COD_PAIS = P.COD_PAIS
        LEFT OUTER JOIN FECXC.FECI_MONEDA_CAT MON ON R.COD_MONEDA = MON.COD_MONEDA OR M.COD_MONEDA = MON.COD_MONEDA;
    DBMS_SQL.RETURN_RESULT(feci_cursor);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            DBMS_OUTPUT.PUT_LINE('feci_cursor ');
END FECI_OBTENER_REPORTE_FLUJO_EFECTIVO_PR;
/
