CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECI_OBTENER_ULTIMA_MONEDA_PR" 
(
        p_ANIO         NUMBER,
        p_TIPO         VARCHAR2
)
IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
feci_cursor SYS_REFCURSOR;
v_query VARCHAR2(10000);
BEGIN
     v_query:='
     SELECT
    COD_MONEDA,
    EXTRACT(YEAR FROM FEC_PRESUPUESTO) AS ANO,
    MAX(FEC_CREACION) AS FEC_CREACION,
    MAX(ID_USUARIO_CREACION) AS ID_USUARIO_CREACION,
    SUM(CASE WHEN COD_MONEDA  in (' || p_TIPO ||') THEN NUM_IMPORTE ELSE 0 END) AS SUMA_NUM_IMPORTE,
    (SELECT DES_NOMBRES
     FROM FECI_USUARIO_TAB
     WHERE ID_USUARIO = (SELECT MAX(ID_USUARIO_CREACION)
                        FROM FECI_PRESUPUESTO_TAB
                        WHERE COD_MONEDA in (' || p_TIPO ||')
                        AND EXTRACT(YEAR FROM FEC_PRESUPUESTO) = TO_NUMBER(' || p_ANIO || '))
    ) AS DES_NOMBRES ,
    (SELECT DES_APELLIDOS
     FROM FECI_USUARIO_TAB
     WHERE ID_USUARIO = (SELECT MAX(ID_USUARIO_CREACION)
                        FROM FECI_PRESUPUESTO_TAB
                        WHERE COD_MONEDA in (' || p_TIPO ||')
                        AND EXTRACT(YEAR FROM FEC_PRESUPUESTO) = TO_NUMBER(' || p_ANIO || '))
    ) AS DES_APELLIDOS,
    (SELECT DES_MONEDA
     FROM FECI_MONEDA_CAT
     WHERE COD_MONEDA = (SELECT MAX(COD_MONEDA)
                        FROM FECI_PRESUPUESTO_TAB
                        WHERE COD_MONEDA in (' || p_TIPO ||')
                        AND EXTRACT(YEAR FROM FEC_PRESUPUESTO) = TO_NUMBER(' || p_ANIO || '))
    ) AS DESC_MONEDA
FROM
    FECI_PRESUPUESTO_TAB
WHERE
    COD_MONEDA in (' || p_TIPO ||')
    AND EXTRACT(YEAR FROM FEC_PRESUPUESTO) = TO_NUMBER(' || p_ANIO || ')
GROUP BY
    COD_MONEDA,
    EXTRACT(YEAR FROM FEC_PRESUPUESTO)';
       OPEN feci_cursor FOR v_query;
       DBMS_SQL.RETURN_RESULT(feci_cursor);
END FECI_OBTENER_ULTIMA_MONEDA_PR ;
/
