CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECI_MODIFICA_CANTIDAD_RECIBOS_CLASIFICADOS_PR" 
(
    p_ID_USUARIO NUMBER
)
AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
BEGIN
           UPDATE FECXC.FECI_RECIBO_MANUAL_TAB
           SET COD_ESTADO_RECIBO ='APLC' ,
           ID_USUARIO_APLICACION = p_ID_USUARIO,
            FEC_APLICACION = SYSDATE,
            FEC_ULT_MODIFICACION =  SYSDATE,
            ID_USUARIO_ULT_MODIF = p_ID_USUARIO
            WHERE
            FOLIO_RECIBO_MANUAL IN (SELECT FOLIO_RECIBO FROM FECXC.FECI_RECIBOS_VW WHERE TIPO_RECIBO='MANUAL'
            and COD_ESTADO_RECIBO='CLSF');
         UPDATE FECXC.FECI_RECIBO_TAB
           SET COD_ESTADO_RECIBO ='APLC' ,
           ID_USUARIO_APLICACION = p_ID_USUARIO,
            FEC_APLICACION = SYSDATE,
            FEC_ULT_MODIFICACION =  SYSDATE,
            ID_USUARIO_ULT_MODIF = p_ID_USUARIO
            WHERE
            FOLIO_RECIBO IN (SELECT FOLIO_RECIBO FROM FECXC.FECI_RECIBOS_VW
            WHERE TIPO_RECIBO='BATCH' and COD_ESTADO_RECIBO='CLSF');
END FECI_MODIFICA_CANTIDAD_RECIBOS_CLASIFICADOS_PR ;
/
