CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECI_MODIFICA_FECHA_OPERATIVA_PR" 
(
    p_RECIBO         NUMBER,
    p_TIPO           VARCHAR2,
    p_NUEVA_FECHA    DATE,
    p_USUARIO        NUMBER
)
AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
BEGIN
    IF p_TIPO = 'BATCH' THEN
        UPDATE FECXC.FECI_RECIBO_TAB
        SET
            FEC_OPERATIVA = TO_DATE(p_NUEVA_FECHA, 'YYYY-MM-DD'),
            ID_USUARIO_ULT_MODIF = p_USUARIO
        WHERE
            FOLIO_RECIBO = p_RECIBO;
    ELSE
        UPDATE FECXC.FECI_RECIBO_MANUAL_TAB
        SET
            FEC_OPERATIVA = TO_DATE(p_NUEVA_FECHA, 'YYYY-MM-DD'),
            ID_USUARIO_ULT_MODIF = p_USUARIO
        WHERE
            FOLIO_RECIBO_MANUAL = p_RECIBO;
    END IF;
    FECI_MODIFICA_TIPO_CAMBIO_RECIBO_PR(p_RECIBO, p_TIPO, p_USUARIO);
    FECI_CALCULA_MONTOS_CLASIFICACION_RECIBOS_PR(p_RECIBO, p_USUARIO);
END FECI_MODIFICA_FECHA_OPERATIVA_PR;
/
