CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_BITACORA_CLASIF_FE" 
(
	P_USUARIO IN VARCHAR2
)
IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
BEGIN
	 INSERT INTO FECXP_B_ENC_CLASIFICACION_FE(VERSION_ID, USUARIO_ID, FECHA_CREACION)
	 SELECT SEC_CLASIFICACION_FE.NEXTVAL, P_USUARIO, SYSDATE
	 FROM DUAL;
	INSERT INTO FECXP_B_DET_CLASIFICACION_FE (VERSION_ID, CLA_FE_ID, CLA_FE_DES, CLA_ATRIBUTO1, CLA_ATRIBUTO2, CLA_ATRIBUTO3, CLA_ATRIBUTO4, CLA_ATRIBUTO5, CLA_ATRIBUTO6, GENERA_SALDO)
	SELECT SEC_CLASIFICACION_FE.CURRVAL, CLA_FE_ID, CLA_FE_DES, CLA_ATRIBUTO1, CLA_ATRIBUTO2, CLA_ATRIBUTO3, CLA_ATRIBUTO4, CLA_ATRIBUTO5, CLA_ATRIBUTO6, GENERA_SALDO
	FROM FECXP_CLASIFICACION_FE;
	COMMIT;
END FECXP_BITACORA_CLASIF_FE;
/
