CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_MOV_COMPLEMTOS" 
IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
  V_FECHA       DATE := TO_DATE(SYSDATE,'DD-MM-YYYY');
  V_FECHA_EJE   VARCHAR (8);
  V_FIN_A       INTEGER(20):=TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'));
  V_FIN_M       INTEGER(20);
  V_FIN_D       INTEGER(20);
  V_FECHA_INI   VARCHAR (8);
  V_INI_A       INTEGER(20):=TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'));
  V_INI_M       INTEGER(20);
  V_INI_D       INTEGER(20);
  V_FECHA_FIN   VARCHAR (8);
  V_EJE_A       INTEGER(20):=TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'));
  V_EJE_M       INTEGER(20);
  V_EJE_D       INTEGER(20);
BEGIN
 -- PARAMETROS DE EJECUCION.
 SELECT DIAEJE, MESEJE,  DIAINI,  MESINI,  DIAFIN,  MESFIN
 INTO  V_EJE_D, V_EJE_M, V_INI_D, V_INI_M, V_FIN_D, V_FIN_M
 FROM FECXC.FECXP_PARAM_EXT_MC;
 V_EJE_M := TO_NUMBER(TO_CHAR(SYSDATE,'MM'));-- + V_EJE_M;         --MES EJECUCIoN  .
 V_EJE_A :=TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'));
 V_INI_M := TO_NUMBER(TO_CHAR(SYSDATE,'MM')) + V_INI_M;    --MES INICIO
 V_INI_A := TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')) + CASE WHEN V_EJE_M - V_INI_M < 0 THEN -1 ELSE 0 END;
 V_FIN_M := TO_NUMBER(TO_CHAR(SYSDATE,'MM')) + V_FIN_M;         --MES FIN
 V_FIN_A :=TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')) + CASE WHEN V_EJE_M - V_FIN_M < 0 THEN -1 ELSE 0 END;
 -- FECHA DE EJECUCION DE PROC.
 V_FECHA_EJE := TO_CHAR (V_EJE_A) || CASE WHEN V_EJE_M < 10 THEN '0' ELSE '' END || TO_CHAR (V_EJE_M) || CASE WHEN V_EJE_D < 10 THEN '0' ELSE '' END || TO_CHAR (V_EJE_D);
 -- FECHA DE INICIO DE EXTRACCION
 V_FECHA_INI := TO_CHAR (V_INI_A) || CASE WHEN V_INI_M < 10 THEN '0' ELSE '' END || TO_CHAR (V_INI_M) || CASE WHEN V_INI_D < 10 THEN '0' ELSE '' END || TO_CHAR (V_INI_D);
 -- FECHA DE FINAL DE EXTRACCION
 V_FECHA_FIN := TO_CHAR (V_FIN_A) || CASE WHEN V_FIN_M < 10 THEN '0' ELSE '' END || TO_CHAR (V_FIN_M) || CASE WHEN V_FIN_D < 10 THEN '0' ELSE '' END || TO_CHAR (V_FIN_D);
 -- v_Fecha_Eje := TO_DATE(v_Fecha_Eje_Str,'YYYYMMDD');
IF V_FECHA_EJE = TO_CHAR (SYSDATE,'YYYYMMDD') THEN
INSERT INTO FECXP_MOV_COMPLE_OPERA_ERP (SECUENCIA_MC_ERP, ORIGEN_POLIZA, JE_HEADER_ID, MONEDA,
            FECHA_EFECTIVA, IMPORTE_LINEA, MONTO_DEB_MON_ORIG, MONTO_CRE_MON_ORIG,
            MONTO_DEB_MON_CONV, MONTO_CRE_MON_CONV, LIBRO_ID, CODE_COMBINATION_ID,
            ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
            ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7)
SELECT SECUENCIA_MC_ERP.NEXTVAL,
    UPPER(JH.JE_SOURCE),		 				-- ORIGEN,
    JH.JE_HEADER_ID,			 		 		-- HEADER_ID,
    JH.CURRENCY_CODE,							-- MONEDA,
    JH.DEFAULT_EFFECTIVE_DATE,					-- FECHA_EFECTIVA,
    NVL(JH.RUNNING_TOTAL_ACCOUNTED_DR,0),		-- IMPORTE_LINEA, -- CHECAR EN LA VISTA: HEADER_RUN_TOTAL_ACCOUNTED_DR
    NVL(JL.ENTERED_DR,0),						-- MONTO_DEB_MON_ORIG, -- MONEDA ORIGEN
    NVL(JL.ENTERED_CR,0),						-- MONTO_CRE_MON_ORIG, -- MONEDA ORIGEN
    NVL(JL.ACCOUNTED_DR,0),						-- MONTO_DEB_MON_CONV, -- CONVETIDO
    NVL(JL.ACCOUNTED_CR,0),						-- MONTO_CRE_MON_CONV, -- CONVETIDO
    JH.SET_OF_BOOKS_ID,  						-- LIBRO_ID,
    G.CODE_COMBINATION_ID,
    G.SEGMENT1,
    G.SEGMENT2,
    G.SEGMENT3,
    G.SEGMENT4,
    G.SEGMENT5,
    G.SEGMENT6,
    G.SEGMENT7
  FROM FECXP_GL_JE_SOURCES JS,
    GL_JE_HEADERS@ERP_PROD JH,
    GL_JE_LINES@ERP_PROD JL,
    GL_CODE_COMBINATIONS@ERP_PROD G
  WHERE G.SUMMARY_FLAG            = 'N'
  AND  G.ENABLED_FLAG          	  = 'Y'
  AND  G.CHART_OF_ACCOUNTS_ID  	  = 101 -- 101 ES PARA GL LIBRO OPERATIVO
  AND  JH.CURRENCY_CODE       	 != 'STAT'
  AND  JH.STATUS            	  = 'P'
  AND  JH.ACTUAL_FLAG        	  = 'A'
  AND  JS.FLAG_ORIGEN_MC          = 1
  AND  TO_CHAR(JH.DEFAULT_EFFECTIVE_DATE,'YYYYMMDD')
  	   BETWEEN V_FECHA_INI AND V_FECHA_FIN
  AND  JS.JE_SOURCE_NAME          = JH.JE_SOURCE
  AND  JH.SET_OF_BOOKS_ID         = JL.SET_OF_BOOKS_ID
  AND  JH.JE_HEADER_ID            = JL.JE_HEADER_ID
  AND  G.CODE_COMBINATION_ID      = JL.CODE_COMBINATION_ID;
END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20000,'No hay datos nuevos.');
END  Fecxp_Mov_Complemtos;
/
