CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXC_IMP_DATOS_LAYOUT" (
	V_ID_SESION  in VARCHAR2,
	V_MES		 in NUMBER,
	V_PER 		 in NUMBER
)
IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
	V_ERRORES INT:= 0;
	MES_ACT VARCHAR2(2);
	PER_ACT VARCHAR2(4);
	PER_SIG	INT;
	FECHA DATE;
	V_ANIOS INT;
BEGIN
	 /* INICIALIZA CIFRAS DE CONTROL*/
	 DELETE FECXC_CIFRAS_CONTROL
	 	WHERE MES = V_MES
		AND PERIODO = V_PER;
	-- ***** DEBUGUEO *****
		UPDATE	FECXC_CARGA_PRESUP
				SET		ESTATUS_ORIGEN = 'VALIDO'
				WHERE TO_NUMBER(TO_CHAR(FECHA,'MM')) = V_MES
				AND ANIO = V_PER;
	--- **** VALIDA EL MES Y PERIODO ACTUUAL
	SELECT SYSDATE
	INTO FECHA FROM DUAL;
	SELECT TO_CHAR(SYSDATE,'MM')
	INTO MES_ACT FROM DUAL;
	SELECT TO_CHAR(SYSDATE,'YYYY')
	INTO PER_ACT FROM DUAL;
	IF TO_NUMBER(MES_ACT) <> V_MES THEN
		INSERT	INTO FECXP_BITACORA_ERRORES (ID_SESION,MENSAJE)
		VALUES (V_ID_SESION,'MES INVALIDO ' || V_MES || 'MES ACTUAL ' ||MES_ACT);
	END IF;
	IF TO_NUMBER(PER_ACT) <> V_PER THEN
		INSERT	INTO FECXP_BITACORA_ERRORES (ID_SESION,MENSAJE)
		VALUES (V_ID_SESION,'PERIODO INVALIDO ' || V_PER || 'PERIODO ACTUAL ' ||MES_ACT);
	END IF;
--verifica si es periodo nuevo, si es asi, inserta codigo de monedas  22 y 14
    PER_SIG := V_PER + 1;
    IF TO_NUMBER(MES_ACT) = 12 THEN
	  SELECT	COUNT (*)
	  INTO	V_ANIOS
	  FROM	FECXC_ENC_DE_PRESU
	  WHERE CODANNO = PER_SIG;
	   IF  V_ANIOS = 0 THEN
	   	   	INSERT INTO FECXC_ENC_DE_PRESU (SEC_PRESUP, SECMONEDA, CODANNO,FECHA, USU_PRES)
		  	select SEC_PRESUP.NEXTVAL, 22, PER_SIG, FECHA, 'Carga Presupuesto '||PER_ACT FROM DUAL;
		    INSERT INTO FECXC_ENC_DE_PRESU (SEC_PRESUP, SECMONEDA, CODANNO,FECHA, USU_PRES)
		  	select SEC_PRESUP.NEXTVAL, 14, PER_SIG, FECHA, 'Carga Presupuesto '||PER_ACT FROM DUAL;
	    END IF;
	END IF;
	-- ***** VALIDA MONEDA *****
	UPDATE	FECXC_CARGA_PRESUP D
	SET		ESTATUS_ORIGEN = 'MONEDA INVALIDA'
	WHERE MONEDA NOT IN (
		  		 SELECT  CODMONEDA
				 FROM FECXC_MONEDAS
				        )
	AND	TO_NUMBER(TO_CHAR(D.FECHA,'MM')) = V_MES
	AND D.ANIO = V_PER;
	/*VALIDA MES DEL ARCHIVO CON EL MES DE GENERACION*/
	UPDATE	FECXC_CARGA_PRESUP D
	SET		ESTATUS_ORIGEN = 'MES INVALIDO'
	WHERE	TO_NUMBER(TO_CHAR(D.FECHA,'MM')) <> V_MES
	AND D.ANIO = V_PER;
	/*VALIDA PERIODO DEL ARCHIVO CON EL PERIODO DE GENERACION*/
	UPDATE	FECXC_CARGA_PRESUP D
	SET		ESTATUS_ORIGEN = 'PERIODO INVALIDO '
	WHERE	TO_NUMBER(TO_CHAR(D.FECHA,'MM')) = V_MES
	AND D.ANIO <> V_PER;
	-- ***** VALIDA MONTOS NEGATIVOS *****
	UPDATE	FECXC_CARGA_PRESUP D
	SET		ESTATUS_ORIGEN = 'MONTO NEGATIVO'
	WHERE IMPORTE < 0
	AND	TO_NUMBER(TO_CHAR(D.FECHA,'MM')) = V_MES
	AND D.ANIO = V_PER;
	-- ***** VALIDA DIVISION *****
	UPDATE FECXC_CARGA_PRESUP D
	SET ESTATUS_ORIGEN = 'DIVISION INVALIDA'
	WHERE DIVISION NOT IN (
		  		   SELECT  COD_VALOR
				   FROM FECXC_DET_CATALOGOS
				   WHERE TIPO_CAT IN('REGION','DIVISION','CANAL')
				    	   )
	AND	TO_NUMBER(TO_CHAR(D.FECHA,'MM')) = V_MES
	AND D.ANIO = V_PER;
	-- ***** VALIDA SEGMENTO *****
	UPDATE FECXC_CARGA_PRESUP D
	SET ESTATUS_ORIGEN = 'SEGMENTO INVALIDO'
	WHERE SEGMENTO NOT IN (
		  		   SELECT COD_VALOR
				   FROM FECXC_DET_CATALOGOS
				   WHERE TIPO_CAT IN('SEGMENTO')
				           )
	AND	TO_NUMBER(TO_CHAR(D.FECHA,'MM')) = V_MES
	AND D.ANIO = V_PER;
	-- ***** VALIDA CONCEPTO *****
	UPDATE FECXC_CARGA_PRESUP D
	SET ESTATUS_ORIGEN = 'CONCEPTO INVALIDO'
	WHERE CONCEPTO NOT IN (
		  		   SELECT  COD_VALOR
				   FROM FECXC_DET_CATALOGOS
				   WHERE TIPO_CAT IN('CONCEPTO')
				   		  )
	AND	TO_NUMBER(TO_CHAR(D.FECHA,'MM')) = V_MES
	AND D.ANIO = V_PER;
	-- ***** GUARDA BITACORAS *****
	-- *****  MONEDA INVALIDA *****
	INSERT	INTO FECXP_BITACORA_ERRORES (
			ID_SESION, MENSAJE)
	SELECT	V_ID_SESION, ESTATUS_ORIGEN || ': ' || MONEDA
	FROM	FECXC_CARGA_PRESUP
	WHERE	ESTATUS_ORIGEN = 'MONEDA INVALIDA'
	AND		TO_NUMBER(TO_CHAR(FECHA,'MM')) = V_MES
	AND 	ANIO = V_PER
	GROUP BY ESTATUS_ORIGEN,MONEDA;
		-- *****  MES INVALIDO *****
	INSERT	INTO FECXP_BITACORA_ERRORES (
			ID_SESION, MENSAJE)
	SELECT	V_ID_SESION, ESTATUS_ORIGEN || ': ' || TO_CHAR(FECHA,'MM')
	FROM	FECXC_CARGA_PRESUP
	WHERE	ESTATUS_ORIGEN = 'MES INVALIDO'
	AND		TO_NUMBER(TO_CHAR(FECHA,'MM')) <> V_MES
	AND 	ANIO = V_PER
	GROUP BY ESTATUS_ORIGEN,TO_CHAR(FECHA,'MM');
			-- *****  PERIODO INVALIDO *****
	INSERT	INTO FECXP_BITACORA_ERRORES (
			ID_SESION, MENSAJE)
	SELECT	V_ID_SESION, ESTATUS_ORIGEN || ': ' || 'A?O ORIGEN'|| TO_CHAR(ANIO)
	FROM	FECXC_CARGA_PRESUP
	WHERE	ESTATUS_ORIGEN = 'PERIODO INVALIDO'
	AND		TO_NUMBER(TO_CHAR(FECHA,'MM')) = V_MES
	AND 	ANIO <> V_PER
	GROUP BY ESTATUS_ORIGEN,TO_CHAR(ANIO);
		-- *****  MONTO  NEGATIVOS*****
	INSERT	INTO FECXP_BITACORA_ERRORES (
			ID_SESION, MENSAJE)
	SELECT	V_ID_SESION, ESTATUS_ORIGEN || ': ' || IMPORTE
	FROM	FECXC_CARGA_PRESUP
	WHERE	ESTATUS_ORIGEN = 'MONTO NEGATIVO'
	AND		TO_NUMBER(TO_CHAR(FECHA,'MM')) = V_MES
	AND 	ANIO = V_PER
	GROUP BY ESTATUS_ORIGEN,IMPORTE;
	-- *****  SEGMENTO INVALIDO *****
	INSERT	INTO FECXP_BITACORA_ERRORES (
			ID_SESION, MENSAJE)
	SELECT	V_ID_SESION, ESTATUS_ORIGEN || ': ' || SEGMENTO
	FROM	FECXC_CARGA_PRESUP
	WHERE	ESTATUS_ORIGEN = 'SEGMENTO INVALIDO'
	AND		TO_NUMBER(TO_CHAR(FECHA,'MM')) = V_MES
	AND 	ANIO = V_PER
	GROUP BY ESTATUS_ORIGEN,SEGMENTO;
	-- *****  CONCEPTO INVALIDO *****
	INSERT	INTO FECXP_BITACORA_ERRORES (
			ID_SESION, MENSAJE)
	SELECT	V_ID_SESION, ESTATUS_ORIGEN || ': ' || CONCEPTO
	FROM	FECXC_CARGA_PRESUP
	WHERE	ESTATUS_ORIGEN = 'CONCEPTO INVALIDO'
	AND		TO_NUMBER(TO_CHAR(FECHA,'MM')) = V_MES
	AND 	ANIO = V_PER
	GROUP BY ESTATUS_ORIGEN,CONCEPTO;
	-- *****  DIVISION INVALIDA *****
	INSERT	INTO FECXP_BITACORA_ERRORES (
			ID_SESION, MENSAJE)
	SELECT	V_ID_SESION, ESTATUS_ORIGEN || ': ' || DIVISION
	FROM	FECXC_CARGA_PRESUP
	WHERE	ESTATUS_ORIGEN = 'DIVISION INVALIDA'
	AND		TO_NUMBER(TO_CHAR(FECHA,'MM')) = V_MES
	AND 	ANIO = V_PER
	GROUP BY ESTATUS_ORIGEN,DIVISION;
	/**insrta registro duplicados */
	INSERT	INTO FECXP_BITACORA_ERRORES (
			ID_SESION, MENSAJE)
	SELECT	V_ID_SESION, 'REGISTRO DUPLICADO. CANTIDAD: ' || CUANTOS ||
			',  FECHA: ' || TO_CHAR (SYSDATE, 'DD-MON-YYYY', 'NLS_DATE_LANGUAGE=SPANISH') ||
			', SEGMENTO: ' || SEGMENTO ||
			', CONCEPTO: ' || CONCEPTO ||
			', ANIO: ' || TO_CHAR (ANIO) ||
			', DIVISION: ' || DIVISION
	FROM	(
				SELECT COUNT (1) CUANTOS, MONEDA,FECHA,SEGMENTO,CONCEPTO,ANIO,DIVISION
				FROM   FECXC_CARGA_PRESUP
				GROUP BY MONEDA,FECHA,SEGMENTO,CONCEPTO,ANIO,DIVISION
			)
	WHERE	CUANTOS > 1;
	--****** VALIDA QUE NO EXISTA COMAS EN LOS IMPORTES ****
	-- ***** PROCESA REGISTROS *****
	SELECT	COUNT (*)
	INTO	V_ERRORES
	FROM	FECXP_BITACORA_ERRORES;
	IF V_ERRORES > 0 THEN
		DELETE	FECXC_CARGA_PRESUP
		WHERE	TO_NUMBER(TO_CHAR(FECHA,'MM')) = V_MES
		AND 	ANIO = V_PER;
	ELSE
	--UNA VEZ QUE EN EL SEIS NO HAY INCONSISTENCIAS SE GENERA EL ARCHIVO DE CIFRAS DE CONTROL
	--ESTO CONLLEVA LOS SIGUIENTES SUB-PASOS POR
	--A..EXTRAER CIFRAS DE CONTROL POR SEGMENT0
	--B..EXTRAER CIFRAS DE CONTROL POR CONCEPTO
	--C..EXTRAER CIFRAS DE CONTROL POR DIVISION
	--D..EXTRAER CIFRAS DE CONTROL POR CANAL
	--E..EXTRAER CIFRAS DE CONTROL POR REGION
--A..EXTRAER CIFRAS DE CONTROL POR SEGMENT0
INSERT INTO FECXC_CIFRAS_CONTROL (MES,PERIODO,SEGMENTO,IMPORTE_SEG)
select V_MES,V_PER,B.COD_VALOR, sum(IMPORTE)
FROM FECXC_CARGA_PRESUP A, FECXC_DET_CATALOGOS B ,
	 FECXC_ENC_DE_PRESU E, FECXC_MONEDAS F
WHERE  B.TIPO_CAT = 'SEGMENTO'
	  AND A.SEGMENTO = B.COD_VALOR
	  AND A.ANIO = E.CODANNO
	  AND A.MONEDA = F.CODMONEDA
	  AND F.SECMONEDA = E.SECMONEDA
	  AND TO_NUMBER(TO_CHAR(A.FECHA,'MM')) = V_MES
	  AND A.ANIO = V_PER
group by V_MES,V_PER,B.COD_VALOR;
--B..EXTRAER CIFRAS DE CONTROL POR CONCEPTO
--DELETE FECXC_CIFRAS_CONTROL
UPDATE FECXC_CIFRAS_CONTROL SET IMPORTE_CON = (SELECT SUM(IMPORTE)
	   										  FROM FECXC_CARGA_PRESUP A, FECXC_DET_CATALOGOS B ,FECXC_DET_CATALOGOS C,
											  FECXC_ENC_DE_PRESU E, FECXC_MONEDAS F
											  WHERE  B.TIPO_CAT = 'SEGMENTO'
									    	  AND A.SEGMENTO = B.COD_VALOR
											  AND C.TIPO_CAT = 'CONCEPTO'
											  AND A.CONCEPTO = C.COD_VALOR
											  AND A.ANIO = E.CODANNO
											  AND A.MONEDA = F.CODMONEDA
											  AND F.SECMONEDA = E.SECMONEDA
											  AND FECXC_CIFRAS_CONTROL.SEGMENTO = B.COD_VALOR
											  AND TO_NUMBER(TO_CHAR(A.FECHA,'MM')) = V_MES
											  AND A.ANIO = V_PER
											  GROUP BY B.COD_VALOR );
--C..EXTRAER CIFRAS DE CONTROL POR DIVISION
UPDATE FECXC_CIFRAS_CONTROL SET IMPORTE_DIV	 = (SELECT sum(IMPORTE)
	   										    FROM FECXC_CARGA_PRESUP A, FECXC_DET_CATALOGOS B ,FECXC_DET_CATALOGOS C, FECXC_DET_CATALOGOS D,
													 FECXC_ENC_DE_PRESU E, FECXC_MONEDAS F
											  WHERE  B.TIPO_CAT = 'SEGMENTO'
										   	     AND A.SEGMENTO = B.COD_VALOR
										   	     AND C.TIPO_CAT = 'CONCEPTO'
												 AND A.CONCEPTO = C.COD_VALOR
	  											 AND D.TIPO_CAT = 'DIVISION'
	  											 AND A.DIVISION = D.COD_VALOR
	  											 AND A.ANIO = E.CODANNO
	  											 AND A.MONEDA = F.CODMONEDA
	  											 AND F.SECMONEDA = E.SECMONEDA
												 AND FECXC_CIFRAS_CONTROL.SEGMENTO = B.COD_VALOR
											     AND TO_NUMBER(TO_CHAR(A.FECHA,'MM')) = V_MES
											     AND A.ANIO = V_PER
												 group by B.COD_VALOR);
--D..EXTRAER CIFRAS DE CONTROL POR CANAL
UPDATE FECXC_CIFRAS_CONTROL SET IMPORTE_CAN	 = (SELECT sum(IMPORTE)
	   										   FROM FECXC_CARGA_PRESUP A, FECXC_DET_CATALOGOS B ,FECXC_DET_CATALOGOS C, FECXC_DET_CATALOGOS D,
											   	 FECXC_ENC_DE_PRESU E, FECXC_MONEDAS F
												 WHERE  B.TIPO_CAT = 'SEGMENTO'
												  AND A.SEGMENTO = B.COD_VALOR
												  AND C.TIPO_CAT = 'CONCEPTO'
												  AND A.CONCEPTO = C.COD_VALOR
												  AND D.TIPO_CAT = 'CANAL'
	  											  AND A.DIVISION = D.COD_VALOR
	 											  AND A.ANIO = E.CODANNO
	  											  AND A.MONEDA = F.CODMONEDA
	  											  AND F.SECMONEDA = E.SECMONEDA
												  AND FECXC_CIFRAS_CONTROL.SEGMENTO = B.COD_VALOR
											     AND TO_NUMBER(TO_CHAR(A.FECHA,'MM')) = V_MES
											     AND A.ANIO = V_PER
												  group by B.COD_VALOR);
--E..EXTRAER CIFRAS DE CONTROL POR REGION
UPDATE FECXC_CIFRAS_CONTROL SET IMPORTE_REG	 = (SELECT sum(IMPORTE)
	   										 FROM FECXC_CARGA_PRESUP A, FECXC_DET_CATALOGOS B ,FECXC_DET_CATALOGOS C, FECXC_DET_CATALOGOS D,
											 	  FECXC_ENC_DE_PRESU E, FECXC_MONEDAS F
										      WHERE  B.TIPO_CAT = 'SEGMENTO'
											  AND A.SEGMENTO = B.COD_VALOR
	  										  AND C.TIPO_CAT = 'CONCEPTO'
 	  										  AND A.CONCEPTO = C.COD_VALOR
	  										  AND D.TIPO_CAT = 'REGION'
	  										  AND A.DIVISION = D.COD_VALOR
	  										  AND A.ANIO = E.CODANNO
	  										  AND A.MONEDA = F.CODMONEDA
											  AND F.SECMONEDA = E.SECMONEDA
											  AND FECXC_CIFRAS_CONTROL.SEGMENTO = B.COD_VALOR
											  AND TO_NUMBER(TO_CHAR(A.FECHA,'MM')) = V_MES
											  AND A.ANIO = V_PER
											  group by B.COD_VALOR);
/*Actualiza conceptos*/
					   UPDATE FECXC_CIFRAS_CONTROL SET CONCEPTO = SEGMENTO
					   WHERE IMPORTE_CON IS NOT NULL;
					   UPDATE FECXC_CIFRAS_CONTROL SET DIVISION = SEGMENTO
					   WHERE IMPORTE_DIV IS NOT NULL;
					   UPDATE FECXC_CIFRAS_CONTROL SET CANAL = SEGMENTO
					   WHERE IMPORTE_CAN IS NOT NULL;
					   UPDATE FECXC_CIFRAS_CONTROL SET REGION = SEGMENTO
					   WHERE IMPORTE_REG IS NOT NULL;
	-- ***** Realiza cifras de control antes de incluir a historicos *****
		INSERT	INTO	FECXP_BITACORA_ERRORES (ID_SESION, MENSAJE)
		VALUES	(V_ID_SESION, 'CIFRAS DE CONTROL GENERADAS');
END IF;
END FECXC_IMP_DATOS_LAYOUT;
/
