CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_PPTO_OP_A_PPTO_FE" IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
BEGIN
----- Extrae el presupuesto ----
INSERT INTO FECXP_PPTO_OPERA_ERP (E_CODIGO,
	   							  SECUENCIA_PTTO_ORACLE,
	   							  PERIODO_EXTRACCION,
	   							  MES_DE_EXTRACCION,
								  PERIODO_PPTO,
								  LIBRO_ID,
								  VERSION_ID,
								  MONEDA,
								  CODE_COMBINATION_ID,
								  ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3,
								  ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7,
								  PPTO_01, PSS_01, USD_01, EUR_01,
								  PPTO_02, PSS_02, USD_02, EUR_02,
								  PPTO_03, PSS_03, USD_03, EUR_03,
								  PPTO_04, PSS_04, USD_04, EUR_04,
								  PPTO_05, PSS_05, USD_05, EUR_05,
								  PPTO_06, PSS_06, USD_06, EUR_06,
								  PPTO_07, PSS_07, USD_07, EUR_07,
								  PPTO_08, PSS_08, USD_08, EUR_08,
								  PPTO_09, PSS_09, USD_09, EUR_09,
								  PPTO_10, PSS_10, USD_10, EUR_10,
								  PPTO_11, PSS_11, USD_11, EUR_11,
								  PPTO_12, PSS_12, USD_12, EUR_12)
SELECT  GLP.CIA,
		SECUENCIA_PTTO_ORACLE.NEXTVAL,
		TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')),
		TO_NUMBER(TO_CHAR(SYSDATE,'MM')),
		GLP.YYYY,
		GLP.LIBRO_ID,
		GLP.VERSION_ID,
		GLP.MONEDA,
		CC.CODE_COMBINATION_ID,
		GLP.CIA, GLP.NEG, GLP.CTA, GLP.SCTA, GLP.CC, GLP.ICIA, GLP.TOP,
		GLP.PPTO_01, TC.PSS_01, TC.USD_01, TC.EUR_01,
		GLP.PPTO_02, TC.PSS_02, TC.USD_02, TC.EUR_02,
		GLP.PPTO_03, TC.PSS_03, TC.USD_03, TC.EUR_03,
		GLP.PPTO_04, TC.PSS_04, TC.USD_04, TC.EUR_04,
		GLP.PPTO_05, TC.PSS_05, TC.USD_05, TC.EUR_05,
		GLP.PPTO_06, TC.PSS_06, TC.USD_06, TC.EUR_06,
		GLP.PPTO_07, TC.PSS_07, TC.USD_07, TC.EUR_07,
		GLP.PPTO_08, TC.PSS_08, TC.USD_08, TC.EUR_08,
		GLP.PPTO_09, TC.PSS_09, TC.USD_09, TC.EUR_09,
		GLP.PPTO_10, TC.PSS_10, TC.USD_10, TC.EUR_10,
		GLP.PPTO_11, TC.PSS_11, TC.USD_11, TC.EUR_11,
		GLP.PPTO_12, TC.PSS_12, TC.USD_12, TC.EUR_12
FROM	GL.GL_CODE_COMBINATIONS@ERP_PROD CC,
		INTERFACE.XXGLB_PPTOS@ERP_PROD GLP,
		INTERFACE.XXGLB_PPTOS_TC@ERP_PROD TC
WHERE   CC.SEGMENT1 = GLP.CIA
AND		CC.SEGMENT2 = GLP.NEG
AND		CC.SEGMENT3 = GLP.CTA
AND		CC.SEGMENT4 = GLP.SCTA
AND		CC.SEGMENT5 = GLP.CC
AND		CC.SEGMENT6 = GLP.ICIA
AND		CC.SEGMENT7 = GLP.TOP
AND     CC.CHART_OF_ACCOUNTS_ID = '101'
AND		GLP.MONEDA <> 'PSS'
AND		TC.LIBRO_ID = GLP.LIBRO_ID;
------------------------------------------------------------------------------------------------------------------------
-- CONVERSION PRESUPUESTO SOIN
-- PRESUPUESTO_ESTATUS : 'E' Extraido, 'C', Convertido, 'I' Importado (Por Archivo de Texto)
------------------------------------------------------------------------------------------------------------------------
INSERT	INTO FECXP_PPTO_CONVERSION_SOIN (
		E_CODIGO,SECUENCIA_PPTO_OPERATIVO_SOIN, PERIODO, MESCOD, ARSMAP, AEJMAP,
		CNCMAP, MONEDA, TIPO_CAMBIO, IMPORTE_LINEA, PERIODO_EXTRACCION,
		MES_EXTRACCION, PRESUPUESTO_ESTATUS)
SELECT	E_CODIGO,SECUENCIA_PPTO_OPERATIVO_SOIN.NEXTVAL, PERIODO, MESCOD, ARSMAP, AEJMAP,
		CNCMAP, MONEDA, TIPO_CAMBIO, IMPORTE_LINEA, PERIODO_EXTRACCION,
		MES_EXTRACCION, 'EXTRAIDO'
FROM	FECXP_PPTO_OPERATIVO_SOIN;
--ACTUALIZA PRESUPUESTO (DE OPERATIVO A "CONVERTIDO" )  .
UPDATE	FECXP_PPTO_CONVERSION_SOIN PFE
SET		IMPORTE_LINEA = 0,
		PRESUPUESTO_ESTATUS = 'CONVERTIDO'
WHERE	EXISTS (
		SELECT	1
		FROM	FECXP_REGLAS_CONVERSION_PPTO RC
		WHERE	(PFE.ARSMAP >= RC.REG_SEGMENTO1_INI OR RC.REG_SEGMENTO1_INI IS NULL)
		AND		(PFE.ARSMAP <= RC.REG_SEGMENTO1_FIN OR RC.REG_SEGMENTO1_FIN IS NULL)
		AND		(PFE.AEJMAP >= RC.REG_SEGMENTO2_INI OR RC.REG_SEGMENTO2_INI IS NULL)
		AND		(PFE.AEJMAP <= RC.REG_SEGMENTO2_FIN OR RC.REG_SEGMENTO2_FIN IS NULL)
		AND		(PFE.CNCMAP >= RC.REG_SEGMENTO3_INI OR RC.REG_SEGMENTO3_INI IS NULL)
		AND		(PFE.CNCMAP <= RC.REG_SEGMENTO3_FIN OR RC.REG_SEGMENTO3_FIN IS NULL)
		AND		(PFE.PERIODO = RC.PERIODO OR RC.PERIODO IS NULL)
		AND		(PFE.MESCOD >= RC.MES_INI OR RC.MES_INI IS NULL)
		AND		(PFE.MESCOD <= RC.MES_FIN OR RC.MES_FIN IS NULL)
		AND		RC.PLATAFORMA = 'SOIN');
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
-- CONVERSION PRESUPUESTO ORACLE
-- PRESUPUESTO_ESTATUS : 'E' Extraido, 'C', Convertido, 'I' Importado (Por Archivo de Texto)
------------------------------------------------------------------------------------------------------------------------
/*
PERIODO_EXTRACCION INT
MES_EXTRACCION INT
PRESUPUESTO_ESTATUS VARCHAR (20)
*/
-- DADO QUE NO SE MANEJAN LOS SQLSTRINGS, DEBERA SER NECESARIO HACER UN INSERT POR CADA MES.
--SOLO PARA EFECTOS DE PRUEBA  .
--TRUNCATE TABLE FECXP_PPTO_CONVERSION_ERP;
--quedaria mejor con "decode" .
-- MES 1
INSERT	INTO FECXP_PPTO_CONVERSION_ERP (
		E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
		MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS)
SELECT	E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL,TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), 1, LIBRO_ID, VERSION_ID,
		MONEDA, CASE
				WHEN MONEDA = 'MXP' THEN PSS_01
				WHEN MONEDA = 'USD' THEN USD_01
				WHEN MONEDA = 'EUR' THEN EUR_01 END,
		CODE_COMBINATION_ID, PPTO_01, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO'
FROM	FECXP_PPTO_OPERA_ERP;
-- MES 2
INSERT	INTO FECXP_PPTO_CONVERSION_ERP (
		E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
		MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS)
SELECT	E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL,TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), 2, LIBRO_ID, VERSION_ID,
		MONEDA,
		CASE
				WHEN MONEDA = 'MXP' THEN PSS_02
				WHEN MONEDA = 'USD' THEN USD_02
				WHEN MONEDA = 'EUR' THEN EUR_02 END,
		CODE_COMBINATION_ID, PPTO_02, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO'
FROM	FECXP_PPTO_OPERA_ERP;
-- MES 3
INSERT	INTO FECXP_PPTO_CONVERSION_ERP (
		E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
		MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS)
SELECT	E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL,TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), 3, LIBRO_ID, VERSION_ID,
		MONEDA,
		CASE
				WHEN MONEDA = 'MXP' THEN PSS_03
				WHEN MONEDA = 'USD' THEN USD_03
				WHEN MONEDA = 'EUR' THEN EUR_03 END,
		CODE_COMBINATION_ID, PPTO_02, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO'
FROM	FECXP_PPTO_OPERA_ERP;
-- MES 4
INSERT	INTO FECXP_PPTO_CONVERSION_ERP (
		E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
		MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS)
SELECT	E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL,TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), 4, LIBRO_ID, VERSION_ID,
		MONEDA,
		CASE
				WHEN MONEDA = 'MXP' THEN PSS_04
				WHEN MONEDA = 'USD' THEN USD_04
				WHEN MONEDA = 'EUR' THEN EUR_04 END,
		CODE_COMBINATION_ID, PPTO_02, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO'
FROM	FECXP_PPTO_OPERA_ERP;
-- MES 5
INSERT	INTO FECXP_PPTO_CONVERSION_ERP (
		E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
		MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS)
SELECT	E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL,TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), 5, LIBRO_ID, VERSION_ID,
		MONEDA,
		CASE
				WHEN MONEDA = 'MXP' THEN PSS_05
				WHEN MONEDA = 'USD' THEN USD_05
				WHEN MONEDA = 'EUR' THEN EUR_05 END,
		CODE_COMBINATION_ID, PPTO_02, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO'
FROM	FECXP_PPTO_OPERA_ERP;
-- MES 6
INSERT	INTO FECXP_PPTO_CONVERSION_ERP (
		E_CODIGO,SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
		MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS)
SELECT	E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL,TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), 6, LIBRO_ID, VERSION_ID,
		MONEDA,
		CASE
				WHEN MONEDA = 'MXP' THEN PSS_06
				WHEN MONEDA = 'USD' THEN USD_06
				WHEN MONEDA = 'EUR' THEN EUR_06 END,
		CODE_COMBINATION_ID, PPTO_02, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO'
FROM	FECXP_PPTO_OPERA_ERP;
-- MES 7
INSERT	INTO FECXP_PPTO_CONVERSION_ERP (
		E_CODIGO, SECUENCIA_PTTO_CONVERSION,  PERIODO, MES, LIBRO_ID, VERSION_ID,
		MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS)
SELECT	E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL,TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), 7, LIBRO_ID, VERSION_ID,
		MONEDA,
		CASE
				WHEN MONEDA = 'MXP' THEN PSS_07
				WHEN MONEDA = 'USD' THEN USD_07
				WHEN MONEDA = 'EUR' THEN EUR_07 END,
		CODE_COMBINATION_ID, PPTO_02, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO'
FROM	FECXP_PPTO_OPERA_ERP;
-- MES 8
INSERT	INTO FECXP_PPTO_CONVERSION_ERP (
		E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
		MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS)
SELECT	E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL,TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), 8, LIBRO_ID, VERSION_ID,
		MONEDA,
		CASE
				WHEN MONEDA = 'MXP' THEN PSS_08
				WHEN MONEDA = 'USD' THEN USD_08
				WHEN MONEDA = 'EUR' THEN EUR_08 END,
		CODE_COMBINATION_ID, PPTO_02, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO'
FROM	FECXP_PPTO_OPERA_ERP;
-- MES 9
INSERT	INTO FECXP_PPTO_CONVERSION_ERP (
		E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
		MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS)
SELECT	E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL,TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), 9, LIBRO_ID, VERSION_ID,
		MONEDA,
		CASE
				WHEN MONEDA = 'MXP' THEN PSS_09
				WHEN MONEDA = 'USD' THEN USD_09
				WHEN MONEDA = 'EUR' THEN EUR_09 END,
		CODE_COMBINATION_ID, PPTO_02, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO'
FROM	FECXP_PPTO_OPERA_ERP;
-- MES 10
INSERT	INTO FECXP_PPTO_CONVERSION_ERP (
		E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
		MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS)
SELECT	E_CODIGO,SECUENCIA_PTTO_CONVERSION.NEXTVAL, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), 10, LIBRO_ID, VERSION_ID,
		MONEDA,
		CASE
				WHEN MONEDA = 'MXP' THEN PSS_10
				WHEN MONEDA = 'USD' THEN USD_10
				WHEN MONEDA = 'EUR' THEN EUR_10 END,
		CODE_COMBINATION_ID, PPTO_02, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO'
FROM	FECXP_PPTO_OPERA_ERP;
-- MES 11
INSERT	INTO FECXP_PPTO_CONVERSION_ERP (
		E_CODIGO,SECUENCIA_PTTO_CONVERSION,  PERIODO, MES, LIBRO_ID, VERSION_ID,
		MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS)
SELECT	E_CODIGO,SECUENCIA_PTTO_CONVERSION.NEXTVAL, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), 11, LIBRO_ID, VERSION_ID,
		MONEDA,
		CASE
				WHEN MONEDA = 'MXP' THEN PSS_11
				WHEN MONEDA = 'USD' THEN USD_11
				WHEN MONEDA = 'EUR' THEN EUR_11 END,
		CODE_COMBINATION_ID, PPTO_02, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO'
FROM	FECXP_PPTO_OPERA_ERP;
-- MES 12
INSERT	INTO FECXP_PPTO_CONVERSION_ERP (
		E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
		MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS)
SELECT	E_CODIGO,SECUENCIA_PTTO_CONVERSION.NEXTVAL, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), 12, LIBRO_ID, VERSION_ID,
		MONEDA,
		CASE
				WHEN MONEDA = 'MXP' THEN PSS_12
				WHEN MONEDA = 'USD' THEN USD_12
				WHEN MONEDA = 'EUR' THEN EUR_12 END,
		CODE_COMBINATION_ID, PPTO_02, ORACLE_SEGMENTO1,
		ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
		ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO'
FROM	FECXP_PPTO_OPERA_ERP;
------------------------------------ FIN MESES -------------------------------
UPDATE	FECXP_PPTO_CONVERSION_ERP PFE
SET		IMPORTE_LINEA = 0,
		PRESUPUESTO_ESTATUS = 'CONVERTIDO'
WHERE EXISTS (
		SELECT 1
		FROM   FECXP_REGLAS_CONVERSION_PPTO RC
		WHERE  (PFE.ORACLE_SEGMENTO1 >= RC.REG_SEGMENTO1_INI OR RC.REG_SEGMENTO1_INI IS NULL)
		AND		(PFE.ORACLE_SEGMENTO1 <= RC.REG_SEGMENTO1_FIN OR RC.REG_SEGMENTO1_FIN IS NULL)
		AND		(PFE.ORACLE_SEGMENTO2 >= RC.REG_SEGMENTO2_INI OR RC.REG_SEGMENTO2_INI IS NULL)
		AND		(PFE.ORACLE_SEGMENTO2 <= RC.REG_SEGMENTO2_FIN OR RC.REG_SEGMENTO2_FIN IS NULL)
		AND		(PFE.ORACLE_SEGMENTO3 >= RC.REG_SEGMENTO3_INI OR RC.REG_SEGMENTO3_INI IS NULL)
		AND		(PFE.ORACLE_SEGMENTO3 <= RC.REG_SEGMENTO3_FIN OR RC.REG_SEGMENTO3_FIN IS NULL)
		AND		(PFE.ORACLE_SEGMENTO4 >= RC.REG_SEGMENTO4_INI OR RC.REG_SEGMENTO4_INI IS NULL)
		AND		(PFE.ORACLE_SEGMENTO4 <= RC.REG_SEGMENTO4_FIN OR RC.REG_SEGMENTO4_FIN IS NULL)
		AND		(PFE.ORACLE_SEGMENTO5 >= RC.REG_SEGMENTO5_INI OR RC.REG_SEGMENTO5_INI IS NULL)
		AND		(PFE.ORACLE_SEGMENTO5 <= RC.REG_SEGMENTO5_FIN OR RC.REG_SEGMENTO5_FIN IS NULL)
		AND		(PFE.ORACLE_SEGMENTO6 >= RC.REG_SEGMENTO6_INI OR RC.REG_SEGMENTO6_INI IS NULL)
		AND		(PFE.ORACLE_SEGMENTO6 <= RC.REG_SEGMENTO6_FIN OR RC.REG_SEGMENTO6_FIN IS NULL)
		AND		(PFE.ORACLE_SEGMENTO7 >= RC.REG_SEGMENTO7_INI OR RC.REG_SEGMENTO7_INI IS NULL)
		AND		(PFE.ORACLE_SEGMENTO7 <= RC.REG_SEGMENTO7_FIN OR RC.REG_SEGMENTO7_FIN IS NULL)
		AND		(PFE.PERIODO = RC.PERIODO OR RC.PERIODO IS NULL)
		AND		(PFE.MES >= RC.MES_INI OR RC.MES_INI IS NULL)
		AND		(PFE.MES <= RC.MES_FIN OR RC.MES_FIN IS NULL)
		AND		RC.PLATAFORMA = 'ORACLE');
COMMIT;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20000,'No hay datos nuevos.');
END Fecxp_Ppto_Op_a_ppto_fe;
/
