CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_DET_CONT_OI" 
(
	V_FECHA_INI DATE:= SYSDATE - 1,
	V_FECHA_FIN DATE:= SYSDATE - 11
)
IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
--	V_FECHA_INI DATE:= SYSDATE - 31;
--	V_FECHA_FIN DATE:= SYSDATE - 1;
	V_CLA_FE_ID FECXP_POLITICAS_ERP.CLA_FE_ID%TYPE;
	V_PRIORIDAD FECXP_POLITICAS_ERP.PRIORIDAD%TYPE;
	V_TIPO_OPERACION_INI FECXP_POLITICAS_ERP.TIPO_OPERACION_INI%TYPE;
	V_TIPO_OPERACION_FIN FECXP_POLITICAS_ERP.TIPO_OPERACION_FIN%TYPE;
	V_ID_BANCO_INI FECXP_POLITICAS_ERP.ID_BANCO_INI%TYPE;
	V_ID_BANCO_FIN FECXP_POLITICAS_ERP.ID_BANCO_FIN%TYPE;
	V_ID_CHEQUERA_INI FECXP_POLITICAS_ERP.ID_CHEQUERA_INI%TYPE;
	V_ID_CHEQUERA_FIN FECXP_POLITICAS_ERP.ID_CHEQUERA_FIN%TYPE;
	V_POLITICA_ERP_ID FECXP_POLITICAS_ERP.POLITICA_ERP_ID%TYPE;
	V_ORA_S1_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_INI%TYPE;
	V_ORA_S1_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_FIN%TYPE;
	V_ORA_S2_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_INI%TYPE;
	V_ORA_S2_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_FIN%TYPE;
	V_ORA_S3_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_INI%TYPE;
	V_ORA_S3_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_FIN%TYPE;
	V_ORA_S4_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_INI%TYPE;
	V_ORA_S4_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_FIN%TYPE;
	V_ORA_S5_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_INI%TYPE;
	V_ORA_S5_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_FIN%TYPE;
	V_ORA_S6_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_INI%TYPE;
	V_ORA_S6_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_FIN%TYPE;
	V_ORA_S7_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_INI%TYPE;
	V_ORA_S7_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_FIN%TYPE;
	CURSOR	CURSOR_CLASIFICACION_FE_ORACLE IS
	SELECT	CLA_FE_ID, POLITICA_ERP_ID, PRIORIDAD, TIPO_OPERACION_INI, TIPO_OPERACION_FIN, ID_BANCO_INI, ID_BANCO_FIN, ID_CHEQUERA_INI, ID_CHEQUERA_FIN,
			ORACLE_SEGMENTO1_INI, ORACLE_SEGMENTO1_FIN, ORACLE_SEGMENTO2_INI, ORACLE_SEGMENTO2_FIN, ORACLE_SEGMENTO3_INI, ORACLE_SEGMENTO3_FIN, ORACLE_SEGMENTO4_INI, ORACLE_SEGMENTO4_FIN, ORACLE_SEGMENTO5_INI, ORACLE_SEGMENTO5_FIN, ORACLE_SEGMENTO6_INI, ORACLE_SEGMENTO6_FIN, ORACLE_SEGMENTO7_INI, ORACLE_SEGMENTO7_FIN
	FROM	FECXP_POLITICAS_ERP
	WHERE 	ID_TIPO_MOVTO IN ('A', 'E')
	AND  	ACTIVA_REGLA = 1
	ORDER BY PRIORIDAD ASC;
	CURSOR	CURSOR_CLASIFICACION_FE_ING IS
	SELECT	CLA_FE_ID, POLITICA_ERP_ID, PRIORIDAD, TIPO_OPERACION_INI, TIPO_OPERACION_FIN, ID_BANCO_INI, ID_BANCO_FIN, ID_CHEQUERA_INI, ID_CHEQUERA_FIN,
			ORACLE_SEGMENTO1_INI, ORACLE_SEGMENTO1_FIN
	FROM	FECXP_POLITICAS_ERP
	WHERE	ID_TIPO_MOVTO IN ('A', 'I')
	AND		ACTIVA_REGLA = 1
	ORDER BY PRIORIDAD ASC;
BEGIN
	DELETE	FECXP_PAGOS_ERP_OI
	WHERE	E_CODIGO > 0;
	--==  INSERTA TODOS LOS DETALLES QUE TENGAN UNA CUENTA DE PROVISI?N ==--
	INSERT	INTO FECXP_PAGOS_ERP_OI (E_CODIGO, FOLIO_SET, TIPO_OPERACION, ESTATUS_MOVIMIENTO, ID_CHEQUERA, ID_BANCO, FORMA_PAGO, FECHA_APLICACION, MONEDA, TIPO_CAMBIO, ORIGEN_MOVIMIENTO, IMPORTE, NUMERO_DE_PARTIDA_ERP, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, IMPORTE_LINEA, CONCEPTO, BENEFICIARIO, CLA_FE_ID_POL, CLA_FE_DES_POL, CLA_FE_ID_OI, CLA_FE_DES_OI, ORGANIZATION_ID, NAME, NO_CLIENTE)
	SELECT	EP.E_CODIGO, EP.FOLIO_SET, EP.TIPO_OPERACION, EP.ESTATUS_MOVIMIENTO, EP.ID_CHEQUERA, EP.ID_BANCO, EP.FORMA_PAGO, EP.FECHA_APLICACION, EP.MONEDA, EP.TIPO_CAMBIO, EP.ORIGEN_MOVIMIENTO, EP.IMPORTE, DE.NUMERO_DE_PARTIDA_ERP, DE.ORACLE_SEGMENTO1, DE.ORACLE_SEGMENTO2, DE.ORACLE_SEGMENTO3, DE.ORACLE_SEGMENTO4, DE.ORACLE_SEGMENTO5, DE.ORACLE_SEGMENTO6, DE.ORACLE_SEGMENTO7, DE.IMPORTE_LINEA, EP.CONCEPTO, EP.BENEFICIARIO, '|', '<SIN CLASIFICACI?N>', '|', '<SIN CLASIFICACI?N>', 0, '<EL REGISTRO NO EXISTE>', EP.NO_CLIENTE
	FROM	FECXP_ENC_PAGOS_ERP EP,
			FECXP_DET_PAGOS_ERP DE,
			FECXP_PAGOS_CUENTAS_APERTURA CA
	WHERE	FECHA_APLICACION >= V_FECHA_INI
	AND		FECHA_APLICACION <= V_FECHA_FIN
	AND		(DE.ORACLE_SEGMENTO1 = CA.ORACLE_SEGMENTO1 OR CA.ORACLE_SEGMENTO1 IS NULL)
	AND		(DE.ORACLE_SEGMENTO2 = CA.ORACLE_SEGMENTO2 OR CA.ORACLE_SEGMENTO2 IS NULL)
	AND		(DE.ORACLE_SEGMENTO3 = CA.ORACLE_SEGMENTO3 OR CA.ORACLE_SEGMENTO3 IS NULL)
	AND		(DE.ORACLE_SEGMENTO4 = CA.ORACLE_SEGMENTO4 OR CA.ORACLE_SEGMENTO4 IS NULL)
	AND		(DE.ORACLE_SEGMENTO5 = CA.ORACLE_SEGMENTO5 OR CA.ORACLE_SEGMENTO5 IS NULL)
	AND		(DE.ORACLE_SEGMENTO6 = CA.ORACLE_SEGMENTO6 OR CA.ORACLE_SEGMENTO6 IS NULL)
	AND		(DE.ORACLE_SEGMENTO7 = CA.ORACLE_SEGMENTO7 OR CA.ORACLE_SEGMENTO7 IS NULL)
	AND		EP.SECUENCIA_PAGOS_ERP = DE.SECUENCIA_PAGOS_ERP;
	DELETE	FECXP_ORGANIZACIONES_AP;
	COMMIT;
	INSERT	INTO FECXP_ORGANIZACIONES_AP (
			E_CODIGO, FOLIO_SET, ORG_ID, VENDOR_ID, PO_DISTRIBUTION_ID)
	SELECT	FE.E_CODIGO,
			FE.FOLIO_SET,
			IA.ORG_ID,
			IA.VENDOR_ID, -- PARA JOIN
			D.PO_DISTRIBUTION_ID -- PARA JOIN
	FROM	(
				SELECT	 E_CODIGO, FOLIO_SET
				FROM	 FECXP_PAGOS_ERP_OI
				GROUP BY E_CODIGO, FOLIO_SET
			) FE,
			AP_INVOICES_ALL@ERP_PROD IA,
			AP_INVOICE_PAYMENTS_ALL@ERP_PROD IP,
			AP_CHECKS_ALL@ERP_PROD CH,
			AP_INVOICE_DISTRIBUTIONS_ALL@ERP_PROD D
	WHERE	D.LINE_TYPE_LOOKUP_CODE = 'ITEM'
	AND		D.PO_DISTRIBUTION_ID IS NOT NULL
	AND		CH.ATTRIBUTE11 = FE.FOLIO_SET
	AND		IA.INVOICE_ID = IP.INVOICE_ID
	AND		IA.INVOICE_ID = D.INVOICE_ID
	AND		IP.CHECK_ID = CH.CHECK_ID
	GROUP BY FE.E_CODIGO,
			FE.FOLIO_SET,
			IA.ORG_ID,
			IA.VENDOR_ID, -- PARA JOIN
			D.PO_DISTRIBUTION_ID; -- PARA JOIN
	COMMIT;
	DELETE	FECXP_ORGANIZACIONES_RCV;
	COMMIT;
	INSERT	INTO FECXP_ORGANIZACIONES_RCV (
			E_CODIGO, FOLIO_SET, ORG_ID, ORG_INVENTARIO, DESC_ORG_INV)
	SELECT	E_CODIGO,
			FOLIO_SET,
			ORG_ID,
			RSH.SHIP_TO_ORG_ID ORG_INVENTARIO,
			OI.NAME DESC_ORG_INV
	FROM 	FECXP_ORGANIZACIONES_AP FE,
			FECXP_ORG_INV_FLUJO OFE,
			PO.RCV_SHIPMENT_HEADERS@ERP_PROD RSH,
			PO.RCV_SHIPMENT_LINES@ERP_PROD RSL,
			PO.RCV_TRANSACTIONS@ERP_PROD RT ,
			HR.HR_ALL_ORGANIZATION_UNITS@ERP_PROD OI
	WHERE	RT.TRANSACTION_TYPE = 'RECEIVE'
	AND		RT.PO_HEADER_ID IS NOT NULL
	AND		OFE.ORGANIZATION_ID = RSH.SHIP_TO_ORG_ID
	AND		RSH.SHIPMENT_HEADER_ID = RSL.SHIPMENT_HEADER_ID
	AND		RSH.SHIPMENT_HEADER_ID = RT.SHIPMENT_HEADER_ID
	AND		RSL.SHIPMENT_LINE_ID = RT.SHIPMENT_LINE_ID
	AND		RSL.SHIPMENT_HEADER_ID = RT.SHIPMENT_HEADER_ID
	AND		OI.ORGANIZATION_ID = RSH.SHIP_TO_ORG_ID
	AND		RSL.PO_DISTRIBUTION_ID = FE.PO_DISTRIBUTION_ID
	GROUP BY E_CODIGO,
			FOLIO_SET,
			ORG_ID,
			RSH.SHIP_TO_ORG_ID,
			OI.NAME;
	COMMIT;
	DELETE	FECXP_PAGOS_ERP_OI OI
	WHERE	EXISTS (
			SELECT	1
			FROM	FECXP_ORGANIZACIONES_RCV RCV
			WHERE	RCV.E_CODIGO = OI.E_CODIGO
			AND		RCV.FOLIO_SET = OI.FOLIO_SET
	);
	COMMIT;
	INSERT	INTO FECXP_PAGOS_ERP_OI (E_CODIGO, FOLIO_SET, TIPO_OPERACION, ESTATUS_MOVIMIENTO, ID_CHEQUERA, ID_BANCO, FORMA_PAGO, FECHA_APLICACION, MONEDA, TIPO_CAMBIO, ORIGEN_MOVIMIENTO, IMPORTE, NUMERO_DE_PARTIDA_ERP, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, IMPORTE_LINEA, CONCEPTO, BENEFICIARIO, CLA_FE_ID_POL, CLA_FE_DES_POL, CLA_FE_ID_OI, CLA_FE_DES_OI, ORGANIZATION_ID, NAME, NO_CLIENTE)
	SELECT	EP.E_CODIGO, EP.FOLIO_SET, EP.TIPO_OPERACION, EP.ESTATUS_MOVIMIENTO, EP.ID_CHEQUERA, EP.ID_BANCO, EP.FORMA_PAGO, EP.FECHA_APLICACION, EP.MONEDA, EP.TIPO_CAMBIO, EP.ORIGEN_MOVIMIENTO, EP.IMPORTE, DE.NUMERO_DE_PARTIDA_ERP, DE.ORACLE_SEGMENTO1, DE.ORACLE_SEGMENTO2, DE.ORACLE_SEGMENTO3, DE.ORACLE_SEGMENTO4, DE.ORACLE_SEGMENTO5, DE.ORACLE_SEGMENTO6, DE.ORACLE_SEGMENTO7, DE.IMPORTE_LINEA, EP.CONCEPTO, EP.BENEFICIARIO, '|', '<SIN CLASIFICACI?N>', '|', '<SIN CLASIFICACI?N>', RCV.ORG_INVENTARIO, RCV.DESC_ORG_INV, EP.NO_CLIENTE
	FROM	FECXP_ORGANIZACIONES_RCV RCV,
			FECXP_ENC_PAGOS_ERP EP,
			FECXP_DET_PAGOS_ERP DE,
			FECXP_PAGOS_CUENTAS_APERTURA CA
	WHERE	EP.FECHA_APLICACION >= V_FECHA_INI
	AND		EP.FECHA_APLICACION <= V_FECHA_FIN
	AND		(DE.ORACLE_SEGMENTO1 = CA.ORACLE_SEGMENTO1 OR CA.ORACLE_SEGMENTO1 IS NULL)
	AND		(DE.ORACLE_SEGMENTO2 = CA.ORACLE_SEGMENTO2 OR CA.ORACLE_SEGMENTO2 IS NULL)
	AND		(DE.ORACLE_SEGMENTO3 = CA.ORACLE_SEGMENTO3 OR CA.ORACLE_SEGMENTO3 IS NULL)
	AND		(DE.ORACLE_SEGMENTO4 = CA.ORACLE_SEGMENTO4 OR CA.ORACLE_SEGMENTO4 IS NULL)
	AND		(DE.ORACLE_SEGMENTO5 = CA.ORACLE_SEGMENTO5 OR CA.ORACLE_SEGMENTO5 IS NULL)
	AND		(DE.ORACLE_SEGMENTO6 = CA.ORACLE_SEGMENTO6 OR CA.ORACLE_SEGMENTO6 IS NULL)
	AND		(DE.ORACLE_SEGMENTO7 = CA.ORACLE_SEGMENTO7 OR CA.ORACLE_SEGMENTO7 IS NULL)
	AND		EP.SECUENCIA_PAGOS_ERP = DE.SECUENCIA_PAGOS_ERP
	AND		EP.E_CODIGO = RCV.E_CODIGO
	AND		EP.FOLIO_SET = RCV.FOLIO_SET;
	UPDATE	FECXP_PAGOS_ERP_OI OI
	SET		CLA_FE_ID_OI =
				(
				SELECT	FE.CLA_FE_ID
				FROM	FECXP_ORG_INV_FLUJO FE
				WHERE	OI.ORGANIZATION_ID = FE.ORGANIZATION_ID
				)
	WHERE	EXISTS (
			SELECT	1
				FROM	FECXP_ORG_INV_FLUJO FE
				WHERE	OI.ORGANIZATION_ID = FE.ORGANIZATION_ID
	);
	COMMIT;
	--==  INTEGRA LA CLASIFICACI?N DE CLAVES DE FLUJO ORIGINALES ==--
	OPEN CURSOR_CLASIFICACION_FE_ORACLE;
	LOOP
		FETCH CURSOR_CLASIFICACION_FE_ORACLE
		INTO V_CLA_FE_ID, V_POLITICA_ERP_ID, V_PRIORIDAD, V_TIPO_OPERACION_INI, V_TIPO_OPERACION_FIN, V_ID_BANCO_INI, V_ID_BANCO_FIN, V_ID_CHEQUERA_INI, V_ID_CHEQUERA_FIN,
		V_ORA_S1_INI, V_ORA_S1_FIN, V_ORA_S2_INI, V_ORA_S2_FIN, V_ORA_S3_INI, V_ORA_S3_FIN, V_ORA_S4_INI, V_ORA_S4_FIN, V_ORA_S5_INI, V_ORA_S5_FIN, V_ORA_S6_INI, V_ORA_S6_FIN, V_ORA_S7_INI, V_ORA_S7_FIN;
		EXIT WHEN CURSOR_CLASIFICACION_FE_ORACLE%NOTFOUND;
		--== CLASIFICACI?N DE CUENTAS CONTABLES ERP ==--
		UPDATE	FECXP_PAGOS_ERP_OI
		SET		CLA_FE_ID_POL = V_CLA_FE_ID
		WHERE	(TIPO_OPERACION >= NVL (V_TIPO_OPERACION_INI, 0))
		AND		(TIPO_OPERACION <= NVL (V_TIPO_OPERACION_FIN, 9999))
		AND		(ID_BANCO >= NVL (V_ID_BANCO_INI, 0))
		AND		(ID_BANCO <= NVL (V_ID_BANCO_FIN, 9999))
		AND		(LPAD (ID_CHEQUERA, 20, '0') >= NVL (LPAD (V_ID_CHEQUERA_INI, 20, '0'), '00000000000000000000'))
		AND		(LPAD (ID_CHEQUERA, 20, '0') <= NVL (LPAD (V_ID_CHEQUERA_FIN, 20, '0'), '99999999999999999999'))
		AND		(ORACLE_SEGMENTO1 <= NVL (V_ORA_S1_FIN, 'z'))
		AND		(ORACLE_SEGMENTO2 >= NVL (V_ORA_S2_INI, '0'))
		AND		(ORACLE_SEGMENTO2 <= NVL (V_ORA_S2_FIN, 'z'))
		AND		(ORACLE_SEGMENTO3 >= NVL (V_ORA_S3_INI, '0'))
		AND		(ORACLE_SEGMENTO3 <= NVL (V_ORA_S3_FIN, 'z'))
		AND		(ORACLE_SEGMENTO4 >= NVL (V_ORA_S4_INI, '0'))
		AND		(ORACLE_SEGMENTO4 <= NVL (V_ORA_S4_FIN, 'z'))
		AND		(ORACLE_SEGMENTO5 >= NVL (V_ORA_S5_INI, '0'))
		AND		(ORACLE_SEGMENTO5 <= NVL (V_ORA_S5_FIN, 'z'))
		AND		(ORACLE_SEGMENTO6 >= NVL (V_ORA_S6_INI, '0'))
		AND		(ORACLE_SEGMENTO6 <= NVL (V_ORA_S6_FIN, 'z'))
		AND		(ORACLE_SEGMENTO7 >= NVL (V_ORA_S7_INI, '0'))
		AND		(ORACLE_SEGMENTO7 <= NVL (V_ORA_S7_FIN, 'z'))
		AND		NVL (CLA_FE_ID_POL, '|') = '|';
	END LOOP;
	CLOSE CURSOR_CLASIFICACION_FE_ORACLE;
	--== ACTUALIZA CAMPO CLA_FE_DES_POL ==--
	UPDATE	FECXP_PAGOS_ERP_OI POI
	SET		POI.CLA_FE_DES_POL  = (SELECT CF.CLA_FE_DES
	FROM	FECXP_CLASIFICACION_FE CF
	WHERE	CF.CLA_FE_ID = POI.CLA_FE_ID_POL);
	--== ACTUALIZA CLA_FE_DES_OI ==--
	UPDATE	FECXP_PAGOS_ERP_OI POI
	SET		POI.CLA_FE_DES_OI= (SELECT CF.CLA_FE_DES
	FROM	FECXP_CLASIFICACION_FE CF
	WHERE	CF.CLA_FE_ID = POI.CLA_FE_ID_OI);
	COMMIT;
-- AGREGAR SIN?NIMOS Y GRANTS
END FECXP_DET_CONT_OI;
/
