CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_PPTO_OP_A_PPTO_FE_ERP" (
    V_VERSION_FE IN INTEGER,
    V_USUARIO_ID IN VARCHAR2,
    V_COMENTARIO IN VARCHAR2
) IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
    V_E_CODIGO INTEGER;
    CURSOR C_CODE_COMB IS
    SELECT DISTINCT e_codigo AS e_codigo FROM FECXP_PPTO_CONVERSION_ERP WHERE version_fe=V_VERSION_FE;
    /*Incluye modificacion de filtro y de periodo*/
    /*20090713  Modificacion para todas las monedas*/
    /*07-DIC-2010 Modificacion para que tome los meses acumulados de las poiticas*/
    /*07-may-2012 Se agrega cursor para update por que con el EXIST no terminaba*/
BEGIN
    DELETE    FECXP_PPTO_CONVERSION_ERP_ENC
    WHERE    VERSION_FE = V_VERSION_FE;
    DELETE    FECXP_PPTO_CONVERSION_ERP
    WHERE    VERSION_FE = V_VERSION_FE AND E_CODIGO = NVL (V_E_CODIGO, E_CODIGO);
    -- MES 1
    INSERT    INTO FECXP_PPTO_CONVERSION_ERP (
            E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
            MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS, VERSION_FE,
            MON_FUNC, MON_ORIG)
    SELECT    E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL, PERIODO_PPTO, 1, LIBRO_ID, VERSION_ID,
            MONEDA, TC_01,CODE_COMBINATION_ID, PPTO_01, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO', VERSION_FE,
            MON_FUNC, MON_ORIG
    FROM    FECXP_PPTO_OPERA_ERP
    WHERE    VERSION_FE = V_VERSION_FE AND E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
            ;
    -- MES 2
    INSERT    INTO FECXP_PPTO_CONVERSION_ERP (
            E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
            MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS, VERSION_FE,
            MON_FUNC, MON_ORIG)
    SELECT    E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL, PERIODO_PPTO, 2, LIBRO_ID, VERSION_ID,
            MONEDA,    TC_02,CODE_COMBINATION_ID, PPTO_02, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO', VERSION_FE,
            MON_FUNC, MON_ORIG
    FROM    FECXP_PPTO_OPERA_ERP
    WHERE    VERSION_FE = V_VERSION_FE AND E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
            ;
    -- MES 3
    INSERT    INTO FECXP_PPTO_CONVERSION_ERP (
            E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
            MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS, VERSION_FE,
            MON_FUNC, MON_ORIG)
    SELECT    E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL, PERIODO_PPTO, 3, LIBRO_ID, VERSION_ID,
            MONEDA,TC_03,CODE_COMBINATION_ID, PPTO_03, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO', VERSION_FE,
            MON_FUNC, MON_ORIG
    FROM    FECXP_PPTO_OPERA_ERP
    WHERE    VERSION_FE = V_VERSION_FE AND E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
            ;
    -- MES 4
    INSERT    INTO FECXP_PPTO_CONVERSION_ERP (
            E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
            MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS, VERSION_FE,
            MON_FUNC, MON_ORIG)
    SELECT    E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL, PERIODO_PPTO, 4, LIBRO_ID, VERSION_ID,
            MONEDA,TC_04,CODE_COMBINATION_ID, PPTO_04, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO', VERSION_FE,
            MON_FUNC, MON_ORIG
    FROM    FECXP_PPTO_OPERA_ERP
    WHERE    VERSION_FE = V_VERSION_FE AND E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
            ;
    -- MES 5
    INSERT    INTO FECXP_PPTO_CONVERSION_ERP (
            E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
            MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS, VERSION_FE,
            MON_FUNC, MON_ORIG)
    SELECT    E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL, PERIODO_PPTO, 5, LIBRO_ID, VERSION_ID,
            MONEDA,TC_05,CODE_COMBINATION_ID, PPTO_05, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO', VERSION_FE,
            MON_FUNC, MON_ORIG
    FROM    FECXP_PPTO_OPERA_ERP
    WHERE    VERSION_FE = V_VERSION_FE AND E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
            ;
    -- MES 6
    INSERT    INTO FECXP_PPTO_CONVERSION_ERP (
            E_CODIGO,SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
            MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS, VERSION_FE,
            MON_FUNC, MON_ORIG)
    SELECT    E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL, PERIODO_PPTO, 6, LIBRO_ID, VERSION_ID,
            MONEDA,TC_06,CODE_COMBINATION_ID, PPTO_06, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO', VERSION_FE,
            MON_FUNC, MON_ORIG
    FROM    FECXP_PPTO_OPERA_ERP
    WHERE    VERSION_FE = V_VERSION_FE AND E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
            ;
    -- MES 7
    INSERT    INTO FECXP_PPTO_CONVERSION_ERP (
            E_CODIGO, SECUENCIA_PTTO_CONVERSION,  PERIODO, MES, LIBRO_ID, VERSION_ID,
            MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS, VERSION_FE,
            MON_FUNC, MON_ORIG)
    SELECT    E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL, PERIODO_PPTO, 7, LIBRO_ID, VERSION_ID,
            MONEDA,TC_07,CODE_COMBINATION_ID, PPTO_07, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO', VERSION_FE,
            MON_FUNC, MON_ORIG
    FROM    FECXP_PPTO_OPERA_ERP
    WHERE    VERSION_FE = V_VERSION_FE AND E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
            ;
    -- MES 8
    INSERT    INTO FECXP_PPTO_CONVERSION_ERP (
            E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
            MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS, VERSION_FE,
            MON_FUNC, MON_ORIG)
    SELECT    E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL, PERIODO_PPTO, 8, LIBRO_ID, VERSION_ID,
            MONEDA,TC_08,CODE_COMBINATION_ID, PPTO_08, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO', VERSION_FE,
            MON_FUNC, MON_ORIG
    FROM    FECXP_PPTO_OPERA_ERP
    WHERE    VERSION_FE = V_VERSION_FE AND E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
            ;
    -- MES 9
    INSERT    INTO FECXP_PPTO_CONVERSION_ERP (
            E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
            MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS, VERSION_FE,
            MON_FUNC, MON_ORIG)
    SELECT    E_CODIGO, SECUENCIA_PTTO_CONVERSION.NEXTVAL, PERIODO_PPTO, 9, LIBRO_ID, VERSION_ID,
            MONEDA,TC_09,CODE_COMBINATION_ID, PPTO_09, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO', VERSION_FE,
            MON_FUNC, MON_ORIG
    FROM    FECXP_PPTO_OPERA_ERP
    WHERE    VERSION_FE = V_VERSION_FE AND E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
            ;
    -- MES 10
    INSERT    INTO FECXP_PPTO_CONVERSION_ERP (
            E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
            MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS, VERSION_FE,
            MON_FUNC, MON_ORIG)
    SELECT    E_CODIGO,SECUENCIA_PTTO_CONVERSION.NEXTVAL, PERIODO_PPTO, 10, LIBRO_ID, VERSION_ID,
            MONEDA,TC_10,CODE_COMBINATION_ID, PPTO_10, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO', VERSION_FE,
            MON_FUNC, MON_ORIG
    FROM    FECXP_PPTO_OPERA_ERP
    WHERE    VERSION_FE = V_VERSION_FE AND E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
            ;
    -- MES 11
    INSERT    INTO FECXP_PPTO_CONVERSION_ERP (
            E_CODIGO,SECUENCIA_PTTO_CONVERSION,  PERIODO, MES, LIBRO_ID, VERSION_ID,
            MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS, VERSION_FE,
            MON_FUNC, MON_ORIG)
    SELECT    E_CODIGO,SECUENCIA_PTTO_CONVERSION.NEXTVAL, PERIODO_PPTO, 11, LIBRO_ID, VERSION_ID,
            MONEDA,TC_11,CODE_COMBINATION_ID, PPTO_11, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO', VERSION_FE,
            MON_FUNC, MON_ORIG
    FROM    FECXP_PPTO_OPERA_ERP
    WHERE    VERSION_FE = V_VERSION_FE AND E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
            ;
    -- MES 12
    INSERT    INTO FECXP_PPTO_CONVERSION_ERP (
            E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
            MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS, VERSION_FE,
            MON_FUNC, MON_ORIG)
    SELECT    E_CODIGO,SECUENCIA_PTTO_CONVERSION.NEXTVAL, PERIODO_PPTO, 12, LIBRO_ID, VERSION_ID,
            MONEDA,TC_12,CODE_COMBINATION_ID, PPTO_12, ORACLE_SEGMENTO1,
            ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
            ORACLE_SEGMENTO7, TO_NUMBER(TO_CHAR(SYSDATE,'YYYY')), TO_NUMBER(TO_CHAR(SYSDATE,'MM')), 'EXTRAIDO', VERSION_FE,
            MON_FUNC, MON_ORIG
    FROM    FECXP_PPTO_OPERA_ERP
    WHERE    VERSION_FE = V_VERSION_FE AND E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
            ;
    ------------------------------------ FIN MESES -------------------------------
    UPDATE    FECXP_PPTO_CONVERSION_ERP PFE
    SET        IMPORTE_LINEA = 0,
            PRESUPUESTO_ESTATUS = 'CONVERTIDO'
    WHERE EXISTS (
            SELECT 1
            FROM   FECXP_REGLAS_CONVERSION_PPTO RC
            WHERE  (PFE.ORACLE_SEGMENTO1 >= RC.REG_SEGMENTO1_INI OR RC.REG_SEGMENTO1_INI IS NULL)
            AND        (PFE.ORACLE_SEGMENTO1 <= RC.REG_SEGMENTO1_FIN OR RC.REG_SEGMENTO1_FIN IS NULL)
            AND        (PFE.ORACLE_SEGMENTO2 >= RC.REG_SEGMENTO2_INI OR RC.REG_SEGMENTO2_INI IS NULL)
            AND        (PFE.ORACLE_SEGMENTO2 <= RC.REG_SEGMENTO2_FIN OR RC.REG_SEGMENTO2_FIN IS NULL)
            AND        (PFE.ORACLE_SEGMENTO3 >= RC.REG_SEGMENTO3_INI OR RC.REG_SEGMENTO3_INI IS NULL)
            AND        (PFE.ORACLE_SEGMENTO3 <= RC.REG_SEGMENTO3_FIN OR RC.REG_SEGMENTO3_FIN IS NULL)
            AND        (PFE.ORACLE_SEGMENTO4 >= RC.REG_SEGMENTO4_INI OR RC.REG_SEGMENTO4_INI IS NULL)
            AND        (PFE.ORACLE_SEGMENTO4 <= RC.REG_SEGMENTO4_FIN OR RC.REG_SEGMENTO4_FIN IS NULL)
            AND        (PFE.ORACLE_SEGMENTO5 >= RC.REG_SEGMENTO5_INI OR RC.REG_SEGMENTO5_INI IS NULL)
            AND        (PFE.ORACLE_SEGMENTO5 <= RC.REG_SEGMENTO5_FIN OR RC.REG_SEGMENTO5_FIN IS NULL)
            AND        (PFE.ORACLE_SEGMENTO6 >= RC.REG_SEGMENTO6_INI OR RC.REG_SEGMENTO6_INI IS NULL)
            AND        (PFE.ORACLE_SEGMENTO6 <= RC.REG_SEGMENTO6_FIN OR RC.REG_SEGMENTO6_FIN IS NULL)
            AND        (PFE.ORACLE_SEGMENTO7 >= RC.REG_SEGMENTO7_INI OR RC.REG_SEGMENTO7_INI IS NULL)
            AND        (PFE.ORACLE_SEGMENTO7 <= RC.REG_SEGMENTO7_FIN OR RC.REG_SEGMENTO7_FIN IS NULL)
            AND        (PFE.PERIODO = RC.PERIODO OR RC.PERIODO IS NULL)
            AND        (PFE.MES >= RC.MES_INI OR RC.MES_INI IS NULL)
            AND        (PFE.MES <= RC.MES_FIN OR RC.MES_FIN IS NULL)
            AND        RC.PLATAFORMA = 'ORACLE'
            AND        RC.MES_ACUMULACION = 0)
    AND        VERSION_FE = V_VERSION_FE
            AND E_CODIGO = NVL (V_E_CODIGO, E_CODIGO);
    INSERT INTO FECXP_PPTO_COMBINA_ERP_TMP(E_CODIGO,LIBRO_ID,VERSION_ID,MONEDA,CODE_COMBINATION,MES_ACUMULACION)
    SELECT      distinct PA.E_CODIGO, PA.LIBRO_ID, PA.VERSION_ID, PA.MONEDA,PA.CODE_COMBINATION,RC.MES_ACUMULACION
    FROM      FECXP_PPTO_CONVERSION_ERP PA,  FECXP_REGLAS_CONVERSION_PPTO RC
    WHERE  (PA.ORACLE_SEGMENTO1 >= RC.REG_SEGMENTO1_INI OR RC.REG_SEGMENTO1_INI IS NULL)
        AND        (PA.ORACLE_SEGMENTO1 <= RC.REG_SEGMENTO1_FIN OR RC.REG_SEGMENTO1_FIN IS NULL)
        AND        (PA.ORACLE_SEGMENTO2 >= RC.REG_SEGMENTO2_INI OR RC.REG_SEGMENTO2_INI IS NULL)
        AND        (PA.ORACLE_SEGMENTO2 <= RC.REG_SEGMENTO2_FIN OR RC.REG_SEGMENTO2_FIN IS NULL)
        AND        (PA.ORACLE_SEGMENTO3 >= RC.REG_SEGMENTO3_INI OR RC.REG_SEGMENTO3_INI IS NULL)
        AND        (PA.ORACLE_SEGMENTO3 <= RC.REG_SEGMENTO3_FIN OR RC.REG_SEGMENTO3_FIN IS NULL)
        AND        (PA.ORACLE_SEGMENTO4 >= RC.REG_SEGMENTO4_INI OR RC.REG_SEGMENTO4_INI IS NULL)
        AND        (PA.ORACLE_SEGMENTO4 <= RC.REG_SEGMENTO4_FIN OR RC.REG_SEGMENTO4_FIN IS NULL)
        AND        (PA.ORACLE_SEGMENTO5 >= RC.REG_SEGMENTO5_INI OR RC.REG_SEGMENTO5_INI IS NULL)
        AND        (PA.ORACLE_SEGMENTO5 <= RC.REG_SEGMENTO5_FIN OR RC.REG_SEGMENTO5_FIN IS NULL)
        AND        (PA.ORACLE_SEGMENTO6 >= RC.REG_SEGMENTO6_INI OR RC.REG_SEGMENTO6_INI IS NULL)
        AND        (PA.ORACLE_SEGMENTO6 <= RC.REG_SEGMENTO6_FIN OR RC.REG_SEGMENTO6_FIN IS NULL)
        AND        (PA.ORACLE_SEGMENTO7 >= RC.REG_SEGMENTO7_INI OR RC.REG_SEGMENTO7_INI IS NULL)
        AND        (PA.ORACLE_SEGMENTO7 <= RC.REG_SEGMENTO7_FIN OR RC.REG_SEGMENTO7_FIN IS NULL)
        AND        (PA.PERIODO = RC.PERIODO OR RC.PERIODO IS NULL)
        AND        (PA.MES >= RC.MES_INI OR RC.MES_INI IS NULL)
        AND        (PA.MES <= RC.MES_FIN OR RC.MES_FIN IS NULL)
        AND        RC.PLATAFORMA = 'ORACLE'
        --AND        RC.MES_ACUMULACION >= PA.MES --modificado 07/12/2010 Para tomar en cuenta todos los meses en las politicas de acumulados
    AND    PA.VERSION_FE = V_VERSION_FE
    AND PA.E_CODIGO = NVL(V_E_CODIGO, E_CODIGO);
    INSERT INTO FECXP_PPTO_ACUMULADO_ERP_TMP(E_CODIGO,LIBRO_ID,VERSION_ID,MONEDA,CODE_COMBINATION,PERIODO_EXTRACCION,MES_EXTRACCION,IMPORTE_LINEA)
    SELECT      PA.E_CODIGO, PA.LIBRO_ID, PA.VERSION_ID, PA.MONEDA,PA.CODE_COMBINATION,PA.PERIODO_EXTRACCION,PA.MES_EXTRACCION,SUM (PA.IMPORTE_LINEA) AS IMPORTE_LINEA
    FROM      FECXP_PPTO_CONVERSION_ERP PA
    where EXISTS (
            SELECT 1
            FROM   FECXP_REGLAS_CONVERSION_PPTO RC
            WHERE  (PA.ORACLE_SEGMENTO1 >= RC.REG_SEGMENTO1_INI OR RC.REG_SEGMENTO1_INI IS NULL)
            AND        (PA.ORACLE_SEGMENTO1 <= RC.REG_SEGMENTO1_FIN OR RC.REG_SEGMENTO1_FIN IS NULL)
            AND        (PA.ORACLE_SEGMENTO2 >= RC.REG_SEGMENTO2_INI OR RC.REG_SEGMENTO2_INI IS NULL)
            AND        (PA.ORACLE_SEGMENTO2 <= RC.REG_SEGMENTO2_FIN OR RC.REG_SEGMENTO2_FIN IS NULL)
            AND        (PA.ORACLE_SEGMENTO3 >= RC.REG_SEGMENTO3_INI OR RC.REG_SEGMENTO3_INI IS NULL)
            AND        (PA.ORACLE_SEGMENTO3 <= RC.REG_SEGMENTO3_FIN OR RC.REG_SEGMENTO3_FIN IS NULL)
            AND        (PA.ORACLE_SEGMENTO4 >= RC.REG_SEGMENTO4_INI OR RC.REG_SEGMENTO4_INI IS NULL)
            AND        (PA.ORACLE_SEGMENTO4 <= RC.REG_SEGMENTO4_FIN OR RC.REG_SEGMENTO4_FIN IS NULL)
            AND        (PA.ORACLE_SEGMENTO5 >= RC.REG_SEGMENTO5_INI OR RC.REG_SEGMENTO5_INI IS NULL)
            AND        (PA.ORACLE_SEGMENTO5 <= RC.REG_SEGMENTO5_FIN OR RC.REG_SEGMENTO5_FIN IS NULL)
            AND        (PA.ORACLE_SEGMENTO6 >= RC.REG_SEGMENTO6_INI OR RC.REG_SEGMENTO6_INI IS NULL)
            AND        (PA.ORACLE_SEGMENTO6 <= RC.REG_SEGMENTO6_FIN OR RC.REG_SEGMENTO6_FIN IS NULL)
            AND        (PA.ORACLE_SEGMENTO7 >= RC.REG_SEGMENTO7_INI OR RC.REG_SEGMENTO7_INI IS NULL)
            AND        (PA.ORACLE_SEGMENTO7 <= RC.REG_SEGMENTO7_FIN OR RC.REG_SEGMENTO7_FIN IS NULL)
            AND        (PA.PERIODO = RC.PERIODO OR RC.PERIODO IS NULL)
            AND        (PA.MES >= RC.MES_INI OR RC.MES_INI IS NULL)
            AND        (PA.MES <= RC.MES_FIN OR RC.MES_FIN IS NULL)
            AND        RC.PLATAFORMA = 'ORACLE'
            --AND        RC.MES_ACUMULACION >= PA.MES --modificado 07/12/2010 Para tomar en cuenta todos los meses en las politicas de acumulados
            )
    AND    PA.VERSION_FE = V_VERSION_FE
    AND PA.E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
    GROUP BY PA.E_CODIGO, PA.LIBRO_ID, PA.VERSION_ID, PA.MONEDA,PA.CODE_COMBINATION, PA.PERIODO_EXTRACCION,PA.MES_EXTRACCION;
    /*Comentado 08052012 Por que no terminaba*/
    /*UPDATE FECXP_PPTO_CONVERSION_ERP up_table
    SET IMPORTE_LINEA = 0.00
    WHERE EXISTS(SELECT 1
                   FROM FECXP_PPTO_COMBINA_ERP_TMP COMB
                 WHERE COMB.E_CODIGO = up_table.E_CODIGO
                     and  COMB.LIBRO_ID = up_table.LIBRO_ID
                    and  COMB.VERSION_ID = up_table.VERSION_ID
                    and  COMB.MONEDA     = up_table.MONEDA
                    and  COMB.CODE_COMBINATION = up_table.CODE_COMBINATION
                    --and COMB.MES_ACUMULACION >= up_table.MES --modificado 07/12/2010 Para tomar en cuenta todos los meses en las politicas de acumulados
                    )
    AND    up_table.VERSION_FE = V_VERSION_FE
    AND up_table.E_CODIGO = NVL (V_E_CODIGO, E_CODIGO);*/
    FOR  CONTADOR IN C_CODE_COMB LOOP
    UPDATE FECXP_PPTO_CONVERSION_ERP up_table
    SET IMPORTE_LINEA = 0.00
    WHERE EXISTS(SELECT 1
                   FROM FECXP_PPTO_COMBINA_ERP_TMP COMB
                 WHERE COMB.E_CODIGO = up_table.E_CODIGO
                     and COMB.LIBRO_ID = up_table.LIBRO_ID
                    and  COMB.VERSION_ID = up_table.VERSION_ID
                    and  COMB.MONEDA     = up_table.MONEDA
                    and  COMB.CODE_COMBINATION = up_table.CODE_COMBINATION
                    AND  COMB.E_CODIGO =contador.e_codigo
                    )
    AND    up_table.VERSION_FE = V_VERSION_FE;
    END LOOP;
    /*UPDATE FECXP_PPTO_CONVERSION_ERP up_table
    SET IMPORTE_LINEA = (select IMPORTE_LINEA
                           FROM FECXP_PPTO_ACUMULADO_ERP_TMP acum
                          WHERE acum.E_CODIGO = up_table.E_CODIGO
                                and acum.LIBRO_ID = up_table.LIBRO_ID
                               and acum.VERSION_ID = up_table.VERSION_ID
                               and acum.MONEDA = up_table.MONEDA
                               and acum.CODE_COMBINATION =  up_table.CODE_COMBINATION),
        PRESUPUESTO_ESTATUS = 'CONVERTIDO'
    WHERE EXISTS(SELECT 1
                   FROM FECXP_PPTO_COMBINA_ERP_TMP COMB
                 WHERE COMB.E_CODIGO = up_table.E_CODIGO
                     and  COMB.LIBRO_ID = up_table.LIBRO_ID
                    and  COMB.VERSION_ID = up_table.VERSION_ID
                    and  COMB.MONEDA     = up_table.MONEDA
                    and  COMB.CODE_COMBINATION = up_table.CODE_COMBINATION
                    and  COMB.MES_ACUMULACION = up_table.MES)
    AND    up_table.VERSION_FE = V_VERSION_FE
    AND up_table.E_CODIGO = NVL (V_E_CODIGO, E_CODIGO);*/
    FOR  CONTADOR1 IN C_CODE_COMB LOOP
    UPDATE FECXP_PPTO_CONVERSION_ERP up_table
    SET IMPORTE_LINEA = (select IMPORTE_LINEA
                           FROM FECXP_PPTO_ACUMULADO_ERP_TMP acum
                          WHERE acum.E_CODIGO = up_table.E_CODIGO
                                and acum.LIBRO_ID = up_table.LIBRO_ID
                               and acum.VERSION_ID = up_table.VERSION_ID
                               and acum.MONEDA = up_table.MONEDA
                               and acum.CODE_COMBINATION =  up_table.CODE_COMBINATION
                               AND acum.E_CODIGO =contador1.e_codigo),
        PRESUPUESTO_ESTATUS = 'CONVERTIDO'
    WHERE EXISTS(SELECT 1
                   FROM FECXP_PPTO_COMBINA_ERP_TMP COMB
                 WHERE COMB.E_CODIGO = up_table.E_CODIGO
                     and  COMB.LIBRO_ID = up_table.LIBRO_ID
                    and  COMB.VERSION_ID = up_table.VERSION_ID
                    and  COMB.MONEDA     = up_table.MONEDA
                    and  COMB.CODE_COMBINATION = up_table.CODE_COMBINATION
                    and  COMB.MES_ACUMULACION = up_table.MES
                    and  COMB.E_CODIGO =contador1.e_codigo)
    AND    up_table.VERSION_FE = V_VERSION_FE;
    END LOOP;
    INSERT    INTO FECXP_PPTO_CONVERSION_ERP_ENC (
            VERSION_FE, COMENTARIO, USUARIO_ID, FECHA_EXTRACCION, VERSION_REGLAS, FECHA_VERSION_REGLAS, PERIODO_ORIGEN, VERSION_ORIGEN, ESTATUS_ORIGEN, VERSION_FE_ORIGEN)
    SELECT    VERSION_FE,V_COMENTARIO, V_USUARIO_ID, SYSDATE, 0, TO_DATE ('19000101', 'YYYYMMDD'), PERIODO_EXTRACCION, VERSION_ID, 'V', 0
    FROM    FECXP_PPTO_CONVERSION_ERP
    WHERE    VERSION_FE = V_VERSION_FE
    AND E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
    GROUP BY VERSION_FE, PERIODO_EXTRACCION, VERSION_ID;
    INSERT    INTO FECXP_PPTO_BITACORA_PROCESOS (
            SEC_EXT_BITACORA, PROCESO_ID, FECHA_EXT_ULT_EJECUCION, ESTATUS_EXT_ULT_EJECUCION, PERIODO_PPTO_ULT_EJECUCION, VERSION_PPTO_ULT_EJECUCION, ESTATUS_PPTO_ULT_EJECUCION, VERSION_PPTO_GENERADO)
    SELECT    SEC_EXT_BITACORA.NEXTVAL, 2, SYSDATE, 'CONVERSI
N EXITOSA', PERIODO_ORIGEN, VERSION_ORIGEN, ESTATUS_ORIGEN, 9
    FROM    (
    SELECT    PERIODO_ORIGEN, VERSION_ORIGEN, ESTATUS_ORIGEN
    FROM    FECXP_PPTO_OPERA_ERP_ENC
    WHERE    VERSION_FE = V_VERSION_FE
    GROUP BY PERIODO_ORIGEN, VERSION_ORIGEN, ESTATUS_ORIGEN);
    COMMIT;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20000,'No hay datos nuevos.');
END FECXP_PPTO_OP_A_PPTO_FE_ERP;
/
