CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_GENERA_VER_PPTO_ENC" (
	V_CUAL_ERP IN VARCHAR2
)
IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
	V_PERIODO_EXTRACCION INTEGER:= (TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY')));
	V_MES_EXTRACCION INTEGER:= (TO_NUMBER (TO_CHAR (SYSDATE, 'MM')));
	V_SIG_VERSION INTEGER;
	V_VERSION_FE_CANTIDAD INTEGER;
	V_VUELTAS INTEGER;
BEGIN
	IF V_CUAL_ERP = 'O' THEN
		-----------------------------------------------------------------------------------------------------------
		-- LIMPIA PPTO ERP OPERATIVO EN CASO DE HABERLO (NO DEBERIA)
		DELETE	FECXP_PPTO_OPERA_ERP
		WHERE	PERIODO_EXTRACCION = V_PERIODO_EXTRACCION
		AND		MES_DE_EXTRACCION = V_MES_EXTRACCION;
		COMMIT;
		DELETE	FECXP_PPTO_OPERA_ERP_ENC
		WHERE	PERIODO_EXTRACCION = V_PERIODO_EXTRACCION
		AND		MES_EXTRACCION = V_MES_EXTRACCION;
		COMMIT;
		-----------------------------------------------------------------------------------------------------------
		-- LIMPIA PPTO ERP CONVERTIDO EN CASO DE HABERLO (NO DEBERIA)
		DELETE	FECXP_PPTO_CONVERSION_ERP
		WHERE	PERIODO_EXTRACCION = V_PERIODO_EXTRACCION
		AND		MES_EXTRACCION = V_MES_EXTRACCION;
		COMMIT;
		DELETE	FECXP_PPTO_CONVERSION_ERP_ENC
		WHERE	PERIODO_EXTRACCION = V_PERIODO_EXTRACCION
		AND		MES_EXTRACCION = V_MES_EXTRACCION;
		COMMIT;
		-----------------------------------------------------------------------------------------------------------
		-- OBTIENE MAXIMO DE VERSIONES FE PARA PPTO ERP
		SELECT	VERSION_FE_CANTIDAD
		INTO	V_VERSION_FE_CANTIDAD
		FROM	FECXP_PPTO_VERSIONES_PARAMS
		WHERE	CUAL_ERP = 'O';
		-----------------------------------------------------------------------------------------------------------
		-- GENERA PPTO ERP
		SELECT	NVL (MAX (VERSION_FE) + 1, 1)
		INTO	V_SIG_VERSION
		FROM	FECXP_PPTO_OPERA_ERP_ENC;
		V_VUELTAS:= 1;
		LOOP
			INSERT	INTO FECXP_PPTO_OPERA_ERP_ENC (
					VERSION_FE, COMENTARIO, USUARIO_ID, FECHA_EXTRACCION, VERSION_REGLAS, FECHA_VERSION_REGLAS, PERIODO_ORIGEN, VERSION_ORIGEN, ESTATUS_ORIGEN, VERSION_FE_ORIGEN, ESTATUS_FE)
			VALUES	(
					V_SIG_VERSION, '', '', '', 0, TO_DATE ('19000101', 'YYYYMMDD'), 0, 0, '', 0, 'SIN APLICAR');
			V_SIG_VERSION:= V_SIG_VERSION + 1;
			V_VUELTAS:= V_VUELTAS + 1;
			EXIT WHEN V_VUELTAS > V_VERSION_FE_CANTIDAD;
		END LOOP;
		COMMIT;
	END IF;
	IF V_CUAL_ERP = 'S' THEN
		-----------------------------------------------------------------------------------------------------------
		-- LIMPIA PPTO SOIN OPERATIVO EN CASO DE HABERLO (NO DEBERIA)
		DELETE	FECXP_PPTO_OPERATIVO_SOIN
		WHERE	PERIODO_EXTRACCION = V_PERIODO_EXTRACCION
		AND		MES_EXTRACCION = V_MES_EXTRACCION;
		COMMIT;
		DELETE	FECXP_PPTO_OPERATIVO_SOIN_ENC
		WHERE	PERIODO_EXTRACCION = V_PERIODO_EXTRACCION
		AND		MES_EXTRACCION = V_MES_EXTRACCION;
		COMMIT;
		-----------------------------------------------------------------------------------------------------------
		-- LIMPIA PPTO SOIN CONVERTIDO EN CASO DE HABERLO (NO DEBERIA)
		DELETE	FECXP_PPTO_CONVERSION_SOIN
		WHERE	PERIODO_EXTRACCION = V_PERIODO_EXTRACCION
		AND		MES_EXTRACCION = V_MES_EXTRACCION;
		COMMIT;
		DELETE	FECXP_PPTO_CONVERSION_SOIN_ENC
		WHERE	PERIODO_EXTRACCION = V_PERIODO_EXTRACCION
		AND		MES_EXTRACCION = V_MES_EXTRACCION;
		COMMIT;
		-----------------------------------------------------------------------------------------------------------
		-- OBTIENE MAXIMO DE VERSIONES FE PARA PPTO SOIN
		SELECT	VERSION_FE_CANTIDAD
		INTO	V_VERSION_FE_CANTIDAD
		FROM	FECXP_PPTO_VERSIONES_PARAMS
		WHERE	CUAL_ERP = 'S';
		-----------------------------------------------------------------------------------------------------------
		-- GENERA PPTO SOIN
		SELECT	NVL (MAX (VERSION_FE) + 1, 1)
		INTO	V_SIG_VERSION
		FROM	FECXP_PPTO_OPERATIVO_SOIN_ENC;
		V_VUELTAS:= 1;
		LOOP
			INSERT	INTO FECXP_PPTO_OPERATIVO_SOIN_ENC (
					VERSION_FE, COMENTARIO, USUARIO_ID, FECHA_EXTRACCION, VERSION_REGLAS, FECHA_VERSION_REGLAS, PERIODO_ORIGEN, VERSION_ORIGEN, ESTATUS_ORIGEN, VERSION_FE_ORIGEN, ESTATUS_FE)
			VALUES	(
					V_SIG_VERSION, '', '', '', 0, TO_DATE ('19000101', 'YYYYMMDD'), 0, 0, '', 0, 'SIN APLICAR');
			V_SIG_VERSION:= V_SIG_VERSION + 1;
			V_VUELTAS:= V_VUELTAS + 1;
			EXIT WHEN V_VUELTAS > V_VERSION_FE_CANTIDAD;
		END LOOP;
		COMMIT;
	END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20000,'No hay datos nuevos.');
END FECXP_GENERA_VER_PPTO_ENC;
/
