CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_EJECUTA_PROCESOS" 
IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
      V_PROCESO_ID FECXP_PPTO_EXTRACCION_PARAMS.PROCESO_ID%TYPE;
    V_PROCESO_NOMBRE FECXP_PPTO_EXTRACCION_PARAMS.PROCESO_NOMBRE%TYPE;
    V_FECHA_EXT_SIG_EJECUCION FECXP_PPTO_EXTRACCION_PARAMS.FECHA_EXT_SIG_EJECUCION%TYPE;
    V_VERSION_FE_SIG_EJECUCION FECXP_PPTO_EXTRACCION_PARAMS.VERSION_FE_SIG_EJECUCION%TYPE;
    V_PERIODO_PPTO_SIG_EJECUCION FECXP_PPTO_EXTRACCION_PARAMS.PERIODO_PPTO_SIG_EJECUCION%TYPE;
    V_VERSION_PPTO_SIG_EJECUCION FECXP_PPTO_EXTRACCION_PARAMS.VERSION_PPTO_SIG_EJECUCION%TYPE;
    V_ESTATUS_PPTO_SIG_EJECUCION FECXP_PPTO_EXTRACCION_PARAMS.ESTATUS_PPTO_SIG_EJECUCION%TYPE;
    V_USUARIO_PPTO_SIG_EJECUCION FECXP_PPTO_EXTRACCION_PARAMS.USUARIO_PPTO_SIG_EJECUCION%TYPE;
    V_FECHA_EXT_ULT_EJECUCION FECXP_PPTO_EXTRACCION_PARAMS.FECHA_EXT_ULT_EJECUCION%TYPE;
    V_ESTATUS_EXT_ULT_EJECUCION FECXP_PPTO_EXTRACCION_PARAMS.ESTATUS_EXT_ULT_EJECUCION%TYPE;
    V_VERSION_FE_ULT_EJECUCION FECXP_PPTO_EXTRACCION_PARAMS.VERSION_FE_ULT_EJECUCION%TYPE;
    V_PERIODO_PPTO_ULT_EJECUCION FECXP_PPTO_EXTRACCION_PARAMS.PERIODO_PPTO_ULT_EJECUCION%TYPE;
    V_VERSION_PPTO_ULT_EJECUCION FECXP_PPTO_EXTRACCION_PARAMS.VERSION_PPTO_ULT_EJECUCION%TYPE;
    V_ESTATUS_PPTO_ULT_EJECUCION FECXP_PPTO_EXTRACCION_PARAMS.ESTATUS_PPTO_ULT_EJECUCION%TYPE;
    V_USUARIO_PPTO_ULT_EJECUCION FECXP_PPTO_EXTRACCION_PARAMS.USUARIO_PPTO_ULT_EJECUCION%TYPE;
    V_ATRIBUTO1    FECXP_PPTO_EXTRACCION_PARAMS.ATRIBUTO1%TYPE;
    V_ESTATUS_EJECUCION_PROCESO FECXP_PPTO_EXTRACCION_PARAMS.ESTATUS_PROCESO%TYPE;
    V_ATRIBUTO2    FECXP_PPTO_EXTRACCION_PARAMS.ATRIBUTO2%TYPE;
    /*20091030 V4 modificado para incluir la obtencion de cuentas contables ingresos*/
    /*20090818 V3 modificado para quitar la automatizacion de los pptos*/
    /* 20090801 V2 modificado para los avisos y la automatizacion*/
    /*V1 modificado para separar aperturacion de extraccion set*/
    --==  SE TOMA EN CUENTA TODOS MENOS EL PROCESO 2 QUE LO ACTUALIZA EL EJB ==--
    CURSOR    CURSOR_PROCESOS IS
    SELECT    PROCESO_ID, PROCESO_NOMBRE, FECHA_EXT_SIG_EJECUCION, VERSION_FE_SIG_EJECUCION, PERIODO_PPTO_SIG_EJECUCION, VERSION_PPTO_SIG_EJECUCION, ESTATUS_PPTO_SIG_EJECUCION, USUARIO_PPTO_SIG_EJECUCION, FECHA_EXT_ULT_EJECUCION, ESTATUS_EXT_ULT_EJECUCION, VERSION_FE_ULT_EJECUCION, PERIODO_PPTO_ULT_EJECUCION, VERSION_PPTO_ULT_EJECUCION, ESTATUS_PPTO_ULT_EJECUCION, USUARIO_PPTO_ULT_EJECUCION, ATRIBUTO1, ATRIBUTO2
    FROM    FECXP_PPTO_EXTRACCION_PARAMS
    WHERE    PROCESO_ID <> 2
    AND        ESTATUS_PROCESO = 'EN PROCESO'
    ORDER BY PROCESO_ID;
    --== Cursor para los reportes automaticos
    --==  SE TOMA EN CUENTA TODOS MENOS EL PROCESO 2 QUE LO ACTUALIZA EL EJB ==--
    CURSOR    CURSOR_AUTOM IS
    SELECT    PROCESO_ID, PROCESO_NOMBRE, ESTATUS_PPTO_SIG_EJECUCION, ATRIBUTO1, ESTATUS_PROCESO, USUARIO_PPTO_SIG_EJECUCION,ESTATUS_EXT_ULT_EJECUCION
    FROM    FECXP_PPTO_EXTRACCION_PARAMS
    WHERE    PROCESO_ID IN (11,12)
    ORDER BY PROCESO_ID;
    /*Bandera para detectar que cursor debe cerrar*/
    V_CONTADOR INTEGER:=0;
    V_PROC_ID INTEGER:=-1;
    V_ERRCODE NUMBER;
    V_ERRMSG VARCHAR2(255);
BEGIN
    --==  CAMBIA ESTATUS DEL PROCESO DE EJECUCION DE PROCESOS ==--
    UPDATE    FECXP_PPTO_EXTRACCION_PARAMS
    SET        ESTATUS_PROCESO = 'EN PROCESO'
    WHERE    PROCESO_ID = 0;
    COMMIT;
    --==  CLASIFICACION DE CUENTAS SESGUN POLITICAS DE CLASIFICACION DE FE ==--
    OPEN    CURSOR_PROCESOS;
    LOOP
        FETCH    CURSOR_PROCESOS
        INTO    V_PROCESO_ID, V_PROCESO_NOMBRE, V_FECHA_EXT_SIG_EJECUCION, V_VERSION_FE_SIG_EJECUCION, V_PERIODO_PPTO_SIG_EJECUCION, V_VERSION_PPTO_SIG_EJECUCION, V_ESTATUS_PPTO_SIG_EJECUCION, V_USUARIO_PPTO_SIG_EJECUCION, V_FECHA_EXT_ULT_EJECUCION, V_ESTATUS_EXT_ULT_EJECUCION, V_VERSION_FE_ULT_EJECUCION, V_PERIODO_PPTO_ULT_EJECUCION, V_VERSION_PPTO_ULT_EJECUCION, V_ESTATUS_PPTO_ULT_EJECUCION, V_USUARIO_PPTO_ULT_EJECUCION, V_ATRIBUTO1, V_ATRIBUTO2;
        EXIT    WHEN CURSOR_PROCESOS%NOTFOUND;
        V_CONTADOR:=1;
        IF V_PROCESO_ID = 1 THEN
            -- EXTRACCION PPTO ORACLE
            FECXP_GENERA_VER_PPTO_ERP (V_VERSION_FE_SIG_EJECUCION, V_USUARIO_PPTO_SIG_EJECUCION, V_ATRIBUTO1, V_PERIODO_PPTO_SIG_EJECUCION, V_VERSION_PPTO_SIG_EJECUCION, V_ESTATUS_PPTO_SIG_EJECUCION);
        END IF;
        -- IF V_PROCESO_ID = 2 THEN -- ES EL EJB DE PPTO SOIN
            -- EXTRACCION PPTO SOIN
        -- END IF;
        IF V_PROCESO_ID = 3 THEN
            -- COPIA PPTO ERP
            FECXP_COPIA_PPTO_ERP (V_VERSION_PPTO_SIG_EJECUCION, V_VERSION_FE_SIG_EJECUCION, V_USUARIO_PPTO_SIG_EJECUCION, V_ATRIBUTO1);
        END IF;
        IF V_PROCESO_ID = 4 THEN
            -- COPIA PPTO SOIN
            FECXP_COPIA_PPTO_SOIN (V_VERSION_PPTO_SIG_EJECUCION, V_VERSION_FE_SIG_EJECUCION, V_USUARIO_PPTO_SIG_EJECUCION, V_ATRIBUTO1);
        END IF;
        IF V_PROCESO_ID = 5 THEN
            -- GENERA ENCABEZADOS DE PPTO ERP
            FECXP_GENERA_VER_PPTO_ENC ('O');
        END IF;
        IF V_PROCESO_ID = 6 THEN
            -- GENERA ENCABEZADOS DE PPTO SOIN
            FECXP_GENERA_VER_PPTO_ENC ('S');
        END IF;
        IF V_PROCESO_ID = 7 THEN
            --dependiendo del reporte elegir su registro para bitacora
            IF V_ATRIBUTO2 = '1' OR V_ATRIBUTO2 = '2' OR V_ATRIBUTO2 = '3' THEN
                IF V_ATRIBUTO2 = '1' THEN
                    V_PROC_ID := 13;
                END IF;
                IF V_ATRIBUTO2 = '2' THEN
                    V_PROC_ID := 14;
                END IF;
                IF V_ATRIBUTO2 = '3' THEN
                    V_PROC_ID := 15;
                END IF;
            END IF;
            EXECUTE IMMEDIATE (V_ESTATUS_PPTO_SIG_EJECUCION);
        END IF;
        IF V_PROCESO_ID = 8 THEN
            -- CONVIERTE PRESUPUESTO
            IF V_ESTATUS_PPTO_SIG_EJECUCION = 'ORACLE' THEN
                FECXP_PPTO_OP_A_PPTO_FE_ERP (V_VERSION_FE_SIG_EJECUCION, V_USUARIO_PPTO_SIG_EJECUCION, V_ATRIBUTO1);
            ELSE
                FECXP_PPTO_OP_A_PPTO_FE_SOIN (V_VERSION_FE_SIG_EJECUCION, V_USUARIO_PPTO_SIG_EJECUCION, V_ATRIBUTO1);
            END IF;
        END IF;
        IF V_PROCESO_ID = 9 THEN
            -- Ejecuta la aperturacion de folios Oracle
                EXECUTE IMMEDIATE (V_ESTATUS_PPTO_SIG_EJECUCION);
        END IF;
        IF V_PROCESO_ID = 16 THEN
            -- Ejecuta la extraccion de cuentas de ingresos
                EXECUTE IMMEDIATE (V_ESTATUS_PPTO_SIG_EJECUCION);
        END IF;
        IF V_PROCESO_ID = 17 THEN
            -- Ejecuta la extraccion de cuentas de ingresos
                EXECUTE IMMEDIATE (V_ESTATUS_PPTO_SIG_EJECUCION);
        END IF;
         IF V_PROCESO_ID = 18 THEN
            -- Ejecuta la extraccion de cuentas de ingresos
                EXECUTE IMMEDIATE (V_ESTATUS_PPTO_SIG_EJECUCION);
        END IF;
        IF V_PROCESO_ID = 19 THEN
            -- Ejecuta la extraccion de cuentas de ingresos
                EXECUTE IMMEDIATE (V_ESTATUS_PPTO_SIG_EJECUCION);
        END IF;
        IF V_PROCESO_ID = 20 THEN
            -- Ejecuta la extraccion de HISTORICOS Y NO SET
                EXECUTE IMMEDIATE (V_ESTATUS_PPTO_SIG_EJECUCION);
        END IF;
        UPDATE    FECXP_PPTO_EXTRACCION_PARAMS
        SET        FECHA_EXT_SIG_EJECUCION = TO_DATE ('19000101', 'YYYYMMDD'),
                VERSION_FE_SIG_EJECUCION = 0,
                PERIODO_PPTO_SIG_EJECUCION = 2006,
                VERSION_PPTO_SIG_EJECUCION = 0,
                ESTATUS_PPTO_SIG_EJECUCION = 'INACTIVO',
                USUARIO_PPTO_SIG_EJECUCION = '',
                FECHA_EXT_ULT_EJECUCION = FECHA_EXT_SIG_EJECUCION,
                ESTATUS_EXT_ULT_EJECUCION = 'EXITOSO',
                VERSION_FE_ULT_EJECUCION = VERSION_FE_SIG_EJECUCION,
                PERIODO_PPTO_ULT_EJECUCION = PERIODO_PPTO_SIG_EJECUCION,
                VERSION_PPTO_ULT_EJECUCION = VERSION_PPTO_SIG_EJECUCION,
                ESTATUS_PPTO_ULT_EJECUCION = ESTATUS_PPTO_SIG_EJECUCION,
                USUARIO_PPTO_ULT_EJECUCION = USUARIO_PPTO_SIG_EJECUCION,
                ESTATUS_PROCESO = 'INACTIVO',
                FEC_FIN = SYSDATE,
                ATRIBUTO2 = ''
        WHERE    PROCESO_ID = V_PROCESO_ID;
        /*Actualizar bitacora por reporte*/
            IF V_ATRIBUTO2 = '1' OR V_ATRIBUTO2 = '2' OR V_ATRIBUTO2 = '3' THEN
                --ACTUALIZAR LA BITACORA DE CADA REPORTE
                UPDATE FECXP_PPTO_EXTRACCION_PARAMS
                SET (ESTATUS_EXT_ULT_EJECUCION, FEC_INI, FEC_FIN, USUARIO_PPTO_ULT_EJECUCION,ESTATUS_PPTO_ULT_EJECUCION, ATRIBUTO1, ATRIBUTO2) =
                    (SELECT ESTATUS_EXT_ULT_EJECUCION, FEC_INI, FEC_FIN, USUARIO_PPTO_ULT_EJECUCION, ESTATUS_PPTO_ULT_EJECUCION, ATRIBUTO1, ATRIBUTO2
                       FROM FECXP_PPTO_EXTRACCION_PARAMS
                       WHERE PROCESO_ID = 7)
                WHERE PROCESO_ID = V_PROC_ID;
            END IF;
        /*Para enviar mensaje de finalizacion en pantalla*/
        UPDATE FECXP_PPTO_EXTRACCION_PARAMS
        SET ALERTAR = 1
        WHERE    PROCESO_ID = V_PROCESO_ID
        AND        ALERTAR=2;
        COMMIT;
    END LOOP;
    CLOSE CURSOR_PROCESOS;
    UPDATE    FECXP_PPTO_EXTRACCION_PARAMS
    SET        ESTATUS_PROCESO = 'INACTIVO'
    WHERE    PROCESO_ID = 0;
    COMMIT;
    /*=============================================INICIA PARTE DE REPORTES AUTOMATICOS=======================================================*/
    UPDATE    FECXP_PPTO_EXTRACCION_PARAMS
    SET        ESTATUS_PROCESO = 'EN EJECUCION'
    WHERE    PROCESO_ID = 0;
    COMMIT;
    OPEN    CURSOR_AUTOM;
    LOOP
        FETCH    CURSOR_AUTOM
        INTO    V_PROCESO_ID, V_PROCESO_NOMBRE, V_ESTATUS_PPTO_SIG_EJECUCION, V_ATRIBUTO1,V_ESTATUS_EJECUCION_PROCESO, V_USUARIO_PPTO_SIG_EJECUCION, V_ESTATUS_EXT_ULT_EJECUCION;
        EXIT    WHEN CURSOR_AUTOM%NOTFOUND;
        V_CONTADOR:=2;
        /*Para el primer reporte*/
        IF V_ESTATUS_EJECUCION_PROCESO= 'EN EJECUCION' THEN
            -- Reportes Automaticos
            EXECUTE IMMEDIATE (V_ESTATUS_PPTO_SIG_EJECUCION);
            /*Marcar fin de proceso*/
            UPDATE    FECXP_PPTO_EXTRACCION_PARAMS
            SET        ESTATUS_PROCESO='AUTOMATICO',
                    ESTATUS_EXT_ULT_EJECUCION = 'EXITOSO',
                    FEC_FIN = SYSDATE
            WHERE    PROCESO_ID = V_PROCESO_ID;
            /*Para enviar mensaje de finalizacion en pantalla*/
            UPDATE FECXP_PPTO_EXTRACCION_PARAMS
            SET ALERTAR = 1
            WHERE    PROCESO_ID = V_PROCESO_ID
            AND        ALERTAR=2;
            COMMIT;
        END IF;
        IF V_ESTATUS_EJECUCION_PROCESO= 'EN ESPERA' THEN
            /*Marcar inicio del reporte para la pantalla */
            UPDATE    FECXP_PPTO_EXTRACCION_PARAMS
                SET        ESTATUS_PROCESO='EN EJECUCION',
                        FEC_INI = SYSDATE
            WHERE    PROCESO_ID = V_PROCESO_ID;
            commit;
            -- Reportes Automaticos
            EXECUTE IMMEDIATE (V_ESTATUS_PPTO_SIG_EJECUCION);
            /*Marcar fin de proceso*/
            UPDATE    FECXP_PPTO_EXTRACCION_PARAMS
            SET        ESTATUS_PROCESO='AUTOMATICO',
                    ESTATUS_EXT_ULT_EJECUCION = 'EXITOSO',
                    FEC_FIN = SYSDATE,
                    ATRIBUTO2 = ''
            WHERE    PROCESO_ID = V_PROCESO_ID;
            /*Para enviar mensaje de finalizacion en pantalla*/
            UPDATE FECXP_PPTO_EXTRACCION_PARAMS
            SET ALERTAR = 1
            WHERE    PROCESO_ID = V_PROCESO_ID
            AND        ALERTAR=2;
            COMMIT;
        END IF;
 END LOOP;
CLOSE CURSOR_AUTOM;
    UPDATE    FECXP_PPTO_EXTRACCION_PARAMS
    SET        ESTATUS_PROCESO = 'INACTIVO'
    WHERE    PROCESO_ID = 0;
    COMMIT;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
      IF V_CONTADOR=1 THEN
           CLOSE CURSOR_PROCESOS;
    ELSE
        CLOSE CURSOR_AUTOM;
    END IF;
    V_ERRCODE := SQLCODE;
    V_ERRMSG := SUBSTR(SQLERRM,1,254);
    UPDATE FECXP_PPTO_EXTRACCION_PARAMS
    SET ATRIBUTO2 = 'Error: ' || V_ERRCODE || ' - ' || V_ERRMSG || '.'
    WHERE PROCESO_ID=V_PROCESO_ID;
    COMMIT;
      IF V_PROCESO_ID = 7 THEN
        UPDATE FECXP_PPTO_EXTRACCION_PARAMS
        SET FEC_FIN = SYSDATE,
            ESTATUS_PROCESO = 'ERROR',
            ESTATUS_EXT_ULT_EJECUCION ='ERROR'
        WHERE PROCESO_ID=V_PROCESO_ID;
        IF V_ATRIBUTO2 = '1' OR V_ATRIBUTO2 = '2' OR V_ATRIBUTO2 = '3' THEN
                --ACTUALIZAR LA BITACORA DE CADA REPORTE
                UPDATE FECXP_PPTO_EXTRACCION_PARAMS
                SET (ESTATUS_EXT_ULT_EJECUCION, FEC_INI, FEC_FIN, USUARIO_PPTO_ULT_EJECUCION,ESTATUS_PPTO_ULT_EJECUCION, ATRIBUTO1, ATRIBUTO2) =
                    (SELECT ESTATUS_EXT_ULT_EJECUCION, FEC_INI, FEC_FIN, USUARIO_PPTO_ULT_EJECUCION, ESTATUS_PPTO_ULT_EJECUCION, ATRIBUTO1, ATRIBUTO2
                       FROM FECXP_PPTO_EXTRACCION_PARAMS
                       WHERE PROCESO_ID = 7)
                WHERE PROCESO_ID = V_PROC_ID;
            END IF;
        COMMIT;
    END IF;
    IF V_PROCESO_ID = 11  OR  V_PROCESO_ID = 12 THEN
        UPDATE FECXP_PPTO_EXTRACCION_PARAMS
        SET FEC_FIN = SYSDATE,
            ESTATUS_EXT_ULT_EJECUCION ='ERROR'
        WHERE PROCESO_ID = V_PROCESO_ID;
        --Para detener la ejecucion del resto
        UPDATE FECXP_PPTO_EXTRACCION_PARAMS
        SET ESTATUS_PROCESO= 'AUTOMATICO'
        WHERE PROCESO_ID IN (11,12);
        COMMIT;
    END IF;
    RAISE_APPLICATION_ERROR(-20000,'Error:' || SQLCODE || ' - ' || SQLERRM);
  WHEN OTHERS THEN
      IF V_CONTADOR=1 THEN
           CLOSE CURSOR_PROCESOS;
    ELSE
        CLOSE CURSOR_AUTOM;
    END IF;
    V_ERRCODE := SQLCODE;
    V_ERRMSG := SUBSTR(SQLERRM,1,254);
    UPDATE FECXP_PPTO_EXTRACCION_PARAMS
    SET ATRIBUTO2 = 'Error: ' || V_ERRCODE || ' - ' || V_ERRMSG || '.'
    WHERE PROCESO_ID=V_PROCESO_ID;
    COMMIT;
    COMMIT;
    /*Si hubo un error entonces detener su ejecucion, no incluye aperturacion para que siga reintentando*/
    IF V_PROCESO_ID = 7   THEN
        UPDATE FECXP_PPTO_EXTRACCION_PARAMS
        SET FEC_FIN = SYSDATE,
            ESTATUS_PROCESO = 'ERROR',
            ESTATUS_EXT_ULT_EJECUCION ='ERROR'
        WHERE PROCESO_ID=V_PROCESO_ID;
        IF V_ATRIBUTO2 = '1' OR V_ATRIBUTO2 = '2' OR V_ATRIBUTO2 = '3' THEN
                --ACTUALIZAR LA BITACORA DE CADA REPORTE
                UPDATE FECXP_PPTO_EXTRACCION_PARAMS
                SET (ESTATUS_EXT_ULT_EJECUCION, FEC_INI, FEC_FIN, USUARIO_PPTO_ULT_EJECUCION,ESTATUS_PPTO_ULT_EJECUCION, ATRIBUTO1, ATRIBUTO2) =
                    (SELECT ESTATUS_EXT_ULT_EJECUCION, FEC_INI, FEC_FIN, USUARIO_PPTO_ULT_EJECUCION, ESTATUS_PPTO_ULT_EJECUCION, ATRIBUTO1, ATRIBUTO2
                       FROM FECXP_PPTO_EXTRACCION_PARAMS
                       WHERE PROCESO_ID = 7)
                WHERE PROCESO_ID = V_PROC_ID;
        END IF;
        COMMIT;
    END IF;
    IF V_PROCESO_ID = 11  OR  V_PROCESO_ID = 12 THEN
        UPDATE FECXP_PPTO_EXTRACCION_PARAMS
        SET FEC_FIN = SYSDATE,
            ESTATUS_EXT_ULT_EJECUCION ='ERROR'
        WHERE PROCESO_ID = V_PROCESO_ID;
        --Para detener la ejecucion del resto
        UPDATE FECXP_PPTO_EXTRACCION_PARAMS
        SET ESTATUS_PROCESO= 'AUTOMATICO'
        WHERE PROCESO_ID IN (11,12);
        COMMIT;
    END IF;
    RAISE_APPLICATION_ERROR(-20000,'Error:' || SQLCODE || ' - ' || SQLERRM);
    /*No detener la aperturacion ya que con los reintentos podria ejecutarse bien cuando es not parsed*/
END FECXP_EJECUTA_PROCESOS;
/
