CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_LLENA_REP_MCOMP_SOIN" 
(
V_PERIODO 	  		  IN INT,
V_MES			  	  IN INT
)IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
/*DECLARE
	V_PERIODO      INT:= 2005;
	V_MES 	       INT:= 01;   */
	V_ID_SESION    VARCHAR2(25):= TO_CHAR(SYSDATE,'YYYYMMDD');
	V_CLA_FE_ID    FECXP_POLITICAS_SOIN.CLA_FE_ID%TYPE;
	V_POLITICA_SOIN_ID FECXP_POLITICAS_SOIN.POLITICA_SOIN_ID%TYPE;
	V_PRIORIDAD    FECXP_POLITICAS_SOIN.PRIORIDAD%TYPE;
	V_CTAM01_INI   FECXP_POLITICAS_SOIN.CTAM01_INI%TYPE;
	V_CTAM01_FIN   FECXP_POLITICAS_SOIN.CTAM01_FIN%TYPE;
	V_CTAM02_INI   FECXP_POLITICAS_SOIN.CTAM02_INI%TYPE;
	V_CTAM02_FIN   FECXP_POLITICAS_SOIN.CTAM02_FIN%TYPE;
	V_CTAM03_INI   FECXP_POLITICAS_SOIN.CTAM03_INI%TYPE;
	V_CTAM03_FIN   FECXP_POLITICAS_SOIN.CTAM03_FIN%TYPE;
	V_TIPO_INI     FECXP_POLITICAS_SOIN.TIPO_INI%TYPE;
	V_TIPO_FIN     FECXP_POLITICAS_SOIN.TIPO_FIN%TYPE;
	V_DIVISION_INI FECXP_POLITICAS_SOIN.DIVISION_INI%TYPE;
	V_DIVISION_FIN FECXP_POLITICAS_SOIN.DIVISION_FIN%TYPE;
	V_RUBRO_INI	   FECXP_POLITICAS_SOIN.RUBRO_INI%TYPE;
	V_RUBRO_FIN    FECXP_POLITICAS_SOIN.RUBRO_FIN%TYPE;
	CURSOR CURSOR_CLASIFICACION_FE IS
	SELECT	 CLA_FE_ID, PRIORIDAD, POLITICA_SOIN_ID, CTAM01_INI, CTAM01_FIN, CTAM02_INI, CTAM02_FIN,
			 CTAM03_INI, CTAM03_FIN, TIPO_INI, TIPO_FIN, DIVISION_INI, DIVISION_FIN, RUBRO_INI, RUBRO_FIN
	FROM	 FECXP_POLITICAS_SOIN
	WHERE  	 ACTIVA_REGLA = 1
	ORDER BY PRIORIDAD ASC;
BEGIN
	DELETE FROM FECXP_REP_MVCOMP_SOIN
	WHERE TO_NUMBER (TO_CHAR (FECHA_APLICACION, 'YYYY')) = V_PERIODO
	  AND TO_NUMBER (TO_CHAR (FECHA_APLICACION, 'MM')) = V_MES;
	--== SE INSERTAN LAS CUENTAS Q GENERARON FLUJO DE EFECTIVO ==--
	INSERT	INTO FECXP_CUENTAS_SOIN_CARATULA (E_CODIGO, CTAM01, CTAM02, CTAM03)
	SELECT	DISTINCT E_CODIGO, CS.CTAM01, CS.CTAM02, CS.CTAM03
	FROM	FECXP_MOV_COMPLE_SOIN CS
	WHERE   TO_NUMBER(TO_CHAR(CS.CGBFEC,'YYYY')) = V_PERIODO
	AND		TO_NUMBER(TO_CHAR(CS.CGBFEC,'MM')) = V_MES;
	--==  SE CLASIFICAN  ==--
	OPEN  CURSOR_CLASIFICACION_FE;
	LOOP
		--***** DEBUG *****-- V_EXISTE:= NULL;
		FETCH CURSOR_CLASIFICACION_FE
		INTO  V_CLA_FE_ID, V_PRIORIDAD, V_POLITICA_SOIN_ID, V_CTAM01_INI, V_CTAM01_FIN, V_CTAM02_INI, V_CTAM02_FIN, V_CTAM03_INI, V_CTAM03_FIN, V_TIPO_INI, V_TIPO_FIN, V_DIVISION_INI, V_DIVISION_FIN, V_RUBRO_INI, V_RUBRO_FIN;
        EXIT WHEN CURSOR_CLASIFICACION_FE%NOTFOUND;
		UPDATE	FECXP_CUENTAS_SOIN_CARATULA
		SET		CLA_FE_ID = V_CLA_FE_ID
	    WHERE	(CTAM01 >= NVL (V_CTAM01_INI, '0'))
		AND		(CTAM01 <= NVL (V_CTAM01_FIN, 'z'))
		AND		(CTAM02 >= NVL (V_CTAM02_INI, '0'))
		AND		(CTAM02 <= NVL (V_CTAM02_FIN, 'z'))
		AND		(CTAM03 >= NVL (V_CTAM03_INI, '0'))
		AND		(CTAM03 <= NVL (V_CTAM03_FIN, 'z'))
		AND		NVL (CLA_FE_ID, '|') = '|';
	END LOOP;
	CLOSE CURSOR_CLASIFICACION_FE;
INSERT INTO FECXP_REP_MVCOMP_SOIN
            (COD_EMPRESA, DES_EMPRESA, CLA_ID_FE, CLA_FE_DES, RUBRO, ORDEN_ID, FECHA_APLICACION,
			 MONEDA, TIPO_CAMBIO, IMPORTE_DEBITO, IMPORTE_CREDITO, CTAM01, CTAM02, CTAM03)
    SELECT  E.E_CODIGO, E.DES_EMPRESA,C.CLA_FE_ID, CFE.CLA_FE_DES, CFE.CLA_ATRIBUTO2, CFE.CLA_ATRIBUTO1,
   			MC.CGBFEC, M.MON_ORACLE, M.TIPO_CAMBIO, CASE WHEN MC.CGTTIP = 'D' THEN MC.CGTMON ELSE 0 END AS DEBITO,
			CASE WHEN MC.CGTTIP = 'C' THEN CGTMON ELSE 0 END AS CREDITO, MC.CTAM01, MC.CTAM02, MC.CTAM03
      FROM  FECXC_EMPRESAS E,
			FECXP_CLASIFICACION_FE CFE,
	 		FECXP_CUENTAS_SOIN_CARATULA C,
			FECXP_MOV_COMPLE_SOIN MC,
			FECXP_MONEDAS M
      WHERE E.E_CODIGO = MC.E_CODIGO
	    AND E.E_CODIGO = C.E_CODIGO
	    AND CFE.CLA_FE_ID = C.CLA_FE_ID
		AND M.MON_SYBASE = MC.MONEDA
		AND M.MES = MC.MESCOD
	    AND	C.CTAM01 = MC.CTAM01
        AND C.CTAM02 = MC.CTAM02
        AND C.CTAM03 = MC.CTAM03;
COMMIT;
END Fecxp_Llena_Rep_Mcomp_Soin;
/
