CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_POSTEA_FORECAST" 
(
	V_COM_MES1 IN VARCHAR2,
	V_COM_MES2 IN VARCHAR2,
	V_COM_MES3 IN VARCHAR2,
	V_COM_MES4 IN VARCHAR2,
	V_COM_MES5 IN VARCHAR2,
	V_COM_MES6 IN VARCHAR2,
	V_COM_MES7 IN VARCHAR2,
	V_COM_MES8 IN VARCHAR2,
	V_COM_MES9 IN VARCHAR2,
	V_COM_MES10 IN VARCHAR2,
	V_COM_MES11 IN VARCHAR2,
	V_COM_MES12 IN VARCHAR2,
	V_COM_FIJO1 IN VARCHAR2,
	V_COM_FIJO2 IN VARCHAR2
)
IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
	V_SALDO_FINAL_REAL VARCHAR2 (3):= 'SF2';
	V_SALDO_FINAL_FORECAST VARCHAR2 (3):= 'SF';
	V_SESION VARCHAR2 (25):= '';
	V_FACTOR NUMBER:= 1000;
	V_FACTOR_TITULO VARCHAR2 (100);
BEGIN
	V_FACTOR_TITULO:= CASE V_FACTOR
					  WHEN 1 THEN 'Montos en Pesos'
					  WHEN 100 THEN 'Cientos de Pesos'
					  WHEN 1000 THEN 'Miles de Pesos'
					  WHEN 1000000 THEN 'Millones de Pesos'
					  ELSE 'Montos x ' || V_FACTOR END;
	DELETE	FECXP_POSTEO
	WHERE	XML_DOC = 'CE_FE_001.xml';
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '<?xml version="1.0" encoding="UTF-8"?>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '<!DOCTYPE xliff PUBLIC "-//XLIFF//DTD XLIFF//EN" "http://www.oasis-open.org/committees/xliff/documents/xliff.dtd" >', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '<xliff version="1.0" xml:lang="es">', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', ' <Encabezado Titulo = "Forecast Flujo de Efectivo" Subtitulo = "'|| V_FACTOR_TITULO || ' nominales. ' || INITCAP (TO_CHAR (ADD_MONTHS(SYSDATE, -1), 'MONTH', 'NLS_DATE_LANGUAGE=SPANISH')) || ' (' || TO_CHAR (ADD_MONTHS(SYSDATE, -1), 'YYYY') || ')" Fecha = "' || TO_CHAR (SYSDATE, 'YYYYMMDD hh24mmss') || '">', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '	<mxp>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) SELECT	SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', XML_STRING, V_SESION
	FROM	(
			SELECT	'		<mes' || TO_CHAR (C.MES) || '>' || LTRIM (TO_CHAR (SUM (C.IMPORTE_LINEA * M.TIPO_CAMBIO / V_FACTOR), '9999999999999999999999999.9')) || '</mes' || TO_CHAR (C.MES) || '>' XML_STRING
			FROM	FECXP_MONEDAS M,
					FECXP_REAL_CARATULA C,
					FECXC_EMP_X_SEGMENTO A
			WHERE	C.CLA_FE_ID = CASE WHEN C.MES < TO_NUMBER (TO_CHAR (SYSDATE, 'MM')) THEN V_SALDO_FINAL_REAL ELSE V_SALDO_FINAL_FORECAST END
			AND		C.MONEDA = 'MXP'
			AND		C.PERIODO = TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'))
			AND		A.ID_SEGMENTO = 23
			AND		C.E_CODIGO = A.E_CODIGO
			AND		M.MON_ORACLE = C.MONEDA
			AND		M.PERIODO = C.PERIODO
			AND		M.MES = C.MES
			GROUP BY C.MES
			);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '	</mxp>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '	<otm>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) SELECT	SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', XML_STRING, V_SESION
	FROM	(
			SELECT	'		<mes' || TO_CHAR (C.MES) || '>' || LTRIM (TO_CHAR (SUM (C.IMPORTE_LINEA * M.TIPO_CAMBIO / V_FACTOR), '9999999999999999999999999.9')) || '</mes' || TO_CHAR (C.MES) || '>' XML_STRING
			FROM	FECXP_MONEDAS M,
					FECXP_REAL_CARATULA C,
					FECXC_EMP_X_SEGMENTO A
			WHERE	C.CLA_FE_ID = CASE WHEN C.MES < TO_NUMBER (TO_CHAR (SYSDATE, 'MM')) THEN V_SALDO_FINAL_REAL ELSE V_SALDO_FINAL_FORECAST END
			AND		C.MONEDA <> 'MXP'
			AND		C.PERIODO = TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'))
			AND		A.ID_SEGMENTO = 23
			AND		C.E_CODIGO = A.E_CODIGO
			AND		M.MON_ORACLE = C.MONEDA
			AND		M.PERIODO = C.PERIODO
			AND		M.MES = C.MES
			GROUP BY C.MES
			);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '	</otm>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '	<tot>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) SELECT	SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', XML_STRING, V_SESION
	FROM	(
			SELECT	'		<mes' || TO_CHAR (C.MES) || '>' || LTRIM (TO_CHAR (SUM (C.IMPORTE_LINEA * M.TIPO_CAMBIO / V_FACTOR), '9999999999999999999999999.9')) || '</mes' || TO_CHAR (C.MES) || '>' XML_STRING
			FROM	FECXP_MONEDAS M,
					FECXP_REAL_CARATULA C,
					FECXC_EMP_X_SEGMENTO A
			WHERE	C.CLA_FE_ID = CASE WHEN C.MES < TO_NUMBER (TO_CHAR (SYSDATE, 'MM')) THEN V_SALDO_FINAL_REAL ELSE V_SALDO_FINAL_FORECAST END
			AND		C.PERIODO = TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'))
			AND		A.ID_SEGMENTO = 23
			AND		C.E_CODIGO = A.E_CODIGO
			AND		M.MON_ORACLE = C.MONEDA
			AND		M.PERIODO = C.PERIODO
			AND		M.MES = C.MES
			GROUP BY C.MES
			);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '	</tot>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '	<com>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '		<mes1>' || V_COM_MES1 || '</mes1>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '		<mes2>' || V_COM_MES2 || '</mes2>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '		<mes3>' || V_COM_MES3 || '</mes3>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '		<mes4>' || V_COM_MES4 || '</mes4>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '		<mes5>' || V_COM_MES5 || '</mes5>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '		<mes6>' || V_COM_MES6 || '</mes6>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '		<mes7>' || V_COM_MES7 || '</mes7>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '		<mes8>' || V_COM_MES8 || '</mes8>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '		<mes9>' || V_COM_MES9 || '</mes9>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '		<mes10>' || V_COM_MES10 || '</mes10>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '		<mes11>' || V_COM_MES11 || '</mes11>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '		<mes12>' || V_COM_MES12 || '</mes12>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '	</com>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '	<mes>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) SELECT	SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', XML_STRING, V_SESION
	FROM	(
			SELECT	'		<mes' || TO_CHAR (C.MES) || '>' || TO_CHAR (TO_DATE (C.MES, 'MM'), 'MON', 'NLS_DATE_LANGUAGE=SPANISH') || '</mes' || TO_CHAR (C.MES) || '>' XML_STRING
			FROM	FECXP_MONEDAS M,
					FECXP_REAL_CARATULA C,
					FECXC_EMP_X_SEGMENTO A
			WHERE	C.PERIODO = TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'))
			AND		A.ID_SEGMENTO = 23
			AND		C.E_CODIGO = A.E_CODIGO
			AND		M.MON_ORACLE = C.MONEDA
			AND		M.PERIODO = C.PERIODO
			AND		M.MES = C.MES
			GROUP BY C.MES
			);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '	</mes>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '	<com>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '		<com1>' || V_COM_FIJO1 || '</com1>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '		<com2>' || V_COM_FIJO2 || '</com2>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '	</com>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', ' </Encabezado>', V_SESION);
	INSERT	INTO FECXP_POSTEO (ORDEN, XML_DOC, XML_STRING, SESION) VALUES (SEC_FECXP_POSTEO.NEXTVAL, 'CE_FE_001.xml', '</xliff>', V_SESION);
	COMMIT;
END FECXP_POSTEA_FORECAST;
/
