CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_RECALCULA_IMPORTACION" (
	V_MES_DESDE	IN VARCHAR2,
	V_PERIODO IN VARCHAR2,
	V_VERSION_FE_IMP IN VARCHAR2
)
IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
	V_E_CODIGO INT;
	V_ID_SESION VARCHAR(25) := TO_CHAR(SYSDATE,'DD-MM-YYYY');
	V_PERIODO_ACT INT:= TO_NUMBER (V_PERIODO);
	V_MES_ACT INT:= TO_NUMBER (V_MES_DESDE);
BEGIN
	----------------------------------------------------------------------------------------------------------------------------------------------
	--== EMPIEZA REAL ==--
	--== INICIALIZA LA TABLA ==--
	DELETE	FECXP_REAL_CARATULA C
	WHERE	C.E_CODIGO = NVL (V_E_CODIGO, C.E_CODIGO)
	AND		TO_DATE (TO_CHAR (C.PERIODO) || LPAD(C.MES, 2, '0') || '01', 'YYYYMMDD') >= TO_DATE (V_PERIODO || LPAD(V_MES_DESDE, 2, '0') || '01', 'YYYYMMDD')
	AND		ESTATUS = 'IMPORTADO';
	--== METE EL SALDO INICIAL ==--
	INSERT	INTO FECXP_REAL_CARATULA (
			E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
	SELECT	C.E_CODIGO, C.DES_EMPRESA, C.ID_SESION_RC,
			CASE WHEN C.MES = 12 THEN C.PERIODO + 1 ELSE C.PERIODO END,
			CASE WHEN C.MES = 12 THEN 1 ELSE C.MES + 1 END, C.MONEDA, C.TIPO_CAMBIO,
			'SI', 'SALDO INICIAL', C.IMPORTE_LINEA
	FROM	FECXP_REAL_CARATULA C
	WHERE	C.E_CODIGO = NVL (V_E_CODIGO, C.E_CODIGO)
	AND		C.PERIODO = CASE TO_NUMBER (V_MES_DESDE) WHEN 1 THEN TO_NUMBER (V_PERIODO) - 1 ELSE TO_NUMBER (V_PERIODO) END
	AND		C.MES = CASE TO_NUMBER (V_MES_DESDE) WHEN 1 THEN 12 ELSE TO_NUMBER (V_MES_DESDE) - 1 END
	AND		C.CLA_FE_ID = 'SF'
	AND		C.ESTATUS = 'IMPORTADO';
	--==  INICIA LA INCLUSION DE REGISTROS IMPORTADOS ==--
	INSERT	INTO FECXP_REAL_CARATULA (
			E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA, ESTATUS)
	SELECT	E.E_CODIGO, E.DES_EMPRESA, V_ID_SESION, TO_NUMBER (TO_CHAR (D.FECHA, 'YYYY')), D.MES, D.MONEDA_IMP, M.TIPO_CAMBIO, C.CLA_FE_ID, C.CLA_FE_DES, TO_NUMBER (C.CLA_ATRIBUTO3) * D.IMPORTE_LINEA, 'IMPORTADO'
	FROM	FECXP_MONEDAS M,
			FECXC_EMPRESAS E,
			FECXP_CLASIFICACION_FE C,
			FECXP_IMPORTACION_DATOS_HIST D
	WHERE	D.ESTATUS_ORIGEN = 'IMPORTADO'
	AND		E.E_CODIGO = NVL (V_E_CODIGO, E.E_CODIGO)
	AND		TO_DATE (TO_CHAR (D.FECHA, 'YYYY') || LPAD(D.MES, 2, '0') || '01', 'YYYYMMDD') >= TO_DATE (V_PERIODO || LPAD(V_MES_DESDE, 2, '0') || '01', 'YYYYMMDD')
	AND 	D.TIPO_IMPORTACION IN ('R', 'S')
	AND		E.E_CODIGO = D.E_EMPRESA_IMP
	AND		M.MON_ORACLE = D.MONEDA_IMP
	AND		M.MES = D.MES
	AND		M.PERIODO = TO_NUMBER (TO_CHAR (D.FECHA, 'YYYY'))
	AND		C.CLA_FE_ID = D.CLA_FE_ID_IMP;
	----------------------------------------------------------------------------------------------------------------------------------------------
	--== TERMINA REAL ==--
	----------------------------------------------------------------------------------------------------------------------------------------------
	--== EMPIEZA PPTO ==--
	DELETE	FECXP_PPTO_CARATULA
	WHERE	TO_DATE (TO_CHAR (PERIODO) || LPAD (MES, 2, '0') || '01', 'YYYYMMDD') = TO_DATE (TO_CHAR (V_PERIODO) || LPAD (V_MES_DESDE, 2, '0') || '01', 'YYYYMMDD')
	AND		E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
	AND		ESTATUS = 'IMPORTADO';
	--== METE EL SALDO INICIAL DE REALES SI V_MES_DESDE = 1 ==--
	INSERT	INTO FECXP_PPTO_CARATULA (
			E_CODIGO, DES_EMPRESA, ID_SESION_PC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA, ESTATUS)
	SELECT	E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA, ESTATUS
	FROM	FECXP_REAL_CARATULA
	WHERE	CLA_FE_ID = 'SI'
	AND		PERIODO = V_PERIODO
	AND		MES = V_MES_DESDE
	AND		V_MES_DESDE = 1
	AND		E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
	AND		ESTATUS = 'IMPORTADO';
	--== METE EL SALDO FINAL DEL MES PASADO DE PPTO SI V_MES_DESDE <> 1 ==--
	INSERT	INTO FECXP_PPTO_CARATULA (
			E_CODIGO, DES_EMPRESA, ID_SESION_PC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
	SELECT	C.E_CODIGO, C.DES_EMPRESA, C.ID_SESION_PC,
			CASE WHEN C.MES = 12 THEN C.PERIODO + 1 ELSE C.PERIODO END,
			CASE WHEN C.MES = 12 THEN 1 ELSE C.MES + 1 END, C.MONEDA, C.TIPO_CAMBIO,
			'SI', 'SALDO INICIAL', C.IMPORTE_LINEA
	FROM	FECXP_PPTO_CARATULA C
	WHERE	C.E_CODIGO = NVL (V_E_CODIGO, C.E_CODIGO)
	AND		C.PERIODO = CASE WHEN V_MES_DESDE = '1' THEN TO_NUMBER (V_PERIODO) - 1 ELSE TO_NUMBER (V_PERIODO) END
	AND		C.MES = CASE WHEN V_MES_DESDE = '1' THEN 12 ELSE TO_NUMBER (V_MES_DESDE) - 1 END
	AND		V_MES_DESDE <> 1
	AND		C.CLA_FE_ID = 'SF'
	AND		C.ESTATUS = 'IMPORTADO';
	--== INSERTA LOS REGISTROS IMPORTADOS ==--
	INSERT	INTO FECXP_PPTO_CARATULA (
			E_CODIGO, DES_EMPRESA, ID_SESION_PC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA, ESTATUS)
	SELECT	E.E_CODIGO, E.DES_EMPRESA, V_ID_SESION, V_PERIODO, D.MES, D.MONEDA_IMP, M.TIPO_CAMBIO, C.CLA_FE_ID, SUBSTR (C.CLA_FE_DES, 1, 25), TO_NUMBER (C.CLA_ATRIBUTO3) * D.IMPORTE_LINEA, 'IMPORTADO'
	FROM	FECXP_MONEDAS M,
			FECXC_EMPRESAS E,
			FECXP_CLASIFICACION_FE C,
			FECXP_IMPORTACION_DATOS_HIST D
	WHERE	D.MES >= V_MES_DESDE
	AND		D.TIPO_IMPORTACION IN ('S', 'P')
	AND		D.ATRIBUTO_3 = V_VERSION_FE_IMP
	AND		E.E_CODIGO = D.E_EMPRESA_IMP
	AND		M.MON_ORACLE = D.MONEDA_IMP
	AND		M.MES = D.MES
	AND		M.PERIODO = TO_NUMBER (TO_CHAR (D.FECHA, 'YYYY'))
	AND		C.CLA_FE_ID = D.CLA_FE_ID_IMP
	AND		E.E_CODIGO = NVL (V_E_CODIGO, E.E_CODIGO);
 	--== CUADRA EL PPTO INTEREMPRESAS ==--
	INSERT	INTO FECXP_PPTO_CARATULA (
			E_CODIGO, DES_EMPRESA, ID_SESION_PC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA, ESTATUS)
	SELECT	P.E_CODIGO, E.DES_EMPRESA, V_ID_SESION, P.PERIODO, P.MES, P.MONEDA, M.TIPO_CAMBIO, P.CLA_FE_ID, C.CLA_FE_DES, TO_NUMBER (C.CLA_ATRIBUTO3) * (P.IMPORTE_ING01 + P.IMPORTE_EGR01) DIFERENCIA, 'CALCULADO'
	FROM	(
				SELECT	PI.E_CODIGO, 'EGR01' CLA_FE_ID, PI.PERIODO, PI.MES, PI.MONEDA,
						PI.IMPORTE_LINEA IMPORTE_ING01,
						PE.IMPORTE_LINEA IMPORTE_EGR01
				FROM
						(
							SELECT	PI.E_CODIGO, PI.PERIODO, PI.MES, PI.MONEDA, SUM (PI.IMPORTE_LINEA) IMPORTE_LINEA
							FROM	FECXP_PPTO_CARATULA PI
							WHERE	PI.CLA_FE_ID = 'ING01'
							GROUP BY PI.E_CODIGO, PI.PERIODO, PI.MES, PI.MONEDA
						) PI,
						(
							SELECT	PE.E_CODIGO, PE.PERIODO, PE.MES, PE.MONEDA, SUM (PE.IMPORTE_LINEA) IMPORTE_LINEA
							FROM	FECXP_PPTO_CARATULA PE
							WHERE	PE.CLA_FE_ID = 'EGR01'
							GROUP BY PE.E_CODIGO, PE.PERIODO, PE.MES, PE.MONEDA
						) PE
				WHERE	PI.E_CODIGO = PE.E_CODIGO
				AND		PI.PERIODO = PE.PERIODO
				AND		PI.MES = PE.MES
				AND		PI.MONEDA = PE.MONEDA
				UNION ALL
				SELECT	PI.E_CODIGO, 'EGR01' CLA_FE_ID, PI.PERIODO, PI.MES, PI.MONEDA,
						PI.IMPORTE_LINEA IMPORTE_ING01, 0
				FROM	(
							SELECT	PI.E_CODIGO, PI.PERIODO, PI.MES, PI.MONEDA, PI.IMPORTE_LINEA
							FROM	FECXP_PPTO_CARATULA PI
							WHERE	PI.CLA_FE_ID = 'ING01'
							AND		NOT EXISTS (
													SELECT	PE.E_CODIGO, PE.PERIODO, PE.MES, PE.MONEDA, SUM (PE.IMPORTE_LINEA) IMPORTE_LINEA
													FROM	FECXP_PPTO_CARATULA PE
													WHERE	PE.CLA_FE_ID = 'EGR01'
													AND		PI.E_CODIGO = PE.E_CODIGO
													AND		PI.PERIODO = PE.PERIODO
													AND		PI.MES = PE.MES
													AND		PI.MONEDA = PE.MONEDA
													GROUP BY PE.E_CODIGO, PE.PERIODO, PE.MES, PE.MONEDA
												)
						) PI
				UNION ALL
				SELECT	PE.E_CODIGO, 'ING01' CLA_FE_ID, PE.PERIODO, PE.MES, PE.MONEDA,
						0, -1 * PE.IMPORTE_LINEA IMPORTE_EGR01
				FROM
						(
							SELECT	PE.E_CODIGO, PE.PERIODO, PE.MES, PE.MONEDA, 0, PE.IMPORTE_LINEA
							FROM	FECXP_PPTO_CARATULA PE
							WHERE	PE.CLA_FE_ID = 'EGR01'
							AND		NOT EXISTS (
													SELECT	PI.E_CODIGO, PI.PERIODO, PI.MES, PI.MONEDA, SUM (PI.IMPORTE_LINEA) IMPORTE_LINEA
													FROM	FECXP_PPTO_CARATULA PI
													WHERE	PI.CLA_FE_ID = 'ING01'
													AND		PI.E_CODIGO = PE.E_CODIGO
													AND		PI.PERIODO = PE.PERIODO
													AND		PI.MES = PE.MES
													AND		PI.MONEDA = PE.MONEDA
													GROUP BY PI.E_CODIGO, PI.PERIODO, PI.MES, PI.MONEDA
												)
						) PE
				) P,
			FECXP_MONEDAS M,
			FECXC_EMPRESAS E,
			FECXP_CLASIFICACION_FE C
	WHERE	M.PERIODO = TO_NUMBER (V_PERIODO)
	AND		M.MES >= TO_NUMBER (V_MES_DESDE)
	AND		P.E_CODIGO = E.E_CODIGO
	AND		M.MON_ORACLE = P.MONEDA
	AND		M.MES = P.MES
	AND		M.PERIODO = P.PERIODO
	AND		C.CLA_FE_ID = P.CLA_FE_ID
	AND		P.E_CODIGO = NVL (V_E_CODIGO, P.E_CODIGO);
	----------------------------------------------------------------------------------------------------------------------------------------------
	--== TERMINA PPTO ==--
	----------------------------------------------------------------------------------------------------------------------------------------------
	--== EMPIEZA CALCULO SALDOS FINALES ==--
	LOOP
		-- COMIENZA PPTO
		--== CALCULA DE SALDOS FINALES PARA LAS EMPRESAS QUE HAYAN GENERADO FE ==--
		INSERT	INTO FECXP_REAL_CARATULA (
				E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
		SELECT	C.E_CODIGO, C.DES_EMPRESA, C.ID_SESION_RC, C.PERIODO, C.MES, C.MONEDA, C.TIPO_CAMBIO, 'SF', 'SALDO FINAL', SUM (C.IMPORTE_LINEA)
		FROM	FECXP_CLASIFICACION_FE CF,
				FECXP_REAL_CARATULA C
		WHERE	C.E_CODIGO = NVL (V_E_CODIGO, C.E_CODIGO)
		AND		C.PERIODO = V_PERIODO_ACT
		AND		C.MES = V_MES_ACT
		AND		CF.GENERA_SALDO = 1
		AND		CF.CLA_FE_ID = C.CLA_FE_ID
		GROUP BY C.E_CODIGO, C.DES_EMPRESA, C.ID_SESION_RC, C.PERIODO, C.MES, C.MONEDA, C.TIPO_CAMBIO;
		-- INSERTA EL SALDO INICIAL DEL SIGUIENTE MES
		INSERT	INTO FECXP_REAL_CARATULA (
				E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
		SELECT	C.E_CODIGO, C.DES_EMPRESA, C.ID_SESION_RC,
				CASE WHEN C.MES = 12 THEN C.PERIODO + 1 ELSE C.PERIODO END,
				CASE WHEN C.MES = 12 THEN 1 ELSE C.MES + 1 END, C.MONEDA, C.TIPO_CAMBIO,
				'SI', 'SALDO INICIAL', C.IMPORTE_LINEA
		FROM	FECXP_REAL_CARATULA C
		WHERE	C.E_CODIGO = NVL (V_E_CODIGO, C.E_CODIGO)
		AND		PERIODO = V_PERIODO_ACT
		AND		MES = V_MES_ACT
		AND		CLA_FE_ID = 'SF';
		EXIT WHEN V_MES_ACT = TO_NUMBER (TO_CHAR(SYSDATE,'MM')) AND V_PERIODO_ACT = TO_NUMBER (TO_CHAR(SYSDATE,'YYYY'));
		-- TERMINA REAL
		-- COMIENZA PPTO
		--== CALCULA DE SALDOS FINALES PARA LAS EMPRESAS QUE HAYAN GENERADO FE ==--
		INSERT	INTO FECXP_PPTO_CARATULA (
				E_CODIGO, DES_EMPRESA, ID_SESION_PC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
		SELECT	E_CODIGO, DES_EMPRESA, ID_SESION_PC, PERIODO, MES, MONEDA, TIPO_CAMBIO, 'SF', 'SALDO FINAL', SUM (IMPORTE_LINEA)
		FROM	FECXP_CLASIFICACION_FE CF,
				FECXP_PPTO_CARATULA C
		WHERE	C.PERIODO = V_PERIODO_ACT
		AND		C.MES = V_MES_ACT
		AND		CF.GENERA_SALDO = 1
		AND		CF.CLA_FE_ID = C.CLA_FE_ID
		AND		CF.CLA_FE_ID <> 'SF'
		AND		C.E_CODIGO = NVL (V_E_CODIGO, C.E_CODIGO)
		GROUP BY C.E_CODIGO, C.DES_EMPRESA, C.ID_SESION_PC, C.PERIODO, C.MES, C.MONEDA, C.TIPO_CAMBIO;
		-- INSERTA EL SALDO INICIAL DEL SIGUIENTE MES
		INSERT	INTO FECXP_PPTO_CARATULA (
				E_CODIGO, DES_EMPRESA, ID_SESION_PC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
		SELECT	E_CODIGO, DES_EMPRESA, ID_SESION_PC,
				CASE WHEN MES = 12 THEN PERIODO + 1 ELSE PERIODO END,
				CASE WHEN MES = 12 THEN 1 ELSE MES + 1 END, MONEDA, TIPO_CAMBIO,
				'SI', 'SALDO INICIAL', IMPORTE_LINEA
		FROM	FECXP_PPTO_CARATULA
		WHERE	PERIODO = V_PERIODO_ACT
		AND		MES = V_MES_ACT
		AND		MES <> 1
		AND		E_CODIGO = NVL (V_E_CODIGO, E_CODIGO)
		AND		CLA_FE_ID = 'SF';
		-- TERMINA PPTO
		V_MES_ACT:= V_MES_ACT + 1;
		IF V_MES_ACT > 12 THEN
			V_MES_ACT:= '1';
			V_PERIODO_ACT:= V_PERIODO_ACT + 1;
		END IF;
	END LOOP;
	----------------------------------------------------------------------------------------------------------------------------------------------
	--== TERMINA CALCULO SALDOS FINALES ==--
	----------------------------------------------------------------------------------------------------------------------------------------------
	--== CALCULA SALDO SF2 ==--
	INSERT	INTO FECXP_REAL_CARATULA (
			E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA, ESTATUS)
	SELECT	C.E_CODIGO, C.DES_EMPRESA, C.ID_SESION_RC,
			C.PERIODO, C.MES, C.MONEDA, C.TIPO_CAMBIO, 'SF2', 'POSICION CON FACULTAD DECISION', SUM (C.IMPORTE_LINEA), 'CALCULADO' ESTATUS
	FROM	(
				SELECT	C.E_CODIGO, C.DES_EMPRESA, C.ID_SESION_RC, C.PERIODO, C.MES, C.MONEDA, C.TIPO_CAMBIO, C.CLA_FE_ID, C.CLA_FE_DES, SUM (C.IMPORTE_LINEA) IMPORTE_LINEA
				FROM	FECXP_REAL_CARATULA C
				WHERE	C.CLA_FE_ID = 'SF'
				GROUP BY C.E_CODIGO, C.DES_EMPRESA, C.ID_SESION_RC, C.PERIODO, C.MES, C.MONEDA, C.TIPO_CAMBIO, C.CLA_FE_ID, C.CLA_FE_DES
				UNION ALL
				SELECT	C.E_CODIGO, C.DES_EMPRESA, C.ID_SESION_RC, C.PERIODO, C.MES, C.MONEDA, C.TIPO_CAMBIO, C.CLA_FE_ID, C.CLA_FE_DES, SUM (C.IMPORTE_LINEA) IMPORTE_LINEA
				FROM	FECXP_REAL_CARATULA C,
						FECXP_CLASIFICACION_FE CF
				WHERE	CF.GENERA_SALDO = 0
				AND		CF.CLA_FE_ID NOT IN ('ING02', 'EGR02')
				AND		C.CLA_FE_ID = CF.CLA_FE_ID
				GROUP BY C.E_CODIGO, C.DES_EMPRESA, C.ID_SESION_RC, C.PERIODO, C.MES, C.MONEDA, C.TIPO_CAMBIO, C.CLA_FE_ID, C.CLA_FE_DES
			) C
	WHERE	C.E_CODIGO = NVL (V_E_CODIGO, C.E_CODIGO)
	AND		TO_DATE (TO_CHAR (C.PERIODO) || LPAD(C.MES, 2, '0') || '01', 'YYYYMMDD') >= TO_DATE (V_PERIODO || LPAD(V_MES_DESDE, 2, '0') || '01', 'YYYYMMDD')
	GROUP BY C.E_CODIGO, C.DES_EMPRESA, C.ID_SESION_RC, C.PERIODO, C.MES, C.MONEDA, C.TIPO_CAMBIO;
	COMMIT;
EXCEPTION
   WHEN NO_DATA_FOUND THEN
   RAISE_APPLICATION_ERROR(-20000,'NO HAY DATOS NUEVOS.');
END FECXP_RECALCULA_IMPORTACION;
/
