CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_LLENA_REP_PPTO_ERP" 
(
V_PERIODO 	  		  IN INT,
V_MES			  	  IN INT
)IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
/*DECLARE
	V_PERIODO INT:= TO_NUMBER(TO_CHAR(SYSDATE,'YYYY'));
	V_MES INT:= TO_NUMBER(TO_CHAR(SYSDATE,'MM'));*/
	V_ID_SESION NUMBER:= TO_NUMBER (TO_CHAR (SYSDATE,'YYYYMMDD'));
 	V_CLA_FE_ID FECXP_POLITICAS_ERP.CLA_FE_ID%TYPE;
	V_POLITICA_ERP_ID FECXP_POLITICAS_ERP.POLITICA_ERP_ID%TYPE;
	V_PRIORIDAD FECXP_POLITICAS_ERP.PRIORIDAD%TYPE;
	V_ORA_S1_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_INI%TYPE;
	V_ORA_S1_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_FIN%TYPE;
	V_ORA_S2_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_INI%TYPE;
	V_ORA_S2_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_FIN%TYPE;
	V_ORA_S3_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_INI%TYPE;
	V_ORA_S3_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_FIN%TYPE;
	V_ORA_S4_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_INI%TYPE;
	V_ORA_S4_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_FIN%TYPE;
	V_ORA_S5_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_INI%TYPE;
	V_ORA_S5_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_FIN%TYPE;
	V_ORA_S6_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_INI%TYPE;
	V_ORA_S6_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_FIN%TYPE;
	V_ORA_S7_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_INI%TYPE;
	V_ORA_S7_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_FIN%TYPE;
	CURSOR CURSOR_CLASIFICACION_FE IS
	SELECT CLA_FE_ID, POLITICA_ERP_ID, PRIORIDAD, ORACLE_SEGMENTO1_INI, ORACLE_SEGMENTO1_FIN, ORACLE_SEGMENTO2_INI, ORACLE_SEGMENTO2_FIN, ORACLE_SEGMENTO3_INI, ORACLE_SEGMENTO3_FIN, ORACLE_SEGMENTO4_INI, ORACLE_SEGMENTO4_FIN, ORACLE_SEGMENTO5_INI, ORACLE_SEGMENTO5_FIN, ORACLE_SEGMENTO6_INI, ORACLE_SEGMENTO6_FIN, ORACLE_SEGMENTO7_INI, ORACLE_SEGMENTO7_FIN
	  FROM FECXP_POLITICAS_ERP
	 WHERE ACTIVA_REGLA = 1
	 ORDER BY PRIORIDAD ASC;
BEGIN
DELETE FECXP_REP_PPTO_ERP;
INSERT INTO FECXP_CUENTAS_ERP_CARATULA (E_CODIGO, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
	   								   	ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7)
SELECT DISTINCT E_CODIGO, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3,ORACLE_SEGMENTO4,
	   			ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
           FROM FECXP_PPTO_CONVERSION_ERP
		  WHERE PERIODO_EXTRACCION = V_PERIODO
		    AND	MES_EXTRACCION = V_MES;
OPEN  CURSOR_CLASIFICACION_FE;
	LOOP
		--***** DEBUG *****-- V_EXISTE:= NULL;
		FETCH CURSOR_CLASIFICACION_FE
		INTO  V_CLA_FE_ID, V_PRIORIDAD, V_POLITICA_ERP_ID, V_ORA_S1_INI, V_ORA_S1_FIN, V_ORA_S2_INI, V_ORA_S2_FIN, V_ORA_S3_INI, V_ORA_S3_FIN, V_ORA_S4_INI, V_ORA_S4_FIN, V_ORA_S5_INI, V_ORA_S5_FIN, V_ORA_S6_INI, V_ORA_S6_FIN, V_ORA_S7_INI, V_ORA_S7_FIN;
        EXIT WHEN CURSOR_CLASIFICACION_FE%NOTFOUND;
	UPDATE	FECXP_CUENTAS_ERP_CARATULA
	   SET	CLA_FE_ID = V_CLA_FE_ID
	WHERE	(ORACLE_SEGMENTO1 >= NVL (V_ORA_S1_INI, '0'))
	AND		(ORACLE_SEGMENTO1 <= NVL (V_ORA_S1_FIN, 'z'))
	AND		(ORACLE_SEGMENTO2 >= NVL (V_ORA_S2_INI, '0'))
	AND		(ORACLE_SEGMENTO2 <= NVL (V_ORA_S2_FIN, 'z'))
	AND		(ORACLE_SEGMENTO3 >= NVL (V_ORA_S3_INI, '0'))
	AND		(ORACLE_SEGMENTO3 <= NVL (V_ORA_S3_FIN, 'z'))
	AND		(ORACLE_SEGMENTO4 >= NVL (V_ORA_S4_INI, '0'))
	AND		(ORACLE_SEGMENTO4 <= NVL (V_ORA_S4_FIN, 'z'))
	AND		(ORACLE_SEGMENTO5 >= NVL (V_ORA_S5_INI, '0'))
	AND		(ORACLE_SEGMENTO5 <= NVL (V_ORA_S5_FIN, 'z'))
	AND		(ORACLE_SEGMENTO6 >= NVL (V_ORA_S6_INI, '0'))
	AND		(ORACLE_SEGMENTO6 <= NVL (V_ORA_S6_FIN, 'z'))
	AND		(ORACLE_SEGMENTO7 >= NVL (V_ORA_S7_INI, '0'))
	AND		(ORACLE_SEGMENTO7 <= NVL (V_ORA_S7_FIN, 'z'))
	AND 	NVL (CLA_FE_ID, '|') = '|';
END LOOP;
CLOSE CURSOR_CLASIFICACION_FE;
INSERT INTO FECXP_REP_PPTO_ERP (
	   COD_EMPRESA, DES_EMPRESA, RUBRO, ORDEN_ID, CLA_ID_FE, CLA_FE_DES, ID_SESION,
	   PERIODO, MES, MONEDA, TIPO_CAMBIO, IMPORTE_LINEA,
	   ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5,
	   ORACLE_SEGMENTO6, ORACLE_SEGMENTO7)
SELECT	EM.E_CODIGO, EM.DES_EMPRESA, CF.CLA_ATRIBUTO2, TO_NUMBER (CF.CLA_ATRIBUTO1), CF.CLA_FE_ID, CF.CLA_FE_DES, V_ID_SESION,
		PP.PERIODO, PP.MES, PP.MONEDA, M.TIPO_CAMBIO, PP.IMPORTE_LINEA,
		PP.ORACLE_SEGMENTO1, PP.ORACLE_SEGMENTO2, PP.ORACLE_SEGMENTO3, PP.ORACLE_SEGMENTO4, PP.ORACLE_SEGMENTO5,
		PP.ORACLE_SEGMENTO6, PP.ORACLE_SEGMENTO7
FROM	FECXC_EMPRESAS EM,
		FECXP_CLASIFICACION_FE CF,
		FECXP_CUENTAS_ERP_CARATULA C,
		FECXP_PPTO_CONVERSION_ERP PP,
		FECXP_MONEDAS M
WHERE	 PP.PERIODO_EXTRACCION = V_PERIODO
AND 	 PP.MES_EXTRACCION = PP.MES
AND		 EM.E_CODIGO = C.E_CODIGO
AND		 CF.CLA_FE_ID = C.CLA_FE_ID
AND		 M.MES = PP.MES
AND 	 C.ORACLE_SEGMENTO1 = PP.ORACLE_SEGMENTO1
AND	 	 C.ORACLE_SEGMENTO2 = PP.ORACLE_SEGMENTO2
AND		 C.ORACLE_SEGMENTO3 = PP.ORACLE_SEGMENTO3
AND		 C.ORACLE_SEGMENTO4 = PP.ORACLE_SEGMENTO4
AND		 C.ORACLE_SEGMENTO5 = PP.ORACLE_SEGMENTO5
AND		 C.ORACLE_SEGMENTO6 = PP.ORACLE_SEGMENTO6
AND		 C.ORACLE_SEGMENTO7 = PP.ORACLE_SEGMENTO7;
END;
/
