CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_LLENA_REP_CONCIL_ERP" 
(
V_PERIODO 	  		  IN INT,
V_MES			  	  IN INT
)IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
/*DECLARE
	V_PERIODO      INT:= 2005;
	V_MES 	       INT:= 01;   */
 	V_CLA_FE_ID FECXP_POLITICAS_ERP.CLA_FE_ID%TYPE;
	V_POLITICA_ERP_ID FECXP_POLITICAS_ERP.POLITICA_ERP_ID%TYPE;
	V_PRIORIDAD FECXP_POLITICAS_ERP.PRIORIDAD%TYPE;
	V_ORA_S1_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_INI%TYPE;
	V_ORA_S1_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_FIN%TYPE;
	V_ORA_S2_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_INI%TYPE;
	V_ORA_S2_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_FIN%TYPE;
	V_ORA_S3_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_INI%TYPE;
	V_ORA_S3_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_FIN%TYPE;
	V_ORA_S4_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_INI%TYPE;
	V_ORA_S4_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_FIN%TYPE;
	V_ORA_S5_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_INI%TYPE;
	V_ORA_S5_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_FIN%TYPE;
	V_ORA_S6_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_INI%TYPE;
	V_ORA_S6_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_FIN%TYPE;
	V_ORA_S7_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_INI%TYPE;
	V_ORA_S7_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_FIN%TYPE;
	V_CLA_FE_DES FECXP_CLASIFICACION_FE.CLA_FE_DES%TYPE;
	CURSOR CURSOR_CLASIFICACION_FE IS
	SELECT	 CLA_FE_ID, POLITICA_ERP_ID, PRIORIDAD, ORACLE_SEGMENTO1_INI, ORACLE_SEGMENTO1_FIN, ORACLE_SEGMENTO2_INI, ORACLE_SEGMENTO2_FIN, ORACLE_SEGMENTO3_INI, ORACLE_SEGMENTO3_FIN, ORACLE_SEGMENTO4_INI, ORACLE_SEGMENTO4_FIN, ORACLE_SEGMENTO5_INI, ORACLE_SEGMENTO5_FIN, ORACLE_SEGMENTO6_INI, ORACLE_SEGMENTO6_FIN, ORACLE_SEGMENTO7_INI, ORACLE_SEGMENTO7_FIN
	FROM	 FECXP_POLITICAS_ERP
	WHERE  	 ACTIVA_REGLA = 1
	ORDER BY PRIORIDAD ASC;
BEGIN
--TRUNCATE TABLE FECXP_REP_CONCILIACION_ERP;
--DELETE FROM FECXP_REP_CONCILIACION_ERP
--WHERE FECHA_APLICACION > = TO_DATE('01-'||V_MES||'-'||V_PERIODO,'DD-MM-YYYY');
COMMIT;
INSERT INTO FECXP_REP_CONCILIACION_ERP_TMP (ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
	   								   	ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ATRIBUTO1)
SELECT DISTINCT RE.ORACLE_SEGMENTO1, RE.ORACLE_SEGMENTO2, RE.ORACLE_SEGMENTO3, RE.ORACLE_SEGMENTO4,
	   			RE.ORACLE_SEGMENTO5, RE.ORACLE_SEGMENTO6, RE.ORACLE_SEGMENTO7, RE.MONEDA
           FROM FECXP_REP_REAL_ERP RE
	      WHERE TO_NUMBER(TO_CHAR(FECHA_APLICACION,'MM')) = V_MES
		    AND TO_NUMBER(TO_CHAR(FECHA_APLICACION,'YYYY')) = V_PERIODO
	   ORDER BY RE.ORACLE_SEGMENTO1;
---  SE ACTUALIZA EL ID DE FLUJO DE EFECTIVO   ---
OPEN  CURSOR_CLASIFICACION_FE;
	LOOP
		FETCH CURSOR_CLASIFICACION_FE
		INTO  V_CLA_FE_ID, V_PRIORIDAD, V_POLITICA_ERP_ID, V_ORA_S1_INI, V_ORA_S1_FIN, V_ORA_S2_INI, V_ORA_S2_FIN, V_ORA_S3_INI, V_ORA_S3_FIN, V_ORA_S4_INI, V_ORA_S4_FIN, V_ORA_S5_INI, V_ORA_S5_FIN, V_ORA_S6_INI, V_ORA_S6_FIN, V_ORA_S7_INI, V_ORA_S7_FIN;
        EXIT WHEN CURSOR_CLASIFICACION_FE%NOTFOUND;
	UPDATE	FECXP_REP_CONCILIACION_ERP_TMP
	   SET	CLA_ID_FE = V_CLA_FE_ID
	WHERE	(ORACLE_SEGMENTO1 >= NVL (V_ORA_S1_INI, '0'))
	AND		(ORACLE_SEGMENTO1 <= NVL (V_ORA_S1_FIN, 'z'))
	AND		(ORACLE_SEGMENTO2 >= NVL (V_ORA_S2_INI, '0'))
	AND		(ORACLE_SEGMENTO2 <= NVL (V_ORA_S2_FIN, 'z'))
	AND		(ORACLE_SEGMENTO3 >= NVL (V_ORA_S3_INI, '0'))
	AND		(ORACLE_SEGMENTO3 <= NVL (V_ORA_S3_FIN, 'z'))
	AND		(ORACLE_SEGMENTO4 >= NVL (V_ORA_S4_INI, '0'))
	AND		(ORACLE_SEGMENTO4 <= NVL (V_ORA_S4_FIN, 'z'))
	AND		(ORACLE_SEGMENTO5 >= NVL (V_ORA_S5_INI, '0'))
	AND		(ORACLE_SEGMENTO5 <= NVL (V_ORA_S5_FIN, 'z'))
	AND		(ORACLE_SEGMENTO6 >= NVL (V_ORA_S6_INI, '0'))
	AND		(ORACLE_SEGMENTO6 <= NVL (V_ORA_S6_FIN, 'z'))
	AND		(ORACLE_SEGMENTO7 >= NVL (V_ORA_S7_INI, '0'))
	AND		(ORACLE_SEGMENTO7 <= NVL (V_ORA_S7_FIN, 'z'))
	AND 	NVL (CLA_ID_FE, '|') = '|';
END LOOP;
CLOSE CURSOR_CLASIFICACION_FE;
			---------------------			---------------------			--------------------
			---							DESCRIPCION DE CLASIFICACION FE						----
			---------------------			---------------------			---------------------
UPDATE FECXP_REP_CONCILIACION_ERP_TMP T
	   	   SET T.CLA_FE_DES = (SELECT CF.CLA_FE_DES FROM FECXP_CLASIFICACION_FE CF
	       	   				    WHERE T.CLA_ID_FE = CF.CLA_FE_ID);
			---------------------			---------------------			--------------------
			---							DESCRIPCION DE SEGMENTOS ORACLE						----
			---------------------			---------------------			---------------------
UPDATE FECXP_REP_CONCILIACION_ERP_TMP T
   SET T.ORACLE_SEGMENTO1_DES = (SELECT A.DESCRIPTION
           FROM FND_FLEX_VALUES_TL@ERP_PROD A, FND_FLEX_VALUES@ERP_PROD B
          WHERE B.FLEX_VALUE_SET_ID = '1007915'
            AND A.FLEX_VALUE_ID = B.FLEX_VALUE_ID
            AND A.LANGUAGE = 'ESA'
            AND ENABLED_FLAG = 'Y'
            AND B.SUMMARY_FLAG = 'N'
			AND T.ORACLE_SEGMENTO1 = A.FLEX_VALUE_MEANING);
UPDATE FECXP_REP_CONCILIACION_ERP_TMP T
   SET T.ORACLE_SEGMENTO2_DES = (SELECT A.DESCRIPTION
           FROM FND_FLEX_VALUES_TL@ERP_PROD A, FND_FLEX_VALUES@ERP_PROD B
          WHERE B.FLEX_VALUE_SET_ID = '1007916'
            AND A.FLEX_VALUE_ID = B.FLEX_VALUE_ID
            AND A.LANGUAGE = 'ESA'
            AND ENABLED_FLAG = 'Y'
            AND B.SUMMARY_FLAG = 'N'
			AND T.ORACLE_SEGMENTO2 = A.FLEX_VALUE_MEANING);
UPDATE FECXP_REP_CONCILIACION_ERP_TMP T
   SET T.ORACLE_SEGMENTO3_DES = (SELECT A.DESCRIPTION
           FROM FND_FLEX_VALUES_TL@ERP_PROD A, FND_FLEX_VALUES@ERP_PROD B
          WHERE B.FLEX_VALUE_SET_ID = '1007917'
            AND A.FLEX_VALUE_ID = B.FLEX_VALUE_ID
            AND A.LANGUAGE = 'ESA'
            AND ENABLED_FLAG = 'Y'
            AND B.SUMMARY_FLAG = 'N'
			AND T.ORACLE_SEGMENTO3 = A.FLEX_VALUE_MEANING);
UPDATE FECXP_REP_CONCILIACION_ERP_TMP T
   SET T.ORACLE_SEGMENTO4_DES = (SELECT A.DESCRIPTION
           FROM FND_FLEX_VALUES_TL@ERP_PROD A, FND_FLEX_VALUES@ERP_PROD B
          WHERE B.FLEX_VALUE_SET_ID = '1007918'
            AND A.FLEX_VALUE_ID = B.FLEX_VALUE_ID
            AND A.LANGUAGE = 'ESA'
            AND ENABLED_FLAG = 'Y'
            AND B.SUMMARY_FLAG = 'N'
			AND T.ORACLE_SEGMENTO4 = A.FLEX_VALUE_MEANING);
UPDATE FECXP_REP_CONCILIACION_ERP_TMP T
   SET T.ORACLE_SEGMENTO5_DES = (SELECT A.DESCRIPTION
           FROM FND_FLEX_VALUES_TL@ERP_PROD A, FND_FLEX_VALUES@ERP_PROD B
          WHERE B.FLEX_VALUE_SET_ID = '1007919'
            AND A.FLEX_VALUE_ID = B.FLEX_VALUE_ID
            AND A.LANGUAGE = 'ESA'
            AND ENABLED_FLAG = 'Y'
            AND B.SUMMARY_FLAG = 'N'
			AND T.ORACLE_SEGMENTO5 = A.FLEX_VALUE_MEANING);
UPDATE FECXP_REP_CONCILIACION_ERP_TMP T
   SET T.ORACLE_SEGMENTO6_DES = (SELECT A.DESCRIPTION
           FROM FND_FLEX_VALUES_TL@ERP_PROD A, FND_FLEX_VALUES@ERP_PROD B
          WHERE B.FLEX_VALUE_SET_ID = '1007921'
            AND A.FLEX_VALUE_ID = B.FLEX_VALUE_ID
            AND A.LANGUAGE = 'ESA'
            AND ENABLED_FLAG = 'Y'
            AND B.SUMMARY_FLAG = 'N'
			AND T.ORACLE_SEGMENTO6 = A.FLEX_VALUE_MEANING);
UPDATE FECXP_REP_CONCILIACION_ERP_TMP T
   SET T.ORACLE_SEGMENTO7_DES = (SELECT A.DESCRIPTION
           FROM FND_FLEX_VALUES_TL@ERP_PROD A, FND_FLEX_VALUES@ERP_PROD B
          WHERE B.FLEX_VALUE_SET_ID = '1007920'
            AND A.FLEX_VALUE_ID = B.FLEX_VALUE_ID
            AND A.LANGUAGE = 'ESA'
            AND ENABLED_FLAG = 'Y'
            AND B.SUMMARY_FLAG = 'N'
			AND T.ORACLE_SEGMENTO7 = A.FLEX_VALUE_MEANING);
			---------------------			---------------------			--------------------
		---							   INSERCION DE MOVIMIENTOS DE REAL						    ----
			---------------------			---------------------			---------------------
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, FECHA_APLICACION, ORACLE_SEGMENTO1,
	   								   	ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
										ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES, ORACLE_SEGMENTO3_DES,
										ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES, ORACLE_SEGMENTO7_DES)
SELECT RR.CLA_ID_FE, RR.CLA_FE_DES, '1REAL' AS CONCEPTO, RR.MONEDA, RR.IMPORTE_LINEA, RR.FECHA_APLICACION, RR.ORACLE_SEGMENTO1,
	   RR.ORACLE_SEGMENTO2, RR.ORACLE_SEGMENTO3, RR.ORACLE_SEGMENTO4, RR.ORACLE_SEGMENTO5, RR.ORACLE_SEGMENTO6, RR.ORACLE_SEGMENTO7,
	   T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES, T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES,
	   T.ORACLE_SEGMENTO6_DES, T.ORACLE_SEGMENTO7_DES
  FROM FECXP_REP_CONCILIACION_ERP_TMP T,
  	   FECXP_REP_REAL_ERP RR
 WHERE TO_NUMBER(TO_CHAR(RR.FECHA_APLICACION,'MM')) = V_MES
	   AND TO_NUMBER(TO_CHAR(RR.FECHA_APLICACION,'YYYY')) = V_PERIODO
	   AND T.ORACLE_SEGMENTO1 = RR.ORACLE_SEGMENTO1
       AND T.ORACLE_SEGMENTO2 = RR.ORACLE_SEGMENTO2
	   AND T.ORACLE_SEGMENTO3 = RR.ORACLE_SEGMENTO3
	   AND T.ORACLE_SEGMENTO4 = RR.ORACLE_SEGMENTO4
	   AND T.ORACLE_SEGMENTO5 = RR.ORACLE_SEGMENTO5
	   AND T.ORACLE_SEGMENTO6 = RR.ORACLE_SEGMENTO6
	   AND T.ORACLE_SEGMENTO7 = RR.ORACLE_SEGMENTO7;
			---------------------			---------------------			--------------------
		---					INSERCION DE MOVIMIENTOS COMPLEMENTARIOS	(DEBITO Y CREDITO)		 ----
			---------------------			---------------------			---------------------
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, FECHA_APLICACION, ORACLE_SEGMENTO1,
	   								   	ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
										ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES, ORACLE_SEGMENTO3_DES,
										ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES, ORACLE_SEGMENTO7_DES)
SELECT RR.CLA_ID_FE, RR.CLA_FE_DES, '6MC_DEB' AS CONCEPTO, RR.MONEDA, RR.IMPORTE_DEBITO, RR.FECHA_APLICACION, RR.ORACLE_SEGMENTO1,
	   RR.ORACLE_SEGMENTO2, RR.ORACLE_SEGMENTO3, RR.ORACLE_SEGMENTO4, RR.ORACLE_SEGMENTO5, RR.ORACLE_SEGMENTO6, RR.ORACLE_SEGMENTO7,
	   T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES, T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES,
	   T.ORACLE_SEGMENTO6_DES, T.ORACLE_SEGMENTO7_DES
  FROM FECXP_REP_CONCILIACION_ERP_TMP T,
  	   FECXP_REP_MVCOMP_ERP  RR
 WHERE TO_NUMBER(TO_CHAR(RR.FECHA_APLICACION,'MM')) = V_MES
	   AND TO_NUMBER(TO_CHAR(RR.FECHA_APLICACION,'YYYY')) = V_PERIODO
	   AND T.ORACLE_SEGMENTO1 = RR.ORACLE_SEGMENTO1
       AND T.ORACLE_SEGMENTO2 = RR.ORACLE_SEGMENTO2
	   AND T.ORACLE_SEGMENTO3 = RR.ORACLE_SEGMENTO3
	   AND T.ORACLE_SEGMENTO4 = RR.ORACLE_SEGMENTO4
	   AND T.ORACLE_SEGMENTO5 = RR.ORACLE_SEGMENTO5
	   AND T.ORACLE_SEGMENTO6 = RR.ORACLE_SEGMENTO6
	   AND T.ORACLE_SEGMENTO7 = RR.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, FECHA_APLICACION, ORACLE_SEGMENTO1,
	   								   	ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
										ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES, ORACLE_SEGMENTO3_DES,
										ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES, ORACLE_SEGMENTO7_DES)
SELECT RR.CLA_ID_FE, RR.CLA_FE_DES, '7MC_CRE' AS CONCEPTO, RR.MONEDA, RR.IMPORTE_CREDITO, RR.FECHA_APLICACION, RR.ORACLE_SEGMENTO1,
	   RR.ORACLE_SEGMENTO2, RR.ORACLE_SEGMENTO3, RR.ORACLE_SEGMENTO4, RR.ORACLE_SEGMENTO5, RR.ORACLE_SEGMENTO6, RR.ORACLE_SEGMENTO7,
	   T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES, T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES,
	   T.ORACLE_SEGMENTO6_DES, T.ORACLE_SEGMENTO7_DES
  FROM FECXP_REP_CONCILIACION_ERP_TMP T,
  	   FECXP_REP_MVCOMP_ERP  RR
 WHERE  TO_NUMBER(TO_CHAR(RR.FECHA_APLICACION,'MM')) = V_MES
	   AND TO_NUMBER(TO_CHAR(RR.FECHA_APLICACION,'YYYY')) = V_PERIODO
	   AND T.ORACLE_SEGMENTO1 = RR.ORACLE_SEGMENTO1
       AND T.ORACLE_SEGMENTO2 = RR.ORACLE_SEGMENTO2
	   AND T.ORACLE_SEGMENTO3 = RR.ORACLE_SEGMENTO3
	   AND T.ORACLE_SEGMENTO4 = RR.ORACLE_SEGMENTO4
	   AND T.ORACLE_SEGMENTO5 = RR.ORACLE_SEGMENTO5
	   AND T.ORACLE_SEGMENTO6 = RR.ORACLE_SEGMENTO6
	   AND T.ORACLE_SEGMENTO7 = RR.ORACLE_SEGMENTO7;
	   ------------------------------ 					  ------------------------------
	   ------------------------------    PRESUPUESTO FE	  ------------------------------
	   ---------------------------------------------------------------------------------
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, FECHA_APLICACION, ORACLE_SEGMENTO1,
	   								   	ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
										ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES, ORACLE_SEGMENTO3_DES,
										ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES, ORACLE_SEGMENTO7_DES)
SELECT RR.CLA_ID_FE, RR.CLA_FE_DES, '2PPTO_FE' AS CONCEPTO, RR.MONEDA, RR.IMPORTE_LINEA, TO_DATE(TO_CHAR(RR.MES)||'-'||RR.PERIODO,'MM-YYYY') AS FECHA, RR.ORACLE_SEGMENTO1,
	   RR.ORACLE_SEGMENTO2, RR.ORACLE_SEGMENTO3, RR.ORACLE_SEGMENTO4, RR.ORACLE_SEGMENTO5, RR.ORACLE_SEGMENTO6, RR.ORACLE_SEGMENTO7,
	   T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES, T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES,
	   T.ORACLE_SEGMENTO6_DES, T.ORACLE_SEGMENTO7_DES
  FROM FECXP_REP_CONCILIACION_ERP_TMP T,
  	   FECXP_REP_PPTO_ERP  RR
 WHERE RR.MES  = V_MES
       AND RR.PERIODO = V_PERIODO
	   AND T.ORACLE_SEGMENTO1 = RR.ORACLE_SEGMENTO1
       AND T.ORACLE_SEGMENTO2 = RR.ORACLE_SEGMENTO2
	   AND T.ORACLE_SEGMENTO3 = RR.ORACLE_SEGMENTO3
	   AND T.ORACLE_SEGMENTO4 = RR.ORACLE_SEGMENTO4
	   AND T.ORACLE_SEGMENTO5 = RR.ORACLE_SEGMENTO5
	   AND T.ORACLE_SEGMENTO6 = RR.ORACLE_SEGMENTO6
	   AND T.ORACLE_SEGMENTO7 = RR.ORACLE_SEGMENTO7;
   -------------------------------------- 			--------------------------
------------------------------		 PRESUPUESTO OPERATIVO  -------------------------
   --------------------------------------	   		--------------------------
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, TIPO_CAMBIO, FECHA_APLICACION,
	   								   ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5,
									   ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES,
									   ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES,
									   ORACLE_SEGMENTO7_DES)
SELECT	T.CLA_ID_FE, T.CLA_FE_DES, '3PPTO_OP' AS CONCEPTO, PO.MONEDA, PO.PPTO_01,
		CASE WHEN MONEDA = 'MXP' THEN PO.PSS_01
			 WHEN MONEDA = 'USD' THEN PO.USD_01
			 WHEN MONEDA = 'EUR' THEN PO.EUR_01 END AS TIPO_CAMBIO,
		TO_DATE(PO.PERIODO_PPTO||'-'||01,'YYYY-MM') AS FECHA,
		PO.ORACLE_SEGMENTO1, PO.ORACLE_SEGMENTO2, PO.ORACLE_SEGMENTO3,
		PO.ORACLE_SEGMENTO4, PO.ORACLE_SEGMENTO5, PO.ORACLE_SEGMENTO6, PO.ORACLE_SEGMENTO7, T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES,
		T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES, T.ORACLE_SEGMENTO6_DES,	T.ORACLE_SEGMENTO7_DES
FROM	FECXP_PPTO_OPERA_ERP PO,
		FECXP_REP_CONCILIACION_ERP_TMP T
WHERE   T.ORACLE_SEGMENTO1 = PO.ORACLE_SEGMENTO1
  AND   T.ORACLE_SEGMENTO2 = PO.ORACLE_SEGMENTO2
  AND   T.ORACLE_SEGMENTO3 = PO.ORACLE_SEGMENTO3
  AND   T.ORACLE_SEGMENTO4 = PO.ORACLE_SEGMENTO4
  AND   T.ORACLE_SEGMENTO5 = PO.ORACLE_SEGMENTO5
  AND   T.ORACLE_SEGMENTO6 = PO.ORACLE_SEGMENTO6
  AND   T.ORACLE_SEGMENTO7 = PO.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, TIPO_CAMBIO, FECHA_APLICACION,
	   								   ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5,
									   ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES,
									   ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES,
									   ORACLE_SEGMENTO7_DES)
SELECT	T.CLA_ID_FE, T.CLA_FE_DES, '3PPTO_OP' AS CONCEPTO, PO.MONEDA, PO.PPTO_02,
		CASE WHEN MONEDA = 'MXP' THEN PO.PSS_02
			 WHEN MONEDA = 'USD' THEN PO.USD_02
			 WHEN MONEDA = 'EUR' THEN PO.EUR_02 END AS TIPO_CAMBIO,
		TO_DATE(PO.PERIODO_PPTO||'-'||02,'YYYY-MM') AS FECHA,
		PO.ORACLE_SEGMENTO1, PO.ORACLE_SEGMENTO2, PO.ORACLE_SEGMENTO3,
		PO.ORACLE_SEGMENTO4, PO.ORACLE_SEGMENTO5, PO.ORACLE_SEGMENTO6, PO.ORACLE_SEGMENTO7, T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES,
		T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES, T.ORACLE_SEGMENTO6_DES,	T.ORACLE_SEGMENTO7_DES
FROM	FECXP_PPTO_OPERA_ERP PO,
		FECXP_REP_CONCILIACION_ERP_TMP T
WHERE   T.ORACLE_SEGMENTO1 = PO.ORACLE_SEGMENTO1
  AND   T.ORACLE_SEGMENTO2 = PO.ORACLE_SEGMENTO2
  AND   T.ORACLE_SEGMENTO3 = PO.ORACLE_SEGMENTO3
  AND   T.ORACLE_SEGMENTO4 = PO.ORACLE_SEGMENTO4
  AND   T.ORACLE_SEGMENTO5 = PO.ORACLE_SEGMENTO5
  AND   T.ORACLE_SEGMENTO6 = PO.ORACLE_SEGMENTO6
  AND   T.ORACLE_SEGMENTO7 = PO.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, TIPO_CAMBIO, FECHA_APLICACION,
	   								   ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5,
									   ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES,
									   ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES,
									   ORACLE_SEGMENTO7_DES)
SELECT	T.CLA_ID_FE, T.CLA_FE_DES, '3PPTO_OP' AS CONCEPTO, PO.MONEDA, PO.PPTO_03,
		CASE WHEN MONEDA = 'MXP' THEN PO.PSS_03
			 WHEN MONEDA = 'USD' THEN PO.USD_03
			 WHEN MONEDA = 'EUR' THEN PO.EUR_03 END AS TIPO_CAMBIO,
		TO_DATE(PO.PERIODO_PPTO||'-'||03,'YYYY-MM') AS FECHA,
		PO.ORACLE_SEGMENTO1, PO.ORACLE_SEGMENTO2, PO.ORACLE_SEGMENTO3,
		PO.ORACLE_SEGMENTO4, PO.ORACLE_SEGMENTO5, PO.ORACLE_SEGMENTO6, PO.ORACLE_SEGMENTO7, T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES,
		T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES, T.ORACLE_SEGMENTO6_DES,	T.ORACLE_SEGMENTO7_DES
FROM	FECXP_PPTO_OPERA_ERP PO,
		FECXP_REP_CONCILIACION_ERP_TMP T
WHERE   T.ORACLE_SEGMENTO1 = PO.ORACLE_SEGMENTO1
  AND   T.ORACLE_SEGMENTO2 = PO.ORACLE_SEGMENTO2
  AND   T.ORACLE_SEGMENTO3 = PO.ORACLE_SEGMENTO3
  AND   T.ORACLE_SEGMENTO4 = PO.ORACLE_SEGMENTO4
  AND   T.ORACLE_SEGMENTO5 = PO.ORACLE_SEGMENTO5
  AND   T.ORACLE_SEGMENTO6 = PO.ORACLE_SEGMENTO6
  AND   T.ORACLE_SEGMENTO7 = PO.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, TIPO_CAMBIO, FECHA_APLICACION,
	   								   ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5,
									   ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES,
									   ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES,
									   ORACLE_SEGMENTO7_DES)
SELECT	T.CLA_ID_FE, T.CLA_FE_DES, '3PPTO_OP' AS CONCEPTO, PO.MONEDA, PO.PPTO_04,
		CASE WHEN MONEDA = 'MXP' THEN PO.PSS_04
			 WHEN MONEDA = 'USD' THEN PO.USD_04
			 WHEN MONEDA = 'EUR' THEN PO.EUR_04 END AS TIPO_CAMBIO,
		TO_DATE(PO.PERIODO_PPTO||'-'||04,'YYYY-MM') AS FECHA,
		PO.ORACLE_SEGMENTO1, PO.ORACLE_SEGMENTO2, PO.ORACLE_SEGMENTO3,
		PO.ORACLE_SEGMENTO4, PO.ORACLE_SEGMENTO5, PO.ORACLE_SEGMENTO6, PO.ORACLE_SEGMENTO7, T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES,
		T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES, T.ORACLE_SEGMENTO6_DES,	T.ORACLE_SEGMENTO7_DES
FROM	FECXP_PPTO_OPERA_ERP PO,
		FECXP_REP_CONCILIACION_ERP_TMP T
WHERE   T.ORACLE_SEGMENTO1 = PO.ORACLE_SEGMENTO1
  AND   T.ORACLE_SEGMENTO2 = PO.ORACLE_SEGMENTO2
  AND   T.ORACLE_SEGMENTO3 = PO.ORACLE_SEGMENTO3
  AND   T.ORACLE_SEGMENTO4 = PO.ORACLE_SEGMENTO4
  AND   T.ORACLE_SEGMENTO5 = PO.ORACLE_SEGMENTO5
  AND   T.ORACLE_SEGMENTO6 = PO.ORACLE_SEGMENTO6
  AND   T.ORACLE_SEGMENTO7 = PO.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, TIPO_CAMBIO, FECHA_APLICACION,
	   								   ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5,
									   ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES,
									   ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES,
									   ORACLE_SEGMENTO7_DES)
SELECT	T.CLA_ID_FE, T.CLA_FE_DES, '3PPTO_OP' AS CONCEPTO, PO.MONEDA, PO.PPTO_05,
		CASE WHEN MONEDA = 'MXP' THEN PO.PSS_05
			 WHEN MONEDA = 'USD' THEN PO.USD_05
			 WHEN MONEDA = 'EUR' THEN PO.EUR_05 END AS TIPO_CAMBIO,
		TO_DATE(PO.PERIODO_PPTO||'-'||05,'YYYY-MM') AS FECHA,
		PO.ORACLE_SEGMENTO1, PO.ORACLE_SEGMENTO2, PO.ORACLE_SEGMENTO3,
		PO.ORACLE_SEGMENTO4, PO.ORACLE_SEGMENTO5, PO.ORACLE_SEGMENTO6, PO.ORACLE_SEGMENTO7, T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES,
		T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES, T.ORACLE_SEGMENTO6_DES,	T.ORACLE_SEGMENTO7_DES
FROM	FECXP_PPTO_OPERA_ERP PO,
		FECXP_REP_CONCILIACION_ERP_TMP T
WHERE   T.ORACLE_SEGMENTO1 = PO.ORACLE_SEGMENTO1
  AND   T.ORACLE_SEGMENTO2 = PO.ORACLE_SEGMENTO2
  AND   T.ORACLE_SEGMENTO3 = PO.ORACLE_SEGMENTO3
  AND   T.ORACLE_SEGMENTO4 = PO.ORACLE_SEGMENTO4
  AND   T.ORACLE_SEGMENTO5 = PO.ORACLE_SEGMENTO5
  AND   T.ORACLE_SEGMENTO6 = PO.ORACLE_SEGMENTO6
  AND   T.ORACLE_SEGMENTO7 = PO.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, TIPO_CAMBIO, FECHA_APLICACION,
	   								   ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5,
									   ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES,
									   ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES,
									   ORACLE_SEGMENTO7_DES)
SELECT	T.CLA_ID_FE, T.CLA_FE_DES, '3PPTO_OP' AS CONCEPTO, PO.MONEDA, PO.PPTO_06,
		CASE WHEN MONEDA = 'MXP' THEN PO.PSS_06
			 WHEN MONEDA = 'USD' THEN PO.USD_06
			 WHEN MONEDA = 'EUR' THEN PO.EUR_06 END AS TIPO_CAMBIO,
		TO_DATE(PO.PERIODO_PPTO||'-'||06,'YYYY-MM') AS FECHA,
		PO.ORACLE_SEGMENTO1, PO.ORACLE_SEGMENTO2, PO.ORACLE_SEGMENTO3,
		PO.ORACLE_SEGMENTO4, PO.ORACLE_SEGMENTO5, PO.ORACLE_SEGMENTO6, PO.ORACLE_SEGMENTO7, T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES,
		T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES, T.ORACLE_SEGMENTO6_DES,	T.ORACLE_SEGMENTO7_DES
FROM	FECXP_PPTO_OPERA_ERP PO,
		FECXP_REP_CONCILIACION_ERP_TMP T
WHERE   T.ORACLE_SEGMENTO1 = PO.ORACLE_SEGMENTO1
  AND   T.ORACLE_SEGMENTO2 = PO.ORACLE_SEGMENTO2
  AND   T.ORACLE_SEGMENTO3 = PO.ORACLE_SEGMENTO3
  AND   T.ORACLE_SEGMENTO4 = PO.ORACLE_SEGMENTO4
  AND   T.ORACLE_SEGMENTO5 = PO.ORACLE_SEGMENTO5
  AND   T.ORACLE_SEGMENTO6 = PO.ORACLE_SEGMENTO6
  AND   T.ORACLE_SEGMENTO7 = PO.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, TIPO_CAMBIO, FECHA_APLICACION,
	   								   ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5,
									   ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES,
									   ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES,
									   ORACLE_SEGMENTO7_DES)
SELECT	T.CLA_ID_FE, T.CLA_FE_DES, '3PPTO_OP' AS CONCEPTO, PO.MONEDA, PO.PPTO_07,
		CASE WHEN MONEDA = 'MXP' THEN PO.PSS_07
			 WHEN MONEDA = 'USD' THEN PO.USD_07
			 WHEN MONEDA = 'EUR' THEN PO.EUR_07 END AS TIPO_CAMBIO,
		TO_DATE(PO.PERIODO_PPTO||'-'||07,'YYYY-MM') AS FECHA,
		PO.ORACLE_SEGMENTO1, PO.ORACLE_SEGMENTO2, PO.ORACLE_SEGMENTO3,
		PO.ORACLE_SEGMENTO4, PO.ORACLE_SEGMENTO5, PO.ORACLE_SEGMENTO6, PO.ORACLE_SEGMENTO7, T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES,
		T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES, T.ORACLE_SEGMENTO6_DES,	T.ORACLE_SEGMENTO7_DES
FROM	FECXP_PPTO_OPERA_ERP PO,
		FECXP_REP_CONCILIACION_ERP_TMP T
WHERE   T.ORACLE_SEGMENTO1 = PO.ORACLE_SEGMENTO1
  AND   T.ORACLE_SEGMENTO2 = PO.ORACLE_SEGMENTO2
  AND   T.ORACLE_SEGMENTO3 = PO.ORACLE_SEGMENTO3
  AND   T.ORACLE_SEGMENTO4 = PO.ORACLE_SEGMENTO4
  AND   T.ORACLE_SEGMENTO5 = PO.ORACLE_SEGMENTO5
  AND   T.ORACLE_SEGMENTO6 = PO.ORACLE_SEGMENTO6
  AND   T.ORACLE_SEGMENTO7 = PO.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, TIPO_CAMBIO, FECHA_APLICACION,
	   								   ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5,
									   ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES,
									   ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES,
									   ORACLE_SEGMENTO7_DES)
SELECT	T.CLA_ID_FE, T.CLA_FE_DES, '3PPTO_OP' AS CONCEPTO, PO.MONEDA, PO.PPTO_08,
		CASE WHEN MONEDA = 'MXP' THEN PO.PSS_08
			 WHEN MONEDA = 'USD' THEN PO.USD_08
			 WHEN MONEDA = 'EUR' THEN PO.EUR_08 END AS TIPO_CAMBIO,
		TO_DATE(PO.PERIODO_PPTO||'-'||08,'YYYY-MM') AS FECHA,
		PO.ORACLE_SEGMENTO1, PO.ORACLE_SEGMENTO2, PO.ORACLE_SEGMENTO3,
		PO.ORACLE_SEGMENTO4, PO.ORACLE_SEGMENTO5, PO.ORACLE_SEGMENTO6, PO.ORACLE_SEGMENTO7, T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES,
		T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES, T.ORACLE_SEGMENTO6_DES,	T.ORACLE_SEGMENTO7_DES
FROM	FECXP_PPTO_OPERA_ERP PO,
		FECXP_REP_CONCILIACION_ERP_TMP T
WHERE   T.ORACLE_SEGMENTO1 = PO.ORACLE_SEGMENTO1
  AND   T.ORACLE_SEGMENTO2 = PO.ORACLE_SEGMENTO2
  AND   T.ORACLE_SEGMENTO3 = PO.ORACLE_SEGMENTO3
  AND   T.ORACLE_SEGMENTO4 = PO.ORACLE_SEGMENTO4
  AND   T.ORACLE_SEGMENTO5 = PO.ORACLE_SEGMENTO5
  AND   T.ORACLE_SEGMENTO6 = PO.ORACLE_SEGMENTO6
  AND   T.ORACLE_SEGMENTO7 = PO.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, TIPO_CAMBIO, FECHA_APLICACION,
	   								   ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5,
									   ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES,
									   ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES,
									   ORACLE_SEGMENTO7_DES)
SELECT	T.CLA_ID_FE, T.CLA_FE_DES, '3PPTO_OP' AS CONCEPTO, PO.MONEDA, PO.PPTO_09,
		CASE WHEN MONEDA = 'MXP' THEN PO.PSS_09
			 WHEN MONEDA = 'USD' THEN PO.USD_09
			 WHEN MONEDA = 'EUR' THEN PO.EUR_09 END AS TIPO_CAMBIO,
		TO_DATE(PO.PERIODO_PPTO||'-'||09,'YYYY-MM') AS FECHA,
		PO.ORACLE_SEGMENTO1, PO.ORACLE_SEGMENTO2, PO.ORACLE_SEGMENTO3,
		PO.ORACLE_SEGMENTO4, PO.ORACLE_SEGMENTO5, PO.ORACLE_SEGMENTO6, PO.ORACLE_SEGMENTO7, T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES,
		T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES, T.ORACLE_SEGMENTO6_DES,	T.ORACLE_SEGMENTO7_DES
FROM	FECXP_PPTO_OPERA_ERP PO,
		FECXP_REP_CONCILIACION_ERP_TMP T
WHERE   T.ORACLE_SEGMENTO1 = PO.ORACLE_SEGMENTO1
  AND   T.ORACLE_SEGMENTO2 = PO.ORACLE_SEGMENTO2
  AND   T.ORACLE_SEGMENTO3 = PO.ORACLE_SEGMENTO3
  AND   T.ORACLE_SEGMENTO4 = PO.ORACLE_SEGMENTO4
  AND   T.ORACLE_SEGMENTO5 = PO.ORACLE_SEGMENTO5
  AND   T.ORACLE_SEGMENTO6 = PO.ORACLE_SEGMENTO6
  AND   T.ORACLE_SEGMENTO7 = PO.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, TIPO_CAMBIO, FECHA_APLICACION,
	   								   ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5,
									   ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES,
									   ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES,
									   ORACLE_SEGMENTO7_DES)
SELECT	T.CLA_ID_FE, T.CLA_FE_DES, '3PPTO_OP' AS CONCEPTO, PO.MONEDA, PO.PPTO_10,
		CASE WHEN MONEDA = 'MXP' THEN PO.PSS_10
			 WHEN MONEDA = 'USD' THEN PO.USD_10
			 WHEN MONEDA = 'EUR' THEN PO.EUR_10 END AS TIPO_CAMBIO,
		TO_DATE(PO.PERIODO_PPTO||'-'||10,'YYYY-MM') AS FECHA,
		PO.ORACLE_SEGMENTO1, PO.ORACLE_SEGMENTO2, PO.ORACLE_SEGMENTO3,
		PO.ORACLE_SEGMENTO4, PO.ORACLE_SEGMENTO5, PO.ORACLE_SEGMENTO6, PO.ORACLE_SEGMENTO7, T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES,
		T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES, T.ORACLE_SEGMENTO6_DES,	T.ORACLE_SEGMENTO7_DES
FROM	FECXP_PPTO_OPERA_ERP PO,
		FECXP_REP_CONCILIACION_ERP_TMP T
WHERE   T.ORACLE_SEGMENTO1 = PO.ORACLE_SEGMENTO1
  AND   T.ORACLE_SEGMENTO2 = PO.ORACLE_SEGMENTO2
  AND   T.ORACLE_SEGMENTO3 = PO.ORACLE_SEGMENTO3
  AND   T.ORACLE_SEGMENTO4 = PO.ORACLE_SEGMENTO4
  AND   T.ORACLE_SEGMENTO5 = PO.ORACLE_SEGMENTO5
  AND   T.ORACLE_SEGMENTO6 = PO.ORACLE_SEGMENTO6
  AND   T.ORACLE_SEGMENTO7 = PO.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, TIPO_CAMBIO, FECHA_APLICACION,
	   								   ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5,
									   ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES,
									   ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES,
									   ORACLE_SEGMENTO7_DES)
SELECT	T.CLA_ID_FE, T.CLA_FE_DES, '3PPTO_OP' AS CONCEPTO, PO.MONEDA, PO.PPTO_01,
		CASE WHEN MONEDA = 'MXP' THEN PO.PSS_11
			 WHEN MONEDA = 'USD' THEN PO.USD_11
			 WHEN MONEDA = 'EUR' THEN PO.EUR_11 END AS TIPO_CAMBIO,
		TO_DATE(PO.PERIODO_PPTO||'-'||11,'YYYY-MM') AS FECHA,
		PO.ORACLE_SEGMENTO1, PO.ORACLE_SEGMENTO2, PO.ORACLE_SEGMENTO3,
		PO.ORACLE_SEGMENTO4, PO.ORACLE_SEGMENTO5, PO.ORACLE_SEGMENTO6, PO.ORACLE_SEGMENTO7, T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES,
		T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES, T.ORACLE_SEGMENTO6_DES,	T.ORACLE_SEGMENTO7_DES
FROM	FECXP_PPTO_OPERA_ERP PO,
		FECXP_REP_CONCILIACION_ERP_TMP T
WHERE   T.ORACLE_SEGMENTO1 = PO.ORACLE_SEGMENTO1
  AND   T.ORACLE_SEGMENTO2 = PO.ORACLE_SEGMENTO2
  AND   T.ORACLE_SEGMENTO3 = PO.ORACLE_SEGMENTO3
  AND   T.ORACLE_SEGMENTO4 = PO.ORACLE_SEGMENTO4
  AND   T.ORACLE_SEGMENTO5 = PO.ORACLE_SEGMENTO5
  AND   T.ORACLE_SEGMENTO6 = PO.ORACLE_SEGMENTO6
  AND   T.ORACLE_SEGMENTO7 = PO.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, TIPO_CAMBIO, FECHA_APLICACION,
	   								   ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5,
									   ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES,
									   ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES,
									   ORACLE_SEGMENTO7_DES)
SELECT	T.CLA_ID_FE, T.CLA_FE_DES, '3PPTO_OP' AS CONCEPTO, PO.MONEDA, PO.PPTO_01,
		CASE WHEN MONEDA = 'MXP' THEN PO.PSS_12
			 WHEN MONEDA = 'USD' THEN PO.USD_12
			 WHEN MONEDA = 'EUR' THEN PO.EUR_12 END AS TIPO_CAMBIO,
		TO_DATE(PO.PERIODO_PPTO||'-'||12,'YYYY-MM') AS FECHA,
		PO.ORACLE_SEGMENTO1, PO.ORACLE_SEGMENTO2, PO.ORACLE_SEGMENTO3,
		PO.ORACLE_SEGMENTO4, PO.ORACLE_SEGMENTO5, PO.ORACLE_SEGMENTO6, PO.ORACLE_SEGMENTO7, T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES,
		T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES, T.ORACLE_SEGMENTO6_DES,	T.ORACLE_SEGMENTO7_DES
FROM	FECXP_PPTO_OPERA_ERP PO,
		FECXP_REP_CONCILIACION_ERP_TMP T
WHERE   T.ORACLE_SEGMENTO1 = PO.ORACLE_SEGMENTO1
  AND   T.ORACLE_SEGMENTO2 = PO.ORACLE_SEGMENTO2
  AND   T.ORACLE_SEGMENTO3 = PO.ORACLE_SEGMENTO3
  AND   T.ORACLE_SEGMENTO4 = PO.ORACLE_SEGMENTO4
  AND   T.ORACLE_SEGMENTO5 = PO.ORACLE_SEGMENTO5
  AND   T.ORACLE_SEGMENTO6 = PO.ORACLE_SEGMENTO6
  AND   T.ORACLE_SEGMENTO7 = PO.ORACLE_SEGMENTO7;
------------------------------							------------------------------
------------------------------			SALDOS			------------------------------
--------------------------------------------------------------------------------------
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, FECHA_APLICACION, ORACLE_SEGMENTO1,
	   								   	ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
										ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES, ORACLE_SEGMENTO3_DES,
										ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES, ORACLE_SEGMENTO7_DES)
SELECT T.CLA_ID_FE, T.CLA_FE_DES, '4SAL_DEB' AS CONCEPTO, RR.MONEDA, RR.DEBITO_INICIAL_MO, TO_DATE(TO_CHAR(RR.MES)||'-'||RR.PERIODO,'MM-YYYY') AS FECHA, RR.ORACLE_SEGMENTO1,
	   RR.ORACLE_SEGMENTO2, RR.ORACLE_SEGMENTO3, RR.ORACLE_SEGMENTO4, RR.ORACLE_SEGMENTO5, RR.ORACLE_SEGMENTO6, RR.ORACLE_SEGMENTO7,
	   T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES, T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES,
	   T.ORACLE_SEGMENTO6_DES, T.ORACLE_SEGMENTO7_DES
  FROM FECXP_REP_CONCILIACION_ERP_TMP T,
  	   FECXP_SALDOS_OPERATIVO_ERP  RR
 WHERE RR.PERIODO =V_PERIODO
   AND RR.MES  = V_MES
   AND RR.PERIODO_EXTRACCION =V_PERIODO
   AND RR.MES_DE_EXTRACCION  = V_MES
   AND T.ORACLE_SEGMENTO1 = RR.ORACLE_SEGMENTO1
   AND T.ORACLE_SEGMENTO2 = RR.ORACLE_SEGMENTO2
   AND T.ORACLE_SEGMENTO3 = RR.ORACLE_SEGMENTO3
   AND T.ORACLE_SEGMENTO4 = RR.ORACLE_SEGMENTO4
   AND T.ORACLE_SEGMENTO5 = RR.ORACLE_SEGMENTO5
   AND T.ORACLE_SEGMENTO6 = RR.ORACLE_SEGMENTO6
   AND T.ORACLE_SEGMENTO7 = RR.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, FECHA_APLICACION, ORACLE_SEGMENTO1,
	   								   	ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
										ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES, ORACLE_SEGMENTO2_DES, ORACLE_SEGMENTO3_DES,
										ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES, ORACLE_SEGMENTO6_DES, ORACLE_SEGMENTO7_DES)
SELECT T.CLA_ID_FE, T.CLA_FE_DES, '5SAL_CRE' AS CONCEPTO, RR.MONEDA, RR.CREDITO_INICIAL_MO, TO_DATE(TO_CHAR(RR.MES)||'-'||RR.PERIODO,'MM-YYYY') AS FECHA, RR.ORACLE_SEGMENTO1,
	   RR.ORACLE_SEGMENTO2, RR.ORACLE_SEGMENTO3, RR.ORACLE_SEGMENTO4, RR.ORACLE_SEGMENTO5, RR.ORACLE_SEGMENTO6, RR.ORACLE_SEGMENTO7,
	   T.ORACLE_SEGMENTO1_DES, T.ORACLE_SEGMENTO2_DES, T.ORACLE_SEGMENTO3_DES, T.ORACLE_SEGMENTO4_DES, T.ORACLE_SEGMENTO5_DES,
	   T.ORACLE_SEGMENTO6_DES, T.ORACLE_SEGMENTO7_DES
  FROM FECXP_REP_CONCILIACION_ERP_TMP T,
  	   FECXP_SALDOS_OPERATIVO_ERP  RR
 WHERE RR.PERIODO =V_PERIODO
   AND RR.MES  = V_MES
   AND RR.PERIODO_EXTRACCION =V_PERIODO
   AND RR.MES_DE_EXTRACCION  = V_MES
   AND T.ORACLE_SEGMENTO1 = RR.ORACLE_SEGMENTO1
   AND T.ORACLE_SEGMENTO2 = RR.ORACLE_SEGMENTO2
   AND T.ORACLE_SEGMENTO3 = RR.ORACLE_SEGMENTO3
   AND T.ORACLE_SEGMENTO4 = RR.ORACLE_SEGMENTO4
   AND T.ORACLE_SEGMENTO5 = RR.ORACLE_SEGMENTO5
   AND T.ORACLE_SEGMENTO6 = RR.ORACLE_SEGMENTO6
   AND T.ORACLE_SEGMENTO7 = RR.ORACLE_SEGMENTO7;
		  	  					 -------------------------------------------------------------------------
-------------------------------- LLENAMOS A 0'S LAS CUENTAS DE SALDOS Q APARECEN EN REAL PERO NO EN SALDOS ---------------------------------------------------------
		  	  					 -------------------------------------------------------------------------
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, FECHA_APLICACION,
	   									 ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
										 ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES,
										 ORACLE_SEGMENTO2_DES, ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES,
										 ORACLE_SEGMENTO6_DES, ORACLE_SEGMENTO7_DES)
SELECT B.CLA_ID_FE, B.CLA_FE_DES, '4SAL_DEB' CONCEPTO, B.ATRIBUTO1, 0 AS MONTO,TO_DATE(TO_CHAR(V_MES)||'-'||V_PERIODO,'MM-YYYY') AS FECHA,
 	   B.ORACLE_SEGMENTO1, B.ORACLE_SEGMENTO2, B.ORACLE_SEGMENTO3, B.ORACLE_SEGMENTO4,
	   B.ORACLE_SEGMENTO5, B.ORACLE_SEGMENTO6, B.ORACLE_SEGMENTO7, B.ORACLE_SEGMENTO1_DES, B.ORACLE_SEGMENTO2_DES,
	   B.ORACLE_SEGMENTO3_DES, B.ORACLE_SEGMENTO4_DES, B.ORACLE_SEGMENTO5_DES, B.ORACLE_SEGMENTO6_DES, B.ORACLE_SEGMENTO7_DES
FROM (SELECT ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
	   ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
	   FROM FECXP_REP_CONCILIACION_ERP_TMP
	   MINUS
	   SELECT DISTINCT ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
    	   			ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
   		FROM FECXP_REP_CONCILIACION_ERP
   		WHERE CONCEPTO = '4SAL_DEB') A, FECXP_REP_CONCILIACION_ERP_TMP B
		WHERE A.ORACLE_SEGMENTO1 = B.ORACLE_SEGMENTO1
		  AND A.ORACLE_SEGMENTO2 = B.ORACLE_SEGMENTO2
		  AND A.ORACLE_SEGMENTO3 = B.ORACLE_SEGMENTO3
		  AND A.ORACLE_SEGMENTO4 = B.ORACLE_SEGMENTO4
		  AND A.ORACLE_SEGMENTO5 = B.ORACLE_SEGMENTO5
		  AND A.ORACLE_SEGMENTO6 = B.ORACLE_SEGMENTO6
		  AND A.ORACLE_SEGMENTO7 = B.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, FECHA_APLICACION,
	   									 ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
										 ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES,
										 ORACLE_SEGMENTO2_DES, ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES,
										 ORACLE_SEGMENTO6_DES, ORACLE_SEGMENTO7_DES)
SELECT B.CLA_ID_FE, B.CLA_FE_DES, '5SAL_CRE' CONCEPTO, B.ATRIBUTO1, 0 AS MONTO,TO_DATE(TO_CHAR(V_MES)||'-'||V_PERIODO,'MM-YYYY') AS FECHA,
 	   B.ORACLE_SEGMENTO1, B.ORACLE_SEGMENTO2, B.ORACLE_SEGMENTO3, B.ORACLE_SEGMENTO4,
	   B.ORACLE_SEGMENTO5, B.ORACLE_SEGMENTO6, B.ORACLE_SEGMENTO7, B.ORACLE_SEGMENTO1_DES, B.ORACLE_SEGMENTO2_DES,
	   B.ORACLE_SEGMENTO3_DES, B.ORACLE_SEGMENTO4_DES, B.ORACLE_SEGMENTO5_DES, B.ORACLE_SEGMENTO6_DES, B.ORACLE_SEGMENTO7_DES
FROM (SELECT ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
	   ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
	   FROM FECXP_REP_CONCILIACION_ERP_TMP
	   MINUS
	   SELECT DISTINCT ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
    	   			ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
   		FROM FECXP_REP_CONCILIACION_ERP
   		WHERE CONCEPTO = '5SAL_CRE') A, FECXP_REP_CONCILIACION_ERP_TMP B
		WHERE A.ORACLE_SEGMENTO1 = B.ORACLE_SEGMENTO1
		  AND A.ORACLE_SEGMENTO2 = B.ORACLE_SEGMENTO2
		  AND A.ORACLE_SEGMENTO3 = B.ORACLE_SEGMENTO3
		  AND A.ORACLE_SEGMENTO4 = B.ORACLE_SEGMENTO4
		  AND A.ORACLE_SEGMENTO5 = B.ORACLE_SEGMENTO5
		  AND A.ORACLE_SEGMENTO6 = B.ORACLE_SEGMENTO6
		  AND A.ORACLE_SEGMENTO7 = B.ORACLE_SEGMENTO7;
   	  					 -------------------------------------------------------------------------
-------------------- LLENAMOS A 0'S LAS CUENTAS DE MOV COMPLEMENTARIOS Q APARECEN EN REAL PERO NO EN MOV COMP ---------------------------------------------------------
  	  					 -------------------------------------------------------------------------
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, FECHA_APLICACION,
	   									 ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
										 ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES,
										 ORACLE_SEGMENTO2_DES, ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES,
										 ORACLE_SEGMENTO6_DES, ORACLE_SEGMENTO7_DES)
SELECT B.CLA_ID_FE, B.CLA_FE_DES, '6MC_DEB' CONCEPTO, B.ATRIBUTO1, 0 AS MONTO,TO_DATE(TO_CHAR(V_MES)||'-'||V_PERIODO,'MM-YYYY') AS FECHA,
 	   B.ORACLE_SEGMENTO1, B.ORACLE_SEGMENTO2, B.ORACLE_SEGMENTO3, B.ORACLE_SEGMENTO4,
	   B.ORACLE_SEGMENTO5, B.ORACLE_SEGMENTO6, B.ORACLE_SEGMENTO7, B.ORACLE_SEGMENTO1_DES, B.ORACLE_SEGMENTO2_DES,
	   B.ORACLE_SEGMENTO3_DES, B.ORACLE_SEGMENTO4_DES, B.ORACLE_SEGMENTO5_DES, B.ORACLE_SEGMENTO6_DES, B.ORACLE_SEGMENTO7_DES
FROM (SELECT ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
	   ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
	   FROM FECXP_REP_CONCILIACION_ERP_TMP
	   MINUS
	   SELECT DISTINCT ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
    	   			ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
   		FROM FECXP_REP_CONCILIACION_ERP
   		WHERE CONCEPTO = '6MC_DEB') A, FECXP_REP_CONCILIACION_ERP_TMP B
		WHERE A.ORACLE_SEGMENTO1 = B.ORACLE_SEGMENTO1
		  AND A.ORACLE_SEGMENTO2 = B.ORACLE_SEGMENTO2
		  AND A.ORACLE_SEGMENTO3 = B.ORACLE_SEGMENTO3
		  AND A.ORACLE_SEGMENTO4 = B.ORACLE_SEGMENTO4
		  AND A.ORACLE_SEGMENTO5 = B.ORACLE_SEGMENTO5
		  AND A.ORACLE_SEGMENTO6 = B.ORACLE_SEGMENTO6
		  AND A.ORACLE_SEGMENTO7 = B.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, FECHA_APLICACION,
	   									 ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
										 ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES,
										 ORACLE_SEGMENTO2_DES, ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES,
										 ORACLE_SEGMENTO6_DES, ORACLE_SEGMENTO7_DES)
SELECT B.CLA_ID_FE, B.CLA_FE_DES, '7MC_CRE' CONCEPTO, B.ATRIBUTO1, 0 AS MONTO,TO_DATE(TO_CHAR(V_MES)||'-'||V_PERIODO,'MM-YYYY') AS FECHA,
 	   B.ORACLE_SEGMENTO1, B.ORACLE_SEGMENTO2, B.ORACLE_SEGMENTO3, B.ORACLE_SEGMENTO4,
	   B.ORACLE_SEGMENTO5, B.ORACLE_SEGMENTO6, B.ORACLE_SEGMENTO7, B.ORACLE_SEGMENTO1_DES, B.ORACLE_SEGMENTO2_DES,
	   B.ORACLE_SEGMENTO3_DES, B.ORACLE_SEGMENTO4_DES, B.ORACLE_SEGMENTO5_DES, B.ORACLE_SEGMENTO6_DES, B.ORACLE_SEGMENTO7_DES
FROM (SELECT ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
	   ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
	   FROM FECXP_REP_CONCILIACION_ERP_TMP
	   MINUS
	   SELECT DISTINCT ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
    	   			ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
   		FROM FECXP_REP_CONCILIACION_ERP
   		WHERE CONCEPTO = '7MC_CRE') A, FECXP_REP_CONCILIACION_ERP_TMP B
		WHERE A.ORACLE_SEGMENTO1 = B.ORACLE_SEGMENTO1
		  AND A.ORACLE_SEGMENTO2 = B.ORACLE_SEGMENTO2
		  AND A.ORACLE_SEGMENTO3 = B.ORACLE_SEGMENTO3
		  AND A.ORACLE_SEGMENTO4 = B.ORACLE_SEGMENTO4
		  AND A.ORACLE_SEGMENTO5 = B.ORACLE_SEGMENTO5
		  AND A.ORACLE_SEGMENTO6 = B.ORACLE_SEGMENTO6
		  AND A.ORACLE_SEGMENTO7 = B.ORACLE_SEGMENTO7;
		  	  					 -------------------------------------------------------------------------
---------------------------------- LLENAMOS A 0'S LAS CUENTAS DE PPTPS Q APARECEN EN REAL PERO NO EN PPTO ---------------------------------------------------------
		  	  					 ---------------------------------------------------------------------------
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, FECHA_APLICACION,
	   									 ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
										 ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES,
										 ORACLE_SEGMENTO2_DES, ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES,
										 ORACLE_SEGMENTO6_DES, ORACLE_SEGMENTO7_DES)
SELECT B.CLA_ID_FE, B.CLA_FE_DES, '2PPTO_FE' CONCEPTO, B.ATRIBUTO1, 0 AS MONTO,TO_DATE(TO_CHAR(V_MES)||'-'||V_PERIODO,'MM-YYYY') AS FECHA,
 	   B.ORACLE_SEGMENTO1, B.ORACLE_SEGMENTO2, B.ORACLE_SEGMENTO3, B.ORACLE_SEGMENTO4,
	   B.ORACLE_SEGMENTO5, B.ORACLE_SEGMENTO6, B.ORACLE_SEGMENTO7, B.ORACLE_SEGMENTO1_DES, B.ORACLE_SEGMENTO2_DES,
	   B.ORACLE_SEGMENTO3_DES, B.ORACLE_SEGMENTO4_DES, B.ORACLE_SEGMENTO5_DES, B.ORACLE_SEGMENTO6_DES, B.ORACLE_SEGMENTO7_DES
FROM (SELECT ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
	   ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
	   FROM FECXP_REP_CONCILIACION_ERP_TMP
	   MINUS
	   SELECT DISTINCT ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
    	   			ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
   		FROM FECXP_REP_CONCILIACION_ERP
   		WHERE CONCEPTO = '2PPTO_FE') A, FECXP_REP_CONCILIACION_ERP_TMP B
		WHERE A.ORACLE_SEGMENTO1 = B.ORACLE_SEGMENTO1
		  AND A.ORACLE_SEGMENTO2 = B.ORACLE_SEGMENTO2
		  AND A.ORACLE_SEGMENTO3 = B.ORACLE_SEGMENTO3
		  AND A.ORACLE_SEGMENTO4 = B.ORACLE_SEGMENTO4
		  AND A.ORACLE_SEGMENTO5 = B.ORACLE_SEGMENTO5
		  AND A.ORACLE_SEGMENTO6 = B.ORACLE_SEGMENTO6
		  AND A.ORACLE_SEGMENTO7 = B.ORACLE_SEGMENTO7;
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, FECHA_APLICACION,
	   									 ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
										 ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES,
										 ORACLE_SEGMENTO2_DES, ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES,
										 ORACLE_SEGMENTO6_DES, ORACLE_SEGMENTO7_DES)
SELECT B.CLA_ID_FE, B.CLA_FE_DES, '3PPTO_OP' CONCEPTO, B.ATRIBUTO1, 0 AS MONTO,TO_DATE(TO_CHAR(V_MES)||'-'||V_PERIODO,'MM-YYYY') AS FECHA,
 	   B.ORACLE_SEGMENTO1, B.ORACLE_SEGMENTO2, B.ORACLE_SEGMENTO3, B.ORACLE_SEGMENTO4,
	   B.ORACLE_SEGMENTO5, B.ORACLE_SEGMENTO6, B.ORACLE_SEGMENTO7, B.ORACLE_SEGMENTO1_DES, B.ORACLE_SEGMENTO2_DES,
	   B.ORACLE_SEGMENTO3_DES, B.ORACLE_SEGMENTO4_DES, B.ORACLE_SEGMENTO5_DES, B.ORACLE_SEGMENTO6_DES, B.ORACLE_SEGMENTO7_DES
FROM (SELECT ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
	   ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
	   FROM FECXP_REP_CONCILIACION_ERP_TMP
	   MINUS
	   SELECT DISTINCT ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
    	   			ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
   		FROM FECXP_REP_CONCILIACION_ERP
   		WHERE CONCEPTO = '3PPTO_OP') A, FECXP_REP_CONCILIACION_ERP_TMP B
		WHERE A.ORACLE_SEGMENTO1 = B.ORACLE_SEGMENTO1
		  AND A.ORACLE_SEGMENTO2 = B.ORACLE_SEGMENTO2
		  AND A.ORACLE_SEGMENTO3 = B.ORACLE_SEGMENTO3
		  AND A.ORACLE_SEGMENTO4 = B.ORACLE_SEGMENTO4
		  AND A.ORACLE_SEGMENTO5 = B.ORACLE_SEGMENTO5
		  AND A.ORACLE_SEGMENTO6 = B.ORACLE_SEGMENTO6
		  AND A.ORACLE_SEGMENTO7 = B.ORACLE_SEGMENTO7;
------------------------------       ------------------------------       ------------------------------
------------------------------                TIPO DE CAMBIO			  ------------------------------
------------------------------       ------------------------------       ------------------------------
UPDATE FECXP_REP_CONCILIACION_ERP RS
SET    RS.TIPO_CAMBIO = (SELECT M.TIPO_CAMBIO FROM FECXP_MONEDAS M
	   				  						 WHERE M.MON_ORACLE = RS.MONEDA
											   AND TO_NUMBER(TO_CHAR(RS.FECHA_APLICACION,'MM')) = M.MES);
------------------------------       ------------------------------       ------------------------------
------------------------------           TODO A PSS						  ------------------------------
------------------------------       ------------------------------       ------------------------------
INSERT INTO FECXP_REP_CONCILIACION_ERP (CLA_ID_FE, CLA_FE_DES, CONCEPTO, MONEDA, IMPORTE_LINEA, FECHA_APLICACION,
	   									 ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4,
										 ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7, ORACLE_SEGMENTO1_DES,
										 ORACLE_SEGMENTO2_DES, ORACLE_SEGMENTO3_DES, ORACLE_SEGMENTO4_DES, ORACLE_SEGMENTO5_DES,
										 ORACLE_SEGMENTO6_DES, ORACLE_SEGMENTO7_DES)
SELECT 	A.CLA_ID_FE, A.CLA_FE_DES, A.CONCEPTO, 'PSS' AS MONEDA, A.IMPORTE_LINEA*B.TIPO_CAMBIO AS IMPORTE, A.FECHA_APLICACION, A.ORACLE_SEGMENTO1,
		A.ORACLE_SEGMENTO2, A.ORACLE_SEGMENTO3, A.ORACLE_SEGMENTO4, A.ORACLE_SEGMENTO5, A.ORACLE_SEGMENTO6,
		A.ORACLE_SEGMENTO7, A.ORACLE_SEGMENTO1_DES, A.ORACLE_SEGMENTO2_DES, A.ORACLE_SEGMENTO3_DES, A.ORACLE_SEGMENTO4_DES,
		A.ORACLE_SEGMENTO5_DES, A.ORACLE_SEGMENTO6_DES, A.ORACLE_SEGMENTO7_DES
FROM FECXP_REP_CONCILIACION_ERP A,
 	 FECXP_MONEDAS B
WHERE TO_NUMBER(TO_CHAR(A.FECHA_APLICACION,'YYYY')) = V_PERIODO
  AND TO_NUMBER(TO_CHAR(A.FECHA_APLICACION,'MM')) = V_MES
  AND B.MON_ORACLE = A.MONEDA
  AND B.MES = TO_NUMBER(TO_CHAR(A.FECHA_APLICACION,'MM'));
END;
/
