CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_LLENA_PPTO_ORACLE12MCT" IS
-- PGV moved types end

-- PGV moved types end


BEGIN
-------------------------------------------------------------------------
-- CONSULTA COMPARATIVA DEL PPTO DE SOIN OPERATIVO VS FLUJO

-------------------------------------------------------------------------
-- CONSULTA COMPARATIVA DEL PPTO DE ORACLE OPERATIVO VS FLUJO

DECLARE
-- PGV moved types start

-- PGV moved types start

	V_CLA_FE_ID FECXP_POLITICAS_ERP.CLA_FE_ID%TYPE;
	V_POLITICA_ERP_ID FECXP_POLITICAS_ERP.POLITICA_ERP_ID%TYPE;
	V_PRIORIDAD FECXP_POLITICAS_ERP.PRIORIDAD%TYPE;
	V_ORA_S1_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_INI%TYPE;
	V_ORA_S1_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_FIN%TYPE;
	V_ORA_S2_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_INI%TYPE;
	V_ORA_S2_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_FIN%TYPE;
	V_ORA_S3_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_INI%TYPE;
	V_ORA_S3_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_FIN%TYPE;
	V_ORA_S4_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_INI%TYPE;
	V_ORA_S4_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_FIN%TYPE;
	V_ORA_S5_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_INI%TYPE;
	V_ORA_S5_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_FIN%TYPE;
	V_ORA_S6_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_INI%TYPE;
	V_ORA_S6_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_FIN%TYPE;
	V_ORA_S7_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_INI%TYPE;
	V_ORA_S7_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_FIN%TYPE;
	V_TIPO_OPERACION_INI FECXP_POLITICAS_ERP.TIPO_OPERACION_INI%TYPE;
	V_TIPO_OPERACION_FIN FECXP_POLITICAS_ERP.TIPO_OPERACION_FIN%TYPE;

	CURSOR CURSOR_CLASIFICACION_FE_ORACLE IS
	SELECT	 CLA_FE_ID, POLITICA_ERP_ID, PRIORIDAD, ORACLE_SEGMENTO1_INI, ORACLE_SEGMENTO1_FIN, ORACLE_SEGMENTO2_INI, ORACLE_SEGMENTO2_FIN, ORACLE_SEGMENTO3_INI, ORACLE_SEGMENTO3_FIN, ORACLE_SEGMENTO4_INI, ORACLE_SEGMENTO4_FIN, ORACLE_SEGMENTO5_INI, ORACLE_SEGMENTO5_FIN, ORACLE_SEGMENTO6_INI, ORACLE_SEGMENTO6_FIN, ORACLE_SEGMENTO7_INI, ORACLE_SEGMENTO7_FIN, TIPO_OPERACION_INI, TIPO_OPERACION_FIN
	FROM	 FECXP_POLITICAS_ERP
	WHERE	ID_TIPO_MOVTO IN ('A', 'E')
	ORDER BY PRIORIDAD ASC;

BEGIN

	INSERT	INTO FECXP_REP_PPTO_COM_CTA_ERP (CLA_FE_ID, E_CODIGO, CODE_COMBINATION_ID, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7)
	SELECT	DISTINCT '|', E_CODIGO, CODE_COMBINATION_ID, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
	FROM	FECXP_PPTO_OPERA_ERP
	WHERE	PERIODO_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))
	AND		MES_DE_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));

	OPEN  CURSOR_CLASIFICACION_FE_ORACLE;
	LOOP
		FETCH CURSOR_CLASIFICACION_FE_ORACLE
		INTO  V_CLA_FE_ID, V_PRIORIDAD, V_POLITICA_ERP_ID, V_ORA_S1_INI, V_ORA_S1_FIN, V_ORA_S2_INI, V_ORA_S2_FIN, V_ORA_S3_INI, V_ORA_S3_FIN, V_ORA_S4_INI, V_ORA_S4_FIN, V_ORA_S5_INI, V_ORA_S5_FIN, V_ORA_S6_INI, V_ORA_S6_FIN, V_ORA_S7_INI, V_ORA_S7_FIN, V_TIPO_OPERACION_INI, V_TIPO_OPERACION_FIN;
        EXIT WHEN CURSOR_CLASIFICACION_FE_ORACLE%NOTFOUND;

  		-- CLASIFICACION DE CUENTAS CONTABLES ERP.
		UPDATE	FECXP_REP_PPTO_COM_CTA_ERP
		SET		CLA_FE_ID = V_CLA_FE_ID
		WHERE	(ORACLE_SEGMENTO1 >= NVL (V_ORA_S1_INI, '0'))
		AND		(ORACLE_SEGMENTO1 <= NVL (V_ORA_S1_FIN, 'z'))
		AND		(ORACLE_SEGMENTO2 >= NVL (V_ORA_S2_INI, '0'))
		AND		(ORACLE_SEGMENTO2 <= NVL (V_ORA_S2_FIN, 'z'))
		AND		(ORACLE_SEGMENTO3 >= NVL (V_ORA_S3_INI, '0'))
		AND		(ORACLE_SEGMENTO3 <= NVL (V_ORA_S3_FIN, 'z'))
		AND		(ORACLE_SEGMENTO4 >= NVL (V_ORA_S4_INI, '0'))
		AND		(ORACLE_SEGMENTO4 <= NVL (V_ORA_S4_FIN, 'z'))
		AND		(ORACLE_SEGMENTO5 >= NVL (V_ORA_S5_INI, '0'))
		AND		(ORACLE_SEGMENTO5 <= NVL (V_ORA_S5_FIN, 'z'))
		AND		(ORACLE_SEGMENTO6 >= NVL (V_ORA_S6_INI, '0'))
		AND		(ORACLE_SEGMENTO6 <= NVL (V_ORA_S6_FIN, 'z'))
		AND		(ORACLE_SEGMENTO7 >= NVL (V_ORA_S7_INI, '0'))
		AND		(ORACLE_SEGMENTO7 <= NVL (V_ORA_S7_FIN, 'z'))
		AND		NVL(V_TIPO_OPERACION_INI, 0) = 0
		AND		NVL(V_TIPO_OPERACION_FIN, 0) = 0
		AND		NVL (CLA_FE_ID, '|') = '|';
	END LOOP;
	CLOSE CURSOR_CLASIFICACION_FE_ORACLE;


	DELETE	FECXP_REP_PPTO_COMP_O_ERP;

	DELETE	FECXP_REP_PPTO_COMP_C_ERP;

	INSERT	INTO FECXP_REP_PPTO_COMP_O_ERP (
			E_CODIGO, PERIODO_EXTRACCION, MES_DE_EXTRACCION, PERIODO_PPTO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION_ID,
			ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7,
			PPTO_01, PSS_01, USD_01, EUR_01,
			PPTO_02, PSS_02, USD_02, EUR_02,
			PPTO_03, PSS_03, USD_03, EUR_03,
			PPTO_04, PSS_04, USD_04, EUR_04,
			PPTO_05, PSS_05, USD_05, EUR_05,
			PPTO_06, PSS_06, USD_06, EUR_06,
			PPTO_07, PSS_07, USD_07, EUR_07,
			PPTO_08, PSS_08, USD_08, EUR_08,
			PPTO_09, PSS_09, USD_09, EUR_09,
			PPTO_10, PSS_10, USD_10, EUR_10,
			PPTO_11, PSS_11, USD_11, EUR_11,
			PPTO_12, PSS_12, USD_12, EUR_12)
	SELECT	E_CODIGO, PERIODO_EXTRACCION, MES_DE_EXTRACCION, PERIODO_PPTO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION_ID,
			ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7,
			PPTO_01, PSS_01, USD_01, EUR_01,
			PPTO_02, PSS_02, USD_02, EUR_02,
			PPTO_03, PSS_03, USD_03, EUR_03,
			PPTO_04, PSS_04, USD_04, EUR_04,
			PPTO_05, PSS_05, USD_05, EUR_05,
			PPTO_06, PSS_06, USD_06, EUR_06,
			PPTO_07, PSS_07, USD_07, EUR_07,
			PPTO_08, PSS_08, USD_08, EUR_08,
			PPTO_09, PSS_09, USD_09, EUR_09,
			PPTO_10, PSS_10, USD_10, EUR_10,
			PPTO_11, PSS_11, USD_11, EUR_11,
			PPTO_12, PSS_12, USD_12, EUR_12
	FROM	FECXP_PPTO_OPERA_ERP
	WHERE	PERIODO_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))
	AND		MES_DE_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));


	INSERT	INTO FECXP_REP_PPTO_COMP_C_ERP (
			E_CODIGO, PERIODO_EXTRACCION, MES_DE_EXTRACCION, PERIODO_PPTO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION_ID, PPTO_01, PRESUPUESTO_ESTATUS)
	SELECT	E_CODIGO, PERIODO_EXTRACCION, MES_EXTRACCION, PERIODO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION, IMPORTE_LINEA, PRESUPUESTO_ESTATUS
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	MES = 1
	AND		PERIODO_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))
	AND		MES_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));


	INSERT	INTO FECXP_REP_PPTO_COMP_C_ERP (
			E_CODIGO, PERIODO_EXTRACCION, MES_DE_EXTRACCION, PERIODO_PPTO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION_ID, PPTO_02, PRESUPUESTO_ESTATUS)
	SELECT	E_CODIGO, PERIODO_EXTRACCION, MES_EXTRACCION, PERIODO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION, IMPORTE_LINEA, PRESUPUESTO_ESTATUS
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	MES = 2
	AND		PERIODO_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))
	AND		MES_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));


	INSERT	INTO FECXP_REP_PPTO_COMP_C_ERP (
			E_CODIGO, PERIODO_EXTRACCION, MES_DE_EXTRACCION, PERIODO_PPTO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION_ID, PPTO_03, PRESUPUESTO_ESTATUS)
	SELECT	E_CODIGO, PERIODO_EXTRACCION, MES_EXTRACCION, PERIODO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION, IMPORTE_LINEA, PRESUPUESTO_ESTATUS
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	MES = 3
	AND		PERIODO_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))
	AND		MES_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));


	INSERT	INTO FECXP_REP_PPTO_COMP_C_ERP (
			E_CODIGO, PERIODO_EXTRACCION, MES_DE_EXTRACCION, PERIODO_PPTO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION_ID, PPTO_04, PRESUPUESTO_ESTATUS)
	SELECT	E_CODIGO, PERIODO_EXTRACCION, MES_EXTRACCION, PERIODO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION, IMPORTE_LINEA, PRESUPUESTO_ESTATUS
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	MES = 4
	AND		PERIODO_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))
	AND		MES_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));


	INSERT	INTO FECXP_REP_PPTO_COMP_C_ERP (
			E_CODIGO, PERIODO_EXTRACCION, MES_DE_EXTRACCION, PERIODO_PPTO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION_ID, PPTO_05, PRESUPUESTO_ESTATUS)
	SELECT	E_CODIGO, PERIODO_EXTRACCION, MES_EXTRACCION, PERIODO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION, IMPORTE_LINEA, PRESUPUESTO_ESTATUS
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	MES = 5
	AND		PERIODO_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))
	AND		MES_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));


	INSERT	INTO FECXP_REP_PPTO_COMP_C_ERP (
			E_CODIGO, PERIODO_EXTRACCION, MES_DE_EXTRACCION, PERIODO_PPTO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION_ID, PPTO_06, PRESUPUESTO_ESTATUS)
	SELECT	E_CODIGO, PERIODO_EXTRACCION, MES_EXTRACCION, PERIODO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION, IMPORTE_LINEA, PRESUPUESTO_ESTATUS
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	MES = 6
	AND		PERIODO_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))
	AND		MES_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));


	INSERT	INTO FECXP_REP_PPTO_COMP_C_ERP (
			E_CODIGO, PERIODO_EXTRACCION, MES_DE_EXTRACCION, PERIODO_PPTO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION_ID, PPTO_07, PRESUPUESTO_ESTATUS)
	SELECT	E_CODIGO, PERIODO_EXTRACCION, MES_EXTRACCION, PERIODO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION, IMPORTE_LINEA, PRESUPUESTO_ESTATUS
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	MES = 7
	AND		PERIODO_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))
	AND		MES_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));


	INSERT	INTO FECXP_REP_PPTO_COMP_C_ERP (
			E_CODIGO, PERIODO_EXTRACCION, MES_DE_EXTRACCION, PERIODO_PPTO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION_ID, PPTO_08, PRESUPUESTO_ESTATUS)
	SELECT	E_CODIGO, PERIODO_EXTRACCION, MES_EXTRACCION, PERIODO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION, IMPORTE_LINEA, PRESUPUESTO_ESTATUS
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	MES = 8
	AND		PERIODO_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))
	AND		MES_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));


	INSERT	INTO FECXP_REP_PPTO_COMP_C_ERP (
			E_CODIGO, PERIODO_EXTRACCION, MES_DE_EXTRACCION, PERIODO_PPTO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION_ID, PPTO_09, PRESUPUESTO_ESTATUS)
	SELECT	E_CODIGO, PERIODO_EXTRACCION, MES_EXTRACCION, PERIODO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION, IMPORTE_LINEA, PRESUPUESTO_ESTATUS
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	MES = 9
	AND		PERIODO_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))
	AND		MES_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));


	INSERT	INTO FECXP_REP_PPTO_COMP_C_ERP (
			E_CODIGO, PERIODO_EXTRACCION, MES_DE_EXTRACCION, PERIODO_PPTO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION_ID, PPTO_10, PRESUPUESTO_ESTATUS)
	SELECT	E_CODIGO, PERIODO_EXTRACCION, MES_EXTRACCION, PERIODO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION, IMPORTE_LINEA, PRESUPUESTO_ESTATUS
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	MES = 10
	AND		PERIODO_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))
	AND		MES_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));


	INSERT	INTO FECXP_REP_PPTO_COMP_C_ERP (
			E_CODIGO, PERIODO_EXTRACCION, MES_DE_EXTRACCION, PERIODO_PPTO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION_ID, PPTO_11, PRESUPUESTO_ESTATUS)
	SELECT	E_CODIGO, PERIODO_EXTRACCION, MES_EXTRACCION, PERIODO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION, IMPORTE_LINEA, PRESUPUESTO_ESTATUS
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	MES = 11
	AND		PERIODO_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))
	AND		MES_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));


	INSERT	INTO FECXP_REP_PPTO_COMP_C_ERP (
			E_CODIGO, PERIODO_EXTRACCION, MES_DE_EXTRACCION, PERIODO_PPTO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION_ID, PPTO_12, PRESUPUESTO_ESTATUS)
	SELECT	E_CODIGO, PERIODO_EXTRACCION, MES_EXTRACCION, PERIODO, LIBRO_ID, VERSION_ID, MONEDA, CODE_COMBINATION, IMPORTE_LINEA, PRESUPUESTO_ESTATUS
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	MES = 12
	AND		PERIODO_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))
	AND		MES_EXTRACCION = TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));

END;


EXCEPTION
WHEN NO_DATA_FOUND THEN
 RAISE_APPLICATION_ERROR(-20000,'No hay datos nuevos.');
END FECXP_LLENA_PPTO_ORACLE12MCT;
/
