CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_BALANZAS_COMPROBACION" IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
BEGIN
----- Extrae e Inserta los Saldos ----
INSERT INTO FECXP_SALDOS_OPERATIVO_ERP (
	   SECUENCIA_SALDOS_OPERA_ERP,
	   E_CODIGO,
	   PERIODO_EXTRACCION,
	   MES_DE_EXTRACCION,
	   LIBRO_ID,
	   MONEDA,
	   CODE_COMBINATION_ID,
	   ORACLE_SEGMENTO1,
	   ORACLE_SEGMENTO2,
	   ORACLE_SEGMENTO3,
	   ORACLE_SEGMENTO4,
	   ORACLE_SEGMENTO5,
	   ORACLE_SEGMENTO6,
	   ORACLE_SEGMENTO7,
	   PERIODO,
	   MES,
	   SALDO_INICIAL_MO,
	   DEBITO_INICIAL_MO,
	   CREDITO_INICIAL_MO,
	   SALDO_FINAL_MO,
	   SALDO_INICIAL_ME,
	   DEBITO_INICIAL_ME,
	   CREDITO_INICIAL_ME,
	   SALDO_FINAL_ME)
SELECT  SECUENCIA_SALDOS_OPERA_ERP.NEXTVAL,
		GCC.SEGMENT1,
		to_number(to_char(sysdate,'YY')),
		to_number(to_char(sysdate,'MM')),
		GLB.SET_OF_BOOKS_ID	AS	LIBRO_ID,
		GLB.CURRENCY_CODE	AS MONEDA,
		GCC.CODE_COMBINATION_ID	AS	CODE_COMBINATION_ID,
		GCC.SEGMENT1		AS		ORACLE_SEGMENT01,
		GCC.SEGMENT2		AS		ORACLE_SEGMENT02,
		GCC.SEGMENT3		AS		ORACLE_SEGMENT03,
		GCC.SEGMENT4		AS		ORACLE_SEGMENT04,
		GCC.SEGMENT5		AS		ORACLE_SEGMENT05,
		GCC.SEGMENT6		AS		ORACLE_SEGMENT06,
		GCC.SEGMENT7		AS		ORACLE_SEGMENT07,
		GLB.PERIOD_YEAR 	AS PERIODO,
		GLB.PERIOD_NUM		AS MES,
		NVL(GLB.BEGIN_BALANCE_DR - GLB.BEGIN_BALANCE_CR,0) AS SALDO_INICIAL_MO,
		NVL(GLB.PERIOD_NET_DR,0)   AS DEBITO_INICIAL_MO,
		NVL(GLB.PERIOD_NET_CR,0)   AS CREDITO_INICIAL_MO,
		NVL(GLB.BEGIN_BALANCE_DR - GLB.BEGIN_BALANCE_CR + GLB.PERIOD_NET_DR - GLB.PERIOD_NET_CR,0)  AS  SALDO_FINAL_MO,
		NVL(GLB.BEGIN_BALANCE_DR_BEQ - GLB.BEGIN_BALANCE_CR_BEQ,0) AS SALDO_INICIAL_ME,
		NVL(GLB.PERIOD_NET_DR_BEQ,0) AS DEBITO_FINAL_ME,
		NVL(GLB.PERIOD_NET_CR_BEQ,0) AS CREDITO_INICIAL_ME,
		NVL(GLB.BEGIN_BALANCE_DR_BEQ-GLB.BEGIN_BALANCE_CR_BEQ+GLB.PERIOD_NET_DR_BEQ-GLB.PERIOD_NET_CR_BEQ,0) AS SALDO_FINAL_ME
FROM	GL_CODE_COMBINATIONS@ERP_PROD GCC, GL_BALANCES@ERP_PROD GLB
WHERE 	GLB.CURRENCY_CODE <> 'PSS'
AND 	GCC.ENABLED_FLAG='Y'
AND 	GCC.SUMMARY_FLAG='N'
AND 	GCC.CHART_OF_ACCOUNTS_ID='101'
AND		GLB.PERIOD_YEAR = to_char(sysdate,'YYYY')
AND 	GLB.PERIOD_NUM >= 1
AND		GLB.ACTUAL_FLAG = 'A'
AND 	GCC.CODE_COMBINATION_ID = GLB.CODE_COMBINATION_ID;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20000,'No hay datos nuevos.');
END FECXP_BALANZAS_COMPROBACION;
/
