CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_COPIA_PPTO_ERP" (
	V_VERSION_FE_INI IN INTEGER,
	V_VERSION_FE_FIN IN INTEGER,
	V_USUARIO_ID IN VARCHAR2,
	V_COMENTARIO IN VARCHAR2
) IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
   V_PERIODO INTEGER;
   V_VERSION INTEGER;
BEGIN
	-----------------------------------------------------------------------------------------------------------
	-- OBTIENE PERIODO Y VERSION DEL PPTO
	SELECT	PERIODO_ORIGEN, V_VERSION_FE_INI
	INTO	V_PERIODO, V_VERSION
	FROM	FECXP_PPTO_OPERA_ERP_ENC
	WHERE	VERSION_FE = V_VERSION_FE_INI
	GROUP BY PERIODO_ORIGEN;
	-----------------------------------------------------------------------------------------------------------
	-- BORRA ENCABEZADO Y DETALLE DE PPTO OPERATIVO
	DELETE	FECXP_PPTO_OPERA_ERP_ENC
	WHERE	VERSION_FE = V_VERSION_FE_FIN;
	DELETE	FECXP_PPTO_OPERA_ERP
	WHERE	VERSION_FE = V_VERSION_FE_FIN;
	COMMIT;
	-----------------------------------------------------------------------------------------------------------
	-- INSERTA ENCABEZADO Y DETALLE DE PPTO OPERATIVO
	INSERT	INTO FECXP_PPTO_OPERA_ERP (
			E_CODIGO,
			SECUENCIA_PTTO_ORACLE,
			PERIODO_EXTRACCION,
			MES_DE_EXTRACCION,
			PERIODO_PPTO,
			LIBRO_ID,
			VERSION_ID,
			MONEDA,
			CODE_COMBINATION_ID,
			ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3,
			ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7,
			PPTO_01, PSS_01, USD_01, EUR_01,
			PPTO_02, PSS_02, USD_02, EUR_02,
			PPTO_03, PSS_03, USD_03, EUR_03,
			PPTO_04, PSS_04, USD_04, EUR_04,
			PPTO_05, PSS_05, USD_05, EUR_05,
			PPTO_06, PSS_06, USD_06, EUR_06,
			PPTO_07, PSS_07, USD_07, EUR_07,
			PPTO_08, PSS_08, USD_08, EUR_08,
			PPTO_09, PSS_09, USD_09, EUR_09,
			PPTO_10, PSS_10, USD_10, EUR_10,
			PPTO_11, PSS_11, USD_11, EUR_11,
			PPTO_12, PSS_12, USD_12, EUR_12,
			VERSION_FE)
	SELECT  E_CODIGO,
			SECUENCIA_PTTO_ORACLE.NEXTVAL,
			PERIODO_EXTRACCION,
			MES_DE_EXTRACCION,
			PERIODO_PPTO,
			LIBRO_ID,
			VERSION_ID,
			MONEDA,
			CODE_COMBINATION_ID,
			ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3,
			ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7,
			PPTO_01, PSS_01, USD_01, EUR_01,
			PPTO_02, PSS_02, USD_02, EUR_02,
			PPTO_03, PSS_03, USD_03, EUR_03,
			PPTO_04, PSS_04, USD_04, EUR_04,
			PPTO_05, PSS_05, USD_05, EUR_05,
			PPTO_06, PSS_06, USD_06, EUR_06,
			PPTO_07, PSS_07, USD_07, EUR_07,
			PPTO_08, PSS_08, USD_08, EUR_08,
			PPTO_09, PSS_09, USD_09, EUR_09,
			PPTO_10, PSS_10, USD_10, EUR_10,
			PPTO_11, PSS_11, USD_11, EUR_11,
			PPTO_12, PSS_12, USD_12, EUR_12,
			V_VERSION_FE_FIN
	FROM	FECXP_PPTO_OPERA_ERP
	WHERE	VERSION_FE = V_VERSION_FE_INI;
	COMMIT;
	INSERT	INTO FECXP_PPTO_OPERA_ERP_ENC (
			VERSION_FE, COMENTARIO, USUARIO_ID, FECHA_EXTRACCION, VERSION_REGLAS, FECHA_VERSION_REGLAS, PERIODO_ORIGEN, VERSION_ORIGEN, ESTATUS_ORIGEN, VERSION_FE_ORIGEN)
	SELECT	VERSION_FE, V_COMENTARIO, V_USUARIO_ID, SYSDATE, 0, TO_DATE ('19000101', 'YYYYMMDD'), PERIODO_EXTRACCION, VERSION_ID, 'V', V_VERSION_FE_INI
	FROM	FECXP_PPTO_OPERA_ERP
	WHERE	VERSION_FE = V_VERSION_FE_FIN
	GROUP BY VERSION_FE, PERIODO_EXTRACCION, VERSION_ID;
	COMMIT;
	-----------------------------------------------------------------------------------------------------------
	-- BORRA ENCABEZADO Y DETALLE DE PPTO CONVERTIDO
	DELETE	FECXP_PPTO_CONVERSION_ERP_ENC
	WHERE	VERSION_FE = V_VERSION_FE_FIN;
	DELETE	FECXP_PPTO_CONVERSION_ERP
	WHERE	VERSION_FE = V_VERSION_FE_FIN;
	COMMIT;
	-----------------------------------------------------------------------------------------------------------
	-- INSERTA ENCABEZADO Y DETALLE DE PPTO CONVERTIDO
	INSERT	INTO FECXP_PPTO_CONVERSION_ERP (
			E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
			MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
			ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
			ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS, VERSION_FE)
	SELECT	E_CODIGO, SECUENCIA_PTTO_CONVERSION, PERIODO, MES, LIBRO_ID, VERSION_ID,
			MONEDA, TIPO_CAMBIO, CODE_COMBINATION, IMPORTE_LINEA, ORACLE_SEGMENTO1,
			ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6,
			ORACLE_SEGMENTO7, PERIODO_EXTRACCION, MES_EXTRACCION, PRESUPUESTO_ESTATUS, V_VERSION_FE_FIN
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	VERSION_FE = V_VERSION_FE_INI;
	COMMIT;
	INSERT	INTO FECXP_PPTO_CONVERSION_ERP_ENC (
			VERSION_FE, COMENTARIO, USUARIO_ID, FECHA_EXTRACCION, VERSION_REGLAS, FECHA_VERSION_REGLAS, PERIODO_ORIGEN, VERSION_ORIGEN, ESTATUS_ORIGEN, VERSION_FE_ORIGEN)
	SELECT	V_VERSION_FE_FIN, V_COMENTARIO, V_USUARIO_ID, SYSDATE, 0, TO_DATE ('19000101', 'YYYYMMDD'), PERIODO_EXTRACCION, VERSION_ID, 'V', V_VERSION_FE_INI
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	VERSION_FE = V_VERSION_FE_INI
	GROUP BY VERSION_FE, PERIODO_EXTRACCION, VERSION_ID;
	COMMIT;
	-----------------------------------------------------------------------------------------------------------
	-- INSERTA BITACORA
	INSERT	INTO FECXP_PPTO_BITACORA_PROCESOS (
			SEC_EXT_BITACORA, PROCESO_ID, FECHA_EXT_ULT_EJECUCION, ESTATUS_EXT_ULT_EJECUCION, PERIODO_PPTO_ULT_EJECUCION, VERSION_PPTO_ULT_EJECUCION, ESTATUS_PPTO_ULT_EJECUCION, VERSION_PPTO_GENERADO)
	VALUES	(SEC_EXT_BITACORA.NEXTVAL, 3,  SYSDATE, 'COPIA EXITOSA VI: ' || TO_CHAR (V_VERSION_FE_INI) || ' VF: ' || TO_CHAR (V_VERSION_FE_FIN), V_PERIODO, V_VERSION, 'V', V_VERSION_FE_FIN);
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20000,'No hay datos nuevos.');
END FECXP_COPIA_PPTO_ERP;
/
