CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."FECXP_LLENA_DET_PPTO_ERP" (
	V_VERSION_FE IN NUMBER,
	V_MES_DESDE IN NUMBER,
	V_MES_HASTA IN NUMBER,
	V_ECODIGO_DESDE IN NUMBER,
    V_ECODIGO_HASTA IN NUMBER
)
IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
	V_PERIODO INTEGER:= TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'));
	V_MES_ACT INTEGER := TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));
	V_CLA_FE_ID FECXP_POLITICAS_ERP.CLA_FE_ID%TYPE;
	V_PRIORIDAD FECXP_POLITICAS_ERP.PRIORIDAD%TYPE;
	V_TIPO_OPERACION_INI FECXP_POLITICAS_ERP.TIPO_OPERACION_INI%TYPE;
	V_TIPO_OPERACION_FIN FECXP_POLITICAS_ERP.TIPO_OPERACION_FIN%TYPE;
	V_ID_BANCO_INI FECXP_POLITICAS_ERP.ID_BANCO_INI%TYPE;
	V_ID_BANCO_FIN FECXP_POLITICAS_ERP.ID_BANCO_FIN%TYPE;
	V_ID_CHEQUERA_INI FECXP_POLITICAS_ERP.ID_CHEQUERA_INI%TYPE;
	V_ID_CHEQUERA_FIN FECXP_POLITICAS_ERP.ID_CHEQUERA_FIN%TYPE;
	V_POLITICA_ERP_ID FECXP_POLITICAS_ERP.POLITICA_ERP_ID%TYPE;
	V_ORA_S1_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_INI%TYPE;
	V_ORA_S1_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_FIN%TYPE;
	V_ORA_S2_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_INI%TYPE;
	V_ORA_S2_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_FIN%TYPE;
	V_ORA_S3_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_INI%TYPE;
	V_ORA_S3_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_FIN%TYPE;
	V_ORA_S4_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_INI%TYPE;
	V_ORA_S4_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_FIN%TYPE;
	V_ORA_S5_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_INI%TYPE;
	V_ORA_S5_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_FIN%TYPE;
	V_ORA_S6_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_INI%TYPE;
	V_ORA_S6_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_FIN%TYPE;
	V_ORA_S7_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_INI%TYPE;
	V_ORA_S7_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_FIN%TYPE;
	CURSOR	CURSOR_CLASIFICACION_FE_ING IS
	SELECT	CLA_FE_ID, POLITICA_ERP_ID, PRIORIDAD, TIPO_OPERACION_INI, TIPO_OPERACION_FIN, ID_BANCO_INI, ID_BANCO_FIN, ID_CHEQUERA_INI, ID_CHEQUERA_FIN,
			ORACLE_SEGMENTO1_INI, ORACLE_SEGMENTO1_FIN, ORACLE_SEGMENTO2_INI, ORACLE_SEGMENTO2_FIN, ORACLE_SEGMENTO3_INI, ORACLE_SEGMENTO3_FIN, ORACLE_SEGMENTO4_INI, ORACLE_SEGMENTO4_FIN, ORACLE_SEGMENTO5_INI, ORACLE_SEGMENTO5_FIN, ORACLE_SEGMENTO6_INI, ORACLE_SEGMENTO6_FIN, ORACLE_SEGMENTO7_INI, ORACLE_SEGMENTO7_FIN
	FROM	FECXP_POLITICAS_ERP
	WHERE	ID_TIPO_MOVTO IN ('A', 'I')
	AND		ACTIVA_REGLA = 1
	ORDER BY PRIORIDAD ASC;
	CURSOR	CURSOR_CLASIFICACION_FE_EGR IS
	SELECT	CLA_FE_ID, POLITICA_ERP_ID, PRIORIDAD, TIPO_OPERACION_INI, TIPO_OPERACION_FIN, ID_BANCO_INI, ID_BANCO_FIN, ID_CHEQUERA_INI, ID_CHEQUERA_FIN,
			ORACLE_SEGMENTO1_INI, ORACLE_SEGMENTO1_FIN, ORACLE_SEGMENTO2_INI, ORACLE_SEGMENTO2_FIN, ORACLE_SEGMENTO3_INI, ORACLE_SEGMENTO3_FIN, ORACLE_SEGMENTO4_INI, ORACLE_SEGMENTO4_FIN, ORACLE_SEGMENTO5_INI, ORACLE_SEGMENTO5_FIN, ORACLE_SEGMENTO6_INI, ORACLE_SEGMENTO6_FIN, ORACLE_SEGMENTO7_INI, ORACLE_SEGMENTO7_FIN
	FROM	FECXP_POLITICAS_ERP
	WHERE	ID_TIPO_MOVTO IN ('A', 'E')
	AND		ACTIVA_REGLA = 1
	ORDER BY PRIORIDAD ASC;
BEGIN
	/*Modificacion Agosto 09 v8 Separacion entre reales y ppto y a?adir parametros*/
    /*Proviene de FECXP_LLENA_DET_CONT_ERP*/
	/*Modificacion Mayo 09 v4  Referencia,Desc y NoCte */
	/*Modificacion Abr 09 v3.  Crear Detalles de Inversion y Coinversion*/
	/*Modificacion Dic 08 v2.*/
--===============================================================================================--
	--== EMPIEZA PPTO ==--
    delete FECXP_DEL_PPTO_COM_CTA_ERP;
    INSERT INTO FECXP_DEL_PPTO_COM_CTA_ERP
    SELECT	DISTINCT E_CODIGO, CODE_COMBINATION, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3,ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	E_CODIGO >= V_ECODIGO_DESDE
    AND		E_CODIGO <= V_ECODIGO_HASTA
	AND		MES >= V_MES_DESDE
    AND		MES <= V_MES_HASTA
    AND		VERSION_FE = V_VERSION_FE
    ;
    commit;
	--== LIMPIA TABLA DE ENLACE  ==--
	DELETE	FECXP_REP_PPTO_COM_CTA_ERP  A -- FECXP_CTAS_CLASIF_PPTO_ERP; -- FECXP_CUENTAS_ERP_CARATULA MENOS (MONEDA, ID_SESION)
	WHERE	EXISTS
    (
    	SELECT 1
        FROM FECXP_PPTO_CONVERSION_ERP D
    	WHERE	D.E_CODIGO >= V_ECODIGO_DESDE
        AND		D.E_CODIGO <= V_ECODIGO_HASTA
        AND		D.MES >= V_MES_DESDE
        AND		D.MES <= V_MES_HASTA
    	AND		D.VERSION_FE = V_VERSION_FE
        AND		nvl(A.ORACLE_SEGMENTO1,'0') =  nvl(D.ORACLE_SEGMENTO1,'0')
        AND		nvl(A.ORACLE_SEGMENTO2,'0') = nvl(D.ORACLE_SEGMENTO2,'0')
        AND		nvl(A.ORACLE_SEGMENTO3,'0') = nvl(D.ORACLE_SEGMENTO3,'0')
        AND		nvl(A.ORACLE_SEGMENTO4,'0') = nvl(D.ORACLE_SEGMENTO4,'0')
        AND		nvl(A.ORACLE_SEGMENTO5,'0') = nvl(D.ORACLE_SEGMENTO5,'0')
        AND		nvl(A.ORACLE_SEGMENTO6,'0') = nvl(D.ORACLE_SEGMENTO6,'0')
        AND		nvl(A.ORACLE_SEGMENTO7,'0') = nvl(D.ORACLE_SEGMENTO7,'0')
    )
    ;
	COMMIT;
	--== SE CARGAN LAS CUENTAS CONTABLES DEL PRESUPUESTO  ==--
	/*INSERT	INTO FECXP_REP_PPTO_COM_CTA_ERP (CLA_FE_ID, E_CODIGO, CODE_COMBINATION_ID, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7)
	SELECT	DISTINCT '|'AS CLA_FE_ID, E_CODIGO, CODE_COMBINATION, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3,ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
	FROM	FECXP_PPTO_CONVERSION_ERP
	WHERE	E_CODIGO >= V_ECODIGO_DESDE
    AND		E_CODIGO <= V_ECODIGO_HASTA
	AND		MES >= V_MES_DESDE
    AND		MES <= V_MES_HASTA
    AND		VERSION_FE = V_VERSION_FE
    ;*/
    INSERT	INTO FECXP_REP_PPTO_COM_CTA_ERP (CLA_FE_ID, E_CODIGO, CODE_COMBINATION_ID, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7)
	SELECT	DISTINCT '|'AS CLA_FE_ID, E_CODIGO, CODE_COMBINATION_ID, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3,ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
	FROM	FECXP_DEL_PPTO_COM_CTA_ERP;
	COMMIT;
	--==  CLASIFICACION DE CUENTAS SESGUN POLITICAS DE CLASIFICACION DE FE ==--
	OPEN	CURSOR_CLASIFICACION_FE_EGR;
	LOOP
		FETCH	CURSOR_CLASIFICACION_FE_EGR
		INTO	V_CLA_FE_ID, V_POLITICA_ERP_ID, V_PRIORIDAD, V_TIPO_OPERACION_INI, V_TIPO_OPERACION_FIN, V_ID_BANCO_INI, V_ID_BANCO_FIN, V_ID_CHEQUERA_INI, V_ID_CHEQUERA_FIN,
				V_ORA_S1_INI, V_ORA_S1_FIN, V_ORA_S2_INI, V_ORA_S2_FIN, V_ORA_S3_INI, V_ORA_S3_FIN, V_ORA_S4_INI, V_ORA_S4_FIN, V_ORA_S5_INI, V_ORA_S5_FIN, V_ORA_S6_INI, V_ORA_S6_FIN, V_ORA_S7_INI, V_ORA_S7_FIN;
		EXIT WHEN CURSOR_CLASIFICACION_FE_EGR%NOTFOUND;
		UPDATE	FECXP_REP_PPTO_COM_CTA_ERP
		SET		CLA_FE_ID = V_CLA_FE_ID
		WHERE	(ORACLE_SEGMENTO1 >= NVL (V_ORA_S1_INI, '0'))
		AND		(ORACLE_SEGMENTO1 <= NVL (V_ORA_S1_FIN, 'z'))
		AND		(ORACLE_SEGMENTO2 >= NVL (V_ORA_S2_INI, '0'))
		AND		(ORACLE_SEGMENTO2 <= NVL (V_ORA_S2_FIN, 'z'))
		AND		(ORACLE_SEGMENTO3 >= NVL (V_ORA_S3_INI, '0'))
		AND		(ORACLE_SEGMENTO3 <= NVL (V_ORA_S3_FIN, 'z'))
		AND		(ORACLE_SEGMENTO4 >= NVL (V_ORA_S4_INI, '0'))
		AND		(ORACLE_SEGMENTO4 <= NVL (V_ORA_S4_FIN, 'z'))
		AND		(ORACLE_SEGMENTO5 >= NVL (V_ORA_S5_INI, '0'))
		AND		(ORACLE_SEGMENTO5 <= NVL (V_ORA_S5_FIN, 'z'))
		AND		(ORACLE_SEGMENTO6 >= NVL (V_ORA_S6_INI, '0'))
		AND		(ORACLE_SEGMENTO6 <= NVL (V_ORA_S6_FIN, 'z'))
		AND		(ORACLE_SEGMENTO7 >= NVL (V_ORA_S7_INI, '0'))
		AND		(ORACLE_SEGMENTO7 <= NVL (V_ORA_S7_FIN, 'z'))
		AND		NVL(V_TIPO_OPERACION_INI, 0) = 0
		AND		NVL(V_TIPO_OPERACION_FIN, 0) = 0
		AND		NVL (V_ID_BANCO_INI, 0) = 0
		AND		NVL (V_ID_BANCO_FIN, 0) = 0
		AND		NVL (LPAD (V_ID_CHEQUERA_INI, 20, '0'), '00000000000000000000') = '00000000000000000000'
		AND		NVL (LPAD (V_ID_CHEQUERA_FIN, 20, '0'), '00000000000000000000') = '00000000000000000000'
		AND		E_CODIGO >= V_ECODIGO_DESDE
        AND		E_CODIGO <= V_ECODIGO_HASTA
		AND		NVL (CLA_FE_ID, '|') = '|';
		COMMIT;
	END LOOP;
	CLOSE	CURSOR_CLASIFICACION_FE_EGR;
	DELETE	FECXP_DET_CONT_VERSION_FE
	WHERE	PROCESO = 'FECXP_LLENA_DET_PPTO_ERP';
	INSERT	INTO FECXP_DET_CONT_VERSION_FE (
			PROCESO, VERSION_FE)
	VALUES (
		   'FECXP_LLENA_DET_PPTO_ERP', V_VERSION_FE);
	COMMIT;
	--===============================================================================================--
	--== TERMINA PPTO ==--
EXCEPTION
	WHEN NO_DATA_FOUND THEN
	RAISE_APPLICATION_ERROR(-20000,'NO HAY DATOS NUEVOS.');
    WHEN OTHERS THEN
       ROLLBACK;
       RAISE_APPLICATION_ERROR(-20000,'Error:' || SQLCODE || ' - ' || SQLERRM);
END FECXP_LLENA_DET_PPTO_ERP;
/
