CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."XXCHK_ASOCIAR_FOLIO_ACHEQUE" (
    p_ID_SEC_CHEQUE IN NUMBER,
    p_USUARIO    IN VARCHAR2
    )
AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
v_count       NUMBER;
v_ID_ESTADO_CHEQUE    NUMBER;
BEGIN
  select count(1)
  into v_count
  FROM XXCHK_CHEQUES_ALL
  WHERE ID_CHEQUE_SEL =p_ID_SEC_CHEQUE;
  IF v_count > 0 THEN
   BEGIN
    select count(1)
   into v_count
   FROM XXCHK_CHEQUES_ALL
      WHERE ID_CHEQUE_SEL =p_ID_SEC_CHEQUE
   group by ID_TIPO_OPERACION_SET, REFERENCIA_CLIENTE, MONEDA
   having count(1) > 1;
   exception
     when NO_DATA_FOUND then
      v_count:=0;
  END;
  IF v_count= 0 THEN
     FOR xxchk_row IN (SELECT A.E_CODIGO, A.NO_FOLIO_DET, A.ID_STATUS_MOV, A.ID_TIPO_OPERACION_SET,
                A.IMPORTE, A.MONEDA, A.REFERENCIA_CLIENTE, B.NO_CHEQUE
              FROM XXCHK_CHEQUES_ALL A, XXCHK_CAPTURA_CHEQUES B
       WHERE A.ID_CHEQUE_SEL = p_ID_SEC_CHEQUE
          AND B.ID_SEC_CHEQUE = p_ID_SEC_CHEQUE) LOOP
   update XXCHK_CHEQUES_ALL up_table
   SET PROCESADO = 1
   WHERE E_CODIGO = xxchk_row.E_CODIGO
      AND NO_FOLIO_DET = xxchk_row.NO_FOLIO_DET
      AND ID_STATUS_MOV = xxchk_row.ID_STATUS_MOV;
   BEGIN
    select ID_ESTADO_CHEQUE
    into v_ID_ESTADO_CHEQUE
    from XXCHK_MAPEO_DE_ESTADOS
    where ID_TIPO_OPERACION_SET = xxchk_row.ID_TIPO_OPERACION_SET;
    exception
       when NO_DATA_FOUND then
          RAISE_APPLICATION_ERROR(-20000,'NO EXISTE LA RELACION DE OPERACION DEL SET VERSUS ESTADO DEL CHEQUE. FAVOR CREARLA Y VOLVER A APLICAR EL PROCESO');
   END;
   INSERT INTO XXCHK_CHEQ_ALL_HIST(
       E_CODIGO, NO_CHEQUE, ID_SEC_CHEQUE,
       NO_FOLIO_DET, DATE_CREATED, MODIFIED_BY,
       TIPO_CHEQ, REFERENCIA_CLIENTE, ID_TIPO_OPERACION_SET,
       PROCESADO, ID_ESTADO_CHEQUE)
   values (xxchk_row.E_CODIGO, xxchk_row.NO_CHEQUE, p_ID_SEC_CHEQUE,
       xxchk_row.NO_FOLIO_DET, sysdate, p_USUARIO,
       'MANUAL', xxchk_row.REFERENCIA_CLIENTE, xxchk_row.ID_TIPO_OPERACION_SET,
       1, v_ID_ESTADO_CHEQUE);
     END LOOP;
     update XXCHK_CAPTURA_CHEQUES up_table
     SET PROCESADO = 1, LAST_MODIFIED_DATE= SYSDATE(), ID_ESTADO_CHEQUE = v_ID_ESTADO_CHEQUE
     WHERE ID_SEC_CHEQUE = p_ID_SEC_CHEQUE;
  ELSE
     RAISE_APPLICATION_ERROR(-20000,'POR FAVOR SELECCIONE SOLO UN REGISTRO POR TIPO DE OPERACION, MONTO Y REFERENCIA.');
  END IF;
  ELSE
    RAISE_APPLICATION_ERROR(-20000,'NO SE HA ASOCIADO NINGUN FOLIO, POR FAVOR SELECCIONE UNO Y VUELVA A APLICAR ESTE PROCESO.');
  END IF;
COMMIT;
END;
/
