CREATE OR REPLACE EDITIONABLE PROCEDURE "FECXC"."XXCHK_ACEPTA_RECHAZO_SET" 
 (
 p_NO_FOLIO_DET		  		IN NUMBER,
 p_IMPORTE		   	  		IN NUMBER,
 p_ID_TIPO_OPERACION_SET    IN NUMBER,
 p_MONEDA					IN VARCHAR2,
 p_ID_USUARIO				IN NUMBER,
 p_USUARIO					IN VARCHAR2
)
IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
V_AYUDA INT;
V_SEC_ID_CHEQUE INT;
V_E_CODIGO INT;
V_FEC_VALOR_ORIGINAL DATE;
V_FEC_VALOR DATE;
V_ID_BANCO INT;
V_REFERENCIA_CLIENTE VARCHAR2(250);
V_ID_ESTADO_CHEQUE INT;
V_IMPORTE NUMERIC(30,4);
V_MONEDA VARCHAR2(250);
V_CUSTOMER_NAME VARCHAR2(250);
BEGIN
	 BEGIN
		SELECT XXCHK_SEC_ID_CHEQUE.NEXTVAL, A.E_CODIGO, A.FEC_VALOR_ORIGINAL,
			   NVL(A.FEC_VALOR,SYSDATE), A.ID_BANCO, A.REFERENCIA_CLIENTE, B.ID_ESTADO_CHEQUE, A.IMPORTE,
			   A.MONEDA
		INTO   V_SEC_ID_CHEQUE, V_E_CODIGO, V_FEC_VALOR_ORIGINAL,
			   V_FEC_VALOR, V_ID_BANCO, V_REFERENCIA_CLIENTE, V_ID_ESTADO_CHEQUE, V_IMPORTE,
			   V_MONEDA
		FROM XXCHK_CHEQUES_ALL A, XXCHK_MAPEO_DE_ESTADOS B
		WHERE	PROCESADO is null
		AND A.NO_FOLIO_DET = p_NO_FOLIO_DET
		AND	A.ID_TIPO_OPERACION_SET = B.ID_TIPO_OPERACION_SET
		AND	CHK_ORDEN = p_ID_USUARIO;
		DBMS_OUTPUT.PUT_LINE('V_SEC_ID_CHEQUE, V_E_CODIGO, V_FEC_VALOR_ORIGINAL,V_FEC_VALOR, V_ID_BANCO, V_REFERENCIA_CLIENTE, V_ID_ESTADO_CHEQUE, V_IMPORTE, V_MONEDA, V_NO_FOLIO_DET'||
							  TO_CHAR(V_SEC_ID_CHEQUE)||' - '||TO_CHAR(V_E_CODIGO)||' - '||TO_CHAR(V_FEC_VALOR_ORIGINAL)||' - '||TO_CHAR(V_FEC_VALOR)||' - '||TO_CHAR(V_ID_BANCO)||' - '||TO_CHAR(V_REFERENCIA_CLIENTE)||' - '||TO_CHAR(V_ID_ESTADO_CHEQUE)||' - '||TO_CHAR(V_IMPORTE)||' - '||TO_CHAR(V_MONEDA)||' - '||TO_CHAR(p_NO_FOLIO_DET));
	    EXCEPTION
	       WHEN no_data_found THEN
--		   		 DBMS_OUTPUT.PUT_LINE('NO HAY DATOS');
				 RAISE_APPLICATION_ERROR(-20000,'No ha seleccionado registros');
		   WHEN OTHERs THEN
--		   		DBMS_OUTPUT.PUT_LINE('Error desconocido');
				RAISE_APPLICATION_ERROR(-20000,'Unknown errors');
	END;
	SELECT CUSTOMER_NAME
	INTO V_CUSTOMER_NAME
	FROM XXCHK_CHEQUES_ALL  A,
		 RA_CUSTOMERS@ERP_PROD B
	WHERE A.NO_FOLIO_DET = p_NO_FOLIO_DET
	AND A.REFERENCIA_CLIENTE = B.ORIG_SYSTEM_REFERENCE;
	BEGIN
		INSERT INTO XXCHK_CAPTURA_CHEQUES(ID_SEC_CHEQUE, CREATED_BY, DATE_CREATED, E_CODIGO, ENTREGADO_POR, FECHA_COBRO,
											FECHA_EMISION, ID_BANCO, ID_CLIENTE, ID_ESTADO_CHEQUE, IMPORTE, LAST_MODIFIED_DATE,
											MODIFIED_BY, MONEDA, NO_CHEQUE, REFERENCIA_CLIENTE,EXPIDE,IMAGEN,DESC_CLIENTE)
		VALUES( V_SEC_ID_CHEQUE,p_USUARIO, SYSDATE, V_E_CODIGO, 'SISTEMA', V_FEC_VALOR_ORIGINAL,
			   V_FEC_VALOR, V_ID_BANCO, V_REFERENCIA_CLIENTE, V_ID_ESTADO_CHEQUE, V_IMPORTE, SYSDATE,
			   '', V_MONEDA, p_NO_FOLIO_DET, V_REFERENCIA_CLIENTE,'EXTRAIDO_SET','SIN IMAGEN',V_CUSTOMER_NAME);
		UPDATE XXCHK_CHEQUES_ALL SET PROCESADO = 1
		WHERE PROCESADO IS NULL
		AND   NO_FOLIO_DET = p_NO_FOLIO_DET
		AND	  CHK_ORDEN = p_ID_USUARIO;
		EXCEPTION
		  WHEN NO_DATA_FOUND THEN
		    RAISE_APPLICATION_ERROR(-20000,'No selecciono ningun registro.');
	END;
	BEGIN
	  FECXC.XXCHK_ENVIA_CHKS_MANUAL (V_SEC_ID_CHEQUE, 'SISTEMA', 80 );
	END;
END;
/
