CREATE OR REPLACE NONEDITIONABLE TRIGGER "USRDRC"."PENDIUM_OTORGAPODER_EP_TAB_TR1" 
BEFORE INSERT ON USRDRC.PENDIUM_OTORGAPODER_EP_TAB 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_OPODER_EP_PK IS NULL THEN
      SELECT PENDIUM_OTORGAPODER_EP_TAB_SE1.NEXTVAL INTO :NEW.ID_OPODER_EP_PK FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "USRDRC"."PENDIUM_OTORGAPODER_EP_TAB_TR1" ENABLE;
