CREATE OR REPLACE NONEDITIONABLE TRIGGER "USRDRC"."PENDIUM_REVOCA_EP_TAB_TRG1" 
BEFORE INSERT ON USRDRC.PENDIUM_REVOCA_EP_TAB 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_REVOCA_EP_PK IS NULL THEN
      SELECT PENDIUM_REVOCA_EP_SEQ.NEXTVAL INTO :NEW.ID_REVOCA_EP_PK FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "USRDRC"."PENDIUM_REVOCA_EP_TAB_TRG1" ENABLE;
