CREATE OR REPLACE EDITIONABLE PROCEDURE "XXMOR"."XXMOR_SEND_NOTIFY_UNKNWN_PR" (P_ID_SOLICITUD    IN INTEGER,
                                                        P_LINEAS          IN VARCHAR2
                                                       )
/*===============================================================
  FILE NAME :            XXMOR_SEND_NOTIFY_UNKNWN_PR.sql
  NOMBRE DEL MDULO :    MORDUNI
  CREATED DATE :         29-Sep-2014
  AUTHOR(S) :            SOIN
  SHORT DESCRIPTION :    Este script crea el procedimiento
                         XXMOR_SEND_NOTIFY_UNKNWN_PR
                         el cual envia correo de notificacion cuando
                         se presenta la mezcla de ordenes
  PROCEDURES CONTAINS :
  RELATED DOCUMENTS :    TV-PRO-ANT-01.doc
  ===============================================================*/
IS
-- PGV moved types start

--Dmap moved type other package XXMOR_FUNCIONAL_PKG;

TYPE XXMOR_FUNCIONAL_PKG.MOR_ENC_REC_TYPE IS RECORD
               (
                       ID_SOLICITUD       XXMOR_SOLICITUDES_ENC_TAB.ID_SOLICITUD%TYPE := NULL,
                       ID_REQUEST         XXMOR_SOLICITUDES_ENC_TAB.ID_REQUEST%TYPE := NULL,
                       ID_SEG_NEG         XXMOR_SOLICITUDES_ENC_TAB.ID_SEG_NEG%TYPE := NULL,
                       ID_FZA_VENTAS      XXMOR_SOLICITUDES_ENC_TAB.ID_FZA_VENTAS%TYPE := NULL,
                       ID_SOLICITUD_HNA   XXMOR_SOLICITUDES_ENC_TAB.ID_SOLICITUD_HNA%TYPE := NULL,
                       PROC_POR_LINEA     XXMOR_SOLICITUDES_ENC_TAB.PROC_POR_LINEA%TYPE := NULL,
                       GARANTIZADO        XXMOR_SOLICITUDES_ENC_TAB.GARANTIZADO%TYPE := NULL,
                       ADVID              XXMOR_SOLICITUDES_ENC_TAB.ADVID%TYPE := NULL,
                       MCONTID            XXMOR_SOLICITUDES_ENC_TAB.MCONTID%TYPE := NULL,
                       MCONTID_CUTIN      XXMOR_SOLICITUDES_ENC_TAB.MCONTID_CUTIN%TYPE := NULL,
                       EMAIL              XXMOR_SOLICITUDES_ENC_TAB.EMAIL%TYPE := NULL,
                       AGYESTNUM          XXMOR_SOLICITUDES_ENC_TAB.AGYESTNUM%TYPE := NULL,
                       ACCTHDRID          XXMOR_SOLICITUDES_ENC_TAB.ACCTHDRID%TYPE := NULL,
                       RTCRDDSCR          XXMOR_SOLICITUDES_ENC_TAB.RTCRDDSCR%TYPE := NULL,
                       RTCRD              XXMOR_SOLICITUDES_ENC_TAB.RTCRD%TYPE := NULL,
                       RTCRDDSCR_CUTIN    XXMOR_SOLICITUDES_ENC_TAB.RTCRDDSCR_CUTIN%TYPE := NULL,
                       RTCRD_CUTIN        XXMOR_SOLICITUDES_ENC_TAB.RTCRD_CUTIN%TYPE := NULL,
                       COMENTARIOS        XXMOR_SOLICITUDES_ENC_TAB.COMENTARIOS%TYPE := NULL,
                       SECNUM             XXMOR_SOLICITUDES_ENC_TAB.SECNUM%TYPE := NULL,
                       PLATAFORMA_CANAL   XXMOR_SOLICITUDES_ENC_TAB.PLATAFORMA_CANAL%TYPE := NULL,
                       AGRUPADOR          XXMOR_SOLICITUDES_ENC_TAB.AGRUPADOR%TYPE := NULL,
                       PRDID_DESC         XXMOR_SOLICITUDES_ENC_TAB.PRDID_DESC%TYPE := NULL,
                       PRDID              XXMOR_SOLICITUDES_ENC_TAB.PRDID%TYPE := NULL,
                       TOTAL_SPOTS        XXMOR_SOLICITUDES_ENC_TAB.TOTAL_SPOTS%TYPE := NULL,
                       TOTAL_SIN_DESC     XXMOR_SOLICITUDES_ENC_TAB.TOTAL_SIN_DESC%TYPE := NULL,
                       TOTAL_CON_DESC     XXMOR_SOLICITUDES_ENC_TAB.TOTAL_CON_DESC%TYPE := NULL,
                       TIPO_FACTURACION   XXMOR_SOLICITUDES_ENC_TAB.TIPO_FACTURACION%TYPE := NULL,
                       DESCUENTO          XXMOR_SOLICITUDES_ENC_TAB.DESCUENTO%TYPE := NULL,
                       TARGET             XXMOR_SOLICITUDES_ENC_TAB.TARGET%TYPE := NULL,
                       ORDEN_ESTATUS      XXMOR_SOLICITUDES_ENC_TAB.ORDEN_ESTATUS%TYPE := NULL,
                       FECHA_CONCOM       XXMOR_SOLICITUDES_ENC_TAB.FECHA_CONCOM%TYPE := NULL,
                       TRACKING_ID_CONCOM XXMOR_SOLICITUDES_ENC_TAB.TRACKING_ID_CONCOM%TYPE := NULL,
                       CREATED_DATE       XXMOR_SOLICITUDES_ENC_TAB.CREATED_DATE%TYPE := NULL,
                       CREATED_BY         XXMOR_SOLICITUDES_ENC_TAB.CREATED_BY%TYPE := NULL,
                       UPDATED_DATE       XXMOR_SOLICITUDES_ENC_TAB.UPDATED_DATE%TYPE := NULL,
                       UPDATED_BY         XXMOR_SOLICITUDES_ENC_TAB.UPDATED_BY%TYPE := NULL
               );

-- PGV moved types end

-- PGV moved types start
--Dmap moved type other package XXMOR_FUNCIONAL_PKG;
TYPE XXMOR_FUNCIONAL_PKG.MOR_ENC_REC_TYPE IS RECORD
               (
                       ID_SOLICITUD       XXMOR_SOLICITUDES_ENC_TAB.ID_SOLICITUD%TYPE := NULL,
                       ID_REQUEST         XXMOR_SOLICITUDES_ENC_TAB.ID_REQUEST%TYPE := NULL,
                       ID_SEG_NEG         XXMOR_SOLICITUDES_ENC_TAB.ID_SEG_NEG%TYPE := NULL,
                       ID_FZA_VENTAS      XXMOR_SOLICITUDES_ENC_TAB.ID_FZA_VENTAS%TYPE := NULL,
                       ID_SOLICITUD_HNA   XXMOR_SOLICITUDES_ENC_TAB.ID_SOLICITUD_HNA%TYPE := NULL,
                       PROC_POR_LINEA     XXMOR_SOLICITUDES_ENC_TAB.PROC_POR_LINEA%TYPE := NULL,
                       GARANTIZADO        XXMOR_SOLICITUDES_ENC_TAB.GARANTIZADO%TYPE := NULL,
                       ADVID              XXMOR_SOLICITUDES_ENC_TAB.ADVID%TYPE := NULL,
                       MCONTID            XXMOR_SOLICITUDES_ENC_TAB.MCONTID%TYPE := NULL,
                       MCONTID_CUTIN      XXMOR_SOLICITUDES_ENC_TAB.MCONTID_CUTIN%TYPE := NULL,
                       EMAIL              XXMOR_SOLICITUDES_ENC_TAB.EMAIL%TYPE := NULL,
                       AGYESTNUM          XXMOR_SOLICITUDES_ENC_TAB.AGYESTNUM%TYPE := NULL,
                       ACCTHDRID          XXMOR_SOLICITUDES_ENC_TAB.ACCTHDRID%TYPE := NULL,
                       RTCRDDSCR          XXMOR_SOLICITUDES_ENC_TAB.RTCRDDSCR%TYPE := NULL,
                       RTCRD              XXMOR_SOLICITUDES_ENC_TAB.RTCRD%TYPE := NULL,
                       RTCRDDSCR_CUTIN    XXMOR_SOLICITUDES_ENC_TAB.RTCRDDSCR_CUTIN%TYPE := NULL,
                       RTCRD_CUTIN        XXMOR_SOLICITUDES_ENC_TAB.RTCRD_CUTIN%TYPE := NULL,
                       COMENTARIOS        XXMOR_SOLICITUDES_ENC_TAB.COMENTARIOS%TYPE := NULL,
                       SECNUM             XXMOR_SOLICITUDES_ENC_TAB.SECNUM%TYPE := NULL,
                       PLATAFORMA_CANAL   XXMOR_SOLICITUDES_ENC_TAB.PLATAFORMA_CANAL%TYPE := NULL,
                       AGRUPADOR          XXMOR_SOLICITUDES_ENC_TAB.AGRUPADOR%TYPE := NULL,
                       PRDID_DESC         XXMOR_SOLICITUDES_ENC_TAB.PRDID_DESC%TYPE := NULL,
                       PRDID              XXMOR_SOLICITUDES_ENC_TAB.PRDID%TYPE := NULL,
                       TOTAL_SPOTS        XXMOR_SOLICITUDES_ENC_TAB.TOTAL_SPOTS%TYPE := NULL,
                       TOTAL_SIN_DESC     XXMOR_SOLICITUDES_ENC_TAB.TOTAL_SIN_DESC%TYPE := NULL,
                       TOTAL_CON_DESC     XXMOR_SOLICITUDES_ENC_TAB.TOTAL_CON_DESC%TYPE := NULL,
                       TIPO_FACTURACION   XXMOR_SOLICITUDES_ENC_TAB.TIPO_FACTURACION%TYPE := NULL,
                       DESCUENTO          XXMOR_SOLICITUDES_ENC_TAB.DESCUENTO%TYPE := NULL,
                       TARGET             XXMOR_SOLICITUDES_ENC_TAB.TARGET%TYPE := NULL,
                       ORDEN_ESTATUS      XXMOR_SOLICITUDES_ENC_TAB.ORDEN_ESTATUS%TYPE := NULL,
                       FECHA_CONCOM       XXMOR_SOLICITUDES_ENC_TAB.FECHA_CONCOM%TYPE := NULL,
                       TRACKING_ID_CONCOM XXMOR_SOLICITUDES_ENC_TAB.TRACKING_ID_CONCOM%TYPE := NULL,
                       CREATED_DATE       XXMOR_SOLICITUDES_ENC_TAB.CREATED_DATE%TYPE := NULL,
                       CREATED_BY         XXMOR_SOLICITUDES_ENC_TAB.CREATED_BY%TYPE := NULL,
                       UPDATED_DATE       XXMOR_SOLICITUDES_ENC_TAB.UPDATED_DATE%TYPE := NULL,
                       UPDATED_BY         XXMOR_SOLICITUDES_ENC_TAB.UPDATED_BY%TYPE := NULL
               );
-- PGV moved types end
V_MAIL_INT          PLS_INTEGER;
V_MAIL_EXT          PLS_INTEGER;
V_MAIL_FAC          PLS_INTEGER;
V_LISTA_MAILS       VARCHAR(3000);
V_LISTA_MAILS_MKT   VARCHAR(3000);
V_NOMBRE_ARCHIVO    VARCHAR(300);
V_AUTORIZACIONES    PLS_INTEGER;
V_RECHAZOS          PLS_INTEGER;
V_ERRORES_LIN       NUMBER;
V_SOLICITUD         XXMOR_FUNCIONAL_PKG.MOR_ENC_REC_TYPE;
V_MAIL_SUBJECT      VARCHAR(300);
liinStatusHead      NUMBER;
--Mails de buyunit-Mercadotecnia
CURSOR ADD_BUYUNT_MKT_CUR(C_ID_SOLICITUD INTEGER) IS
SELECT NVL2(MKT_DIRECTOR,MKT_DIRECTOR||', ',' ')||
       NVL2(MKT_GERENTE,MKT_GERENTE||', ',' ')||
       NVL2(MKT_COORDINADOR,MKT_COORDINADOR||', ',' ')||
       NVL2(MKT_EJECUTIVO,MKT_EJECUTIVO||', ',' ') AS MAILS
FROM   XXMOR_CAT_BUYUNIT_MKT_TAB BM
WHERE  EXISTS (SELECT 1
               FROM   XXMOR_SOLICITUDES_ENC_TAB E,
                      XXMOR_SOLICITUDES_DET_TAB D,
                      XXMOR_FZAS_VTAS_TAB FV
               WHERE  E.ID_SOLICITUD   = C_ID_SOLICITUD
               AND    E.ID_SOLICITUD   = D.ID_SOLICITUD
               AND    E.ID_FZA_VENTAS  = FV.ID_FZA_VENTAS
               AND    FV.MERCADOTECNIA = 1 --LA ORDEN TIENE QUE SER DE UNA FZA DE VTAS DE MKT
               AND    E.ID_FZA_VENTAS  = BM.ID_FZA_VENTAS
               AND    NVL(TRIM(D.BUYUNTID),'SIN BUYUNIT') = NVL(TRIM(BM.BUYUNTID),'SIN BUYUNIT')
              );
CURSOR MAILS_USRS_CUR IS
SELECT ID_USER,
       ADMINISTRADOR
FROM   XXMOR_FZAS_VTAS_USUARIOS_TAB
WHERE  ID_SEG_NEG    = 1
AND    ID_FZA_VENTAS = (SELECT ID_FZA_VENTAS
                        FROM   XXMOR_SOLICITUDES_ENC_TAB
                        WHERE  ID_SOLICITUD = P_ID_SOLICITUD
                       )
AND    ADMINISTRADOR = 1;
CURSOR LINEAS_ORDEN_CUR IS
SELECT LINEA
FROM   XXMOR_SOLICITUDES_DET_TAB
WHERE  ID_SOLICITUD =  P_ID_SOLICITUD;
BEGIN
    -- JLBS - Se obtiene el estatus de la orden en la que se ecnuentra
    SELECT NVL(ORDEN_ESTATUS,0)
      INTO liinStatusHead
      FROM XXMOR_SOLICITUDES_ENC_TAB
     WHERE ID_SOLICITUD = P_ID_SOLICITUD;
    -- JLBS
    FOR LINEA_ORDEN IN LINEAS_ORDEN_CUR LOOP
        V_ERRORES_LIN := 0;
        SELECT COUNT(1)
        INTO   V_ERRORES_LIN
        FROM   XXMOR_CONCOM_RPTA_TAB
        WHERE  ID_SOLICITUD             = P_ID_SOLICITUD
        AND    NVL(NUMLINEA_CONCOM,'0') = TO_CHAR(LINEA_ORDEN.LINEA)
        AND    UPPER(ACCION_CONCOM)     = 'RECHAZO'
        AND    ESTATUS_ORDUNI           = '10';
        IF V_ERRORES_LIN > 0 THEN
            -- PARA ACTUALIZAR A ESTATUS 20 LAS LINEAS QUE FUERON RECHAZADAS Y QUE
            -- AUN SIGUEN CON ESTATUS 10.
            UPDATE XXMOR_CONCOM_RPTA_TAB CR
            SET    CR.ESTATUS_ORDUNI = 20,
                   CR.UPDATED_BY     = 'ORDUNI',
                   CR.UPDATED_DATE   = SYSDATE
            WHERE CR.ID_SOLICITUD       = P_ID_SOLICITUD
            AND UPPER(CR.ACCION_CONCOM) IN ('REPROCESO','AUTORIZACION')
            AND NUMLINEA_CONCOM         = TO_CHAR(LINEA_ORDEN.LINEA)
            AND ESTATUS_ORDUNI          = '10';
        END IF;
    END LOOP;
    --Revisamos si tiene rechazos
    SELECT COUNT(1)
    INTO   v_rechazos
    FROM   XXMOR_CONCOM_RPTA_TAB
    WHERE  ID_SOLICITUD         = P_ID_SOLICITUD
    AND    UPPER(ACCION_CONCOM) = 'RECHAZO'
    AND    ESTATUS_ORDUNI       = '10';
    --Revisamos si tiene autorizaciones
    SELECT COUNT(1)
    INTO   v_autorizaciones
    FROM   XXMOR_CONCOM_RPTA_TAB
    WHERE  ID_SOLICITUD         = P_ID_SOLICITUD
    AND    UPPER(ACCION_CONCOM) = 'AUTORIZACION'
    AND    ESTATUS_ORDUNI       = '10';
    SELECT ID_SOLICITUD,
           ADVID,
           ACCTHDRID,
           MCONTID,
           RTCRDDSCR,
           COMENTARIOS,
           ID_FZA_VENTAS,
           EMAIL,
           CREATED_BY
    INTO   V_SOLICITUD.ID_SOLICITUD,
           V_SOLICITUD.ADVID,
           V_SOLICITUD.ACCTHDRID,
           V_SOLICITUD.MCONTID,
           V_SOLICITUD.RTCRDDSCR,
           V_SOLICITUD.COMENTARIOS,
           V_SOLICITUD.ID_FZA_VENTAS,
           V_SOLICITUD.EMAIL,
           V_SOLICITUD.CREATED_BY
    FROM   XXMOR_SOLICITUDES_ENC_TAB
    WHERE  ID_SOLICITUD =  P_ID_SOLICITUD;
    BEGIN
        -- JLBS Enviar a usuarios se toma como 100
        SELECT NVL(USUARIO_INTERNO,0),
               NVL(USUARIO_AGENCIA,0),
               NVL(USUARIO_FACTUR,0)
        INTO   V_MAIL_INT,
               V_MAIL_EXT,
               V_MAIL_FAC
        FROM   XXMOR_CONF_NOTIFIC_TAB
        WHERE  ID_SEG_NEG      = 1
        AND    ID_FZA_VENTAS   = V_SOLICITUD.ID_FZA_VENTAS
        AND    ID_NOTIFICACION = 100;
        -- JLBS
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            V_MAIL_INT := 0;
            V_MAIL_EXT := 0;
            V_MAIL_FAC := 0;
    END;
    SELECT A.NOM_ARCHIVO_SOL
    INTO   V_NOMBRE_ARCHIVO
    FROM   XXMOR_SOLICITUDES_ARCH_TAB     A,
           XXMOR_SOLICITUDES_ENC_TAB      E,
           XXMOR_SOLICITUDES_ORIG_ENC_TAB EO
    WHERE  E.ID_SOLICITUD    = P_ID_SOLICITUD
    AND    E.ID_REQUEST      = EO.ID_REQUEST
    AND    EO.ID_ARCHIVO_SOL = A.ID_ARCHIVO_SOL
    AND    E.ID_SEG_NEG      = 1
    AND    E.ID_SEG_NEG      = A.ID_SEG_NEG;
    -- JLBS - Se toma como notificacion 100
    SELECT 'Orden '|| P_ID_SOLICITUD ||' ('||V_NOMBRE_ARCHIVO||') Error al actualizar, Verifique la orden'
    INTO   V_MAIL_SUBJECT
    FROM   XXMOR_ORDENES_ESTATUS_TAB
    WHERE  ID_NOTIFICACION = 100
    AND    ID_SEG_NEG      = 1;
    -- fin JLBS
    V_LISTA_MAILS := NULL;
    --Mail interno
    IF V_MAIL_INT = 1 THEN
        FOR DESTINATARIOS IN MAILS_USRS_CUR LOOP
            V_LISTA_MAILS := V_LISTA_MAILS ||DESTINATARIOS.ID_USER ||'@televisa.com.mx,';
        END LOOP;
        V_LISTA_MAILS:= V_LISTA_MAILS ||V_SOLICITUD.CREATED_BY ||'@televisa.com.mx,';
        DBMS_OUTPUT.PUT_LINE( 'sale mail interno: '||V_LISTA_MAILS);
    END IF;
    --Mail externo
    IF V_MAIL_EXT = 1 AND INSTR(V_SOLICITUD.EMAIL,'@') > 0 THEN
        DBMS_OUTPUT.PUT_LINE( 'entra a mail externo');
        V_LISTA_MAILS:= V_LISTA_MAILS ||TRIM(LOWER(V_SOLICITUD.EMAIL))||',';
        DBMS_OUTPUT.PUT_LINE( 'sale mail externo: '||V_LISTA_MAILS);
    END IF;
    --Mail FACTUR
    IF V_MAIL_FAC = 1 THEN
        V_LISTA_MAILS := V_LISTA_MAILS || XXMOR_FUNCIONAL_PKG.XXMOR_GET_MAILS_FACTUR_FUN(P_ID_SOLICITUD)||',';
        DBMS_OUTPUT.PUT_LINE( 'sale mail factur: '||V_LISTA_MAILS);
    END IF;
        -- SE ENVIA LA NOTIFICACION DESPUES DE VALIDACION
    IF LENGTH(V_LISTA_MAILS) > 5 THEN
        DBMS_OUTPUT.PUT_LINE( 'V_LISTA_MAILS: '||V_LISTA_MAILS ||' V_MAIL_SUBJECT: '|| V_MAIL_SUBJECT);
        XXMOR_FUNCIONAL_PKG.XXMOR_HTML_EMAIL_PR(V_LISTA_MAILS, V_MAIL_SUBJECT, NULL, XXMOR_FUNCIONAL_PKG.XXMOR_HTML_MAIL(P_ID_SOLICITUD, NULL, 10)  );
    END IF;
    FOR C_MAILS IN ADD_BUYUNT_MKT_CUR(P_ID_SOLICITUD) LOOP
        V_LISTA_MAILS_MKT := V_LISTA_MAILS_MKT ||C_MAILS.MAILS;
        DBMS_OUTPUT.PUT_LINE( 'C_MAILS.MAILS: ' ||C_MAILS.MAILS);
    END LOOP;
    IF LENGTH(V_LISTA_MAILS_MKT ) > 5 THEN
        SELECT 'Orden '|| P_ID_SOLICITUD ||' ('||V_NOMBRE_ARCHIVO||') ' || DESC_NOTIFICACION
        INTO   V_MAIL_SUBJECT
        FROM   XXMOR_ORDENES_ESTATUS_TAB
        WHERE  ID_NOTIFICACION = 84
        AND    ID_SEG_NEG      = 1;
        DBMS_OUTPUT.PUT_LINE( 'V_LISTA_MAILS_MKT: '||V_LISTA_MAILS_MKT ||' V_MAIL_SUBJECT: '|| V_MAIL_SUBJECT);
        XXMOR_FUNCIONAL_PKG.XXMOR_HTML_EMAIL_PR(V_LISTA_MAILS_MKT, V_MAIL_SUBJECT, NULL, XXMOR_FUNCIONAL_PKG.XXMOR_HTML_MAIL(P_ID_SOLICITUD, P_LINEAS, liinStatusHead)  );
    END IF;
END;
/
