CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMP"."ADMP_PARRILLA_COPIA_VW" ("ID_CANAL", "DES_CANAL", "DES_ACRONIMO", "ID_PARRILLA", "FEC_PARRILLA", "DIA", "ID_TIPO_PARRILLA", "NUM_VERSION", "ID_PARRILLA_DET", "DES_CICLO", "DES_HORA_INICIO", "DES_HORA_FIN", "DES_HORA_INICIO_REAL", "DES_HORA_FIN_REAL", "DES_PROGRAMA", "DES_PROGRAMA_ORIGINAL", "DES_NOTAS") AS 
  SELECT  C.ID_CANAL
        ,C.DES_CANAL
        ,C.DES_ACRONIMO
        ,P.ID_PARRILLA
        ,P.FEC_PARRILLA
        ,1 + TRUNC (FEC_PARRILLA) - TRUNC (FEC_PARRILLA, 'IW') DIA
        --,TO_CHAR(FEC_PARRILLA,'DAY','NLS_DATE_LANGUAGE=''MEXICAN SPANISH''') DIA
        ,P.ID_TIPO_PARRILLA
        ,P.NUM_VERSION
        ,PD.ID_PARRILLA_DET
        ,DES_CICLO
        ,DES_HORA_INICIO
        ,DES_HORA_FIN
        ,DES_HORA_INICIO_REAL
        ,DES_HORA_FIN_REAL
        ,PD.DES_PROGRAMA
        ,PD.DES_PROGRAMA_ORIGINAL
        ,PD.DES_NOTAS
FROM    ADMP_CANAL_TAB          C
        ,ADMP_PARRILLA_TAB      P
        ,ADMP_PARRILLA_DET_TAB  PD
WHERE   C.ID_CANAL          =  P.ID_CANAL
AND     C.ID_ESTADO         = 1
AND     P.ID_ESTADO         = 1
AND     P.ID_PARRILLA       = PD.ID_PARRILLA;
