CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMP"."ADMP_REP_PARRILLA_X_CANAL_VM" ("ID_CANAL", "DES_CANAL", "DES_ACRONIMO", "ID_PARRILLA", "FEC_PARRILLA", "NUM_VERSION", "ID_TIPO_PARRILLA", "DES_TIPO_PARRILLA", "ID_PARRILLA_DET", "ID_GENERO", "DES_GENERO", "COD_HEX_COLOR", "COD_HEX_BORDE", "COD_HEX_TEXTO", "DES_CICLO", "DES_HORA_INICIO", "DES_HORA_FIN", "DES_HORA_INICIO_REAL", "DES_HORA_FIN_REAL", "DES_HORA_INICIO_ISO", "DES_HORA_FIN_ISO", "ID_TIPO", "DES_TIPO", "DES_PROGRAMA", "DES_PROGRAMA_ORIGINAL", "ID_CLASIFICACION", "COD_CLASIFICACION", "DES_CLASIFICACION", "ID_FORMATO", "COD_FORMATO", "DES_FORMATO", "ID_RESTRICCION", "COD_RESTRICCION", "DES_RESTRICCION", "DES_NOTAS") AS 
  SELECT  C.ID_CANAL
        ,C.DES_CANAL
        ,C.DES_ACRONIMO
        ,P.ID_PARRILLA
        ,P.FEC_PARRILLA
        ,P.NUM_VERSION
        ,P.ID_TIPO_PARRILLA
        ,TP.DES_TIPO_PARRILLA
        ,PD.ID_PARRILLA_DET
        ,G.ID_GENERO
        ,G.DES_GENERO
        ,G.COD_HEX_COLOR
        ,G.COD_HEX_BORDE
        ,G.COD_HEX_TEXTO
        ,DES_CICLO
        ,DES_HORA_INICIO
        ,DES_HORA_FIN
        ,DES_HORA_INICIO_REAL
        ,DES_HORA_FIN_REAL
        ,DES_HORA_INICIO_ISO
        ,DES_HORA_FIN_ISO
        ,T.ID_TIPO
        ,T.DES_TIPO
        ,PD.DES_PROGRAMA
        ,PD.DES_PROGRAMA_ORIGINAL
        ,CL.ID_CLASIFICACION
        ,CL.COD_CLASIFICACION
        ,CL.DES_CLASIFICACION
        ,F.ID_FORMATO
        ,F.COD_FORMATO
        ,F.DES_FORMATO
        ,R.ID_RESTRICCION
        ,R.COD_RESTRICCION
        ,R.DES_RESTRICCION
        ,PD.DES_NOTAS
FROM    ADMP_CANAL_TAB          C
        ,ADMP_PARRILLA_TAB      P
        ,ADMP_PARRILLA_DET_TAB  PD
        ,ADMP_GENERO_TAB        G
        ,ADMP_TIPO_TAB          T
        ,ADMP_CLASIFICACION_TAB CL
        ,ADMP_FORMATO_TAB       F
        ,ADMP_RESTRICCION_TAB   R
        ,ADMP_TIPO_PARRILLA_TAB TP
WHERE   C.ID_CANAL          =  P.ID_CANAL
AND     C.ID_ESTADO         = 1
AND     P.ID_ESTADO         = 1
AND     P.ID_PARRILLA       = PD.ID_PARRILLA
AND     PD.ID_GENERO        = G.ID_GENERO
AND     PD.ID_TIPO          = T.ID_TIPO(+)
AND     PD.ID_CLASIFICACION = CL.ID_CLASIFICACION(+)
AND     PD.ID_FORMATO       = F.ID_FORMATO(+)
AND     PD.ID_RESTRICCION   = R.ID_RESTRICCION(+)
AND     P.ID_TIPO_PARRILLA  = TP.ID_TIPO_PARRILLA(+);
