CREATE TABLE "LABPROD"."AMORTIZACIONES" 
   (	"AMO_RECURP" VARCHAR2(20) NOT NULL ENABLE, 
	"AMO_KEYEMP" NUMBER(10,0) NOT NULL ENABLE, 
	"AMO_REFERE" VARCHAR2(20), 
	"AMO_CANTID" NUMBER(12,2), 
	"AMO_IMPORT" NUMBER(12,2), 
	"AMO_KEYPER" VARCHAR2(7), 
	"AMO_KEYPRO" NUMBER(5,0), 
	"AMO_KEYCON" VARCHAR2(3), 
	"AMO_VALIDA" VARCHAR2(100), 
	"AMO_FECMOV" DATE, 
	"AMO_STATUS" NUMBER
   ) ;
