CREATE TABLE "LABPROD"."API_CATALOGO" 
   (	"ID_TRANSACCION" VARCHAR2(30) NOT NULL ENABLE, 
	"PAM_KEYPAR" VARCHAR2(4) NOT NULL ENABLE, 
	"PAM_CVESEC" VARCHAR2(6) NOT NULL ENABLE, 
	"PAM_NOMPAR" VARCHAR2(100) NOT NULL ENABLE, 
	"PAM_FOLINI" VARCHAR2(100), 
	"PAM_FOLFIN" VARCHAR2(100), 
	"FECHA_INSERT" DATE, 
	"FECHA_PROC" DATE, 
	"STATUS" VARCHAR2(150), 
	"CODE" VARCHAR2(200), 
	"MESSAGE" VARCHAR2(200)
   ) ;
