CREATE TABLE "LABPROD"."CFDI2NOMINAEMISOR" 
   (	"IDCOMPROBANTEEMP" NUMBER(10,0) NOT NULL ENABLE, 
	"CURP" VARCHAR2(18), 
	"REGISTROPATRONAL" VARCHAR2(20), 
	"RFCPATRONORIGEN" VARCHAR2(13), 
	"ORIGENRECURSO" VARCHAR2(2), 
	"MONTORECURSOPROPIO" NUMBER(18,2)
   ) ;
ALTER TABLE "LABPROD"."CFDI2NOMINAEMISOR" ADD CONSTRAINT "PK_CFDI2NOMINAEMISOR" PRIMARY KEY ("IDCOMPROBANTEEMP")
  USING INDEX  ENABLE;
