CREATE TABLE "LABPROD"."CFDI2PERCEPCIONESJUBILACION" 
   (	"IDNOMINA" NUMBER(10,0) NOT NULL ENABLE, 
	"TOTALUNAEXHIBICION" NUMBER(18,2), 
	"TOTALPARCIALIDAD" NUMBER(18,2), 
	"MONTODIARIO" NUMBER(18,2), 
	"INGRESOACUMULABLE" NUMBER(18,2) NOT NULL ENABLE, 
	"INGRESONOACUMULABLE" NUMBER(18,2) NOT NULL ENABLE
   ) ;
ALTER TABLE "LABPROD"."CFDI2PERCEPCIONESJUBILACION" ADD CONSTRAINT "PK_CFDI2PERCEPCIONESJUBILACION" PRIMARY KEY ("IDNOMINA")
  USING INDEX  ENABLE;
