CREATE TABLE "LABPROD"."CFDIDEDUCCIONES" 
   (	"IDCOMPROBANTEEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"COM_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"COM_KEYCON" VARCHAR2(3), 
	"TIPODEDUCCION" VARCHAR2(3) NOT NULL ENABLE, 
	"CLAVE" VARCHAR2(6) NOT NULL ENABLE, 
	"CONCEPTO" VARCHAR2(100) NOT NULL ENABLE, 
	"IMPORTEGRAVADO" NUMBER(18,6), 
	"IMPORTEEXENTO" NUMBER(18,6)
   ) ;
