CREATE TABLE "LABPROD"."CFDICANCELACIONES" 
   (	"IDCOMPROBANTEEMP" NUMBER(*,0), 
	"CAN_KEYEMP" VARCHAR2(50), 
	"CAN_KEYPRO" NUMBER(*,0), 
	"CAN_KEYPER" VARCHAR2(10), 
	"CAN_UUID" VARCHAR2(36), 
	"CAN_ESTATUS" NUMBER(*,0), 
	"CAN_XMLCANCELADO" VARCHAR2(200), 
	"CAN_FECHACANCELACION" DATE, 
	"CAN_PAC" VARCHAR2(50)
   ) ;
