CREATE TABLE "LABPROD"."CFDI2COMPROBANTEPRO" 
   (	"IDCOMPROBANTEPRO" NUMBER(10,0) NOT NULL ENABLE, 
	"COM_KEYPRO" NUMBER(5,0) NOT NULL ENABLE, 
	"COM_KEYPER" VARCHAR2(7) NOT NULL ENABLE, 
	"COM_EJECUT" NUMBER(5,0) NOT NULL ENABLE
   ) ;
ALTER TABLE "LABPROD"."CFDI2COMPROBANTEPRO" ADD CONSTRAINT "PK_CFDI2COMPROBANTEPRO" PRIMARY KEY ("IDCOMPROBANTEPRO")
  USING INDEX  ENABLE;
