CREATE TABLE "LABPROD"."CFDIPERCEPCIONES" 
   (	"IDCOMPROBANTEEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"COM_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"COM_KEYCON" VARCHAR2(3), 
	"TIPOPERCEPCION" VARCHAR2(3) NOT NULL ENABLE, 
	"CLAVE" VARCHAR2(6) NOT NULL ENABLE, 
	"CONCEPTO" VARCHAR2(100) NOT NULL ENABLE, 
	"IMPORTEGRAVADO" NUMBER(18,6) NOT NULL ENABLE, 
	"IMPORTEEXENTO" NUMBER(18,6) NOT NULL ENABLE
   ) ;
