CREATE TABLE "LABPROD"."CFDI2DEDUCCIONESDETALLE" 
   (	"IDDEDUCCION" NUMBER(10,0) NOT NULL ENABLE, 
	"IDNOMINA" NUMBER(10,0) NOT NULL ENABLE, 
	"TIPODEDUCCION" VARCHAR2(3) NOT NULL ENABLE, 
	"CLAVE" VARCHAR2(15) NOT NULL ENABLE, 
	"CONCEPTO" VARCHAR2(100) NOT NULL ENABLE, 
	"IMPORTE" NUMBER(18,2) NOT NULL ENABLE, 
	"IMPORTEGRAVADO" NUMBER(18,2) NOT NULL ENABLE, 
	"IMPORTEEXENTO" NUMBER(18,2) NOT NULL ENABLE
   ) ;
ALTER TABLE "LABPROD"."CFDI2DEDUCCIONESDETALLE" ADD CONSTRAINT "PK_CFDI2DEDUCCIONESDETALLE" PRIMARY KEY ("IDDEDUCCION")
  USING INDEX  ENABLE;
