CREATE TABLE "LABPROD"."CFDICOMPROBANTEEMISOR" 
   (	"IDCOMPROBANTEPRO" NUMBER(*,0) NOT NULL ENABLE, 
	"RFC" VARCHAR2(13) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100), 
	"CALLE" VARCHAR2(100), 
	"NOEXTERIOR" VARCHAR2(100), 
	"NOINTERIOR" VARCHAR2(100), 
	"COLONIA" VARCHAR2(100), 
	"LOCALIDAD" VARCHAR2(100), 
	"REFERENCIA" VARCHAR2(100), 
	"MUNICIPIO" VARCHAR2(100), 
	"ESTADO" VARCHAR2(100), 
	"PAIS" VARCHAR2(100), 
	"CODIGOPOSTAL" VARCHAR2(5)
   ) ;
ALTER TABLE "LABPROD"."CFDICOMPROBANTEEMISOR" ADD CONSTRAINT "CFDICOMPROBANTEEMISOR_PK" PRIMARY KEY ("IDCOMPROBANTEPRO")
  USING INDEX  ENABLE;
