CREATE TABLE "LABPROD"."CFDI2REPORTECIFRAS" 
   (	"IDNOMINA" NUMBER(*,0) NOT NULL ENABLE, 
	"COM_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"COM_CODIMP" VARCHAR2(2) NOT NULL ENABLE, 
	"COM_KEYCON" VARCHAR2(3) NOT NULL ENABLE, 
	"CON_TIPCON" VARCHAR2(3) NOT NULL ENABLE, 
	"TIPO" VARCHAR2(3) NOT NULL ENABLE, 
	"DESCTIPO" VARCHAR2(100), 
	"CLAVE" VARCHAR2(15) NOT NULL ENABLE, 
	"CONCEPTO" VARCHAR2(100), 
	"IMPORTEGRAVADO" NUMBER(18,2) NOT NULL ENABLE, 
	"IMPORTEEXENTO" NUMBER(18,2) NOT NULL ENABLE
   ) ;
