CREATE TABLE "LABPROD"."COM_SIPS_ORAC_BITA" 
   (	"BIT_REGIST" VARCHAR2(50), 
	"BIT_VALANT" VARCHAR2(50), 
	"BIT_VALNUE" VARCHAR2(50), 
	"BIT_KEYEMP" NUMBER(*,0), 
	"BIT_FECMOV" DATE, 
	"BIT_MENERR" VARCHAR2(200), 
	"BIT_NOCTVO" NUMBER(10,0) NOT NULL ENABLE, 
	"BIT_STATUS" VARCHAR2(1)
   ) ;
