CREATE TABLE "LABPROD"."DATOSGENERALES_ERRSAF" 
   (	"EMPLEADO" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"TIPO" VARCHAR2(10) NOT NULL ENABLE, 
	"FECHA" DATE NOT NULL ENABLE, 
	"QUERY" VARCHAR2(300)
   ) ;
