CREATE TABLE "LABPROD"."DET_CAPINC" 
   (	"DET_NUMID" NUMBER(10,0) NOT NULL ENABLE, 
	"DET_CVEDIA" VARCHAR2(2) NOT NULL ENABLE, 
	"DET_KEYUSU" VARCHAR2(18) NOT NULL ENABLE, 
	"DET_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"DET_KEYSEM" NUMBER(*,0) NOT NULL ENABLE, 
	"DET_CCOSTO" VARCHAR2(18), 
	"DET_ENT" VARCHAR2(5), 
	"DET_SAL" VARCHAR2(5), 
	"DET_CONCEP" VARCHAR2(3), 
	"DET_FECHA" DATE NOT NULL ENABLE, 
	"DET_HORAS" NUMBER(10,2) NOT NULL ENABLE, 
	"DET_IMPOR" NUMBER(16,2), 
	"DET_CVEINC" VARCHAR2(2), 
	"DET_XYTECH" NUMBER(*,0)
   ) ;
