CREATE TABLE "LABPROD"."FUARCHIVODETALLE" 
   (	"ID" NUMBER(*,0), 
	"IDARCHIVO" NUMBER(*,0), 
	"SERIE" VARCHAR2(10), 
	"FOLIO" VARCHAR2(10), 
	"CONDICIONES" VARCHAR2(50), 
	"LUGAREXPEDICION" VARCHAR2(5), 
	"SUBTOTAL" NUMBER(18,2), 
	"TOTAL" NUMBER(18,2), 
	"NOMBREEMISOR" VARCHAR2(200), 
	"REGIMENEMISOR" VARCHAR2(3), 
	"RFCEMISOR" VARCHAR2(14), 
	"NOMBRERECEPTOR" VARCHAR2(100), 
	"RFCRECEPTOR" VARCHAR2(14), 
	"DOMICILIORECEPTOR" VARCHAR2(5), 
	"REGIMENRECEPTOR" VARCHAR2(3), 
	"COM_STATUS" VARCHAR2(1)
   ) ;
