CREATE TABLE "LABPROD"."FUCFDICOMPROBANTEPRO" 
   (	"IDCOMPROBANTEPRO" NUMBER(*,0), 
	"COM_KEYPRO" NUMBER(*,0), 
	"COM_KEYPER" VARCHAR2(7), 
	"COM_TIPO" VARCHAR2(1), 
	"COM_NOMARC" VARCHAR2(200), 
	"COM_REGVAL" NUMBER(*,0), 
	"COM_REGENV" NUMBER(*,0), 
	"COM_REGTIM" NUMBER(*,0), 
	"COM_REGERR" NUMBER(*,0), 
	"COM_REGCAN" NUMBER(*,0)
   ) ;
