CREATE TABLE "LABPROD"."FUCFDIXML" 
   (	"IDCOMPROBANTEEMP" NUMBER(10,0) NOT NULL ENABLE, 
	"XMLCFDI" VARCHAR2(4000), 
	"TIMBRADO" NUMBER(1,0), 
	"CADENAORIGINAL" VARCHAR2(4000), 
	"PAC" VARCHAR2(100), 
	"UUID" VARCHAR2(36), 
	"SELLOSAT" VARCHAR2(4000), 
	"NOCERTIFICADOSAT" VARCHAR2(50)
   ) ;
ALTER TABLE "LABPROD"."FUCFDIXML" ADD CONSTRAINT "PK_FUCFDIXML" PRIMARY KEY ("IDCOMPROBANTEEMP")
  USING INDEX  ENABLE;
