CREATE TABLE "LABPROD"."GLCODOCU" 
   (	"DOC_KEYDOC" NUMBER(10,0), 
	"DOC_KEYTAB" VARCHAR2(18), 
	"DOC_CAMPO1" VARCHAR2(16), 
	"DOC_CAMPO2" VARCHAR2(16), 
	"DOC_KEYUNO" VARCHAR2(16), 
	"DOC_KEYDOS" VARCHAR2(16), 
	"DOC_FECACT" DATE, 
	"DOC_KEYUSU" NUMBER(10,0)
   ) ;
