CREATE TABLE "LABPROD"."INLOPGRA" 
   (	"PGR_KEYPGR" NUMBER(5,0), 
	"PGR_DESPGR" VARCHAR2(30), 
	"PGR_REGPGR" VARCHAR2(25), 
	"PGR_TIPPGR" VARCHAR2(1), 
	"PGR_CA1AUX" VARCHAR2(10), 
	"PGR_CA2AUX" VARCHAR2(10), 
	"PGR_CA3AUX" VARCHAR2(10), 
	"PGR_OBSERV" VARCHAR2(1), 
	"PGR_KEYDEP" VARCHAR2(16), 
	"PGR_KEYPUE" VARCHAR2(16)
   ) ;
