CREATE TABLE "LABPROD"."INLODWSQ" 
   (	"DWS_KEYWOR" VARCHAR2(4), 
	"DWS_NUMSQL" NUMBER(5,0), 
	"DWS_NUMSEC" NUMBER(5,0), 
	"DWS_SQLASO" NUMBER(5,0), 
	"DWS_SECCMP" NUMBER(5,0), 
	"DWS_DESCMP" VARCHAR2(20)
   ) ;
