CREATE TABLE "LABPROD"."INLOPCAP" 
   (	"PCA_KEYPCA" NUMBER(5,0), 
	"PCA_KEYCIA" VARCHAR2(2), 
	"PCA_REGPLA" VARCHAR2(25), 
	"PCA_FECINI" DATE, 
	"PCA_FECFIN" DATE, 
	"PCA_CA1AUX" VARCHAR2(10), 
	"PCA_CA2AUX" VARCHAR2(10), 
	"PCA_CA3AUX" VARCHAR2(10), 
	"PCA_TIPPLA" VARCHAR2(1)
   ) ;
