CREATE TABLE "LABPROD"."INLOKARD" 
   (	"KAR_KEYEMP" NUMBER(5,0), 
	"KAR_KEYCUR" VARCHAR2(8), 
	"KAR_KEYGPO" NUMBER(5,0), 
	"KAR_KEYDEP" VARCHAR2(16), 
	"KAR_KEYPUE" VARCHAR2(16), 
	"KAR_CALIFI" NUMBER(8,4), 
	"KAR_APROBA" VARCHAR2(1), 
	"KAR_HORCUR" VARCHAR2(5), 
	"KAR_KEYFTE" VARCHAR2(13), 
	"KAR_FECACT" DATE, 
	"KAR_HORACT" VARCHAR2(8)
   ) ;
