CREATE TABLE "LABPROD"."MOLODCAL" 
   (	"DCA_DBORIG" NUMBER(5,0), 
	"DCA_DBOPER" NUMBER(5,0), 
	"DCA_KEYCAL" NUMBER(5,0), 
	"DCA_FECDIA" DATE, 
	"DCA_TIPDIA" VARCHAR2(3), 
	"DCA_TABCAM" VARCHAR2(20), 
	"DCA_VALOR" VARCHAR2(16)
   ) ;
