CREATE TABLE "LABPROD"."NMCALINCI" 
   (	"INC_KEYPER" VARCHAR2(7), 
	"INC_FECLUN" DATE, 
	"INC_FECMAR" DATE, 
	"INC_FECMIE" DATE, 
	"INC_FECJUE" DATE, 
	"INC_FECVIE" DATE, 
	"INC_FECSAB" DATE, 
	"INC_FECDOM" DATE
   ) ;
ALTER TABLE "LABPROD"."NMCALINCI" ADD CONSTRAINT "NMCALINCI01" UNIQUE ("INC_KEYPER")
  USING INDEX  ENABLE;
