CREATE TABLE "LABPROD"."NMCOFORP" 
   (	"FOR_KEYFOR" VARCHAR2(16), 
	"FOR_DESFOR" VARCHAR2(60), 
	"FOR_RENENC" NUMBER(5,0), 
	"FOR_RENDET" NUMBER(5,0), 
	"FOR_RENTOT" NUMBER(5,0), 
	"FOR_RENPIE" NUMBER(5,0), 
	"FOR_COLUMN" NUMBER(5,0), 
	"FOR_NUMASC" NUMBER(5,0), 
	"FOR_TOTPAG" VARCHAR2(1), 
	"FOR_ORDENA" VARCHAR2(110), 
	"FOR_KEYUSU" NUMBER(10,0), 
	"FOR_NOMARC" VARCHAR2(60)
   ) ;
