CREATE TABLE "LABPROD"."NMCORVAC" 
   (	"RVA_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"RVA_ANTIGU" NUMBER(*,0) NOT NULL ENABLE, 
	"RVA_CONSEC" NUMBER(*,0), 
	"RVA_FECSOL" DATE, 
	"RVA_PERIOD" VARCHAR2(10), 
	"RVA_FECINI" DATE, 
	"RVA_FECFIN" DATE, 
	"RVA_DIADIS" NUMBER(6,2), 
	"RVA_AUTORI" VARCHAR2(100), 
	"RVA_MOTIVO" VARCHAR2(18), 
	"RVA_KEYDEP" VARCHAR2(18), 
	"RVA_KEYCEN" VARCHAR2(18), 
	"RVA_NUMFOL" VARCHAR2(12), 
	"RVA_NUMUSU" NUMBER(*,0), 
	"RVA_FECCAP" DATE
   ) ;
ALTER TABLE "LABPROD"."NMCORVAC" ADD PRIMARY KEY ("RVA_KEYEMP", "RVA_ANTIGU", "RVA_CONSEC")
  USING INDEX  ENABLE;
