CREATE TABLE "LABPROD"."NMCOCVAC" 
   (	"VAC_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"VAC_ANTIGU" NUMBER(*,0) NOT NULL ENABLE, 
	"VAC_DIAVAC" NUMBER(6,2), 
	"VAC_PERIOD" VARCHAR2(10), 
	"VAC_FECINI" DATE, 
	"VAC_FECFIN" DATE, 
	"VAC_FECPRE" DATE, 
	"VAC_DTOMAD" NUMBER(6,2), 
	"VAC_SALPER" NUMBER(6,2), 
	"VAC_STATUS" VARCHAR2(1), 
	"VAC_COSREA" NUMBER(10,2)
   ) ;
