CREATE TABLE "LABPROD"."NMCOPVAC" 
   (	"PVA_KEYPRO" NUMBER(*,0) NOT NULL ENABLE, 
	"PVA_PLAPRE" NUMBER(4,2), 
	"PVA_CONNOM" VARCHAR2(3) NOT NULL ENABLE, 
	"PVA_STAPAS" VARCHAR2(1) NOT NULL ENABLE
   ) ;
