CREATE TABLE "LABPROD"."NMCOCPER" 
   (	"CPE_KEYPRO" NUMBER(5,0), 
	"CPE_PERORI" VARCHAR2(7), 
	"CPE_KEYEMP" NUMBER(10,0), 
	"CPE_PERNUE" VARCHAR2(7), 
	"CPE_KEYINC" NUMBER(16,6), 
	"CPE_KEYCON" VARCHAR2(3), 
	"CPE_CANTID" NUMBER(16,6), 
	"CPE_IMPORT" NUMBER(12,2), 
	"CPE_STATUS" NUMBER(5,0), 
	"CPE_FECREG" DATE, 
	"CPE_HORREG" VARCHAR2(8), 
	"CPE_KEYUSU" NUMBER(10,0)
   ) ;
