CREATE TABLE "LABPROD"."NMDESCAN" 
   (	"DES_NODES" NUMBER(*,0) NOT NULL ENABLE, 
	"DES_DESCA1" CHAR(16) NOT NULL ENABLE, 
	"DES_DESCA2" CHAR(16) NOT NULL ENABLE
   ) ;
ALTER TABLE "LABPROD"."NMDESCAN" ADD PRIMARY KEY ("DES_NODES")
  USING INDEX  ENABLE;
