CREATE TABLE "LABPROD"."NMDETINC" 
   (	"INC_CVEDIA" VARCHAR2(2), 
	"INC_KEYUSU" NUMBER(*,0), 
	"INC_KEYEMP" NUMBER(*,0), 
	"INC_KEYSEM" NUMBER(*,0), 
	"INC_CCOSTO" VARCHAR2(16), 
	"INC_HORENT" VARCHAR2(5), 
	"INC_HORSAL" VARCHAR2(5), 
	"INC_CONCEP" VARCHAR2(3), 
	"INC_FECHA" DATE, 
	"INC_HORAS" NUMBER(5,2), 
	"INC_IMPOR" NUMBER(14,2), 
	"INC_CVEINC" VARCHAR2(2), 
	"INC_KEYPRO" NUMBER(*,0), 
	"INC_KEYPER" VARCHAR2(7)
   )  ENABLE ROW MOVEMENT ;
