CREATE TABLE "LABPROD"."NMLOCOSA" 
   (	"COS_KEYIMS" VARCHAR2(5), 
	"COS_KEYEMP" NUMBER(10,0), 
	"COS_REGPAT" VARCHAR2(11), 
	"COS_REGIMS" VARCHAR2(11), 
	"COS_REGRFC" VARCHAR2(13), 
	"COS_RECURP" VARCHAR2(18), 
	"COS_NOMBRE" VARCHAR2(50), 
	"COS_TIPTRA" VARCHAR2(1), 
	"COS_TIPJOR" VARCHAR2(1), 
	"COS_FECALT" VARCHAR2(10), 
	"COS_SALINT" NUMBER(12,6), 
	"COS_CVEUBI" VARCHAR2(17), 
	"COS_NUMCRE" VARCHAR2(10), 
	"COS_FECIDE" VARCHAR2(10), 
	"COS_TIPDES" VARCHAR2(1), 
	"COS_VALDES" NUMBER(12,6)
   ) ;
