CREATE TABLE "LABPROD"."NMLOFONE" 
   (	"FON_KEYFON" NUMBER(10,0) NOT NULL ENABLE, 
	"FON_KEYPRO" NUMBER(3,0) NOT NULL ENABLE, 
	"FON_FECCAR" DATE NOT NULL ENABLE, 
	"FON_HORCAR" VARCHAR2(8) NOT NULL ENABLE, 
	"FON_NOMARC" VARCHAR2(200) NOT NULL ENABLE, 
	"FON_KEYUSU" NUMBER(5,0) NOT NULL ENABLE, 
	"FON_NUMANI" NUMBER(4,0) NOT NULL ENABLE, 
	"FON_NUMMES" NUMBER(2,0) NOT NULL ENABLE, 
	"FON_ACTUAL" NUMBER(1,0) NOT NULL ENABLE
   ) ;
