CREATE TABLE "LABPROD"."NMLOCANR" 
   (	"CAN_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"CAN_KEYPRO" NUMBER(5,0) NOT NULL ENABLE, 
	"CAN_PERORI" VARCHAR2(7) NOT NULL ENABLE, 
	"CAN_PERCAN" VARCHAR2(7) NOT NULL ENABLE, 
	"CAN_FECREG" DATE, 
	"CAN_HORREG" VARCHAR2(10), 
	"CAN_KEYUSU" NUMBER(10,0)
   ) ;
