CREATE TABLE "LABPROD"."NMLOCFGN" 
   (	"CFG_KEYCFG" VARCHAR2(5), 
	"CFG_KEYCIA" VARCHAR2(2), 
	"CFG_KEYPRO" NUMBER(10,0), 
	"CFG_DESCFG" VARCHAR2(30), 
	"CFG_KEYNOM" NUMBER(5,0), 
	"CFG_TABLAT" VARCHAR2(2), 
	"CFG_FECREG" DATE, 
	"CFG_FECACT" DATE
   ) ;
