CREATE TABLE "LABPROD"."NMLOSEMA" 
   (	"SEM_KEYSEM" VARCHAR2(6) NOT NULL ENABLE, 
	"SEM_NUMANI" VARCHAR2(4) NOT NULL ENABLE, 
	"SEM_NUMSEM" VARCHAR2(2) NOT NULL ENABLE, 
	"SEM_FECINI" DATE NOT NULL ENABLE, 
	"SEM_FECFIN" DATE NOT NULL ENABLE
   ) ;
