CREATE TABLE "LABPROD"."NMLOCATE" 
   (	"CAT_KEYCAT" VARCHAR2(16) NOT NULL ENABLE, 
	"CAT_DESCAT" VARCHAR2(40) NOT NULL ENABLE, 
	"CAT_REFCON" VARCHAR2(20), 
	"CAT_NU1AUX" VARCHAR2(10), 
	"CAT_NU2AUX" VARCHAR2(10), 
	"CAT_NU3AUX" VARCHAR2(10), 
	"CAT_NU4AUX" VARCHAR2(10), 
	"CAT_NU5AUX" VARCHAR2(10), 
	"CAT_CA1AUX" VARCHAR2(10), 
	"CAT_CA2AUX" VARCHAR2(10), 
	"CAT_CA3AUX" VARCHAR2(10), 
	"CAT_CA4AUX" VARCHAR2(10), 
	"CAT_CA5AUX" VARCHAR2(10)
   ) ;
ALTER TABLE "LABPROD"."NMLOCATE" ADD CONSTRAINT "NMCATE01" UNIQUE ("CAT_KEYCAT")
  USING INDEX  ENABLE;
