CREATE TABLE "LABPROD"."NMLOENFM" 
   (	"ENF_KEYFOR" VARCHAR2(4) NOT NULL ENABLE, 
	"ENF_DE1FOR" VARCHAR2(40), 
	"ENF_DE2FOR" VARCHAR2(40), 
	"ENF_DE3FOR" VARCHAR2(40), 
	"ENF_IDEVER" VARCHAR2(15)
   ) ;
