CREATE TABLE "LABPROD"."NMLODFIJ" 
   (	"DFI_KEYEMP" NUMBER(10,0), 
	"DFI_KEYCON" VARCHAR2(3), 
	"DFI_KEYPRO" NUMBER(5,0), 
	"DFI_PERINI" VARCHAR2(7), 
	"DFI_PERFIN" VARCHAR2(7), 
	"DFI_KEYDEP" VARCHAR2(16), 
	"DFI_KEYPUE" VARCHAR2(16), 
	"DFI_FECMOV" DATE, 
	"DFI_CANTID" NUMBER(12,2), 
	"DFI_IMPORT" NUMBER(12,2), 
	"DFI_CA1AUX" VARCHAR2(10), 
	"DFI_CA2AUX" VARCHAR2(10)
   ) ;
