CREATE TABLE "LABPROD"."NMLOINFO" 
   (	"ID" NUMBER(*,0) NOT NULL ENABLE, 
	"INF_KEYEMP" NUMBER(10,0) NOT NULL ENABLE, 
	"INF_TIPMOV" VARCHAR2(2) NOT NULL ENABLE, 
	"INF_FECMOV" DATE NOT NULL ENABLE, 
	"INF_TIPDES" VARCHAR2(1) NOT NULL ENABLE, 
	"INF_VALDES" NUMBER(10,4) NOT NULL ENABLE, 
	"INF_REGINF" VARCHAR2(12), 
	"INF_FECCAP" DATE NOT NULL ENABLE, 
	"INF_HORCAP" VARCHAR2(8) NOT NULL ENABLE, 
	"INF_KEYUSU" NUMBER(5,0) NOT NULL ENABLE, 
	"INF_PERINI" VARCHAR2(7)
   ) ;
