CREATE TABLE "LABPROD"."NMLOCCOL" 
   (	"CCO_KEYRCO" VARCHAR2(8), 
	"CCO_NUMSEC" NUMBER(38,0), 
	"CCO_SECOPE" NUMBER(38,0), 
	"CCO_OPERAN" VARCHAR2(10), 
	"CCO_OPERAD" VARCHAR2(1), 
	"CCO_TIPOPE" VARCHAR2(1), 
	"CCO_UNIIMP" VARCHAR2(1), 
	"CCO_PERACU" VARCHAR2(15)
   ) ;
