CREATE TABLE "LABPROD"."NMLODCCN" 
   (	"DCC_KEYCIA" VARCHAR2(5) NOT NULL ENABLE, 
	"DCC_KEYPER" VARCHAR2(7) NOT NULL ENABLE, 
	"DCC_KEYRUB" VARCHAR2(3) NOT NULL ENABLE, 
	"DCC_CODIMP" VARCHAR2(2) NOT NULL ENABLE, 
	"DCC_KEYCON" VARCHAR2(3) NOT NULL ENABLE, 
	"DCC_TIPOPE" VARCHAR2(1) NOT NULL ENABLE
   ) ;
