CREATE TABLE "LABPROD"."NMPROCHE" 
   (	"CHE_KEYPRO" NUMBER(5,0), 
	"CHE_KEYPER" VARCHAR2(7), 
	"CHE_KEYEMP" NUMBER(10,0), 
	"CHE_PERPRO" VARCHAR2(7), 
	"CHE_FECINS" DATE, 
	"CHE_KEYUSU" NUMBER(10,0), 
	"CHE_PERPAG" VARCHAR2(7), 
	"CHE_STATUS" VARCHAR2(1), 
	"ID" NUMBER(10,0)
   ) ;
ALTER TABLE "LABPROD"."NMPROCHE" ADD CONSTRAINT "NMPROCHE_PK" PRIMARY KEY ("CHE_KEYPRO", "CHE_KEYPER", "CHE_KEYEMP")
  USING INDEX  ENABLE;
