CREATE TABLE "LABPROD"."NMTABAYU" 
   (	"TAB_IDETAB" VARCHAR2(5), 
	"TAB_DESTAB" VARCHAR2(35), 
	"TAB_TRANSP" NUMBER(5,2), 
	"TAB_DESAYU" NUMBER(5,2), 
	"TAB_COMIDA" NUMBER(5,2), 
	"TAB_CENA" NUMBER(5,2), 
	"TAB_PASAJE" NUMBER(5,2), 
	"TAB_GASTRA" NUMBER(5,2), 
	"TAB_MONNOC" NUMBER(5,2), 
	"TAB_MAXALI" VARCHAR2(11)
   ) ;
