CREATE TABLE "LABPROD"."PLLOPNCN" 
   (	"PCN_KEYMIN" VARCHAR2(5), 
	"PCN_KEYPNL" VARCHAR2(5), 
	"PCN_KEYHOJ" VARCHAR2(5), 
	"PCN_KEYPCN" VARCHAR2(10), 
	"PCN_DESPCN" VARCHAR2(40), 
	"PCN_ORDEN" NUMBER(10,0), 
	"PCN_ORIGEN" VARCHAR2(1)
   ) ;
