CREATE TABLE "LABPROD"."PLLOINFO" 
   (	"INF_KEYMIN" VARCHAR2(5), 
	"INF_KEYEST" VARCHAR2(3), 
	"INF_KEYDEP" VARCHAR2(18), 
	"INF_KEYLIB" VARCHAR2(5), 
	"INF_KEYHOJ" VARCHAR2(5), 
	"INF_KEYCON" VARCHAR2(10), 
	"INF_KEYCOL" VARCHAR2(10), 
	"INF_KEYPER" NUMBER(10,0), 
	"INF_KEYVER" VARCHAR2(5), 
	"INF_VALINF" NUMBER(18,2), 
	"INF_STATUS" VARCHAR2(2)
   ) ;
