CREATE TABLE "LABPROD"."PLLOPERI" 
   (	"PER_KEYPER" NUMBER(10,0), 
	"PER_KEYMIN" VARCHAR2(5), 
	"PER_KEYTIP" NUMBER(5,0), 
	"PER_NIVELP" NUMBER(5,0), 
	"PER_DESPER" VARCHAR2(60), 
	"PER_FECINI" DATE, 
	"PER_FECFIN" DATE, 
	"PER_PPADRE" NUMBER(10,0), 
	"PER_AGREGA" VARCHAR2(2), 
	"PER_ORDPER" NUMBER(5,0), 
	"PER_STATUS" NUMBER(5,0)
   ) ;
