CREATE TABLE "LABPROD"."PLLOPCEL" 
   (	"PCE_KEYMIN" VARCHAR2(5), 
	"PCE_KEYPNL" VARCHAR2(5), 
	"PCE_KEYHOJ" VARCHAR2(5), 
	"PCE_KEYPCL" VARCHAR2(10), 
	"PCE_KEYPCN" VARCHAR2(10), 
	"PCE_FORMUL" VARCHAR2(800), 
	"PCE_FOMATO" VARCHAR2(25), 
	"PCE_COLOR" VARCHAR2(1), 
	"PCE_NATURA" VARCHAR2(1), 
	"PCE_STADEL" VARCHAR2(1)
   ) ;
