CREATE TABLE "LABPROD"."RECIBOS_GENERACION" 
   (	"ID" NUMBER(*,0), 
	"EJE_FECEJE" TIMESTAMP (3) NOT NULL ENABLE, 
	"EJE_MENSAJ" VARCHAR2(4000), 
	"EJE_ERROR" NUMBER(1,0) DEFAULT 0 NOT NULL ENABLE, 
	"EJE_KEYPRO" NUMBER(5,0), 
	"EJE_KEYPER" VARCHAR2(7)
   ) ;
