CREATE TABLE "LABPROD"."SCCOBAJA" 
   (	"ID" NUMBER(*,0), 
	"BAJ_KEYEMP" NUMBER(*,0), 
	"BAJ_FECBAJ" DATE, 
	"BAJ_FECIMS" DATE, 
	"BAJ_CVEBAJ" VARCHAR2(2), 
	"BAJ_CVEMOT" VARCHAR2(2), 
	"BAJ_PERBAJ" VARCHAR2(7), 
	"BAJ_STATUS" VARCHAR2(2), 
	"BAJ_NUMLIQ" VARCHAR2(6), 
	"BAJ_KEYUSU" NUMBER(5,0), 
	"BAJ_FECCAP" DATE, 
	"BAJ_HORCAP" VARCHAR2(8), 
	"BAJ_IDPLZ" NUMBER(*,0), 
	"BAJ_IDEMP" NUMBER(*,0), 
	"BAJ_TRAEMP" NUMBER(*,0), 
	"BAJ_TRAPRO" NUMBER(5,0)
   ) ;
ALTER TABLE "LABPROD"."SCCOBAJA" ADD CONSTRAINT "SCCOBAJA_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
