CREATE TABLE "LABPROD"."TVCAPDES" 
   (	"PDE_KEYEMP" NUMBER(*,0), 
	"PDE_RECURP" CHAR(18), 
	"PDE_FECMOV" DATE, 
	"PDE_CAPNEW" NUMBER(16,2), 
	"PDE_FECANT" DATE, 
	"PDE_CAPANT" NUMBER(16,2), 
	"PDE_STATUS" NUMBER(*,0), 
	"PDE_HORANT" CHAR(10), 
	"PDE_HORMOV" CHAR(10)
   ) ;
