CREATE TABLE "LABPROD"."TVGASDET" 
   (	"DET_KEYDET" NUMBER(*,0) NOT NULL ENABLE, 
	"DET_KEYCAR" NUMBER(*,0) NOT NULL ENABLE, 
	"DET_NUMMES" NUMBER(*,0), 
	"DET_KEYCIA" VARCHAR2(3), 
	"DET_TIPMOV" VARCHAR2(20), 
	"DET_TIPO" VARCHAR2(20), 
	"DEL_TIPCTA" VARCHAR2(20), 
	"DET_CIA" VARCHAR2(3), 
	"DET_NEG" VARCHAR2(2), 
	"DET_CTA" VARCHAR2(3), 
	"DET_SCTA" VARCHAR2(6), 
	"DET_CC" VARCHAR2(8), 
	"DET_ICIA" VARCHAR2(3), 
	"DET_TOP" VARCHAR2(1), 
	"DET_IMPCAR" NUMBER(16,2), 
	"DET_IMPABO" NUMBER(16,2), 
	"DET_TOTAL" NUMBER(16,2), 
	"DET_KEYPOL" VARCHAR2(10), 
	"DET_CIA2" VARCHAR2(3), 
	"DET_NEG2" VARCHAR2(2), 
	"DET_KEYCON" VARCHAR2(20), 
	"DET_DESPOL" VARCHAR2(100)
   ) ;
ALTER TABLE "LABPROD"."TVGASDET" ADD CONSTRAINT "TVGASDET_PK" PRIMARY KEY ("DET_KEYDET")
  USING INDEX  ENABLE;
ALTER TABLE "LABPROD"."TVGASDET" ADD CONSTRAINT "TVGASDET_FOREING_KEY" FOREIGN KEY ("DET_KEYCAR")
	  REFERENCES "LABPROD"."TVGASCAR" ("CAR_KEYCAR") ENABLE;
