CREATE TABLE "LABPROD"."TVGASCAR" 
   (	"CAR_KEYCAR" NUMBER(*,0) NOT NULL ENABLE, 
	"CAR_KEYUSU" NUMBER(*,0) NOT NULL ENABLE, 
	"CAR_FECCAR" DATE, 
	"CAR_HORCAR" VARCHAR2(8), 
	"CAR_NOMARC" VARCHAR2(60), 
	"CAR_ANIO" NUMBER(*,0), 
	"CAR_NUMMES" NUMBER(*,0), 
	"CAR_STATUS" NUMBER(*,0), 
	"CAR_TOTFIL" NUMBER, 
	"CAR_TOTIMP" NUMBER(14,2)
   ) ;
ALTER TABLE "LABPROD"."TVGASCAR" ADD CONSTRAINT "TVGASCAR_PK" PRIMARY KEY ("CAR_KEYCAR")
  USING INDEX  ENABLE;
