CREATE TABLE "LABPROD"."TVLOHALT" 
   (	"HAL_KEYPRO" NUMBER(*,0) NOT NULL ENABLE, 
	"HAL_KEYPER" VARCHAR2(7) NOT NULL ENABLE, 
	"HAL_KEYNOM" NUMBER(*,0) NOT NULL ENABLE, 
	"HAL_KEYDEP" VARCHAR2(16), 
	"HAL_KEYCEN" VARCHAR2(16), 
	"HAL_REFCON" VARCHAR2(9), 
	"HAL_TPOEMP" VARCHAR2(6), 
	"HAL_KEYEMP" NUMBER(*,0), 
	"HAL_VICRH" VARCHAR2(10), 
	"HAL_VICCON" VARCHAR2(10), 
	"HAL_KEYPLZ" NUMBER(*,0), 
	"HAL_SALMES" NUMBER(12,2), 
	"HAL_STATUS" NUMBER(*,0), 
	"HAL_FECAUM" DATE
   ) ;
