CREATE TABLE "LABPROD"."TVPRBITA" 
   (	"BIT_KEYUSU" NUMBER(*,0) NOT NULL ENABLE, 
	"BIT_LOGUSU" CHAR(15) NOT NULL ENABLE, 
	"BIT_IDEPCC" CHAR(15) NOT NULL ENABLE, 
	"BIT_FECMOV" DATE NOT NULL ENABLE, 
	"BIT_HORMOV" CHAR(8) NOT NULL ENABLE, 
	"BIT_TIPMOV" CHAR(2) NOT NULL ENABLE, 
	"BIT_KEY001" CHAR(18), 
	"BIT_KEY002" CHAR(18) NOT NULL ENABLE, 
	"BIT_KEY003" NUMBER(*,0) NOT NULL ENABLE, 
	"BIT_VAL001" CHAR(18), 
	"BIT_VAL002" CHAR(18), 
	"BIT_VAL003" CHAR(18), 
	"BIT_DESMEN" CHAR(36), 
	"BIT_IDENIV" NUMBER(*,0) NOT NULL ENABLE, 
	"BIT_KEYPRE" NUMBER(16,6), 
	"BIT_CA1AUX" NUMBER(*,0)
   ) ;
