CREATE TABLE "LABPROD"."WEPARMEN" 
   (	"WEP_CVEMEN" NUMBER(*,0), 
	"WEP_NOMMEN" VARCHAR2(20), 
	"WEP_STATUS" NUMBER(*,0)
   ) ;
ALTER TABLE "LABPROD"."WEPARMEN" ADD PRIMARY KEY ("WEP_CVEMEN")
  USING INDEX  ENABLE;
