CREATE TABLE "LABPROD"."WEPARDET" 
   (	"DET_CVEDET" NUMBER(*,0), 
	"DET_CVEMEN" NUMBER(*,0), 
	"DET_CVEPRO" NUMBER(*,0), 
	"DET_NUMPAD" NUMBER(*,0), 
	"DET_NUMPOS" NUMBER(*,0), 
	"DET_VALPER" VARCHAR2(50)
   ) ;
ALTER TABLE "LABPROD"."WEPARDET" ADD PRIMARY KEY ("DET_CVEDET")
  USING INDEX  ENABLE;
