CREATE TABLE "LABPROD"."WESEND" 
   (	"ID" NUMBER(*,0), 
	"KEYEMP" NUMBER(*,0), 
	"KEYSOL" NUMBER(16,6), 
	"TIPO" NUMBER(*,0), 
	"FECHA_ENVIO" DATE, 
	"INTENTOS" NUMBER(*,0), 
	"ESTATUS" NUMBER(*,0), 
	"ERROR" VARCHAR2(200)
   ) ;
ALTER TABLE "LABPROD"."WESEND" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
