CREATE TABLE "LABPROD"."WESUPERV" 
   (	"SUP_CVESUP" NUMBER(*,0), 
	"SUP_KEYSUP" NUMBER(*,0) NOT NULL ENABLE, 
	"SUP_KEYEMP" NUMBER(*,0) NOT NULL ENABLE
   ) ;
ALTER TABLE "LABPROD"."WESUPERV" ADD PRIMARY KEY ("SUP_CVESUP")
  USING INDEX  ENABLE;
