CREATE TABLE "LABPROD"."XXHR_ELIM_EMPLEADOS_LAB" 
   (	"NO_EMPLEADO" VARCHAR2(30), 
	"MOTIVO_ABANDONO" VARCHAR2(100), 
	"FECHA_TERMINACION" DATE, 
	"ULT_FECHA_PROC_ESTANDAR" DATE, 
	"FECHA_FINAL_PROCESO" DATE, 
	"FECHA_SIPROS" DATE, 
	"SUBMOVIMIENTO" NUMBER(*,0), 
	"ESTATUS_INTERFACE" VARCHAR2(1), 
	"FECHA_INTERFACE" DATE, 
	"ID_LABORA" NUMBER(*,0)
   ) ;
