CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXMOR"."XXLMK_ERR_LIN_ARCH_VW" ("ID_ERROR", "ID_ARCHIVO", "NOM_ORDEN", "CVE_POSICION", "DES_ERROR", "NUM_LINEA") AS 
  SELECT
    ERR.ID_ERROR,
    ERR.ID_ARCHIVO,
    ERR.NOM_ORDEN,
    ERR.CVE_POSICION,
    ERR.DES_ERROR,
    ERR.NUM_LINEA
FROM
    XXMOR.XXLMK_ERRORES_ARCH_TAB ERR
WHERE
    ERR.CVE_POSICION = 'L'
ORDER BY
    ERR.NOM_ORDEN,
    ERR.NUM_LINEA;
