CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXMOR"."XXLMK_AUT_URG_LN_VW" ("ID_LINEA", "ID_ORDHDR", "NUM_LINEA", "CVE_CANAL", "DES_FEC_INI", "DES_FEC_FIN", "NUM_DURACION", "ID_BUYUNT", "DES_HORA_INI", "DES_HORA_FIN", "CAN_SPOTS", "CAN_LUN", "CAN_MAR", "CAN_MIE", "CAN_JUE", "CAN_VIE", "CAN_SAB", "CAN_DOM", "DES_TIPO_SERVICIO", "IND_BN", "IND_P", "DES_MARCA", "DES_VERSION", "CAN_TAR_SP_SIN_DESC", "CAN_TAR_SP_CON_DES", "CAN_TOT_LIN_SIN_DESC", "CAN_TOT_LIN_CON_DESC", "DES_SOBRECARGO", "DES_OBSERVACIONES", "DES_PLATAFORMA", "POS1", "POS2", "POS3", "POS_ANT", "POS_PEN", "POS_ULT", "FEC_CREACION", "CVE_CREADO_POR", "FEC_ACTUALIZACION", "CVE_ACTUALIZADO_POR", "DES_CAMPANA", "CAN_GRPS", "DES_SPTCHR", "DES_USRCHR", "CAN_SPOTS_X_SEM", "IND_ESTATUS", "ID_AUT", "ID_ORDEN", "IND_ESTATUS_AUT", "IND_TIPO_AUT", "IND_NIVEL", "NUM_LINEA_AUT", "DES_AUT") AS 
  SELECT
    O.ID_LINEA,
    O.ID_ORDHDR,
    O.NUM_LINEA,
    O.CVE_CANAL,
    O.DES_FEC_INI,
    O.DES_FEC_FIN,
    O.NUM_DURACION,
    O.ID_BUYUNT,
    O.DES_HORA_INI,
    O.DES_HORA_FIN,
    O.CAN_SPOTS,
    O.CAN_LUN,
    O.CAN_MAR,
    O.CAN_MIE,
    O.CAN_JUE,
    O.CAN_VIE,
    O.CAN_SAB,
    O.CAN_DOM,
    O.DES_TIPO_SERVICIO,
    O.IND_BN,
    O.IND_P,
    O.DES_MARCA,
    O.DES_VERSION,
    O.CAN_TAR_SP_SIN_DESC,
    O.CAN_TAR_SP_CON_DES,
    O.CAN_TOT_LIN_SIN_DESC,
    O.CAN_TOT_LIN_CON_DESC,
    O.DES_SOBRECARGO,
    O.DES_OBSERVACIONES,
    O.DES_PLATAFORMA,
    O.POS1,
    O.POS2,
    O.POS3,
    O.POS_ANT,
    O.POS_PEN,
    O.POS_ULT,
    O.FEC_CREACION,
    O.CVE_CREADO_POR,
    O.FEC_ACTUALIZACION,
    O.CVE_ACTUALIZADO_POR,
    O.DES_CAMPANA,
    O.CAN_GRPS,
    O.DES_SPTCHR,
    O.DES_USRCHR,
    O.CAN_SPOTS_X_SEM,
    O.IND_ESTATUS,
    AUT.ID_AUT,
    AUT.ID_ORDEN,
    NVL(AUT.IND_ESTATUS, 0) AS IND_ESTATUS_AUT,
    AUT.IND_TIPO_AUT,
    AUT.IND_NIVEL,
    AUT.NUM_LINEA AS NUM_LINEA_AUT,
    AUT.DES_AUT
FROM
    XXLMK_ORDLN_TAB    O
JOIN
    (SELECT * FROM
        XXLMK_AUTORIZACIONES_TAB    A
        WHERE A.IND_NIVEL       = 'L'
        AND   A.IND_TIPO_AUT    = 'URG'
    ) AUT
ON O.ID_ORDHDR = AUT.ID_ORDEN
AND O.NUM_LINEA = AUT.NUM_LINEA;
