CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXMOR"."XXLMK_LINEAS_SPOTS_VW" ("ID_LINEA", "ID_ORDHDR", "NUM_LINEA", "CVE_CANAL", "DES_FEC_INI", "DES_FEC_FIN", "NUM_DURACION", "ID_BUYUNT", "DES_HORA_INI", "DES_HORA_FIN", "CAN_SPOTS", "CAN_LUN", "CAN_MAR", "CAN_MIE", "CAN_JUE", "CAN_VIE", "CAN_SAB", "CAN_DOM", "DES_TIPO_SERVICIO", "IND_BN", "IND_P", "DES_MARCA", "DES_VERSION", "CAN_TAR_SP_SIN_DESC", "CAN_TAR_SP_CON_DES", "CAN_TOT_LIN_SIN_DESC", "CAN_TOT_LIN_CON_DESC", "DES_SOBRECARGO", "DES_OBSERVACIONES", "DES_PLATAFORMA", "POS1", "POS2", "POS3", "POS_ANT", "POS_PEN", "POS_ULT", "FEC_CREACION", "CVE_CREADO_POR", "FEC_ACTUALIZACION", "CVE_ACTUALIZADO_POR", "DES_CAMPANA", "CAN_GRPS", "DES_SPTCHR", "DES_USRCHR", "CAN_SPOTS_X_SEM", "IND_ESTATUS", "ID_SPOT", "ID_LINEA1", "DES_FECHA_BREAK", "DES_HORA_INICIO", "DES_HORA_FIN1", "DES_HORA_BREAK", "NUM_DURACION1", "DES_TOLERANCIA", "IND_ESTATUS1", "FEC_CREACION1", "CVE_CREADO_POR1", "FEC_ACTUALIZACION1", "CVE_ACTUALIZADO_POR1", "NUM_CAMP", "FEC_INI_CAMP", "FEC_FIN_CAMP", "VAL_TARIFA", "ESTATUS_ORDEN", "IND_TIPO_ORDEN", "CVE_ADVID", "CVE_MCONTID", "NOM_ARCHIVO_SOL", "NUM_PRODUCT") AS 
  SELECT
    OL.ID_LINEA ,
    OL.ID_ORDHDR ,
    OL.NUM_LINEA ,
    OL.CVE_CANAL ,
    OL.DES_FEC_INI ,
    OL.DES_FEC_FIN ,
    OL.NUM_DURACION ,
    OL.ID_BUYUNT ,
    OL.DES_HORA_INI ,
    OL.DES_HORA_FIN ,
    OL.CAN_SPOTS ,
    OL.CAN_LUN ,
    OL.CAN_MAR ,
    OL.CAN_MIE ,
    OL.CAN_JUE ,
    OL.CAN_VIE ,
    OL.CAN_SAB ,
    OL.CAN_DOM ,
    OL.DES_TIPO_SERVICIO ,
    OL.IND_BN ,
    OL.IND_P ,
    OL.DES_MARCA ,
    OL.DES_VERSION ,
    OL.CAN_TAR_SP_SIN_DESC ,
    OL.CAN_TAR_SP_CON_DES ,
    OL.CAN_TOT_LIN_SIN_DESC ,
    OL.CAN_TOT_LIN_CON_DESC ,
    OL.DES_SOBRECARGO ,
    OL.DES_OBSERVACIONES ,
    OL.DES_PLATAFORMA ,
    OL.POS1 ,
    OL.POS2 ,
    OL.POS3 ,
    OL.POS_ANT ,
    OL.POS_PEN ,
    OL.POS_ULT ,
    OL.FEC_CREACION ,
    OL.CVE_CREADO_POR ,
    OL.FEC_ACTUALIZACION ,
    OL.CVE_ACTUALIZADO_POR ,
    OL.DES_CAMPANA ,
    OL.CAN_GRPS ,
    OL.DES_SPTCHR ,
    OL.DES_USRCHR ,
    OL.CAN_SPOTS_X_SEM ,
    OL.IND_ESTATUS ,
    LS.ID_SPOT ,
    LS.ID_LINEA ID_LINEA1 ,
    LS.DES_FECHA_BREAK ,
    LS.DES_HORA_INICIO ,
    LS.DES_HORA_FIN DES_HORA_FIN1 ,
    LS.DES_HORA_BREAK ,
    LS.NUM_DURACION NUM_DURACION1 ,
    LS.DES_TOLERANCIA ,
    LS.IND_ESTATUS         IND_ESTATUS1 ,
    LS.FEC_CREACION        FEC_CREACION1 ,
    LS.CVE_CREADO_POR      CVE_CREADO_POR1 ,
    LS.FEC_ACTUALIZACION   FEC_ACTUALIZACION1 ,
    LS.CVE_ACTUALIZADO_POR CVE_ACTUALIZADO_POR1 ,
    CE.NUM_CAMP,
    CE.FEC_INI_CAMP,
    CE.FEC_FIN_CAMP,
    NVL(LS.VAL_TARIFA, 0) AS VAL_TARIFA,
    O.IND_ESTATUS         AS ESTATUS_ORDEN,
    O.IND_TIPO_ORDEN,
    O.CVE_ADVID,
    O.CVE_MCONTID,
    AR.NOM_ARCHIVO_SOL,
    CE.NUM_PRODUCT
FROM
    XXMOR.XXLMK_ORDLN_TAB OL
JOIN
    XXMOR.XXLMK_LINEAS_SPOTS_TAB LS
ON
    OL.ID_LINEA = LS.ID_LINEA
JOIN
    XXMOR.XXLMK_ORDHDR_TAB O
ON
    OL.ID_ORDHDR = O.ID_ORDHDR
LEFT JOIN
    XXMOR.XXLMK_CAMP_ENV_TAB CE
ON
    CASE
        WHEN O.IND_TIPO_ORDEN = 1
        AND O.ID_ORDHDR = CE.ID_ORDHDR
        AND ( ( TRIM(OL.DES_TIPO_SERVICIO) = TRIM(CE.DES_TIPO_SERVICIO) )
            OR  ( TRIM(OL.DES_MARCA) = TRIM(CE.DES_TIPO_SERVICIO) ) )
        THEN 1
        WHEN (O.IND_TIPO_ORDEN = 2
            OR  O.IND_TIPO_ORDEN = 3)
        AND O.ID_ORDHDR = CE.ID_ORDHDR
        AND TRIM(O.DES_TIPO_SERV) = TRIM(CE.DES_TIPO_SERVICIO)
        THEN 1
        ELSE 0
    END = 1
JOIN
    XXMOR.XXLMK_ARCHIVOS_SOL_TAB AR
ON
    O.ID_ARCHIVO = AR.ID_ARCHIVO_SOL;
