CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXMOR"."XXMOR_ARCH_FZA_VTAS_VW" ("ID_FZA_VENTAS", "ID_ARCHIVO_FZA", "NOMBRE_FZA_VENTAS", "IDENT_FZA_VENTAS", "NOMBRE_ARCHIVO_FZA", "DESC_ARCHIVO_FZA", "CREATED_BY", "CREATED_DATE") AS 
  SELECT   AFV.ID_FZA_VENTAS,
              AFV.ID_ARCHIVO_FZA,
              FV.NOMBRE_FZA_VENTAS,
              FV.IDENT_FZA_VENTAS,
              AFV.NOMBRE_ARCHIVO_FZA,
              AFV.DESC_ARCHIVO_FZA,
              AFV.CREATED_BY,
              AFV.CREATED_DATE
       FROM   XXMOR_FZAS_VTAS_ARCHIVOS_TAB AFV, XXMOR_FZAS_VTAS_TAB FV
      WHERE   AFV.ID_FZA_VENTAS = FV.ID_FZA_VENTAS
   ORDER BY   1,
              3,
              4,
              5
 ;
