CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXMOR"."XXMOR_RETENCION_ORD_ENC_VW" ("ID_SOLICITUD", "ID_REQUEST", "ID_SEG_NEG", "ID_FZA_VENTAS", "IDENT_FZA_VENTAS", "ID_SOLICITUD_HNA", "PROC_POR_LINEA", "GARANTIZADO", "ADVID", "MCONTID", "MCONTID_CUTIN", "EMAIL", "AGYESTNUM", "ACCTHDRID", "RTCRDDSCR", "RTCRD", "RTCRDDSCR_CUTIN", "RTCRD_CUTIN", "COMENTARIOS", "SECNUM", "PLATAFORMA_CANAL", "AGRUPADOR", "PRDID_DESC", "PRDID", "TOTAL_SPOTS", "TOTAL_SIN_DESC", "TOTAL_CON_DESC", "TIPO_FACTURACION", "DESCUENTO", "TARGET", "CREATED_DATE", "CREATED_BY", "UPDATED_DATE", "UPDATED_BY", "ORDEN_ESTATUS", "FECHA_CONCOM", "TRACKING_ID_CONCOM", "AUX1", "AUX2", "AUX3") AS 
  SELECT DISTINCT E.ID_SOLICITUD, E.ID_REQUEST, E.ID_SEG_NEG, E.ID_FZA_VENTAS, F.IDENT_FZA_VENTAS, E.ID_SOLICITUD_HNA, E.PROC_POR_LINEA, E.GARANTIZADO, E.ADVID, E.MCONTID, E.MCONTID_CUTIN, E.EMAIL, E.AGYESTNUM, E.ACCTHDRID, E.RTCRDDSCR, E.RTCRD, E.RTCRDDSCR_CUTIN, E.RTCRD_CUTIN, E.COMENTARIOS, E.SECNUM, E.PLATAFORMA_CANAL, E.AGRUPADOR, E.PRDID_DESC, E.PRDID, E.TOTAL_SPOTS, E.TOTAL_SIN_DESC, E.TOTAL_CON_DESC, E.TIPO_FACTURACION, E.DESCUENTO, E.TARGET, E.CREATED_DATE, E.CREATED_BY, E.UPDATED_DATE, E.UPDATED_BY, E.ORDEN_ESTATUS, E.FECHA_CONCOM, E.TRACKING_ID_CONCOM, E.AUX1, E.AUX2, E.AUX3
FROM XXMOR_SOLICITUDES_ENC_TAB E,
     XXMOR_CONCOM_RPTA_TAB C,
     XXMOR_FZAS_VTAS_TAB F
WHERE E.ID_FZA_VENTAS = F.ID_FZA_VENTAS
and E.ID_SOLICITUD = c.id_solicitud
and upper(C.ACCION_CONCOM) = 'RETENCION'
AND C.ESTATUS_ORDUNI = 10
 ;
