CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXMOR"."XXMOR_CANALES_NAC_VW" ("CANAL") AS 
  select '2CAN' AS CANAL FROM DUAL
UNION
SELECT '4CAN' FROM DUAL
UNION
SELECT '5CAN' FROM DUAL
UNION
SELECT '9CAN' FROM DUAL
 ;
