CREATE OR REPLACE FORCE EDITIONABLE VIEW "XXMOR"."XXMOR_CONCOM_RPTA_TAB_VW" ("ID_SOLICITUD", "ID_RPTA_CONCOM", "RESULTADOGENERAL", "TRACKINGID", "DESC_CONCOM", "POSICION_CONCOM", "ID_CONCOM", "NUMLINEA_CONCOM", "ESTATUS_CONCOM", "CAMPO_CONCOM", "DETALLE_CONCOM", "ACCION_CONCOM", "TIPOREGLA_CONCOM", "ESTATUS_ORDUNI", "CREATED_DATE", "CREATED_BY", "UPDATED_DATE", "UPDATED_BY", "ID_SEG_NEG", "TAKE_IT") AS 
  SELECT ID_SOLICITUD, ID_RPTA_CONCOM, RESULTADOGENERAL, TRACKINGID, DESC_CONCOM, POSICION_CONCOM, ID_CONCOM, NUMLINEA_CONCOM,
            ESTATUS_CONCOM, CAMPO_CONCOM, DETALLE_CONCOM, ACCION_CONCOM, TIPOREGLA_CONCOM, ESTATUS_ORDUNI, CREATED_DATE, CREATED_BY,
            UPDATED_DATE, UPDATED_BY, ID_SEG_NEG,nvl(UPDATED_BY,0) as take_it
FROM XXMOR_CONCOM_RPTA_TAB
 ;
