CREATE TABLE "LABCONF"."CFDICOMPROBANTERECEPTOR" 
   (	"IDCOMPROBANTEEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"COM_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"RFC" VARCHAR2(13) NOT NULL ENABLE, 
	"NOMBRE" VARCHAR2(100), 
	"CALLE" VARCHAR2(100), 
	"NOEXTERIOR" VARCHAR2(100), 
	"NOINTERIOR" VARCHAR2(100), 
	"COLONIA" VARCHAR2(100), 
	"LOCALIDAD" VARCHAR2(100), 
	"REFERENCIA" VARCHAR2(100), 
	"MUNICIPIO" VARCHAR2(100), 
	"ESTADO" VARCHAR2(100), 
	"PAIS" VARCHAR2(100), 
	"CODIGOPOSTAL" VARCHAR2(5)
   ) ;
ALTER TABLE "LABCONF"."CFDICOMPROBANTERECEPTOR" ADD CONSTRAINT "CFDICOMPROBANTERECEPTOR_PK" PRIMARY KEY ("IDCOMPROBANTEEMP")
  USING INDEX  ENABLE;
