CREATE TABLE "LABCONF"."CFDI2ESTATUSRECIBOS" 
   (	"IDCOMPROBANTEEMP" NUMBER(10,0) NOT NULL ENABLE, 
	"EST_FECLEC" TIMESTAMP (3), 
	"EST_STATUS" NUMBER(5,0), 
	"EST_ERROR" VARCHAR2(4000)
   ) ;
ALTER TABLE "LABCONF"."CFDI2ESTATUSRECIBOS" ADD CONSTRAINT "PK_CFDI2ESTATUSRECIBOS" PRIMARY KEY ("IDCOMPROBANTEEMP")
  USING INDEX  ENABLE;
