CREATE TABLE "LABCONF"."CFDI2CANCELACIONES" 
   (	"IDCOMPROBANTEEMP" NUMBER(10,0) NOT NULL ENABLE, 
	"CAN_KEYEMP" NUMBER(10,0) NOT NULL ENABLE, 
	"CAN_KEYPRO" NUMBER(5,0) NOT NULL ENABLE, 
	"CAN_KEYPER" VARCHAR2(7) NOT NULL ENABLE, 
	"CAN_UUID" VARCHAR2(36), 
	"CAN_ESTATUS" NUMBER(5,0), 
	"CAN_XMLCANCELADO" VARCHAR2(4000), 
	"CAN_FECHACANCELACION" TIMESTAMP (3), 
	"CAN_PAC" VARCHAR2(10), 
	"MOTIVOCANCELACION" VARCHAR2(2), 
	"FOLIOSUSTITUCION" VARCHAR2(36) DEFAULT '', 
	"IDCOMPROBANTEEMPSUSTITUCION" NUMBER(*,0)
   ) ;
ALTER TABLE "LABCONF"."CFDI2CANCELACIONES" ADD CONSTRAINT "PK_CFDI2CANCELACIONES" PRIMARY KEY ("IDCOMPROBANTEEMP")
  USING INDEX  ENABLE;
