CREATE TABLE "LABCONF"."CFDI2PERCEPCIONESSEPARACION" 
   (	"IDNOMINA" NUMBER(10,0) NOT NULL ENABLE, 
	"TOTALPAGADO" NUMBER(18,2) NOT NULL ENABLE, 
	"NUMANIOSSERVICIO" NUMBER(10,0) NOT NULL ENABLE, 
	"ULTIMOSUELDOMENSORD" NUMBER(18,2) NOT NULL ENABLE, 
	"INGRESOACUMULABLE" NUMBER(18,2) NOT NULL ENABLE, 
	"INGRESONOACUMULABLE" NUMBER(18,2) NOT NULL ENABLE
   ) ;
ALTER TABLE "LABCONF"."CFDI2PERCEPCIONESSEPARACION" ADD CONSTRAINT "PK_CFDI2PERCEPCIONESSEPARACION" PRIMARY KEY ("IDNOMINA")
  USING INDEX  ENABLE;
