CREATE TABLE "LABCONF"."CFDI2HORASEXTRA" 
   (	"IDNOMINA" NUMBER(10,0) NOT NULL ENABLE, 
	"IDPERCEPCION" NUMBER(10,0) NOT NULL ENABLE, 
	"DIAS" NUMBER(10,0), 
	"TIPOHORAS" VARCHAR2(2), 
	"HORASEXTRA" NUMBER(10,0), 
	"IMPORTEPAGADO" NUMBER(18,2)
   ) ;
