CREATE TABLE "LABCONF"."CFDI2QR" 
   (	"IDCOMPROBANTEEMP" NUMBER(10,0) NOT NULL ENABLE, 
	"QRCODE" BLOB
   ) ;
ALTER TABLE "LABCONF"."CFDI2QR" ADD CONSTRAINT "PK_CFDI2QR" PRIMARY KEY ("IDCOMPROBANTEEMP")
  USING INDEX  ENABLE;
