CREATE TABLE "LABCONF"."DETALLEPARAMETROS" 
   (	"IDDETALLE" NUMBER(10,0) NOT NULL ENABLE, 
	"ENQ_KEYREP" VARCHAR2(16) NOT NULL ENABLE, 
	"ORDEN" NUMBER(10,0) NOT NULL ENABLE, 
	"DESCRIPCIONPARAMETRO" VARCHAR2(50) NOT NULL ENABLE
   ) ;
ALTER TABLE "LABCONF"."DETALLEPARAMETROS" ADD CONSTRAINT "PK_DETALLEPARAMETROS" PRIMARY KEY ("IDDETALLE")
  USING INDEX  ENABLE;
