CREATE TABLE "LABCONF"."EOLOMVPZ" 
   (	"MPZ_KEYPLZ" NUMBER(10,0) NOT NULL ENABLE, 
	"MPZ_KEYSOL" NUMBER(10,0) NOT NULL ENABLE, 
	"MPZ_KEYEST" VARCHAR2(3), 
	"MPZ_KEYDEP" VARCHAR2(16), 
	"MPZ_KEYPUE" VARCHAR2(16), 
	"MPZ_TIPMOV" VARCHAR2(2), 
	"MPZ_DESMOV" VARCHAR2(60), 
	"MPZ_FECMOV" DATE, 
	"MPZ_CA1AUX" VARCHAR2(10), 
	"MPZ_CA2AUX" VARCHAR2(10), 
	"MPZ_CA3AUX" VARCHAR2(10), 
	"MPZ_CA4AUX" VARCHAR2(10)
   ) ;
