CREATE TABLE "LABCONF"."GLCOERRO" 
   (	"MER_KEYERR" VARCHAR2(16), 
	"MER_TIPERR" VARCHAR2(3), 
	"MER_DESSIS" VARCHAR2(125), 
	"MER_DESUSU" VARCHAR2(125), 
	"MER_AYUERR" VARCHAR2(250), 
	"MER_TITMOS" VARCHAR2(25), 
	"MER_BOTMOS" NUMBER(10,0), 
	"MER_ICOMOS" NUMBER(10,0), 
	"MER_ARCAYU" VARCHAR2(20), 
	"MER_CONTEX" VARCHAR2(16), 
	"MER_VALDEV" NUMBER(5,0)
   ) ;
