CREATE TABLE "LABCONF"."HIST_DATOS" 
   (	"HID_ANIO" NUMBER(*,0) NOT NULL ENABLE, 
	"HID_MES" NUMBER(*,0) NOT NULL ENABLE, 
	"HID_KEYPRO" NUMBER(*,0) NOT NULL ENABLE, 
	"HID_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"HID_KEYDEP" VARCHAR2(16), 
	"HID_TPOEMP" NUMBER(*,0), 
	"HID_VICRH" VARCHAR2(16), 
	"HID_VICCON" VARCHAR2(16), 
	"HID_KEYPLZ" NUMBER(*,0), 
	"HID_KEYPUE" VARCHAR2(16)
   ) ;
ALTER TABLE "LABCONF"."HIST_DATOS" ADD PRIMARY KEY ("HID_ANIO", "HID_MES", "HID_KEYPRO", "HID_KEYEMP")
  USING INDEX  ENABLE;
