CREATE TABLE "LABCONF"."INLOPPRO" 
   (	"PPR_KEYPCA" NUMBER(5,0), 
	"PPR_KEYCIA" VARCHAR2(2), 
	"PPR_KEYPGR" NUMBER(5,0), 
	"PPR_CA1AUX" VARCHAR2(10), 
	"PPR_CA2AUX" VARCHAR2(10), 
	"PPR_CA3AUX" VARCHAR2(10)
   ) ;
