CREATE TABLE "LABCONF"."INLOCUEM" 
   (	"CUE_KEYEMP" NUMBER(5,0), 
	"CUE_RFCEMP" VARCHAR2(14), 
	"CUE_FECDIS" DATE, 
	"CUE_KEYCUR" VARCHAR2(8), 
	"CUE_KEYGPO" NUMBER(5,0), 
	"CUE_STATUS" VARCHAR2(2), 
	"CUE_FECSTA" DATE, 
	"CUE_CA1AUX" VARCHAR2(10), 
	"CUE_CA2AUX" VARCHAR2(10), 
	"CUE_CA3AUX" VARCHAR2(10)
   ) ;
