CREATE TABLE "LABCONF"."ISNCONF" 
   (	"IDCONFIG" NUMBER(10,0), 
	"CON_ANIO" NUMBER(4,0), 
	"CON_KEYENT" VARCHAR2(2), 
	"CON_KEYCON" VARCHAR2(3), 
	"CON_TIPCON" NUMBER(10,0), 
	"CON_TIPOPE" VARCHAR2(1)
   ) ;
