CREATE TABLE "LABCONF"."ISNTOTALES" 
   (	"ISN_KEYENT" VARCHAR2(2), 
	"ISN_KEYCIA" VARCHAR2(5), 
	"ISN_ANIO" NUMBER(*,0), 
	"ISN_MES" NUMBER(*,0), 
	"ISN_KEYPER" VARCHAR2(7), 
	"ISN_PORCEN" NUMBER(8,2), 
	"ISN_PORADI" NUMBER(8,2), 
	"ISN_KEYTAB" VARCHAR2(3), 
	"ISN_CUOFIJ" NUMBER(12,2), 
	"ISN_BASE" NUMBER(12,2), 
	"ISN_TOTREG" NUMBER(10,0), 
	"ISN_TOTEMP" NUMBER(10,0), 
	"ISN_IMPISN" NUMBER(12,2), 
	"ISN_IMPADI" NUMBER(12,2)
   ) ;
