CREATE TABLE "LABCONF"."MOLODIAD" 
   (	"DIA_KEYEMP" NUMBER(10,0), 
	"DIA_KEYCON" VARCHAR2(10), 
	"DIA_DIADER" NUMBER(10,0), 
	"DIA_FECINI" DATE, 
	"DIA_FECCAD" DATE, 
	"DIA_DIAANT" NUMBER(10,0), 
	"DIA_KEYUSU" NUMBER(10,0), 
	"DIA_FECACT" DATE
   ) ;
