CREATE TABLE "LABCONF"."NMCAPINC" 
   (	"INC_KEYUSU" NUMBER(*,0) NOT NULL ENABLE, 
	"INC_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"INC_KEYSEM" NUMBER(*,0) NOT NULL ENABLE, 
	"INC_KEYJOR" NUMBER(*,0) NOT NULL ENABLE, 
	"INC_KEYCCO" VARCHAR2(16) NOT NULL ENABLE, 
	"INC_FECCAP" DATE NOT NULL ENABLE, 
	"INC_DDESC1" VARCHAR2(2), 
	"INC_DDESC2" VARCHAR2(2), 
	"INC_KEYPRO" NUMBER(*,0), 
	"INC_XYTECH" NUMBER(*,0)
   ) ;
