CREATE TABLE "LABCONF"."NMSTAUSU" 
   (	"STA_KEYUSU" NUMBER(*,0), 
	"STA_KEYUBI" VARCHAR2(1), 
	"STA_STATUS" VARCHAR2(1), 
	"STA_VERUSU" VARCHAR2(300), 
	"STA_ACTIVO" VARCHAR2(5), 
	"STA_KEYSEM" VARCHAR2(53), 
	"STA_KEYSEMQ" VARCHAR2(53)
   ) ;
