CREATE TABLE "LABCONF"."NMTARJET" 
   (	"TAR_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"TAR_NOHOR" NUMBER(*,0) NOT NULL ENABLE, 
	"TAR_NODES" NUMBER(*,0) NOT NULL ENABLE
   ) ;
ALTER TABLE "LABCONF"."NMTARJET" ADD PRIMARY KEY ("TAR_KEYEMP")
  USING INDEX  ENABLE;
