CREATE TABLE "LABCONF"."NMWKHISM" 
   (	"HIS_KEYPRO" NUMBER(5,0), 
	"HIS_KEYEMP" NUMBER(10,0), 
	"HIS_KEYCON" VARCHAR2(3), 
	"HIS_CODIMP" VARCHAR2(2), 
	"HIS_KEYPER" VARCHAR2(7), 
	"HIS_CANTID" NUMBER(16,2), 
	"HIS_IMPORT" NUMBER(16,2), 
	"HIS_IDEPCC" VARCHAR2(15)
   ) ;
