CREATE TABLE "LABCONF"."PLLOHJPN" 
   (	"PNL_KEYMIN" VARCHAR2(5), 
	"PNL_KEYPNL" VARCHAR2(5), 
	"PNL_KEYHOJ" VARCHAR2(5), 
	"PNL_DESHOJ" VARCHAR2(25), 
	"PNL_SENSIB" NUMBER(10,0), 
	"PNL_COMENT" VARCHAR2(250), 
	"PNL_AUTORC" VARCHAR2(30), 
	"PNL_FECHAC" DATE, 
	"PNL_PRECOL" VARCHAR2(3), 
	"PNL_PRECON" VARCHAR2(2), 
	"PNL_HOJINF" VARCHAR2(5), 
	"PNL_TIPHOJ" VARCHAR2(1), 
	"PNL_STADEL" VARCHAR2(1)
   ) ;
