CREATE TABLE "LABCONF"."SCLOFURE" 
   (	"FUR_KEYFUE" VARCHAR2(16), 
	"FUR_FECREG" DATE, 
	"FUR_TIPFUE" VARCHAR2(6), 
	"FUR_NOMFUE" VARCHAR2(40), 
	"FUR_DOMFUE" VARCHAR2(60), 
	"FUR_EDOFUE" VARCHAR2(20), 
	"FUR_TELFUE" VARCHAR2(40), 
	"FUR_NOMAG1" VARCHAR2(40), 
	"FUR_PUEAG1" VARCHAR2(40), 
	"FUR_NOMAG2" VARCHAR2(40), 
	"FUR_PUEAG2" VARCHAR2(40), 
	"FUR_NOMAG3" VARCHAR2(40), 
	"FUR_PUEAG3" VARCHAR2(40), 
	"FUR_STATUS" VARCHAR2(2), 
	"FUR_FECSTA" DATE, 
	"FUR_FAXFUE" VARCHAR2(20), 
	"FUR_HORATE" VARCHAR2(20)
   ) ;
