CREATE TABLE "LABCONF"."TVPMOCAJ" 
   (	"OCA_TIPNOM" VARCHAR2(1) NOT NULL ENABLE, 
	"OCA_KEYCIA" VARCHAR2(4) NOT NULL ENABLE, 
	"OCA_KEYPRO" NUMBER(*,0) NOT NULL ENABLE, 
	"OCA_KEYPER" VARCHAR2(7) NOT NULL ENABLE, 
	"OCA_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"OCA_KEYPRE" NUMBER(*,0) NOT NULL ENABLE, 
	"OCA_IMPPRE" NUMBER(16,2) NOT NULL ENABLE, 
	"OCA_IMPDES" NUMBER(16,2) NOT NULL ENABLE, 
	"OCA_IMPSAL" NUMBER(16,2) NOT NULL ENABLE, 
	"OCA_UNIPRE" NUMBER(16,2) NOT NULL ENABLE, 
	"OCA_UNIDES" NUMBER(16,2) NOT NULL ENABLE, 
	"OCA_UNISAL" NUMBER(16,2) NOT NULL ENABLE, 
	"OCA_FECINI" DATE NOT NULL ENABLE, 
	"OCA_KEYUSU" NUMBER(*,0) NOT NULL ENABLE, 
	"OCA_IDEPCC" VARCHAR2(15) NOT NULL ENABLE, 
	"OCA_FECMOD" DATE NOT NULL ENABLE, 
	"OCA_KEYCON" VARCHAR2(3) NOT NULL ENABLE
   ) ;
