CREATE TABLE "LABCONF"."TVPRETAR" 
   (	"TAR_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"TAR_TPOPRO" NUMBER(*,0) NOT NULL ENABLE, 
	"TAR_STATUS" NUMBER(*,0) NOT NULL ENABLE, 
	"TAR_FECHA" CHAR(10) NOT NULL ENABLE, 
	"TAR_HORA" CHAR(8) NOT NULL ENABLE, 
	"TAR_IMPORTE" NUMBER(12,2) NOT NULL ENABLE, 
	"TAR_NOMBRE" VARCHAR2(70) NOT NULL ENABLE, 
	"TAR_USUARIO" NUMBER(*,0), 
	"TAR_AUXC" CHAR(60), 
	"TAR_AUXN" NUMBER(*,0), 
	"TAR_IDNNUM" NUMBER(*,0)
   ) ;
ALTER TABLE "LABCONF"."TVPRETAR" ADD PRIMARY KEY ("TAR_KEYEMP", "TAR_TPOPRO", "TAR_STATUS")
  USING INDEX  ENABLE;
