CREATE TABLE "LABCONF"."WEACCEMP" 
   (	"WEA_IDUSUA" NUMBER(*,0), 
	"WEA_KEYEMP" VARCHAR2(50), 
	"WEA_CLAVEA" VARCHAR2(50), 
	"WEA_FECALT" DATE, 
	"WEA_IDMENU" NUMBER(*,0), 
	"WEA_ESTATU" VARCHAR2(2)
   ) ;
ALTER TABLE "LABCONF"."WEACCEMP" ADD PRIMARY KEY ("WEA_IDUSUA")
  USING INDEX  ENABLE;
