CREATE TABLE "LABCONF"."WEPARPRO" 
   (	"PRO_CVEPRO" NUMBER(*,0), 
	"PRO_NOMPRO" VARCHAR2(40), 
	"PRO_TIPPRO" NUMBER(*,0), 
	"PRO_URLPRO" VARCHAR2(40), 
	"PRO_ICOPRO" VARCHAR2(40)
   ) ;
ALTER TABLE "LABCONF"."WEPARPRO" ADD PRIMARY KEY ("PRO_CVEPRO")
  USING INDEX  ENABLE;
