CREATE TABLE "XX_BLOQUEOBAJAS"."USUARIOEMPLEADO" 
   (	"IDUSUARIO" NUMBER NOT NULL ENABLE, 
	"USUARIO" VARCHAR2(50) NOT NULL ENABLE, 
	"KEYEMP" NUMBER NOT NULL ENABLE, 
	"FECHAINGRESO" DATE NOT NULL ENABLE, 
	"DIRIP" VARCHAR2(16) NOT NULL ENABLE, 
	"NOMBREPC" VARCHAR2(50) NOT NULL ENABLE, 
	"CORREO" VARCHAR2(50), 
	"ROL" VARCHAR2(20) NOT NULL ENABLE, 
	"NOMBREUSUARIO" VARCHAR2(100)
   ) ;
ALTER TABLE "XX_BLOQUEOBAJAS"."USUARIOEMPLEADO" ADD CONSTRAINT "USUARIOEMPLEADO_PK" PRIMARY KEY ("IDUSUARIO")
  USING INDEX  ENABLE;
ALTER TABLE "XX_BLOQUEOBAJAS"."USUARIOEMPLEADO" ADD CONSTRAINT "USUARIOEMPLEADO_UK1" UNIQUE ("USUARIO")
  USING INDEX  ENABLE;
