CREATE TABLE "LABCONF"."CFDI2NOMINAEMISOR" 
   (	"IDCOMPROBANTEEMP" NUMBER(10,0) NOT NULL ENABLE, 
	"CURP" VARCHAR2(18), 
	"REGISTROPATRONAL" VARCHAR2(20), 
	"RFCPATRONORIGEN" VARCHAR2(13), 
	"ORIGENRECURSO" VARCHAR2(2), 
	"MONTORECURSOPROPIO" NUMBER(18,2)
   ) ;
  CREATE UNIQUE INDEX "LABCONF"."PK_CFDI2NOMINAEMISOR" ON "LABCONF"."CFDI2NOMINAEMISOR" ("IDCOMPROBANTEEMP") 
  ;
ALTER TABLE "LABCONF"."CFDI2NOMINAEMISOR" ADD CONSTRAINT "PK_CFDI2NOMINAEMISOR" PRIMARY KEY ("IDCOMPROBANTEEMP")
  USING INDEX "LABCONF"."PK_CFDI2NOMINAEMISOR"  ENABLE;
