CREATE TABLE "LABCONF"."CFDI2PERCEPCIONESDETALLE" 
   (	"IDPERCEPCION" NUMBER(10,0) NOT NULL ENABLE, 
	"IDNOMINA" NUMBER(10,0) NOT NULL ENABLE, 
	"TIPOPERCEPCION" VARCHAR2(3) NOT NULL ENABLE, 
	"CLAVE" VARCHAR2(15) NOT NULL ENABLE, 
	"CONCEPTO" VARCHAR2(100) NOT NULL ENABLE, 
	"IMPORTEGRAVADO" NUMBER(18,2) NOT NULL ENABLE, 
	"IMPORTEEXENTO" NUMBER(18,2) NOT NULL ENABLE, 
	"VALORMERCADO" NUMBER(18,2), 
	"PRECIOALOTORGARSE" NUMBER(18,2)
   ) ;
  CREATE UNIQUE INDEX "LABCONF"."PK_CFDI2PERCEPCIONESDETALLE" ON "LABCONF"."CFDI2PERCEPCIONESDETALLE" ("IDPERCEPCION") 
  ;
ALTER TABLE "LABCONF"."CFDI2PERCEPCIONESDETALLE" ADD CONSTRAINT "PK_CFDI2PERCEPCIONESDETALLE" PRIMARY KEY ("IDPERCEPCION")
  USING INDEX "LABCONF"."PK_CFDI2PERCEPCIONESDETALLE"  ENABLE;
