CREATE TABLE "LABCONF"."CFDIINCAPACIDADES" 
   (	"IDCOMPROBANTEEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"COM_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"DIASINCAPACIDAD" NUMBER(18,6) NOT NULL ENABLE, 
	"TIPOINCAPACIDAD" NUMBER(*,0) NOT NULL ENABLE, 
	"DESCUENTO" NUMBER(18,6) NOT NULL ENABLE
   ) ;
