CREATE TABLE "LABCONF"."CFDIHORASEXTRA" 
   (	"IDCOMPROBANTEEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"COM_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"DIAS" NUMBER(*,0) NOT NULL ENABLE, 
	"TIPOHORAS" VARCHAR2(10) NOT NULL ENABLE, 
	"HORASEXTRA" NUMBER(18,6) NOT NULL ENABLE, 
	"IMPORTEPAGADO" NUMBER(18,6) NOT NULL ENABLE
   ) ;
