CREATE TABLE "LABCONF"."CFDI2PERCEPCIONESTOTAL" 
   (	"IDNOMINA" NUMBER(10,0) NOT NULL ENABLE, 
	"TOTALSUELDOS" NUMBER(18,2), 
	"TOTALSEPARACIONINDEMNIZACION" NUMBER(18,2), 
	"TOTALJUBILACIONPENSIONRETIRO" NUMBER(18,2), 
	"TOTALGRAVADO" NUMBER(18,2) NOT NULL ENABLE, 
	"TOTALEXENTO" NUMBER(18,2) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "LABCONF"."PK_CFDI2PERCEPCIONESTOTAL" ON "LABCONF"."CFDI2PERCEPCIONESTOTAL" ("IDNOMINA") 
  ;
ALTER TABLE "LABCONF"."CFDI2PERCEPCIONESTOTAL" ADD CONSTRAINT "PK_CFDI2PERCEPCIONESTOTAL" PRIMARY KEY ("IDNOMINA")
  USING INDEX "LABCONF"."PK_CFDI2PERCEPCIONESTOTAL"  ENABLE;
