CREATE TABLE "LABCONF"."CFDICONF" 
   (	"IDCONFIG" NUMBER(*,0) NOT NULL ENABLE, 
	"CON_KEYCIA" VARCHAR2(2) NOT NULL ENABLE, 
	"CON_CODIMP" VARCHAR2(2) NOT NULL ENABLE, 
	"CON_KEYCON" VARCHAR2(3) NOT NULL ENABLE, 
	"CON_TIPCON" VARCHAR2(1) NOT NULL ENABLE, 
	"CON_TIPSAT" VARCHAR2(3) NOT NULL ENABLE, 
	"CON_CLAVE" VARCHAR2(15) NOT NULL ENABLE, 
	"CON_DESCRI" VARCHAR2(100) NOT NULL ENABLE, 
	"CON_CAMEXE" VARCHAR2(6), 
	"CON_CAMGRA" VARCHAR2(6), 
	"CON_TIPOPE" VARCHAR2(1), 
	"CON_INCDIA" VARCHAR2(6), 
	"CON_INCDES" VARCHAR2(6), 
	"CON_HEXDIA" VARCHAR2(6), 
	"CON_HEXHOR" VARCHAR2(6), 
	"CON_HEXIMP" VARCHAR2(6), 
	"CON_DIAPAG" VARCHAR2(6)
   ) ;
  CREATE UNIQUE INDEX "LABCONF"."CFDICONF_PK" ON "LABCONF"."CFDICONF" ("IDCONFIG") 
  ;
ALTER TABLE "LABCONF"."CFDICONF" ADD CONSTRAINT "CFDICONF_PK" PRIMARY KEY ("IDCONFIG")
  USING INDEX "LABCONF"."CFDICONF_PK"  ENABLE;
