CREATE TABLE "LABCONF"."CFDI2NOMINARECEPTOR" 
   (	"IDNOMINA" NUMBER(10,0) NOT NULL ENABLE, 
	"CURP" VARCHAR2(18), 
	"NUMSEGURIDADSOCIAL" VARCHAR2(15), 
	"FECHAINICIORELLABORAL" DATE, 
	"ANTIGUEDAD" VARCHAR2(20), 
	"TIPOCONTRATO" VARCHAR2(2), 
	"SINDICALIZADO" VARCHAR2(2), 
	"TIPOJORNADA" VARCHAR2(2), 
	"TIPOREGIMEN" VARCHAR2(2), 
	"NUMEMPLEADO" VARCHAR2(15), 
	"DEPARTAMENTO" VARCHAR2(100), 
	"PUESTO" VARCHAR2(100), 
	"RIESGOPUESTO" VARCHAR2(1), 
	"PERIODICIDADPAGO" VARCHAR2(2), 
	"BANCO" VARCHAR2(3), 
	"CUENTABANCARIA" VARCHAR2(18), 
	"SALARIOBASECOTAPOR" NUMBER(18,2), 
	"SALARIODIARIOINTEGRADO" NUMBER(18,2), 
	"CLAVEENTFED" VARCHAR2(3)
   ) ;
  CREATE UNIQUE INDEX "LABCONF"."PK_CFDI2NOMINARECEPTOR" ON "LABCONF"."CFDI2NOMINARECEPTOR" ("IDNOMINA") 
  ;
ALTER TABLE "LABCONF"."CFDI2NOMINARECEPTOR" ADD CONSTRAINT "PK_CFDI2NOMINARECEPTOR" PRIMARY KEY ("IDNOMINA")
  USING INDEX "LABCONF"."PK_CFDI2NOMINARECEPTOR"  ENABLE;
