CREATE TABLE "LABCONF"."CFDINOMINA" 
   (	"IDCOMPROBANTEEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"IDCOMPROBANTEPRO" NUMBER(*,0), 
	"COM_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"VERSION" VARCHAR2(5) NOT NULL ENABLE, 
	"REGISTROPATRONAL" VARCHAR2(20), 
	"NUMEMPLEADO" VARCHAR2(15) NOT NULL ENABLE, 
	"CURP" VARCHAR2(18), 
	"TIPOREGIMEN" NUMBER(*,0), 
	"NUMSEGURIDADSOCIAL" VARCHAR2(20), 
	"FECHAPAGO" DATE NOT NULL ENABLE, 
	"FECHAINICIALPAGO" DATE NOT NULL ENABLE, 
	"FECHAFINALPAGO" DATE NOT NULL ENABLE, 
	"NUMDIASPAGADOS" NUMBER(18,6), 
	"DEPARTAMENTO" VARCHAR2(100), 
	"CLABE" VARCHAR2(20), 
	"BANCO" VARCHAR2(5), 
	"FECHAINICIORELLABORAL" DATE, 
	"ANTIGUEDAD" NUMBER(*,0), 
	"PUESTO" VARCHAR2(100), 
	"TIPOCONTRATO" VARCHAR2(50), 
	"TIPOJORNADA" VARCHAR2(50), 
	"PERIODICIDADPAGO" VARCHAR2(100) NOT NULL ENABLE, 
	"SALARIOBASECOTAPOR" NUMBER(18,6), 
	"RIESGOPUESTO" NUMBER(*,0), 
	"SALARIODIARIOINTEGRADO" NUMBER(18,6), 
	"TOTALGRAVADOPERCEPCION" NUMBER(18,6), 
	"TOTALEXENTOPERCEPCION" NUMBER(18,6), 
	"TOTALGRAVADODEDUCCION" NUMBER(18,6), 
	"TOTALEXENTODEDUCCION" NUMBER(18,6)
   ) ;
  CREATE UNIQUE INDEX "LABCONF"."CFDINOMINA_PK" ON "LABCONF"."CFDINOMINA" ("IDCOMPROBANTEEMP") 
  ;
ALTER TABLE "LABCONF"."CFDINOMINA" ADD CONSTRAINT "CFDINOMINA_PK" PRIMARY KEY ("IDCOMPROBANTEEMP")
  USING INDEX "LABCONF"."CFDINOMINA_PK"  ENABLE;
