CREATE TABLE "LABCONF"."CFDIREGIMEN" 
   (	"IDCOMPROBANTEPRO" NUMBER(*,0) NOT NULL ENABLE, 
	"REGIMEN" VARCHAR2(250)
   ) ;
  CREATE UNIQUE INDEX "LABCONF"."CFDIREGIMEN_PK" ON "LABCONF"."CFDIREGIMEN" ("IDCOMPROBANTEPRO") 
  ;
ALTER TABLE "LABCONF"."CFDIREGIMEN" ADD CONSTRAINT "CFDIREGIMEN_PK" PRIMARY KEY ("IDCOMPROBANTEPRO")
  USING INDEX "LABCONF"."CFDIREGIMEN_PK"  ENABLE;
