CREATE TABLE "LABCONF"."EOCOENCP" 
   (	"ECP_KEYDEP" VARCHAR2(16), 
	"ECP_KEYPUE" VARCHAR2(16), 
	"ECP_KEYCON" VARCHAR2(3), 
	"ECP_AUTORI" NUMBER(14,2), 
	"ECP_MODIFI" NUMBER(14,2), 
	"ECP_COMPRO" NUMBER(14,2), 
	"ECP_RESERV" NUMBER(14,2), 
	"ECP_EJERCI" NUMBER(14,2), 
	"ECP_DISPON" NUMBER(14,2), 
	"ECP_FECINI" DATE, 
	"ECP_FECFIN" DATE
   ) ;
