CREATE TABLE "LABCONF"."GLCODECO" 
   (	"DCO_RAZSOC" VARCHAR2(60), 
	"DCO_NUMLIC" NUMBER(38,0), 
	"DCO_IDENPC" VARCHAR2(16), 
	"DCO_SISOPE" VARCHAR2(20), 
	"DCO_FECREG" DATE, 
	"DCO_CVELIC" VARCHAR2(25)
   ) ;
