CREATE TABLE "LABCONF"."GLCOACAR" 
   (	"ACA_KEYUSU" NUMBER(*,0) NOT NULL ENABLE, 
	"ACA_KEYAPR" VARCHAR2(6) NOT NULL ENABLE, 
	"ACA_KEYPRO" NUMBER(*,0) NOT NULL ENABLE, 
	"ACA_ACTUAL" VARCHAR2(1)
   ) ;
  CREATE UNIQUE INDEX "LABCONF"."PK_GLCOACAR" ON "LABCONF"."GLCOACAR" ("ACA_KEYUSU", "ACA_KEYAPR", "ACA_KEYPRO") 
  ;
ALTER TABLE "LABCONF"."GLCOACAR" ADD CONSTRAINT "PK_GLCOACAR" PRIMARY KEY ("ACA_KEYUSU", "ACA_KEYAPR", "ACA_KEYPRO")
  USING INDEX "LABCONF"."PK_GLCOACAR"  ENABLE;
