CREATE TABLE "LABCONF"."GLCOUSUA" 
   (	"USU_KEYUSU" NUMBER(10,0) NOT NULL ENABLE, 
	"USU_NOMUSU" VARCHAR2(40) NOT NULL ENABLE, 
	"USU_KEYEST" VARCHAR2(3), 
	"USU_KEYDEP" VARCHAR2(16), 
	"USU_FECALT" DATE, 
	"USU_HORALT" VARCHAR2(5), 
	"USU_CVEUSU" VARCHAR2(64), 
	"USU_KEYMEN" VARCHAR2(4), 
	"USU_MASOPC" VARCHAR2(10), 
	"USU_STATUS" VARCHAR2(1), 
	"USU_ACCESO" DATE, 
	"USU_PASSWD" DATE, 
	"USU_FECDUR" NUMBER(10,0), 
	"USU_TIPUSU" VARCHAR2(1), 
	"USU_PERMEN" VARCHAR2(1)
   ) ;
  CREATE UNIQUE INDEX "LABCONF"."GLUSUA01" ON "LABCONF"."GLCOUSUA" ("USU_KEYUSU") 
  ;
ALTER TABLE "LABCONF"."GLCOUSUA" ADD CONSTRAINT "GLUSUA01" UNIQUE ("USU_KEYUSU")
  USING INDEX "LABCONF"."GLUSUA01"  ENABLE;
