CREATE TABLE "LABCONF"."INLOHISC" 
   (	"INH_KEYEMP" NUMBER(5,0), 
	"INH_RFCEMP" VARCHAR2(14), 
	"INH_KEYPRO" NUMBER(5,0), 
	"INH_KEYDEP" VARCHAR2(16), 
	"INH_KEYPUE" VARCHAR2(16), 
	"INH_KEYCUR" VARCHAR2(8), 
	"INH_KEYGPO" VARCHAR2(4), 
	"INH_COSALM" NUMBER(10,2), 
	"INH_EVAALM" NUMBER(5,2), 
	"INH_EVACUR" NUMBER(5,2), 
	"INH_EVAINS" NUMBER(5,2), 
	"INH_CVEAPR" VARCHAR2(6), 
	"INH_TIPASI" VARCHAR2(6)
   ) ;
