CREATE TABLE "LABCONF"."INLOMOEQ" 
   (	"MOE_KEYEQU" VARCHAR2(16), 
	"MOE_FECSOL" DATE, 
	"MOE_KEYDEP" VARCHAR2(16), 
	"MOE_KEYLOC" VARCHAR2(16), 
	"MOE_KEYCEN" VARCHAR2(16), 
	"MOE_OBSPRE" VARCHAR2(60), 
	"MOE_STATUS" VARCHAR2(2), 
	"MOE_FECPRO" DATE, 
	"MOE_FECDEV" DATE, 
	"MOE_EMPREC" NUMBER(5,0), 
	"MOE_EMPRES" NUMBER(5,0), 
	"MOE_OBSDEV" VARCHAR2(60)
   ) ;
