CREATE TABLE "LABCONF"."INLOHOGR" 
   (	"HOG_KEYGPO" NUMBER(5,0), 
	"HOG_KEYCUR" VARCHAR2(8), 
	"HOG_KEYLUG" VARCHAR2(8), 
	"HOG_FECDIA" DATE, 
	"HOG_HORINI" VARCHAR2(5), 
	"HOG_HORFIN" VARCHAR2(5), 
	"HOG_STATUS" VARCHAR2(1), 
	"HOG_FECSTA" DATE
   ) ;
