CREATE TABLE "LABCONF"."NMLOMNEM" 
   (	"MNE_KEYNEM" VARCHAR2(16) NOT NULL ENABLE, 
	"MNE_KEYTAB" VARCHAR2(8), 
	"MNE_KEYCAM" VARCHAR2(16), 
	"MNE_CONDIC" VARCHAR2(16), 
	"MNE_TIPDAT" VARCHAR2(1)
   ) ;
  CREATE UNIQUE INDEX "LABCONF"."NMMNEM01" ON "LABCONF"."NMLOMNEM" ("MNE_KEYNEM") 
  ;
ALTER TABLE "LABCONF"."NMLOMNEM" ADD CONSTRAINT "NMMNEM01" UNIQUE ("MNE_KEYNEM")
  USING INDEX "LABCONF"."NMMNEM01"  ENABLE;
