CREATE TABLE "LABCONF"."NMLOTABN" 
   (	"TAB_KEYTAB" VARCHAR2(9), 
	"TAB_SECTAB" NUMBER(10,0), 
	"TAB_ELEUNO" NUMBER(18,6), 
	"TAB_ELEDOS" NUMBER(18,6), 
	"TAB_ELETRE" NUMBER(18,6), 
	"TAB_ELECUA" NUMBER(18,6)
   ) ;
