CREATE TABLE "LABCONF"."NMLOBEBE" 
   (	"BEB_KEYEMP" NUMBER(10,0), 
	"BEB_KEYBEN" NUMBER(5,0), 
	"BEB_COMFAM" NUMBER(5,0), 
	"BEB_TIPBEN" VARCHAR2(2), 
	"BEB_FECVEN" DATE, 
	"BEB_PORPAR" NUMBER(7,4), 
	"BEB_FORPAG" VARCHAR2(2), 
	"BEB_KEYCON" VARCHAR2(3), 
	"BEB_PERINI" VARCHAR2(7), 
	"BEB_PERFIN" VARCHAR2(7), 
	"BEB_STATUS" VARCHAR2(1), 
	"BEB_IMPFIJ" NUMBER(12,2), 
	"BEB_FECINI" DATE
   ) ;
