CREATE TABLE "LABCONF"."NMLONOMI" 
   (	"NOM_KEYNOM" NUMBER(5,0) NOT NULL ENABLE, 
	"NOM_DESTIP" VARCHAR2(40) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "LABCONF"."NMNOMI01" ON "LABCONF"."NMLONOMI" ("NOM_KEYNOM") 
  ;
ALTER TABLE "LABCONF"."NMLONOMI" ADD CONSTRAINT "NMNOMI01" UNIQUE ("NOM_KEYNOM")
  USING INDEX "LABCONF"."NMNOMI01"  ENABLE;
