CREATE TABLE "LABCONF"."PLLOCONC" 
   (	"CON_KEYCON" VARCHAR2(10), 
	"CON_KEYRUB" VARCHAR2(5), 
	"CON_DESCON" VARCHAR2(40), 
	"CON_NATCON" VARCHAR2(1), 
	"CON_TIPCON" NUMBER(5,0), 
	"CON_MANPER" NUMBER(5,0)
   ) ;
