CREATE TABLE "LABCONF"."PLLOPNCL" 
   (	"PCL_KEYMIN" VARCHAR2(5), 
	"PCL_KEYPNL" VARCHAR2(5), 
	"PCL_KEYHOJ" VARCHAR2(5), 
	"PCL_KEYPCL" VARCHAR2(10), 
	"PCL_DESPCL" VARCHAR2(20), 
	"PCL_ORDEN" NUMBER(10,0), 
	"PCL_ORIGEN" VARCHAR2(1), 
	"PCL_MOMPPT" VARCHAR2(1)
   ) ;
