CREATE TABLE "LABCONF"."SCCOCOMA" 
   (	"COM_KEYPLZ" NUMBER(5,0), 
	"COM_KEYEMP" NUMBER(5,0), 
	"COM_FECMOV" DATE, 
	"COM_TIPMOV" VARCHAR2(2), 
	"COM_KEYUSU" NUMBER(5,0), 
	"COM_FECCAP" DATE, 
	"COM_STATUS" VARCHAR2(2), 
	"COM_SALCON" NUMBER(12,6), 
	"COM_KEYIMS" VARCHAR2(5)
   ) ;
