CREATE TABLE "LABCONF"."TVCAPDES" 
   (	"PDE_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"PDE_RECURP" CHAR(18) NOT NULL ENABLE, 
	"PDE_FECMOV" DATE NOT NULL ENABLE, 
	"PDE_CAPNEW" NUMBER(16,2) NOT NULL ENABLE, 
	"PDE_FECANT" DATE NOT NULL ENABLE, 
	"PDE_CAPANT" NUMBER(16,2) NOT NULL ENABLE, 
	"PDE_STATUS" NUMBER(*,0) NOT NULL ENABLE, 
	"PDE_HORANT" CHAR(10) NOT NULL ENABLE, 
	"PDE_HORMOV" CHAR(10) NOT NULL ENABLE
   ) ;
