CREATE TABLE "LABCONF"."TVLOFAEM" 
   (	"FAE_KEYFAC" VARCHAR2(30) NOT NULL ENABLE, 
	"FAE_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"FAE_KEYPRO" NUMBER(5,0) NOT NULL ENABLE, 
	"FAE_KEYPER" VARCHAR2(7) NOT NULL ENABLE
   ) ;
