CREATE TABLE "LABCONF"."TVPRDETB" 
   (	"DET_KEYUSU" NUMBER(*,0) NOT NULL ENABLE, 
	"DET_FECMOV" DATE NOT NULL ENABLE, 
	"DET_HORMOV" VARCHAR2(8) NOT NULL ENABLE, 
	"DET_KEYTAB" VARCHAR2(18), 
	"DET_KEYCAM" VARCHAR2(18) NOT NULL ENABLE, 
	"DET_VALANT" VARCHAR2(40) NOT NULL ENABLE, 
	"DET_VALACT" VARCHAR2(40) NOT NULL ENABLE
   ) ;
