CREATE TABLE "LABCONF"."WEBITACC" 
   (	"WCC_IDBACC" NUMBER(*,0), 
	"WCC_KEYEMP" NUMBER(*,0) NOT NULL ENABLE, 
	"WCC_PCEMPL" VARCHAR2(20) NOT NULL ENABLE, 
	"WCC_DETALL" VARCHAR2(100) NOT NULL ENABLE, 
	"WCC_FECALT" DATE NOT NULL ENABLE
   ) ;
ALTER TABLE "LABCONF"."WEBITACC" ADD PRIMARY KEY ("WCC_IDBACC")
  USING INDEX  ENABLE;
