CREATE TABLE "LABCONF"."XXPER_SIPROS_NMLODATA" 
   (	"DAT_KEYEMP" VARCHAR2(150) NOT NULL ENABLE, 
	"DAT_KEYPAR" VARCHAR2(2) NOT NULL ENABLE, 
	"DAT_VALPAR" VARCHAR2(100), 
	"ORA_SYSTEM" VARCHAR2(30), 
	"ORA_TRANSACTION" VARCHAR2(30), 
	"ORA_DATE" DATE, 
	"ORA_SECUENCIA" NUMBER, 
	"ORA_STATUS" VARCHAR2(2)
   ) ;
