CREATE TABLE "COFIDI"."XXCOFIDI_PARAMETRO_CT_TAB" 
   (	"ID_PARAMETRO_PK" NUMBER(*,0) NOT NULL ENABLE, 
	"VALOR" VARCHAR2(255) NOT NULL ENABLE, 
	"DES_PARAMETRO" VARCHAR2(255), 
	"ORDEN" NUMBER(2,0)
   ) ;
ALTER TABLE "COFIDI"."XXCOFIDI_PARAMETRO_CT_TAB" ADD CONSTRAINT "XXCOFIDI_PARAMETRO_PK_IDX01" PRIMARY KEY ("ID_PARAMETRO_PK")
  USING INDEX  ENABLE;
