CREATE TABLE "COFIDI"."XXCOFIDI_EMPRESA_CT_TAB" 
   (	"ID_EMPRESA_PK" NUMBER(*,0) NOT NULL ENABLE, 
	"NOM_EMPRESA" VARCHAR2(255) NOT NULL ENABLE, 
	"ID_ESTADO_FK" NUMBER NOT NULL ENABLE, 
	"RFC" VARCHAR2(13) NOT NULL ENABLE, 
	"COD_CIA" VARCHAR2(3)
   ) ;
ALTER TABLE "COFIDI"."XXCOFIDI_EMPRESA_CT_TAB" ADD CONSTRAINT "XXCOFIDI_EMPRESA_PK_IDX01" PRIMARY KEY ("ID_EMPRESA_PK")
  USING INDEX  ENABLE;
ALTER TABLE "COFIDI"."XXCOFIDI_EMPRESA_CT_TAB" ADD CONSTRAINT "XXCOFIDI_EMPRESA_ESTADO_IDX" FOREIGN KEY ("ID_ESTADO_FK")
	  REFERENCES "COFIDI"."XXCOFIDI_ESTADO_CT_TAB" ("ID_ESTADO_PK") ENABLE;
