CREATE TABLE "COFIDI"."XXCOFIDI_CFDI_IMPUESTO_CON_TAB" 
   (	"ID_CFDI_IMPUESTO_CONCEPTO_PK" NUMBER NOT NULL ENABLE, 
	"ID_FACTURA_FK" NUMBER NOT NULL ENABLE, 
	"ID_CFDI_CONCEPTO_FK" NUMBER, 
	"TRASLADO" NUMBER(1,0) NOT NULL ENABLE, 
	"BASE" VARCHAR2(20), 
	"IMPUESTO" VARCHAR2(20) NOT NULL ENABLE, 
	"TIPO_FACTOR" VARCHAR2(20), 
	"TASA_O_CUOTA" VARCHAR2(20), 
	"IMPORTE" VARCHAR2(20)
   ) ;
ALTER TABLE "COFIDI"."XXCOFIDI_CFDI_IMPUESTO_CON_TAB" ADD CONSTRAINT "XXCOFIDI_CFDI_IMPUESTO_CON_PK" PRIMARY KEY ("ID_CFDI_IMPUESTO_CONCEPTO_PK")
  USING INDEX  ENABLE;
ALTER TABLE "COFIDI"."XXCOFIDI_CFDI_IMPUESTO_CON_TAB" ADD CONSTRAINT "XXCOFIDI_IMP_CONCEPT_FK_IDX01" FOREIGN KEY ("ID_CFDI_CONCEPTO_FK")
	  REFERENCES "COFIDI"."XXCOFIDI_CFDI_CONCEPTO_TAB" ("ID_CFDI_CONCEPTO_PK") ENABLE;
ALTER TABLE "COFIDI"."XXCOFIDI_CFDI_IMPUESTO_CON_TAB" ADD CONSTRAINT "XXCOFIDI_IMP_FACTURA_FK_IDX01" FOREIGN KEY ("ID_FACTURA_FK")
	  REFERENCES "COFIDI"."XXCOFIDI_FACTURA_TAB" ("ID_FACTURA_PK") ENABLE;
