CREATE TABLE "COFIDI"."XXCOFIDI_BITACORA_TAB" 
   (	"ID_BITACORA_PK" NUMBER(*,0) NOT NULL ENABLE, 
	"FEC_EVENTO" TIMESTAMP (6), 
	"EVENTO" VARCHAR2(20), 
	"ID_USUARIO_FK" NUMBER(*,0)
   ) ;
ALTER TABLE "COFIDI"."XXCOFIDI_BITACORA_TAB" ADD CONSTRAINT "XXCOFIDI_BITACORA_PK_IDX01" PRIMARY KEY ("ID_BITACORA_PK")
  USING INDEX  ENABLE;
ALTER TABLE "COFIDI"."XXCOFIDI_BITACORA_TAB" ADD CONSTRAINT "XXCOFIDI_BITACORA_USU_FK_IDX01" FOREIGN KEY ("ID_USUARIO_FK")
	  REFERENCES "COFIDI"."XXCOFIDI_USUARIO_TAB" ("ID_USUARIO_PK") ENABLE;
