CREATE TABLE "COFIDI"."XXCOFIDI_CFDI_EMISOR_RECEP_TAB" 
   (	"ID_CFDI_EMISOR_RECEP_PK" NUMBER NOT NULL ENABLE, 
	"ID_FACTURA_FK" NUMBER NOT NULL ENABLE, 
	"EMISOR" NUMBER(1,0) NOT NULL ENABLE, 
	"RFC" VARCHAR2(20), 
	"NOMBRE" VARCHAR2(255), 
	"REGIMEN_FISCAL" VARCHAR2(20), 
	"NUM_REG_ID_TRIB" VARCHAR2(20), 
	"USO_CFDI" VARCHAR2(20), 
	"RESIDENCIA_FISCAL" VARCHAR2(20)
   ) ;
ALTER TABLE "COFIDI"."XXCOFIDI_CFDI_EMISOR_RECEP_TAB" ADD CONSTRAINT "XXCOFIDI_CFDI_EMISOR_RECEP_PK" PRIMARY KEY ("ID_CFDI_EMISOR_RECEP_PK")
  USING INDEX  ENABLE;
ALTER TABLE "COFIDI"."XXCOFIDI_CFDI_EMISOR_RECEP_TAB" ADD CONSTRAINT "XXCOFIDI_CFDI_EMI_RE_FK_IDX01" FOREIGN KEY ("ID_FACTURA_FK")
	  REFERENCES "COFIDI"."XXCOFIDI_FACTURA_TAB" ("ID_FACTURA_PK") ENABLE;
