CREATE TABLE "COFIDI"."XXCOFIDI_SERIES_EMPRESA_TAB" 
   (	"ID_SERIES_EMPRESA_PK" NUMBER NOT NULL ENABLE, 
	"ID_SERIE_FK" NUMBER NOT NULL ENABLE, 
	"ID_EMPRESA_FK" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "COFIDI"."XXCOFIDI_SERIES_EMPRESA_TAB" ADD CONSTRAINT "XXCOFIDI_SERIES_EMP_PK_IDX01" PRIMARY KEY ("ID_SERIES_EMPRESA_PK")
  USING INDEX  ENABLE;
ALTER TABLE "COFIDI"."XXCOFIDI_SERIES_EMPRESA_TAB" ADD CONSTRAINT "XXCOFIDI_SER_EMP1_EMP2_TAB_IDX" FOREIGN KEY ("ID_EMPRESA_FK")
	  REFERENCES "COFIDI"."XXCOFIDI_EMPRESA_CT_TAB" ("ID_EMPRESA_PK") ENABLE;
ALTER TABLE "COFIDI"."XXCOFIDI_SERIES_EMPRESA_TAB" ADD CONSTRAINT "XXCOFIDI_SER_EMP_SERIE_TAB_IDX" FOREIGN KEY ("ID_SERIE_FK")
	  REFERENCES "COFIDI"."XXCOFIDI_SERIE_CT_TAB" ("ID_SERIE_PK") ENABLE;
