CREATE TABLE "COFIDI"."XXCOFIDI_CFDI_PAGO_TAB" 
   (	"ID_CFDI_PAGO_PK" NUMBER NOT NULL ENABLE, 
	"UUID" VARCHAR2(40), 
	"IMPORTE_PAGADO" VARCHAR2(20), 
	"IMPORTE_SALDO_ANT" VARCHAR2(20), 
	"IMPORTE_SALDO_INSOLUTO" VARCHAR2(20), 
	"MONEDA_DR" VARCHAR2(20), 
	"NUM_PARCIALIDAD" VARCHAR2(20), 
	"TIPO_CAMBIO_DR" VARCHAR2(20), 
	"METODO_PAGO_DR" VARCHAR2(20), 
	"ID_FACTURA_FK" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "COFIDI"."XXCOFIDI_CFDI_PAGO_TAB" ADD CONSTRAINT "XXCOFIDI_CFDI_PAGO_PK" PRIMARY KEY ("ID_CFDI_PAGO_PK")
  USING INDEX  ENABLE;
ALTER TABLE "COFIDI"."XXCOFIDI_CFDI_PAGO_TAB" ADD CONSTRAINT "XXCOFIDI_CFDI_PAGO_FK_IDX01" FOREIGN KEY ("ID_FACTURA_FK")
	  REFERENCES "COFIDI"."XXCOFIDI_FACTURA_TAB" ("ID_FACTURA_PK") ENABLE;
