CREATE TABLE "COFIDI"."XXCOFIDI_DOCUMENTO_TAB" 
   (	"ID_DOCUMENTO_PK" NUMBER(*,0) NOT NULL ENABLE, 
	"TIPO_ARCHIVO" VARCHAR2(3) NOT NULL ENABLE, 
	"NOM_ARCHIVO" VARCHAR2(150), 
	"ARCHIVO" BLOB NOT NULL ENABLE
   ) ;
ALTER TABLE "COFIDI"."XXCOFIDI_DOCUMENTO_TAB" ADD CONSTRAINT "XXCOFIDI_DOCUMENTO_PK_IDX01" PRIMARY KEY ("ID_DOCUMENTO_PK")
  USING INDEX  ENABLE;
