CREATE TABLE "COFIDI"."XXCOFIDI_EMPRESA_SERIE_USU_TAB" 
   (	"ID_EMPRESA_SERIE_USU_PK" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_USUARIO_FK" NUMBER NOT NULL ENABLE, 
	"ID_EMPRESA_FK" NUMBER NOT NULL ENABLE, 
	"ID_SERIE_FK" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "COFIDI"."XXCOFIDI_EMPRESA_SERIE_USU_TAB" ADD CONSTRAINT "XXCOFIDI_EMP_SER_USU_PK_IDX01" PRIMARY KEY ("ID_EMPRESA_SERIE_USU_PK")
  USING INDEX  ENABLE;
ALTER TABLE "COFIDI"."XXCOFIDI_EMPRESA_SERIE_USU_TAB" ADD CONSTRAINT "XXCOFIDI_EMPSERUSU_SER2_IDX01" FOREIGN KEY ("ID_SERIE_FK")
	  REFERENCES "COFIDI"."XXCOFIDI_SERIE_CT_TAB" ("ID_SERIE_PK") ENABLE;
ALTER TABLE "COFIDI"."XXCOFIDI_EMPRESA_SERIE_USU_TAB" ADD CONSTRAINT "XXCOFIDI_EMPSERUSU_USU2_IDX01" FOREIGN KEY ("ID_USUARIO_FK")
	  REFERENCES "COFIDI"."XXCOFIDI_USUARIO_TAB" ("ID_USUARIO_PK") ENABLE;
ALTER TABLE "COFIDI"."XXCOFIDI_EMPRESA_SERIE_USU_TAB" ADD CONSTRAINT "XXCOFIDI_EMPSERUSU_EMP2_IDX01" FOREIGN KEY ("ID_EMPRESA_FK")
	  REFERENCES "COFIDI"."XXCOFIDI_EMPRESA_CT_TAB" ("ID_EMPRESA_PK") ENABLE;
