CREATE TABLE "COFIDI"."XXCOFIDI_ORIGEN_CT_TAB" 
   (	"ID_ORIGEN_PK" NUMBER(*,0) NOT NULL ENABLE, 
	"ORIGEN" VARCHAR2(255) NOT NULL ENABLE, 
	"TIPO" NUMBER(1,0) DEFAULT 0, 
	"ID_ESTADO_FK" NUMBER, 
	"PROCESAR_SOLO_XML" NUMBER(1,0) NOT NULL ENABLE, 
	"FOLIO_NUMERICO" NUMBER(1,0) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(150) NOT NULL ENABLE
   ) ;
ALTER TABLE "COFIDI"."XXCOFIDI_ORIGEN_CT_TAB" ADD CONSTRAINT "XXCOFIDI_ORIGEN_PK_IDX01" PRIMARY KEY ("ID_ORIGEN_PK")
  USING INDEX  ENABLE;
ALTER TABLE "COFIDI"."XXCOFIDI_ORIGEN_CT_TAB" ADD CONSTRAINT "XXCOFIDI_ORIGEN_ESTADO_IDX" FOREIGN KEY ("ID_ESTADO_FK")
	  REFERENCES "COFIDI"."XXCOFIDI_ESTADO_CT_TAB" ("ID_ESTADO_PK") ENABLE;
