CREATE TABLE "COFIDI"."XXCOFIDI_ROL_CT_TAB" 
   (	"ID_ROL_PK" NUMBER(*,0) NOT NULL ENABLE, 
	"ROL" VARCHAR2(50) NOT NULL ENABLE
   ) ;
ALTER TABLE "COFIDI"."XXCOFIDI_ROL_CT_TAB" ADD CONSTRAINT "XXCOFIDI_ROL_PK_IDX01" PRIMARY KEY ("ID_ROL_PK")
  USING INDEX  ENABLE;
