CREATE TABLE "COFIDI"."XXCOFIDI_FACTURA_TAB" 
   (	"ID_FACTURA_PK" NUMBER(*,0) NOT NULL ENABLE, 
	"CLIENTE_TRANSACCIONAL" VARCHAR2(100), 
	"FEC_TIMBRADO" TIMESTAMP (6), 
	"FOLIO" NUMBER(38,0), 
	"NOM_EMISOR" VARCHAR2(255), 
	"NOM_RECEPTOR" VARCHAR2(255), 
	"RFC_EMISOR" VARCHAR2(13), 
	"RFC_RECEPTOR" VARCHAR2(13), 
	"SERIE" VARCHAR2(50), 
	"UUID" VARCHAR2(50), 
	"ID_DOCUMENTO_PDF_FK" NUMBER(*,0), 
	"ID_DOCUMENTO_XML_FK" NUMBER(*,0), 
	"ID_ESTADO_FK" NUMBER NOT NULL ENABLE, 
	"FEC_EMISION" TIMESTAMP (6), 
	"TIPO_COMPROBANTE" VARCHAR2(20) NOT NULL ENABLE, 
	"VAL_SUBTOTAL" VARCHAR2(20), 
	"VAL_IMPUESTO" VARCHAR2(20), 
	"VAL_TOTAL" VARCHAR2(20), 
	"PAC" VARCHAR2(10), 
	"ORIGEN" VARCHAR2(50), 
	"FOLIO_ALFANUMERICO" VARCHAR2(50), 
	"CVE_EXPORTACION" VARCHAR2(10), 
	"CVE_PERIODICIDAD" VARCHAR2(10), 
	"CVE_MESES" VARCHAR2(10), 
	"CVE_ANIO" NUMBER, 
	"CVE_BASE" VARCHAR2(10), 
	"COD_DOM_FISCAL_R" VARCHAR2(20), 
	"COD_REG_FISCAL_R" VARCHAR2(20), 
	"COD_RFC_A_TERCEROS" VARCHAR2(20), 
	"CVE_NOM_ACUENT_ATERC" VARCHAR2(256), 
	"COD_REG_FIS_ATERC" VARCHAR2(20), 
	"COD_DOM_FISCAL_ATERC" VARCHAR2(20)
   ) ;
ALTER TABLE "COFIDI"."XXCOFIDI_FACTURA_TAB" ADD CONSTRAINT "XXCOFIDI_FACTURA_PK_IDX01" PRIMARY KEY ("ID_FACTURA_PK")
  USING INDEX  ENABLE;
ALTER TABLE "COFIDI"."XXCOFIDI_FACTURA_TAB" ADD CONSTRAINT "XXCOFIDI_FACTURA_ESTADO_IDX" FOREIGN KEY ("ID_ESTADO_FK")
	  REFERENCES "COFIDI"."XXCOFIDI_ESTADO_CT_TAB" ("ID_ESTADO_PK") ENABLE;
ALTER TABLE "COFIDI"."XXCOFIDI_FACTURA_TAB" ADD CONSTRAINT "XXCOFIDI_FAC_DOC_PDF_FK_IDX01" FOREIGN KEY ("ID_DOCUMENTO_PDF_FK")
	  REFERENCES "COFIDI"."XXCOFIDI_DOCUMENTO_TAB" ("ID_DOCUMENTO_PK") ENABLE;
ALTER TABLE "COFIDI"."XXCOFIDI_FACTURA_TAB" ADD CONSTRAINT "XXCOFIDI_FAC_DOC_XML_FK_IDX01" FOREIGN KEY ("ID_DOCUMENTO_XML_FK")
	  REFERENCES "COFIDI"."XXCOFIDI_DOCUMENTO_TAB" ("ID_DOCUMENTO_PK") ENABLE;
