CREATE TABLE "COFIDI"."XXCOFIDI_USUARIO_CORREO_TAB" 
   (	"ID_USUARIO_CORREO_PK" NUMBER NOT NULL ENABLE, 
	"NOM_USUARIO_CORREO" VARCHAR2(50) NOT NULL ENABLE, 
	"CVE_USUARIO_CORREO" VARCHAR2(50) NOT NULL ENABLE, 
	"HOST" VARCHAR2(100) NOT NULL ENABLE, 
	"PUERTO" VARCHAR2(10) NOT NULL ENABLE, 
	"AUTENTICACION" VARCHAR2(10) NOT NULL ENABLE, 
	"REMITENTE" VARCHAR2(100) NOT NULL ENABLE, 
	"REMITENTE_NO_ENVIAR" VARCHAR2(100)
   ) ;
ALTER TABLE "COFIDI"."XXCOFIDI_USUARIO_CORREO_TAB" ADD CONSTRAINT "XXCOFIDI_USUARIO_CORR_PK_IDX01" PRIMARY KEY ("ID_USUARIO_CORREO_PK")
  USING INDEX  ENABLE;
