CREATE OR REPLACE EDITIONABLE PACKAGE "FECXC"."FECXP_CARATULA_PKG" 
AS
PROCEDURE REALES;
PROCEDURE FORECAST;
PROCEDURE PRESUPUESTO;
PROCEDURE CARGA_CARATULA
(
v_CALCULAR_REALES IN NUMBER,
v_CALCULAR_FORECAST IN NUMBER,
v_CALCULAR_PRESUPUESTO IN NUMBER,
v_DEBUG       IN VARCHAR2 DEFAULT 'N'
);
END FECXP_CARATULA_PKG;
/
CREATE OR REPLACE EDITIONABLE PACKAGE BODY "FECXC"."FECXP_CARATULA_PKG" 
AS
PROCEDURE REALES
IS
V_PERIODO INT:= TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'));
	V_MES	INT:= 1;
	V_MES_SALDO INT;
	V_ID_SESION VARCHAR(25) := TO_CHAR(SYSDATE,'DD-MM-YYYY');
	V_FEC_ANT DATE;
	V_FIN INT;
	V_MES_ACT INT := TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));
	V_CLA_FE_ID FECXP_POLITICAS_ERP.CLA_FE_ID%TYPE;
	V_POLITICA_ERP_ID FECXP_POLITICAS_ERP.POLITICA_ERP_ID%TYPE;
	V_PRIORIDAD FECXP_POLITICAS_ERP.PRIORIDAD%TYPE;
	V_ORA_S1_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_INI%TYPE;
	V_ORA_S1_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_FIN%TYPE;
	V_ORA_S2_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_INI%TYPE;
	V_ORA_S2_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_FIN%TYPE;
	V_ORA_S3_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_INI%TYPE;
	V_ORA_S3_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_FIN%TYPE;
	V_ORA_S4_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_INI%TYPE;
	V_ORA_S4_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_FIN%TYPE;
	V_ORA_S5_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_INI%TYPE;
	V_ORA_S5_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_FIN%TYPE;
	V_ORA_S6_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_INI%TYPE;
	V_ORA_S6_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_FIN%TYPE;
	V_ORA_S7_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_INI%TYPE;
	V_ORA_S7_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_FIN%TYPE;
	V_POLITICA_SOIN_ID FECXP_POLITICAS_SOIN.POLITICA_SOIN_ID%TYPE;
	V_E_CODIGO_INI FECXP_POLITICAS_SOIN.E_CODIGO_INI%TYPE;
	V_E_CODIGO_FIN FECXP_POLITICAS_SOIN.E_CODIGO_FIN%TYPE;
	V_CTAM01_INI FECXP_POLITICAS_SOIN.CTAM01_INI%TYPE;
	V_CTAM01_FIN FECXP_POLITICAS_SOIN.CTAM01_FIN%TYPE;
	V_CTAM02_INI FECXP_POLITICAS_SOIN.CTAM02_INI%TYPE;
	V_CTAM02_FIN FECXP_POLITICAS_SOIN.CTAM02_FIN%TYPE;
	V_CTAM03_INI FECXP_POLITICAS_SOIN.CTAM03_INI%TYPE;
	V_CTAM03_FIN FECXP_POLITICAS_SOIN.CTAM03_FIN%TYPE;
	V_TIPO_INI FECXP_POLITICAS_SOIN.TIPO_INI%TYPE;
	V_TIPO_FIN FECXP_POLITICAS_SOIN.TIPO_FIN%TYPE;
	V_DIVISION_INI FECXP_POLITICAS_SOIN.DIVISION_INI%TYPE;
	V_DIVISION_FIN FECXP_POLITICAS_SOIN.DIVISION_FIN%TYPE;
	V_RUBRO_INI FECXP_POLITICAS_SOIN.RUBRO_INI%TYPE;
	V_RUBRO_FIN FECXP_POLITICAS_SOIN.RUBRO_FIN%TYPE;
	V_CTACR1_INI FECXP_POLITICAS_SOIN.CTACR1_INI%TYPE;
	V_CTACR1_FIN FECXP_POLITICAS_SOIN.CTACR1_FIN%TYPE;
	V_CTACR2_INI FECXP_POLITICAS_SOIN.CTACR2_INI%TYPE;
	V_CTACR2_FIN FECXP_POLITICAS_SOIN.CTACR2_FIN%TYPE;
	v_errores INTEGER;
	CURSOR CURSOR_CLASIFICACION_FE_ORACLE IS
	SELECT	 CLA_FE_ID, POLITICA_ERP_ID, PRIORIDAD, ORACLE_SEGMENTO1_INI, ORACLE_SEGMENTO1_FIN, ORACLE_SEGMENTO2_INI, ORACLE_SEGMENTO2_FIN, ORACLE_SEGMENTO3_INI, ORACLE_SEGMENTO3_FIN, ORACLE_SEGMENTO4_INI, ORACLE_SEGMENTO4_FIN, ORACLE_SEGMENTO5_INI, ORACLE_SEGMENTO5_FIN, ORACLE_SEGMENTO6_INI, ORACLE_SEGMENTO6_FIN, ORACLE_SEGMENTO7_INI, ORACLE_SEGMENTO7_FIN
	FROM	 FECXP_POLITICAS_ERP
	ORDER BY PRIORIDAD ASC;
	CURSOR CURSOR_CLASIFICACION_FE_SOIN IS
	SELECT	 CLA_FE_ID, POLITICA_SOIN_ID, PRIORIDAD, E_CODIGO_INI, E_CODIGO_FIN, CTAM01_INI, CTAM01_FIN, CTAM02_INI, CTAM02_FIN, CTAM03_INI, CTAM03_FIN, TIPO_INI, TIPO_FIN, DIVISION_INI, DIVISION_FIN, RUBRO_INI, RUBRO_FIN, CTACR1_INI, CTACR1_FIN, CTACR2_INI, CTACR2_FIN
	FROM	 FECXP_POLITICAS_SOIN
	ORDER BY PRIORIDAD ASC;
BEGIN
	BEGIN
		DELETE	FECXP_REAL_CARATULA;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
		--== CARGAMOS LAS CUENTAS CONTABLES QUE GENERARON MOVIMIENTO DURANTE EL MES  ==--
		INSERT	INTO FECXP_CUENTAS_ERP_CARATULA
				(CLA_FE_ID, E_CODIGO, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7)
		SELECT DISTINCT '|'AS CLA_ID, D.E_CODIGO, D.ORACLE_SEGMENTO1, D.ORACLE_SEGMENTO2, D.ORACLE_SEGMENTO3, D.ORACLE_SEGMENTO4, D.ORACLE_SEGMENTO5, D.ORACLE_SEGMENTO6, D.ORACLE_SEGMENTO7
		FROM	FECXP_ENC_PAGOS_ERP E,
				FECXP_DET_PAGOS_PROCESADOS D
		WHERE	TO_NUMBER (TO_CHAR (E.FECHA_APLICACION, 'YYYY')) = V_PERIODO
		AND		TO_NUMBER (TO_CHAR (E.FECHA_APLICACION, 'MM')) < V_MES_ACT
		AND		E.SECUENCIA_PAGOS_ERP = D.SECUENCIA_PAGOS_ERP;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
		INSERT	INTO FECXP_CTAS_SOIN_CARATULA_TMP
		(CLA_FE_ID, E_CODIGO, CTAM01, CTAM02, CTAM03, DIVISION, RUBRO, CTACR1, CTACR2)
		SELECT	DISTINCT '|' AS CLA_ID, E.E_CODIGO, D.CTAM01, D.CTAM02, D.CTAM03, 0, 0, '0', '0'
		FROM	FECXP_ENC_PAGOS_SOIN E,
		FECXP_DET_PAGOS_SOIN D
		WHERE   TO_NUMBER (TO_CHAR (E.FECHA_APLICACION, 'YYYY')) =V_PERIODO
		AND		TO_NUMBER (TO_CHAR (E.FECHA_APLICACION, 'MM')) < V_MES_ACT
		AND		E.SECUENCIA_PAGOS_SOIN = D.SECUENCIA_PAGOS_SOIN;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
		UPDATE	FECXP_CTAS_SOIN_CARATULA_TMP C1
		SET		DIVISION = 	(
						SELECT	DISTINCT C2.CG13DI
						FROM	FECXP_CAT_CUENTAS_SOIN C2
						WHERE   C1.CTAM01 = C2.CTAM01
						AND		C1.CTAM02 = C2.CTAM02
						AND		C1.CTAM03 = C2.CTAM03
						),
			RUBRO = (
						SELECT	DISTINCT C2.CG13RU
						FROM	FECXP_CAT_CUENTAS_SOIN C2
						WHERE   C1.CTAM01 = C2.CTAM01
						AND		C1.CTAM02 = C2.CTAM02
						AND		C1.CTAM03 = C2.CTAM03
						)
		WHERE	EXISTS (
			 	SELECT	C2.CG13RU
				FROM	FECXP_CAT_CUENTAS_SOIN C2
				WHERE   C1.CTAM01 = C2.CTAM01
				AND		C1.CTAM02 = C2.CTAM02
				AND		C1.CTAM03 = C2.CTAM03
				);
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	--==  CLASIFICACION DE CUENTAS SESGUN POLITICAS DE CLASIFICACION DE FE ==--
	OPEN  CURSOR_CLASIFICACION_FE_ORACLE;
	LOOP
		FETCH CURSOR_CLASIFICACION_FE_ORACLE
		INTO  V_CLA_FE_ID, V_PRIORIDAD, V_POLITICA_ERP_ID, V_ORA_S1_INI, V_ORA_S1_FIN, V_ORA_S2_INI, V_ORA_S2_FIN, V_ORA_S3_INI, V_ORA_S3_FIN, V_ORA_S4_INI, V_ORA_S4_FIN, V_ORA_S5_INI, V_ORA_S5_FIN, V_ORA_S6_INI, V_ORA_S6_FIN, V_ORA_S7_INI, V_ORA_S7_FIN;
        EXIT WHEN CURSOR_CLASIFICACION_FE_ORACLE%NOTFOUND;
		BEGIN
				  		--== CLASIFICACION DE CUENTAS CONTABLES ERP ==--
				UPDATE	FECXP_CUENTAS_ERP_CARATULA
				SET		CLA_FE_ID = V_CLA_FE_ID
				WHERE	(ORACLE_SEGMENTO1 >= NVL (V_ORA_S1_INI, '0'))
				AND		(ORACLE_SEGMENTO1 <= NVL (V_ORA_S1_FIN, 'z'))
				AND		(ORACLE_SEGMENTO2 >= NVL (V_ORA_S2_INI, '0'))
				AND		(ORACLE_SEGMENTO2 <= NVL (V_ORA_S2_FIN, 'z'))
				AND		(ORACLE_SEGMENTO3 >= NVL (V_ORA_S3_INI, '0'))
				AND		(ORACLE_SEGMENTO3 <= NVL (V_ORA_S3_FIN, 'z'))
				AND		(ORACLE_SEGMENTO4 >= NVL (V_ORA_S4_INI, '0'))
				AND		(ORACLE_SEGMENTO4 <= NVL (V_ORA_S4_FIN, 'z'))
				AND		(ORACLE_SEGMENTO5 >= NVL (V_ORA_S5_INI, '0'))
				AND		(ORACLE_SEGMENTO5 <= NVL (V_ORA_S5_FIN, 'z'))
				AND		(ORACLE_SEGMENTO6 >= NVL (V_ORA_S6_INI, '0'))
				AND		(ORACLE_SEGMENTO6 <= NVL (V_ORA_S6_FIN, 'z'))
				AND		(ORACLE_SEGMENTO7 >= NVL (V_ORA_S7_INI, '0'))
				AND		(ORACLE_SEGMENTO7 <= NVL (V_ORA_S7_FIN, 'z'))
				AND		NVL (CLA_FE_ID, '|') = '|';
				EXCEPTION
				WHEN NO_DATA_FOUND THEN
					 v_errores :=1;
	 	END;
	END LOOP;
	CLOSE CURSOR_CLASIFICACION_FE_ORACLE;
	--== CLASIFICACION FLUJO DE EFECTIVO PARA SOIN ==--
	OPEN  CURSOR_CLASIFICACION_FE_SOIN;
	LOOP
		FETCH CURSOR_CLASIFICACION_FE_SOIN
		INTO  V_CLA_FE_ID, V_POLITICA_SOIN_ID, V_PRIORIDAD, V_E_CODIGO_INI, V_E_CODIGO_FIN, V_CTAM01_INI, V_CTAM01_FIN, V_CTAM02_INI, V_CTAM02_FIN, V_CTAM03_INI, V_CTAM03_FIN, V_TIPO_INI, V_TIPO_FIN, V_DIVISION_INI, V_DIVISION_FIN, V_RUBRO_INI, V_RUBRO_FIN, V_CTACR1_INI, V_CTACR1_FIN, V_CTACR2_INI, V_CTACR2_FIN;
        EXIT WHEN CURSOR_CLASIFICACION_FE_SOIN%NOTFOUND;
		BEGIN
						--== SE CLASIFICAN LAS CUENTAS DE SOIN ==--
				UPDATE	FECXP_CTAS_SOIN_CARATULA_TMP
				SET		CLA_FE_ID = V_CLA_FE_ID
				WHERE	(E_CODIGO >= NVL (V_E_CODIGO_INI, 0))
				AND		(E_CODIGO <= NVL (V_E_CODIGO_FIN, 9999))
				AND		(CTAM01 >= NVL (V_CTAM01_INI, '0'))
				AND		(CTAM01 <= NVL (V_CTAM01_FIN, 'z'))
				AND		(CTAM02 >= NVL (V_CTAM02_INI, '0'))
				AND		(CTAM02 <= NVL (V_CTAM02_FIN, 'z'))
				AND		(CTAM03 >= NVL (V_CTAM03_INI, '0'))
				AND		(CTAM03 <= NVL (V_CTAM03_FIN, 'z'))
				AND		(NVL (DIVISION, 0) >= NVL (V_DIVISION_INI, 0))
				AND		(NVL (DIVISION, 0) <= NVL (V_DIVISION_FIN, 9999))
				AND		(NVL (RUBRO, 0) >= NVL (V_RUBRO_INI, 0))
				AND		(NVL (RUBRO, 0) <= NVL (V_RUBRO_FIN, 9999))
				AND		(CTACR1 >= NVL (V_CTACR1_INI, '000'))
				AND		(CTACR1 <= NVL (V_CTACR1_FIN, 'zzz'))
				AND		(CTACR2 >= NVL (V_CTACR2_INI, '0000'))
				AND		(CTACR2 <= NVL (V_CTACR2_FIN, 'zzzz'))
				AND		NVL (CLA_FE_ID, '|') = '|';
				EXCEPTION
						WHEN NO_DATA_FOUND THEN
						v_errores :=1;
		END;
	END LOOP;
	CLOSE CURSOR_CLASIFICACION_FE_SOIN;
/******************************************************************************************************/
	BEGIN
		--== INSERTA INGRESOS COBRANZA E ICIA ==--
		INSERT	INTO FECXP_REAL_CARATULA (E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
		SELECT	I.NO_EMPRESA, I.DES_EMPRESA, V_ID_SESION, I.PERIODO, I.MES, I.MONEDA, I.TIPO_CAMBIO, I.CLA_FE_ID, CF.CLA_FE_DES, I.IMPORTE_LINEA
		FROM	FECXP_CLASIFICACION_FE CF,
				(
				SELECT	A.NO_EMPRESA,
					C.DES_EMPRESA,
					TO_NUMBER (TO_CHAR (A.FEC_VALOR, 'YYYY')) AS PERIODO,
					TO_NUMBER (TO_CHAR (A.FEC_VALOR, 'MM')) AS MES,
					M.MON_ORACLE MONEDA,
					M.TIPO_CAMBIO,
					CASE WHEN B.COD_VALOR IS NULL THEN
						CASE WHEN ID_TIPO_OPERACION_SET = 3100 THEN 'A7'
							 WHEN ID_TIPO_OPERACION_SET = 3101 AND A.ID_BANCO <> 14  AND ID_CHEQUERA <> '51451001688' THEN 'B1'
		  					 WHEN ID_TIPO_OPERACION_SET = 3102 THEN 'A7'
		   					 WHEN ID_TIPO_OPERACION_SET = 3103 THEN 'B1'
		   					 WHEN ID_TIPO_OPERACION_SET = 3107 THEN 'A7'
		   					 WHEN ID_TIPO_OPERACION_SET = 3109 THEN 'A7'
							 WHEN ID_TIPO_OPERACION_SET = 3111 THEN 'B1'
							 WHEN ID_TIPO_OPERACION_SET = 3500 THEN 'B1'
							 WHEN ID_TIPO_OPERACION_SET = 3706 THEN 'ING02' --INTEREMPRESAS
							 WHEN ID_TIPO_OPERACION_SET = 4102 THEN 'ING02' --INTEREMPRESAS
							 WHEN ID_TIPO_OPERACION_SET = 3112 THEN 'B1'
						 ELSE 'ING01' END
					ELSE B.COD_VALOR END CLA_FE_ID,
					SUM(CASE WHEN B.IMPORTE_DETALLE IS NULL THEN A.IMPORTE ELSE B.IMPORTE_DETALLE END) IMPORTE_LINEA
			FROM	FECXC_DEP_ESPECIALES A, FECXP_MONEDAS M,	(SELECT BASE_INF.CODFOLIO, BASE_INF.E_CODIGO, BASE_INF.SEGMENTO1, BASE_INF.CODOPERACION, BASE_INF.TIPOCAMBIO, BASE_INF.IMPORTE, BASE_INF.IMPORTE_DETALLE,
																					BASE_INF.F_DEPOSITO,  BASE_INF.SEGMENTO2, BASE_INF.COD_SEC_DET,
																					BASE_INF.COD_SEC_CATCLAS, BASE_INF.SECMONEDA,
																					COD_FLUJO.COD_VALOR, COD_FLUJO.DESC_VALOR
											FROM (SELECT	A.CODFOLIO, A.E_CODIGO, B.SEGMENTO1, A.CODOPERACION, A.TIPOCAMBIO, A.IMPORTE, B.IMPORTE AS IMPORTE_DETALLE,
																					A.F_DEPOSITO,  NVL (B.SEGMENTO2, -1) AS SEGMENTO2, B.COD_SEC_DET,
																					B.COD_SEC_CATCLAS, A.SECMONEDA
																			FROM	FECXC_ENC_CLASIFICADOS A,
																					FECXC_DET_CLASIFICADOS B,
																					FECXC_DET_CLASFECXC I
																			WHERE	A.E_CODIGO = B.E_CODIGO
																			AND		A.COD_SEC_CLASIFICA = B.COD_SEC_CLASIFICA
																			AND		B.COD_SEC_DET = I.COD_SEC_DET
																			AND		B.COD_SEC_CATCLAS = I.COD_SEC_CATCLAS
																			--AND		I.EXCLUIR_ENREPORTES = 'NO'
																			AND		B.SEGMENTO1 IS NOT NULL) BASE_INF,
																			(SELECT	G1.COD_SEC_LIN, G1.SEC_FLUJO_DETCAT, H1.COD_VALOR,
																					H1.DESC_VALOR
																			FROM	FECXC_MAPEO_FLUJO G1, FECXC_DET_CATALOGOS H1
																			WHERE	G1.SEC_FLUJO_DETCAT = H1.COD_SEC_LIN
																			AND		H1.TIPO_CAT = 'FLUJO'
																			UNION
																			SELECT	-1, -1, 'NO MAPEADOS', 'NO MAPEADOS'
																			FROM	DUAL)  COD_FLUJO
											WHERE BASE_INF.SEGMENTO2 = COD_FLUJO.COD_SEC_LIN(+)) B,
							FECXC_EMPRESAS C
			WHERE A.NO_EMPRESA = B.E_CODIGO (+)
				  AND A.NO_FOLIO_DET = B.CODFOLIO 	(+)
				  AND	TO_NUMBER (TO_CHAR (A.FEC_VALOR, 'YYYY')) = V_PERIODO
				  AND 	TO_NUMBER (TO_CHAR (A.FEC_VALOR, 'MM'))  < V_MES_ACT
				  AND 	A.NO_EMPRESA = C.E_CODIGO
				  AND	M.MON_SET = A.ID_DIVISA
				  AND	TO_NUMBER (TO_CHAR (A.FEC_VALOR, 'MM')) = M.MES
		  GROUP BY A.NO_EMPRESA,
					C.DES_EMPRESA,
					TO_NUMBER (TO_CHAR (A.FEC_VALOR, 'YYYY')),
					TO_NUMBER (TO_CHAR (A.FEC_VALOR, 'MM')),
					M.MON_ORACLE,
					M.TIPO_CAMBIO,
					CASE WHEN B.COD_VALOR IS NULL THEN
						CASE WHEN ID_TIPO_OPERACION_SET = 3100 THEN 'A7'
							 WHEN ID_TIPO_OPERACION_SET = 3101 AND A.ID_BANCO <> 14  AND ID_CHEQUERA <> '51451001688' THEN 'B1'
		  					 WHEN ID_TIPO_OPERACION_SET = 3102 THEN 'A7'
		   					 WHEN ID_TIPO_OPERACION_SET = 3103 THEN 'B1'
		   					 WHEN ID_TIPO_OPERACION_SET = 3107 THEN 'A7'
		   					 WHEN ID_TIPO_OPERACION_SET = 3109 THEN 'A7'
							 WHEN ID_TIPO_OPERACION_SET = 3111 THEN 'B1'
							 WHEN ID_TIPO_OPERACION_SET = 3500 THEN 'B1'
							 WHEN ID_TIPO_OPERACION_SET = 3706 THEN 'ING02' --INTEREMPRESAS
							 WHEN ID_TIPO_OPERACION_SET = 4102 THEN 'ING02' --INTEREMPRESAS
							 WHEN ID_TIPO_OPERACION_SET = 3112 THEN 'B1'
						 ELSE 'ING01' END
					ELSE B.COD_VALOR END,
					CASE WHEN B.DESC_VALOR IS NULL THEN 'INGRESOS' ELSE B.DESC_VALOR END) I
			WHERE	I.CLA_FE_ID = CF.CLA_FE_ID;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
			/*  INICIA LA INCLUSION DE INFORMACION DEL ERP*/
		INSERT INTO FECXP_ERP_CARATULA_TMP
		SELECT	PE.E_CODIGO, E.DES_EMPRESA, (TO_CHAR(PE.FECHA_APLICACION,'YYYY')) AS PERIODO, (TO_CHAR(PE.FECHA_APLICACION,'MM')) AS MES,
				M.MON_ORACLE, M.TIPO_CAMBIO,  (PP.IMPORTE_LINEA) IMPORTE, PP.ORACLE_SEGMENTO1, PP.ORACLE_SEGMENTO2, PP.ORACLE_SEGMENTO3,
				PP.ORACLE_SEGMENTO4, PP.ORACLE_SEGMENTO5, PP.ORACLE_SEGMENTO6, PP.ORACLE_SEGMENTO7
		FROM	FECXP_ENC_PAGOS_ERP PE,
				FECXP_DET_PAGOS_PROCESADOS PP,
				FECXC_EMPRESAS E,
				FECXP_MONEDAS M
		WHERE  	TO_NUMBER (TO_CHAR (PE.FECHA_APLICACION, 'YYYY')) = V_PERIODO
		AND		TO_NUMBER (TO_CHAR (PE.FECHA_APLICACION, 'MM')) <  V_MES_ACT
		AND		M.MES = TO_NUMBER(TO_CHAR(PE.FECHA_APLICACION,'MM'))
		AND		M.MON_SET = PE.MONEDA
		AND		E.E_CODIGO = PE.E_CODIGO
		AND		PE.SECUENCIA_PAGOS_ERP = PP.SECUENCIA_PAGOS_ERP
		AND		PE.E_CODIGO 	   = PP.E_CODIGO;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
		INSERT	INTO FECXP_REAL_CARATULA (E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO,
				 					  CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
		SELECT	A.E_CODIGO, A.DES_EMPRESA,  V_ID_SESION, A.PERIODO, A.MES,
			A.MON_ORACLE, A.TIPO_CAMBIO, B.CLA_FE_ID, B.CLA_FE_DES, SUM (A.IMPORTE * TO_NUMBER (B.CLA_ATRIBUTO3))
		FROM FECXP_ERP_CARATULA_TMP A, (SELECT C.E_CODIGO, B.CLA_FE_ID, B.CLA_FE_DES, B.CLA_ATRIBUTO3 , C.ORACLE_SEGMENTO1, C.ORACLE_SEGMENTO2, C.ORACLE_SEGMENTO3,
		 	   C.ORACLE_SEGMENTO4, C.ORACLE_SEGMENTO5, C.ORACLE_SEGMENTO6, C.ORACLE_SEGMENTO7
		  	   FROM FECXP_CLASIFICACION_FE B, FECXP_CUENTAS_ERP_CARATULA C
			   WHERE B.CLA_FE_ID = C.CLA_FE_ID) b
		WHERE A.E_CODIGO = B.E_CODIGO
		  AND A.ORACLE_SEGMENTO1 = B.ORACLE_SEGMENTO1
		  AND A.ORACLE_SEGMENTO2 = B.ORACLE_SEGMENTO2
		  AND A.ORACLE_SEGMENTO3 = B.ORACLE_SEGMENTO3
		  AND A.ORACLE_SEGMENTO4 = B.ORACLE_SEGMENTO4
		  AND A.ORACLE_SEGMENTO5 = B.ORACLE_SEGMENTO5
		  AND A.ORACLE_SEGMENTO6 = B.ORACLE_SEGMENTO6
		  AND A.ORACLE_SEGMENTO7 = B.ORACLE_SEGMENTO7
		GROUP BY A.E_CODIGO, A.DES_EMPRESA, 1,  A.PERIODO,  A.MES,
				A.MON_ORACLE, A.TIPO_CAMBIO, B.CLA_FE_ID, B.CLA_FE_DES;
		/*  TERMINA LA INCLUSION DE REGISTROS CARATULA ERP*/
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
		/*  INICIA LA INCLUSION DE REGISTROS CARATULA SOIN*/
		INSERT INTO FECXP_SOIN_CARATULA_TMP
		SELECT	EP.E_CODIGO, E.DES_EMPRESA, (TO_CHAR(EP.FECHA_APLICACION,'YYYY')) AS PERIODO, (TO_CHAR(EP.FECHA_APLICACION,'MM')) AS MES,
			M.MON_ORACLE, M.TIPO_CAMBIO, PS.IMPORTE_LINEA  AS IMPORTE, PS.CTAM01, PS.CTAM02, PS.CTAM03
		 FROM	FECXP_ENC_PAGOS_SOIN EP,
			FECXP_DET_PAGOS_SOIN PS,
			FECXC_EMPRESAS E,
			FECXP_MONEDAS M
		WHERE	TO_NUMBER (TO_CHAR (EP.FECHA_APLICACION, 'YYYY')) = V_PERIODO
		AND		TO_NUMBER (TO_CHAR (EP.FECHA_APLICACION, 'MM')) < V_MES_ACT
		AND		M.MES = TO_NUMBER (TO_CHAR (EP.FECHA_APLICACION, 'MM'))
			AND		M.MON_SET = EP.MONEDA
		AND		E.E_CODIGO = EP.E_CODIGO
		AND		EP.SECUENCIA_PAGOS_SOIN = PS.SECUENCIA_PAGOS_SOIN
		AND		EP.E_CODIGO 			= PS.E_CODIGO
		AND		PS.CTAM01 <> '000';
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
		INSERT	INTO FECXP_REAL_CARATULA (
			E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
		SELECT A.E_CODIGO, A.DES_EMPRESA, V_ID_SESION,  A.PERIODO,  A.MES,
				A.MON_ORACLE, A.TIPO_CAMBIO, B.CLA_FE_ID, B.CLA_FE_DES, SUM(IMPORTE*B.CLA_ATRIBUTO3)
		FROM FECXP_SOIN_CARATULA_TMP A, (SELECT C.E_CODIGO, B.CLA_FE_ID, B.CLA_ATRIBUTO3,B.CLA_FE_DES,  C.CTAM01, C.CTAM02, C.CTAM03
		  	   FROM FECXP_CLASIFICACION_FE B, FECXP_CTAS_SOIN_CARATULA_TMP C
			   WHERE B.CLA_FE_ID = C.CLA_FE_ID) B
		WHERE A.E_CODIGO = B.E_CODIGO
		  AND A.CTAM01 = B.CTAM01
		  AND A.CTAM02  = B.CTAM02
		 	  AND A.CTAM03  = B.CTAM03
		GROUP BY A.E_CODIGO, A.DES_EMPRESA, 1,  A.PERIODO,  A.MES,
				A.MON_ORACLE, A.TIPO_CAMBIO, B.CLA_FE_ID, B.CLA_FE_DES;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	/*  TERMINA LA INCLUSION DE REGISTROS CARATULA SOIN*/
	BEGIN
			--== INSERTA REGISTROS IMPORTADOS QUE AFECTAN AL SALDO ==--
		INSERT	INTO FECXP_REAL_CARATULA (
				E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA, ESTATUS)
		SELECT	E.E_CODIGO, E.DES_EMPRESA, V_ID_SESION, TO_NUMBER (TO_CHAR (D.FECHA, 'YYYY')), D.MES, D.MONEDA_IMP, M.TIPO_CAMBIO, C.CLA_FE_ID, C.CLA_FE_DES, TO_NUMBER (C.CLA_ATRIBUTO3) * D.IMPORTE_LINEA, 'IMPORTADO'
		FROM	FECXP_MONEDAS M,
				FECXC_EMPRESAS E,
				FECXP_CLASIFICACION_FE C,
				FECXP_IMPORTACION_DATOS_HIST D
		WHERE	D.ESTATUS_ORIGEN = 'IMPORTADO'
		AND		TO_NUMBER (TO_CHAR (D.FECHA, 'YYYY')) = V_PERIODO
		AND		D.MES < V_MES_ACT
		AND		D.TIPO_IMPORTACION IN ('R', 'S')
		AND		E.E_CODIGO = D.E_EMPRESA_IMP
		AND		M.MON_ORACLE = D.MONEDA_IMP
		AND		M.MES = D.MES
		AND		C.CLA_FE_ID = D.CLA_FE_ID_IMP;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	--== INSERTA LOS SALDOS INICIALES ==--
	------------------------------------------------------------------------------
	------------------------------------------------------------------------------
	--== CALCULA E INSERTA SALDOS ==--
	V_MES_ACT:= 1;
	LOOP
		BEGIN
					--== CALCULA DE SALDOS FINALES PARA LAS EMPRESAS QUE HAYAN GENERADO FE ==--
			INSERT	INTO FECXP_REAL_CARATULA (
					E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
			SELECT	E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, 'SF', 'SALDO FINAL', SUM (IMPORTE_LINEA)
			FROM	FECXP_CLASIFICACION_FE CF,
					FECXP_REAL_CARATULA C
			WHERE	C.PERIODO = V_PERIODO
			AND		C.MES = V_MES_ACT
			AND		CF.GENERA_SALDO = 1
			AND		CF.CLA_FE_ID = C.CLA_FE_ID
			GROUP BY C.E_CODIGO, C.DES_EMPRESA, C.ID_SESION_RC, C.PERIODO, C.MES, C.MONEDA, C.TIPO_CAMBIO;
			EXCEPTION
			WHEN NO_DATA_FOUND THEN
				 v_errores :=1;
		END;
		BEGIN
			-- INSERTA EL SALDO INICIAL DEL SIGUIENTE MES
			INSERT	INTO FECXP_REAL_CARATULA (
				E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
			SELECT	E_CODIGO, DES_EMPRESA, ID_SESION_RC,
				CASE WHEN MES = 12 THEN PERIODO + 1 ELSE PERIODO END,
				CASE WHEN MES = 12 THEN 1 ELSE MES + 1 END, MONEDA, TIPO_CAMBIO,
				'SI', 'SALDO INICIAL', IMPORTE_LINEA
			FROM	FECXP_REAL_CARATULA
			WHERE	PERIODO = V_PERIODO
			AND		MES = V_MES_ACT
			AND		CLA_FE_ID = 'SF';
			EXCEPTION
			WHEN NO_DATA_FOUND THEN
			 	 v_errores :=1;
	 	END;
		V_MES_ACT := V_MES_ACT + 1;
        EXIT WHEN V_MES_ACT = 11;
	END LOOP;
	/*
		--  INSERTAMOS EN LA TABLA DE REPORTE REAL FLUCTUACION CAMBIARIA PARA DATOS ERP
	INSERT	INTO FECXP_REAL_CARATULA (
			E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES,
			MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
	SELECT	CM.E_CODIGO,
			CM.DES_EMPRESA,
			V_ID_SESION,
			CM.PERIODO,
			CM.MES,
			'MXP' MONEDA,
			1 TIPO_CAMBIO,
			'DIC01' CLA_FE_ID,
			'DIFERENCIAL CAMBIARIO' CLA_FE_DES,
			CD.IMPORTE_LINEA - CM.IMPORTE_LINEA IMPORTE_LINEA
	FROM	(
			SELECT	PE.E_CODIGO,
					E.DES_EMPRESA,
					(TO_CHAR(PE.FECHA_APLICACION,'YYYY')) AS PERIODO,
					(TO_CHAR(PE.FECHA_APLICACION,'MM')) AS MES,
					SUM (M.TIPO_CAMBIO * PP.IMPORTE_LINEA * CF.CLA_ATRIBUTO3) IMPORTE_LINEA
			FROM	FECXP_CUENTAS_ERP_CARATULA C,
					FECXP_ENC_PAGOS_ERP PE,
					FECXP_DET_PAGOS_PROCESADOS PP,
					FECXC_EMPRESAS E,
					FECXP_CLASIFICACION_FE CF,
					FECXP_MONEDAS M
			WHERE	TO_NUMBER (TO_CHAR (PE.FECHA_APLICACION, 'YYYY')) =V_PERIODO
			AND		TO_NUMBER (TO_CHAR (PE.FECHA_APLICACION, 'MM')) < V_MES_ACT
			AND		M.MES = TO_NUMBER(TO_CHAR(PE.FECHA_APLICACION,'MM'))
			AND		M.MON_SET = PE.MONEDA
			AND		E.E_CODIGO = PE.E_CODIGO
			AND		CF.CLA_FE_ID = C.CLA_FE_ID
			AND		PE.SECUENCIA_PAGOS_ERP = PP.SECUENCIA_PAGOS_ERP
			AND		C.ORACLE_SEGMENTO1 = PP.ORACLE_SEGMENTO1
			AND		C.ORACLE_SEGMENTO2 = PP.ORACLE_SEGMENTO2
			AND		C.ORACLE_SEGMENTO3 = PP.ORACLE_SEGMENTO3
			AND		C.ORACLE_SEGMENTO4 = PP.ORACLE_SEGMENTO4
			AND		C.ORACLE_SEGMENTO5 = PP.ORACLE_SEGMENTO5
			AND		C.ORACLE_SEGMENTO6 = PP.ORACLE_SEGMENTO6
			AND		C.ORACLE_SEGMENTO7 = PP.ORACLE_SEGMENTO7
			GROUP BY PE.E_CODIGO, E.DES_EMPRESA, (TO_CHAR(PE.FECHA_APLICACION,'YYYY')), (TO_CHAR(PE.FECHA_APLICACION,'MM'))
			) CM,
			(
			SELECT	PE.E_CODIGO,
					(TO_CHAR(PE.FECHA_APLICACION,'YYYY')) AS PERIODO,
					(TO_CHAR(PE.FECHA_APLICACION,'MM')) AS MES,
					SUM (PE.TIPO_CAMBIO * PP.IMPORTE_LINEA * CF.CLA_ATRIBUTO3) IMPORTE_LINEA
			FROM	FECXP_CUENTAS_ERP_CARATULA C,
					FECXP_ENC_PAGOS_ERP PE,
					FECXP_DET_PAGOS_PROCESADOS PP,
					FECXP_CLASIFICACION_FE CF
			WHERE	TO_NUMBER (TO_CHAR (PE.FECHA_APLICACION, 'YYYY')) =V_PERIODO
			AND		TO_NUMBER (TO_CHAR (PE.FECHA_APLICACION, 'MM')) < V_MES_ACT
			AND		CF.CLA_FE_ID = C.CLA_FE_ID
			AND		PE.SECUENCIA_PAGOS_ERP = PP.SECUENCIA_PAGOS_ERP
			AND		C.ORACLE_SEGMENTO1 = PP.ORACLE_SEGMENTO1
			AND		C.ORACLE_SEGMENTO2 = PP.ORACLE_SEGMENTO2
			AND		C.ORACLE_SEGMENTO3 = PP.ORACLE_SEGMENTO3
			AND		C.ORACLE_SEGMENTO4 = PP.ORACLE_SEGMENTO4
			AND		C.ORACLE_SEGMENTO5 = PP.ORACLE_SEGMENTO5
			AND		C.ORACLE_SEGMENTO6 = PP.ORACLE_SEGMENTO6
			AND		C.ORACLE_SEGMENTO7 = PP.ORACLE_SEGMENTO7
			GROUP BY PE.E_CODIGO, (TO_CHAR(PE.FECHA_APLICACION,'YYYY')), (TO_CHAR(PE.FECHA_APLICACION,'MM'))
			) CD
	WHERE	CD.E_CODIGO = CM.E_CODIGO
	AND		CD.PERIODO = CM.PERIODO
	AND		CD.MES = CM.MES;
		--  INSERTAMOS EN LA TABLA DE REPORTE REAL FLUCTUACION CAMBIARIA PARA DATOS SOIN
	INSERT	INTO FECXP_REAL_CARATULA (
			E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES,
			MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
	SELECT	CM.E_CODIGO,
			CM.DES_EMPRESA,
			V_ID_SESION,
			CM.PERIODO,
			CM.MES,
			'MXP' MONEDA,
			1 TIPO_CAMBIO,
			'DIC01' CLA_FE_ID,
			'DIFERENCIAL CAMBIARIO' CLA_FE_DES,
			CD.IMPORTE_LINEA - CM.IMPORTE_LINEA IMPORTE_LINEA
	FROM	(
			SELECT	EP.E_CODIGO,
					E.DES_EMPRESA,
					(TO_CHAR(EP.FECHA_APLICACION,'YYYY')) AS PERIODO,
					(TO_CHAR(EP.FECHA_APLICACION,'MM')) AS MES,
					SUM (M.TIPO_CAMBIO * PS.IMPORTE_LINEA * CF.CLA_ATRIBUTO3) IMPORTE_LINEA
			FROM	FECXP_CTAS_SOIN_CARATULA_TMP C,
					FECXP_ENC_PAGOS_SOIN EP,
					FECXP_DET_PAGOS_SOIN PS,
					FECXC_EMPRESAS E,
					FECXP_CLASIFICACION_FE CF,
					FECXP_MONEDAS M
			WHERE	TO_NUMBER (TO_CHAR (EP.FECHA_APLICACION, 'YYYY')) =V_PERIODO
			AND		TO_NUMBER (TO_CHAR (EP.FECHA_APLICACION, 'MM')) < V_MES_ACT
			AND		M.MES = TO_NUMBER (TO_CHAR (EP.FECHA_APLICACION, 'MM'))
		  	AND		M.MON_SET = EP.MONEDA
			AND		CF.CLA_FE_ID = C.CLA_FE_ID
			AND		E.E_CODIGO = EP.E_CODIGO
			AND		EP.SECUENCIA_PAGOS_SOIN = PS.SECUENCIA_PAGOS_SOIN
			AND		PS.CTAM01 <> '000'
			AND		C.CTAM01 = PS.CTAM01
			AND		C.CTAM02 = PS.CTAM02
			AND		C.CTAM03 = PS.CTAM03
			GROUP BY EP.E_CODIGO, E.DES_EMPRESA, (TO_CHAR(EP.FECHA_APLICACION,'YYYY')), (TO_CHAR(EP.FECHA_APLICACION,'MM'))
			) CM,
			(
			SELECT	EP.E_CODIGO,
					(TO_CHAR(EP.FECHA_APLICACION,'YYYY')) AS PERIODO,
					(TO_CHAR(EP.FECHA_APLICACION,'MM')) AS MES,
					SUM (EP.TIPO_CAMBIO * PS.IMPORTE_LINEA * CF.CLA_ATRIBUTO3) IMPORTE_LINEA
			FROM	FECXP_CTAS_SOIN_CARATULA_TMP C,
					FECXP_ENC_PAGOS_SOIN EP,
					FECXP_DET_PAGOS_SOIN PS,
					FECXP_CLASIFICACION_FE CF
			WHERE	TO_NUMBER (TO_CHAR (EP.FECHA_APLICACION, 'YYYY')) =V_PERIODO
			AND		TO_NUMBER (TO_CHAR (EP.FECHA_APLICACION, 'MM')) < V_MES_ACT
			AND		CF.CLA_FE_ID = C.CLA_FE_ID
			AND		EP.SECUENCIA_PAGOS_SOIN = PS.SECUENCIA_PAGOS_SOIN
			AND		PS.CTAM01 <> '000'
			AND		C.CTAM01 = PS.CTAM01
			AND		C.CTAM02 = PS.CTAM02
			AND		C.CTAM03 = PS.CTAM03
			GROUP BY EP.E_CODIGO, (TO_CHAR(EP.FECHA_APLICACION,'YYYY')), (TO_CHAR(EP.FECHA_APLICACION,'MM'))
			) CD;
	-- 4COMMIT;
	*/
END REALES;
PROCEDURE FORECAST
IS
/******************************************************************************************************************************
*
*    OJO ESTE PROCESO DEPENDE QUE SE HAYA EJECUTADO EL PROCESO DE CALCULO DE REALES, ESTO EN ESTE PROCESO NO SE CONTROLA
*	LA ELMINACION DE REGISTROS DE LA ESTRUCTURA FECXP_REAL_CARATULA
*
*******************************************************************************************************************************/
	V_PERIODO INT:= TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'));
	V_MES	INT:= 1;
	V_MES_SALDO INT;
	V_ID_SESION VARCHAR(25) := TO_CHAR(SYSDATE,'DD-MM-YYYY');
	V_FEC_ANT DATE;
	V_FIN INT;
	V_MES_ACT INT := TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));
	V_CLA_FE_ID FECXP_POLITICAS_ERP.CLA_FE_ID%TYPE;
	V_POLITICA_ERP_ID FECXP_POLITICAS_ERP.POLITICA_ERP_ID%TYPE;
	V_PRIORIDAD FECXP_POLITICAS_ERP.PRIORIDAD%TYPE;
	V_ORA_S1_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_INI%TYPE;
	V_ORA_S1_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_FIN%TYPE;
	V_ORA_S2_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_INI%TYPE;
	V_ORA_S2_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_FIN%TYPE;
	V_ORA_S3_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_INI%TYPE;
	V_ORA_S3_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_FIN%TYPE;
	V_ORA_S4_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_INI%TYPE;
	V_ORA_S4_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_FIN%TYPE;
	V_ORA_S5_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_INI%TYPE;
	V_ORA_S5_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_FIN%TYPE;
	V_ORA_S6_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_INI%TYPE;
	V_ORA_S6_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_FIN%TYPE;
	V_ORA_S7_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_INI%TYPE;
	V_ORA_S7_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_FIN%TYPE;
	V_POLITICA_SOIN_ID FECXP_POLITICAS_SOIN.POLITICA_SOIN_ID%TYPE;
	V_E_CODIGO_INI FECXP_POLITICAS_SOIN.E_CODIGO_INI%TYPE;
	V_E_CODIGO_FIN FECXP_POLITICAS_SOIN.E_CODIGO_FIN%TYPE;
	V_CTAM01_INI FECXP_POLITICAS_SOIN.CTAM01_INI%TYPE;
	V_CTAM01_FIN FECXP_POLITICAS_SOIN.CTAM01_FIN%TYPE;
	V_CTAM02_INI FECXP_POLITICAS_SOIN.CTAM02_INI%TYPE;
	V_CTAM02_FIN FECXP_POLITICAS_SOIN.CTAM02_FIN%TYPE;
	V_CTAM03_INI FECXP_POLITICAS_SOIN.CTAM03_INI%TYPE;
	V_CTAM03_FIN FECXP_POLITICAS_SOIN.CTAM03_FIN%TYPE;
	V_TIPO_INI FECXP_POLITICAS_SOIN.TIPO_INI%TYPE;
	V_TIPO_FIN FECXP_POLITICAS_SOIN.TIPO_FIN%TYPE;
	V_DIVISION_INI FECXP_POLITICAS_SOIN.DIVISION_INI%TYPE;
	V_DIVISION_FIN FECXP_POLITICAS_SOIN.DIVISION_FIN%TYPE;
	V_RUBRO_INI FECXP_POLITICAS_SOIN.RUBRO_INI%TYPE;
	V_RUBRO_FIN FECXP_POLITICAS_SOIN.RUBRO_FIN%TYPE;
	v_errores INTEGER;
	CURSOR CURSOR_CLASIFICACION_FE_ORACLE IS
	SELECT	 CLA_FE_ID, POLITICA_ERP_ID, PRIORIDAD, ORACLE_SEGMENTO1_INI, ORACLE_SEGMENTO1_FIN, ORACLE_SEGMENTO2_INI, ORACLE_SEGMENTO2_FIN, ORACLE_SEGMENTO3_INI, ORACLE_SEGMENTO3_FIN, ORACLE_SEGMENTO4_INI, ORACLE_SEGMENTO4_FIN, ORACLE_SEGMENTO5_INI, ORACLE_SEGMENTO5_FIN, ORACLE_SEGMENTO6_INI, ORACLE_SEGMENTO6_FIN, ORACLE_SEGMENTO7_INI, ORACLE_SEGMENTO7_FIN
	FROM	 FECXP_POLITICAS_ERP
	ORDER BY PRIORIDAD ASC;
	CURSOR CURSOR_CLASIFICACION_FE_SOIN IS
	SELECT	 CLA_FE_ID, POLITICA_SOIN_ID, PRIORIDAD, E_CODIGO_INI, E_CODIGO_FIN, CTAM01_INI, CTAM01_FIN, CTAM02_INI, CTAM02_FIN, CTAM03_INI, CTAM03_FIN, TIPO_INI, TIPO_FIN, DIVISION_INI, DIVISION_FIN, RUBRO_INI, RUBRO_FIN
	FROM	 FECXP_POLITICAS_SOIN
	ORDER BY PRIORIDAD ASC;
BEGIN
	BEGIN
		--== CARGAMOS LAS CUENTAS CONTABLES QUE GENERARON MOVIMIENTO DURANTE EL MES  ==--
		INSERT	INTO FECXP_CUENTAS_ERP_CARATULA
				(CLA_FE_ID, E_CODIGO, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7)
		SELECT	DISTINCT '|'AS CLA_ID, E_CODIGO, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3,ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
		FROM	FECXP_PPTO_CONVERSION_ERP
		WHERE	PERIODO_EXTRACCION = V_PERIODO
		AND		MES_EXTRACCION = V_MES_ACT
		AND		PERIODO = V_PERIODO;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
		INSERT	INTO FECXP_CUENTAS_SOIN_CARATULA
			(CLA_FE_ID, E_CODIGO, CTAM01, CTAM02, CTAM03, DIVISION, RUBRO)
		SELECT	DISTINCT '|' AS CLA_ID, PS.E_CODIGO, PS.ARSMAP, PS.AEJMAP, PS.CNCMAP, 0, 0
		FROM	FECXP_PPTO_CONVERSION_SOIN PS
		WHERE	PS.PERIODO_EXTRACCION = V_PERIODO
		AND 	PS.MES_EXTRACCION = V_MES_ACT;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
		UPDATE	FECXP_CUENTAS_SOIN_CARATULA C1
		SET		DIVISION = 	(
						SELECT	C2.CG13DI
						FROM	FECXP_CAT_CUENTAS_SOIN C2
						WHERE   C1.CTAM01 = C2.CTAM01
						AND		C1.CTAM02 = C2.CTAM02
						AND		C1.CTAM03 = C2.CTAM03
						),
			RUBRO = (
						SELECT	C2.CG13RU
						FROM	FECXP_CAT_CUENTAS_SOIN C2
						WHERE   C1.CTAM01 = C2.CTAM01
						AND		C1.CTAM02 = C2.CTAM02
						AND		C1.CTAM03 = C2.CTAM03
						)
		WHERE	EXISTS (
			 	SELECT	C2.CG13RU
				FROM	FECXP_CAT_CUENTAS_SOIN C2
				WHERE   C1.CTAM01 = C2.CTAM01
				AND		C1.CTAM02 = C2.CTAM02
				AND		C1.CTAM03 = C2.CTAM03
				);
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	--==  CLASIFICACION DE CUENTAS SESGUN POLITICAS DE CLASIFICACION DE FE ==--
	OPEN  CURSOR_CLASIFICACION_FE_ORACLE;
	LOOP
		FETCH CURSOR_CLASIFICACION_FE_ORACLE
		INTO  V_CLA_FE_ID, V_PRIORIDAD, V_POLITICA_ERP_ID, V_ORA_S1_INI, V_ORA_S1_FIN, V_ORA_S2_INI, V_ORA_S2_FIN, V_ORA_S3_INI, V_ORA_S3_FIN, V_ORA_S4_INI, V_ORA_S4_FIN, V_ORA_S5_INI, V_ORA_S5_FIN, V_ORA_S6_INI, V_ORA_S6_FIN, V_ORA_S7_INI, V_ORA_S7_FIN;
        EXIT WHEN CURSOR_CLASIFICACION_FE_ORACLE%NOTFOUND;
		BEGIN
			--== CLASIFICACION DE CUENTAS CONTABLES ERP ==--
			UPDATE	FECXP_CUENTAS_ERP_CARATULA
			SET		CLA_FE_ID = V_CLA_FE_ID
			WHERE	(ORACLE_SEGMENTO1 >= NVL (V_ORA_S1_INI, '0'))
			AND		(ORACLE_SEGMENTO1 <= NVL (V_ORA_S1_FIN, 'z'))
			AND		(ORACLE_SEGMENTO2 >= NVL (V_ORA_S2_INI, '0'))
			AND		(ORACLE_SEGMENTO2 <= NVL (V_ORA_S2_FIN, 'z'))
			AND		(ORACLE_SEGMENTO3 >= NVL (V_ORA_S3_INI, '0'))
			AND		(ORACLE_SEGMENTO3 <= NVL (V_ORA_S3_FIN, 'z'))
			AND		(ORACLE_SEGMENTO4 >= NVL (V_ORA_S4_INI, '0'))
			AND		(ORACLE_SEGMENTO4 <= NVL (V_ORA_S4_FIN, 'z'))
			AND		(ORACLE_SEGMENTO5 >= NVL (V_ORA_S5_INI, '0'))
			AND		(ORACLE_SEGMENTO5 <= NVL (V_ORA_S5_FIN, 'z'))
			AND		(ORACLE_SEGMENTO6 >= NVL (V_ORA_S6_INI, '0'))
			AND		(ORACLE_SEGMENTO6 <= NVL (V_ORA_S6_FIN, 'z'))
			AND		(ORACLE_SEGMENTO7 >= NVL (V_ORA_S7_INI, '0'))
			AND		(ORACLE_SEGMENTO7 <= NVL (V_ORA_S7_FIN, 'z'))
			AND		NVL (CLA_FE_ID, '|') = '|';
			EXCEPTION
			WHEN NO_DATA_FOUND THEN
				 v_errores :=1;
		END;
	END LOOP;
	CLOSE CURSOR_CLASIFICACION_FE_ORACLE;
	--== CLASIFICACION FLUJO DE EFECTIVO PARA SOIN ==--
	OPEN  CURSOR_CLASIFICACION_FE_SOIN;
	LOOP
		FETCH CURSOR_CLASIFICACION_FE_SOIN
		INTO  V_CLA_FE_ID, V_POLITICA_SOIN_ID, V_PRIORIDAD, V_E_CODIGO_INI, V_E_CODIGO_FIN, V_CTAM01_INI, V_CTAM01_FIN, V_CTAM02_INI, V_CTAM02_FIN, V_CTAM03_INI, V_CTAM03_FIN, V_TIPO_INI, V_TIPO_FIN, V_DIVISION_INI, V_DIVISION_FIN, V_RUBRO_INI, V_RUBRO_FIN;
        EXIT WHEN CURSOR_CLASIFICACION_FE_SOIN%NOTFOUND;
		BEGIN
					--== SE CLASIFICAN LAS CUENTAS DE SOIN ==--
			UPDATE	FECXP_CUENTAS_SOIN_CARATULA
			SET		CLA_FE_ID = V_CLA_FE_ID
			WHERE	(E_CODIGO >= NVL (V_E_CODIGO_INI, 0))
			AND		(E_CODIGO <= NVL (V_E_CODIGO_FIN, 9999))
			AND		(CTAM01 >= NVL (V_CTAM01_INI, '0'))
			AND		(CTAM01 <= NVL (V_CTAM01_FIN, 'z'))
			AND		(CTAM02 >= NVL (V_CTAM02_INI, '0'))
			AND		(CTAM02 <= NVL (V_CTAM02_FIN, 'z'))
			AND		(CTAM03 >= NVL (V_CTAM03_INI, '0'))
			AND		(CTAM03 <= NVL (V_CTAM03_FIN, 'z'))
			AND		(NVL (DIVISION, 0) >= NVL (V_DIVISION_INI, 0))
			AND		(NVL (DIVISION, 0) <= NVL (V_DIVISION_FIN, 9999))
			AND		(NVL (RUBRO, 0) >= NVL (V_RUBRO_INI, 0))
			AND		(NVL (RUBRO, 0) <= NVL (V_RUBRO_FIN, 9999))
			AND		NVL (CLA_FE_ID, '|') = '|';
			EXCEPTION
			WHEN NO_DATA_FOUND THEN
				 v_errores :=1;
		END;
	END LOOP;
	CLOSE CURSOR_CLASIFICACION_FE_SOIN;
/******************************************************************************************************/
--== FORECAST ==--
	-------------------------------------------ORACLE---------------------------------
	BEGIN
			--== SE INSERTAN LOS MOVIMIENTOS DE LAS CUENTAS CONTABLES ERP ==--
		INSERT INTO FECXP_PPTO_CONV_ERP_TMP
		SELECT	E.E_CODIGO, E.DES_EMPRESA, PP.PERIODO, PP.MES, PP.MONEDA, M.TIPO_CAMBIO,
				PP.ORACLE_SEGMENTO1, PP.ORACLE_SEGMENTO2, PP.ORACLE_SEGMENTO3, PP.ORACLE_SEGMENTO4, PP.ORACLE_SEGMENTO5
				,PP.ORACLE_SEGMENTO6,PP.ORACLE_SEGMENTO7,
				SUM(PP.IMPORTE_LINEA)
		FROM	FECXP_PPTO_CONVERSION_ERP PP,
				FECXC_EMPRESAS E,
				FECXP_MONEDAS M
		WHERE	PP.PERIODO_EXTRACCION = V_PERIODO
		AND		PP.MES_EXTRACCION = V_MES_ACT
		AND		PP.MES >= V_MES_ACT
		AND		M.MES = PP.MES
		AND		M.MON_ORACLE = PP.MONEDA
		AND		E.E_CODIGO = PP.E_CODIGO
		GROUP BY E.E_CODIGO, E.DES_EMPRESA, PP.PERIODO, PP.MES, PP.MONEDA, M.TIPO_CAMBIO,
				PP.ORACLE_SEGMENTO1, PP.ORACLE_SEGMENTO2, PP.ORACLE_SEGMENTO3, PP.ORACLE_SEGMENTO4, PP.ORACLE_SEGMENTO5
				,PP.ORACLE_SEGMENTO6,PP.ORACLE_SEGMENTO7;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
		INSERT INTO FECXP_REAL_CARATULA (E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
		SELECT	A.E_CODIGO, A.DES_EMPRESA,  V_ID_SESION, A.PERIODO, A.MES,
			A.MONEDA, A.TIPO_CAMBIO, B.CLA_FE_ID, SUBSTR (B.CLA_FE_DES, 1, 25) CLA_FE_DES, SUM (A.IMPORTE_LINEA)
		FROM FECXP_PPTO_CONV_ERP_TMP A, (SELECT C.E_CODIGO, B.CLA_FE_ID, B.CLA_FE_DES, B.CLA_ATRIBUTO3 , C.ORACLE_SEGMENTO1, C.ORACLE_SEGMENTO2, C.ORACLE_SEGMENTO3,
		 	   C.ORACLE_SEGMENTO4, C.ORACLE_SEGMENTO5, C.ORACLE_SEGMENTO6, C.ORACLE_SEGMENTO7
		  	   FROM FECXP_CLASIFICACION_FE B, FECXP_CUENTAS_ERP_CARATULA C
			   WHERE B.CLA_FE_ID = C.CLA_FE_ID) b
		WHERE A.E_CODIGO = B.E_CODIGO
		  AND A.ORACLE_SEGMENTO1 = B.ORACLE_SEGMENTO1
		  AND A.ORACLE_SEGMENTO2 = B.ORACLE_SEGMENTO2
		  AND A.ORACLE_SEGMENTO3 = B.ORACLE_SEGMENTO3
		  AND A.ORACLE_SEGMENTO4 = B.ORACLE_SEGMENTO4
		  AND A.ORACLE_SEGMENTO5 = B.ORACLE_SEGMENTO5
		  AND A.ORACLE_SEGMENTO6 = B.ORACLE_SEGMENTO6
		  AND A.ORACLE_SEGMENTO7 = B.ORACLE_SEGMENTO7
		GROUP BY A.E_CODIGO, A.DES_EMPRESA,   A.PERIODO, A.MES,
			A.MONEDA, A.TIPO_CAMBIO, B.CLA_FE_ID, SUBSTR (B.CLA_FE_DES, 1, 25);
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	-------------------------------------------SOIN---------------------------------
	BEGIN
			--== SE INSERTAN LOS REGISTROS DE LAS CUENTAS Q GENERARON FE ==--
		INSERT INTO FECXP_PPTO_CONV_SOIN_TMP
	    SELECT	PS.E_CODIGO, E.DES_EMPRESA, PS.PERIODO, PS.MESCOD, M.MON_ORACLE, M.TIPO_CAMBIO, SUM(PS.IMPORTE_LINEA),
				ARSMAP, AEJMAP, CNCMAP, CTACR1, CTACR2
		FROM	FECXP_PPTO_CONVERSION_SOIN PS,
				FECXC_EMPRESAS E,
				FECXP_MONEDAS M
		WHERE	PS.PERIODO_EXTRACCION = V_PERIODO
		AND		PS.MES_EXTRACCION = V_MES_ACT
		AND		PS.MESCOD >= V_MES_ACT
		AND		E.E_CODIGO = PS.E_CODIGO
		AND		M.MES = PS.MESCOD
		AND		M.MON_SYBASE = PS.MONEDA
		GROUP BY PS.E_CODIGO, E.DES_EMPRESA, PS.PERIODO, PS.MESCOD, M.MON_ORACLE, M.TIPO_CAMBIO, ARSMAP, AEJMAP, CNCMAP, CTACR1, CTACR2;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
		INSERT	INTO FECXP_REAL_CARATULA (E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
		  SELECT	A.E_CODIGO, A.DES_EMPRESA, V_ID_SESION, A.PERIODO, A.MESCOD, A.MON_ORACLE, A.TIPO_CAMBIO, B.CLA_FE_ID, SUBSTR (B.CLA_FE_DES, 1, 25), SUM (A.IMPORTE_LINEA)
		FROM FECXP_PPTO_CONV_SOIN_TMP A, (SELECT C.E_CODIGO, B.CLA_FE_ID, B.CLA_ATRIBUTO3,B.CLA_FE_DES,  C.CTAM01, C.CTAM02, C.CTAM03
		  	   FROM FECXP_CLASIFICACION_FE B, FECXP_CUENTAS_SOIN_CARATULA C
			   WHERE B.CLA_FE_ID = C.CLA_FE_ID) B
		WHERE A.E_CODIGO = B.E_CODIGO
		  AND A.CTAM01 = B.CTAM01
		  AND A.CTAM02  = B.CTAM02
		 	  AND A.CTAM03  = B.CTAM03
		GROUP BY A.E_CODIGO, A.DES_EMPRESA, A.PERIODO, A.MESCOD, A.MON_ORACLE, A.TIPO_CAMBIO, B.CLA_FE_ID, SUBSTR (B.CLA_FE_DES, 1, 25);
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
		--== INSERTA LOS REGISTROS IMPORTADOS ==--
		INSERT	INTO FECXP_REAL_CARATULA (
			E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA, ESTATUS)
		SELECT	E.E_CODIGO, E.DES_EMPRESA, V_ID_SESION, TO_NUMBER (TO_CHAR (D.FECHA, 'YYYY')), D.MES, D.MONEDA_IMP, M.TIPO_CAMBIO, C.CLA_FE_ID, SUBSTR (C.CLA_FE_DES, 1, 25), TO_NUMBER (C.CLA_ATRIBUTO3) * D.IMPORTE_LINEA, 'IMPORTADO'
		FROM	FECXP_MONEDAS M,
			FECXC_EMPRESAS E,
			FECXP_CLASIFICACION_FE C,
			FECXP_IMPORTACION_DATOS_HIST D
		WHERE	TO_NUMBER (TO_CHAR (D.FECHA, 'YYYY')) = V_PERIODO
		AND		D.MES >= V_MES_ACT
		AND		D.ESTATUS_ORIGEN = 'IMPORTADO'
		AND		D.TIPO_IMPORTACION IN ('P')
		AND		E.E_CODIGO = D.E_EMPRESA_IMP
		AND		M.MON_ORACLE = D.MONEDA_IMP
		AND		M.MES = D.MES
		AND		C.CLA_FE_ID = D.CLA_FE_ID_IMP;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	--== INSERTA LOS SALDOS INICIALES ==--
	------------------------------------------------------------------------------
	------------------------------------------------------------------------------
	LOOP
	--== CALCULA E INSERTA SALDOS ==--
		BEGIN
			--== CALCULA DE SALDOS FINALES PARA LAS EMPRESAS QUE HAYAN GENERADO FE ==--
			INSERT	INTO FECXP_REAL_CARATULA (
			E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
			SELECT	E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, 'SF', 'SALDO FINAL', SUM (IMPORTE_LINEA)
			FROM	FECXP_CLASIFICACION_FE CF,
			FECXP_REAL_CARATULA C
			WHERE	C.PERIODO = V_PERIODO
			AND		CF.GENERA_SALDO = 1
			AND		CF.CLA_FE_ID = C.CLA_FE_ID
			AND		MES = V_MES_ACT
			GROUP BY C.E_CODIGO, C.DES_EMPRESA, C.ID_SESION_RC, C.PERIODO, C.MES, C.MONEDA, C.TIPO_CAMBIO;
			EXCEPTION
			WHEN NO_DATA_FOUND THEN
				 v_errores :=1;
		END;
		BEGIN
			-- INSERTA EL SALDO INICIAL DEL SIGUIENTE MES
			INSERT	INTO FECXP_REAL_CARATULA (
			E_CODIGO, DES_EMPRESA, ID_SESION_RC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
			SELECT	E_CODIGO, DES_EMPRESA, ID_SESION_RC,
			CASE WHEN MES = 12 THEN PERIODO + 1 ELSE PERIODO END,
			CASE WHEN MES = 12 THEN 1 ELSE MES + 1 END, MONEDA, TIPO_CAMBIO,
			'SI', 'SALDO INICIAL', IMPORTE_LINEA
			FROM	FECXP_REAL_CARATULA
			WHERE	PERIODO = V_PERIODO
			AND		CLA_FE_ID = 'SF'
			AND		MES = V_MES_ACT;
			EXCEPTION
			WHEN NO_DATA_FOUND THEN
				 v_errores :=1;
		END;
		V_MES_ACT := V_MES_ACT + 1;
        EXIT WHEN V_MES_ACT = 11;
		END LOOP;
END FORECAST;
PROCEDURE PRESUPUESTO
IS
V_PERIODO INT:= TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'));
	V_MES	INT:= 1;
	V_MES_SALDO INT;
	V_ID_SESION VARCHAR(25) := TO_CHAR(SYSDATE,'DD-MM-YYYY');
	V_FEC_ANT DATE;
	V_FIN INT;
	V_MES_ACT INT := TO_NUMBER (TO_CHAR (SYSDATE, 'MM'));
	V_CLA_FE_ID FECXP_POLITICAS_ERP.CLA_FE_ID%TYPE;
	V_POLITICA_ERP_ID FECXP_POLITICAS_ERP.POLITICA_ERP_ID%TYPE;
	V_PRIORIDAD FECXP_POLITICAS_ERP.PRIORIDAD%TYPE;
	V_ORA_S1_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_INI%TYPE;
	V_ORA_S1_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO1_FIN%TYPE;
	V_ORA_S2_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_INI%TYPE;
	V_ORA_S2_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO2_FIN%TYPE;
	V_ORA_S3_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_INI%TYPE;
	V_ORA_S3_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO3_FIN%TYPE;
	V_ORA_S4_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_INI%TYPE;
	V_ORA_S4_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO4_FIN%TYPE;
	V_ORA_S5_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_INI%TYPE;
	V_ORA_S5_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO5_FIN%TYPE;
	V_ORA_S6_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_INI%TYPE;
	V_ORA_S6_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO6_FIN%TYPE;
	V_ORA_S7_INI FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_INI%TYPE;
	V_ORA_S7_FIN FECXP_POLITICAS_ERP.ORACLE_SEGMENTO7_FIN%TYPE;
	V_POLITICA_SOIN_ID FECXP_POLITICAS_SOIN.POLITICA_SOIN_ID%TYPE;
	V_E_CODIGO_INI FECXP_POLITICAS_SOIN.E_CODIGO_INI%TYPE;
	V_E_CODIGO_FIN FECXP_POLITICAS_SOIN.E_CODIGO_FIN%TYPE;
	V_CTAM01_INI FECXP_POLITICAS_SOIN.CTAM01_INI%TYPE;
	V_CTAM01_FIN FECXP_POLITICAS_SOIN.CTAM01_FIN%TYPE;
	V_CTAM02_INI FECXP_POLITICAS_SOIN.CTAM02_INI%TYPE;
	V_CTAM02_FIN FECXP_POLITICAS_SOIN.CTAM02_FIN%TYPE;
	V_CTAM03_INI FECXP_POLITICAS_SOIN.CTAM03_INI%TYPE;
	V_CTAM03_FIN FECXP_POLITICAS_SOIN.CTAM03_FIN%TYPE;
	V_TIPO_INI FECXP_POLITICAS_SOIN.TIPO_INI%TYPE;
	V_TIPO_FIN FECXP_POLITICAS_SOIN.TIPO_FIN%TYPE;
	V_DIVISION_INI FECXP_POLITICAS_SOIN.DIVISION_INI%TYPE;
	V_DIVISION_FIN FECXP_POLITICAS_SOIN.DIVISION_FIN%TYPE;
	V_RUBRO_INI FECXP_POLITICAS_SOIN.RUBRO_INI%TYPE;
	V_RUBRO_FIN FECXP_POLITICAS_SOIN.RUBRO_FIN%TYPE;
	v_errores INTEGER;
	CURSOR CURSOR_CLASIFICACION_FE_ORACLE IS
	SELECT	 CLA_FE_ID, POLITICA_ERP_ID, PRIORIDAD, ORACLE_SEGMENTO1_INI, ORACLE_SEGMENTO1_FIN, ORACLE_SEGMENTO2_INI, ORACLE_SEGMENTO2_FIN, ORACLE_SEGMENTO3_INI, ORACLE_SEGMENTO3_FIN, ORACLE_SEGMENTO4_INI, ORACLE_SEGMENTO4_FIN, ORACLE_SEGMENTO5_INI, ORACLE_SEGMENTO5_FIN, ORACLE_SEGMENTO6_INI, ORACLE_SEGMENTO6_FIN, ORACLE_SEGMENTO7_INI, ORACLE_SEGMENTO7_FIN
	FROM	 FECXP_POLITICAS_ERP
	ORDER BY PRIORIDAD ASC;
	CURSOR CURSOR_CLASIFICACION_FE_SOIN IS
	SELECT	 CLA_FE_ID, POLITICA_SOIN_ID, PRIORIDAD, E_CODIGO_INI, E_CODIGO_FIN, CTAM01_INI, CTAM01_FIN, CTAM02_INI, CTAM02_FIN, CTAM03_INI, CTAM03_FIN, TIPO_INI, TIPO_FIN, DIVISION_INI, DIVISION_FIN, RUBRO_INI, RUBRO_FIN
	FROM	 FECXP_POLITICAS_SOIN
	ORDER BY PRIORIDAD ASC;
BEGIN
	BEGIN
		DELETE	FECXP_PPTO_CARATULA;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
			--== CARGAMOS LAS CUENTAS CONTABLES QUE GENERARON MOVIMIENTO DURANTE EL MES  ==--
		INSERT	INTO FECXP_CUENTAS_ERP_CARATULA
				(CLA_FE_ID, E_CODIGO, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3, ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7)
		SELECT	DISTINCT '|'AS CLA_ID, E_CODIGO, ORACLE_SEGMENTO1, ORACLE_SEGMENTO2, ORACLE_SEGMENTO3,ORACLE_SEGMENTO4, ORACLE_SEGMENTO5, ORACLE_SEGMENTO6, ORACLE_SEGMENTO7
		FROM	FECXP_PPTO_CONVERSION_ERP
		WHERE	PERIODO_EXTRACCION = V_PERIODO
		AND		MES_EXTRACCION = V_MES_ACT
		AND		PERIODO = V_PERIODO;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
		INSERT	INTO FECXP_CUENTAS_SOIN_CARATULA
			(CLA_FE_ID, E_CODIGO, CTAM01, CTAM02, CTAM03, DIVISION, RUBRO)
		SELECT	DISTINCT '|' AS CLA_ID, PS.E_CODIGO, PS.ARSMAP, PS.AEJMAP, PS.CNCMAP, 0, 0
		FROM	FECXP_PPTO_CONVERSION_SOIN PS
		WHERE	PS.PERIODO_EXTRACCION = V_PERIODO
		AND 	PS.MES_EXTRACCION = V_MES_ACT;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
		UPDATE	FECXP_CUENTAS_SOIN_CARATULA C1
		SET		DIVISION = 	(
						SELECT	C2.CG13DI
						FROM	FECXP_CAT_CUENTAS_SOIN C2
						WHERE   C1.CTAM01 = C2.CTAM01
						AND		C1.CTAM02 = C2.CTAM02
						AND		C1.CTAM03 = C2.CTAM03
						),
			RUBRO = (
						SELECT	C2.CG13RU
						FROM	FECXP_CAT_CUENTAS_SOIN C2
						WHERE   C1.CTAM01 = C2.CTAM01
						AND		C1.CTAM02 = C2.CTAM02
						AND		C1.CTAM03 = C2.CTAM03
						)
		WHERE	EXISTS (
			 	SELECT	C2.CG13RU
				FROM	FECXP_CAT_CUENTAS_SOIN C2
				WHERE   C1.CTAM01 = C2.CTAM01
				AND		C1.CTAM02 = C2.CTAM02
				AND		C1.CTAM03 = C2.CTAM03
				);
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	--==  CLASIFICACION DE CUENTAS SESGUN POLITICAS DE CLASIFICACION DE FE ==--
	OPEN  CURSOR_CLASIFICACION_FE_ORACLE;
	LOOP
		FETCH CURSOR_CLASIFICACION_FE_ORACLE
		INTO  V_CLA_FE_ID, V_PRIORIDAD, V_POLITICA_ERP_ID, V_ORA_S1_INI, V_ORA_S1_FIN, V_ORA_S2_INI, V_ORA_S2_FIN, V_ORA_S3_INI, V_ORA_S3_FIN, V_ORA_S4_INI, V_ORA_S4_FIN, V_ORA_S5_INI, V_ORA_S5_FIN, V_ORA_S6_INI, V_ORA_S6_FIN, V_ORA_S7_INI, V_ORA_S7_FIN;
        EXIT WHEN CURSOR_CLASIFICACION_FE_ORACLE%NOTFOUND;
		BEGIN
					--== CLASIFICACION DE CUENTAS CONTABLES ERP ==--
			UPDATE	FECXP_CUENTAS_ERP_CARATULA
			SET		CLA_FE_ID = V_CLA_FE_ID
			WHERE	(ORACLE_SEGMENTO1 >= NVL (V_ORA_S1_INI, '0'))
			AND		(ORACLE_SEGMENTO1 <= NVL (V_ORA_S1_FIN, 'z'))
			AND		(ORACLE_SEGMENTO2 >= NVL (V_ORA_S2_INI, '0'))
			AND		(ORACLE_SEGMENTO2 <= NVL (V_ORA_S2_FIN, 'z'))
			AND		(ORACLE_SEGMENTO3 >= NVL (V_ORA_S3_INI, '0'))
			AND		(ORACLE_SEGMENTO3 <= NVL (V_ORA_S3_FIN, 'z'))
			AND		(ORACLE_SEGMENTO4 >= NVL (V_ORA_S4_INI, '0'))
			AND		(ORACLE_SEGMENTO4 <= NVL (V_ORA_S4_FIN, 'z'))
			AND		(ORACLE_SEGMENTO5 >= NVL (V_ORA_S5_INI, '0'))
			AND		(ORACLE_SEGMENTO5 <= NVL (V_ORA_S5_FIN, 'z'))
			AND		(ORACLE_SEGMENTO6 >= NVL (V_ORA_S6_INI, '0'))
			AND		(ORACLE_SEGMENTO6 <= NVL (V_ORA_S6_FIN, 'z'))
			AND		(ORACLE_SEGMENTO7 >= NVL (V_ORA_S7_INI, '0'))
			AND		(ORACLE_SEGMENTO7 <= NVL (V_ORA_S7_FIN, 'z'))
			AND		NVL (CLA_FE_ID, '|') = '|';
			EXCEPTION
			WHEN NO_DATA_FOUND THEN
				 v_errores :=1;
		END;
	END LOOP;
	CLOSE CURSOR_CLASIFICACION_FE_ORACLE;
	--== CLASIFICACION FLUJO DE EFECTIVO PARA SOIN ==--
	OPEN  CURSOR_CLASIFICACION_FE_SOIN;
	LOOP
		FETCH CURSOR_CLASIFICACION_FE_SOIN
		INTO  V_CLA_FE_ID, V_POLITICA_SOIN_ID, V_PRIORIDAD, V_E_CODIGO_INI, V_E_CODIGO_FIN, V_CTAM01_INI, V_CTAM01_FIN, V_CTAM02_INI, V_CTAM02_FIN, V_CTAM03_INI, V_CTAM03_FIN, V_TIPO_INI, V_TIPO_FIN, V_DIVISION_INI, V_DIVISION_FIN, V_RUBRO_INI, V_RUBRO_FIN;
        EXIT WHEN CURSOR_CLASIFICACION_FE_SOIN%NOTFOUND;
		BEGIN
					--== SE CLASIFICAN LAS CUENTAS DE SOIN ==--
			UPDATE	FECXP_CUENTAS_SOIN_CARATULA
			SET		CLA_FE_ID = V_CLA_FE_ID
			WHERE	(E_CODIGO >= NVL (V_E_CODIGO_INI, 0))
			AND		(E_CODIGO <= NVL (V_E_CODIGO_FIN, 9999))
			AND		(CTAM01 >= NVL (V_CTAM01_INI, '0'))
			AND		(CTAM01 <= NVL (V_CTAM01_FIN, 'z'))
			AND		(CTAM02 >= NVL (V_CTAM02_INI, '0'))
			AND		(CTAM02 <= NVL (V_CTAM02_FIN, 'z'))
			AND		(CTAM03 >= NVL (V_CTAM03_INI, '0'))
			AND		(CTAM03 <= NVL (V_CTAM03_FIN, 'z'))
			AND		(NVL (DIVISION, 0) >= NVL (V_DIVISION_INI, 0))
			AND		(NVL (DIVISION, 0) <= NVL (V_DIVISION_FIN, 9999))
			AND		(NVL (RUBRO, 0) >= NVL (V_RUBRO_INI, 0))
			AND		(NVL (RUBRO, 0) <= NVL (V_RUBRO_FIN, 9999))
			AND		NVL (CLA_FE_ID, '|') = '|';
			EXCEPTION
			WHEN NO_DATA_FOUND THEN
				 v_errores :=1;
		END;
	END LOOP;
	CLOSE CURSOR_CLASIFICACION_FE_SOIN;
	/******************************************************************************************************/
	--== PRESUPUESTO ==--
	-------------------------------------------ORACLE---------------------------------
	BEGIN
			--== SE INSERTAN LOS MOVIMIENTOS DE LAS CUENTAS CONTABLES ERP ==--
		INSERT INTO FECXP_PPTO_CONV_ERP_TMP
		SELECT	E.E_CODIGO, E.DES_EMPRESA, PP.PERIODO, PP.MES, PP.MONEDA, M.TIPO_CAMBIO,
				PP.ORACLE_SEGMENTO1, PP.ORACLE_SEGMENTO2, PP.ORACLE_SEGMENTO3, PP.ORACLE_SEGMENTO4, PP.ORACLE_SEGMENTO5
				,PP.ORACLE_SEGMENTO6,PP.ORACLE_SEGMENTO7,
				SUM(PP.IMPORTE_LINEA)
		FROM	FECXP_PPTO_CONVERSION_ERP PP,
				FECXC_EMPRESAS E,
				FECXP_MONEDAS M
		WHERE	PP.PERIODO_EXTRACCION = V_PERIODO
		AND		PP.MES_EXTRACCION = V_MES_ACT
		AND		M.MES = PP.MES
		AND		M.MON_ORACLE = PP.MONEDA
		AND		E.E_CODIGO = PP.E_CODIGO
		GROUP BY E.E_CODIGO, E.DES_EMPRESA, PP.PERIODO, PP.MES, PP.MONEDA, M.TIPO_CAMBIO,
				PP.ORACLE_SEGMENTO1, PP.ORACLE_SEGMENTO2, PP.ORACLE_SEGMENTO3, PP.ORACLE_SEGMENTO4, PP.ORACLE_SEGMENTO5
				,PP.ORACLE_SEGMENTO6,PP.ORACLE_SEGMENTO7;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
		INSERT INTO FECXP_PPTO_CARATULA (E_CODIGO, DES_EMPRESA, ID_SESION_PC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
		SELECT	A.E_CODIGO, A.DES_EMPRESA,  V_ID_SESION, A.PERIODO, A.MES,
			A.MONEDA, A.TIPO_CAMBIO, B.CLA_FE_ID, SUBSTR (B.CLA_FE_DES, 1, 25) CLA_FE_DES, SUM (A.IMPORTE_LINEA*TO_NUMBER (B.CLA_ATRIBUTO3))
		FROM FECXP_PPTO_CONV_ERP_TMP A, (SELECT C.E_CODIGO, B.CLA_FE_ID, B.CLA_FE_DES, B.CLA_ATRIBUTO3 , C.ORACLE_SEGMENTO1, C.ORACLE_SEGMENTO2, C.ORACLE_SEGMENTO3,
		 	   C.ORACLE_SEGMENTO4, C.ORACLE_SEGMENTO5, C.ORACLE_SEGMENTO6, C.ORACLE_SEGMENTO7
		  	   FROM FECXP_CLASIFICACION_FE B, FECXP_CUENTAS_ERP_CARATULA C
			   WHERE B.CLA_FE_ID = C.CLA_FE_ID) b
		WHERE A.E_CODIGO = B.E_CODIGO
		  AND A.ORACLE_SEGMENTO1 = B.ORACLE_SEGMENTO1
		  AND A.ORACLE_SEGMENTO2 = B.ORACLE_SEGMENTO2
		  AND A.ORACLE_SEGMENTO3 = B.ORACLE_SEGMENTO3
		  AND A.ORACLE_SEGMENTO4 = B.ORACLE_SEGMENTO4
		  AND A.ORACLE_SEGMENTO5 = B.ORACLE_SEGMENTO5
		  AND A.ORACLE_SEGMENTO6 = B.ORACLE_SEGMENTO6
		  AND A.ORACLE_SEGMENTO7 = B.ORACLE_SEGMENTO7
		GROUP BY A.E_CODIGO, A.DES_EMPRESA,   A.PERIODO, A.MES,
			A.MONEDA, A.TIPO_CAMBIO, B.CLA_FE_ID, SUBSTR (B.CLA_FE_DES, 1, 25);
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	-------------------------------------------SOIN---------------------------------
	BEGIN
			--== SE INSERTAN LOS REGISTROS DE LAS CUENTAS Q GENERARON FE ==--
		INSERT INTO FECXP_PPTO_CONV_SOIN_TMP
	    SELECT	PS.E_CODIGO, E.DES_EMPRESA, PS.PERIODO, PS.MESCOD, M.MON_ORACLE, M.TIPO_CAMBIO, SUM(PS.IMPORTE_LINEA),
				ARSMAP, AEJMAP, CNCMAP, CTACR1, CTACR2
		FROM	FECXP_PPTO_CONVERSION_SOIN PS,
				FECXC_EMPRESAS E,
				FECXP_MONEDAS M
		WHERE	PS.PERIODO_EXTRACCION = V_PERIODO
		AND		PS.MES_EXTRACCION = V_MES_ACT
		AND		E.E_CODIGO = PS.E_CODIGO
		AND		M.MES = PS.MESCOD
		AND		M.MON_SYBASE = PS.MONEDA
		GROUP BY PS.E_CODIGO, E.DES_EMPRESA, PS.PERIODO, PS.MESCOD, M.MON_ORACLE, M.TIPO_CAMBIO, ARSMAP, AEJMAP, CNCMAP, CTACR1, CTACR2;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
			INSERT	INTO FECXP_PPTO_CARATULA (E_CODIGO, DES_EMPRESA, ID_SESION_PC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
	    SELECT	A.E_CODIGO, A.DES_EMPRESA, V_ID_SESION, A.PERIODO, A.MESCOD, A.MON_ORACLE, A.TIPO_CAMBIO, B.CLA_FE_ID, SUBSTR (B.CLA_FE_DES, 1, 25), SUM (A.IMPORTE_LINEA* TO_NUMBER (B.CLA_ATRIBUTO3))
		FROM FECXP_PPTO_CONV_SOIN_TMP A, (SELECT C.E_CODIGO, B.CLA_FE_ID, B.CLA_ATRIBUTO3,B.CLA_FE_DES,  C.CTAM01, C.CTAM02, C.CTAM03
			  	   FROM FECXP_CLASIFICACION_FE B, FECXP_CUENTAS_SOIN_CARATULA C
				   WHERE B.CLA_FE_ID = C.CLA_FE_ID) B
		WHERE A.E_CODIGO = B.E_CODIGO
			  AND A.CTAM01 = B.CTAM01
			  AND A.CTAM02  = B.CTAM02
		  	  AND A.CTAM03  = B.CTAM03
		GROUP BY A.E_CODIGO, A.DES_EMPRESA, A.PERIODO, A.MESCOD, A.MON_ORACLE, A.TIPO_CAMBIO, B.CLA_FE_ID, SUBSTR (B.CLA_FE_DES, 1, 25);
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	BEGIN
			--== INSERTA LOS REGISTROS IMPORTADOS ==--
		INSERT	INTO FECXP_PPTO_CARATULA (
				E_CODIGO, DES_EMPRESA, ID_SESION_PC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA, ESTATUS)
		SELECT	E.E_CODIGO, E.DES_EMPRESA, 1 V_ID_SESION, TO_NUMBER (TO_CHAR (D.FECHA, 'YYYY')), D.MES, D.MONEDA_IMP, M.TIPO_CAMBIO, C.CLA_FE_ID, SUBSTR (C.CLA_FE_DES, 1, 25), TO_NUMBER (C.CLA_ATRIBUTO3) * D.IMPORTE_LINEA, 'IMPORTADO'
		FROM	FECXP_MONEDAS M,
				FECXC_EMPRESAS E,
				FECXP_CLASIFICACION_FE C,
				FECXP_IMPORTACION_DATOS_HIST D
		WHERE	TO_NUMBER (TO_CHAR (D.FECHA, 'YYYY')) = V_PERIODO
		AND		D.ESTATUS_ORIGEN = 'IMPORTADO'
		AND		D.TIPO_IMPORTACION IN ('S', 'P')
		AND		E.E_CODIGO = D.E_EMPRESA_IMP
		AND		M.MON_ORACLE = D.MONEDA_IMP
		AND		M.MES = D.MES
		AND		C.CLA_FE_ID = D.CLA_FE_ID_IMP;
		EXCEPTION
		WHEN NO_DATA_FOUND THEN
			 v_errores :=1;
	END;
	--== INSERTA LOS SALDOS INICIALES ==--
	------------------------------------------------------------------------------
	------------------------------------------------------------------------------
	--== CALCULA E INSERTA SALDOS ==--
	V_MES_ACT:= 1;
	LOOP
		BEGIN
					--== CALCULA DE SALDOS FINALES PARA LAS EMPRESAS QUE HAYAN GENERADO FE ==--
			INSERT	INTO FECXP_PPTO_CARATULA (
					E_CODIGO, DES_EMPRESA, ID_SESION_PC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
			SELECT	E_CODIGO, DES_EMPRESA, ID_SESION_PC, PERIODO, MES, MONEDA, TIPO_CAMBIO, 'SF', 'SALDO FINAL', SUM (IMPORTE_LINEA)
			FROM	FECXP_CLASIFICACION_FE CF,
					FECXP_PPTO_CARATULA C
			WHERE	C.PERIODO = V_PERIODO
			AND		CF.GENERA_SALDO = 1
			AND		CF.CLA_FE_ID = C.CLA_FE_ID
			AND 	C.MES = V_MES_ACT
			GROUP BY C.E_CODIGO, C.DES_EMPRESA, C.ID_SESION_PC, C.PERIODO, C.MES, C.MONEDA, C.TIPO_CAMBIO;
			EXCEPTION
			WHEN NO_DATA_FOUND THEN
				 v_errores :=1;
		END;
		BEGIN
					-- INSERTA EL SALDO INICIAL DEL SIGUIENTE MES
			INSERT	INTO FECXP_PPTO_CARATULA (
					E_CODIGO, DES_EMPRESA, ID_SESION_PC, PERIODO, MES, MONEDA, TIPO_CAMBIO, CLA_FE_ID, CLA_FE_DES, IMPORTE_LINEA)
			SELECT	E_CODIGO, DES_EMPRESA, ID_SESION_PC,
					CASE WHEN MES = 12 THEN PERIODO + 1 ELSE PERIODO END,
					CASE WHEN MES = 12 THEN 1 ELSE MES + 1 END, MONEDA, TIPO_CAMBIO,
					'SI', 'SALDO INICIAL', IMPORTE_LINEA
			FROM	FECXP_PPTO_CARATULA
			WHERE	PERIODO = V_PERIODO
			AND		CLA_FE_ID = 'SF'
			AND		MES = V_MES_ACT;
			EXCEPTION
			WHEN NO_DATA_FOUND THEN
				 v_errores :=1;
		END;
		V_MES_ACT := V_MES_ACT + 1;
        EXIT WHEN V_MES_ACT = 11;
	END LOOP;
END PRESUPUESTO;
PROCEDURE CARGA_CARATULA
(
v_CALCULAR_REALES IN NUMBER,
v_CALCULAR_FORECAST IN NUMBER,
v_CALCULAR_PRESUPUESTO IN NUMBER,
v_DEBUG				   IN VARCHAR2 DEFAULT 'N'
)
IS
BEGIN
  IF v_CALCULAR_REALES = 1 THEN
  	 	 IF v_DEBUG = 'S' THEN
		 	   	 DBMS_OUTPUT.PUT_LINE('CALCULANDO REALES');
		 END IF;
		 REALES();
	 	 COMMIT;
  END IF;
  IF v_CALCULAR_FORECAST = 1 THEN
   	 	 IF v_DEBUG = 'S' THEN
		 	   	 DBMS_OUTPUT.PUT_LINE('CALCULANDO FORECAST');
		 END IF;
	   	 FORECAST();
	 	 COMMIT;
  END IF;
   IF v_CALCULAR_PRESUPUESTO = 1 THEN
   	 	 IF v_DEBUG = 'S' THEN
	 	   	 DBMS_OUTPUT.PUT_LINE('CALCULANDO PRESUPUESTO');
		 END IF;
	   	 PRESUPUESTO();
	 	 COMMIT;
  END IF;
END CARGA_CARATULA;
END FECXP_CARATULA_PKG;
/;
