CREATE OR REPLACE EDITIONABLE PACKAGE "FECXC"."FECXP_SET_VERSION_H" 
IS
 G_VERSION_ID INTEGER;
 FUNCTION SET_VERSION(ID_VERSION_H IN INTEGER) RETURN INTEGER;
 FUNCTION GET_VERSION RETURN INTEGER;
END  FECXP_SET_VERSION_H;
/
CREATE OR REPLACE EDITIONABLE PACKAGE BODY "FECXC"."FECXP_SET_VERSION_H" 
AS
    FUNCTION SET_VERSION(ID_VERSION_H IN INTEGER) RETURN INTEGER  IS
     BEGIN
           G_VERSION_ID:= ID_VERSION_H;
           RETURN 1;
      END SET_VERSION;
    FUNCTION GET_VERSION RETURN INTEGER IS
      BEGIN
           RETURN G_VERSION_ID;
      END GET_VERSION;
END FECXP_SET_VERSION_H ;
/;
