CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "LABCONF"."PB_VACACIONES" ("FECHA_CAPTURA", "KEYEMP", "NOMBRE", "FECHA_INICIO", "FECHA_FINAL", "DIAS_VACACIONES") AS 
  SELECT VAC_FECMOD FECHA_CAPTURA,
          VAC_KEYEMP KEYEMP,
          EMP_NOMEMP NOMBRE,
          VAC_FECINI FECHA_INICIO,
          VAC_FECFIN FECHA_FINAL,
          VAC_DIAVAC DIAS_VACACIONES
     FROM LABCONF.TVPBVACC
          INNER JOIN LABCONF.NMCOEMPL ON VAC_KEYEMP = EMP_KEYEMP
    WHERE     VAC_DIAVAC >= 30
          AND VAC_FECMOD >= SYSDATE - 2
          AND VAC_FECMOD <= SYSDATE + 1;
