CREATE TABLE "USRDRC"."DERCORP_ADD_CAMPO_CAT_VAL_TAB" 
   (	"ID_CATALOGO_VALOR" NUMBER NOT NULL ENABLE, 
	"ID_CATALOGO" NUMBER, 
	"COD_CAT_VAL" VARCHAR2(10), 
	"NOM_CAT_VAL" VARCHAR2(1000), 
	"VAL_CAT_VAL" VARCHAR2(4000), 
	"DES_CAT_VAL" VARCHAR2(4000), 
	"NUM_CREATED_BY" NUMBER(15,0), 
	"FEC_CREATION_DATE" DATE, 
	"NUM_LAST_UPDATED_BY" NUMBER(15,0), 
	"FEC_LAST_UPDATE_DATE" DATE, 
	"NUM_LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATRIBUTO1" VARCHAR2(4000), 
	"ATRIBUTO2" VARCHAR2(4000), 
	"ATRIBUTO3" VARCHAR2(4000), 
	"ATRIBUTO4" VARCHAR2(250), 
	"ATRIBUTO5" VARCHAR2(250), 
	"ATRIBUTO6" VARCHAR2(250), 
	"ATRIBUTO7" VARCHAR2(250), 
	"ATRIBUTO8" VARCHAR2(250), 
	"ATRIBUTO9" VARCHAR2(250), 
	"ATRIBUTO10" VARCHAR2(250), 
	"ATRIBUTO11" VARCHAR2(250), 
	"ATRIBUTO12" VARCHAR2(250), 
	"ATRIBUTO13" VARCHAR2(250), 
	"ATRIBUTO14" VARCHAR2(250), 
	"ATRIBUTO15" VARCHAR2(250), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(250)
   ) ;
ALTER TABLE "USRDRC"."DERCORP_ADD_CAMPO_CAT_VAL_TAB" ADD CONSTRAINT "DERCORP_ADD_CAMPO_CAT_VAL__PK" PRIMARY KEY ("ID_CATALOGO_VALOR")
  USING INDEX  ENABLE;
ALTER TABLE "USRDRC"."DERCORP_ADD_CAMPO_CAT_VAL_TAB" ADD CONSTRAINT "DERCORP_ADD_CAMPO_CAT_VAL_UK1" UNIQUE ("ID_CATALOGO", "VAL_CAT_VAL")
  USING INDEX  ENABLE;
