CREATE TABLE "USRDRC"."DERCORP_PG_TAB" 
   (	"ID_PODER_GENERAL" NUMBER NOT NULL ENABLE, 
	"ID_PODER" NUMBER NOT NULL ENABLE, 
	"NUM_ORDEN" NUMBER, 
	"ID_APODERADO" NUMBER, 
	"ID_CATALOGO" NUMBER, 
	"NUM_CREATED_BY" NUMBER, 
	"FEC_CREATION_DATE" DATE, 
	"NUM_LAST_UPDATED_BY" NUMBER, 
	"FEC_LAST_UPDATE_DATE" DATE, 
	"NUM_LAST_UPDATE_LOGIN" NUMBER, 
	"ATRIBUTO1" VARCHAR2(250), 
	"ATRIBUTO2" VARCHAR2(250), 
	"ATRIBUTO3" VARCHAR2(250), 
	"ATRIBUTO4" VARCHAR2(250), 
	"ATRIBUTO5" VARCHAR2(250), 
	"ATRIBUTO6" VARCHAR2(250), 
	"ATRIBUTO7" VARCHAR2(250), 
	"ATRIBUTO8" VARCHAR2(250), 
	"ATRIBUTO9" VARCHAR2(250), 
	"ATRIBUTO10" VARCHAR2(250), 
	"ATRIBUTO11" VARCHAR2(250), 
	"ATRIBUTO12" VARCHAR2(250), 
	"ATRIBUTO13" VARCHAR2(250), 
	"ATRIBUTO14" VARCHAR2(250), 
	"ATRIBUTO15" VARCHAR2(250), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(250)
   ) ;
ALTER TABLE "USRDRC"."DERCORP_PG_TAB" ADD CONSTRAINT "DERCORP_PG_TAB_PK" PRIMARY KEY ("ID_PODER_GENERAL")
  USING INDEX  ENABLE;
ALTER TABLE "USRDRC"."DERCORP_PG_TAB" ADD CONSTRAINT "DERCORP_PG_TAB_FK" FOREIGN KEY ("ID_PODER")
	  REFERENCES "USRDRC"."DERCORP_PODERES_TAB" ("ID_PODER") ENABLE;
