CREATE TABLE "USRDRC"."DERCORP_REP_CAP_SOCIAL_TAB" 
   (	"ID_EMPRESA_SUP" NUMBER, 
	"CVE_EMPRESA_SUP" VARCHAR2(240), 
	"ID_CAT_VALOR_SUP" NUMBER, 
	"ID_EMPRESA_INF" NUMBER, 
	"CVE_EMPRESA_INF" VARCHAR2(240), 
	"ID_CAT_VALOR_INF" NUMBER, 
	"ID_CATALOGO" NUMBER, 
	"ID_FLEX" NUMBER, 
	"ID_NIVEL" NUMBER
   ) ;
