CREATE TABLE "USRDRC"."DERCORP_CONTROL_SECCION" 
   (	"ID_USER" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"ID_EMPRESA" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"ID_SECCION" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE, 
	"STATUS" NUMBER(*,0) DEFAULT 0 NOT NULL ENABLE
   ) ;
ALTER TABLE "USRDRC"."DERCORP_CONTROL_SECCION" ADD PRIMARY KEY ("ID_USER")
  USING INDEX  ENABLE;
