CREATE TABLE "USRDRC"."LOG_FLAS_TAB" 
   (	"VALOR_ANTERIOR" VARCHAR2(20), 
	"VALOR_ACTUAL" VARCHAR2(20), 
	"CREATION_DATE" DATE, 
	"NOM_DENOMINACION_ACTUAL" VARCHAR2(300), 
	"NOM_DENOMINACION_ANTERIOR" VARCHAR2(300), 
	"NOM_MODIFICO" VARCHAR2(150)
   ) ;
