CREATE TABLE "USRSIHO"."ACCESOCC" 
   (	"ACC_USUARIO" VARCHAR2(20), 
	"ACC_NOMUSUARIO" VARCHAR2(60), 
	"ACC_CENCOS" VARCHAR2(16), 
	"ACC_RESSOL" VARCHAR2(1), 
	"ACC_USSIHO" NUMBER(10,0), 
	"ACC_CORREO" VARCHAR2(200), 
	"ACC_CCOPIA" VARCHAR2(200), 
	"ACC_STATUS" VARCHAR2(1)
   ) ;
