CREATE TABLE "USRSIHO"."DETSOLACT" 
   (	"DSA_NUMSOL" NUMBER(10,0), 
	"DSA_IDEREG" NUMBER(10,0), 
	"DSA_KEYEMP" NUMBER(10,0), 
	"DSA_NOMART" VARCHAR2(40), 
	"DSA_PERSON" VARCHAR2(40), 
	"DSA_SINDICATO" VARCHAR2(12), 
	"DSA_KEYPUE" VARCHAR2(16), 
	"DSA_KEYNAC" VARCHAR2(20), 
	"DSA_NUMCAP" VARCHAR2(60), 
	"DSA_COMENT" VARCHAR2(255), 
	"DSA_STSREG" NUMBER(10,0), 
	"DSA_TIPODIS" VARCHAR2(25), 
	"DSA_REVDIS" VARCHAR2(20), 
	"DSA_NUMPET" NUMBER(10,0), 
	"DSA_NUMLLA" NUMBER(10,0), 
	"DSA_NPCANR" NUMBER(10,0), 
	"DSA_NREPTRA" NUMBER(10,0)
   ) ;
