CREATE TABLE "USRSIHO"."EMCAMPOS" 
   (	"CAM_KEYCAM" NUMBER(10,0) NOT NULL ENABLE, 
	"CAM_NOMBRE" VARCHAR2(10) NOT NULL ENABLE, 
	"CAM_DESCRI" VARCHAR2(255) NOT NULL ENABLE, 
	"CAM_KEYTAB" NUMBER(10,0) NOT NULL ENABLE
   ) ;
