CREATE TABLE "USRSIHO"."EMDETBIT" 
   (	"DET_KEYBIT" NUMBER(10,0) NOT NULL ENABLE, 
	"DET_TABLA" VARCHAR2(20) NOT NULL ENABLE, 
	"DET_CAMPO" VARCHAR2(20) NOT NULL ENABLE, 
	"DET_VALACT" VARCHAR2(100), 
	"DET_VALANT" VARCHAR2(100)
   ) ;
