CREATE TABLE "USRSIHO"."EMENVIOS" 
   (	"ENV_KEYENV" NUMBER(10,0) NOT NULL ENABLE, 
	"ENV_KEYDEP" VARCHAR2(16) NOT NULL ENABLE, 
	"ENV_FECLLA" DATE NOT NULL ENABLE, 
	"ENV_FECREQ" DATE NOT NULL ENABLE, 
	"ENV_HORLLA" VARCHAR2(5) NOT NULL ENABLE, 
	"ENV_KEYSTA" NUMBER(10,0) NOT NULL ENABLE, 
	"ENV_KEYFOR" VARCHAR2(6) NOT NULL ENABLE, 
	"ENV_KEYUSU" NUMBER(10,0) NOT NULL ENABLE, 
	"ENV_FECCAN" DATE, 
	"ENV_USUCAN" NUMBER(10,0), 
	"ENV_NOTAS" VARCHAR2(200)
   ) ;
