CREATE TABLE "USRSIHO"."EMFACTURAS" 
   (	"FAC_NUMFAC" NUMBER(10,0) NOT NULL ENABLE, 
	"FAC_CENCOS" VARCHAR2(16) NOT NULL ENABLE, 
	"FAC_NUMAGE" NUMBER(10,0) NOT NULL ENABLE, 
	"FAC_FECHA" DATE NOT NULL ENABLE, 
	"FAC_DESCRI" VARCHAR2(100) NOT NULL ENABLE, 
	"FAC_IMPORT" NUMBER(18,2) NOT NULL ENABLE, 
	"FAC_IVA" NUMBER(15,2) NOT NULL ENABLE
   ) ;
