CREATE TABLE "USRSIHO"."EMGENCAT" 
   (	"GEN_KEYCAT" NUMBER(10,0) NOT NULL ENABLE, 
	"GEN_DESCRI" VARCHAR2(60) NOT NULL ENABLE, 
	"GEN_KEYDAT" NUMBER(10,0), 
	"GEN_RANINI" VARCHAR2(30), 
	"GEN_RANFIN" VARCHAR2(255), 
	"GEN_RANMED" VARCHAR2(30)
   ) ;
