CREATE TABLE "USRSIHO"."EMLOCACION" 
   (	"LOC_KEYLOC" NUMBER(10,0) NOT NULL ENABLE, 
	"LOC_KEYDEP" VARCHAR2(16) NOT NULL ENABLE, 
	"LOC_FECHA" DATE NOT NULL ENABLE, 
	"LOC_DESCRI" VARCHAR2(100) NOT NULL ENABLE, 
	"LOC_IMPORT" NUMBER(18,2) NOT NULL ENABLE, 
	"LOC_IVA" NUMBER(15,2) NOT NULL ENABLE
   ) ;
