CREATE TABLE "USRSIHO"."EMMENACE" 
   (	"ALM_KLOGIN" NUMBER(10,0) NOT NULL ENABLE, 
	"ALM_KNUOBJ" NUMBER(10,0) NOT NULL ENABLE, 
	"ALM_TIPMOV" VARCHAR2(4) NOT NULL ENABLE, 
	"ALM_TIPACC" VARCHAR2(1), 
	"ALM_VALOR" VARCHAR2(1), 
	"ALM_PADRE" NUMBER(5,0) NOT NULL ENABLE, 
	"ALM_ORDEN" NUMBER(5,0) NOT NULL ENABLE, 
	"ALM_TIPMEN" VARCHAR2(1) NOT NULL ENABLE, 
	"ALM_TIPOBJ" VARCHAR2(4) NOT NULL ENABLE, 
	"ALM_DESCOR" VARCHAR2(20) NOT NULL ENABLE
   ) ;
