CREATE TABLE "USRSIHO"."EMOBJETO" 
   (	"OBJ_KEYPRO" VARCHAR2(10) NOT NULL ENABLE, 
	"OBJ_NOMFRM" VARCHAR2(20) NOT NULL ENABLE, 
	"OBJ_NOMOBJ" VARCHAR2(60) NOT NULL ENABLE, 
	"OBJ_KEYOBJ" NUMBER(10,0) NOT NULL ENABLE, 
	"OBJ_DESOBJ" VARCHAR2(60) NOT NULL ENABLE, 
	"OBJ_PERFIL" VARCHAR2(1) NOT NULL ENABLE, 
	"OBJ_EVENTO" VARCHAR2(1)
   ) ;
