CREATE TABLE "USRSIHO"."EMPAGDXM" 
   (	"PAG_KEYPAG" NUMBER(10,0) NOT NULL ENABLE, 
	"PAG_KEYDET" NUMBER(10,0) NOT NULL ENABLE, 
	"PAG_KEYEMP" NUMBER(10,0) NOT NULL ENABLE, 
	"PAG_HRLLEG" VARCHAR2(5) NOT NULL ENABLE, 
	"PAG_HRSALI" VARCHAR2(5) NOT NULL ENABLE, 
	"PAG_TABULA" FLOAT(126) NOT NULL ENABLE, 
	"PAG_VIATIC" FLOAT(126), 
	"PAG_NOHRAS" FLOAT(126), 
	"PAG_EXHRAS" FLOAT(126), 
	"PAG_IMPHRE" FLOAT(126), 
	"PAG_TOTALE" FLOAT(126) NOT NULL ENABLE, 
	"PAG_KEYPUE" VARCHAR2(16) NOT NULL ENABLE
   ) ;
