CREATE TABLE "USRSIHO"."EMPAGEXM" 
   (	"PAG_KEYPAG" NUMBER(10,0) NOT NULL ENABLE, 
	"PAG_KEYDEP" VARCHAR2(16) NOT NULL ENABLE, 
	"PAG_KEYFOR" NUMBER(10,0) NOT NULL ENABLE, 
	"PAG_FECPAG" DATE NOT NULL ENABLE, 
	"PAG_KEYRPH" NUMBER(10,0), 
	"PAG_KEYENV" NUMBER(10,0), 
	"PAG_KEYEST" NUMBER(5,0), 
	"PAG_FIRMAS" VARCHAR2(11), 
	"PAG_OBSERV" CLOB
   ) ;
