CREATE TABLE "USRSIHO"."ENCPCANR" 
   (	"EPC_NUMPCO" NUMBER(10,0), 
	"EPC_KEYDEP" VARCHAR2(16), 
	"EPC_FECPET" DATE, 
	"EPC_OBSERV" VARCHAR2(255), 
	"EPC_KEYUSU" VARCHAR2(20), 
	"EPC_STSPET" NUMBER(10,0)
   ) ;
