CREATE TABLE "USRSIHO"."EOLOTPLZ" 
   (	"TPL_NUMSEC" NUMBER(5,0), 
	"TPL_TIPPLZ" VARCHAR2(2), 
	"TPL_DESCRI" VARCHAR2(40), 
	"TPL_DESSEC" VARCHAR2(20), 
	"TPL_CATEGO" VARCHAR2(1), 
	"TPL_KEYPRO" NUMBER(5,0)
   ) ;
