CREATE TABLE "USRSIHO"."GLCOESEV" 
   (	"ESE_KEYEVE" VARCHAR2(16), 
	"ESE_SECEVE" NUMBER(5,0), 
	"ESE_NIVDEF" NUMBER(5,0), 
	"ESE_KEYCAT" VARCHAR2(4), 
	"ESE_DESEVE" VARCHAR2(60), 
	"ESE_NUMEVE" NUMBER(5,0), 
	"ESE_INDUTI" VARCHAR2(1), 
	"ESE_INDETQ" VARCHAR2(1), 
	"ESE_USOCAM" VARCHAR2(14), 
	"ESE_VALCO1" NUMBER(5,0), 
	"ESE_VALCO2" NUMBER(5,0), 
	"ESE_VALCO3" NUMBER(5,0)
   ) ;
