CREATE TABLE "USRSIHO"."GLCOCONS" 
   (	"CON_KEYCVC" NUMBER(10,0) NOT NULL ENABLE, 
	"CON_KEYEMP" NUMBER(10,0) NOT NULL ENABLE, 
	"CON_KEYPRO" NUMBER(5,0), 
	"CON_KEYAPR" NUMBER(5,0), 
	"CON_FECALT" DATE
   ) ;
