CREATE TABLE "USRSIHO"."GLCODETB" 
   (	"DET_KEYUSU" NUMBER(10,0), 
	"DET_FECMOV" DATE, 
	"DET_HORMOV" VARCHAR2(8), 
	"DET_KEYTAB" VARCHAR2(18), 
	"DET_KEYCAM" VARCHAR2(18), 
	"DET_VALANT" VARCHAR2(40), 
	"DET_VALACT" VARCHAR2(40)
   ) ;
