CREATE TABLE "USRSIHO"."GLCOACNO" 
   (	"ACN_KEYNOM" NUMBER(5,0) NOT NULL ENABLE, 
	"ACN_KEYUSU" NUMBER(10,0) NOT NULL ENABLE
   ) ;
ALTER TABLE "USRSIHO"."GLCOACNO" ADD CONSTRAINT "PK_GACNO" PRIMARY KEY ("ACN_KEYNOM", "ACN_KEYUSU")
  USING INDEX  ENABLE;
