CREATE TABLE "USRSIHO"."GLCODIGO" 
   (	"COD_KEYEMP" NUMBER(10,0) NOT NULL ENABLE, 
	"COD_KEYPRO" NUMBER(5,0), 
	"COD_NOMBRE" VARCHAR2(40), 
	"COD_APLLPA" VARCHAR2(40), 
	"COD_APLLMA" VARCHAR2(40)
   ) ;
