CREATE TABLE "USRSIHO"."GLDESBITA" 
   (	"SBI_NUMREC" NUMBER(10,0) NOT NULL ENABLE, 
	"SBI_KEYUSU" NUMBER(10,0), 
	"SBI_KEYNOM" NUMBER(10,0), 
	"SBI_NUMEMI" NUMBER(10,0), 
	"SBI_KEYPRO" NUMBER(10,0) NOT NULL ENABLE, 
	"SBI_KEYAPR" VARCHAR2(6), 
	"SBI_KEYEMP" NUMBER(10,0), 
	"SBI_EJERCI" NUMBER(10,0) NOT NULL ENABLE, 
	"SBI_FECDES" VARCHAR2(10), 
	"SBI_HORDES" VARCHAR2(5), 
	"SBI_NUMREM" NUMBER(10,0), 
	"SBI_CVEPOL" NUMBER(10,0), 
	"SBI_FECCOB" VARCHAR2(10)
   ) ;
