CREATE TABLE "USRSIHO"."GLWKRANG" 
   (	"RAN_NOMREP" VARCHAR2(10), 
	"RAN_IDEPCC" VARCHAR2(15), 
	"RAN_KEYUSU" NUMBER(10,0), 
	"RAN_KEYPRO" NUMBER(5,0), 
	"RAN_KEYEMP" NUMBER(10,0), 
	"RAN_KEYCON" VARCHAR2(3), 
	"RAN_KEYPER" VARCHAR2(7), 
	"RAN_KEYDEP" VARCHAR2(16), 
	"RAN_KEYPUE" VARCHAR2(16), 
	"RAN_KEYNOM" NUMBER(5,0), 
	"RAN_KEYCAT" VARCHAR2(16), 
	"RAN_KEYCEN" VARCHAR2(16)
   ) ;
