CREATE TABLE "USRSIHO"."HOCAPANDA" 
   (	"CAP_KEYDEP" VARCHAR2(16), 
	"CAP_KEYCAP" NUMBER(5,0), 
	"CAP_KEYRPH" NUMBER(10,0), 
	"CAP_RPHORI" NUMBER(10,0), 
	"CAP_FECTRA" DATE, 
	"CAP_TIPRPH" VARCHAR2(2)
   ) ;
