CREATE TABLE "USRSIHO"."HOCOMPRO" 
   (	"CPR_KEYDEP" VARCHAR2(30), 
	"CPR_DESDEP" VARCHAR2(60), 
	"CPR_PRESUPUESTO" NUMBER(20,2), 
	"CPR_COMPROMETIDO" NUMBER(20,2), 
	"CPR_EJERCIDO" NUMBER(20,2), 
	"CPR_DISPONIBLE" NUMBER(20,2), 
	"CPR_LLASINCON" NUMBER(20,2), 
	"CPR_KEYPUE" VARCHAR2(20)
   ) ;
