CREATE TABLE "USRSIHO"."HOLOEQUI" 
   (	"EQU_KEYPRO" NUMBER(5,0) NOT NULL ENABLE, 
	"EQU_KEYNOM" NUMBER(5,0) NOT NULL ENABLE, 
	"EQU_KEYAPR" NUMBER(5,0) NOT NULL ENABLE, 
	"EQU_EQUIVA" VARCHAR2(16) NOT NULL ENABLE
   ) ;
