CREATE TABLE "USRSIHO"."HOLOALRP" 
   (	"FRP_KEYSOL" NUMBER(10,0) NOT NULL ENABLE, 
	"FRP_KEYDEP" VARCHAR2(16) NOT NULL ENABLE, 
	"FRP_KEYPER" VARCHAR2(7), 
	"FRP_FECACT" DATE NOT NULL ENABLE, 
	"FRP_STSFOL" VARCHAR2(1) NOT NULL ENABLE, 
	"FRP_TOTCOS" NUMBER(15,2) NOT NULL ENABLE, 
	"FRP_KEYUSU" NUMBER(10,0) NOT NULL ENABLE, 
	"FRP_KEYNOM" NUMBER(5,0) NOT NULL ENABLE, 
	"FRP_REPETI" VARCHAR2(3) NOT NULL ENABLE, 
	"FRP_TIPTRA" VARCHAR2(2), 
	"FRP_FECSOL" DATE, 
	"FRP_FECITR" DATE, 
	"FRP_FECTRAB" DATE, 
	"FRP_FORPAG" NUMBER(10,0), 
	"FRP_TIPCAM" NUMBER(16,6), 
	"FRP_PERTRA" NUMBER(10,0), 
	"FRP_TIPFOL" VARCHAR2(1), 
	"FRP_TOTEMP" NUMBER(15,2), 
	"FRP_KEYPRO" NUMBER(5,0), 
	"FRP_UNIFOR" NUMBER(5,0), 
	"FRP_TRANSP" NUMBER(5,0), 
	"FRP_KEYRPH" NUMBER(10,0)
   ) ;
ALTER TABLE "USRSIHO"."HOLOALRP" ADD CONSTRAINT "PK_HOLOALRP" PRIMARY KEY ("FRP_KEYSOL")
  USING INDEX  ENABLE;
