CREATE TABLE "USRSIHO"."HOLOENCLLA" 
   (	"ENC_NUM_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ENC_KEYDEP" VARCHAR2(16), 
	"ENC_FECLLA" DATE, 
	"ENC_KEYTPR" VARCHAR2(6), 
	"ENC_NOMPRD" VARCHAR2(60), 
	"ENC_FECCAP" DATE NOT NULL ENABLE, 
	"ENC_KEYPRO" NUMBER(5,0), 
	"ENC_USUORI" VARCHAR2(15), 
	"ENC_AUXNU1" NUMBER(10,0), 
	"ENC_AUXCA1" VARCHAR2(60), 
	"ENC_SOLSCC" NUMBER(10,0), 
	"ENC_STSLLA" NUMBER(10,0), 
	"ENC_HJATRA" NUMBER(10,0)
   ) ;
