CREATE TABLE "USRSIHO"."HOLOCAPI" 
   (	"CAP_KEYDEP" VARCHAR2(16) NOT NULL ENABLE, 
	"CAP_KEYCAP" NUMBER(10,0) NOT NULL ENABLE, 
	"CAP_DESCAP" VARCHAR2(60), 
	"CAP_NU1AUX" VARCHAR2(10), 
	"CAP_NU2AUX" VARCHAR2(10), 
	"CAP_CA1AUX" VARCHAR2(10), 
	"CAP_CA2AUX" VARCHAR2(10)
   ) ;
ALTER TABLE "USRSIHO"."HOLOCAPI" ADD CONSTRAINT "PK_HCAPI" PRIMARY KEY ("CAP_KEYDEP", "CAP_KEYCAP")
  USING INDEX  ENABLE;
