CREATE TABLE "USRSIHO"."HOLOCOAC" 
   (	"COA_KEYPLZ" NUMBER(10,0) NOT NULL ENABLE, 
	"COA_KEYPUE" VARCHAR2(16) NOT NULL ENABLE, 
	"COA_COSUNI" NUMBER(13,2) NOT NULL ENABLE
   ) ;
ALTER TABLE "USRSIHO"."HOLOCOAC" ADD CONSTRAINT "PK_HCOAC" PRIMARY KEY ("COA_KEYPLZ", "COA_KEYPUE")
  USING INDEX  ENABLE;
