CREATE TABLE "USRSIHO"."HOLORETR" 
   (	"RET_KEYRPH" NUMBER(10,0), 
	"RET_KEYRPV" NUMBER(10,0), 
	"RET_STATUS" VARCHAR2(1), 
	"RET_KEYUSU" NUMBER(10,0), 
	"RET_LOGUSU" VARCHAR2(15), 
	"RET_IDEPCC" VARCHAR2(15), 
	"RET_FECMOV" DATE, 
	"RET_HORMOV" VARCHAR2(8)
   ) ;
