CREATE TABLE "USRSIHO"."HOLOCOCA" 
   (	"COC_KEYPLZ" NUMBER(10,0) NOT NULL ENABLE, 
	"COC_KEYCAP" NUMBER(5,0) NOT NULL ENABLE, 
	"COC_NUMSEC" NUMBER(6,0) NOT NULL ENABLE, 
	"COC_STSPAG" VARCHAR2(1) NOT NULL ENABLE, 
	"COC_KEYRPH" NUMBER(10,0), 
	"COC_KEYGDP" NUMBER(10,0), 
	"COC_HJATRA" NUMBER(10,0), 
	"COC_REGHJA" NUMBER(10,0)
   ) ;
