CREATE TABLE "USRSIHO"."HOLODEAR" 
   (	"DEA_KEYDEP" VARCHAR2(16) NOT NULL ENABLE, 
	"DEA_KEYAPR" VARCHAR2(6) NOT NULL ENABLE
   ) ;
ALTER TABLE "USRSIHO"."HOLODEAR" ADD CONSTRAINT "PK_HDEAR" PRIMARY KEY ("DEA_KEYDEP", "DEA_KEYAPR")
  USING INDEX  ENABLE;
