CREATE TABLE "USRSIHO"."HOLOFIRP" 
   (	"FIR_KEYPRO" NUMBER(5,0) NOT NULL ENABLE, 
	"FIR_KEYAPR" VARCHAR2(6) NOT NULL ENABLE, 
	"FIR_KEYNOM" NUMBER(5,0) NOT NULL ENABLE, 
	"FIR_KEYDEP" VARCHAR2(16) NOT NULL ENABLE, 
	"FIR_CODVB1" NUMBER(10,0), 
	"FIR_CODVB2" NUMBER(10,0)
   ) ;
ALTER TABLE "USRSIHO"."HOLOFIRP" ADD CONSTRAINT "PK_HFIRP" PRIMARY KEY ("FIR_KEYPRO", "FIR_KEYAPR", "FIR_KEYNOM", "FIR_KEYDEP")
  USING INDEX  ENABLE;
