CREATE TABLE "USRSIHO"."HOLOHGDP_TMP" 
   (	"HGD_KEYSEC" NUMBER(10,0), 
	"HGD_KEYDEP" VARCHAR2(16), 
	"HGD_KEYRPH" NUMBER(10,0), 
	"HGD_FECHAG" DATE, 
	"HGD_KEYEMP" NUMBER(10,0), 
	"HGD_REGRFC" VARCHAR2(13), 
	"HGD_RECURP" VARCHAR2(18), 
	"HGD_KEYPUE" VARCHAR2(16), 
	"HGD_CAPINI" NUMBER(10,0), 
	"HGD_CAPFIN" NUMBER(10,0), 
	"HGD_NUMCAP" NUMBER(10,0), 
	"HGD_KEYCON" VARCHAR2(3), 
	"HGD_MARCON" VARCHAR2(1), 
	"HGD_MARCOS" VARCHAR2(1), 
	"HGD_COSTOG" FLOAT(126), 
	"HGD_KEYSUE" VARCHAR2(4), 
	"HGD_KEYTCO" NUMBER(3,0), 
	"HGD_KEYFOL" NUMBER(6,0), 
	"HGD_KEYUSU" NUMBER(10,0), 
	"HGD_MINLEG" NUMBER(6,0), 
	"HGD_MINSAL" NUMBER(6,0), 
	"HGD_MINEXT" NUMBER(6,0), 
	"HGD_MINCOM" NUMBER(6,0)
   ) ;
ALTER TABLE "USRSIHO"."HOLOHGDP_TMP" ADD CONSTRAINT "PK_HOLOHGDP_TMP" PRIMARY KEY ("HGD_KEYSEC")
  USING INDEX  ENABLE;
