CREATE TABLE "USRSIHO"."HOLOAPCO" 
   (	"APC_KEYPRO" NUMBER(5,0) NOT NULL ENABLE, 
	"APC_KEYAPR" VARCHAR2(6), 
	"APC_KEYNOM" NUMBER(5,0) NOT NULL ENABLE, 
	"APC_KEYCON" VARCHAR2(3) NOT NULL ENABLE, 
	"APC_KEYTFO" VARCHAR2(1) NOT NULL ENABLE, 
	"APC_KEYCOM" VARCHAR2(40), 
	"APC_KEYCMC" VARCHAR2(40), 
	"APC_KEYCDF" VARCHAR2(40), 
	"APC_KEYCGT" VARCHAR2(40)
   ) ;
ALTER TABLE "USRSIHO"."HOLOAPCO" ADD CONSTRAINT "PK_HAPCO" PRIMARY KEY ("APC_KEYPRO", "APC_KEYAPR", "APC_KEYNOM", "APC_KEYCON", "APC_KEYTFO")
  USING INDEX  ENABLE;
