CREATE TABLE "USRSIHO"."HOLODETP2" 
   (	"DET_KEYPOL" NUMBER(10,0) NOT NULL ENABLE, 
	"DET_KEYFOL" NUMBER(6,0), 
	"DET_CUENTA" VARCHAR2(40) NOT NULL ENABLE, 
	"DET_CARGOS" NUMBER(16,6), 
	"DET_ABONOS" NUMBER(16,6), 
	"DET_KEYPUE" VARCHAR2(16), 
	"DET_CAIETU" NUMBER(10,0), 
	"DET_SEC_SINDICAL" VARCHAR2(50)
   ) ;
