CREATE TABLE "USRSIHO"."HOLOAGCP01" 
   (	"AGC_KEYAGR" NUMBER(5,0) NOT NULL ENABLE, 
	"AGC_KEYCON" VARCHAR2(3) NOT NULL ENABLE
   ) ;
ALTER TABLE "USRSIHO"."HOLOAGCP01" ADD CONSTRAINT "PK_HAGCP01" PRIMARY KEY ("AGC_KEYAGR", "AGC_KEYCON")
  USING INDEX  ENABLE;
