CREATE TABLE "USRSIHO"."HOLOPRES" 
   (	"PRE_KEYDEP" VARCHAR2(16) NOT NULL ENABLE, 
	"PRE_KEYPUE" VARCHAR2(16) NOT NULL ENABLE, 
	"PRE_PRESUP" NUMBER(16,2) NOT NULL ENABLE, 
	"PRE_EJERCI" NUMBER(16,2) NOT NULL ENABLE, 
	"PRE_PAGADO" NUMBER(16,2), 
	"PRE_ANIO" NUMBER(5,0), 
	"PRE_STATUS" VARCHAR2(1)
   ) ;
ALTER TABLE "USRSIHO"."HOLOPRES" ADD CONSTRAINT "PK_HPRES" PRIMARY KEY ("PRE_ANIO", "PRE_KEYDEP", "PRE_KEYPUE")
  USING INDEX  ENABLE;
