CREATE TABLE "USRSIHO"."HOLOCONT_SDW" 
   (	"MARCA_ACT" VARCHAR2(2), 
	"CMD" VARCHAR2(15), 
	"OLD_CON_KEYEMP" NUMBER(10,0), 
	"OLD_CON_FECINI" DATE, 
	"OLD_CON_FECVEN" DATE, 
	"OLD_CON_KEYDEP" VARCHAR2(16), 
	"OLD_CON_KEYPUE" VARCHAR2(16), 
	"NEW_CON_KEYEMP" NUMBER(10,0), 
	"NEW_CON_FECINI" DATE, 
	"NEW_CON_FECVEN" DATE, 
	"NEW_CON_KEYDEP" VARCHAR2(16), 
	"NEW_CON_KEYPUE" VARCHAR2(16), 
	"ORDERID1" DATE, 
	"ORDERID2" NUMBER(10,0) NOT NULL ENABLE
   ) ;
ALTER TABLE "USRSIHO"."HOLOCONT_SDW" ADD CONSTRAINT "PK_HOLOCONT_SDW" PRIMARY KEY ("ORDERID2")
  USING INDEX  ENABLE;
