CREATE TABLE "USRSIHO"."HOLOGDPR" 
   (	"GDP_KEYSEC" NUMBER(10,0) NOT NULL ENABLE, 
	"GDP_KEYDEP" VARCHAR2(16), 
	"GDP_KEYRPH" NUMBER(10,0) NOT NULL ENABLE, 
	"GDP_FECHAG" DATE NOT NULL ENABLE, 
	"GDP_KEYEMP" NUMBER(10,0) NOT NULL ENABLE, 
	"GDP_REGRFC" VARCHAR2(13), 
	"GDP_RECURP" VARCHAR2(18), 
	"GDP_KEYPUE" VARCHAR2(16) NOT NULL ENABLE, 
	"GDP_CAPINI" NUMBER(10,0) NOT NULL ENABLE, 
	"GDP_CAPFIN" NUMBER(10,0) NOT NULL ENABLE, 
	"GDP_NUMCAP" NUMBER(10,0) NOT NULL ENABLE, 
	"GDP_KEYCON" VARCHAR2(3) NOT NULL ENABLE, 
	"GDP_MARCON" VARCHAR2(1) NOT NULL ENABLE, 
	"GDP_MARCOS" VARCHAR2(1) NOT NULL ENABLE, 
	"GDP_COSUNI" FLOAT(126) NOT NULL ENABLE, 
	"GDP_KEYSUE" VARCHAR2(4), 
	"GDP_KEYTCO" NUMBER(5,0), 
	"GDP_KEYFOL" NUMBER(10,0), 
	"GDP_KEYUSU" NUMBER(10,0), 
	"GDP_MINLEG" NUMBER(10,0), 
	"GDP_MINSAL" NUMBER(10,0), 
	"GDP_MINEXT" NUMBER(10,0), 
	"GDP_MINCOM" NUMBER(10,0)
   ) ;
ALTER TABLE "USRSIHO"."HOLOGDPR" ADD CONSTRAINT "PK_HGDPR" PRIMARY KEY ("GDP_KEYSEC")
  USING INDEX  ENABLE;
