CREATE TABLE "USRSIHO"."NMCODEPS_SDW" 
   (	"MARCA_ACT" VARCHAR2(2), 
	"CMD" VARCHAR2(15), 
	"OLD_DEP_KEYDEP" VARCHAR2(16), 
	"OLD_DEP_DESDEP" VARCHAR2(40), 
	"NEW_DEP_KEYDEP" VARCHAR2(16), 
	"NEW_DEP_DESDEP" VARCHAR2(40), 
	"ORDERID1" DATE, 
	"ORDERID2" NUMBER(10,0) NOT NULL ENABLE
   ) ;
ALTER TABLE "USRSIHO"."NMCODEPS_SDW" ADD CONSTRAINT "PK_NMCODEPS_SDW" PRIMARY KEY ("ORDERID2")
  USING INDEX  ENABLE;
