CREATE TABLE "USRSIHO"."NMLOALDE" 
   (	"ALD_KEYDEP" VARCHAR2(16) NOT NULL ENABLE, 
	"ALD_KEYTPR" VARCHAR2(6), 
	"ALD_KEYEMP" NUMBER(10,0), 
	"ALD_KEYAPR" VARCHAR2(6), 
	"ALD_KEYEVE" VARCHAR2(6), 
	"ALD_PERTRA" VARCHAR2(3), 
	"ALD_IDIOMA" VARCHAR2(6), 
	"ALD_EQUCON" VARCHAR2(15), 
	"ALD_FECIDUR" DATE NOT NULL ENABLE, 
	"ALD_FECFDUR" DATE, 
	"ALD_EQUCPR" VARCHAR2(15), 
	"ALD_CTABAJ" VARCHAR2(20), 
	"ALD_MARCCO" VARCHAR2(1), 
	"ALD_COSGAS" VARCHAR2(1), 
	"ALD_KEYPRO" NUMBER(5,0) NOT NULL ENABLE, 
	"ALD_STATUS" VARCHAR2(1)
   ) ;
ALTER TABLE "USRSIHO"."NMLOALDE" ADD CONSTRAINT "PK_NALDE" PRIMARY KEY ("ALD_KEYDEP")
  USING INDEX  ENABLE;
