CREATE TABLE "USRSIHO"."NMLOCIAS_SDW" 
   (	"MARCA_ACT" VARCHAR2(2), 
	"CMD" VARCHAR2(15), 
	"OLD_CIA_KEYCIA" VARCHAR2(16), 
	"OLD_CIA_DESCIA" VARCHAR2(40), 
	"NEW_CIA_KEYCIA" VARCHAR2(16), 
	"NEW_CIA_DESCIA" VARCHAR2(40), 
	"ORDERID1" DATE, 
	"ORDERID2" NUMBER(10,0) NOT NULL ENABLE
   ) ;
ALTER TABLE "USRSIHO"."NMLOCIAS_SDW" ADD CONSTRAINT "PK_NMLOCIAS_SDW" PRIMARY KEY ("ORDERID2")
  USING INDEX  ENABLE;
