CREATE TABLE "USRSIHO"."NMLOPERI" 
   (	"PER_KEYPRO" NUMBER(5,0), 
	"PER_KEYNOM" NUMBER(5,0), 
	"PER_KEYPER" VARCHAR2(7), 
	"PER_FECINI" DATE, 
	"PER_FECFIN" DATE, 
	"PER_FECPAG" DATE, 
	"PER_FECCOR" DATE, 
	"PER_NUMMES" NUMBER(5,0), 
	"PER_ACUDOS" NUMBER(5,0), 
	"PER_ACUTRE" NUMBER(5,0), 
	"PER_ACUCUA" NUMBER(5,0), 
	"PER_NU1AUX" VARCHAR2(10), 
	"PER_NU2AUX" VARCHAR2(10), 
	"PER_NU3AUX" VARCHAR2(10), 
	"PER_NU4AUX" VARCHAR2(10), 
	"PER_NU5AUX" VARCHAR2(10), 
	"PER_KEYPOL" VARCHAR2(10), 
	"PER_IMPNOM" NUMBER(18,2), 
	"PER_TOTEMP" NUMBER(10,0), 
	"PER_FECACT" DATE, 
	"PER_HORACT" VARCHAR2(6), 
	"PER_PERSEL" VARCHAR2(1), 
	"PER_FECPOL" DATE, 
	"PER_DESPOL" VARCHAR2(20)
   ) ;
ALTER TABLE "USRSIHO"."NMLOPERI" ADD CONSTRAINT "U119_74" PRIMARY KEY ("PER_KEYPRO", "PER_KEYPER")
  USING INDEX  ENABLE;
