CREATE TABLE "USRSIHO"."NMREPLEG" 
   (	"PLE_NOMREP" VARCHAR2(100), 
	"PLE_RFCREP" VARCHAR2(20), 
	"PLE_CURP" VARCHAR2(20)
   ) ;
ALTER TABLE "USRSIHO"."NMREPLEG" ADD CONSTRAINT "PK_NMREPLEG" PRIMARY KEY ("PLE_RFCREP")
  USING INDEX  ENABLE;
