CREATE TABLE "USRSIHO"."RPCOENQU" 
   (	"ENQ_KEYREP" VARCHAR2(16), 
	"ENQ_IDEPCC" VARCHAR2(15), 
	"ENQ_KEYUSU" NUMBER(38,0), 
	"ENQ_FECELA" DATE, 
	"ENQ_FECACT" DATE, 
	"ENQ_TITREP" VARCHAR2(80), 
	"ENQ_STATUS" VARCHAR2(1), 
	"ENQ_DESREP" VARCHAR2(60), 
	"ENQ_USUEXP" VARCHAR2(1)
   ) ;
