CREATE TABLE "FECI"."FECI_LOG_TAB" 
   (	"ID_LOG" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CLASE" VARCHAR2(250) NOT NULL ENABLE, 
	"MENSAJE" VARCHAR2(500) NOT NULL ENABLE, 
	"EXCEPCION" VARCHAR2(4000), 
	"NIVEL" VARCHAR2(100) NOT NULL ENABLE, 
	"FECHA_HORA" DATE NOT NULL ENABLE, 
	"CLAVE_RASTREO" VARCHAR2(100) NOT NULL ENABLE
   ) ;
ALTER TABLE "FECI"."FECI_LOG_TAB" ADD CONSTRAINT "LOG_PK" PRIMARY KEY ("ID_LOG")
  USING INDEX  ENABLE;
