CREATE TABLE "FECI"."FECI_GRUPO_FORECAST_CAT" 
   (	"ID_GRUPO_FORECAST" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"COD_GRUPO_FORECAST" VARCHAR2(20) NOT NULL ENABLE, 
	"DES_GRUPO_FORECAST" VARCHAR2(250) NOT NULL ENABLE, 
	"FEC_CREACION" DATE NOT NULL ENABLE, 
	"FEC_ULT_MODIFICACION" DATE NOT NULL ENABLE, 
	"ID_USUARIO_CREACION" NUMBER NOT NULL ENABLE, 
	"ID_USUARIO_ULT_MODIF" NUMBER NOT NULL ENABLE, 
	"IND_ESTADO" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "FECI"."FECI_GRUPO_FORECAST_CAT" ADD CONSTRAINT "GRUPO_FORECAST_PK" PRIMARY KEY ("ID_GRUPO_FORECAST")
  USING INDEX  ENABLE;
