CREATE TABLE "FECI"."FECI_CLASE_CLIENTE_CAT" 
   (	"ID_CLASE_CLIENTE" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"COD_CLASE_CLIENTE" VARCHAR2(20) NOT NULL ENABLE, 
	"DES_CLASE_CLIENTE" VARCHAR2(250) NOT NULL ENABLE, 
	"FEC_CREACION" DATE NOT NULL ENABLE, 
	"FEC_ULT_MODIFICACION" DATE NOT NULL ENABLE, 
	"ID_USUARIO_CREACION" NUMBER NOT NULL ENABLE, 
	"ID_USUARIO_ULT_MODIF" NUMBER NOT NULL ENABLE, 
	"IND_ESTADO" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "FECI"."FECI_CLASE_CLIENTE_CAT" ADD CONSTRAINT "CLASE_CLIENTE_PK" PRIMARY KEY ("ID_CLASE_CLIENTE")
  USING INDEX  ENABLE;
