CREATE TABLE "FECI"."FECI_ESTIMACION_TAB" 
   (	"ID_ESTIMACION" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"COD_GRUPO_FORECAST" VARCHAR2(20) NOT NULL ENABLE, 
	"COD_SEGMENTO" VARCHAR2(20) NOT NULL ENABLE, 
	"NUM_ANIO" NUMBER NOT NULL ENABLE, 
	"NUM_MES" NUMBER NOT NULL ENABLE, 
	"NUM_SEMANA" NUMBER NOT NULL ENABLE, 
	"NUM_IMPORTE_MXN" NUMBER NOT NULL ENABLE, 
	"NUM_IMPORTE_USD" NUMBER NOT NULL ENABLE, 
	"FEC_CREACION" DATE NOT NULL ENABLE, 
	"FEC_ULT_MODIFICACION" DATE NOT NULL ENABLE, 
	"ID_USUARIO_CREACION" NUMBER NOT NULL ENABLE, 
	"ID_USUARIO_ULT_MODIF" NUMBER NOT NULL ENABLE, 
	"IND_ESTADO" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "FECI"."FECI_ESTIMACION_TAB" ADD CONSTRAINT "ESTIMACION_PK" PRIMARY KEY ("ID_ESTIMACION")
  USING INDEX  ENABLE;
