CREATE TABLE "FECI"."FECI_REGN_CONC_CAT" 
   (	"ID_REGION" NUMBER, 
	"ID_CONCEPTO" NUMBER, 
	"FEC_CREACION" DATE NOT NULL ENABLE, 
	"FEC_ULT_MODIFICACION" DATE NOT NULL ENABLE, 
	"ID_USUARIO_CREACION" NUMBER NOT NULL ENABLE, 
	"ID_USUARIO_ULT_MODIF" NUMBER NOT NULL ENABLE, 
	"IND_ESTADO" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "FECI"."FECI_REGN_CONC_CAT" ADD CONSTRAINT "FK_FECI_REG_FECI_RECO_FECI_CON" FOREIGN KEY ("ID_CONCEPTO")
	  REFERENCES "FECI"."FECI_CONCEPTO_CAT" ("ID_CONCEPTO") ENABLE;
ALTER TABLE "FECI"."FECI_REGN_CONC_CAT" ADD CONSTRAINT "FK_FECI_REG_FECI_RECO_FECI_REG" FOREIGN KEY ("ID_REGION")
	  REFERENCES "FECI"."FECI_REGION_CAT" ("ID_REGION") ENABLE;
