CREATE TABLE "FECI"."HF_HASH" 
   (	"ID" NUMBER(10,0), 
	"KEY" NVARCHAR2(255), 
	"VALUE" NCLOB, 
	"EXPIRE_AT" TIMESTAMP (4), 
	"FIELD" NVARCHAR2(40)
   ) ;
ALTER TABLE "FECI"."HF_HASH" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
ALTER TABLE "FECI"."HF_HASH" ADD UNIQUE ("KEY", "FIELD")
  USING INDEX  ENABLE;
