CREATE TABLE "FECI"."HF_JOB" 
   (	"ID" NUMBER(10,0), 
	"STATE_ID" NUMBER(10,0), 
	"STATE_NAME" NVARCHAR2(20), 
	"INVOCATION_DATA" NCLOB, 
	"ARGUMENTS" NCLOB, 
	"CREATED_AT" TIMESTAMP (4), 
	"EXPIRE_AT" TIMESTAMP (4)
   ) ;
ALTER TABLE "FECI"."HF_JOB" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
