CREATE TABLE "FECI"."HF_JOB_PARAMETER" 
   (	"ID" NUMBER(10,0), 
	"NAME" NVARCHAR2(40), 
	"VALUE" NCLOB, 
	"JOB_ID" NUMBER(10,0)
   ) ;
ALTER TABLE "FECI"."HF_JOB_PARAMETER" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
ALTER TABLE "FECI"."HF_JOB_PARAMETER" ADD CONSTRAINT "FK_JOB_PARAMETER_JOB" FOREIGN KEY ("JOB_ID")
	  REFERENCES "FECI"."HF_JOB" ("ID") ON DELETE CASCADE ENABLE;
