CREATE TABLE "FECI"."HF_LIST" 
   (	"ID" NUMBER(10,0), 
	"KEY" NVARCHAR2(255), 
	"VALUE" NCLOB, 
	"EXPIRE_AT" TIMESTAMP (4)
   ) ;
ALTER TABLE "FECI"."HF_LIST" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
