CREATE OR REPLACE EDITIONABLE PROCEDURE "FECI"."FECI_OBTENER_CONFIGURACION_PR" 
AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
feci_cursor SYS_REFCURSOR;
BEGIN
    open feci_cursor for
    SELECT ID_CONFIGURACION,COD_CONFIGURACION,DES_CONFIGURACION,
    FEC_CREACION,FEC_ULT_MODIFICACION,ID_USUARIO_CREACION,
    ID_USUARIO_ULT_MODIF,IND_ESTADO
    FROM FECI_CONFIGURACION_CAT WHERE IND_ESTADO = 1;
    DBMS_SQL.RETURN_RESULT(feci_cursor);
END FECI_OBTENER_CONFIGURACION_PR;
/
