CREATE OR REPLACE EDITIONABLE PROCEDURE "FECI"."FECI_OBTENER_GRFC_SEGM_PR" 
AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
feci_cursor SYS_REFCURSOR;
BEGIN
   open feci_cursor for
        SELECT ID_SEGMENTO,ID_GRUPO_FORECAST,FEC_CREACION,FEC_ULT_MODIFICACION,
        ID_USUARIO_CREACION,ID_USUARIO_ULT_MODIF,IND_ESTADO
        FROM FECI_GRFC_SEGM_CAT WHERE IND_ESTADO =1;
    DBMS_SQL.RETURN_RESULT(feci_cursor);
END FECI_OBTENER_GRFC_SEGM_PR;
/
