CREATE OR REPLACE EDITIONABLE PROCEDURE "FECI"."FECI_OBTENER_CLASIFICACION_PR" 
(
        p_FOLIO_RECIBO         VARCHAR2,
        p_TIPO_RECIBO          VARCHAR2
)
AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
feci_cursor SYS_REFCURSOR;
BEGIN
   open feci_cursor for
        select
        ID_CLASIFICACION,FOLIO_RECIBO,TIPO_RECIBO,ORDEN,PORCENTAJE_IVA,IMPORTE_ORG,
        MONTO_BASE_ORG,MONTO_IVA_ORG,IMPORTE_MXN,MONTO_BASE_MXN,MONTO_IVA_MXN,
        IMPORTE_USD,MONTO_BASE_USD,MONTO_IVA_USD,COD_SEGMENTO,COD_GRUPO_FORECAST,
        COD_CONCEPTO,COD_REGION,COD_PAIS,DESC_CPS,FEC_CREACION,FEC_ULT_MODIFICACION,
        ID_USUARIO_CREACION,ID_USUARIO_ULT_MODIF,IND_ESTADO
        from FECI_CLASIFICACION_TAB
        WHERE FOLIO_RECIBO = p_FOLIO_RECIBO
        AND TIPO_RECIBO = p_TIPO_RECIBO
        AND IND_ESTADO = 1;
   DBMS_SQL.RETURN_RESULT(feci_cursor);
END FECI_OBTENER_CLASIFICACION_PR;
/
