CREATE OR REPLACE EDITIONABLE PROCEDURE "FECI"."FECI_OBTENER_PORCENTAJE_IVA_PR" 
AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
feci_cursor SYS_REFCURSOR;
BEGIN
   open feci_cursor for
        SELECT ID_PORCENTAJE_IVA,COD_PORCENTAJE_IVA,NUM_VALOR,
        FEC_CREACION,FEC_ULT_MODIFICACION,ID_USUARIO_CREACION,
        ID_USUARIO_ULT_MODIF
        FROM FECI_PORCENTAJE_IVA_CAT WHERE IND_ESTADO =1 ;
    DBMS_SQL.RETURN_RESULT(feci_cursor);
END FECI_OBTENER_PORCENTAJE_IVA_PR;
/
