CREATE OR REPLACE EDITIONABLE PROCEDURE "FECI"."FECI_OBTENER_SEGMENTO_PR" 
AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
feci_cursor SYS_REFCURSOR;
BEGIN
   open feci_cursor for
        SELECT ID_SEGMENTO,COD_SEGMENTO,DES_SEGMENTO,COD_MONEDA,IND_CPS,FEC_CREACION,FEC_ULT_MODIFICACION,
        ID_USUARIO_CREACION,ID_USUARIO_ULT_MODIF,IND_ESTADO, IND_PAIS
        FROM FECI_SEGMENTO_CAT WHERE IND_ESTADO =1 ;
    DBMS_SQL.RETURN_RESULT(feci_cursor);
END FECI_OBTENER_SEGMENTO_PR;
/
