CREATE OR REPLACE EDITIONABLE PROCEDURE "FECI"."FECI_OBTENER_CLASE_CLIENTE_PR" 
AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
feci_cursors SYS_REFCURSOR;
BEGIN
    open feci_cursors for
    SELECT
    ID_CLASE_CLIENTE,COD_CLASE_CLIENTE,DES_CLASE_CLIENTE,FEC_CREACION,FEC_ULT_MODIFICACION,FEC_ULT_MODIFICACION,
    ID_USUARIO_CREACION,ID_USUARIO_ULT_MODIF,IND_ESTADO
    FROM FECI_CLASE_CLIENTE_CAT WHERE  IND_ESTADO =1;
    DBMS_SQL.RETURN_RESULT(feci_cursors);
END FECI_OBTENER_CLASE_CLIENTE_PR ;
/
