CREATE OR REPLACE EDITIONABLE PROCEDURE "FECI"."FECI_OBTENER_ROL_OPERACION_PR" 
(
    p_ROL NUMBER
)
AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
feci_cursor SYS_REFCURSOR;
BEGIN
   open feci_cursor for
        SELECT
        OPER.ID_OPERACION,
        OPER.DES_AGRUPADOR,
        OPER.COD_OPERACION,
        OPER.DES_NOMBRE,
        OPER.COD_TIPO_OPERACION,
        RO.ID_ROL
        FROM FECI_OPERACION_TAB OPER
        LEFT JOIN FECI_ROL_OPERACION_TAB RO ON OPER.ID_OPERACION = RO.ID_OPERACION
         WHERE RO.ID_ROL = p_ROL AND OPER.IND_ESTADO=1 AND RO.IND_ESTADO=1;
    DBMS_SQL.RETURN_RESULT(feci_cursor);
END FECI_OBTENER_ROL_OPERACION_PR ;
/
