CREATE OR REPLACE EDITIONABLE PROCEDURE "FECI"."FECI_OBTENER_RESULTADO_BATCH" 
AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
feci_cursor SYS_REFCURSOR;
BEGIN
   open feci_cursor for
        SELECT ID_RESULTADO_BATCH, FEC_INICIO, FEC_FIN, TIPO_EJECUCION,TIPO_RESULTADO,OBSERVACIONES,NUM_NUEVOS_RECIBOS,
        NUM_NUEVAS_EMPRESAS,NUM_NUEVAS_MONEDAS,NUM_NUEVOS_TC FROM FECI_RESULTADO_BATCH_TAB
        WHERE ID_RESULTADO_BATCH = (SELECT MAX(ID_RESULTADO_BATCH) FROM FECI_RESULTADO_BATCH_TAB);
    DBMS_SQL.RETURN_RESULT(feci_cursor);
END FECI_OBTENER_RESULTADO_BATCH;
/
