CREATE OR REPLACE EDITIONABLE PROCEDURE "FECI"."FECI_MODIFICA_GRUPO_FORECAST_PR" 
(
        p_CODIGO         VARCHAR2,
        p_DESCRIPCION         VARCHAR2,
        p_ID                NUMBER,
        p_USUARIO              NUMBER
)
IS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
BEGIN
        UPDATE FECI_GRUPO_FORECAST_CAT
        SET COD_GRUPO_FORECAST = p_CODIGO,
        DES_GRUPO_FORECAST = p_DESCRIPCION,
        ID_USUARIO_ULT_MODIF = p_USUARIO,
        FEC_ULT_MODIFICACION = SYSDATE
        WHERE ID_GRUPO_FORECAST = p_ID;
END FECI_MODIFICA_GRUPO_FORECAST_PR ;
/
