CREATE OR REPLACE EDITIONABLE PROCEDURE "FECI"."HISTFECI_PROCESA_CATALOGOS_PR" 
AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
  CONTADOR_EMPRESA NUMBER;
  CONTADOR_MONEDAS NUMBER;
  CONTADOR_PAIS NUMBER;
BEGIN
    --PARA CATALOGO EMPRESAS
    SELECT
       COUNT(DISTINCT TRIM(COD_EMPRESA)) INTO CONTADOR_EMPRESA
    FROM HISTFECI_RECIBOS_MASIVO_TAB
    WHERE TRIM(COD_EMPRESA) IS NOT NULL
    AND TRIM(COD_EMPRESA) NOT IN (SELECT TRIM(COD_EMPRESA) FROM FECI_EMPRESA_CAT);
    IF CONTADOR_EMPRESA > 0 THEN
        -- Registra empresas que no estan en el catalogo FECI_EMPRESA_CAT
        INSERT INTO FECI_EMPRESA_CAT (
            COD_EMPRESA,
            DES_EMPRESA,
            FEC_CREACION,
            FEC_ULT_MODIFICACION,
            ID_USUARIO_CREACION,
            ID_USUARIO_ULT_MODIF,
            IND_ESTADO
        )
        SELECT DISTINCT
            TRIM(COD_EMPRESA) AS COD_EMPRESA,
            TRIM(DES_EMPRESA) AS DES_EMPRESA,
            SYSDATE AS FEC_CREACION,
            SYSDATE AS FEC_ULT_MODIFICACION,
            0 AS ID_USUARIO_CREACION,
            0 AS ID_USUARIO_ULT_MODIF,
            1 AS IND_ESTADO
        FROM HISTFECI_RECIBOS_MASIVO_TAB
        WHERE TRIM(COD_EMPRESA) IS NOT NULL
        AND TRIM(COD_EMPRESA) NOT IN (SELECT TRIM(COD_EMPRESA) FROM FECI_EMPRESA_CAT);
    END IF;
    ---PARA CATALOGO MONEDAS
    SELECT
        COUNT(DISTINCT TRIM(COD_MONEDA))  INTO CONTADOR_MONEDAS
    FROM HISTFECI_RECIBOS_MASIVO_TAB
    WHERE TRIM(COD_MONEDA) IS NOT NULL
    AND TRIM(COD_MONEDA) NOT IN (SELECT TRIM(COD_MONEDA) FROM FECI_MONEDA_CAT);
    IF CONTADOR_MONEDAS > 0 THEN
       -- Registra monedas que no estan en el catalogo FECI_MONEDA_CAT
       INSERT INTO FECI_MONEDA_CAT (
            COD_MONEDA,
            DES_MONEDA,
            FEC_CREACION,
            FEC_ULT_MODIFICACION,
            ID_USUARIO_CREACION,
            ID_USUARIO_ULT_MODIF,
            IND_ESTADO
        )
        SELECT DISTINCT
            TRIM(COD_MONEDA) AS MONEDA,
            TRIM(DES_MONEDA) AS DES_MONEDA,
            SYSDATE AS FEC_CREACION,
            SYSDATE AS FEC_ULT_MODIFICACION,
            0 AS ID_USUARIO_CREACION,
            0 AS ID_USUARIO_ULT_MODIF,
            1 AS IND_ESTADO
        FROM HISTFECI_RECIBOS_MASIVO_TAB
        WHERE TRIM(COD_MONEDA) IS NOT NULL
        AND TRIM(COD_MONEDA) NOT IN (SELECT TRIM(COD_MONEDA) FROM FECI_MONEDA_CAT);
    END IF;
    ---PARA CATALOGO FECI_PAIS_CAT
    SELECT
        COUNT(DISTINCT TRIM(COD_PAIS))  INTO CONTADOR_PAIS
    FROM HISTFECI_RECIBOS_MASIVO_TAB
    WHERE TRIM(COD_PAIS) IS NOT NULL
    AND TRIM(COD_PAIS) NOT IN (SELECT TRIM(COD_PAIS) FROM FECI_PAIS_CAT);
    IF CONTADOR_PAIS > 0 THEN
       -- Registra monedas que no estan en el catalogo FECI_PAIS_CAT
       INSERT INTO FECI_PAIS_CAT (
            COD_PAIS,
            DES_PAIS,
            FEC_CREACION,
            FEC_ULT_MODIFICACION,
            ID_USUARIO_CREACION,
            ID_USUARIO_ULT_MODIF,
            IND_ESTADO
        )
        SELECT DISTINCT
            TRIM(COD_PAIS) AS COD_PAIS,
            TRIM(DES_PAIS) AS DES_PAIS,
            SYSDATE AS FEC_CREACION,
            SYSDATE AS FEC_ULT_MODIFICACION,
            0 AS ID_USUARIO_CREACION,
            0 AS ID_USUARIO_ULT_MODIF,
            1 AS IND_ESTADO
        FROM HISTFECI_RECIBOS_MASIVO_TAB
        WHERE TRIM(COD_PAIS) IS NOT NULL
        AND TRIM(COD_PAIS) NOT IN (SELECT TRIM(COD_PAIS) FROM FECI_PAIS_CAT);
    END IF;
END;
/
