CREATE OR REPLACE EDITIONABLE PROCEDURE "FECI"."HISTFECI_PROCESA_CLASIFICACIONES_PR" AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
    CONTADOR NUMBER;
BEGIN
  FOR rec IN (SELECT FOLIO_RECIBO, PORCENTAJE_IVA, IMPORTE_ORG, MONTO_BASE_ORG, MONTO_IVA_ORG,
                     IMPORTE_MXN, MONTO_BASE_MXN, MONTO_IVA_MXN, IMPORTE_USD, MONTO_BASE_USD,
                     MONTO_IVA_USD, COD_SEGMENTO, COD_GRUPO_FORECAST, COD_CONCEPTO, COD_REGION,
                     COD_PAIS, DESC_CPS
              FROM HISTFECI_RECIBOS_MASIVO_TAB)
  LOOP
      SELECT COUNT(FOLIO_RECIBO) INTO CONTADOR FROM FECI_CLASIFICACION_TAB
      WHERE FOLIO_RECIBO =  rec.FOLIO_RECIBO;
    -- Insertar en FECI_CLASIFICACION_TAB
    INSERT INTO FECI_CLASIFICACION_TAB (
      FOLIO_RECIBO, TIPO_RECIBO,ORDEN,
      PORCENTAJE_IVA,
      IMPORTE_ORG,
      MONTO_BASE_ORG,
      MONTO_IVA_ORG,
      IMPORTE_MXN,
      MONTO_BASE_MXN,
      MONTO_IVA_MXN,
      IMPORTE_USD,
      MONTO_BASE_USD,
      MONTO_IVA_USD,
      COD_SEGMENTO,
      COD_GRUPO_FORECAST,
      COD_CONCEPTO,
      COD_REGION,
      COD_PAIS,
      DESC_CPS,
      FEC_CREACION,
      FEC_ULT_MODIFICACION,
      ID_USUARIO_CREACION,
      ID_USUARIO_ULT_MODIF,
      IND_ESTADO
    ) VALUES (
      rec.FOLIO_RECIBO, 'BATCH', CONTADOR+1,
      rec.PORCENTAJE_IVA,
      rec.IMPORTE_ORG,
      rec.MONTO_BASE_ORG,
      rec.MONTO_IVA_ORG,
      rec.IMPORTE_MXN,
      rec.MONTO_BASE_MXN,
      rec.MONTO_IVA_MXN,
      rec.IMPORTE_USD,
      rec.MONTO_BASE_USD,
      rec.MONTO_IVA_USD,
      rec.COD_SEGMENTO,
      rec.COD_GRUPO_FORECAST,
      rec.COD_CONCEPTO,
      rec.COD_REGION,
      rec.COD_PAIS,
      rec.DESC_CPS,
      SYSDATE, SYSDATE, 0, 0, 1
    );
  END LOOP;
END;
/
