CREATE OR REPLACE FORCE EDITIONABLE VIEW "PPPT"."PPPCOMPETENCIA" ("IDCOMPETENCIA", "COMPETENCIA", "TIPO", "IDEMPRESA", "INACTIVA", "DEFINICION") AS 
  SELECT IdCompetencia, Competencia, Tipo, IdEmpresa, Inactiva, Definicion
FROM CatCompetencias360;
