CREATE OR REPLACE FORCE EDITIONABLE VIEW "PPPT"."PPPPERFILENTREVISTA" ("IDPERFIL", "IDCOMPETENCIA", "NIVEL") AS 
  SELECT     IdPuesto AS IdPerfil, IdCompetencia, Nivel
FROM         ECPuestoCompetenciaNivel;
