CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABCONF"."CFDICONF_TRG" 
      BEFORE INSERT ON LABCONF.cfdiConf
      FOR EACH ROW
    BEGIN
      SELECT cfdiConf_seq.nextval INTO :new.idConfig FROM dual;
    END;


/
ALTER TRIGGER "LABCONF"."CFDICONF_TRG" ENABLE;
