CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABCONF"."CFDICOMPROBANTEPRO_TRG" 
      BEFORE INSERT ON LABCONF.cfdiComprobantePro
      FOR EACH ROW
    BEGIN
      SELECT cfdiComprobantePro_seq.nextval INTO :new.idComprobantePro FROM dual;
    END;


/
ALTER TRIGGER "LABCONF"."CFDICOMPROBANTEPRO_TRG" ENABLE;
