CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABCONF"."CFDICOMPROBANTEEMP_TRG" 
      BEFORE INSERT ON LABCONF.cfdiComprobanteEmp
      FOR EACH ROW
    BEGIN
      SELECT cfdiComprobanteEmp_seq.nextval INTO :new.idComprobanteEmp FROM dual;
    END;


/
ALTER TRIGGER "LABCONF"."CFDICOMPROBANTEEMP_TRG" ENABLE;
