CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABCONF"."CFDI2COMPROBANTEPRO_SEQ_TR" 
 BEFORE INSERT ON LABCONF.cfdi2ComprobantePro FOR EACH ROW
     WHEN (NEW.idComprobantePro IS NULL) BEGIN
 SELECT LABCONF.cfdi2ComprobantePro_seq.NEXTVAL INTO :NEW.idComprobantePro FROM DUAL;
END;


/
ALTER TRIGGER "LABCONF"."CFDI2COMPROBANTEPRO_SEQ_TR" ENABLE;
