CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABCONF"."DETALLEPARAMETROSID_SEQ_TR" 
 BEFORE INSERT ON LABCONF.DETALLEPARAMETROS FOR EACH ROW
    WHEN (NEW.IdDetalle IS NULL) BEGIN
 SELECT LABCONF.DETALLEPARAMETROSID_SEQ.NEXTVAL INTO :NEW.IdDetalle FROM DUAL;
END;

/
ALTER TRIGGER "LABCONF"."DETALLEPARAMETROSID_SEQ_TR" ENABLE;
