CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABCONF"."ISNCONF02_TRG" 
      BEFORE INSERT ON LABCONF.ISNCONF
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.IDCONFIG IS NULL THEN
      SELECT LABCONF.ISNCONF02_SEQ.nextval INTO :new.IDCONFIG FROM dual;
    END IF;
  END COLUMN_SEQUENCES;
END;


/
ALTER TRIGGER "LABCONF"."ISNCONF02_TRG" ENABLE;
