CREATE OR REPLACE NONEDITIONABLE TRIGGER "LABCONF"."WESEND_TRG" 
  BEFORE INSERT ON LABCONF.WESEND
  FOR EACH ROW
  BEGIN
      SELECT NVL(:new.Id, WESEND_SEQ.nextval) INTO :new.Id FROM dual;
  END;


/
ALTER TRIGGER "LABCONF"."WESEND_TRG" ENABLE;
