CREATE OR REPLACE NONEDITIONABLE PACKAGE "LABPROD"."API_NMLOCENCS" AS
 PROCEDURE SetNmlocenc
 (
    ID_TRANSACCION IN VARCHAR2,
    CEN_KEYCEN VARCHAR2,
    CEN_DESCEN VARCHAR2,
    CEN_REFCON VARCHAR2,
    CEN_NU1AUX VARCHAR2,
    CEN_NU2AUX VARCHAR2,
    CEN_NU3AUX VARCHAR2,
    CEN_NU4AUX VARCHAR2,
    CEN_NU5AUX VARCHAR2,
    CEN_CA1AUX VARCHAR2,
    CEN_CA2AUX VARCHAR2,
    CEN_CA3AUX VARCHAR2,
    CEN_CA4AUX VARCHAR2,
    CEN_CA5AUX VARCHAR2,
    STATUS out varchar2,
    CODE out varchar2,
    MESSAGE out varchar2,
    FECHA out date
 );
 PROCEDURE SetNmlocencEnc
 (
    ID_TRANSACCION IN VARCHAR2,
    CEN_KEYCEN VARCHAR2,
    CEN_DESCEN VARCHAR2,
    CEN_REFCON VARCHAR2,
    CEN_NU1AUX VARCHAR2,
    CEN_NU2AUX VARCHAR2,
    CEN_NU3AUX VARCHAR2,
    CEN_NU4AUX VARCHAR2,
    CEN_NU5AUX VARCHAR2,
    CEN_CA1AUX VARCHAR2,
    CEN_CA2AUX VARCHAR2,
    CEN_CA3AUX VARCHAR2,
    CEN_CA4AUX VARCHAR2,
    CEN_CA5AUX VARCHAR2,
    STATUS out varchar2,
    CODE out varchar2,
    MESSAGE out varchar2,
    FECHA out date
 );
END;
/
CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "LABPROD"."API_NMLOCENCS" AS
PROCEDURE SetNmlocenc
(
ID_TRANSACCION IN VARCHAR2,
CEN_KEYCEN VARCHAR2,
CEN_DESCEN VARCHAR2,
CEN_REFCON VARCHAR2,
CEN_NU1AUX VARCHAR2,
CEN_NU2AUX VARCHAR2,
CEN_NU3AUX VARCHAR2,
CEN_NU4AUX VARCHAR2,
CEN_NU5AUX VARCHAR2,
CEN_CA1AUX VARCHAR2,
CEN_CA2AUX VARCHAR2,
CEN_CA3AUX VARCHAR2,
CEN_CA4AUX VARCHAR2,
CEN_CA5AUX VARCHAR2,
STATUS out varchar2,
CODE out varchar2,
MESSAGE out varchar2,
FECHA out date
) as
centroCosto number;
BEGIN
    FECHA := SYSDATE;
    IF ID_TRANSACCION = '0' THEN
    FECHA := SYSDATE;
    Status := 'OK';
    Code := '0';
    Message := 'PRUEBA DE SERVICIO';
    ELSE
    BEGIN
    Status := 'OK';
    Code := '1';
    Message := 'SE INSERTO EN STAGGIN CON EXITO';
    IF  LENGTH(CEN_KEYCEN) > 16 THEN
        Message:= 'CEN_KEYCEN  LONGITUD MAYOR A 16 ';
        Status := 'ERROR';
        Code := '4';
    END IF;
    IF  LENGTH(CEN_DESCEN) > 40 THEN
        Message:= 'CEN_DESCEN LONGITUD MAYOR A 40 ';
        Status := 'ERROR';
        Code := '4';
    END IF;
    IF Code = '1' THEN
    BEGIN
    Insert into LABPROD.API_NMLOCENC
    (ID_TRANSACCION,CEN_KEYCEN,CEN_DESCEN,CEN_REFCON,CEN_NU1AUX,CEN_NU2AUX,CEN_NU3AUX,CEN_NU4AUX,CEN_NU5AUX,CEN_CA1AUX,CEN_CA2AUX,CEN_CA3AUX,CEN_CA4AUX,CEN_CA5AUX,
    FECHA_INSERT,ESTATUS,CODE,MESSAGE)
    values
    (ID_TRANSACCION,CEN_KEYCEN,CEN_DESCEN,CEN_REFCON,CEN_NU1AUX,CEN_NU2AUX,CEN_NU3AUX,CEN_NU4AUX,CEN_NU5AUX,CEN_CA1AUX,CEN_CA2AUX,CEN_CA3AUX,CEN_CA4AUX,CEN_CA5AUX
    ,FECHA,Status,Code,Message);
    COMMIT;
        EXCEPTION when others then
        Status := 'ERROR';
        Code := SQLCODE;
        Message := SUBSTR(SQLERRM, 1 , 150);
        COMMIT;
    END ;
    select COUNT(*) INTO centroCosto from LABPROD.NMLOCENC WHERE NMLOCENC.CEN_KEYCEN = SetNmlocenc.CEN_KEYCEN;
    IF  centroCosto = 0  THEN
    Begin
        Insert into LABPROD.NMLOCENC
        (CEN_KEYCEN,CEN_DESCEN,CEN_REFCON,CEN_NU1AUX,CEN_NU2AUX,CEN_NU3AUX,CEN_NU4AUX,CEN_NU5AUX,CEN_CA1AUX,CEN_CA2AUX,CEN_CA3AUX,CEN_CA4AUX,CEN_CA5AUX)
        values
        (SetNmlocenc.CEN_KEYCEN,SetNmlocenc.CEN_DESCEN,SetNmlocenc.CEN_REFCON,SetNmlocenc.CEN_NU1AUX,SetNmlocenc.CEN_NU2AUX,SetNmlocenc.CEN_NU3AUX,
        SetNmlocenc.CEN_NU4AUX,SetNmlocenc.CEN_NU5AUX,SetNmlocenc.CEN_CA1AUX,SetNmlocenc.CEN_CA2AUX,SetNmlocenc.CEN_CA3AUX,SetNmlocenc.CEN_CA4AUX,SetNmlocenc.CEN_CA5AUX);
        COMMIT;
        Status := 'OK';
        Code := '3';
        Message := 'Se proceso con exito';
        UPDATE LABPROD.API_NMLOCENC SET ESTATUS=SetNmlocenc.Status,CODE=SetNmlocenc.Code,MESSAGE=SetNmlocenc.Message,FECHA_PROC=SYSDATE WHERE API_NMLOCENC.ID_TRANSACCION =SetNmlocenc.ID_TRANSACCION;
        commit;
    EXCEPTION when others then
        Status := 'ERROR';
        Code := SQLCODE;
        Message := SUBSTR(SQLERRM, 1 , 150);
        UPDATE LABPROD.API_NMLOCENC SET ESTATUS=SetNmlocenc.Status,CODE=SetNmlocenc.Code,MESSAGE=SetNmlocenc.Message,FECHA_PROC=SYSDATE WHERE API_NMLOCENC.ID_TRANSACCION =SetNmlocenc.ID_TRANSACCION;
        COMMIT;
    end;
    END IF;
    if centroCosto > 0 then
        begin
            update LABPROD.NMLOCENC SET
            CEN_KEYCEN =SetNmlocenc.CEN_KEYCEN,
            CEN_DESCEN =SetNmlocenc.CEN_DESCEN,
            CEN_REFCON =SetNmlocenc.CEN_REFCON,
            CEN_NU1AUX =SetNmlocenc.CEN_NU1AUX,
            CEN_NU2AUX =SetNmlocenc.CEN_NU2AUX,
            CEN_NU3AUX =SetNmlocenc.CEN_NU3AUX,
            CEN_NU4AUX =SetNmlocenc.CEN_NU4AUX,
            CEN_NU5AUX =SetNmlocenc.CEN_NU5AUX,
            CEN_CA1AUX =SetNmlocenc.CEN_CA1AUX,
            CEN_CA2AUX =SetNmlocenc.CEN_CA2AUX,
            CEN_CA3AUX =SetNmlocenc.CEN_CA3AUX,
            CEN_CA4AUX =SetNmlocenc.CEN_CA4AUX,
            CEN_CA5AUX =SetNmlocenc.CEN_CA5AUX
            WHERE CEN_KEYCEN =SetNmlocenc.CEN_KEYCEN;
            Status := 'OK';
            Code := '3';
            Message := 'Se proceso con exito';
            UPDATE LABPROD.API_NMLOCENC SET API_NMLOCENC.ESTATUS=SetNmlocenc.Status,API_NMLOCENC.CODE=SetNmlocenc.Code,API_NMLOCENC.MESSAGE=SetNmlocenc.Message,FECHA_PROC=SYSDATE WHERE API_NMLOCENC.ID_TRANSACCION =SetNmlocenc.ID_TRANSACCION;
            commit;
            EXCEPTION when others then
            Status := 'ERROR';
            Code := SQLCODE;
            Message := SUBSTR(SQLERRM, 1 , 150);
            --UPDATE LABPROD.API_NMLOCENC SET API_NMLOCENC.ESTATUS=SetNmlocenc.Status,API_NMLOCENC.CODE=SetNmlocenc.Code,API_NMLOCENC.MESSAGE=SetNmlocenc.Message,FECHA_PROC=SYSDATE WHERE API_NMLOCENC.ID_TRANSACCION = SetNmlocenc.ID_TRANSACCION;
            COMMIT;
        end;
        end if;
        END IF;
    END;
END IF;
END;
PROCEDURE SetNmlocencEnc
(
ID_TRANSACCION IN VARCHAR2,
CEN_KEYCEN VARCHAR2,
CEN_DESCEN VARCHAR2,
CEN_REFCON VARCHAR2,
CEN_NU1AUX VARCHAR2,
CEN_NU2AUX VARCHAR2,
CEN_NU3AUX VARCHAR2,
CEN_NU4AUX VARCHAR2,
CEN_NU5AUX VARCHAR2,
CEN_CA1AUX VARCHAR2,
CEN_CA2AUX VARCHAR2,
CEN_CA3AUX VARCHAR2,
CEN_CA4AUX VARCHAR2,
CEN_CA5AUX VARCHAR2,
STATUS out varchar2,
CODE out varchar2,
MESSAGE out varchar2,
FECHA out date
) as
existe int;
BEGIN
    IF ID_TRANSACCION = '0' THEN
    Status := 'OK';
    Code := '0';
    Message := 'PRUEBA DE SERVICIO';
    ELSE
    Code := '1';
        SELECT COUNT(ID_TRANSACCION) INTO  existe  FROM LABPROD.API_NMLOCENC WHERE API_NMLOCENC.ID_TRANSACCION = SetNmlocencEnc.ID_TRANSACCION;
        if existe != 0  then
                Status := 'ERROR';
                Code := '006';
                Message := 'ID_TRANSACCION DUPLICADO';
        end if;
    if Code ='1' then
        BEGIN
        SetNmlocenc(ID_TRANSACCION, FN_DECODE(CEN_KEYCEN),FN_DECODE(CEN_DESCEN),FN_DECODE(CEN_REFCON),FN_DECODE(CEN_NU1AUX),FN_DECODE(CEN_NU2AUX),FN_DECODE(CEN_NU3AUX),FN_DECODE(CEN_NU4AUX),
        FN_DECODE(CEN_NU5AUX),FN_DECODE(CEN_CA1AUX),FN_DECODE(CEN_CA2AUX),FN_DECODE(CEN_CA3AUX),FN_DECODE(CEN_CA4AUX),FN_DECODE(CEN_CA5AUX),SetNmlocencEnc.STATUS,
        SetNmlocencEnc.CODE,SetNmlocencEnc.MESSAGE,SetNmlocencEnc.FECHA);
    EXCEPTION WHEN OTHERS THEN
    CODE := SQLCODE;
    MESSAGE := SUBSTR(SQLERRM, 1 , 150);
    STATUS :='ERROR';
    END;
    END IF;
    END IF;
END;
END;
/;
