CREATE OR REPLACE NONEDITIONABLE PACKAGE "LABPROD"."INTERFACES" AS
  /* TODO enter package declarations (types, exceptions, methods etc) here */
    PROCEDURE VALIDAEMP(
    --ID_TRANSACCION IN VARCHAR2,
    EMP_TIPMOV IN VARCHAR,
    EMP_SUBMOV IN VARCHAR,
    ESTATUS OUT VARCHAR2,
    CODE OUT VARCHAR2,
    MESSAGE OUT VARCHAR2,
    FECHA OUT DATE
    );
    PROCEDURE VALIDAEMP2(EMP_KEYEMP IN number,EMP_KEYDEP IN VARCHAR2,EMP_KEYPUE IN VARCHAR2,EMP_KEYLOC IN VARCHAR2,
    EMP_KEYCEN IN VARCHAR2,EMP_KEYIMS IN VARCHAR2,EMP_KEYPRO IN VARCHAR2,EMP_MUNEMP IN VARCHAR2,EMP_ENTEMP IN VARCHAR2,EMP_KEYPLZ IN NUMBER,
    ESTATUS OUT VARCHAR2,
    CODE OUT VARCHAR2,
    MESSAGE OUT VARCHAR2,
    FECHA OUT DATE
    );
    PROCEDURE VALIDAMOV(ID_TRANSACCION IN VARCHAR2,
    ESTATUS OUT VARCHAR2,
    CODE OUT VARCHAR2,
    MESSAGE OUT VARCHAR2,
    FECHA OUT DATE
    );
    /*
    PROCEDURE VALIDAEMP2(EMP_KEYEMP IN number,EMP_KEYDEP IN VARCHAR,EMP_KEYPUE IN VARCHAR,EMP_KEYLOC IN VARCHAR,
    EMP_KEYCEN IN VARCHAR,EMP_KEYIMS IN VARCHAR,EMP_KEYPRO IN VARCHAR,EMP_MUNEMP IN VARCHAR,EMP_ENTEMP IN VARCHAR,
    ESTATUS OUT VARCHAR2,
    CODE OUT VARCHAR2,
    MESSAGE OUT VARCHAR2,
    FECHA OUT DATE
    );
    EMP_KEYDEP VARCHAR(16);
    EMP_KEYPUE VARCHAR(16);
    EMP_KEYLOC VARCHAR(16);
    EMP_KEYCEN VARCHAR(16);
    EMP_KEYIMS VARCHAR(5);
    EMP_KEYPRO VARCHAR(10);
    EMP_MUNEMP VARCHAR(6);
    EMP_ENTEMP VARCHAR(6);
    PROCEDURE VALIDATRAY(
    ID_TRANSACCION IN number,
    EMP_KEYEMP IN number,
    FECHA_MOV IN Date,
    EMP_TIPMOV VARCHAR2,
    ESTATUS OUT VARCHAR2,
    CODE OUT VARCHAR2,
    MESSAGE OUT VARCHAR2
    );
    */
END INTERFACES;
/
CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "LABPROD"."INTERFACES" AS
PROCEDURE VALIDAEMP (
    EMP_TIPMOV IN VARCHAR,
    EMP_SUBMOV IN VARCHAR,
    ESTATUS OUT VARCHAR2,
    CODE OUT VARCHAR2,
    MESSAGE OUT VARCHAR2,
    FECHA OUT DATE
    ) AS
    VALIDA NUMBER := 0;
    BEGIN
   /* SELECT API_MOVIMIENTOSPER.EMP_TIPMOV,API_MOVIMIENTOSPER.EMP_SUBMOV INTO VALIDAEMP.EMP_TIPMOV,VALIDAEMP.EMP_SUBMOV
    FROM LABPROD.API_MOVIMIENTOSPER WHERE API_MOVIMIENTOSPER.ID_TRANSACCION = VALIDAEMP.ID_TRANSACCION and  API_MOVIMIENTOSPER.Code = 'OK';
    */
    CODE:='1';
    FECHA := SYSDATE;
    IF VALIDAEMP.EMP_TIPMOV = '1' AND  VALIDAEMP.EMP_SUBMOV = '11' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '1' AND  VALIDAEMP.EMP_SUBMOV = '45' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '1' AND VALIDAEMP.EMP_SUBMOV = '12' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '1' AND VALIDAEMP.EMP_SUBMOV = '13' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '1' AND VALIDAEMP.EMP_SUBMOV = '14' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '1' AND VALIDAEMP.EMP_SUBMOV = '15' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '1' AND VALIDAEMP.EMP_SUBMOV = '16' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '1' AND VALIDAEMP.EMP_SUBMOV = '19' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '1' AND VALIDAEMP.EMP_SUBMOV = 'AL' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND  VALIDAEMP.EMP_SUBMOV = '1' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '2'  THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '3'  THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '4'  THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '5'  THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '7'  THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '8'  THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '9'  THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '10' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '11' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '12' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '13' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '14' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '15' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '16' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '17' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = '21' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '2' AND VALIDAEMP.EMP_SUBMOV = 'AL' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '5' AND VALIDAEMP.EMP_SUBMOV = '21' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '5' AND VALIDAEMP.EMP_SUBMOV = '22' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '5' AND VALIDAEMP.EMP_SUBMOV = '24' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '5' AND VALIDAEMP.EMP_SUBMOV = '26' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '5' AND VALIDAEMP.EMP_SUBMOV = '27' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '5' AND VALIDAEMP.EMP_SUBMOV = '36' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '5' AND VALIDAEMP.EMP_SUBMOV = '53' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '6' AND VALIDAEMP.EMP_SUBMOV = '11' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '6' AND VALIDAEMP.EMP_SUBMOV = '12' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '6' AND VALIDAEMP.EMP_SUBMOV = '13' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '6' AND VALIDAEMP.EMP_SUBMOV = '14' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '6' AND VALIDAEMP.EMP_SUBMOV = '15' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '6' AND VALIDAEMP.EMP_SUBMOV = '16' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '6' AND VALIDAEMP.EMP_SUBMOV = '19' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '6' AND VALIDAEMP.EMP_SUBMOV = '44' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '6' AND VALIDAEMP.EMP_SUBMOV = 'AL' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '35' and VALIDAEMP.EMP_SUBMOV = '35' THEN VALIDA :=1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '36' AND VALIDAEMP.EMP_SUBMOV = '36' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '36' AND VALIDAEMP.EMP_SUBMOV = '22' THEN VALIDA := 1; END IF;
    IF VALIDAEMP.EMP_TIPMOV = '36' AND VALIDAEMP.EMP_SUBMOV = '35' THEN VALIDA := 1; END IF;
    IF VALIDA = 0  THEN
        ESTATUS := 'ERROR';
        CODE := '3';
        MESSAGE := 'El Movimiento No existe: EMP_TIPMOV ['|| VALIDAEMP.EMP_TIPMOV ||'] EMP_SUBMOV ['|| VALIDAEMP.EMP_SUBMOV ||']';
       /* UPDATE LABPROD.API_MOVIMIENTOSPER
        SET API_MOVIMIENTOSPER.MESSAGE = 'El Movimiento No existe: EMP_TIPMOV ['|| VALIDAEMP.EMP_TIPMOV ||'] EMP_SUBMOV ['|| VALIDAEMP.EMP_SUBMOV ||']',
        API_MOVIMIENTOSPER.ESTATUS = '2',
        API_MOVIMIENTOSPER.CODE='ERROR',
        API_MOVIMIENTOSPER.FECHA_PROC = SYSDATE
        WHERE API_MOVIMIENTOSPER.ID_TRANSACCION = VALIDAEMP.ID_TRANSACCION;
        commit;
        */
    END IF;
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ESTATUS := 'ERROR';
        CODE := '3';
        MESSAGE := 'ID_TRANSACCION EN  API_MOVIMIENTOSPER NO EXISTE ';
    WHEN TOO_MANY_ROWS THEN
        ESTATUS := 'ERROR';
        CODE := '3';
        MESSAGE := 'ID_TRANSACCION EN  API_MOVIMIENTOSPER DUPLICADO';
        /*UPDATE  LABPROD.API_MOVIMIENTOSPER SET ESTATUS = '2',CODE = 'ERROR', MESSAGE = 'ID_TRANSACCION EN  API_MOVIMIENTOSPER DUPLICADO'
        WHERE API_MOVIMIENTOSPER.ID_TRANSACCION = VALIDAEMP.ID_TRANSACCION  AND ESTATUS = '1' ;*/
END;
PROCEDURE VALIDAEMP2 (
    EMP_KEYEMP IN number,EMP_KEYDEP IN VARCHAR2,EMP_KEYPUE IN VARCHAR2,EMP_KEYLOC IN VARCHAR2,
    EMP_KEYCEN IN VARCHAR2,EMP_KEYIMS IN VARCHAR2,EMP_KEYPRO IN VARCHAR2,EMP_MUNEMP IN VARCHAR2,EMP_ENTEMP IN VARCHAR2,EMP_KEYPLZ IN NUMBER,
    ESTATUS OUT VARCHAR2,
    CODE OUT VARCHAR2,
    MESSAGE OUT VARCHAR2,
    FECHA OUT DATE
    ) AS
    COUNTEMP number ;
    COUNTDEP number ;
    COUNTPUE number ;
    COUNTLOC number ;
    COUNTCEN number ;
    COUNTIMS number ;
    COUNTPRO number ;
    COUNTEMP number ;
    COUNTMUN number ;
    COUNTENTEMP number;
    COUNTPLZ number;
    band number := 0;
    BEGIN
        ESTATUS := 'OK';
        CODE := '1';
        MESSAGE := 'Pendiente de validar';
        FECHA := SYSDATE;
        BEGIN
        IF VALIDAEMP2.EMP_ENTEMP IS NOT NULL THEN
        select COUNT(*) INTO COUNTENTEMP from LABPROD.GLCOPAMS WHERE GLCOPAMS.PAM_CVESEC = VALIDAEMP2.EMP_ENTEMP AND GLCOPAMS.PAM_KEYPAR='EF';
        IF COUNTENTEMP = 0  THEN
            /*UPDATE LABPROD.API_MOVIMIENTOSPER SET
            ESTATUS = '2',
            CODE = 'ERROR',
            MESSAGE = 'Entidad Federativa [string] no existe',
            API_MOVIMIENTOSPER.FECHA_PROC = SYSDATE
            where api_movimientosper.id_transaccion = validaemp2.ID_TRANSACCION AND API_MOVIMIENTOSPER.Code = 'OK';
            */
            ESTATUS := 'ERROR';
            CODE := '5';
            MESSAGE := 'Entidad Federativa ' || VALIDAEMP2.EMP_ENTEMP  || ' no existe';
            commit;
        END IF;
        END IF;
            EXCEPTION WHEN NO_DATA_FOUND THEN
            BEGIN
                COUNTENTEMP := 0;
            END;
        END;
        BEGIN
        IF VALIDAEMP2.EMP_MUNEMP IS NOT NULL THEN
        select COUNT(*) INTO COUNTMUN from LABPROD.GLCOPAMS WHERE GLCOPAMS.PAM_CVESEC = VALIDAEMP2.EMP_MUNEMP AND GLCOPAMS.PAM_KEYPAR='MU';
        IF COUNTMUN = 0  THEN
            /*UPDATE LABPROD.API_MOVIMIENTOSPER SET
                 ESTATUS = '2',
                CODE = 'ERROR',
                MESSAGE = 'Municipio [string] no existe',
                API_MOVIMIENTOSPER.FECHA_PROC = SYSDATE
                where api_movimientosper.id_transaccion = validaemp2.ID_TRANSACCION AND API_MOVIMIENTOSPER.Code = 'OK';
                */
                ESTATUS := 'ERROR';
                CODE := '5';
                MESSAGE := 'Municipio ' || VALIDAEMP2.EMP_MUNEMP || ' no existe';
                commit;
        END IF;
        END IF;
            EXCEPTION WHEN NO_DATA_FOUND THEN
            BEGIN
            COUNTMUN := 0;
            END;
        END;
        BEGIN
        select COUNT(*) INTO COUNTDEP from LABPROD.NMCODEPS WHERE NMCODEPS.DEP_KEYDEP = VALIDAEMP2.EMP_KEYDEP;
        IF COUNTDEP = 0  THEN
                /* UPDATE LABPROD.API_MOVIMIENTOSPER SET
                ESTATUS = '2',
                CODE = 'ERROR',
                MESSAGE = 'Departamento [string] no existe',
                API_MOVIMIENTOSPER.FECHA_PROC = SYSDATE
                where api_movimientosper.id_transaccion = validaemp2.ID_TRANSACCION AND API_MOVIMIENTOSPER.Code = 'OK';
                */
                ESTATUS := 'ERROR';
                CODE := '5';
                MESSAGE := 'Departamento ' || VALIDAEMP2.EMP_KEYDEP || ' no existe';
                 commit;
        END IF;
                EXCEPTION WHEN NO_DATA_FOUND THEN
                BEGIN
                COUNTDEP := 0;
                DBMS_OUTPUT.PUT_LINE ('NO EXISTE DEPARTAMENTO');
                END;
        END;
        BEGIN
        select COUNT(*) INTO COUNTPUE from LABPROD.NMCOPUES WHERE NMCOPUES.PUE_KEYPUE = VALIDAEMP2.EMP_KEYPUE;
        IF COUNTPUE = 0  THEN
            /*UPDATE API_MOVIMIENTOSPER SET MESSAGE = 'Puesto [string] no existe',
            API_MOVIMIENTOSPER.ESTATUS = '2', API_MOVIMIENTOSPER.CODE='ERROR',
            API_MOVIMIENTOSPER.FECHA_PROC = SYSDATE
            where api_movimientosper.id_transaccion = validaemp2.ID_TRANSACCION AND API_MOVIMIENTOSPER.Code = 'OK';
            */
            ESTATUS := 'ERROR';
            CODE := '5';
            MESSAGE := 'Puesto ' || VALIDAEMP2.EMP_KEYPUE || ' no existe';
            commit;
        END IF;
            EXCEPTION WHEN NO_DATA_FOUND THEN
            BEGIN
                COUNTPUE := 0;
            END;
        END;
        BEGIN
        select COUNT(*) INTO COUNTLOC from NMLOLOCP WHERE NMLOLOCP.LOC_KEYLOC = VALIDAEMP2.EMP_KEYLOC;
        IF COUNTLOC = 0  THEN
            /*UPDATE LABPROD.API_MOVIMIENTOSPER SET MESSAGE = 'LOCALIDAD [string] no existe',
            API_MOVIMIENTOSPER.ESTATUS = '2', API_MOVIMIENTOSPER.CODE='ERROR',
            API_MOVIMIENTOSPER.FECHA_PROC = SYSDATE
            where api_movimientosper.id_transaccion = validaemp2.ID_TRANSACCION AND API_MOVIMIENTOSPER.Code = 'OK';
            */
            ESTATUS := 'ERROR';
            CODE := '5';
            MESSAGE := 'LOCALIDAD ' || VALIDAEMP2.EMP_KEYLOC || ' no existe';
            commit;
        END IF;
        EXCEPTION WHEN NO_DATA_FOUND THEN
        BEGIN
            COUNTLOC := 0;
        END;
    END;
    BEGIN
        select COUNT(*) INTO COUNTCEN from LABPROD.NMLOCENC WHERE NMLOCENC.CEN_KEYCEN = VALIDAEMP2.EMP_KEYCEN;
        IF COUNTCEN = 0  THEN
            /*UPDATE LABPROD.API_MOVIMIENTOSPER SET MESSAGE = 'CENTRO DE COSTOS [string] no existe',
            API_MOVIMIENTOSPER.ESTATUS = '2', API_MOVIMIENTOSPER.CODE='ERROR',
            API_MOVIMIENTOSPER.FECHA_PROC = SYSDATE
            where api_movimientosper.id_transaccion = validaemp2.ID_TRANSACCION AND API_MOVIMIENTOSPER.Code = 'OK';
            */
            ESTATUS := 'ERROR';
            CODE := '5';
            MESSAGE := 'CENTRO DE COSTOS '  || VALIDAEMP2.EMP_KEYCEN || ' no existe';
            commit;
        END IF;
        EXCEPTION WHEN NO_DATA_FOUND THEN
        BEGIN
        COUNTCEN := 0;
        END;
    END;
    BEGIN
        -- mandar el rfcimss para validad....
       -- select COUNT(*) INTO COUNTIMS from LABPROD.NMLOIMSS WHERE NMLOIMSS.IMS_KEYIMS = VALIDAEMP2.EMP_KEYIMS;
        select COUNT(*) INTO COUNTIMS from LABPROD.NMLOIMSS WHERE NMLOIMSS.IMS_RFCIMS = VALIDAEMP2.EMP_KEYIMS;
        IF COUNTIMS = 0  THEN
            /*UPDATE API_MOVIMIENTOSPER SET MESSAGE = 'IMSS [string] no existe',
            API_MOVIMIENTOSPER.ESTATUS = '2', API_MOVIMIENTOSPER.CODE='ERROR' ,
            API_MOVIMIENTOSPER.FECHA_PROC = SYSDATE
            where api_movimientosper.id_transaccion = validaemp2.ID_TRANSACCION AND API_MOVIMIENTOSPER.Code = 'OK';
            */
            ESTATUS := 'ERROR';
            CODE := '5';
            MESSAGE := 'Registro Patronal IMSS ' || VALIDAEMP2.EMP_KEYIMS || ' no existe ';
            commit;
        END IF;
        if COUNTIMS > 1 then
            ESTATUS := 'ERROR';
            CODE := '5';
            MESSAGE := 'RFC en Registro Patronal IMSS ' || VALIDAEMP2.EMP_KEYIMS || ' Duplicado ';
            commit;
        end if;
        EXCEPTION WHEN NO_DATA_FOUND THEN
        BEGIN
            COUNTIMS := 0;
        END;
    END;
      BEGIN
        -- mandar el rfcimss para validad....
       -- select COUNT(*) INTO COUNTIMS from LABPROD.NMLOIMSS WHERE NMLOIMSS.IMS_KEYIMS = VALIDAEMP2.EMP_KEYIMS;
        select COUNT(*) INTO COUNTPLZ from LABPROD.EOCOPLZA WHERE EOCOPLZA.PLZ_KEYPLZ = VALIDAEMP2.EMP_KEYPLZ;
        IF COUNTPLZ = 0  THEN
            /*UPDATE API_MOVIMIENTOSPER SET MESSAGE = 'IMSS [string] no existe',
            API_MOVIMIENTOSPER.ESTATUS = '2', API_MOVIMIENTOSPER.CODE='ERROR' ,
            API_MOVIMIENTOSPER.FECHA_PROC = SYSDATE
            where api_movimientosper.id_transaccion = validaemp2.ID_TRANSACCION AND API_MOVIMIENTOSPER.Code = 'OK';
            */
            ESTATUS := 'ERROR';
            CODE := '5';
            MESSAGE := 'PLAZA ' || VALIDAEMP2.EMP_KEYPLZ || ' no existe';
            commit;
        END IF;
        EXCEPTION WHEN NO_DATA_FOUND THEN
        BEGIN
            COUNTIMS := 0;
        END;
    END;
    BEGIN
        select COUNT(*) INTO COUNTPRO from LABPROD.NMLOPROC WHERE NMLOPROC.PRO_KEYPRO = VALIDAEMP2.EMP_KEYPRO;
        IF COUNTPRO = 0  THEN
            /*UPDATE LABPROD.API_MOVIMIENTOSPER SET MESSAGE = 'Proceso [string] no existe',
            API_MOVIMIENTOSPER.ESTATUS = '2', API_MOVIMIENTOSPER.CODE='ERROR',
            API_MOVIMIENTOSPER.FECHA_PROC = SYSDATE
            where api_movimientosper.id_transaccion = validaemp2.ID_TRANSACCION AND API_MOVIMIENTOSPER.Code = 'OK';
            */
            ESTATUS := 'ERROR';
            CODE := '5';
            MESSAGE := 'Proceso ' || VALIDAEMP2.EMP_KEYPRO || ' no existe';
            commit;
        END IF;
        EXCEPTION WHEN NO_DATA_FOUND THEN
        BEGIN
        COUNTPRO := 0;
        END;
    END;
END;
PROCEDURE VALIDAMOV (
    ID_TRANSACCION IN VARCHAR2,
    ESTATUS OUT VARCHAR2,
    CODE OUT VARCHAR2,
    MESSAGE OUT VARCHAR2,
    FECHA OUT DATE
    ) AS
    keyemp NUMBER;
    tipmov varchar2(2);
    submov varchar2(6);
    cuenta number;
    existe number;
    statusemp varchar2(1);
    BEGIN
    Message := 'Pendiente de validar';
    Estatus := 'OK';
    Code := '1';
    Fecha := SYSDATE;
    SELECT count(*)  into cuenta  FROM LABPROD.API_MOVIMIENTOSPER WHERE API_MOVIMIENTOSPER.ID_TRANSACCION = VALIDAMOV.ID_TRANSACCION AND API_MOVIMIENTOSPER.ESTATUS = '4';
        DBMS_OUTPUT.PUT_LINE ('CUENTA' || CUENTA);
    if cuenta != 0 then
            SELECT  emp_tipmov,emp_submov,emp_keyemp  into tipmov,submov ,keyemp
            FROM LABPROD.API_MOVIMIENTOSPER WHERE API_MOVIMIENTOSPER.ID_TRANSACCION = VALIDAMOV.ID_TRANSACCION AND API_MOVIMIENTOSPER.ESTATUS = '4';
            DBMS_OUTPUT.PUT_LINE ('KEYEMP' || KEYEMP);
            select count(*) into existe  from labprod.nmcoempl where nmcoempl.emp_keyemp = VALIDAMOV.keyemp;
            DBMS_OUTPUT.PUT_LINE ('EXISTE' || EXISTE);
            IF EXISTE = 0 THEN
            -- SI NO EXISTE EL EMPLEADO
                IF tipmov !='1' AND tipmov != '6'  THEN
                    Message:= 'EL EMPLEADO NO EXISTE, DAR DE ALTA PRIMERO';
                    Estatus := 'ERROR';
                    Code := '5';
                END if;
                 IF tipmov = '6' AND submov = '44'   THEN
                    Message:= 'EL EMPLEADO NO EXISTE, DAR DE ALTA PRIMERO';
                    Estatus := 'ERROR';
                    Code := '5';
                END if;
            END IF;
        if existe > 0 then
            select emp_status into statusemp from labprod.nmcoempl where nmcoempl.emp_keyemp = VALIDAMOV.keyemp;
            IF TIPMOV = '1' THEN
                Message:= 'NO SE PUEDE DAR DE ALTA A UN EMPLEADO EXISTENTE';
                Estatus := 'ERROR';
                Code := '5';
            end if;
            IF tipmov = '6' and statusemp  = '1' THEN
                Message:= 'NO SE PUEDE REINGRESAR A UN EMPLEADO ACTIVO';
                Estatus := 'ERROR';
                Code := '5';
            end if;
            IF statusemp  = '2' AND TIPMOV !='6' THEN
                Message:= 'NO SE PUEDE APLICAR MOVIMIENTO A UN EMPLEADO DADO DE BAJA, SOLO REINGRESO';
                Estatus := 'ERROR';
                Code := '5';
            END if;
        end if;
    end if;
    END;
END;
/;
