CREATE OR REPLACE NONEDITIONABLE PACKAGE "LABPROD"."RESPUESTASAP" AS
PROCEDURE REGISTROSPENDIENTES
(
    p_result out SYS_REFCURSOR
);
PROCEDURE ACTUALIZARLABORA
(
    ID_TRANSACCION IN VARCHAR2,
    ESTATUS OUT VARCHAR2,
    CODE OUT VARCHAR2,
    MESSAGE OUT VARCHAR2
);
PROCEDURE INSERTATRAYECTORIA
(
    ID_TRANSACCION IN VARCHAR2,
    EMP_KEYEMP IN number,
    FECHA_MOV IN Date,
    EMP_TIPMOV VARCHAR2
);
PROCEDURE InsertaTray
(
    EMP_KEYEMP IN number,
    FECHA_MOV IN Date,
    EMP_TIPMOV IN VARCHAR2,
    EMP_KEYDEP IN VARCHAR2 ,
	EMP_KEYPUE IN VARCHAR2,
	EMP_KEYCEN IN VARCHAR2,
	EMP_KEYLOC IN VARCHAR2,
	EMP_APEPAT IN VARCHAR2,
	EMP_APEMAT IN VARCHAR2,
	EMP_NOMBRE IN VARCHAR2,
	EMP_DOMEMP IN VARCHAR2,
	EMP_NUMEXT IN VARCHAR2,
	EMP_NUMINT IN VARCHAR2,
	EMP_COLEMP IN VARCHAR2,
	EMP_CIDEMP IN VARCHAR2,
	EMP_MUNEMP IN VARCHAR2,
	EMP_ENTEMP IN VARCHAR2,
	EMP_CODEMP IN VARCHAR2,
	EMP_TELEMP IN VARCHAR2,
	EMP_REGRFC IN VARCHAR2,
	EMP_RECURP IN VARCHAR2,
	EMP_REGIMS IN VARCHAR2,
	EMP_CVESEX IN VARCHAR2,
	EMP_KEYIMS IN VARCHAR2,
	EMP_CVEZON IN NUMBER,
	EMP_KEYPRO IN NUMBER,
	EMP_TIPEMP IN VARCHAR2,
	EMP_TIPSAL IN VARCHAR2,
	EMP_STATUS IN NUMBER,
	EMP_SALHOR IN NUMBER,
	EMP_SALDIA IN NUMBER,
	EMP_SALMES IN NUMBER,
	EMP_FORPAG IN VARCHAR2,
	EMP_CTABAN IN VARCHAR2,
	EMP_CVEBAJ IN VARCHAR2,
	EMP_FECAUX IN DATE,
	EMP_JORLAB IN VARCHAR2,
	EMP_UNIJOR IN NUMBER,
	EMP_CA2AUX IN VARCHAR2,
	EMP_FECVEN IN DATE,
	EMP_FECPLA IN DATE,
	EMP_CA1AUX IN VARCHAR2,
	EMP_FECHA_IMSS IN DATE,
	EMP_SUBMOV IN VARCHAR2,
	EMP_SALINT IN NUMBER,
    KEYPER IN VARCHAR2,
    EMP_SALIVC IN NUMBER,
    EMP_SALINF IN NUMBER,
    EMP_INTSIN IN NUMBER,
    EMP_INFSIN IN NUMBER
);
PROCEDURE ACTUALIZARSALARIO
(
    EMP_KEYEMP IN NUMBER,
    NEW_SALMES IN NUMBER,
    NEW_SALINT IN NUMBER,
    NEW_SALIVC IN NUMBER,
    NEW_SALINF IN NUMBER,
    NEW_INTSIN IN NUMBER,
    NEW_INFSIN IN NUMBER
);
PROCEDURE SetRefCon
(
    WS_PRO_CA4AUX IN VARCHAR2 ,
    WS_PRO_CA5AUX IN VARCHAR2 ,
    WS_EMP_CA2AUX IN VARCHAR2 ,
    WS_EMP_TIPEMP IN VARCHAR2 ,
    WS_EMP_CA4AUX OUT VARCHAR2,
    WS_EMP_REFCON OUT VARCHAR2
);
PROCEDURE ClaveBanco
(
    EMP_FORPAG IN number,
    EMP_CVEBAN OUT VARCHAR
);
PROCEDURE CAMBIOPROCESO
(
    API_KEYPRO IN NUMBER,
    API_KEYEMP IN NUMBER,
    API_FECMOV DATE,
    API_PERING VARCHAR,
    EMP_KEYPRO IN NUMBER,
    FECHAING OUT DATE,
    PERING OUT VARCHAR
);
END RESPUESTASAP;
/
CREATE OR REPLACE NONEDITIONABLE PACKAGE BODY "LABPROD"."RESPUESTASAP" AS
    PROCEDURE REGISTROSPENDIENTES(p_result out SYS_REFCURSOR) AS
    BEGIN
        OPEN p_result FOR
        SELECT ID_TRANSACCION
        FROM LABPROD.API_MOVIMIENTOSPER
        WHERE ESTATUS=1 ORDER BY FECHA_INSERT ASC;
    END;
    PROCEDURE ACTUALIZARLABORA
    (
    ID_TRANSACCION IN VARCHAR2,
    ESTATUS OUT VARCHAR2,
    CODE OUT VARCHAR2,
    MESSAGE OUT VARCHAR2
    ) AS
    BAND number;
    BAND2 number;
    BAND3 number;
    -- EMP_KEYEMP NUMBER;
    FECHA_MOV  DATE;
    --EMP_TIPMOV VARCHAR2(2);
    NMCOEMP_KEYEMP NUMBER;
    NMCOEMP_KEYDEP VARCHAR2(16);
    NMCOEMP_KEYPUE VARCHAR2(16);
    NMCOEMP_KEYIMS VARCHAR2(5);
    NMCOEMP_KEYCAT VARCHAR2(16);
    NMCOEMP_KEYCEN VARCHAR2(16);
    NMCOEMP_SALDIA NUMBER;
    NMCOEMP_SALHOR NUMBER;
    NMCOEMP_SALMES NUMBER;
    NMCOEMP_SALINT NUMBER;
    NMCOEMP_SALIVC NUMBER;
    NMCOEMP_SALINF NUMBER;
    NMCOEMP_INTSIN NUMBER;
    NMCOEMP_INFSIN NUMBER;
    NMCOEMP_KEYPRO NUMBER;
    NMCOEMP_JORLAB VARCHAR2(1);
    NMCOEMP_UNIJOR NUMBER;
    NMCOEMP_CA1AUX VARCHAR2(10);
    NMCOEMP_CA2AUX VARCHAR2(10);
    NMCOEMP_FECMOD DATE;
    NMCOEMP_HORMOD VARCHAR2(8);
    NMCOEMP_KEYLOC VARCHAR(16);
    NMCOEMP_FECING DATE;
    NMCOEMP_PERING VARCHAR(7);
    EMP_KEYEMP NUMBER;
    EMP_KEYDEP VARCHAR2(16) ;
    EMP_KEYPUE VARCHAR2(16) ;
    EMP_KEYCEN VARCHAR2(16) ;
    EMP_KEYLOC VARCHAR2(16) ;
    EMP_APEPAT VARCHAR2(90) ;
    EMP_APEMAT VARCHAR2(90) ;
    EMP_NOMBRE VARCHAR2(90) ;
    EMP_DOMEMP VARCHAR2(100);
    EMP_NUMEXT VARCHAR2(10);
    EMP_NUMINT VARCHAR2(10);
    EMP_COLEMP VARCHAR2(100);
    EMP_CIDEMP VARCHAR2(255);
    EMP_MUNEMP VARCHAR2(6);
    EMP_ENTEMP VARCHAR2(2);
    EMP_CODEMP VARCHAR2(5);
    EMP_TELEMP VARCHAR2(60);
    EMP_REGRFC VARCHAR2(13);
    EMP_RECURP VARCHAR2(18);
    EMP_REGIMS VARCHAR2(12);
    EMP_CVESEX VARCHAR2(1);
    EMP_KEYIMS VARCHAR2(5);
    EMP_RFCIMS VARCHAR2(16);
    EMP_CVEZON NUMBER;
    EMP_KEYPRO NUMBER;
    EMP_TIPEMP VARCHAR2(6);
    EMP_TIPSAL VARCHAR2(1);
    EMP_STATUS NUMBER;
    EMP_SALHOR NUMBER;
    EMP_SALDIA NUMBER;
    EMP_SALMES NUMBER;
    EMP_FORPAG VARCHAR2(2);
    EMP_CTABAN VARCHAR2(18);
    EMP_CVEBAJ VARCHAR2(4);
    EMP_FECAUX DATE;
    EMP_JORLAB VARCHAR2(1);
    EMP_UNIJOR FLOAT(126);
    EMP_CA2AUX VARCHAR2(10);
    EMP_FECVEN DATE;
    EMP_FECPLA DATE;
    EMP_CA1AUX VARCHAR2(10);
    EMP_FECHA_MOV DATE;
    EMP_FECHA_IMSS DATE;
    EMP_TIPMOV VARCHAR2(2);
    EMP_SUBMOV VARCHAR2(6);
    EMP_SALINT NUMBER;
    EMP_SALIVC NUMBER(12);
    EMP_SALINF NUMBER(12);
    EMP_INTSIN NUMBER(12);
    EMP_INFSIN NUMBER(12);
    EMP_KEYPLZ NUMBER(38);
    KEYPER VARCHAR2(7);
    BANDPERIODO NUMBER;
    PERIODO VARCHAR2(7);
    PERIODO2 VARCHAR2(7);
    PERIODOFIN VARCHAR2(7);
    PERIODOMOD VARCHAR2(7);
    DIA NUMBER;
    HORA NUMBER;
    PERIODOTRAY VARCHAR2(7);
    FECHAREINGRESO DATE := null;
    FECHAAUMENTO DATE := null;
    BANDBAN NUMBER;
    ws_pro_ca4aux VARCHAR2(10);
    ws_pro_ca5aux VARCHAR2(10);
    ws_emp_ca2aux VARCHAR2(6);
    ws_emp_tipemp VARCHAR2(6);
    ws_emp_ca4aux VARCHAR2(6);
    ws_emp_refcon VARCHAR2(6);
    EMP_CVEBAN    VARCHAR2(7);
    CVEBAJ VARCHAR2(4);
    fecmod varchar(20);
    hormod varchar (10);
    FECHATRAY DATE;
    TEMPMOV VARCHAR2(2);
    TEMPSUBMOV VARCHAR2(6);
    FECING DATE ;
    --COUNTIMS NUMBER;
    BEGIN
        BEGIN
        SELECT
        emp_keyemp,emp_keydep,emp_keypue,emp_keycen,emp_keyloc,emp_apepat,emp_apemat,emp_nombre,emp_domemp,emp_numext,
        emp_numint,emp_colemp,emp_cidemp,emp_munemp,emp_entemp,emp_codemp,emp_telemp,emp_regrfc,emp_recurp,emp_regims,
        emp_cvesex,emp_keyims,emp_cvezon,emp_keypro,emp_tipemp,emp_tipsal,emp_status,emp_salhor,emp_saldia,emp_salmes,
        emp_forpag,emp_ctaban,emp_cvebaj,emp_fecaux,emp_jorlab,emp_unijor,emp_ca2aux,emp_fecven,emp_fecpla,emp_ca1aux,
        emp_fecha_mov,emp_fecha_imss,emp_tipmov,emp_submov,emp_salint,keyper,emp_fecha_mov fecha_mov,code,
        emp_salivc,emp_salinf,emp_intsin,emp_infsin,emp_keyplz
        INTO
        ACTUALIZARLABORA.EMP_KEYEMP,ACTUALIZARLABORA.EMP_KEYDEP,ACTUALIZARLABORA.EMP_KEYPUE,ACTUALIZARLABORA.EMP_KEYCEN,ACTUALIZARLABORA.EMP_KEYLOC,
        ACTUALIZARLABORA.EMP_APEPAT ,ACTUALIZARLABORA.EMP_APEMAT,ACTUALIZARLABORA.EMP_NOMBRE,ACTUALIZARLABORA.EMP_DOMEMP,ACTUALIZARLABORA.EMP_NUMEXT,
        ACTUALIZARLABORA.EMP_NUMINT,ACTUALIZARLABORA.EMP_COLEMP,ACTUALIZARLABORA.EMP_CIDEMP,ACTUALIZARLABORA.EMP_MUNEMP,ACTUALIZARLABORA.EMP_ENTEMP,
        ACTUALIZARLABORA.EMP_CODEMP,ACTUALIZARLABORA.EMP_TELEMP,ACTUALIZARLABORA.EMP_REGRFC,ACTUALIZARLABORA.EMP_RECURP,ACTUALIZARLABORA.EMP_REGIMS,
        ACTUALIZARLABORA.EMP_CVESEX,ACTUALIZARLABORA.EMP_RFCIMS,ACTUALIZARLABORA.EMP_CVEZON ,ACTUALIZARLABORA.EMP_KEYPRO,ACTUALIZARLABORA.EMP_TIPEMP,
        ACTUALIZARLABORA.EMP_TIPSAL,ACTUALIZARLABORA.EMP_STATUS,ACTUALIZARLABORA.EMP_SALHOR,ACTUALIZARLABORA.EMP_SALDIA,ACTUALIZARLABORA.EMP_SALMES,
        ACTUALIZARLABORA.EMP_FORPAG,ACTUALIZARLABORA.EMP_CTABAN,ACTUALIZARLABORA.EMP_CVEBAJ,ACTUALIZARLABORA.EMP_FECAUX,ACTUALIZARLABORA.EMP_JORLAB,
        ACTUALIZARLABORA.EMP_UNIJOR,ACTUALIZARLABORA.EMP_CA2AUX,ACTUALIZARLABORA.EMP_FECVEN ,ACTUALIZARLABORA.EMP_FECPLA,ACTUALIZARLABORA.EMP_CA1AUX,
        ACTUALIZARLABORA.EMP_FECHA_MOV,ACTUALIZARLABORA.EMP_FECHA_IMSS,ACTUALIZARLABORA.EMP_TIPMOV,ACTUALIZARLABORA.EMP_SUBMOV,
        ACTUALIZARLABORA.EMP_SALINT,ACTUALIZARLABORA.KEYPER,FECHA_MOV,CODE,
        ACTUALIZARLABORA.EMP_SALIVC, ACTUALIZARLABORA.EMP_SALINF,ACTUALIZARLABORA.EMP_INTSIN,ACTUALIZARLABORA.EMP_INFSIN,ACTUALIZARLABORA.EMP_KEYPLZ
        from LABPROD.API_MOVIMIENTOSPER WHERE API_MOVIMIENTOSPER.ID_TRANSACCION = ACTUALIZARLABORA.ID_TRANSACCION AND API_MOVIMIENTOSPER.CODE = 'OK';
        PERIODO := KEYPER;
        DIA :=  (ACTUALIZARLABORA.EMP_SALMES / 30);
        HORA := (DIA / ACTUALIZARLABORA.EMP_UNIJOR);
        CODE :='OK';
      --SELECT IMS_KEYIMS INTO ACTUALIZARLABORA.EMP_KEYIMS FROM LABPROD.NMLOIMSS WHERE ACTUALIZARLABORA.EMP_RFCIMS = NMLOIMSS.IMS_RFCIMS;
        BEGIN
            SELECT IMS_KEYIMS INTO ACTUALIZARLABORA.EMP_KEYIMS FROM LABPROD.NMLOIMSS WHERE ACTUALIZARLABORA.EMP_RFCIMS = NMLOIMSS.IMS_RFCIMS;
            EXCEPTION  WHEN TOO_MANY_ROWS THEN
             BEGIN
                MESSAGE :='REGISTRO PATRONAL DUPLICADO RFC '|| ACTUALIZARLABORA.EMP_RFCIMS;
                ESTATUS:='5';
                CODE :='ERROR';
                UPDATE LABPROD.API_MOVIMIENTOSPER SET ESTATUS =ACTUALIZARLABORA.ESTATUS,CODE=ACTUALIZARLABORA.CODE,MESSAGE=ACTUALIZARLABORA.MESSAGE
                WHERE LABPROD.API_MOVIMIENTOSPER.ID_TRANSACCION = ACTUALIZARLABORA.ID_TRANSACCION;
                COMMIT;
            END;
        END ;
        select COUNT(*) into BAND2 from LABPROD.NMCOEMPL WHERE NMCOEMPL.EMP_KEYEMP=ACTUALIZARLABORA.EMP_KEYEMP;
        BEGIN
           select COUNT(*) into BAND3 from LABPROD.API_MOVIMIENTOSPER  WHERE API_MOVIMIENTOSPER.ID_TRANSACCION = ACTUALIZARLABORA.ID_TRANSACCION AND API_MOVIMIENTOSPER.ESTATUS='1' AND code = 'OK';
            EXCEPTION  WHEN TOO_MANY_ROWS THEN
             BEGIN
                UPDATE LABPROD.API_MOVIMIENTOSPER SET ESTATUS = '2',CODE='ERROR',MESSAGE='ID_TRANSACCION DUPLICADO'
                WHERE LABPROD.API_MOVIMIENTOSPER.ID_TRANSACCION = ACTUALIZARLABORA.ID_TRANSACCION AND ESTATUS = '1' AND CODE='OK' ;
                COMMIT;
                ESTATUS:='2';
                CODE :='ERROR';
                MESSAGE :='ID_TRANSACCION DUPLICADO';
            END;
        END ;
    END;
    IF CODE != 'ERROR' THEN
        CVEBAJ := ACTUALIZARLABORA.EMP_CVEBAJ;
        --MODIFICADO EHC
        if  ACTUALIZARLABORA.EMP_TIPMOV = '2' then
            ACTUALIZARLABORA.EMP_CVEBAJ := EMP_SUBMOV;
            ACTUALIZARLABORA.EMP_SUBMOV := CVEBAJ;
            UPDATE LABPROD.SCCOBAJA SET baj_status = '2'
            WHERE baj_keyemp = ACTUALIZARLABORA.EMP_KEYEMP
              AND baj_fecbaj =  ACTUALIZARLABORA.EMP_FECHA_MOV
              AND baj_status = '1';
        end if;
        -- TERMINA MODIFICADO EHC
        --DBMS_OUTPUT.PUT_LINE ('EMP_TIPMOV' || EMP_TIPMOV );
        IF  EMP_TIPMOV = '2' OR EMP_TIPMOV = '36' or EMP_TIPMOV = '35' OR EMP_TIPMOV = '6'   THEN
            FECHATRAY :=ACTUALIZARLABORA.EMP_FECHA_MOV;
        ELSE
            FECHATRAY :=ACTUALIZARLABORA.EMP_FECHA_IMSS;
        END IF;
        TEMPMOV := EMP_TIPMOV  ;
        IF ACTUALIZARLABORA.EMP_TIPMOV = '6' and ACTUALIZARLABORA.EMP_SUBMOV = '15' THEN
            ACTUALIZARLABORA.EMP_TIPMOV := '1';
            ACTUALIZARLABORA.EMP_SUBMOV := ACTUALIZARLABORA.EMP_SUBMOV;
        END IF;
        IF ACTUALIZARLABORA.EMP_TIPMOV != '36' and  ACTUALIZARLABORA.EMP_TIPMOV != '35' AND ACTUALIZARLABORA.EMP_SUBMOV != '44' THEN
            DBMS_OUTPUT.PUT_LINE ('ENTRA PARA INSERTAR EN NMLOTRAY');
            BEGIN
            InsertaTray
            (
            ACTUALIZARLABORA.EMP_KEYEMP ,ACTUALIZARLABORA.FECHATRAY ,ACTUALIZARLABORA.EMP_TIPMOV ,ACTUALIZARLABORA.EMP_KEYDEP ,ACTUALIZARLABORA.EMP_KEYPUE ,ACTUALIZARLABORA.EMP_KEYCEN ,
            ACTUALIZARLABORA.EMP_KEYLOC ,ACTUALIZARLABORA.EMP_APEPAT ,ACTUALIZARLABORA.EMP_APEMAT ,ACTUALIZARLABORA.EMP_NOMBRE ,ACTUALIZARLABORA.EMP_DOMEMP ,ACTUALIZARLABORA.EMP_NUMEXT ,
            ACTUALIZARLABORA.EMP_NUMINT ,ACTUALIZARLABORA.EMP_COLEMP ,ACTUALIZARLABORA.EMP_CIDEMP ,ACTUALIZARLABORA.EMP_MUNEMP ,ACTUALIZARLABORA.EMP_ENTEMP ,ACTUALIZARLABORA.EMP_CODEMP ,
            ACTUALIZARLABORA.EMP_TELEMP ,ACTUALIZARLABORA.EMP_REGRFC ,ACTUALIZARLABORA.EMP_RECURP ,ACTUALIZARLABORA.EMP_REGIMS ,ACTUALIZARLABORA.EMP_CVESEX ,ACTUALIZARLABORA.EMP_KEYIMS ,
            ACTUALIZARLABORA.EMP_CVEZON ,ACTUALIZARLABORA.EMP_KEYPRO ,ACTUALIZARLABORA.EMP_TIPEMP ,ACTUALIZARLABORA.EMP_TIPSAL ,ACTUALIZARLABORA.EMP_STATUS ,
            ACTUALIZARLABORA.EMP_SALHOR ,ACTUALIZARLABORA.DIA ,ACTUALIZARLABORA.EMP_SALMES ,ACTUALIZARLABORA.EMP_FORPAG ,ACTUALIZARLABORA.EMP_CTABAN ,ACTUALIZARLABORA.EMP_CVEBAJ ,
            ACTUALIZARLABORA.EMP_FECAUX ,ACTUALIZARLABORA.EMP_JORLAB ,ACTUALIZARLABORA.EMP_UNIJOR ,ACTUALIZARLABORA.EMP_CA2AUX ,
            ACTUALIZARLABORA.EMP_FECVEN ,ACTUALIZARLABORA.EMP_FECPLA ,ACTUALIZARLABORA.EMP_CA1AUX ,ACTUALIZARLABORA.EMP_FECHA_IMSS ,ACTUALIZARLABORA.EMP_SUBMOV ,
            ACTUALIZARLABORA.EMP_SALINT ,ACTUALIZARLABORA.KEYPER,
            ACTUALIZARLABORA.EMP_SALIVC,ACTUALIZARLABORA.EMP_SALINF,ACTUALIZARLABORA.EMP_INTSIN,ACTUALIZARLABORA.EMP_INFSIN
            ) ;
            COMMIT;
                EXCEPTION  WHEN TOO_MANY_ROWS THEN
                BEGIN
                    ESTATUS:='2';
                    CODE :='ERROR';
                    MESSAGE := SUBSTR(SQLERRM, 1, 149);
                END;
            END;
        END IF;
        IF  ACTUALIZARLABORA.EMP_TIPMOV != '1' AND ACTUALIZARLABORA.EMP_TIPMOV != '6' AND ACTUALIZARLABORA.EMP_TIPMOV != '2'  AND  BAND2 != 0  THEN
            SELECT NMCOEMPL.EMP_KEYEMP,NMCOEMPL.EMP_KEYDEP,NMCOEMPL.EMP_KEYPUE,NMCOEMPL.EMP_KEYIMS,NMCOEMPL.EMP_KEYPRO,
            EMP_KEYCEN,EMP_SALDIA,EMP_SALMES,EMP_SALINT,EMP_KEYLOC,EMP_JORLAB,EMP_UNIJOR,EMP_FECING,EMP_PERING
            INTO NMCOEMP_KEYEMP,NMCOEMP_KEYDEP,NMCOEMP_KEYPUE,NMCOEMP_KEYIMS,NMCOEMP_KEYPRO,
            NMCOEMP_KEYCEN,NMCOEMP_SALDIA,NMCOEMP_SALMES,NMCOEMP_SALINT,NMCOEMP_KEYLOC,NMCOEMP_JORLAB,NMCOEMP_UNIJOR,NMCOEMP_FECING,NMCOEMP_PERING
            FROM LABPROD.NMCOEMPL WHERE NMCOEMPL.EMP_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP;
            IF ACTUALIZARLABORA.EMP_KEYDEP != ACTUALIZARLABORA.NMCOEMP_KEYDEP THEN
                InsertaTray
                (
                EMP_KEYEMP ,FECHATRAY ,'8',EMP_KEYDEP ,EMP_KEYPUE ,EMP_KEYCEN , EMP_KEYLOC , EMP_APEPAT , EMP_APEMAT , EMP_NOMBRE , EMP_DOMEMP , EMP_NUMEXT ,
                EMP_NUMINT , EMP_COLEMP , EMP_CIDEMP , EMP_MUNEMP , EMP_ENTEMP , EMP_CODEMP , EMP_TELEMP , EMP_REGRFC , EMP_RECURP , EMP_REGIMS , EMP_CVESEX , EMP_KEYIMS ,
                EMP_CVEZON ,EMP_KEYPRO ,EMP_TIPEMP , EMP_TIPSAL , EMP_STATUS ,EMP_SALHOR , ROUND(DIA,4) , EMP_SALMES , EMP_FORPAG , EMP_CTABAN ,EMP_CVEBAJ ,
                EMP_FECAUX ,EMP_JORLAB , EMP_UNIJOR ,EMP_CA2AUX , EMP_FECVEN ,EMP_FECPLA , EMP_CA1AUX , EMP_FECHA_IMSS , EMP_SUBMOV , EMP_SALINT ,KEYPER,
                ACTUALIZARLABORA.EMP_SALIVC,ACTUALIZARLABORA.EMP_SALINF,ACTUALIZARLABORA.EMP_INTSIN,ACTUALIZARLABORA.EMP_INFSIN
                ) ;
                COMMIT;
            END IF;
            IF  ACTUALIZARLABORA.EMP_KEYPUE != ACTUALIZARLABORA.NMCOEMP_KEYPUE THEN
                InsertaTray
                (
                EMP_KEYEMP ,FECHATRAY ,'9' ,EMP_KEYDEP ,EMP_KEYPUE ,EMP_KEYCEN , EMP_KEYLOC , EMP_APEPAT , EMP_APEMAT , EMP_NOMBRE , EMP_DOMEMP , EMP_NUMEXT ,
                EMP_NUMINT , EMP_COLEMP , EMP_CIDEMP , EMP_MUNEMP , EMP_ENTEMP , EMP_CODEMP , EMP_TELEMP , EMP_REGRFC , EMP_RECURP , EMP_REGIMS , EMP_CVESEX , EMP_KEYIMS ,
                EMP_CVEZON ,EMP_KEYPRO ,EMP_TIPEMP , EMP_TIPSAL , EMP_STATUS ,EMP_SALHOR , ROUND(DIA,4) , EMP_SALMES , EMP_FORPAG , EMP_CTABAN ,EMP_CVEBAJ ,
                EMP_FECAUX ,EMP_JORLAB , EMP_UNIJOR ,EMP_CA2AUX , EMP_FECVEN ,EMP_FECPLA , EMP_CA1AUX , EMP_FECHA_IMSS , EMP_SUBMOV , EMP_SALINT ,KEYPER,
                ACTUALIZARLABORA.EMP_SALIVC,ACTUALIZARLABORA.EMP_SALINF,ACTUALIZARLABORA.EMP_INTSIN,ACTUALIZARLABORA.EMP_INFSIN
                ) ;
                COMMIT;
            END IF;
            IF ACTUALIZARLABORA.EMP_KEYPRO != ACTUALIZARLABORA.NMCOEMP_KEYPRO THEN
                CAMBIOPROCESO(ACTUALIZARLABORA.EMP_KEYPRO ,ACTUALIZARLABORA.EMP_KEYEMP ,ACTUALIZARLABORA.EMP_FECHA_MOV ,PERIODO,NMCOEMP_KEYPRO, NMCOEMP_FECING,NMCOEMP_PERING);
                InsertaTray
                (
                EMP_KEYEMP ,FECHATRAY ,'11' ,EMP_KEYDEP ,EMP_KEYPUE ,EMP_KEYCEN , EMP_KEYLOC , EMP_APEPAT , EMP_APEMAT , EMP_NOMBRE , EMP_DOMEMP , EMP_NUMEXT ,
                EMP_NUMINT , EMP_COLEMP , EMP_CIDEMP , EMP_MUNEMP , EMP_ENTEMP , EMP_CODEMP , EMP_TELEMP , EMP_REGRFC , EMP_RECURP , EMP_REGIMS , EMP_CVESEX , EMP_KEYIMS ,
                EMP_CVEZON ,EMP_KEYPRO ,EMP_TIPEMP , EMP_TIPSAL , EMP_STATUS ,EMP_SALHOR , ROUND(DIA,4) , EMP_SALMES , EMP_FORPAG , EMP_CTABAN ,EMP_CVEBAJ ,
                EMP_FECAUX ,EMP_JORLAB , EMP_UNIJOR ,EMP_CA2AUX , EMP_FECVEN ,EMP_FECPLA , EMP_CA1AUX , EMP_FECHA_IMSS , EMP_SUBMOV , EMP_SALINT ,KEYPER,
                ACTUALIZARLABORA.EMP_SALIVC,ACTUALIZARLABORA.EMP_SALINF,ACTUALIZARLABORA.EMP_INTSIN,ACTUALIZARLABORA.EMP_INFSIN
                ) ;
                COMMIT;
                InsertaTray
                (
                EMP_KEYEMP , FECHATRAY-1 ,'20' ,ACTUALIZARLABORA.NMCOEMP_KEYDEP ,NMCOEMP_KEYPUE,NMCOEMP_KEYCEN , NMCOEMP_KEYLOC , EMP_APEPAT , EMP_APEMAT , EMP_NOMBRE , EMP_DOMEMP , EMP_NUMEXT ,
                EMP_NUMINT , EMP_COLEMP , EMP_CIDEMP , EMP_MUNEMP , EMP_ENTEMP , EMP_CODEMP , EMP_TELEMP , EMP_REGRFC , EMP_RECURP , EMP_REGIMS , EMP_CVESEX , ACTUALIZARLABORA.NMCOEMP_KEYIMS ,
                EMP_CVEZON ,ACTUALIZARLABORA.NMCOEMP_KEYPRO ,EMP_TIPEMP , EMP_TIPSAL , EMP_STATUS ,EMP_SALHOR , ROUND(ACTUALIZARLABORA.NMCOEMP_SALDIA,4) ,ACTUALIZARLABORA.NMCOEMP_SALMES , EMP_FORPAG , EMP_CTABAN ,EMP_CVEBAJ ,
                EMP_FECAUX ,ACTUALIZARLABORA.NMCOEMP_JORLAB , ACTUALIZARLABORA.NMCOEMP_UNIJOR ,EMP_CA2AUX , EMP_FECVEN ,EMP_FECPLA , EMP_CA1AUX , EMP_FECHA_IMSS , EMP_SUBMOV , NMCOEMP_SALINT ,KEYPER,
                ACTUALIZARLABORA.EMP_SALIVC,ACTUALIZARLABORA.EMP_SALINF,ACTUALIZARLABORA.EMP_INTSIN,ACTUALIZARLABORA.EMP_INFSIN);
                COMMIT;
            END IF;
            IF  ACTUALIZARLABORA.EMP_KEYIMS != ACTUALIZARLABORA.NMCOEMP_KEYIMS THEN
                InsertaTray
                (
                EMP_KEYEMP ,FECHATRAY ,'3' ,EMP_KEYDEP ,EMP_KEYPUE ,EMP_KEYCEN , EMP_KEYLOC , EMP_APEPAT , EMP_APEMAT , EMP_NOMBRE , EMP_DOMEMP , EMP_NUMEXT ,
                EMP_NUMINT , EMP_COLEMP , EMP_CIDEMP , EMP_MUNEMP , EMP_ENTEMP , EMP_CODEMP , EMP_TELEMP , EMP_REGRFC , EMP_RECURP , EMP_REGIMS , EMP_CVESEX , EMP_KEYIMS ,
                EMP_CVEZON ,EMP_KEYPRO ,EMP_TIPEMP , EMP_TIPSAL , EMP_STATUS ,EMP_SALHOR , ROUND(DIA,4) , EMP_SALMES , EMP_FORPAG , EMP_CTABAN ,EMP_CVEBAJ ,
                EMP_FECAUX ,EMP_JORLAB , EMP_UNIJOR ,EMP_CA2AUX , EMP_FECVEN ,EMP_FECPLA , EMP_CA1AUX , EMP_FECHA_IMSS , EMP_SUBMOV , EMP_SALINT ,KEYPER,
                ACTUALIZARLABORA.EMP_SALIVC,ACTUALIZARLABORA.EMP_SALINF,ACTUALIZARLABORA.EMP_INTSIN,ACTUALIZARLABORA.EMP_INFSIN
                ) ;
                COMMIT;
                InsertaTray
                (
                EMP_KEYEMP , FECHATRAY-1 ,'4' ,ACTUALIZARLABORA.NMCOEMP_KEYDEP ,NMCOEMP_KEYPUE,NMCOEMP_KEYCEN , NMCOEMP_KEYLOC , EMP_APEPAT , EMP_APEMAT , EMP_NOMBRE , EMP_DOMEMP , EMP_NUMEXT ,
                EMP_NUMINT , EMP_COLEMP , EMP_CIDEMP , EMP_MUNEMP , EMP_ENTEMP , EMP_CODEMP , EMP_TELEMP , EMP_REGRFC , EMP_RECURP , EMP_REGIMS , EMP_CVESEX , ACTUALIZARLABORA.NMCOEMP_KEYIMS ,
                EMP_CVEZON ,ACTUALIZARLABORA.NMCOEMP_KEYPRO ,EMP_TIPEMP , EMP_TIPSAL , EMP_STATUS ,EMP_SALHOR , ROUND(ACTUALIZARLABORA.NMCOEMP_SALDIA,4) ,ACTUALIZARLABORA.NMCOEMP_SALMES , EMP_FORPAG , EMP_CTABAN ,EMP_CVEBAJ ,
                EMP_FECAUX ,ACTUALIZARLABORA.NMCOEMP_JORLAB , ACTUALIZARLABORA.NMCOEMP_UNIJOR ,EMP_CA2AUX , EMP_FECVEN ,EMP_FECPLA , EMP_CA1AUX , EMP_FECHA_IMSS , EMP_SUBMOV , NMCOEMP_SALINT ,KEYPER,
                ACTUALIZARLABORA.EMP_SALIVC,ACTUALIZARLABORA.EMP_SALINF,ACTUALIZARLABORA.EMP_INTSIN,ACTUALIZARLABORA.EMP_INFSIN);
                COMMIT;
            END IF;
        END IF;
        BEGIN
        PERIODOTRAY := PERIODO;
        PERIODOMOD := PERIODO;
        PERIODOFIN  := PERIODO;
        IF  EMP_TIPMOV != '2' THEN
            ACTUALIZARLABORA.FECHA_MOV := NULL;
            PERIODOFIN := NULL;
            PERIODOMOD := NULL;
        END IF;
        ClaveBanco(ACTUALIZARLABORA.EMP_FORPAG ,ACTUALIZARLABORA.EMP_CVEBAN);
        IF BAND2 = 0 THEN
            INSERT INTO LABPROD.nmcoempl (
            emp_keyemp,emp_keydep,emp_keypue,emp_keycen,emp_keyloc,emp_nomemp,
            emp_domemp,emp_colemp,emp_cidemp,emp_munemp,emp_entemp,
            emp_codemp,emp_telemp,emp_regrfc,emp_recurp,emp_regims,
            emp_cvesex,emp_keyims,emp_cvezon,emp_keypro,emp_tipemp,
            emp_tipsal,emp_status,emp_cobert,
            emp_salmes,
            emp_forpag,emp_ctaban, emp_cvebaj,emp_fecaux,emp_jorlab,emp_unijor,
            emp_ca2aux,emp_fecven,emp_fecpla,emp_ca1aux,
            emp_fecing,EMP_FECBAJ,EMP_PERING,emp_salint,emp_salivc,emp_salinf,emp_intsin,emp_infsin,EMP_PERAUM,EMP_FECREI,
            EMP_PERDEP, EMP_PERPUE, EMP_PERPRO,EMP_CVEBAN,EMP_CVETUR,
            emp_fecmod,EMP_HORMOD)
            SELECT
            EMP_KEYEMP,EMP_KEYDEP,EMP_KEYPUE,EMP_KEYCEN ,EMP_KEYLOC ,CONCAT(CONCAT(CONCAT(CONCAT(EMP_APEPAT, '/'),EMP_APEMAT),'/'),EMP_NOMBRE) Nombre,
            CONCAT(CONCAT(CONCAT(CONCAT(EMP_DOMEMP, ' '),EMP_NUMEXT),' '),EMP_NUMINT) DOMICILIO,
            EMP_COLEMP ,substr(EMP_CIDEMP,1,20),EMP_MUNEMP ,EMP_ENTEMP ,
            EMP_CODEMP ,EMP_TELEMP ,EMP_REGRFC ,EMP_RECURP ,EMP_REGIMS ,
            EMP_CVESEX ,ACTUALIZARLABORA.EMP_KEYIMS ,EMP_CVEZON ,EMP_KEYPRO ,EMP_TIPEMP ,
            EMP_TIPSAL ,EMP_STATUS ,'1',
            --EMP_SALMES ,
            0,
            EMP_FORPAG ,EMP_CTABAN ,EMP_CVEBAJ ,EMP_FECAUX ,EMP_JORLAB ,EMP_UNIJOR ,
            EMP_CA2AUX ,EMP_FECVEN ,EMP_FECPLA ,EMP_CA1AUX  ,
            ACTUALIZARLABORA.EMP_FECHA_MOV,ACTUALIZARLABORA.FECHA_MOV,PERIODO,0,0,0,0,0,PERIODOMOD,FECHAREINGRESO,
            PERIODO, PERIODO, PERIODO,ACTUALIZARLABORA.EMP_CVEBAN,0,
            TO_DATE(TO_CHAR(sysdate, 'MM/DD/YYYY'), 'MM/DD/YYYY'),
            to_char(sysdate, 'hh24:mi:ss')
            FROM LABPROD.API_MOVIMIENTOSPER where
            --API_MOVIMIENTOSPER.emp_keyemp = ACTUALIZARLABORA.EMP_KEYEMP AND
            API_MOVIMIENTOSPER.ID_TRANSACCION = ACTUALIZARLABORA.ID_TRANSACCION AND CODE = 'OK';
            COMMIT;
            UPDATE LABPROD.EOCOPLZA SET PLZ_KEYEMP = 0 WHERE PLZ_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP;
            COMMIT;
            UPDATE LABPROD.EOCOPLZA SET PLZ_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP WHERE plz_keyplz = ACTUALIZARLABORA.EMP_KEYPLZ;
            COMMIT;
        END IF;
   DBMS_OUTPUT.PUT_LINE ('count empleado ' || BAND2 );
        IF BAND2  >  0 THEN
       DBMS_OUTPUT.PUT_LINE ('ENTRA PARA MODIFICAR EMPLEADO');
       SELECT EMP_FECING, EMP_PERING INTO FECING,PERIODO2 FROM LABPROD.NMCOEMPL WHERE NMCOEMPL.EMP_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP;
            UPDATE LABPROD.NMCOEMPL  SET
            NMCOEMPL.emp_keydep = ACTUALIZARLABORA.EMP_KEYDEP,
            NMCOEMPL.emp_keypue = ACTUALIZARLABORA.EMP_KEYPUE,
            NMCOEMPL.emp_keycen = ACTUALIZARLABORA.EMP_KEYCEN,
            NMCOEMPL.emp_keyloc = ACTUALIZARLABORA.EMP_KEYLOC,
            NMCOEMPL.emp_nomemp = CONCAT(CONCAT(CONCAT(CONCAT(ACTUALIZARLABORA.EMP_APEPAT, '/'),ACTUALIZARLABORA.EMP_APEMAT),'/'),ACTUALIZARLABORA.EMP_NOMBRE),
            NMCOEMPL.emp_domemp = CONCAT(CONCAT(CONCAT(CONCAT(ACTUALIZARLABORA.EMP_DOMEMP, ' '),ACTUALIZARLABORA.EMP_NUMEXT),' '),ACTUALIZARLABORA.EMP_NUMINT),
            NMCOEMPL.emp_colemp = ACTUALIZARLABORA.EMP_COLEMP,
            NMCOEMPL.emp_cidemp = substr(ACTUALIZARLABORA.EMP_CIDEMP,1,20),
            NMCOEMPL.emp_munemp = ACTUALIZARLABORA.EMP_MUNEMP,
            NMCOEMPL.emp_entemp = ACTUALIZARLABORA.EMP_ENTEMP,
            NMCOEMPL.emp_codemp = ACTUALIZARLABORA.EMP_CODEMP,
            NMCOEMPL.emp_telemp = ACTUALIZARLABORA.EMP_TELEMP,
            NMCOEMPL.emp_regrfc = ACTUALIZARLABORA.EMP_REGRFC,
            NMCOEMPL.emp_recurp = ACTUALIZARLABORA.EMP_RECURP,
            NMCOEMPL.emp_regims = ACTUALIZARLABORA.EMP_REGIMS,
            NMCOEMPL.emp_cvesex = ACTUALIZARLABORA.EMP_CVESEX,
            NMCOEMPL.emp_keyims = ACTUALIZARLABORA.EMP_KEYIMS,
            NMCOEMPL.emp_cvezon = ACTUALIZARLABORA.EMP_CVEZON,
            NMCOEMPL.emp_keypro = ACTUALIZARLABORA.EMP_KEYPRO,
            NMCOEMPL.emp_tipemp = ACTUALIZARLABORA.EMP_TIPEMP,
            NMCOEMPL.emp_tipsal = ACTUALIZARLABORA.EMP_TIPSAL,
            NMCOEMPL.emp_status = ACTUALIZARLABORA.EMP_STATUS,
            NMCOEMPL.emp_forpag = ACTUALIZARLABORA.EMP_FORPAG,
            NMCOEMPL.emp_ctaban = ACTUALIZARLABORA.EMP_CTABAN,
            NMCOEMPL.emp_cvebaj = ACTUALIZARLABORA.EMP_CVEBAJ,
            NMCOEMPL.emp_fecaux = ACTUALIZARLABORA.EMP_FECAUX,
            NMCOEMPL.emp_jorlab = ACTUALIZARLABORA.EMP_JORLAB,
            NMCOEMPL.emp_unijor = ACTUALIZARLABORA.EMP_UNIJOR,
            NMCOEMPL.emp_ca2aux = ACTUALIZARLABORA.EMP_CA2AUX,
            NMCOEMPL.emp_fecven = ACTUALIZARLABORA.EMP_FECVEN,
            NMCOEMPL.emp_fecpla = ACTUALIZARLABORA.EMP_FECPLA,
            NMCOEMPL.emp_ca1aux = ACTUALIZARLABORA.EMP_CA1AUX,
            NMCOEMPL.emp_cobert = '1',
            NMCOEMPL.EMP_FECING = CASE WHEN NMCOEMP_FECING IS NULL THEN NMCOEMPL.EMP_FECING ELSE NMCOEMP_FECING END,
            NMCOEMPL.EMP_PERING = CASE WHEN NMCOEMP_PERING IS NULL THEN NMCOEMPL.EMP_PERING ELSE NMCOEMP_PERING END,
            NMCOEMPL.EMP_PERDEP = (CASE WHEN NMCOEMPL.EMP_KEYDEP = ACTUALIZARLABORA.EMP_KEYDEP THEN NMCOEMPL.EMP_PERDEP ELSE PERIODO END),
            NMCOEMPL.EMP_PERPUE = (CASE WHEN NMCOEMPL.EMP_KEYPUE = ACTUALIZARLABORA.EMP_KEYPUE THEN NMCOEMPL.EMP_PERPUE ELSE PERIODO END),
            NMCOEMPL.EMP_PERPRO = (CASE WHEN NMCOEMPL.EMP_KEYPRO = ACTUALIZARLABORA.EMP_KEYPRO THEN NMCOEMPL.EMP_PERPRO ELSE PERIODO END),
            EMP_CVEBAN = ACTUALIZARLABORA.EMP_CVEBAN,
            EMP_FECMOD = SYSDATE,
            EMP_HORMOD = to_char(sysdate, 'hh24:mi:ss')
            WHERE NMCOEMPL.EMP_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP;
            commit;
            if  EMP_TIPMOV ='1' then
                DELETE FROM nmlodata WHERE dat_keyemp = ACTUALIZARLABORA.EMP_KEYEMP AND dat_keypar IN ('V0','V1');
                INSERT INTO nmlodata VALUES (ACTUALIZARLABORA.EMP_KEYEMP,'V0','1');
                INSERT INTO nmlodata VALUES (ACTUALIZARLABORA.EMP_KEYEMP,'V1', TO_CHAR(SYSDATE,'yyyy-mm-dd'));
                commit;
            end if;
            IF EMP_TIPMOV = '6' AND EMP_SUBMOV = '44' THEN
               -- SELECT EMP_FECING, EMP_PERING INTO FECING,PERIODO FROM LABPROD.NMCOEMPL WHERE NMCOEMPL.EMP_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP;
                UPDATE LABPROD.NMCOEMPL SET EMP_FECING =  FECING , EMP_PERING = PERIODO2,
                NMCOEMPL.emp_fecbaj = null,
                NMCOEMPL.emp_perbaj = null,
                NMCOEMPL.emp_cvebaj = null
                WHERE EMP_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP;
            END IF;
            IF EMP_TIPMOV = '36' THEN
                UPDATE LABPROD.NMCOEMPL SET EMP_FECING =  FECING , EMP_PERING = PERIODO2
                WHERE EMP_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP;
            END IF;
            IF  EMP_TIPMOV = '2' THEN
                UPDATE LABPROD.EOCOPLZA SET EOCOPLZA.PLZ_KEYEMP = 0 WHERE EOCOPLZA.PLZ_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP;
                COMMIT;
            else
                UPDATE LABPROD.EOCOPLZA SET EOCOPLZA.PLZ_KEYEMP = 0 WHERE EOCOPLZA.PLZ_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP;
                COMMIT;
                UPDATE LABPROD.EOCOPLZA SET EOCOPLZA.PLZ_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP WHERE EOCOPLZA.plz_keyplz = ACTUALIZARLABORA.EMP_KEYPLZ;
                COMMIT;
            end if;
            IF  TEMPMOV = '6' AND EMP_SUBMOV != '44' THEN
                FECHAREINGRESO := EMP_FECHA_MOV;
                UPDATE LABPROD.NMCOEMPL  SET
                NMCOEMPL.EMp_FECING = ACTUALIZARLABORA.EMP_FECHA_MOV,
                NMCOEMPL.EMP_PERING = KEYPER,
                NMCOEMPL.emp_fecbaj = null,
                NMCOEMPL.emp_perbaj = null,
                NMCOEMPL.emp_cvebaj = null
                WHERE NMCOEMPL.EMP_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP;
                COMMIT;
            END IF;
            IF  EMP_TIPMOV = '5' THEN
                FECHAAUMENTO := EMP_FECHA_MOV;
                PERIODOMOD := PERIODO;
                UPDATE LABPROD.NMCOEMPL  SET
                NMCOEMPL.emp_peraum = KEYPER ,
                NMCOEMPL.EMP_FECAUM = ACTUALIZARLABORA.FECHAAUMENTO
                WHERE NMCOEMPL.EMP_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP;
                COMMIT;
            END IF;
            IF EMP_TIPMOV = '2' THEN
                UPDATE LABPROD.NMCOEMPL  SET
                NMCOEMPL.emp_fecbaj = ACTUALIZARLABORA.FECHA_MOV,
                NMCOEMPL.emp_perbaj = ACTUALIZARLABORA.PERIODOFIN
                WHERE NMCOEMPL.EMP_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP;
                COMMIT;
            END IF;
            IF  TEMPMOV = '6' AND EMP_SUBMOV = '44' THEN
                select  MAX(to_char(tra_fecmod, 'DD/MM/YY hh24:mi:ss'))  into fecmod from labprod.nmlotray
                where tra_keyemp = ACTUALIZARLABORA.EMP_KEYEMP and nmlotray.tra_tipmov = '2';
                delete labprod.nmlotray where
                tra_keyemp = ACTUALIZARLABORA.EMP_KEYEMP and nmlotray.tra_tipmov = '2' and
                fecmod=to_char(nmlotray.tra_fecmod, 'DD/MM/YY hh24:mi:ss');
                COMMIT;
                UPDATE LABPROD.SCCOBAJA SET baj_status = '4'
                WHERE baj_keyemp = ACTUALIZARLABORA.EMP_KEYEMP
                AND baj_fecbaj =  ACTUALIZARLABORA.EMP_FECHA_IMSS
                AND baj_status in( '2','1');
                --OR baj_status = '1';
                COMMIT;
            END IF;
        END IF ;
        SELECT COUNT(*) INTO  BANDBAN FROM LABPROD.NMLOCTAS  WHERE ACTUALIZARLABORA.EMP_KEYPRO = CTA_KEYPRO AND CTA_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP;
        IF  BANDBAN  = 0 THEN
            INSERT INTO LABPROD.NMLOCTAS ( cta_keypro,cta_keyemp,cta_ctaban ) VALUES
            ( ACTUALIZARLABORA.EMP_KEYPRO,ACTUALIZARLABORA.EMP_KEYEMP,ACTUALIZARLABORA.EMP_CTABAN );
            COMMIT;
        END IF;
        IF  BANDBAN > 0 THEN
            UPDATE LABPROD.NMLOCTAS SET
            cta_keypro = ACTUALIZARLABORA.EMP_KEYPRO ,
            cta_keyemp = ACTUALIZARLABORA.EMP_KEYEMP,
            cta_ctaban = ACTUALIZARLABORA.EMP_CTABAN WHERE ACTUALIZARLABORA.EMP_KEYPRO = CTA_KEYPRO AND CTA_KEYEMP = ACTUALIZARLABORA.EMP_KEYEMP;
            Commit;
        END IF;
        select nmloproc.pro_ca4aux, nmloproc.pro_ca5aux into WS_PRO_CA4AUX, WS_PRO_CA5AUX from LABPROD.nmloproc where nmloproc.pro_keypro = ACTUALIZARLABORA.EMP_KEYPRO;
        if  WS_PRO_CA4AUX is null then
            WS_PRO_CA4AUX := '';
        end if;
        if  WS_PRO_CA5AUX is null then
            WS_PRO_CA5AUX := '';
        end if;
        SetRefCon(WS_PRO_CA4AUX,WS_PRO_CA5AUX,ACTUALIZARLABORA.EMP_CA2AUX,ACTUALIZARLABORA.EMP_TIPEMP,WS_EMP_CA4AUX , WS_EMP_REFCON ) ;
        update LABPROD.nmcoempl set nmcoempl.EMP_REFCON=WS_EMP_REFCON, nmcoempl.EMP_CA4AUX = WS_EMP_CA4AUX where nmcoempl.emp_keyemp = ACTUALIZARLABORA.EMP_KEYEMP ;
        Commit;
        DBMS_OUTPUT.PUT_LINE (ACTUALIZARLABORA.ID_TRANSACCION);
        UPDATE LABPROD.API_MOVIMIENTOSPER SET ESTATUS = '2', CODE='OK',MESSAGE='PROCESADO EN LABORA',FECHA_PROC = SYSDATE
        WHERE API_MOVIMIENTOSPER.ID_TRANSACCION = ACTUALIZARLABORA.ID_TRANSACCION AND API_MOVIMIENTOSPER.CODE ='OK';
        --AND ESTATUS = '1' AND CODE='OK' ;
        COMMIT;
        ESTATUS:='2';
        CODE :='OK';
        MESSAGE :='PROCESADO EN LABORA';
        EXCEPTION WHEN TOO_MANY_ROWS THEN
        --DBMS_OUTPUT.PUT_LINE (' ID_TRANSACCION DUPLICADO ' );
            UPDATE LABPROD.API_MOVIMIENTOSPER SET ESTATUS = '2',CODE='ERROR',MESSAGE='ID_TRANSACCION DUPLICADO'
            WHERE LABPROD.API_MOVIMIENTOSPER.ID_TRANSACCION = ACTUALIZARLABORA.ID_TRANSACCION;
            COMMIT;
        END;
END IF;
        EXCEPTION WHEN NO_DATA_FOUND THEN
            BEGIN
                BAND := 0;
            END;
        wHEN TOO_MANY_ROWS THEN
        BEGIN
                BAND := 0;
            END;
    END;
    PROCEDURE INSERTATRAYECTORIA
    (
    ID_TRANSACCION IN VARCHAR2,
    EMP_KEYEMP IN number,
    FECHA_MOV IN Date,
    EMP_TIPMOV IN VARCHAR2
    ) AS
    BAND NUMBER;
	EMP_KEYDEP VARCHAR2(16) ;
	EMP_KEYPUE VARCHAR2(16) ;
	EMP_KEYCEN VARCHAR2(16) ;
	EMP_KEYLOC VARCHAR2(16) ;
	EMP_APEPAT VARCHAR2(90) ;
	EMP_APEMAT VARCHAR2(90) ;
	EMP_NOMBRE VARCHAR2(90) ;
	EMP_DOMEMP VARCHAR2(100);
	EMP_NUMEXT VARCHAR2(10);
	EMP_NUMINT VARCHAR2(10);
	EMP_COLEMP VARCHAR2(100);
	EMP_CIDEMP VARCHAR2(20);
	EMP_MUNEMP VARCHAR2(6);
	EMP_ENTEMP VARCHAR2(2);
	EMP_CODEMP VARCHAR2(5);
	EMP_TELEMP VARCHAR2(60);
	EMP_REGRFC VARCHAR2(13);
	EMP_RECURP VARCHAR2(18);
	EMP_REGIMS VARCHAR2(12);
	EMP_CVESEX VARCHAR2(1);
	EMP_KEYIMS VARCHAR2(5);
	EMP_CVEZON NUMBER;
	EMP_KEYPRO NUMBER;
	EMP_TIPEMP VARCHAR2(6);
	EMP_TIPSAL VARCHAR2(1);
	EMP_STATUS NUMBER;
	EMP_SALHOR NUMBER;
	EMP_SALDIA NUMBER;
	EMP_SALMES NUMBER;
	EMP_FORPAG VARCHAR2(2);
	EMP_CTABAN VARCHAR2(18);
	EMP_CVEBAJ VARCHAR2(4);
	EMP_FECAUX DATE;
	EMP_JORLAB VARCHAR2(1);
	EMP_UNIJOR FLOAT(126);
	EMP_CA2AUX VARCHAR2(10);
	EMP_FECVEN DATE;
	EMP_FECPLA DATE;
	EMP_CA1AUX VARCHAR2(10);
	EMP_FECHA_IMSS DATE;
	EMP_SUBMOV VARCHAR2(6);
	EMP_SALINT NUMBER;
    KEYPER VARCHAR2(7);
    PERIODO NUMBER;
    KEYPRO NUMBER;
    SALINT NUMBER;
    DIA NUMBER;
    HORA NUMBER;
    MES NUMBER;
    UNIJOR NUMBER;
    BEGIN
    BEGIN
    SELECT COUNT(*) INTO BAND FROM LABPROD.NMLOTRAY
    WHERE NMLOTRAY.TRA_KEYEMP = INSERTATRAYECTORIA.EMP_KEYEMP
    AND TO_DATE(TRA_FECMOV, 'DD/MM/YY') = TO_DATE(INSERTATRAYECTORIA.FECHA_MOV , 'DD/MM/YY')
    AND INSERTATRAYECTORIA.EMP_TIPMOV =TRA_TIPMOV;
    SELECT EMP_KEYPRO,EMP_SALINT,EMP_SALMES,EMP_UNIJOR
    INTO KEYPRO,SALINT,MES,UNIJOR
    FROM LABPROD.API_MOVIMIENTOSPER
    WHERE API_MOVIMIENTOSPER.ID_TRANSACCION = INSERTATRAYECTORIA.ID_TRANSACCION;
    SELECT min(PER_KEYPER) into PERIODO
    FROM LABPROD.NMLOPERI
    WHERE NMLOPERI.PER_KEYPRO = INSERTATRAYECTORIA.KEYPRO
    AND PER_KEYNOM = 1 AND PER_FECACT IS NULL;
    EXCEPTION WHEN TOO_MANY_ROWS THEN
    DBMS_OUTPUT.PUT_LINE (' EMPLEADO DUPLICADO DENTRO DE NMLOTRAY ' );
    END;
    DIA  :=  (MES / 30);
    HORA := (DIA / UNIJOR);
    IF BAND  = 0  THEN
        INSERT INTO LABPROD.NMLOTRAY (
        tra_keyemp,tra_fecmov,tra_tipmov,tra_keydep,tra_keypue,
        tra_keycat,tra_keycen,tra_saldia,tra_salmes,tra_salint,
        tra_salivc,tra_salinf,tra_intsin,tra_infsin,tra_keyims,
        tra_keyper,tra_codloc,tra_keypla,tra_keypro,tra_jorlab,
        tra_unijor,tra_submov,tra_ca1aux,tra_ca2aux,tra_fecmod,TRA_HORMOD)
        SELECT emp_keyemp,emp_fecha_mov,emp_tipmov,emp_keydep,emp_keypue,
        0,emp_keycen,(API_MOVIMIENTOSPER.emp_salmes/30),emp_salmes,SALINT,
        SALINT,SALINT,SALINT,SALINT,emp_keyims,
        PERIODO,emp_keyloc,0,emp_keypro,emp_jorlab,
        emp_unijor,emp_submov,NULL,NULL,sysdate,to_char(sysdate, 'hh24:mi:ss')
        from LABPROD.API_MOVIMIENTOSPER
        where API_MOVIMIENTOSPER.EMP_KEYEMP=INSERTATRAYECTORIA.EMP_KEYEMP AND INSERTATRAYECTORIA.ID_TRANSACCION = API_MOVIMIENTOSPER.ID_TRANSACCION;
        COMMIT;
    END IF;
    IF  BAND > 0 THEN
        SELECT
        emp_keydep,emp_keypue,emp_keycen,emp_keyloc,
        emp_apepat,emp_apemat,emp_nombre,emp_domemp,emp_numext,
        emp_numint,emp_colemp,emp_cidemp,emp_munemp,emp_entemp,
        emp_codemp,emp_telemp,emp_regrfc,emp_recurp,emp_regims,
        emp_cvesex,emp_keyims,emp_cvezon,emp_keypro,emp_tipemp,
        emp_tipsal,emp_status,emp_salhor,emp_saldia,emp_salmes,
        emp_forpag,emp_ctaban,emp_cvebaj,emp_fecaux,emp_jorlab,
        emp_unijor,emp_ca2aux,emp_fecven,emp_fecpla,emp_ca1aux,
        emp_fecha_imss,emp_submov,emp_salint,keyper
        INTO
        INSERTATRAYECTORIA.EMP_KEYDEP,INSERTATRAYECTORIA.EMP_KEYPUE,INSERTATRAYECTORIA.EMP_KEYCEN,INSERTATRAYECTORIA.EMP_KEYLOC
        ,INSERTATRAYECTORIA.EMP_APEPAT,INSERTATRAYECTORIA.EMP_APEMAT,INSERTATRAYECTORIA.EMP_NOMBRE,INSERTATRAYECTORIA.EMP_DOMEMP,INSERTATRAYECTORIA.EMP_NUMEXT
        ,INSERTATRAYECTORIA.EMP_NUMINT,INSERTATRAYECTORIA.EMP_COLEMP,INSERTATRAYECTORIA.EMP_CIDEMP,INSERTATRAYECTORIA.EMP_MUNEMP,INSERTATRAYECTORIA.EMP_ENTEMP
        ,INSERTATRAYECTORIA.EMP_CODEMP,INSERTATRAYECTORIA.EMP_TELEMP,INSERTATRAYECTORIA.EMP_REGRFC,INSERTATRAYECTORIA.EMP_RECURP,INSERTATRAYECTORIA.EMP_REGIMS
        ,INSERTATRAYECTORIA.EMP_CVESEX,INSERTATRAYECTORIA.EMP_KEYIMS,INSERTATRAYECTORIA.EMP_CVEZON ,INSERTATRAYECTORIA.EMP_KEYPRO,INSERTATRAYECTORIA.EMP_TIPEMP
        ,INSERTATRAYECTORIA.EMP_TIPSAL,INSERTATRAYECTORIA.EMP_STATUS,INSERTATRAYECTORIA.EMP_SALHOR,INSERTATRAYECTORIA.EMP_SALDIA,INSERTATRAYECTORIA.EMP_SALMES
        ,INSERTATRAYECTORIA.EMP_FORPAG,INSERTATRAYECTORIA.EMP_CTABAN,INSERTATRAYECTORIA.EMP_CVEBAJ,INSERTATRAYECTORIA.EMP_FECAUX,INSERTATRAYECTORIA.EMP_JORLAB
        ,INSERTATRAYECTORIA.EMP_UNIJOR,INSERTATRAYECTORIA.EMP_CA2AUX,INSERTATRAYECTORIA.EMP_FECVEN ,INSERTATRAYECTORIA.EMP_FECPLA,INSERTATRAYECTORIA.EMP_CA1AUX
        ,INSERTATRAYECTORIA.EMP_FECHA_IMSS,INSERTATRAYECTORIA.EMP_SUBMOV
        ,INSERTATRAYECTORIA.EMP_SALINT,INSERTATRAYECTORIA.KEYPER
        from LABPROD.API_MOVIMIENTOSPER
        WHERE API_MOVIMIENTOSPER.ID_TRANSACCION = INSERTATRAYECTORIA.ID_TRANSACCION;
        UPDATE LABPROD.NMLOTRAY SET
        NMLOTRAY.tra_fecmov = INSERTATRAYECTORIA.FECHA_MOV,
        NMLOTRAY.tra_tipmov = INSERTATRAYECTORIA.EMP_TIPMOV,
        NMLOTRAY.tra_keydep = INSERTATRAYECTORIA.EMP_KEYDEP,
        NMLOTRAY.tra_keypue = INSERTATRAYECTORIA.EMP_KEYEMP,
        NMLOTRAY.tra_keycat = 0,
        NMLOTRAY.tra_keycen = INSERTATRAYECTORIA.EMP_KEYCEN,
        NMLOTRAY.tra_saldia = ROUND(DIA ,4),
        NMLOTRAY.tra_salmes = INSERTATRAYECTORIA.EMP_SALMES,
        NMLOTRAY.tra_salint = SALINT,
        NMLOTRAY.tra_salivc = SALINT,
        NMLOTRAY.tra_salinf = SALINT,
        NMLOTRAY.tra_intsin = SALINT,
        NMLOTRAY.tra_infsin = SALINT,
        NMLOTRAY.tra_keyims = INSERTATRAYECTORIA.EMP_KEYIMS,
        NMLOTRAY.tra_keyper = PERIODO,
        NMLOTRAY.tra_codloc = INSERTATRAYECTORIA.EMP_KEYLOC,
        NMLOTRAY.tra_keypla = 0,
        NMLOTRAY.tra_keypro = INSERTATRAYECTORIA.EMP_KEYPRO,
        NMLOTRAY.tra_jorlab = INSERTATRAYECTORIA.EMP_JORLAB,
        NMLOTRAY.tra_unijor = INSERTATRAYECTORIA.EMP_UNIJOR,
        NMLOTRAY.tra_submov = INSERTATRAYECTORIA.EMP_SUBMOV,
        NMLOTRAY.tra_ca1aux = INSERTATRAYECTORIA.EMP_CA1AUX,
        NMLOTRAY.tra_ca2aux = INSERTATRAYECTORIA.EMP_CA2AUX,
        NMLOTRAY.tra_fecmod = SYSDATE,
        NMLOTRAY.TRA_HORMOD = to_char(sysdate, 'hh24:mi:ss')
        WHERE NMLOTRAY.TRA_KEYEMP = INSERTATRAYECTORIA.EMP_KEYEMP
        AND TO_DATE(TRA_FECMOV, 'DD/MM/YY') = TO_DATE(INSERTATRAYECTORIA.FECHA_MOV , 'DD/MM/YY')
        AND INSERTATRAYECTORIA.EMP_TIPMOV = NMLOTRAY.TRA_TIPMOV;
        COMMIT;
    END IF;
END;
    PROCEDURE ACTUALIZARSALARIO(
    EMP_KEYEMP IN NUMBER,
    NEW_SALMES IN NUMBER,
    NEW_SALINT IN NUMBER,
    NEW_SALIVC IN NUMBER,
    NEW_SALINF IN NUMBER,
    NEW_INTSIN IN NUMBER,
    NEW_INFSIN IN NUMBER)
    AS
    DIA NUMBER;
    HORA NUMBER;
    DIAANT NUMBER;
    HORAANT NUMBER;
    MESANT NUMBER;
    EMP_SALIVC NUMBER;
    EMP_SALINF NUMBER;
    EMP_INTSIN NUMBER;
    EMP_INFSIN NUMBER;
    EMP_TIPMOV VARCHAR(2);
    UNIJOR NUMBER;
    BEGIN
        DIA :=  (NEW_SALMES / 30);
        SELECT EMP_SALMES,EMP_UNIJOR
        INTO   MESANT,UNIJOR
        FROM NMCOEMPL WHERE NMCOEMPL.EMP_KEYEMP = ACTUALIZARSALARIO.EMP_KEYEMP;
        DBMS_OUTPUT.PUT_LINE ('MESANT' || MESANT);
       IF MESANT != NEW_SALMES THEN
            UPDATE LABPROD.NMCOEMPL SET
            EMP_ANTMES = EMP_SALMES , EMP_SALMES = NEW_SALMES,
            EMP_ANTINT = EMP_SALINT, EMP_SALINT = NEW_SALINT,
            EMP_ANTIVC = EMP_SALIVC, EMP_SALIVC = NEW_SALIVC,
            EMP_ANTINF = EMP_SALINF, EMP_SALINF = NEW_SALINF,
            EMP_ANTITS = EMP_INTSIN, EMP_INTSIN = NEW_INTSIN,
            EMP_ANTIFS = EMP_INFSIN, EMP_INFSIN = NEW_INFSIN,
            EMP_ANTDIA = ROUND(EMP_SALDIA,4), EMP_SALDIA = ROUND(DIA,4),
            EMP_ANTHOR = (EMP_SALHOR), EMP_SALHOR = ROUND(DIA/EMP_UNIJOR,4)
            WHERE EMP_KEYEMP = ACTUALIZARSALARIO.EMP_KEYEMP;
        COMMIT;
        END IF;
    END ;
    PROCEDURE SetRefCon
    (
    WS_PRO_CA4AUX IN VARCHAR2,
    WS_PRO_CA5AUX IN VARCHAR2,
    WS_EMP_CA2AUX IN VARCHAR2,
    WS_EMP_TIPEMP IN VARCHAR2,
    WS_EMP_CA4AUX OUT VARCHAR2,
    WS_EMP_REFCON OUT VARCHAR2
    )
    AS
    BEGIN
    If  ws_pro_ca4aux is null And ws_pro_ca5aux is null Then
        ws_emp_ca4aux :='N';
        ws_emp_refcon :='2';
    end if;
    If  ws_pro_ca4aux ='S' And ws_pro_ca5aux ='T' Then
        ws_emp_ca4aux :='F';
        ws_emp_refcon :='1';
    end if;
    If  ws_pro_ca4aux ='N' Then
        ws_emp_ca4aux :='N';
        ws_emp_refcon :='2';
    end if;
    If  ws_pro_ca4aux ='S' And ws_pro_ca5aux ='C' Then
        If  ws_emp_tipemp ='1' Then
            ws_emp_ca4aux :='F';
            ws_emp_refcon :='1';
        Else
            ws_emp_ca4aux :='N';
            ws_emp_refcon :='2';
        End If;
    end if;
    If  ws_pro_ca4aux ='S' And ws_pro_ca5aux ='S' Then
        If  ws_emp_tipemp ='2' Then
            ws_emp_ca4aux :='F';
            ws_emp_refcon :='1';
        Else
            ws_emp_ca4aux :='N';
            ws_emp_refcon :='2';
        End If;
    End If;
    If  ws_emp_ca2aux > '2' And ws_emp_ca2aux < '8' Then
        ws_emp_ca4aux :='N';
        ws_emp_refcon :='2';
    end if;
    END;
    PROCEDURE InsertaTray
    (
    EMP_KEYEMP IN number,
    FECHA_MOV IN Date,
    EMP_TIPMOV IN VARCHAR2,
    EMP_KEYDEP IN VARCHAR2 ,
	EMP_KEYPUE IN VARCHAR2,
	EMP_KEYCEN IN VARCHAR2,
	EMP_KEYLOC IN VARCHAR2,
	EMP_APEPAT IN VARCHAR2,
	EMP_APEMAT IN VARCHAR2,
	EMP_NOMBRE IN  VARCHAR2,
	EMP_DOMEMP IN VARCHAR2,
	EMP_NUMEXT IN VARCHAR2,
	EMP_NUMINT IN VARCHAR2,
	EMP_COLEMP IN VARCHAR2,
	EMP_CIDEMP IN VARCHAR2,
	EMP_MUNEMP IN VARCHAR2,
	EMP_ENTEMP IN VARCHAR2,
	EMP_CODEMP IN VARCHAR2,
	EMP_TELEMP IN VARCHAR2,
	EMP_REGRFC IN VARCHAR2,
	EMP_RECURP IN VARCHAR2,
	EMP_REGIMS IN VARCHAR2,
	EMP_CVESEX IN VARCHAR2,
	EMP_KEYIMS IN VARCHAR2,
	EMP_CVEZON IN NUMBER,
	EMP_KEYPRO IN NUMBER,
	EMP_TIPEMP IN VARCHAR2,
	EMP_TIPSAL IN VARCHAR2,
	EMP_STATUS IN NUMBER,
	EMP_SALHOR IN NUMBER,
	EMP_SALDIA IN NUMBER,
	EMP_SALMES IN NUMBER,
	EMP_FORPAG IN VARCHAR2,
	EMP_CTABAN IN VARCHAR2,
	EMP_CVEBAJ IN VARCHAR2,
	EMP_FECAUX IN DATE,
	EMP_JORLAB IN VARCHAR2,
	EMP_UNIJOR IN NUMBER,
	EMP_CA2AUX IN VARCHAR2,
	EMP_FECVEN IN DATE,
	EMP_FECPLA IN DATE,
	EMP_CA1AUX IN VARCHAR2,
	EMP_FECHA_IMSS IN DATE,
	EMP_SUBMOV IN VARCHAR2,
	EMP_SALINT IN NUMBER,
    KEYPER IN VARCHAR2,
    EMP_SALIVC IN NUMBER,
    EMP_SALINF IN NUMBER,
    EMP_INTSIN IN NUMBER,
    EMP_INFSIN IN NUMBER
    ) AS
    BAND NUMBER;
    DIA NUMBER;
    HORA NUMBER;
    PERIODO VARCHAR2(7);
    BEGIN
    DIA  :=  (EMP_SALMES / 30);
    HORA := (DIA / InsertaTray.EMP_UNIJOR);
    SELECT COUNT(*) INTO BAND FROM LABPROD.NMLOTRAY WHERE NMLOTRAY.TRA_KEYEMP = InsertaTray.EMP_KEYEMP  AND
    TO_DATE(NMLOTRAY.TRA_FECMOV, 'DD/MM/YY') = TO_DATE(InsertaTray.FECHA_MOV , 'DD/MM/YY')  AND InsertaTray.EMP_TIPMOV =TRA_TIPMOV;
    IF  EMP_TIPMOV = '4' OR EMP_TIPMOV = '20' THEN
        SELECT MIN(PER_KEYPER) INTO PERIODO FROM LABPROD.NMLOPERI WHERE PER_KEYPRO = EMP_KEYPRO AND PER_KEYNOM = 1 AND PER_FECACT IS NULL;
    ELSE
        PERIODO := KEYPER;
    END IF;
    IF BAND = 0 THEN
        INSERT INTO LABPROD.nmlotray
        (tra_keyemp,tra_fecmov,tra_tipmov,tra_keydep,tra_keypue,
        tra_keycen,tra_saldia,tra_salmes,tra_salint,
        tra_salivc,tra_salinf,tra_intsin,tra_infsin,tra_keyims,
        tra_keyper,tra_codloc,tra_keypro,tra_jorlab,
        tra_unijor,tra_submov,
        tra_fecmod,tra_hormod)
        VALUES (EMP_KEYEMP ,FECHA_MOV ,EMP_TIPMOV ,EMP_KEYDEP ,EMP_KEYPUE ,
        EMP_KEYCEN ,EMP_SALDIA,EMP_SALMES,EMP_SALINT,
        EMP_SALINT,EMP_SALINT,EMP_SALINT,EMP_SALINT,EMP_KEYIMS,
        PERIODO,EMP_KEYLOC,EMP_KEYPRO,EMP_JORLAB,
        EMP_UNIJOR,EMP_SUBMOV,TO_DATE(TO_CHAR(sysdate, 'MM/DD/YYYY'), 'MM/DD/YYYY'),
        to_char(sysdate, 'hh24:mi:ss'));
        COMMIT;
    END IF;
    IF BAND >= 1 THEN
        UPDATE LABPROD.NMLOTRAY SET
        NMLOTRAY.tra_fecmov = InsertaTray.FECHA_MOV,
        NMLOTRAY.tra_tipmov = InsertaTray.EMP_TIPMOV,
        NMLOTRAY.tra_keydep = InsertaTray.EMP_KEYDEP,
        NMLOTRAY.tra_keypue = InsertaTray.EMP_KEYPUE,
        NMLOTRAY.tra_keycen = InsertaTray.EMP_KEYCEN,
        NMLOTRAY.tra_saldia = ROUND(InsertaTray.EMP_SALDIA ,4),
        NMLOTRAY.tra_salmes = InsertaTray.EMP_SALMES,
        NMLOTRAY.tra_salint = InsertaTray.EMP_SALINT,
        NMLOTRAY.tra_salivc = InsertaTray.EMP_SALINT,
        NMLOTRAY.tra_salinf = InsertaTray.EMP_SALINT,
        NMLOTRAY.tra_intsin = InsertaTray.EMP_SALINT,
        NMLOTRAY.tra_infsin = InsertaTray.EMP_SALINT,
        NMLOTRAY.tra_keyims = InsertaTray.EMP_KEYIMS,
        NMLOTRAY.tra_keyper = PERIODO,
        NMLOTRAY.tra_codloc = InsertaTray.EMP_KEYLOC,
        NMLOTRAY.tra_keypro = InsertaTray.EMP_KEYPRO,
        NMLOTRAY.tra_jorlab = InsertaTray.EMP_JORLAB,
        NMLOTRAY.tra_unijor = InsertaTray.EMP_UNIJOR,
        NMLOTRAY.tra_submov = InsertaTray.EMP_SUBMOV,
        NMLOTRAY.tra_fecmod = TO_DATE(TO_CHAR(sysdate, 'MM/DD/YYYY'), 'MM/DD/YYYY'),
        NMLOTRAY.TRA_HORMOD = to_char(sysdate, 'hh24:mi:ss')
        WHERE NMLOTRAY.TRA_KEYEMP = InsertaTray.EMP_KEYEMP
        AND TO_DATE(TRA_FECMOV, 'DD/MM/YY') = TO_DATE(InsertaTray.FECHA_MOV , 'DD/MM/YY')
        AND InsertaTray.EMP_TIPMOV = NMLOTRAY.TRA_TIPMOV;
        COMMIT;
    END IF;
    END ;
    PROCEDURE ClaveBanco
    (
        EMP_FORPAG IN number,
        EMP_CVEBAN OUT VARCHAR
    ) AS
    EMP_CVEBAN2 VARCHAR(7);
    BEGIN
        SELECT PAM_FOLINI INTO EMP_CVEBAN FROM LABPROD.GLCOPAMS WHERE PAM_KEYPAR = 'FP' AND PAM_CVESEC =ClaveBanco.EMP_FORPAG;
        EXCEPTION WHEN NO_DATA_FOUND THEN
        EMP_CVEBAN := NULL;
    END;
    PROCEDURE CAMBIOPROCESO
    (
    API_KEYPRO IN NUMBER,
    API_KEYEMP IN NUMBER,
    API_FECMOV DATE,
    API_PERING VARCHAR,
    EMP_KEYPRO IN NUMBER,
    FECHAING OUT DATE,
    PERING OUT VARCHAR
    ) AS
    PRO_KEYPRO NUMBER;
    EMP_FECING DATE;
    EMP_PERING VARCHAR(7);
    PRO_DIAPER NUMBER(5);
    API_DIAPER NUMBER(5);
    BEGIN
    --SELECT EMP_KEYPRO,EMP_FECING,EMP_PERING INTO PRO_KEYPRO,EMP_FECING,EMP_PERING FROM LABPROD.NMCOEMPL  WHERE EMP_KEYEMP = CAMBIOPROCESO.API_KEYEMP;
        SELECT PRO_DIAPER INTO PRO_DIAPER FROM LABPROD.NMLOPROC WHERE PRO_KEYPRO = CAMBIOPROCESO.EMP_KEYPRO;
        SELECT PRO_DIAPER INTO API_DIAPER FROM LABPROD.NMLOPROC WHERE PRO_KEYPRO = CAMBIOPROCESO.API_KEYPRO;
        IF CAMBIOPROCESO.PRO_DIAPER  != API_DIAPER  THEN
            FECHAING:=API_FECMOV;
            PERING:=API_PERING;
        ELSE
            FECHAING:=EMP_FECING;
            PERING:=EMP_PERING;
        END IF;
    END;
END;
/;
