CREATE OR REPLACE EDITIONABLE TRIGGER "USRSIHO"."CFDIPAGOS_TRG" 
BEFORE INSERT
ON USRSIHO.CFDIPAGOS
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column IDCOMPROBANTEEMP
  :new.IDCOMPROBANTEEMP := CFDIPAGOS_SEQ.nextval;
END CFDIPAGOS_TRG;


/
ALTER TRIGGER "USRSIHO"."CFDIPAGOS_TRG" ENABLE;
