CREATE OR REPLACE EDITIONABLE TRIGGER "USRSIHO"."DETALLEPARAMETROSID_SEQ_TR" 
 BEFORE INSERT ON USRSIHO.DETALLEPARAMETROS FOR EACH ROW
    WHEN (NEW.IdDetalle IS NULL) BEGIN
 SELECT USRSIHO.DETALLEPARAMETROSID_SEQ.NEXTVAL INTO :NEW.IdDetalle FROM DUAL;
END;

/
ALTER TRIGGER "USRSIHO"."DETALLEPARAMETROSID_SEQ_TR" ENABLE;
