CREATE OR REPLACE EDITIONABLE TRIGGER "USRSIHO"."FACTURA_TER_TRG" 
BEFORE INSERT
ON USRSIHO.FACTURA_TER
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
BEGIN
-- For Toad:  Highlight column POLIZA
  :new.POLIZA := FACTURA_TER_SEQ.nextval;
END FACTURA_TER_TRG;


/
ALTER TRIGGER "USRSIHO"."FACTURA_TER_TRG" ENABLE;
