CREATE OR REPLACE FORCE EDITIONABLE VIEW "LABCONF"."XXLB_CFDIXPOLIZA_V" ("KEYFAC", "ORIGEN", "MES", "ANIO", "UUID", "ORGID", "RFC_EMISOR", "RFC_RECEPTOR", "IMPORTE", "FECHA_EMISION") AS 
  SELECT KEYFAC,
          ORIGEN,
          MES,
          ANIO,
          UUID,
          ORGID,
          RFC_EMISOR,
          RFC_RECEPTOR,
          IMPORTE,
          FECHA_EMISION
     FROM LABCONF.CFDIXPOLIZA;
