CREATE OR REPLACE FORCE EDITIONABLE VIEW "XX_LMKTEDIAL"."XXTDL_INT_LIST_CHANNELS_ALL_VW" ("ROW_ID", "ID_SERVICE", "NOM_SERVICE", "IND_DESC_SERVICE", "ID_PARAMETER", "NOM_PARAMETER", "IND_DESC_PARAMETER", "IND_USED_BY", "IND_VALUE_PARAMETER", "IND_ESTATUS", "FEC_CREATION_DATE", "VAL_MOSTRAR", "VAL_VALUE", "SELECTED") AS 
  SELECT CAN.ROWID,
       SCT.ID_SERVICE,
       SCT.NOM_SERVICE,
       SCT.IND_DESC_SERVICE,
       CAN.ID_PARAMETER,
       CAN.NOM_PARAMETER,
       CAN.IND_DESC_PARAMETER,
       CAN.IND_USED_BY,
       CAN.IND_VALUE_PARAMETER,
       CAN.IND_ESTATUS,
       CAN.FEC_CREATION_DATE,
       'false' VAL_MOSTRAR,
       'abcedario' VAL_VALUE,
       CASE WHEN (SELECT COUNT(*)
                    FROM XX_LMKTEDIAL.XXTDL_INT_SERVICES_PARAMS_TAB PRM
                   WHERE PRM.ID_SERVICE    = SCT.ID_SERVICE
                     AND PRM.IND_PARAMETER = CAN.NOM_PARAMETER
                     AND PRM.IND_VAL_PARAMETER   = '1'
                  ) > 0
            THEN 'true'
            ELSE 'false' END AS SELECTED
  FROM XX_LMKTEDIAL.XXTDL_INT_CONFIG_PARAM_TAB CAN,
       XX_LMKTEDIAL.XXTDL_INT_SERVICES_CAT_TAB SCT
 WHERE CAN.IND_USED_BY = 'CHANNEL_PARAMETER';
