CREATE OR REPLACE FORCE EDITIONABLE VIEW "XX_LMKTEDIAL"."XXTDL_INT_SERVICES_LOG_VW" ("ID_LOG_SERVICES", "ID_SERVICE", "NOM_SERVICE", "ID_FILE_XML", "ID_REQUEST", "NOM_FILE", "IND_PARAMETERS", "SHOW_REQUEST", "SHOW_RESPONSE", "IND_PROCESS", "IND_PROCESS_NOM", "IND_RESPONSE", "NUM_USER", "FEC_RESPONSE", "FEC_REQUEST", "NUM_PROCESS_ID", "NUM_PGM_PROCESS_ID", "IND_CALCULATE_STATUS", "IND_ESTATUS", "ATTRIBUTE_CATEGORY", "ATTRIBUTE1", "ATTRIBUTE2", "ATTRIBUTE3", "ATTRIBUTE4", "ATTRIBUTE5", "ATTRIBUTE6", "ATTRIBUTE7", "ATTRIBUTE8", "ATTRIBUTE9", "ATTRIBUTE10", "ATTRIBUTE11", "ATTRIBUTE12", "ATTRIBUTE13", "ATTRIBUTE14", "ATTRIBUTE15", "FEC_CREATION_DATE", "NUM_CREATED_BY", "FEC_LAST_UPDATE_DATE", "NUM_LAST_UPDATED_BY", "NUM_LAST_UPDATE_LOGIN") AS 
  SELECT SLOG.ID_LOG_SERVICES,
          SLOG.ID_SERVICE,
          (SELECT CSV.IND_DESC_SERVICE
             FROM XX_LMKTEDIAL.XXTDL_INT_SERVICES_CAT_TAB CSV
            WHERE CSV.ID_SERVICE = SLOG.ID_SERVICE
          ) NOM_SERVICE,
          XFL.ID_FILE_XML,
          XFL.ID_REQUEST,
          XFL.NOM_FILE,
          XFL.ATTRIBUTE1 AS IND_PARAMETERS,
          (CASE WHEN (SELECT COUNT(1)
                     FROM XX_LMKTEDIAL.XXTDL_INT_XML_FILES_TAB XTB
                    WHERE XTB.ID_REQUEST       = XFL.ID_REQUEST
                      AND XTB.ID_SERVICE       = XFL.ID_SERVICE
                      AND XTB.ID_FILE_XML      = XFL.ID_FILE_XML
                      AND UPPER(IND_FILE_TYPE) = UPPER('REQUEST')
              ) > 0 THEN 'true'
              ELSE 'false'
              END
          ) AS SHOW_REQUEST,
          (CASE WHEN (SELECT COUNT(1)
                     FROM XX_LMKTEDIAL.XXTDL_INT_XML_FILES_TAB XTB
                    WHERE XTB.ID_REQUEST       = XFL.ID_REQUEST
                      AND XTB.ID_SERVICE       = XFL.ID_SERVICE
                      AND XTB.ID_FILE_XML      = XFL.ID_FILE_XML
                      AND UPPER(IND_FILE_TYPE) = UPPER('RESPONSE')
              ) > 0 THEN 'true'
              ELSE 'false'
              END
          ) AS SHOW_RESPONSE,
          SLOG.IND_PROCESS,
          (SELECT CSV.NOM_PARAMETER
             FROM XX_LMKTEDIAL.XXTDL_INT_CONFIG_PARAM_TAB CSV
            WHERE CSV.ID_PARAMETER = SLOG.IND_PROCESS
          ) IND_PROCESS_NOM,
          SLOG.IND_RESPONSE,
          SLOG.NUM_USER,
          SLOG.FEC_RESPONSE,
          SLOG.FEC_REQUEST,
          SLOG.NUM_PROCESS_ID,
          SLOG.NUM_PGM_PROCESS_ID,
          (SELECT DISTINCT CASE XTB.IND_ESTATUS
              WHEN 'R' THEN 'CREADO'
              WHEN 'C' THEN 'COMPLETO'
              WHEN 'E' THEN 'COMPLETO CON ERROR'
              WHEN 'L' THEN 'EN LANDMARK'
              WHEN 'F' THEN 'ERROR AL ENVIAR A LANDMARK'
	      WHEN 'M' THEN 'LEIDO, CON ERRORES EN PARADIGM'
	      WHEN 'W' THEN 'LEIDO, EN TABLAS DE PARADIGM'
              ELSE 'DESCONOCIDO'
              END CASE
             FROM XX_LMKTEDIAL.XXTDL_INT_XML_FILES_TAB XTB
            WHERE XTB.ID_REQUEST       = XFL.ID_REQUEST
              AND XTB.ID_SERVICE       = XFL.ID_SERVICE
              AND XTB.ID_FILE_XML      = XFL.ID_FILE_XML
          )
          AS IND_CALCULATE_STATUS,
          XFL.IND_ESTATUS,
          SLOG.ATTRIBUTE_CATEGORY,
          SLOG.ATTRIBUTE1,
          SLOG.ATTRIBUTE2,
          SLOG.ATTRIBUTE3,
          SLOG.ATTRIBUTE4,
          SLOG.ATTRIBUTE5,
          SLOG.ATTRIBUTE6,
          SLOG.ATTRIBUTE7,
          SLOG.ATTRIBUTE8,
          SLOG.ATTRIBUTE9,
          SLOG.ATTRIBUTE10,
          SLOG.ATTRIBUTE11,
          SLOG.ATTRIBUTE12,
          SLOG.ATTRIBUTE13,
          SLOG.ATTRIBUTE14,
          SLOG.ATTRIBUTE15,
          SLOG.FEC_CREATION_DATE,
          SLOG.NUM_CREATED_BY,
          XFL.FEC_LAST_UPDATE_DATE,
          SLOG.NUM_LAST_UPDATED_BY,
          SLOG.NUM_LAST_UPDATE_LOGIN
     FROM XX_LMKTEDIAL.XXTDL_INT_SERVICES_LOG_TAB SLOG,
          XX_LMKTEDIAL.XXTDL_INT_XML_FILES_TAB    XFL
    WHERE SLOG.ID_LOG_SERVICES = XFL.ID_REQUEST
      AND SLOG.ID_SERVICE      = XFL.ID_SERVICE;
