CREATE TABLE "FECXC"."CCM001" 
   (	"MONCOD" CHAR(2) NOT NULL ENABLE, 
	"MONDES" VARCHAR2(40), 
	"MONTPC" FLOAT(126), 
	"MONTPV" FLOAT(126) NOT NULL ENABLE, 
	"MONFCA" VARCHAR2(8), 
	"MONUSR" VARCHAR2(8), 
	"MONIMP" VARCHAR2(3), 
	"MONVTC" FLOAT(126), 
	"timestamp" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CCM001" ADD PRIMARY KEY ("MONCOD")
  USING INDEX  ENABLE;
