CREATE TABLE "FECXC"."CGE004" 
   (	"CGE1COD" CHAR(5) NOT NULL ENABLE, 
	"CGE3COD" NUMBER(*,0) NOT NULL ENABLE, 
	"CGE4VAL" VARCHAR2(100) NOT NULL ENABLE, 
	"TS_RVERSION" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CGE004" ADD PRIMARY KEY ("CGE1COD", "CGE3COD")
  USING INDEX  ENABLE;
ALTER TABLE "FECXC"."CGE004" ADD CONSTRAINT "FK_CGE004_CGE001" FOREIGN KEY ("CGE1COD")
	  REFERENCES "FECXC"."CGE001" ("CGE1COD") ENABLE;
ALTER TABLE "FECXC"."CGE004" ADD CONSTRAINT "FK_CGE004_CGE003" FOREIGN KEY ("CGE3COD")
	  REFERENCES "FECXC"."CGE003" ("CGE3COD") ENABLE;
