CREATE TABLE "FECXC"."CGE021" 
   (	"CGE20COD" NUMBER(*,0) NOT NULL ENABLE, 
	"CGE1COD" CHAR(5) NOT NULL ENABLE, 
	"CGE15COD" CHAR(4) NOT NULL ENABLE, 
	"CGE21FEC" TIMESTAMP (6) NOT NULL ENABLE, 
	"timestamp" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CGE021" ADD PRIMARY KEY ("CGE20COD", "CGE1COD", "CGE15COD")
  USING INDEX  ENABLE;
ALTER TABLE "FECXC"."CGE021" ADD CONSTRAINT "FK_CGE021_CGE015" FOREIGN KEY ("CGE15COD")
	  REFERENCES "FECXC"."CGE015" ("CGE15COD") ENABLE;
ALTER TABLE "FECXC"."CGE021" ADD CONSTRAINT "FK_CGE021_CGE001" FOREIGN KEY ("CGE1COD")
	  REFERENCES "FECXC"."CGE001" ("CGE1COD") ENABLE;
