CREATE TABLE "FECXC"."CGE013" 
   (	"CGE13COD" NUMBER(*,0) NOT NULL ENABLE, 
	"CGE13DES" VARCHAR2(40) NOT NULL ENABLE, 
	"CGE13MAR" VARCHAR2(40) NOT NULL ENABLE, 
	"CGE13VER" VARCHAR2(20) NOT NULL ENABLE, 
	"TS_RVERSION" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CGE013" ADD PRIMARY KEY ("CGE13COD")
  USING INDEX  ENABLE;
