CREATE TABLE "FECXC"."CGE017" 
   (	"CGE17COD" NUMBER(*,0) NOT NULL ENABLE, 
	"CGE17NOM" VARCHAR2(40) NOT NULL ENABLE, 
	"CGE17FAB" VARCHAR2(40) NOT NULL ENABLE, 
	"TS_RVERSION" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CGE017" ADD PRIMARY KEY ("CGE17COD")
  USING INDEX  ENABLE;
