CREATE TABLE "FECXC"."CGE007" 
   (	"CGE7COD" NUMBER(*,0) NOT NULL ENABLE, 
	"CGE7DES" VARCHAR2(40) NOT NULL ENABLE, 
	"CGE7FIS" VARCHAR2(30) NOT NULL ENABLE, 
	"CGE7RES" CHAR(1) NOT NULL ENABLE, 
	"CGE15COD" CHAR(4) NOT NULL ENABLE, 
	"TS_RVERSION" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CGE007" ADD PRIMARY KEY ("CGE7COD")
  USING INDEX  ENABLE;
ALTER TABLE "FECXC"."CGE007" ADD CONSTRAINT "FK_CGE007_CGE015" FOREIGN KEY ("CGE15COD")
	  REFERENCES "FECXC"."CGE015" ("CGE15COD") ENABLE;
