CREATE TABLE "FECXC"."CGE006" 
   (	"PR1COD" NUMBER(*,0) NOT NULL ENABLE, 
	"PR1NOM" VARCHAR2(50) NOT NULL ENABLE, 
	"timestamp" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CGE006" ADD PRIMARY KEY ("PR1COD")
  USING INDEX  ENABLE;
