CREATE TABLE "FECXC"."CGE022" 
   (	"CGE1COD" CHAR(5) NOT NULL ENABLE, 
	"CGE15COD" CHAR(4) NOT NULL ENABLE, 
	"CGE22FEC" TIMESTAMP (6) NOT NULL ENABLE, 
	"CGE10COD" NUMBER(*,0) NOT NULL ENABLE, 
	"CGE16CON" NUMBER(*,0) NOT NULL ENABLE, 
	"CGE14FEC" TIMESTAMP (6) NOT NULL ENABLE, 
	"CGE14USR" VARCHAR2(30) NOT NULL ENABLE, 
	"timestamp" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CGE022" ADD PRIMARY KEY ("CGE1COD", "CGE15COD", "CGE22FEC")
  USING INDEX  ENABLE;
ALTER TABLE "FECXC"."CGE022" ADD CONSTRAINT "FK_CGE022_CGE014" FOREIGN KEY ("CGE1COD", "CGE15COD")
	  REFERENCES "FECXC"."CGE014" ("CGE1COD", "CGE15COD") ENABLE;
