CREATE TABLE "FECXC"."CGE010" 
   (	"CGE1COD" CHAR(5) NOT NULL ENABLE, 
	"CGE10COD" NUMBER(*,0) NOT NULL ENABLE, 
	"CGE10NBD" VARCHAR2(40) NOT NULL ENABLE, 
	"CGE10USC" VARCHAR2(30), 
	"CGE10PSC" VARCHAR2(30), 
	"CGE10ACT" CHAR(1) NOT NULL ENABLE, 
	"CGE9COD" NUMBER(*,0) NOT NULL ENABLE, 
	"CGE17COD" NUMBER(*,0) NOT NULL ENABLE, 
	"CGE18CON" NUMBER(*,0) NOT NULL ENABLE, 
	"TS_RVERSION" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CGE010" ADD PRIMARY KEY ("CGE1COD", "CGE10COD")
  USING INDEX  ENABLE;
ALTER TABLE "FECXC"."CGE010" ADD CONSTRAINT "FK_CGE010_CGE001" FOREIGN KEY ("CGE1COD")
	  REFERENCES "FECXC"."CGE001" ("CGE1COD") ENABLE;
ALTER TABLE "FECXC"."CGE010" ADD CONSTRAINT "FK_CGE010_CGE009" FOREIGN KEY ("CGE9COD")
	  REFERENCES "FECXC"."CGE009" ("CGE9COD") ENABLE;
ALTER TABLE "FECXC"."CGE010" ADD CONSTRAINT "FK_CGE010_CGE018" FOREIGN KEY ("CGE17COD", "CGE18CON")
	  REFERENCES "FECXC"."CGE018" ("CGE17COD", "CGE18CON") ENABLE;
