CREATE TABLE "FECXC"."CGE025" 
   (	"CGE24COD" NUMBER(*,0) NOT NULL ENABLE, 
	"CGE15COD" CHAR(4) NOT NULL ENABLE, 
	"CGE16CON" NUMBER(*,0) NOT NULL ENABLE, 
	"CGE19CON" NUMBER(*,0) NOT NULL ENABLE, 
	"timestamp" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CGE025" ADD PRIMARY KEY ("CGE24COD", "CGE15COD", "CGE16CON", "CGE19CON")
  USING INDEX  ENABLE;
ALTER TABLE "FECXC"."CGE025" ADD CONSTRAINT "FK_CGE025_CGE024" FOREIGN KEY ("CGE24COD")
	  REFERENCES "FECXC"."CGE024" ("CGE24COD") ENABLE;
ALTER TABLE "FECXC"."CGE025" ADD CONSTRAINT "FK_CGE025_CGE019" FOREIGN KEY ("CGE15COD", "CGE16CON", "CGE19CON")
	  REFERENCES "FECXC"."CGE019" ("CGE15COD", "CGE16CON", "CGE19CON") ENABLE;
