CREATE TABLE "FECXC"."CGE015" 
   (	"CGE15COD" CHAR(4) NOT NULL ENABLE, 
	"CGE15NOM" VARCHAR2(40) NOT NULL ENABLE, 
	"CGE15URL" VARCHAR2(60), 
	"TS_RVERSION" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CGE015" ADD PRIMARY KEY ("CGE15COD")
  USING INDEX  ENABLE;
