CREATE TABLE "FECXC"."CGE008" 
   (	"CGE1COD" CHAR(5) NOT NULL ENABLE, 
	"CGE7COD" NUMBER(*,0) NOT NULL ENABLE, 
	"CGE10COD" NUMBER(*,0) NOT NULL ENABLE, 
	"CGE8TIP" CHAR(1) NOT NULL ENABLE, 
	"CGE8LON" NUMBER(*,0) NOT NULL ENABLE, 
	"CGE8RIN" NUMBER(*,0), 
	"CGE8RSU" NUMBER(*,0), 
	"CGE8MAS" VARCHAR2(20) NOT NULL ENABLE, 
	"TS_RVERSION" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CGE008" ADD PRIMARY KEY ("CGE1COD", "CGE7COD", "CGE10COD")
  USING INDEX  ENABLE;
ALTER TABLE "FECXC"."CGE008" ADD CONSTRAINT "FK_CGE008_CGE001" FOREIGN KEY ("CGE1COD")
	  REFERENCES "FECXC"."CGE001" ("CGE1COD") ENABLE;
ALTER TABLE "FECXC"."CGE008" ADD CONSTRAINT "FK_CGE008_CGE010" FOREIGN KEY ("CGE1COD", "CGE10COD")
	  REFERENCES "FECXC"."CGE010" ("CGE1COD", "CGE10COD") ENABLE;
ALTER TABLE "FECXC"."CGE008" ADD CONSTRAINT "FK_CGE008_CGE007" FOREIGN KEY ("CGE7COD")
	  REFERENCES "FECXC"."CGE007" ("CGE7COD") ENABLE;
