CREATE TABLE "FECXC"."CGEM02" 
   (	"CGEXORI" CHAR(2) NOT NULL ENABLE, 
	"CGEDORI" VARCHAR2(40) NOT NULL ENABLE, 
	"timestamp" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CGEM02" ADD PRIMARY KEY ("CGEXORI")
  USING INDEX  ENABLE;
