CREATE TABLE "FECXC"."CGET02" 
   (	"CGECBAT" NUMBER(*,0) NOT NULL ENABLE, 
	"CGEXFEC" TIMESTAMP (6) NOT NULL ENABLE, 
	"CGE1COD" CHAR(5) NOT NULL ENABLE, 
	"CGE5COD" VARCHAR2(5) NOT NULL ENABLE, 
	"CGE1EAF" CHAR(5) NOT NULL ENABLE, 
	"CGEXDES" VARCHAR2(30) NOT NULL ENABLE, 
	"CGE5SAF" CHAR(5) NOT NULL ENABLE, 
	"CGEXUSR" VARCHAR2(30) NOT NULL ENABLE, 
	"CGEXDEB" FLOAT(126) NOT NULL ENABLE, 
	"CGEXCRE" FLOAT(126) NOT NULL ENABLE, 
	"CGEXDOC" VARCHAR2(12) NOT NULL ENABLE, 
	"CGEXMON" FLOAT(126) NOT NULL ENABLE, 
	"MONCOD" CHAR(2) NOT NULL ENABLE, 
	"CGEXTCM" FLOAT(126) NOT NULL ENABLE, 
	"CGEXELI" CHAR(1) NOT NULL ENABLE, 
	"timestamp" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CGET02" ADD PRIMARY KEY ("CGECBAT")
  USING INDEX  ENABLE;
