CREATE TABLE "FECXC"."CGEX05" 
   (	"CGECBAT" NUMBER(*,0) NOT NULL ENABLE, 
	"CGECLIN" NUMBER(*,0) NOT NULL ENABLE, 
	"CGEXDOC" VARCHAR2(12) NOT NULL ENABLE, 
	"CGEXFEC" TIMESTAMP (6) NOT NULL ENABLE, 
	"CGE27COD" CHAR(2) NOT NULL ENABLE, 
	"CGE1COD" CHAR(5) NOT NULL ENABLE, 
	"CGE5COD" VARCHAR2(5) NOT NULL ENABLE, 
	"CGEXMON" FLOAT(126) NOT NULL ENABLE, 
	"MONCOD" CHAR(2) NOT NULL ENABLE, 
	"CGEXTCM" FLOAT(126) NOT NULL ENABLE, 
	"CGM1ID" NUMBER(*,0), 
	"CGM1IM" CHAR(4) NOT NULL ENABLE, 
	"CGM1CD" VARCHAR2(100) NOT NULL ENABLE, 
	"CGEXTIP" CHAR(1) NOT NULL ENABLE, 
	"CGEXELI" CHAR(1) NOT NULL ENABLE, 
	"CGEXRF1" VARCHAR2(12), 
	"CGEXRF2" VARCHAR2(12), 
	"timestamp" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CGEX05" ADD PRIMARY KEY ("CGECBAT", "CGECLIN")
  USING INDEX  ENABLE;
ALTER TABLE "FECXC"."CGEX05" ADD CONSTRAINT "FK_CGEX05_CCM001" FOREIGN KEY ("MONCOD")
	  REFERENCES "FECXC"."CCM001" ("MONCOD") ENABLE;
ALTER TABLE "FECXC"."CGEX05" ADD CONSTRAINT "FK_CGEX05_CGEX04" FOREIGN KEY ("CGECBAT")
	  REFERENCES "FECXC"."CGEX04" ("CGECBAT") ENABLE;
ALTER TABLE "FECXC"."CGEX05" ADD CONSTRAINT "FK_CGEX05_CGE027" FOREIGN KEY ("CGE27COD")
	  REFERENCES "FECXC"."CGE027" ("CGE27COD") ENABLE;
ALTER TABLE "FECXC"."CGEX05" ADD CONSTRAINT "FK_CGEX05_CGE005" FOREIGN KEY ("CGE1COD", "CGE5COD")
	  REFERENCES "FECXC"."CGE005" ("CGE1COD", "CGE5COD") ENABLE;
