CREATE TABLE "FECXC"."CGM001" 
   (	"CG15ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CGM1ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CGM1IM" CHAR(4), 
	"CGM1CD" VARCHAR2(100), 
	"CGM1IP" NUMBER(*,0), 
	"CGM1NI" NUMBER(*,0) NOT NULL ENABLE, 
	"CGM1IC" NUMBER(*,0), 
	"CTADES" VARCHAR2(100), 
	"CTAEDI" CHAR(1), 
	"CTAFEC" VARCHAR2(8), 
	"CTAMOV" CHAR(1), 
	"CTANIV" CHAR(1), 
	"CTASAL" CHAR(1), 
	"CTATIP" CHAR(1), 
	"CTAUSU" VARCHAR2(10), 
	"CTABAL" CHAR(1) NOT NULL ENABLE, 
	"CTAREF" CHAR(1), 
	"CTAEFE" CHAR(1), 
	"CTADOL" CHAR(1), 
	"CTADEF" VARCHAR2(40), 
	"CTAAUX" CHAR(1), 
	"CGM1AU" NUMBER(*,0) NOT NULL ENABLE, 
	"CGM1RE" VARCHAR2(255), 
	"CGM1FI" VARCHAR2(100), 
	"timestamp" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."CGM001" ADD PRIMARY KEY ("CGM1ID")
  USING INDEX  ENABLE;
