CREATE TABLE "FECXC"."ENTIDADES" 
   (	"entidad" VARCHAR2(30) NOT NULL ENABLE, 
	"descripcion" VARCHAR2(40) NOT NULL ENABLE, 
	"timestamp" TIMESTAMP (6)
   ) ;
ALTER TABLE "FECXC"."ENTIDADES" ADD PRIMARY KEY ("entidad")
  USING INDEX  ENABLE;
