CREATE TABLE "FECXC"."EUL4_BAS" 
   (	"BA_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BA_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"BA_DEVELOPER_KEY" VARCHAR2(100) NOT NULL ENABLE, 
	"BA_DESCRIPTION" VARCHAR2(240), 
	"BA_EXT_NAME" VARCHAR2(64), 
	"BA_USER_PROP1" VARCHAR2(100), 
	"BA_USER_PROP2" VARCHAR2(100), 
	"BA_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"BA_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"BA_CREATED_DATE" DATE NOT NULL ENABLE, 
	"BA_UPDATED_BY" VARCHAR2(64), 
	"BA_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_BA_PK" ON "FECXC"."EUL4_BAS" ("BA_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_BA_UK_1" ON "FECXC"."EUL4_BAS" ("BA_DEVELOPER_KEY") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_BA_UK_2" ON "FECXC"."EUL4_BAS" ("BA_NAME") 
  ;
ALTER TABLE "FECXC"."EUL4_BAS" ADD CONSTRAINT "EUL4_BA_PK" PRIMARY KEY ("BA_ID")
  USING INDEX "FECXC"."EUL4_BA_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_BAS" ADD CONSTRAINT "EUL4_BA_UK_1" UNIQUE ("BA_DEVELOPER_KEY")
  USING INDEX "FECXC"."EUL4_BA_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_BAS" ADD CONSTRAINT "EUL4_BA_UK_2" UNIQUE ("BA_NAME")
  USING INDEX "FECXC"."EUL4_BA_UK_2"  ENABLE;
