CREATE TABLE "FECXC"."EUL4_BQ_TABLES" 
   (	"BQT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BQT_BQ_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BQT_BRR_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BQT_TABLE_NAME" VARCHAR2(64) NOT NULL ENABLE, 
	"BQT_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"BQT_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"BQT_CREATED_DATE" DATE NOT NULL ENABLE, 
	"BQT_UPDATED_BY" VARCHAR2(64), 
	"BQT_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_BQT_UK_1" ON "FECXC"."EUL4_BQ_TABLES" ("BQT_TABLE_NAME") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_BQT_UK_2" ON "FECXC"."EUL4_BQ_TABLES" ("BQT_BQ_ID", "BQT_BRR_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_BQT_PK" ON "FECXC"."EUL4_BQ_TABLES" ("BQT_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_BQ_TABLES" ADD CONSTRAINT "EUL4_BQT_UK_1" UNIQUE ("BQT_TABLE_NAME")
  USING INDEX "FECXC"."EUL4_BQT_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_BQ_TABLES" ADD CONSTRAINT "EUL4_BQT_UK_2" UNIQUE ("BQT_BQ_ID", "BQT_BRR_ID")
  USING INDEX "FECXC"."EUL4_BQT_UK_2"  ENABLE;
ALTER TABLE "FECXC"."EUL4_BQ_TABLES" ADD CONSTRAINT "EUL4_BQT_PK" PRIMARY KEY ("BQT_ID")
  USING INDEX "FECXC"."EUL4_BQT_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_BQ_TABLES" ADD CONSTRAINT "EUL4_BQT_BQ_FK" FOREIGN KEY ("BQT_BQ_ID")
	  REFERENCES "FECXC"."EUL4_BATCH_QUERIES" ("BQ_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_BQ_TABLES" ADD CONSTRAINT "EUL4_BQT_BRR_FK" FOREIGN KEY ("BQT_BRR_ID")
	  REFERENCES "FECXC"."EUL4_BR_RUNS" ("BRR_ID") ENABLE;
