CREATE TABLE "FECXC"."EUL4_VERSIONS" 
   (	"VER_NAME" VARCHAR2(100), 
	"VER_DESCRIPTION" VARCHAR2(240), 
	"VER_RELEASE" VARCHAR2(30) NOT NULL ENABLE, 
	"VER_MIN_CODE_VER" VARCHAR2(30) NOT NULL ENABLE, 
	"VER_EUL_TIMESTAMP" VARCHAR2(30) NOT NULL ENABLE, 
	"VER_SA" NUMBER(22,0)
   ) ;
