CREATE TABLE "FECXC"."EUL4_BA_OBJ_LINKS" 
   (	"BOL_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BOL_BA_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BOL_OBJ_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BOL_SEQUENCE" NUMBER(22,0), 
	"BOL_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"BOL_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"BOL_CREATED_DATE" DATE NOT NULL ENABLE, 
	"BOL_UPDATED_BY" VARCHAR2(64), 
	"BOL_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_BOL_UK_1" ON "FECXC"."EUL4_BA_OBJ_LINKS" ("BOL_BA_ID", "BOL_OBJ_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_BOL_PK" ON "FECXC"."EUL4_BA_OBJ_LINKS" ("BOL_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_BA_OBJ_LINKS" ADD CONSTRAINT "EUL4_BOL_UK_1" UNIQUE ("BOL_BA_ID", "BOL_OBJ_ID")
  USING INDEX "FECXC"."EUL4_BOL_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_BA_OBJ_LINKS" ADD CONSTRAINT "EUL4_BOL_PK" PRIMARY KEY ("BOL_ID")
  USING INDEX "FECXC"."EUL4_BOL_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_BA_OBJ_LINKS" ADD CONSTRAINT "EUL4_BOL_BA_FK" FOREIGN KEY ("BOL_BA_ID")
	  REFERENCES "FECXC"."EUL4_BAS" ("BA_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_BA_OBJ_LINKS" ADD CONSTRAINT "EUL4_BOL_OBJ_FK" FOREIGN KEY ("BOL_OBJ_ID")
	  REFERENCES "FECXC"."EUL4_OBJS" ("OBJ_ID") ENABLE;
