CREATE TABLE "FECXC"."EUL4_SUB_QUERIES" 
   (	"SQ_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SQ_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"SQ_DEVELOPER_KEY" VARCHAR2(100) NOT NULL ENABLE, 
	"SQ_DESCRIPTION" VARCHAR2(240), 
	"SQ_OBJ_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SQ_IT_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SQ_FIL_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SQ_USER_PROP2" VARCHAR2(100), 
	"SQ_USER_PROP1" VARCHAR2(100), 
	"SQ_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"SQ_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"SQ_CREATED_DATE" DATE NOT NULL ENABLE, 
	"SQ_UPDATED_BY" VARCHAR2(64), 
	"SQ_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_SQ_UK_2" ON "FECXC"."EUL4_SUB_QUERIES" ("SQ_FIL_ID", "SQ_NAME") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_SQ_PK" ON "FECXC"."EUL4_SUB_QUERIES" ("SQ_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_SQ_UK_1" ON "FECXC"."EUL4_SUB_QUERIES" ("SQ_FIL_ID", "SQ_DEVELOPER_KEY") 
  ;
ALTER TABLE "FECXC"."EUL4_SUB_QUERIES" ADD CONSTRAINT "EUL4_SQ_UK_2" UNIQUE ("SQ_FIL_ID", "SQ_NAME")
  USING INDEX "FECXC"."EUL4_SQ_UK_2"  ENABLE;
ALTER TABLE "FECXC"."EUL4_SUB_QUERIES" ADD CONSTRAINT "EUL4_SQ_PK" PRIMARY KEY ("SQ_ID")
  USING INDEX "FECXC"."EUL4_SQ_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_SUB_QUERIES" ADD CONSTRAINT "EUL4_SQ_UK_1" UNIQUE ("SQ_FIL_ID", "SQ_DEVELOPER_KEY")
  USING INDEX "FECXC"."EUL4_SQ_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_SUB_QUERIES" ADD CONSTRAINT "EUL4_SQ_FIL_FK" FOREIGN KEY ("SQ_FIL_ID")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_SUB_QUERIES" ADD CONSTRAINT "EUL4_SQ_IT_FK" FOREIGN KEY ("SQ_IT_ID")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_SUB_QUERIES" ADD CONSTRAINT "EUL4_SQ_OBJ_FK" FOREIGN KEY ("SQ_OBJ_ID")
	  REFERENCES "FECXC"."EUL4_OBJS" ("OBJ_ID") ENABLE;
