CREATE TABLE "FECXC"."EUL4_ACCESS_PRIVS" 
   (	"AP_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"AP_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"AP_EU_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"AP_PRIV_LEVEL" NUMBER(2,0) NOT NULL ENABLE, 
	"GP_APP_ID" NUMBER(10,0), 
	"GBA_BA_ID" NUMBER(10,0), 
	"GD_DOC_ID" NUMBER(10,0), 
	"AP_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"AP_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"AP_CREATED_DATE" DATE NOT NULL ENABLE, 
	"AP_UPDATED_BY" VARCHAR2(64), 
	"AP_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_AP_PK" ON "FECXC"."EUL4_ACCESS_PRIVS" ("AP_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_AP_UK_1" ON "FECXC"."EUL4_ACCESS_PRIVS" ("GP_APP_ID", "GBA_BA_ID", "GD_DOC_ID", "AP_EU_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_ACCESS_PRIVS" ADD CONSTRAINT "EUL4_AP_PK" PRIMARY KEY ("AP_ID")
  USING INDEX "FECXC"."EUL4_AP_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_ACCESS_PRIVS" ADD CONSTRAINT "EUL4_AP_CHECK_2" CHECK (    ap_priv_level IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_ACCESS_PRIVS" ADD CONSTRAINT "EUL4_AP_UK_1" UNIQUE ("GP_APP_ID", "GBA_BA_ID", "GD_DOC_ID", "AP_EU_ID")
  USING INDEX "FECXC"."EUL4_AP_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_ACCESS_PRIVS" ADD CONSTRAINT "EUL4_AP_CHECK_1" CHECK (    ap_type IN ( 'GBA' , 'GP', 'GD' )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_ACCESS_PRIVS" ADD CONSTRAINT "EUL4_AP_EU_FK" FOREIGN KEY ("AP_EU_ID")
	  REFERENCES "FECXC"."EUL4_EUL_USERS" ("EU_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_ACCESS_PRIVS" ADD CONSTRAINT "EUL4_GBA_BA_FK" FOREIGN KEY ("GBA_BA_ID")
	  REFERENCES "FECXC"."EUL4_BAS" ("BA_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_ACCESS_PRIVS" ADD CONSTRAINT "EUL4_GD_DOC_FK" FOREIGN KEY ("GD_DOC_ID")
	  REFERENCES "FECXC"."EUL4_DOCUMENTS" ("DOC_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_ACCESS_PRIVS" ADD CONSTRAINT "EUL4_GP_PRI_FK" FOREIGN KEY ("GP_APP_ID")
	  REFERENCES "FECXC"."EUL4_APP_PARAMS" ("APP_ID") ENABLE;
