CREATE TABLE "FECXC"."EUL4_FREQ_UNITS" 
   (	"RFU_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"RFU_NAME_MN" NUMBER(10,0) NOT NULL ENABLE, 
	"RFU_SQL_EXPRESSION" VARCHAR2(240) NOT NULL ENABLE, 
	"RFU_SEQUENCE" NUMBER(22,0), 
	"RFU_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"RFU_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"RFU_CREATED_DATE" DATE NOT NULL ENABLE, 
	"RFU_UPDATED_BY" VARCHAR2(64), 
	"RFU_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_RFU_UK_1" ON "FECXC"."EUL4_FREQ_UNITS" ("RFU_NAME_MN") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_RFU_PK" ON "FECXC"."EUL4_FREQ_UNITS" ("RFU_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_FREQ_UNITS" ADD CONSTRAINT "EUL4_RFU_UK_1" UNIQUE ("RFU_NAME_MN")
  USING INDEX "FECXC"."EUL4_RFU_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_FREQ_UNITS" ADD CONSTRAINT "EUL4_RFU_PK" PRIMARY KEY ("RFU_ID")
  USING INDEX "FECXC"."EUL4_RFU_PK"  ENABLE;
