CREATE TABLE "FECXC"."EUL4_HI_NODES" 
   (	"HN_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"HN_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"HN_DEVELOPER_KEY" VARCHAR2(100) NOT NULL ENABLE, 
	"HN_DESCRIPTION" VARCHAR2(240), 
	"HN_HI_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"HN_EXT_NODE" VARCHAR2(64), 
	"HN_USER_PROP2" VARCHAR2(100), 
	"HN_USER_PROP1" VARCHAR2(100), 
	"HN_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"HN_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"HN_CREATED_DATE" DATE NOT NULL ENABLE, 
	"HN_UPDATED_BY" VARCHAR2(64), 
	"HN_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_HN_PK" ON "FECXC"."EUL4_HI_NODES" ("HN_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_HN_UK_2" ON "FECXC"."EUL4_HI_NODES" ("HN_HI_ID", "HN_NAME") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_HN_UK_1" ON "FECXC"."EUL4_HI_NODES" ("HN_HI_ID", "HN_DEVELOPER_KEY") 
  ;
ALTER TABLE "FECXC"."EUL4_HI_NODES" ADD CONSTRAINT "EUL4_HN_PK" PRIMARY KEY ("HN_ID")
  USING INDEX "FECXC"."EUL4_HN_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_HI_NODES" ADD CONSTRAINT "EUL4_HN_UK_2" UNIQUE ("HN_HI_ID", "HN_NAME")
  USING INDEX "FECXC"."EUL4_HN_UK_2"  ENABLE;
ALTER TABLE "FECXC"."EUL4_HI_NODES" ADD CONSTRAINT "EUL4_HN_UK_1" UNIQUE ("HN_HI_ID", "HN_DEVELOPER_KEY")
  USING INDEX "FECXC"."EUL4_HN_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_HI_NODES" ADD CONSTRAINT "EUL4_HN_IBH_FK" FOREIGN KEY ("HN_HI_ID")
	  REFERENCES "FECXC"."EUL4_HIERARCHIES" ("HI_ID") ENABLE;
