CREATE TABLE "FECXC"."EUL4_SQ_CRRLTNS" 
   (	"SQC_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SQC_SQ_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SQC_IT_INNER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SQC_IT_OUTER_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SQC_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"SQC_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"SQC_CREATED_DATE" DATE NOT NULL ENABLE, 
	"SQC_UPDATED_BY" VARCHAR2(64), 
	"SQC_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_SQC_UK_1" ON "FECXC"."EUL4_SQ_CRRLTNS" ("SQC_SQ_ID", "SQC_IT_INNER_ID", "SQC_IT_OUTER_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_SQC_PK" ON "FECXC"."EUL4_SQ_CRRLTNS" ("SQC_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_SQ_CRRLTNS" ADD CONSTRAINT "EUL4_SQC_UK_1" UNIQUE ("SQC_SQ_ID", "SQC_IT_INNER_ID", "SQC_IT_OUTER_ID")
  USING INDEX "FECXC"."EUL4_SQC_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_SQ_CRRLTNS" ADD CONSTRAINT "EUL4_SQC_PK" PRIMARY KEY ("SQC_ID")
  USING INDEX "FECXC"."EUL4_SQC_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_SQ_CRRLTNS" ADD CONSTRAINT "EUL4_SQC_IT_I_FK" FOREIGN KEY ("SQC_IT_INNER_ID")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_SQ_CRRLTNS" ADD CONSTRAINT "EUL4_SQC_IT_O_FK" FOREIGN KEY ("SQC_IT_OUTER_ID")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_SQ_CRRLTNS" ADD CONSTRAINT "EUL4_SQC_SQ_FK" FOREIGN KEY ("SQC_SQ_ID")
	  REFERENCES "FECXC"."EUL4_SUB_QUERIES" ("SQ_ID") ENABLE;
