CREATE TABLE "FECXC"."EUL4_APP_PARAMS" 
   (	"APP_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"APP_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"APP_NAME_MN" NUMBER(10,0) NOT NULL ENABLE, 
	"APP_DESCRIPTION_MN" NUMBER(10,0) NOT NULL ENABLE, 
	"SP_DEFAULT_VALUE" VARCHAR2(240), 
	"SP_VALUE" VARCHAR2(240), 
	"APP_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"APP_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"APP_CREATED_DATE" DATE NOT NULL ENABLE, 
	"APP_UPDATED_BY" VARCHAR2(64), 
	"APP_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_APP_UK_1" ON "FECXC"."EUL4_APP_PARAMS" ("APP_NAME_MN") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_APP_PK" ON "FECXC"."EUL4_APP_PARAMS" ("APP_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_APP_PARAMS" ADD CONSTRAINT "EUL4_APP_CHECK_1" CHECK (    app_type IN ( 'PRI' , 'SP' )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_APP_PARAMS" ADD CONSTRAINT "EUL4_APP_UK_1" UNIQUE ("APP_NAME_MN")
  USING INDEX "FECXC"."EUL4_APP_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_APP_PARAMS" ADD CONSTRAINT "EUL4_APP_PK" PRIMARY KEY ("APP_ID")
  USING INDEX "FECXC"."EUL4_APP_PK"  ENABLE;
