CREATE TABLE "FECXC"."EUL4_SUMO_EXP_USGS" 
   (	"SEU_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SEU_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"SEU_SUMO_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SEU_EXT_COLUMN" VARCHAR2(64), 
	"SEU_VISIBLE" NUMBER(1,0) NOT NULL ENABLE, 
	"SIU_EXP_ID" NUMBER(10,0), 
	"SIU_ITEM_MODIFIED" NUMBER(1,0), 
	"SMIU_FUN_ID" NUMBER(10,0), 
	"SFU_FUN_ID" NUMBER(10,0), 
	"SEU_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"SEU_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"SEU_CREATED_DATE" DATE NOT NULL ENABLE, 
	"SEU_UPDATED_BY" VARCHAR2(64), 
	"SEU_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_SEU_PK" ON "FECXC"."EUL4_SUMO_EXP_USGS" ("SEU_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_SEU_UK_1" ON "FECXC"."EUL4_SUMO_EXP_USGS" ("SEU_TYPE", "SEU_SUMO_ID", "SIU_EXP_ID", "SMIU_FUN_ID", "SFU_FUN_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_SUMO_EXP_USGS" ADD CONSTRAINT "EUL4_SEU_PK" PRIMARY KEY ("SEU_ID")
  USING INDEX "FECXC"."EUL4_SEU_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_SUMO_EXP_USGS" ADD CONSTRAINT "EUL4_SEU_UK_1" UNIQUE ("SEU_TYPE", "SEU_SUMO_ID", "SIU_EXP_ID", "SMIU_FUN_ID", "SFU_FUN_ID")
  USING INDEX "FECXC"."EUL4_SEU_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_SUMO_EXP_USGS" ADD CONSTRAINT "EUL4_SEU_CHECK_1" CHECK (    seu_type IN ( 'SAIU' , 'SMIU' , 'SFU' )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_SUMO_EXP_USGS" ADD CONSTRAINT "EUL4_SEU_CHECK_2" CHECK (    siu_item_modified IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_SUMO_EXP_USGS" ADD CONSTRAINT "EUL4_SEU_CHECK_3" CHECK (    seu_visible IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_SUMO_EXP_USGS" ADD CONSTRAINT "EUL4_SEU_SUMO_FK" FOREIGN KEY ("SEU_SUMO_ID")
	  REFERENCES "FECXC"."EUL4_SUMMARY_OBJS" ("SUMO_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_SUMO_EXP_USGS" ADD CONSTRAINT "EUL4_SFU_FUN_FK" FOREIGN KEY ("SFU_FUN_ID")
	  REFERENCES "FECXC"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_SUMO_EXP_USGS" ADD CONSTRAINT "EUL4_SIU_IT_FK" FOREIGN KEY ("SIU_EXP_ID")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_SUMO_EXP_USGS" ADD CONSTRAINT "EUL4_SMIU_FUN_FK" FOREIGN KEY ("SMIU_FUN_ID")
	  REFERENCES "FECXC"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
