CREATE TABLE "FECXC"."EUL4_IG_EXP_LINKS" 
   (	"IEL_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"IEL_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"HIL_EXP_ID" NUMBER(10,0), 
	"HIL_HN_ID" NUMBER(10,0), 
	"KIL_EXP_ID" NUMBER(10,0), 
	"KIL_KEY_ID" NUMBER(10,0), 
	"KIL_SEQUENCE" NUMBER(22,0), 
	"IEL_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"IEL_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"IEL_CREATED_DATE" DATE NOT NULL ENABLE, 
	"IEL_UPDATED_BY" VARCHAR2(64), 
	"IEL_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_IEL_UK_1" ON "FECXC"."EUL4_IG_EXP_LINKS" ("KIL_EXP_ID", "KIL_KEY_ID", "HIL_EXP_ID", "HIL_HN_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_IEL_PK" ON "FECXC"."EUL4_IG_EXP_LINKS" ("IEL_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_IG_EXP_LINKS" ADD CONSTRAINT "EUL4_IEL_CHECK_1" CHECK (    iel_type in ('HIL', 'KIL')    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_IG_EXP_LINKS" ADD CONSTRAINT "EUL4_IEL_UK_1" UNIQUE ("KIL_EXP_ID", "KIL_KEY_ID", "HIL_EXP_ID", "HIL_HN_ID")
  USING INDEX "FECXC"."EUL4_IEL_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_IG_EXP_LINKS" ADD CONSTRAINT "EUL4_IEL_PK" PRIMARY KEY ("IEL_ID")
  USING INDEX "FECXC"."EUL4_IEL_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_IG_EXP_LINKS" ADD CONSTRAINT "EUL4_HIL_IT_FK" FOREIGN KEY ("HIL_EXP_ID")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_IG_EXP_LINKS" ADD CONSTRAINT "EUL4_KIL_IT_FK" FOREIGN KEY ("KIL_EXP_ID")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_IG_EXP_LINKS" ADD CONSTRAINT "EUL4_KIL_KEY_FK" FOREIGN KEY ("KIL_KEY_ID")
	  REFERENCES "FECXC"."EUL4_KEY_CONS" ("KEY_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_IG_EXP_LINKS" ADD CONSTRAINT "EUL4_HIL_HN_FK" FOREIGN KEY ("HIL_HN_ID")
	  REFERENCES "FECXC"."EUL4_HI_NODES" ("HN_ID") ENABLE;
