CREATE TABLE "FECXC"."EUL4_ASMP_CONS" 
   (	"APC_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"APC_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"APC_CONS_TYPE" NUMBER(2,0) NOT NULL ENABLE, 
	"APC_ASMP_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"AOC_OBJ_ID" NUMBER(10,0), 
	"ASOC_SUMO_ID" NUMBER(10,0), 
	"AUC_EU_ID" NUMBER(10,0), 
	"APC_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"APC_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"APC_CREATED_DATE" DATE NOT NULL ENABLE, 
	"APC_UPDATED_BY" VARCHAR2(64), 
	"APC_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_APC_PK" ON "FECXC"."EUL4_ASMP_CONS" ("APC_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_APC_UK_1" ON "FECXC"."EUL4_ASMP_CONS" ("APC_ASMP_ID", "ASOC_SUMO_ID", "AUC_EU_ID", "AOC_OBJ_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_ASMP_CONS" ADD CONSTRAINT "EUL4_APC_CHECK_1" CHECK (    apc_type in ('AOC','ASOC','AUC')    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_ASMP_CONS" ADD CONSTRAINT "EUL4_APC_CHECK_2" CHECK (    apc_cons_type in (1,2)    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_ASMP_CONS" ADD CONSTRAINT "EUL4_APC_PK" PRIMARY KEY ("APC_ID")
  USING INDEX "FECXC"."EUL4_APC_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_ASMP_CONS" ADD CONSTRAINT "EUL4_APC_UK_1" UNIQUE ("APC_ASMP_ID", "ASOC_SUMO_ID", "AUC_EU_ID", "AOC_OBJ_ID")
  USING INDEX "FECXC"."EUL4_APC_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_ASMP_CONS" ADD CONSTRAINT "EUL4_AOC_OBJ_FK" FOREIGN KEY ("AOC_OBJ_ID")
	  REFERENCES "FECXC"."EUL4_OBJS" ("OBJ_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_ASMP_CONS" ADD CONSTRAINT "EUL4_APC_ASMP_FK" FOREIGN KEY ("APC_ASMP_ID")
	  REFERENCES "FECXC"."EUL4_ASM_POLICIES" ("ASMP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_ASMP_CONS" ADD CONSTRAINT "EUL4_ASOC_SUMO_FK" FOREIGN KEY ("ASOC_SUMO_ID")
	  REFERENCES "FECXC"."EUL4_SUMMARY_OBJS" ("SUMO_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_ASMP_CONS" ADD CONSTRAINT "EUL4_AUC_EU_FK" FOREIGN KEY ("AUC_EU_ID")
	  REFERENCES "FECXC"."EUL4_EUL_USERS" ("EU_ID") ENABLE;
