CREATE TABLE "FECXC"."EUL4_FUN_ARGUMENTS" 
   (	"FA_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"FA_NAME_S" VARCHAR2(100), 
	"FA_NAME_MN" NUMBER(10,0), 
	"FA_DEVELOPER_KEY" VARCHAR2(100) NOT NULL ENABLE, 
	"FA_DESCRIPTION_S" VARCHAR2(240), 
	"FA_DESCRIPTION_MN" NUMBER(10,0), 
	"FA_DATA_TYPE" NUMBER(2,0) NOT NULL ENABLE, 
	"FA_OPTIONAL" NUMBER(1,0) NOT NULL ENABLE, 
	"FA_POSITION" NUMBER(22,0) NOT NULL ENABLE, 
	"FA_FUN_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"FA_USER_PROP2" VARCHAR2(100), 
	"FA_USER_PROP1" VARCHAR2(100), 
	"FA_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"FA_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"FA_CREATED_DATE" DATE NOT NULL ENABLE, 
	"FA_UPDATED_BY" VARCHAR2(64), 
	"FA_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_FA_UK_1" ON "FECXC"."EUL4_FUN_ARGUMENTS" ("FA_DEVELOPER_KEY", "FA_FUN_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_FA_UK_3" ON "FECXC"."EUL4_FUN_ARGUMENTS" ("FA_NAME_MN", "FA_NAME_S", "FA_FUN_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_FA_PK" ON "FECXC"."EUL4_FUN_ARGUMENTS" ("FA_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_FA_UK_2" ON "FECXC"."EUL4_FUN_ARGUMENTS" ("FA_POSITION", "FA_FUN_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_FUN_ARGUMENTS" ADD CONSTRAINT "EUL4_FA_UK_1" UNIQUE ("FA_DEVELOPER_KEY", "FA_FUN_ID")
  USING INDEX "FECXC"."EUL4_FA_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_FUN_ARGUMENTS" ADD CONSTRAINT "EUL4_FA_CHECK_2" CHECK (    fa_data_type IN (0,1,2,3,4,5,6,7,8,9,10,11,12,13)    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_FUN_ARGUMENTS" ADD CONSTRAINT "EUL4_FA_CHECK_3" CHECK (    fa_optional IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_FUN_ARGUMENTS" ADD CONSTRAINT "EUL4_FA_UK_3" UNIQUE ("FA_NAME_MN", "FA_NAME_S", "FA_FUN_ID")
  USING INDEX "FECXC"."EUL4_FA_UK_3"  ENABLE;
ALTER TABLE "FECXC"."EUL4_FUN_ARGUMENTS" ADD CONSTRAINT "EUL4_FA_PK" PRIMARY KEY ("FA_ID")
  USING INDEX "FECXC"."EUL4_FA_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_FUN_ARGUMENTS" ADD CONSTRAINT "EUL4_FA_UK_2" UNIQUE ("FA_POSITION", "FA_FUN_ID")
  USING INDEX "FECXC"."EUL4_FA_UK_2"  ENABLE;
ALTER TABLE "FECXC"."EUL4_FUN_ARGUMENTS" ADD CONSTRAINT "EUL4_FA_CHECK_1" CHECK (    fa_name_s is not null or fa_name_mn is not null    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_FUN_ARGUMENTS" ADD CONSTRAINT "EUL4_FA_FUN_FK" FOREIGN KEY ("FA_FUN_ID")
	  REFERENCES "FECXC"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
