CREATE TABLE "FECXC"."EUL4_ASMP_LOGS" 
   (	"APL_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"APL_TIMESTAMP" DATE NOT NULL ENABLE, 
	"APL_EVENT_TYPE" NUMBER(2,0) NOT NULL ENABLE, 
	"APL_ASMP_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"APL_SUMO_ID" NUMBER(10,0), 
	"APL_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"APL_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"APL_CREATED_DATE" DATE NOT NULL ENABLE, 
	"APL_UPDATED_BY" VARCHAR2(64), 
	"APL_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_APL_PK" ON "FECXC"."EUL4_ASMP_LOGS" ("APL_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_ASMP_LOGS" ADD CONSTRAINT "EUL4_APL_PK" PRIMARY KEY ("APL_ID")
  USING INDEX "FECXC"."EUL4_APL_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_ASMP_LOGS" ADD CONSTRAINT "EUL4_APL_CHECK_1" CHECK (    apl_event_type in (0,1,2)    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_ASMP_LOGS" ADD CONSTRAINT "EUL4_APL_ASMP_FK" FOREIGN KEY ("APL_ASMP_ID")
	  REFERENCES "FECXC"."EUL4_ASM_POLICIES" ("ASMP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_ASMP_LOGS" ADD CONSTRAINT "EUL4_APL_SUMO_FK" FOREIGN KEY ("APL_SUMO_ID")
	  REFERENCES "FECXC"."EUL4_SUMMARY_OBJS" ("SUMO_ID") ENABLE;
