CREATE TABLE "FECXC"."EUL4_OBJ_DEPS" 
   (	"OD_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"OD_OBJ_ID_FROM" NUMBER(10,0) NOT NULL ENABLE, 
	"OD_OBJ_ID_TO" NUMBER(10,0) NOT NULL ENABLE, 
	"OD_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"OD_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"OD_CREATED_DATE" DATE NOT NULL ENABLE, 
	"OD_UPDATED_BY" VARCHAR2(64), 
	"OD_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_OD_PK" ON "FECXC"."EUL4_OBJ_DEPS" ("OD_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_OD_UK_1" ON "FECXC"."EUL4_OBJ_DEPS" ("OD_OBJ_ID_FROM", "OD_OBJ_ID_TO") 
  ;
ALTER TABLE "FECXC"."EUL4_OBJ_DEPS" ADD CONSTRAINT "EUL4_OD_CHECK_1" CHECK (    od_obj_id_from != od_obj_id_to    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJ_DEPS" ADD CONSTRAINT "EUL4_OD_PK" PRIMARY KEY ("OD_ID")
  USING INDEX "FECXC"."EUL4_OD_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJ_DEPS" ADD CONSTRAINT "EUL4_OD_UK_1" UNIQUE ("OD_OBJ_ID_FROM", "OD_OBJ_ID_TO")
  USING INDEX "FECXC"."EUL4_OD_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJ_DEPS" ADD CONSTRAINT "EUL4_OD_COBJ_FK" FOREIGN KEY ("OD_OBJ_ID_FROM")
	  REFERENCES "FECXC"."EUL4_OBJS" ("OBJ_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJ_DEPS" ADD CONSTRAINT "EUL4_OD_OBJ_FK" FOREIGN KEY ("OD_OBJ_ID_TO")
	  REFERENCES "FECXC"."EUL4_OBJS" ("OBJ_ID") ENABLE;
