CREATE TABLE "FECXC"."EUL4_HI_SEGMENTS" 
   (	"HS_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"HS_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"DHS_HI_ID" NUMBER(10,0), 
	"DHS_DHN_ID_CHILD" NUMBER(10,0), 
	"DHS_DHN_ID_PARENT" NUMBER(10,0), 
	"IHS_HN_ID_CHILD" NUMBER(10,0), 
	"IHS_HN_ID_PARENT" NUMBER(10,0), 
	"IHS_HI_ID" NUMBER(10,0), 
	"HS_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"HS_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"HS_CREATED_DATE" DATE NOT NULL ENABLE, 
	"HS_UPDATED_BY" VARCHAR2(64), 
	"HS_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_HS_PK" ON "FECXC"."EUL4_HI_SEGMENTS" ("HS_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_HS_UK_1" ON "FECXC"."EUL4_HI_SEGMENTS" ("IHS_HN_ID_CHILD", "IHS_HN_ID_PARENT", "IHS_HI_ID", "DHS_HI_ID", "DHS_DHN_ID_CHILD", "DHS_DHN_ID_PARENT") 
  ;
ALTER TABLE "FECXC"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_HS_PK" PRIMARY KEY ("HS_ID")
  USING INDEX "FECXC"."EUL4_HS_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_HS_CHECK_2" CHECK (    hs_type IN ( 'IHS' , 'DHS' )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_HS_UK_1" UNIQUE ("IHS_HN_ID_CHILD", "IHS_HN_ID_PARENT", "IHS_HI_ID", "DHS_HI_ID", "DHS_DHN_ID_CHILD", "DHS_DHN_ID_PARENT")
  USING INDEX "FECXC"."EUL4_HS_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_HS_CHECK_1" CHECK (    (hs_type != 'DHS' or dhs_dhn_id_child != dhs_dhn_id_parent)    and    (hs_type != 'IHS' or ihs_hn_id_child != ihs_hn_id_parent)    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_DHS_DBH_FK" FOREIGN KEY ("DHS_HI_ID")
	  REFERENCES "FECXC"."EUL4_HIERARCHIES" ("HI_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_DHS_DHN_C_FK" FOREIGN KEY ("DHS_DHN_ID_PARENT")
	  REFERENCES "FECXC"."EUL4_DBH_NODES" ("DHN_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_DHS_DHN_P_FK" FOREIGN KEY ("DHS_DHN_ID_CHILD")
	  REFERENCES "FECXC"."EUL4_DBH_NODES" ("DHN_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_IHS_IBH_FK" FOREIGN KEY ("IHS_HI_ID")
	  REFERENCES "FECXC"."EUL4_HIERARCHIES" ("HI_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_IHS_HN_C_FK" FOREIGN KEY ("IHS_HN_ID_PARENT")
	  REFERENCES "FECXC"."EUL4_HI_NODES" ("HN_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_HI_SEGMENTS" ADD CONSTRAINT "EUL4_IHS_HN_P_FK" FOREIGN KEY ("IHS_HN_ID_CHILD")
	  REFERENCES "FECXC"."EUL4_HI_NODES" ("HN_ID") ENABLE;
