CREATE TABLE "FECXC"."EUL4_OBJS" 
   (	"OBJ_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"OBJ_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"OBJ_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"OBJ_DEVELOPER_KEY" VARCHAR2(100) NOT NULL ENABLE, 
	"OBJ_DESCRIPTION" VARCHAR2(240), 
	"OBJ_BA_ID" NUMBER(10,0), 
	"OBJ_HIDDEN" NUMBER(1,0) NOT NULL ENABLE, 
	"OBJ_DISTINCT_FLAG" NUMBER(1,0) NOT NULL ENABLE, 
	"OBJ_NDETERMINISTIC" NUMBER(1,0) NOT NULL ENABLE, 
	"OBJ_CBO_HINT" VARCHAR2(100), 
	"OBJ_EXT_OBJECT" VARCHAR2(64), 
	"OBJ_EXT_OWNER" VARCHAR2(64), 
	"OBJ_EXT_DB_LINK" VARCHAR2(64), 
	"OBJ_OBJECT_SQL1" VARCHAR2(250), 
	"OBJ_OBJECT_SQL2" VARCHAR2(250), 
	"OBJ_OBJECT_SQL3" VARCHAR2(250), 
	"SOBJ_EXT_TABLE" VARCHAR2(64), 
	"OBJ_USER_PROP2" VARCHAR2(100), 
	"OBJ_USER_PROP1" VARCHAR2(100), 
	"OBJ_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"OBJ_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"OBJ_CREATED_DATE" DATE NOT NULL ENABLE, 
	"OBJ_UPDATED_BY" VARCHAR2(64), 
	"OBJ_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_OBJ_UK_2" ON "FECXC"."EUL4_OBJS" ("OBJ_NAME") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_OBJ_PK" ON "FECXC"."EUL4_OBJS" ("OBJ_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_OBJ_UK_1" ON "FECXC"."EUL4_OBJS" ("OBJ_DEVELOPER_KEY") 
  ;
ALTER TABLE "FECXC"."EUL4_OBJS" ADD CONSTRAINT "EUL4_OBJ_CHECK_1" CHECK (    obj_type IN ( 'COBJ' , 'SOBJ', 'CUO' )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJS" ADD CONSTRAINT "EUL4_OBJ_UK_2" UNIQUE ("OBJ_NAME")
  USING INDEX "FECXC"."EUL4_OBJ_UK_2"  ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJS" ADD CONSTRAINT "EUL4_OBJ_CHECK_2" CHECK (    obj_hidden IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJS" ADD CONSTRAINT "EUL4_OBJ_PK" PRIMARY KEY ("OBJ_ID")
  USING INDEX "FECXC"."EUL4_OBJ_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJS" ADD CONSTRAINT "EUL4_OBJ_CHECK_3" CHECK (    obj_distinct_flag IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJS" ADD CONSTRAINT "EUL4_OBJ_UK_1" UNIQUE ("OBJ_DEVELOPER_KEY")
  USING INDEX "FECXC"."EUL4_OBJ_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJS" ADD CONSTRAINT "EUL4_OBJ_CHECK_4" CHECK (    obj_ndeterministic in (0,1)    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJS" ADD CONSTRAINT "EUL4_OBJ_BA_FK" FOREIGN KEY ("OBJ_BA_ID")
	  REFERENCES "FECXC"."EUL4_BAS" ("BA_ID") ENABLE;
