CREATE TABLE "FECXC"."EUL4_SUM_BITMAPS" 
   (	"SB_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SB_BITMAP" RAW(250) NOT NULL ENABLE, 
	"SB_SEQUENCE" NUMBER(22,0) NOT NULL ENABLE, 
	"SB_EXP_ID" NUMBER(10,0), 
	"SB_KEY_ID" NUMBER(10,0), 
	"SB_FUN_ID" NUMBER(10,0), 
	"SB_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"SB_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"SB_CREATED_DATE" DATE NOT NULL ENABLE, 
	"SB_UPDATED_DATE" DATE, 
	"SB_UPDATED_BY" VARCHAR2(64), 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_SB_UK_1" ON "FECXC"."EUL4_SUM_BITMAPS" ("SB_EXP_ID", "SB_KEY_ID", "SB_FUN_ID", "SB_SEQUENCE") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_SB_PK" ON "FECXC"."EUL4_SUM_BITMAPS" ("SB_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_SUM_BITMAPS" ADD CONSTRAINT "EUL4_SB_CHECK_1" CHECK (    (sb_key_id is not null and sb_fun_id is null and sb_exp_id is null) or    (sb_key_id is null and sb_fun_id is not null and sb_exp_id is null) or    (sb_key_id is null and sb_fun_id is not null and sb_exp_id is not    null) or    (sb_key_id is null and sb_fun_id is null and sb_exp_id is not null)    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_SUM_BITMAPS" ADD CONSTRAINT "EUL4_SB_UK_1" UNIQUE ("SB_EXP_ID", "SB_KEY_ID", "SB_FUN_ID", "SB_SEQUENCE")
  USING INDEX "FECXC"."EUL4_SB_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_SUM_BITMAPS" ADD CONSTRAINT "EUL4_SB_PK" PRIMARY KEY ("SB_ID")
  USING INDEX "FECXC"."EUL4_SB_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_SUM_BITMAPS" ADD CONSTRAINT "EUL4_SB_FK_FK" FOREIGN KEY ("SB_KEY_ID")
	  REFERENCES "FECXC"."EUL4_KEY_CONS" ("KEY_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_SUM_BITMAPS" ADD CONSTRAINT "EUL4_SB_IT_FK" FOREIGN KEY ("SB_EXP_ID")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_SUM_BITMAPS" ADD CONSTRAINT "EUL4_SB_FUN_FK" FOREIGN KEY ("SB_FUN_ID")
	  REFERENCES "FECXC"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
