CREATE TABLE "FECXC"."EUL4_SUM_RFSH_SETS" 
   (	"SRS_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SRS_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"SRS_DEVELOPER_KEY" VARCHAR2(100) NOT NULL ENABLE, 
	"SRS_DESCRIPTION" VARCHAR2(240), 
	"SRS_STATE" NUMBER(2,0) NOT NULL ENABLE, 
	"SRS_ONLINE" NUMBER(1,0) NOT NULL ENABLE, 
	"SRS_AUTO_REFRESH" NUMBER(1,0) NOT NULL ENABLE, 
	"SRS_LAST_REFRESH" DATE, 
	"SRS_NEXT_REFRESH" DATE, 
	"SRS_JOB_ID" NUMBER(22,0), 
	"SRS_EU_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SRS_NUM_FREQ_UNITS" NUMBER(22,0), 
	"SRS_RFU_ID" NUMBER(10,0), 
	"SRS_REFRESH_COUNT" NUMBER(22,0), 
	"SRS_USER_PROP2" VARCHAR2(100), 
	"SRS_USER_PROP1" VARCHAR2(100), 
	"SRS_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"SRS_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"SRS_CREATED_DATE" DATE NOT NULL ENABLE, 
	"SRS_UPDATED_BY" VARCHAR2(64), 
	"SRS_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_SRS_UK_1" ON "FECXC"."EUL4_SUM_RFSH_SETS" ("SRS_DEVELOPER_KEY") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_SRS_PK" ON "FECXC"."EUL4_SUM_RFSH_SETS" ("SRS_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_SRS_UK_2" ON "FECXC"."EUL4_SUM_RFSH_SETS" ("SRS_NAME") 
  ;
ALTER TABLE "FECXC"."EUL4_SUM_RFSH_SETS" ADD CONSTRAINT "EUL4_SRS_UK_1" UNIQUE ("SRS_DEVELOPER_KEY")
  USING INDEX "FECXC"."EUL4_SRS_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_SUM_RFSH_SETS" ADD CONSTRAINT "EUL4_SRS_CHECK_1" CHECK (    srs_state IN (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18)    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_SUM_RFSH_SETS" ADD CONSTRAINT "EUL4_SRS_PK" PRIMARY KEY ("SRS_ID")
  USING INDEX "FECXC"."EUL4_SRS_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_SUM_RFSH_SETS" ADD CONSTRAINT "EUL4_SRS_CHECK_3" CHECK (    srs_auto_refresh IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_SUM_RFSH_SETS" ADD CONSTRAINT "EUL4_SRS_CHECK_2" CHECK (    srs_online IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_SUM_RFSH_SETS" ADD CONSTRAINT "EUL4_SRS_UK_2" UNIQUE ("SRS_NAME")
  USING INDEX "FECXC"."EUL4_SRS_UK_2"  ENABLE;
ALTER TABLE "FECXC"."EUL4_SUM_RFSH_SETS" ADD CONSTRAINT "EUL4_SRS_EU_FK" FOREIGN KEY ("SRS_EU_ID")
	  REFERENCES "FECXC"."EUL4_EUL_USERS" ("EU_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_SUM_RFSH_SETS" ADD CONSTRAINT "EUL4_SRS_RFU_FK" FOREIGN KEY ("SRS_RFU_ID")
	  REFERENCES "FECXC"."EUL4_FREQ_UNITS" ("RFU_ID") ENABLE;
