CREATE TABLE "FECXC"."EUL4_EXP_DEPS" 
   (	"ED_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ED_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"PD_P_ID" NUMBER(10,0), 
	"PED_EXP_ID" NUMBER(10,0), 
	"PFD_FUN_ID" NUMBER(10,0), 
	"PSD_SQ_ID" NUMBER(10,0), 
	"CD_EXP_ID" NUMBER(10,0), 
	"CFD_FUN_ID" NUMBER(10,0), 
	"CID_EXP_ID" NUMBER(10,0), 
	"ED_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"ED_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"ED_CREATED_DATE" DATE NOT NULL ENABLE, 
	"ED_UPDATED_BY" VARCHAR2(64), 
	"ED_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_ED_PK" ON "FECXC"."EUL4_EXP_DEPS" ("ED_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_ED_UK_1" ON "FECXC"."EUL4_EXP_DEPS" ("PSD_SQ_ID", "PFD_FUN_ID", "CD_EXP_ID", "PED_EXP_ID", "PD_P_ID", "CFD_FUN_ID", "CID_EXP_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_ED_CHECK_1" CHECK (    ed_type IN ( 'PSD' , 'PFD' , 'CFD' , 'CID' , 'PED' )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_ED_PK" PRIMARY KEY ("ED_ID")
  USING INDEX "FECXC"."EUL4_ED_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_ED_UK_1" UNIQUE ("PSD_SQ_ID", "PFD_FUN_ID", "CD_EXP_ID", "PED_EXP_ID", "PD_P_ID", "CFD_FUN_ID", "CID_EXP_ID")
  USING INDEX "FECXC"."EUL4_ED_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_CD_CI_FK" FOREIGN KEY ("CD_EXP_ID")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_CFD_FUN_FK" FOREIGN KEY ("CFD_FUN_ID")
	  REFERENCES "FECXC"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_CID_IT_FK" FOREIGN KEY ("CID_EXP_ID")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_PD_P_FK" FOREIGN KEY ("PD_P_ID")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_PED_EXP_FK" FOREIGN KEY ("PED_EXP_ID")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_PFD_FUN_FK" FOREIGN KEY ("PFD_FUN_ID")
	  REFERENCES "FECXC"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_EXP_DEPS" ADD CONSTRAINT "EUL4_PSD_SQ_FK" FOREIGN KEY ("PSD_SQ_ID")
	  REFERENCES "FECXC"."EUL4_SUB_QUERIES" ("SQ_ID") ENABLE;
