CREATE TABLE "FECXC"."EUL4_DOMAINS" 
   (	"DOM_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"DOM_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"DOM_DEVELOPER_KEY" VARCHAR2(100) NOT NULL ENABLE, 
	"DOM_DESCRIPTION" VARCHAR2(240), 
	"DOM_DATA_TYPE" NUMBER(2,0) NOT NULL ENABLE, 
	"DOM_LOGICAL_ITEM" NUMBER(1,0) NOT NULL ENABLE, 
	"DOM_SYS_GENERATED" NUMBER(1,0) NOT NULL ENABLE, 
	"DOM_CARDINALITY" NUMBER(22,0), 
	"DOM_LAST_EXEC_TIME" NUMBER(22,0), 
	"DOM_CACHED" NUMBER(1,0) NOT NULL ENABLE, 
	"DOM_IT_ID_LOV" NUMBER(10,0), 
	"DOM_IT_ID_RANK" NUMBER(10,0), 
	"DOM_USER_PROP2" VARCHAR2(100), 
	"DOM_USER_PROP1" VARCHAR2(100), 
	"DOM_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"DOM_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"DOM_CREATED_DATE" DATE NOT NULL ENABLE, 
	"DOM_UPDATED_BY" VARCHAR2(64), 
	"DOM_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_DOM_UK_1" ON "FECXC"."EUL4_DOMAINS" ("DOM_DEVELOPER_KEY") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_DOM_PK" ON "FECXC"."EUL4_DOMAINS" ("DOM_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_DOM_UK_2" ON "FECXC"."EUL4_DOMAINS" ("DOM_NAME") 
  ;
ALTER TABLE "FECXC"."EUL4_DOMAINS" ADD CONSTRAINT "EUL4_DOM_CHECK_5" CHECK (    dom_cached IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_DOMAINS" ADD CONSTRAINT "EUL4_DOM_UK_1" UNIQUE ("DOM_DEVELOPER_KEY")
  USING INDEX "FECXC"."EUL4_DOM_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_DOMAINS" ADD CONSTRAINT "EUL4_DOM_PK" PRIMARY KEY ("DOM_ID")
  USING INDEX "FECXC"."EUL4_DOM_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_DOMAINS" ADD CONSTRAINT "EUL4_DOM_UK_2" UNIQUE ("DOM_NAME")
  USING INDEX "FECXC"."EUL4_DOM_UK_2"  ENABLE;
ALTER TABLE "FECXC"."EUL4_DOMAINS" ADD CONSTRAINT "EUL4_DOM_CHECK_3" CHECK (    dom_logical_item IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_DOMAINS" ADD CONSTRAINT "EUL4_DOM_CHECK_2" CHECK (    dom_data_type IN (0,1,2,3,4,5,6,7,8,9,10,11,12,13)    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_DOMAINS" ADD CONSTRAINT "EUL4_DOM_CHECK_4" CHECK (    dom_sys_generated IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_DOMAINS" ADD CONSTRAINT "EUL4_DOM_IT_L_FK" FOREIGN KEY ("DOM_IT_ID_LOV")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_DOMAINS" ADD CONSTRAINT "EUL4_DOM_IT_R_FK" FOREIGN KEY ("DOM_IT_ID_RANK")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
