CREATE TABLE "FECXC"."EUL4_BQ_DEPS" 
   (	"BQD_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BQD_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"BQD_BQ_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BFILD_FIL_ID" NUMBER(10,0), 
	"BID_IT_ID" NUMBER(10,0), 
	"BFUND_FUN_ID" NUMBER(10,0), 
	"BQD_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"BQD_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"BQD_CREATED_DATE" DATE NOT NULL ENABLE, 
	"BQD_UPDATED_BY" VARCHAR2(64), 
	"BQD_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_BQD_PK" ON "FECXC"."EUL4_BQ_DEPS" ("BQD_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_BQD_UK_1" ON "FECXC"."EUL4_BQ_DEPS" ("BQD_TYPE", "BQD_BQ_ID", "BFILD_FIL_ID", "BID_IT_ID", "BFUND_FUN_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_BQ_DEPS" ADD CONSTRAINT "EUL4_BQD_PK" PRIMARY KEY ("BQD_ID")
  USING INDEX "FECXC"."EUL4_BQD_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_BQ_DEPS" ADD CONSTRAINT "EUL4_BQD_UK_1" UNIQUE ("BQD_TYPE", "BQD_BQ_ID", "BFILD_FIL_ID", "BID_IT_ID", "BFUND_FUN_ID")
  USING INDEX "FECXC"."EUL4_BQD_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_BQ_DEPS" ADD CONSTRAINT "EUL4_BQD_CHECK_1" CHECK (    bqd_type IN ('BFUND', 'BFILD', 'BID')    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_BQ_DEPS" ADD CONSTRAINT "EUL4_BFILD_FIL_FK" FOREIGN KEY ("BFILD_FIL_ID")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_BQ_DEPS" ADD CONSTRAINT "EUL4_BFUND_FUN_FK" FOREIGN KEY ("BFUND_FUN_ID")
	  REFERENCES "FECXC"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_BQ_DEPS" ADD CONSTRAINT "EUL4_BID_IT_FK" FOREIGN KEY ("BID_IT_ID")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_BQ_DEPS" ADD CONSTRAINT "EUL4_BQD_BQ_FK" FOREIGN KEY ("BQD_BQ_ID")
	  REFERENCES "FECXC"."EUL4_BATCH_QUERIES" ("BQ_ID") ENABLE;
