CREATE TABLE "FECXC"."EUL4_BATCH_QUERIES" 
   (	"BQ_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BQ_BS_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BQ_QUERY_ID" VARCHAR2(240) NOT NULL ENABLE, 
	"BQ_RESULT_SQL_1" VARCHAR2(250), 
	"BQ_RESULT_SQL_2" VARCHAR2(250), 
	"BQ_RESULT_SQL_3" VARCHAR2(250), 
	"BQ_RESULT_SQL_4" VARCHAR2(250), 
	"BQ_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"BQ_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"BQ_CREATED_DATE" DATE NOT NULL ENABLE, 
	"BQ_UPDATED_BY" VARCHAR2(64), 
	"BQ_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_BQ_PK" ON "FECXC"."EUL4_BATCH_QUERIES" ("BQ_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_BQ_UK_1" ON "FECXC"."EUL4_BATCH_QUERIES" ("BQ_BS_ID", "BQ_QUERY_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_BATCH_QUERIES" ADD CONSTRAINT "EUL4_BQ_PK" PRIMARY KEY ("BQ_ID")
  USING INDEX "FECXC"."EUL4_BQ_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_BATCH_QUERIES" ADD CONSTRAINT "EUL4_BQ_UK_1" UNIQUE ("BQ_BS_ID", "BQ_QUERY_ID")
  USING INDEX "FECXC"."EUL4_BQ_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_BATCH_QUERIES" ADD CONSTRAINT "EUL4_BQ_BS_FK" FOREIGN KEY ("BQ_BS_ID")
	  REFERENCES "FECXC"."EUL4_BATCH_SHEETS" ("BS_ID") ENABLE;
