CREATE TABLE "FECXC"."EUL4_HIERARCHIES" 
   (	"HI_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"HI_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"HI_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"HI_DEVELOPER_KEY" VARCHAR2(100) NOT NULL ENABLE, 
	"HI_DESCRIPTION" VARCHAR2(240), 
	"HI_SYS_GENERATED" NUMBER(1,0) NOT NULL ENABLE, 
	"HI_EXT_HIERARCHY" VARCHAR2(64), 
	"DBH_DEFAULT" NUMBER(1,0), 
	"IBH_DBH_ID" NUMBER(10,0), 
	"HI_USER_PROP2" VARCHAR2(100), 
	"HI_USER_PROP1" VARCHAR2(100), 
	"HI_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"HI_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"HI_CREATED_DATE" DATE NOT NULL ENABLE, 
	"HI_UPDATED_BY" VARCHAR2(64), 
	"HI_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_HI_PK" ON "FECXC"."EUL4_HIERARCHIES" ("HI_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_HI_UK_1" ON "FECXC"."EUL4_HIERARCHIES" ("HI_DEVELOPER_KEY") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_HI_UK_2" ON "FECXC"."EUL4_HIERARCHIES" ("HI_NAME") 
  ;
ALTER TABLE "FECXC"."EUL4_HIERARCHIES" ADD CONSTRAINT "EUL4_HI_CHECK_1" CHECK (    hi_type IN ( 'DBH' , 'IBH' )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_HIERARCHIES" ADD CONSTRAINT "EUL4_HI_UK_1" UNIQUE ("HI_DEVELOPER_KEY")
  USING INDEX "FECXC"."EUL4_HI_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_HIERARCHIES" ADD CONSTRAINT "EUL4_HI_CHECK_2" CHECK (    hi_sys_generated IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_HIERARCHIES" ADD CONSTRAINT "EUL4_HI_UK_2" UNIQUE ("HI_NAME")
  USING INDEX "FECXC"."EUL4_HI_UK_2"  ENABLE;
ALTER TABLE "FECXC"."EUL4_HIERARCHIES" ADD CONSTRAINT "EUL4_HI_PK" PRIMARY KEY ("HI_ID")
  USING INDEX "FECXC"."EUL4_HI_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_HIERARCHIES" ADD CONSTRAINT "EUL4_HI_CHECK_3" CHECK (    dbh_default IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_HIERARCHIES" ADD CONSTRAINT "EUL4_IBH_DBH_FK" FOREIGN KEY ("IBH_DBH_ID")
	  REFERENCES "FECXC"."EUL4_HIERARCHIES" ("HI_ID") ENABLE;
