CREATE TABLE "FECXC"."EUL4_OBJ_JOIN_USGS" 
   (	"OJU_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"OJU_OBJ_ID" NUMBER(10,0), 
	"OJU_JOIN_MODIFIED" NUMBER(1,0) NOT NULL ENABLE, 
	"OJU_KEY_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"OJU_SUMO_ID" NUMBER(10,0), 
	"OJU_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"OJU_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"OJU_CREATED_DATE" DATE NOT NULL ENABLE, 
	"OJU_UPDATED_BY" VARCHAR2(64), 
	"OJU_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_OJU_UK_1" ON "FECXC"."EUL4_OBJ_JOIN_USGS" ("OJU_OBJ_ID", "OJU_KEY_ID", "OJU_SUMO_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_OJU_PK" ON "FECXC"."EUL4_OBJ_JOIN_USGS" ("OJU_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_OBJ_JOIN_USGS" ADD CONSTRAINT "EUL4_OJU_UK_1" UNIQUE ("OJU_OBJ_ID", "OJU_KEY_ID", "OJU_SUMO_ID")
  USING INDEX "FECXC"."EUL4_OJU_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJ_JOIN_USGS" ADD CONSTRAINT "EUL4_OJU_CHECK_2" CHECK (    oju_join_modified IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJ_JOIN_USGS" ADD CONSTRAINT "EUL4_OJU_CHECK_1" CHECK (    (oju_obj_id is null and oju_sumo_id is not null)    or    (oju_obj_id is not null and oju_sumo_id is null)    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJ_JOIN_USGS" ADD CONSTRAINT "EUL4_OJU_PK" PRIMARY KEY ("OJU_ID")
  USING INDEX "FECXC"."EUL4_OJU_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJ_JOIN_USGS" ADD CONSTRAINT "EUL4_OJU_COBJ_FK" FOREIGN KEY ("OJU_OBJ_ID")
	  REFERENCES "FECXC"."EUL4_OBJS" ("OBJ_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJ_JOIN_USGS" ADD CONSTRAINT "EUL4_OJU_FK_FK" FOREIGN KEY ("OJU_KEY_ID")
	  REFERENCES "FECXC"."EUL4_KEY_CONS" ("KEY_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_OBJ_JOIN_USGS" ADD CONSTRAINT "EUL4_OJU_SUMO_FK" FOREIGN KEY ("OJU_SUMO_ID")
	  REFERENCES "FECXC"."EUL4_SUMMARY_OBJS" ("SUMO_ID") ENABLE;
