CREATE TABLE "FECXC"."EUL4_EXPRESSIONS" 
   (	"EXP_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"EXP_TYPE" VARCHAR2(10) NOT NULL ENABLE, 
	"EXP_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"EXP_DEVELOPER_KEY" VARCHAR2(100) NOT NULL ENABLE, 
	"EXP_DESCRIPTION" VARCHAR2(240), 
	"EXP_FORMULA1" VARCHAR2(250), 
	"EXP_DATA_TYPE" NUMBER(2,0) NOT NULL ENABLE, 
	"EXP_SEQUENCE" NUMBER(22,0), 
	"IT_DOM_ID" NUMBER(10,0), 
	"IT_OBJ_ID" NUMBER(10,0), 
	"IT_DOC_ID" NUMBER(10,0), 
	"IT_FORMAT_MASK" VARCHAR2(100), 
	"IT_MAX_DATA_WIDTH" NUMBER, 
	"IT_MAX_DISP_WIDTH" NUMBER, 
	"IT_ALIGNMENT" NUMBER(2,0), 
	"IT_WORD_WRAP" NUMBER(1,0), 
	"IT_DISP_NULL_VAL" VARCHAR2(100), 
	"IT_FUN_ID" NUMBER(10,0), 
	"IT_HEADING" VARCHAR2(240), 
	"IT_HIDDEN" NUMBER(1,0), 
	"IT_PLACEMENT" NUMBER(2,0), 
	"IT_USER_DEF_FMT" VARCHAR2(100), 
	"IT_CASE_STORAGE" NUMBER(2,0), 
	"IT_CASE_DISPLAY" NUMBER(2,0), 
	"IT_EXT_COLUMN" VARCHAR2(64), 
	"CI_IT_ID" NUMBER(10,0), 
	"CI_RUNTIME_ITEM" NUMBER(1,0), 
	"PAR_MULTIPLE_VALS" NUMBER(1,0), 
	"CO_NULLABLE" NUMBER(1,0), 
	"P_CASE_SENSITIVE" NUMBER(1,0), 
	"JP_KEY_ID" NUMBER(10,0), 
	"FIL_OBJ_ID" NUMBER(10,0), 
	"FIL_DOC_ID" NUMBER(10,0), 
	"FIL_RUNTIME_FILTER" NUMBER(1,0), 
	"FIL_APP_TYPE" NUMBER(2,0), 
	"FIL_EXT_FILTER" VARCHAR2(64), 
	"EXP_USER_PROP2" VARCHAR2(100), 
	"EXP_USER_PROP1" VARCHAR2(100), 
	"EXP_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"EXP_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"EXP_CREATED_DATE" DATE NOT NULL ENABLE, 
	"EXP_UPDATED_BY" VARCHAR2(64), 
	"EXP_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_EXP_UK_2" ON "FECXC"."EUL4_EXPRESSIONS" ("IT_OBJ_ID", "FIL_OBJ_ID", "JP_KEY_ID", "EXP_NAME", "IT_DOC_ID", "FIL_DOC_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_EXP_UK_1" ON "FECXC"."EUL4_EXPRESSIONS" ("IT_OBJ_ID", "FIL_OBJ_ID", "JP_KEY_ID", "EXP_DEVELOPER_KEY", "IT_DOC_ID", "FIL_DOC_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_EXP_PK" ON "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") 
  ;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_CHECK_6" CHECK (    it_hidden IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_CHECK_1" CHECK (    exp_type IN ( 'CI' , 'CO' , 'JP' , 'FIL' , 'PAR' )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_CHECK_10" CHECK (    it_case_display IN ( 1 , 2 , 3 , 4 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_UK_2" UNIQUE ("IT_OBJ_ID", "FIL_OBJ_ID", "JP_KEY_ID", "EXP_NAME", "IT_DOC_ID", "FIL_DOC_ID")
  USING INDEX "FECXC"."EUL4_EXP_UK_2"  ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_CHECK_9" CHECK (    it_case_storage IN ( 0 , 1 , 2 , 3 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_CHECK_4" CHECK (    it_word_wrap IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_CHECK_12" CHECK (    p_case_sensitive IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_CHECK_14" CHECK (    ci_runtime_item in (1,0)    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_CHECK_15" CHECK (    fil_app_type in (0,1,2)    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_CHECK_5" CHECK (    par_multiple_vals IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_CHECK_11" CHECK (    co_nullable IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_CHECK_8" CHECK (    it_placement IN ( 0 , 1 , 2 , 3 , 4 , 5 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_UK_1" UNIQUE ("IT_OBJ_ID", "FIL_OBJ_ID", "JP_KEY_ID", "EXP_DEVELOPER_KEY", "IT_DOC_ID", "FIL_DOC_ID")
  USING INDEX "FECXC"."EUL4_EXP_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_CHECK_2" CHECK (    exp_data_type IN (0,1,2,3,4,5,6,7,8,9,10,11,12,13)    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_CHECK_13" CHECK (    fil_runtime_filter IN ( 1 , 0 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_CHECK_3" CHECK (    it_alignment IN ( 1 , 2 , 3 , 4 )    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_EXP_PK" PRIMARY KEY ("EXP_ID")
  USING INDEX "FECXC"."EUL4_EXP_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_CI_IT_FK" FOREIGN KEY ("CI_IT_ID")
	  REFERENCES "FECXC"."EUL4_EXPRESSIONS" ("EXP_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_FIL_OBJ_FK" FOREIGN KEY ("FIL_OBJ_ID")
	  REFERENCES "FECXC"."EUL4_OBJS" ("OBJ_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_IT_DOM_FK" FOREIGN KEY ("IT_DOM_ID")
	  REFERENCES "FECXC"."EUL4_DOMAINS" ("DOM_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_IT_OBJ_FK" FOREIGN KEY ("IT_OBJ_ID")
	  REFERENCES "FECXC"."EUL4_OBJS" ("OBJ_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_FIL_DOC_FK" FOREIGN KEY ("FIL_DOC_ID")
	  REFERENCES "FECXC"."EUL4_DOCUMENTS" ("DOC_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_IT_DOC_FK" FOREIGN KEY ("IT_DOC_ID")
	  REFERENCES "FECXC"."EUL4_DOCUMENTS" ("DOC_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_IT_FUN_FK" FOREIGN KEY ("IT_FUN_ID")
	  REFERENCES "FECXC"."EUL4_FUNCTIONS" ("FUN_ID") ENABLE;
ALTER TABLE "FECXC"."EUL4_EXPRESSIONS" ADD CONSTRAINT "EUL4_JP_FK_FK" FOREIGN KEY ("JP_KEY_ID")
	  REFERENCES "FECXC"."EUL4_KEY_CONS" ("KEY_ID") ENABLE;
