CREATE TABLE "FECXC"."EUL4_BR_RUNS" 
   (	"BRR_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BRR_BR_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"BRR_RUN_NUMBER" NUMBER(22,0) NOT NULL ENABLE, 
	"BRR_STATE" NUMBER(2,0) NOT NULL ENABLE, 
	"BRR_RUN_DATE" DATE, 
	"BRR_SVR_ERR_CODE" NUMBER, 
	"BRR_SVR_ERR_TEXT" VARCHAR2(240), 
	"BRR_ACT_ELAP_TIME" NUMBER, 
	"BRR_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"BRR_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"BRR_CREATED_DATE" DATE NOT NULL ENABLE, 
	"BRR_UPDATED_BY" VARCHAR2(64), 
	"BRR_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_BRR_PK" ON "FECXC"."EUL4_BR_RUNS" ("BRR_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_BRR_UK_1" ON "FECXC"."EUL4_BR_RUNS" ("BRR_BR_ID", "BRR_RUN_NUMBER") 
  ;
ALTER TABLE "FECXC"."EUL4_BR_RUNS" ADD CONSTRAINT "EUL4_BRR_CHECK_1" CHECK (    brr_state in (0, 1, 2, 3, 4, 5, 6, 7, 8, 9)    ) ENABLE;
ALTER TABLE "FECXC"."EUL4_BR_RUNS" ADD CONSTRAINT "EUL4_BRR_PK" PRIMARY KEY ("BRR_ID")
  USING INDEX "FECXC"."EUL4_BRR_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_BR_RUNS" ADD CONSTRAINT "EUL4_BRR_UK_1" UNIQUE ("BRR_BR_ID", "BRR_RUN_NUMBER")
  USING INDEX "FECXC"."EUL4_BRR_UK_1"  ENABLE;
ALTER TABLE "FECXC"."EUL4_BR_RUNS" ADD CONSTRAINT "EUL4_BRR_BR_FK" FOREIGN KEY ("BRR_BR_ID")
	  REFERENCES "FECXC"."EUL4_BATCH_REPORTS" ("BR_ID") ENABLE;
