CREATE TABLE "FECXC"."EUL4_ASM_POLICIES" 
   (	"ASMP_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ASMP_NAME" VARCHAR2(100) NOT NULL ENABLE, 
	"ASMP_DEVELOPER_KEY" VARCHAR2(100) NOT NULL ENABLE, 
	"ASMP_DESCRIPTION" VARCHAR2(240), 
	"ASMP_USER_PROP1" VARCHAR2(100), 
	"ASMP_USER_PROP2" VARCHAR2(100), 
	"ASMP_ELEMENT_STATE" NUMBER(10,0) NOT NULL ENABLE, 
	"ASMP_CREATED_BY" VARCHAR2(64) NOT NULL ENABLE, 
	"ASMP_CREATED_DATE" DATE NOT NULL ENABLE, 
	"ASMP_UPDATED_BY" VARCHAR2(64), 
	"ASMP_UPDATED_DATE" DATE, 
	"NOTM" NUMBER(10,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_ASMP_PK" ON "FECXC"."EUL4_ASM_POLICIES" ("ASMP_ID") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_ASMP_UK_2" ON "FECXC"."EUL4_ASM_POLICIES" ("ASMP_NAME") 
  ;
  CREATE UNIQUE INDEX "FECXC"."EUL4_ASMP_UK_1" ON "FECXC"."EUL4_ASM_POLICIES" ("ASMP_DEVELOPER_KEY") 
  ;
ALTER TABLE "FECXC"."EUL4_ASM_POLICIES" ADD CONSTRAINT "EUL4_ASMP_PK" PRIMARY KEY ("ASMP_ID")
  USING INDEX "FECXC"."EUL4_ASMP_PK"  ENABLE;
ALTER TABLE "FECXC"."EUL4_ASM_POLICIES" ADD CONSTRAINT "EUL4_ASMP_UK_2" UNIQUE ("ASMP_NAME")
  USING INDEX "FECXC"."EUL4_ASMP_UK_2"  ENABLE;
ALTER TABLE "FECXC"."EUL4_ASM_POLICIES" ADD CONSTRAINT "EUL4_ASMP_UK_1" UNIQUE ("ASMP_DEVELOPER_KEY")
  USING INDEX "FECXC"."EUL4_ASMP_UK_1"  ENABLE;
