CREATE TABLE "FECXC"."FECI_EMP_USU_TAB" 
   (	"ID_USUARIO" NUMBER, 
	"ID_EMPRESA" NUMBER, 
	"FEC_CREACION" DATE NOT NULL ENABLE, 
	"FEC_ULT_MODIFICACION" DATE NOT NULL ENABLE, 
	"ID_USUARIO_CREACION" NUMBER NOT NULL ENABLE, 
	"ID_USUARIO_ULT_MODIF" NUMBER NOT NULL ENABLE, 
	"IND_ESTADO" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "FECXC"."FECI_EMP_USU_TAB" ADD CONSTRAINT "FK_FECI_EMP_FECI_EMPU_FECI_EMP" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "FECXC"."FECI_EMPRESA_CAT" ("ID_EMPRESA") ENABLE;
ALTER TABLE "FECXC"."FECI_EMP_USU_TAB" ADD CONSTRAINT "FK_FECI_EMP_FECI_EMPU_FECI_USU" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "FECXC"."FECI_USUARIO_TAB" ("ID_USUARIO") ENABLE;
