CREATE TABLE "FECXC"."FECI_USUARIO_TAB" 
   (	"ID_USUARIO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 53 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"ID_ROL" NUMBER, 
	"DES_EMAIL" VARCHAR2(250) NOT NULL ENABLE, 
	"DES_NOMBRES" VARCHAR2(150) NOT NULL ENABLE, 
	"DES_APELLIDOS" VARCHAR2(250) NOT NULL ENABLE, 
	"FEC_CREACION" DATE NOT NULL ENABLE, 
	"FEC_ULT_MODIFICACION" DATE NOT NULL ENABLE, 
	"ID_USUARIO_CREACION" NUMBER NOT NULL ENABLE, 
	"ID_USUARIO_ULT_MODIF" NUMBER NOT NULL ENABLE, 
	"IND_ESTADO" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "FECXC"."FECI_USUARIO_TAB" ADD CONSTRAINT "USUARIO_PK" PRIMARY KEY ("ID_USUARIO") DEFERRABLE
  USING INDEX  ENABLE;
ALTER TABLE "FECXC"."FECI_USUARIO_TAB" ADD CONSTRAINT "FK_FECI_USU_FECI_USU__FECI_ROL" FOREIGN KEY ("ID_ROL")
	  REFERENCES "FECXC"."FECI_ROL_TAB" ("ID_ROL") ENABLE;
