CREATE TABLE "FECXC"."FECI_SEGM_CONC_CAT" 
   (	"ID_SEGMENTO" NUMBER, 
	"ID_GRUPO_FORECAST" NUMBER, 
	"ID_CONCEPTO" NUMBER, 
	"FEC_CREACION" DATE NOT NULL ENABLE, 
	"FEC_ULT_MODIFICACION" DATE NOT NULL ENABLE, 
	"ID_USUARIO_CREACION" NUMBER NOT NULL ENABLE, 
	"ID_USUARIO_ULT_MODIF" NUMBER NOT NULL ENABLE, 
	"IND_ESTADO" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "FECXC"."FECI_SEGM_CONC_CAT" ADD CONSTRAINT "FK_FECI_SEG_FECI_SGCO_FECI_CON" FOREIGN KEY ("ID_CONCEPTO")
	  REFERENCES "FECXC"."FECI_CONCEPTO_CAT" ("ID_CONCEPTO") ENABLE;
ALTER TABLE "FECXC"."FECI_SEGM_CONC_CAT" ADD CONSTRAINT "FK_FECI_SEG_FECI_SGCO_FECI_GRU" FOREIGN KEY ("ID_GRUPO_FORECAST")
	  REFERENCES "FECXC"."FECI_GRUPO_FORECAST_CAT" ("ID_GRUPO_FORECAST") ENABLE;
ALTER TABLE "FECXC"."FECI_SEGM_CONC_CAT" ADD CONSTRAINT "FK_FECI_SEG_FECI_SGCO_FECI_SEG" FOREIGN KEY ("ID_SEGMENTO")
	  REFERENCES "FECXC"."FECI_SEGMENTO_CAT" ("ID_SEGMENTO") ENABLE;
