CREATE TABLE "FECXC"."FECI_PRESUPUESTO_TAB" 
   (	"ID_PRESUPUESTO" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 68 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"COD_SEGMENTO" VARCHAR2(20) NOT NULL ENABLE, 
	"COD_CONCEPTO" VARCHAR2(20) NOT NULL ENABLE, 
	"COD_REGION" VARCHAR2(20), 
	"COD_MONEDA" VARCHAR2(20) NOT NULL ENABLE, 
	"FEC_PRESUPUESTO" DATE NOT NULL ENABLE, 
	"NUM_GESTION" NUMBER NOT NULL ENABLE, 
	"NUM_IMPORTE" NUMBER NOT NULL ENABLE, 
	"FEC_CREACION" DATE NOT NULL ENABLE, 
	"FEC_ULT_MODIFICACION" DATE NOT NULL ENABLE, 
	"ID_USUARIO_CREACION" NUMBER NOT NULL ENABLE, 
	"ID_USUARIO_ULT_MODIF" NUMBER NOT NULL ENABLE, 
	"IND_ESTADO" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "FECXC"."FECI_PRESUPUESTO_TAB" ADD CONSTRAINT "PRESUPUESTO_PK" PRIMARY KEY ("ID_PRESUPUESTO")
  USING INDEX  ENABLE;
