CREATE TABLE "FECXC"."FECI_MONEDA_CAT" 
   (	"ID_MONEDA" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 43 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"COD_MONEDA" VARCHAR2(20) NOT NULL ENABLE, 
	"DES_MONEDA" VARCHAR2(250) NOT NULL ENABLE, 
	"FEC_CREACION" DATE NOT NULL ENABLE, 
	"FEC_ULT_MODIFICACION" DATE NOT NULL ENABLE, 
	"ID_USUARIO_CREACION" NUMBER NOT NULL ENABLE, 
	"ID_USUARIO_ULT_MODIF" NUMBER NOT NULL ENABLE, 
	"IND_ESTADO" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "FECXC"."FECI_MONEDA_CAT" ADD CONSTRAINT "MONEDA_PK" PRIMARY KEY ("ID_MONEDA")
  USING INDEX  ENABLE;
