CREATE TABLE "FECXC"."FECXP_REAL_CARATULA" 
   (	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"DES_EMPRESA" VARCHAR2(100) NOT NULL ENABLE, 
	"ID_SESION_RC" VARCHAR2(256) NOT NULL ENABLE, 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"MONEDA" VARCHAR2(3), 
	"TIPO_CAMBIO" NUMBER(20,11), 
	"CLA_FE_ID" VARCHAR2(25) NOT NULL ENABLE, 
	"CLA_FE_DES" VARCHAR2(100) NOT NULL ENABLE, 
	"IMPORTE_LINEA" NUMBER(20,4), 
	"ESTATUS" VARCHAR2(25) DEFAULT ('EXTRAIDO'), 
	"TIPO_CARATULA" VARCHAR2(2)
   ) ;
