CREATE TABLE "FECXC"."FECXC_COBRANZA_ANTERIOR" 
   (	"E_CODIGO" NUMBER(*,0), 
	"SEGMENTO" NUMBER(*,0), 
	"CODMONEDA" VARCHAR2(3), 
	"COBRANZA_ANTERIOR" NUMBER(20,4), 
	"COBRANZAREAL_ANTERIOR" NUMBER(20,4)
   ) ;
ALTER TABLE "FECXC"."FECXC_COBRANZA_ANTERIOR" ADD CONSTRAINT "FK_FECXC_CO_TV_COBANT_FECXC_EM" FOREIGN KEY ("E_CODIGO")
	  REFERENCES "FECXC"."FECXC_EMPRESAS" ("E_CODIGO") ENABLE;
