CREATE TABLE "FECXC"."FECXP_SALDOS_OPERATIVO_ERP" 
   (	"SECUENCIA_SALDOS_OPERA_ERP" NUMBER(*,0) NOT NULL ENABLE, 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"PERIODO_EXTRACCION" NUMBER(15,0) DEFAULT to_number(to_char(sysdate,'YYYY')) NOT NULL ENABLE, 
	"MES_DE_EXTRACCION" NUMBER(15,0) NOT NULL ENABLE, 
	"LIBRO_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"MONEDA" VARCHAR2(3) NOT NULL ENABLE, 
	"CODE_COMBINATION_ID" NUMBER NOT NULL ENABLE, 
	"ORACLE_SEGMENTO1" VARCHAR2(25) NOT NULL ENABLE, 
	"ORACLE_SEGMENTO2" VARCHAR2(25) NOT NULL ENABLE, 
	"ORACLE_SEGMENTO3" VARCHAR2(25) NOT NULL ENABLE, 
	"ORACLE_SEGMENTO4" VARCHAR2(25) NOT NULL ENABLE, 
	"ORACLE_SEGMENTO5" VARCHAR2(25) NOT NULL ENABLE, 
	"ORACLE_SEGMENTO6" VARCHAR2(25) NOT NULL ENABLE, 
	"ORACLE_SEGMENTO7" VARCHAR2(25) NOT NULL ENABLE, 
	"SALDO_INICIAL_MO" NUMBER(20,2) NOT NULL ENABLE, 
	"DEBITO_INICIAL_MO" NUMBER(20,2) NOT NULL ENABLE, 
	"CREDITO_INICIAL_MO" NUMBER(20,2) NOT NULL ENABLE, 
	"SALDO_FINAL_MO" NUMBER(20,2) NOT NULL ENABLE, 
	"SALDO_INICIAL_ME" NUMBER(20,2) NOT NULL ENABLE, 
	"DEBITO_INICIAL_ME" NUMBER(20,2) NOT NULL ENABLE, 
	"CREDITO_INICIAL_ME" NUMBER(20,2) NOT NULL ENABLE, 
	"SALDO_FINAL_ME" NUMBER(20,2) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXP_SALDOS_OPERATIVO_ERP" ON "FECXC"."FECXP_SALDOS_OPERATIVO_ERP" ("E_CODIGO", "SECUENCIA_SALDOS_OPERA_ERP") 
  ;
ALTER TABLE "FECXC"."FECXP_SALDOS_OPERATIVO_ERP" ADD CONSTRAINT "PK_FECXP_SALDOS_OPERATIVO_ERP" PRIMARY KEY ("E_CODIGO", "SECUENCIA_SALDOS_OPERA_ERP")
  USING INDEX "FECXC"."PK_FECXP_SALDOS_OPERATIVO_ERP"  ENABLE;
