CREATE TABLE "FECXC"."FECXC_CARGA_PRESUP" 
   (	"MONEDA" VARCHAR2(25), 
	"FECHA" DATE, 
	"SEGMENTO" VARCHAR2(25), 
	"CONCEPTO" VARCHAR2(25), 
	"IMPORTE" NUMBER, 
	"ANIO" NUMBER(*,0), 
	"DIVISION" VARCHAR2(25), 
	"ESTATUS_ORIGEN" VARCHAR2(25) DEFAULT 'EN ESPERA'
   ) ;
