CREATE TABLE "FECXC"."FECXP_PRESUPUESTO_SOIN" 
   (	"SECUENCIA_PRESUPUESTO_SOIN" NUMBER(*,0) NOT NULL ENABLE, 
	"SECMONEDA" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0), 
	"PRSCOD" NUMBER(*,0), 
	"MESCOD" NUMBER(*,0), 
	"MONEDA" VARCHAR2(3), 
	"ARSMAP" VARCHAR2(3), 
	"AEJMAP" VARCHAR2(3), 
	"CNCMAP" VARCHAR2(3), 
	"IMPORTE" NUMBER(20,2)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXP_PRESUPUESTO_SOIN" ON "FECXC"."FECXP_PRESUPUESTO_SOIN" ("SECUENCIA_PRESUPUESTO_SOIN") 
  ;
ALTER TABLE "FECXC"."FECXP_PRESUPUESTO_SOIN" ADD CONSTRAINT "PK_FECXP_PRESUPUESTO_SOIN" PRIMARY KEY ("SECUENCIA_PRESUPUESTO_SOIN")
  USING INDEX "FECXC"."PK_FECXP_PRESUPUESTO_SOIN"  ENABLE;
ALTER TABLE "FECXC"."FECXP_PRESUPUESTO_SOIN" ADD CONSTRAINT "FK_FECXP_PR_MONEDA_DE_FECXC_MO" FOREIGN KEY ("SECMONEDA")
	  REFERENCES "FECXC"."FECXC_MONEDAS" ("SECMONEDA") ENABLE;
