CREATE TABLE "FECXC"."FECXP_BIT_INGR_FACT" 
   (	"NO_EMPRESA" NUMBER(*,0) NOT NULL ENABLE, 
	"NO_FOLIO_DET" NUMBER(*,0) NOT NULL ENABLE, 
	"RECEIPT_NUMBER" VARCHAR2(30), 
	"NUM_RECIBO" NUMBER(*,0), 
	"FEC_VALOR" DATE, 
	"ID_STATUS_MOV" VARCHAR2(1), 
	"ID_TIPO_OPERACION_SET" NUMBER(*,0), 
	"FECHA_ACTUALIZACION" DATE, 
	"CASH_RECEIPT_ID" NUMBER(15,0), 
	"CUSTOMER_TRX_ID" NUMBER(15,0), 
	"CUSTOMER_TRX_LINE_ID" NUMBER(15,0), 
	"STATUS_RECIBO" VARCHAR2(30), 
	"SECUENCIA_DEP_ESPECIALES" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_DIVISA" VARCHAR2(3), 
	"IMPORTE" NUMBER(20,2), 
	"IMPORTE_RECIBO" NUMBER(20,2), 
	"CODE_COMBINATION" NUMBER(*,0), 
	"ORACLE_SEGMENTO1" VARCHAR2(25), 
	"ORACLE_SEGMENTO2" VARCHAR2(25), 
	"ORACLE_SEGMENTO3" VARCHAR2(25), 
	"ORACLE_SEGMENTO4" VARCHAR2(25), 
	"ORACLE_SEGMENTO5" VARCHAR2(25), 
	"ORACLE_SEGMENTO6" VARCHAR2(25), 
	"ORACLE_SEGMENTO7" VARCHAR2(25)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXP_BIT_INGR_FACT" ON "FECXC"."FECXP_BIT_INGR_FACT" ("SECUENCIA_DEP_ESPECIALES", "CASH_RECEIPT_ID", "CUSTOMER_TRX_ID", "CUSTOMER_TRX_LINE_ID") 
  ;
ALTER TABLE "FECXC"."FECXP_BIT_INGR_FACT" ADD CONSTRAINT "PK_FECXP_BIT_INGR_FACT" PRIMARY KEY ("SECUENCIA_DEP_ESPECIALES", "CASH_RECEIPT_ID", "CUSTOMER_TRX_ID", "CUSTOMER_TRX_LINE_ID")
  USING INDEX "FECXC"."PK_FECXP_BIT_INGR_FACT"  ENABLE;
