CREATE TABLE "FECXC"."FECXP_SEG_NO_SET" 
   (	"ID_SEG" NUMBER NOT NULL ENABLE, 
	"DESC_SEG" VARCHAR2(500) NOT NULL ENABLE, 
	"TIPO_EMPRESA" VARCHAR2(10) DEFAULT 'SET'
   ) ;
ALTER TABLE "FECXC"."FECXP_SEG_NO_SET" ADD PRIMARY KEY ("ID_SEG")
  USING INDEX  ENABLE;
