CREATE TABLE "FECXC"."FECXP_EMP_X_SEGMENTO_NO_SET" 
   (	"ID_SEGMENTO" NUMBER(*,0) NOT NULL ENABLE, 
	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"TIPO_EMPRESA" VARCHAR2(10)
   ) ;
ALTER TABLE "FECXC"."FECXP_EMP_X_SEGMENTO_NO_SET" ADD CONSTRAINT "PK_FECXP_EMP_X_SEGMENTO_NO_SET" PRIMARY KEY ("ID_SEGMENTO", "E_CODIGO")
  USING INDEX  ENABLE;
