CREATE TABLE "FECXC"."FECXC_DET_COMM_SEG_PDF" 
   (	"ID_FORMATO_PDF" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_USUARIO" VARCHAR2(30) NOT NULL ENABLE, 
	"ID_SEG_PDF" NUMBER(*,0) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXC_DET_COMM_SEG_PDF" ON "FECXC"."FECXC_DET_COMM_SEG_PDF" ("ID_FORMATO_PDF", "ID_USUARIO", "ID_SEG_PDF") 
  ;
ALTER TABLE "FECXC"."FECXC_DET_COMM_SEG_PDF" ADD CONSTRAINT "PK_FECXC_DET_COMM_SEG_PDF" PRIMARY KEY ("ID_FORMATO_PDF", "ID_USUARIO", "ID_SEG_PDF")
  USING INDEX "FECXC"."PK_FECXC_DET_COMM_SEG_PDF"  ENABLE;
ALTER TABLE "FECXC"."FECXC_DET_COMM_SEG_PDF" ADD CONSTRAINT "FK_FECXC_DE_FK_COMMSE_FECXC_EN" FOREIGN KEY ("ID_FORMATO_PDF", "ID_USUARIO")
	  REFERENCES "FECXC"."FECXC_ENC_COMMENTS_PDF" ("ID_FORMATO_PDF", "ID_USUARIO") ENABLE;
