CREATE TABLE "FECXC"."FECXP_BIT_CONT_DIN_APER_ENC" 
   (	"SECUENCIA_PAGOS_ERP" NUMBER(*,0) NOT NULL ENABLE, 
	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"FOLIO_SET" VARCHAR2(150) NOT NULL ENABLE, 
	"MONEDA" VARCHAR2(3), 
	"FECHA_APLICACION" DATE, 
	"TIPO_OPERACION" NUMBER(*,0), 
	"ID_BANCO" NUMBER(*,0), 
	"FORMA_PAGO" NUMBER(*,0), 
	"ESTATUS_MOVIMIENTO" VARCHAR2(1), 
	"ID_CHEQUERA" VARCHAR2(11), 
	"CONCEPTO" VARCHAR2(100), 
	"BENEFICIARIO" VARCHAR2(60), 
	"IMPORTE_SET" NUMBER(20,2), 
	"ESTATUS_CONT_DIN_APER" VARCHAR2(1) DEFAULT ('P'), 
	"FEC_PRIMERA_EJECUCION" DATE DEFAULT (SYSDATE), 
	"FEC_ULTIMA_EJECUCION" DATE DEFAULT (SYSDATE), 
	"DIAS_VIGENCIA_APERTURA" NUMBER(*,0) DEFAULT (60)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXP_BIT_CONT_DIN_APER_ENC" ON "FECXC"."FECXP_BIT_CONT_DIN_APER_ENC" ("E_CODIGO", "SECUENCIA_PAGOS_ERP") 
  ;
ALTER TABLE "FECXC"."FECXP_BIT_CONT_DIN_APER_ENC" ADD CONSTRAINT "CKC_BIT_CONT_DIN_APER_ENC" CHECK (ESTATUS_CONT_DIN_APER IN ('P','S', 'C')) ENABLE;
ALTER TABLE "FECXC"."FECXP_BIT_CONT_DIN_APER_ENC" ADD CONSTRAINT "PK_FECXP_BIT_CONT_DIN_APER_ENC" PRIMARY KEY ("E_CODIGO", "SECUENCIA_PAGOS_ERP")
  USING INDEX "FECXC"."PK_FECXP_BIT_CONT_DIN_APER_ENC"  ENABLE;
ALTER TABLE "FECXC"."FECXP_BIT_CONT_DIN_APER_ENC" ADD CONSTRAINT "FK_FECXP_BIT_CONT_DIN_PAGOS" FOREIGN KEY ("E_CODIGO", "SECUENCIA_PAGOS_ERP")
	  REFERENCES "FECXC"."FECXP_ENC_PAGOS_ERP" ("E_CODIGO", "SECUENCIA_PAGOS_ERP") ENABLE;
