CREATE TABLE "FECXC"."FECXP_REP_CONCILIACION_SOIN" 
   (	"COD_EMPRESA" NUMBER(*,0), 
	"DES_EMPRESA" VARCHAR2(100), 
	"CLA_ID_FE" VARCHAR2(25), 
	"CLA_FE_DES" VARCHAR2(25), 
	"CONCEPTO" VARCHAR2(40), 
	"MONEDA" VARCHAR2(3), 
	"IMPORTE_LINEA" NUMBER(20,4), 
	"TIPO_CAMBIO" NUMBER(20,11), 
	"FECHA_APLICACION" DATE, 
	"CTAM01" VARCHAR2(3), 
	"CTAM02" VARCHAR2(3), 
	"CTAM03" VARCHAR2(3)
   ) ;
