CREATE TABLE "FECXC"."FECXP_FOLIOS_PROV_DET" 
   (	"FECXP_E_CODIGO" NUMBER(*,0), 
	"FECXP_NO_FOLIO_DET" VARCHAR2(150), 
	"FECXP_IMPORTE" NUMBER(20,2), 
	"AP_INVOICE_ID" NUMBER(15,0), 
	"AP_INVOICE_AMOUNT" NUMBER, 
	"AP_DISTRIBUTION_LINE_NUMBER" NUMBER(15,0), 
	"AP_DISTRIBUTION_AMOUNT" NUMBER, 
	"AP_DIST_CODE_COMBINATION_ID" NUMBER(15,0), 
	"AP_CUENTA" VARCHAR2(150), 
	"SEGMENTO1" VARCHAR2(25), 
	"SEGMENTO2" VARCHAR2(25), 
	"SEGMENTO3" VARCHAR2(25), 
	"SEGMENTO4" VARCHAR2(25), 
	"SEGMENTO5" VARCHAR2(25), 
	"SEGMENTO6" VARCHAR2(25), 
	"SEGMENTO7" VARCHAR2(25)
   ) ;
