CREATE TABLE "FECXC"."FECXP_PPTO_BITACORA_PROCESOS" 
   (	"SEC_EXT_BITACORA" NUMBER(*,0), 
	"PROCESO_ID" NUMBER(*,0), 
	"FECHA_EXT_ULT_EJECUCION" DATE DEFAULT (TO_DATE ('19000101', 'YYYYMMDD')), 
	"ESTATUS_EXT_ULT_EJECUCION" VARCHAR2(255) DEFAULT ('NO APLICA'), 
	"PERIODO_PPTO_ULT_EJECUCION" NUMBER(*,0), 
	"VERSION_PPTO_ULT_EJECUCION" NUMBER(*,0), 
	"ESTATUS_PPTO_ULT_EJECUCION" VARCHAR2(255), 
	"VERSION_PPTO_GENERADO" NUMBER(*,0)
   ) ;
