CREATE TABLE "FECXC"."FECXC_ENC_CLASFECXC" 
   (	"COD_SEC_CATCLAS" NUMBER(*,0) NOT NULL ENABLE, 
	"CODCLASIF" VARCHAR2(10) NOT NULL ENABLE, 
	"SUB_DESCRIP" VARCHAR2(40) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXC_ENC_CLASFECXC" ON "FECXC"."FECXC_ENC_CLASFECXC" ("COD_SEC_CATCLAS") 
  ;
ALTER TABLE "FECXC"."FECXC_ENC_CLASFECXC" ADD CONSTRAINT "PK_FECXC_ENC_CLASFECXC" PRIMARY KEY ("COD_SEC_CATCLAS")
  USING INDEX "FECXC"."PK_FECXC_ENC_CLASFECXC"  ENABLE;
