CREATE TABLE "FECXC"."FECXP_B_DET_CLASIFICACION_FE" 
   (	"VERSION_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CLA_FE_ID" VARCHAR2(25) NOT NULL ENABLE, 
	"CLA_FE_DES" VARCHAR2(50), 
	"CLA_ATRIBUTO1" VARCHAR2(250), 
	"CLA_ATRIBUTO2" VARCHAR2(250), 
	"CLA_ATRIBUTO3" VARCHAR2(250), 
	"CLA_ATRIBUTO4" VARCHAR2(50), 
	"CLA_ATRIBUTO5" VARCHAR2(50), 
	"CLA_ATRIBUTO6" VARCHAR2(50), 
	"GENERA_SALDO" NUMBER(*,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."FECXP_B_DET_CLASIFICACION_FE00" ON "FECXC"."FECXP_B_DET_CLASIFICACION_FE" ("VERSION_ID", "CLA_FE_ID") 
  ;
ALTER TABLE "FECXC"."FECXP_B_DET_CLASIFICACION_FE" ADD CONSTRAINT "PKFECXP_B_DET_CLASIFICACION_FE" PRIMARY KEY ("VERSION_ID", "CLA_FE_ID")
  USING INDEX "FECXC"."FECXP_B_DET_CLASIFICACION_FE00"  ENABLE;
ALTER TABLE "FECXC"."FECXP_B_DET_CLASIFICACION_FE" ADD CONSTRAINT "FKFECXP_B_DET_CLASIFICACION_FE" FOREIGN KEY ("VERSION_ID")
	  REFERENCES "FECXC"."FECXP_B_ENC_CLASIFICACION_FE" ("VERSION_ID") ENABLE;
