CREATE TABLE "FECXC"."FECXC_RESTA_SEGMENTOS" 
   (	"COD_SEC_TIPCAT" NUMBER(*,0), 
	"COD_SEC_LIN" NUMBER(*,0)
   ) ;
ALTER TABLE "FECXC"."FECXC_RESTA_SEGMENTOS" ADD CONSTRAINT "FK_FECXC_RE_SEGMENTOS_FECXC_DE" FOREIGN KEY ("COD_SEC_TIPCAT", "COD_SEC_LIN")
	  REFERENCES "FECXC"."FECXC_DET_CATALOGOS" ("COD_SEC_TIPCAT", "COD_SEC_LIN") ENABLE;
