CREATE TABLE "FECXC"."FECXC_COB_CANAL_XMES" 
   (	"E_CODIGO" NUMBER(*,0), 
	"SEGMENTO" NUMBER(*,0), 
	"CODMONEDA" VARCHAR2(3), 
	"MES" NUMBER(*,0), 
	"COBRANZA_MES" NUMBER(20,2), 
	"COBRANZAREAL_MES" NUMBER(20,2)
   ) ;
ALTER TABLE "FECXC"."FECXC_COB_CANAL_XMES" ADD CONSTRAINT "FK_FECXC_CO_CN_COBMES_FECXC_EM" FOREIGN KEY ("E_CODIGO")
	  REFERENCES "FECXC"."FECXC_EMPRESAS" ("E_CODIGO") ENABLE;
