CREATE TABLE "FECXC"."FECXP_CLASIFICACION_FE" 
   (	"CLA_FE_ID" VARCHAR2(25) NOT NULL ENABLE, 
	"CLA_FE_DES" VARCHAR2(50), 
	"CLA_ATRIBUTO1" VARCHAR2(250), 
	"CLA_ATRIBUTO2" VARCHAR2(250), 
	"CLA_ATRIBUTO3" VARCHAR2(250), 
	"CLA_ATRIBUTO4" VARCHAR2(50), 
	"CLA_ATRIBUTO5" VARCHAR2(50), 
	"CLA_ATRIBUTO6" VARCHAR2(50), 
	"GENERA_SALDO" NUMBER(*,0), 
	"VERSION_ID" NUMBER(*,0) DEFAULT (0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXP_CLASIFICACION_FE" ON "FECXC"."FECXP_CLASIFICACION_FE" ("CLA_FE_ID") 
  ;
ALTER TABLE "FECXC"."FECXP_CLASIFICACION_FE" ADD CONSTRAINT "PK_FECXP_CLASIFICACION_FE" PRIMARY KEY ("CLA_FE_ID")
  USING INDEX "FECXC"."PK_FECXP_CLASIFICACION_FE"  ENABLE;
