CREATE TABLE "FECXC"."FECXC_ENC_COMMENTS_PDF" 
   (	"ID_FORMATO_PDF" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_USUARIO" VARCHAR2(30) NOT NULL ENABLE, 
	"COMENTARIO" VARCHAR2(100) NOT NULL ENABLE, 
	"COMENTARIO_CORTO" VARCHAR2(10) NOT NULL ENABLE, 
	"ESTATUS_COMM" VARCHAR2(1) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXC_ENC_COMMENTS_PDF" ON "FECXC"."FECXC_ENC_COMMENTS_PDF" ("ID_FORMATO_PDF", "ID_USUARIO") 
  ;
ALTER TABLE "FECXC"."FECXC_ENC_COMMENTS_PDF" ADD CONSTRAINT "CKC_ESTATUS_COMM_FECXC_EN" CHECK (ESTATUS_COMM in ('A','I')) ENABLE;
ALTER TABLE "FECXC"."FECXC_ENC_COMMENTS_PDF" ADD CONSTRAINT "PK_FECXC_ENC_COMMENTS_PDF" PRIMARY KEY ("ID_FORMATO_PDF", "ID_USUARIO")
  USING INDEX "FECXC"."PK_FECXC_ENC_COMMENTS_PDF"  ENABLE;
