CREATE TABLE "FECXC"."FECXP_PPTO_CONVERSION_SOIN" 
   (	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"SECUENCIA_PPTO_OPERATIVO_SOIN" NUMBER(*,0) NOT NULL ENABLE, 
	"PERIODO" NUMBER(*,0) NOT NULL ENABLE, 
	"MESCOD" NUMBER(*,0) NOT NULL ENABLE, 
	"ARSMAP" VARCHAR2(3) NOT NULL ENABLE, 
	"AEJMAP" VARCHAR2(3) NOT NULL ENABLE, 
	"CNCMAP" VARCHAR2(3) NOT NULL ENABLE, 
	"CTACR1" VARCHAR2(3), 
	"CTACR2" VARCHAR2(4), 
	"IMPORTE_LINEA" NUMBER(20,4) NOT NULL ENABLE, 
	"MONEDA" VARCHAR2(3) NOT NULL ENABLE, 
	"TIPO_CAMBIO" NUMBER(20,11) NOT NULL ENABLE, 
	"PERIODO_EXTRACCION" NUMBER(15,0) DEFAULT to_number(to_char(sysdate,'yyyy')), 
	"MES_EXTRACCION" NUMBER(*,0) DEFAULT to_number(to_char(sysdate,'mm')), 
	"PRESUPUESTO_ESTATUS" VARCHAR2(20), 
	"VERSION_FE" NUMBER(*,0) DEFAULT (0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXP_PPTO_CONVERSION_SOIN" ON "FECXC"."FECXP_PPTO_CONVERSION_SOIN" ("E_CODIGO", "SECUENCIA_PPTO_OPERATIVO_SOIN", "VERSION_FE") 
  ;
ALTER TABLE "FECXC"."FECXP_PPTO_CONVERSION_SOIN" ADD CONSTRAINT "PK_FECXP_PPTO_CONVERSION_SOIN" PRIMARY KEY ("E_CODIGO", "SECUENCIA_PPTO_OPERATIVO_SOIN", "VERSION_FE")
  USING INDEX "FECXC"."PK_FECXP_PPTO_CONVERSION_SOIN"  ENABLE;
