CREATE TABLE "FECXC"."FECXP_PPTO_CONVERSION_SOIN_ENC" 
   (	"VERSION_FE" NUMBER(*,0), 
	"COMENTARIO" VARCHAR2(255), 
	"USUARIO_ID" VARCHAR2(15), 
	"FECHA_EXTRACCION" DATE, 
	"VERSION_REGLAS" NUMBER(*,0), 
	"FECHA_VERSION_REGLAS" DATE, 
	"PERIODO_ORIGEN" NUMBER(*,0), 
	"VERSION_ORIGEN" NUMBER(*,0), 
	"ESTATUS_ORIGEN" VARCHAR2(255), 
	"VERSION_FE_ORIGEN" NUMBER(*,0), 
	"MES_EXTRACCION" NUMBER(*,0) DEFAULT (TO_NUMBER (TO_CHAR (SYSDATE, 'MM'))), 
	"PERIODO_EXTRACCION" NUMBER(*,0) DEFAULT (TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY'))), 
	"ESTATUS_FE" VARCHAR2(25) DEFAULT ('APLICADA')
   ) ;
