CREATE TABLE "FECXC"."FECXP_CTAS_CLASIF_PPTO_ERP" 
   (	"CLA_FE_ID" VARCHAR2(25), 
	"E_CODIGO" NUMBER(*,0), 
	"CODE_COMBINATION_ID" NUMBER(*,0), 
	"ORACLE_SEGMENTO1" VARCHAR2(25), 
	"ORACLE_SEGMENTO2" VARCHAR2(25), 
	"ORACLE_SEGMENTO3" VARCHAR2(25), 
	"ORACLE_SEGMENTO4" VARCHAR2(25), 
	"ORACLE_SEGMENTO5" VARCHAR2(25), 
	"ORACLE_SEGMENTO6" VARCHAR2(25), 
	"ORACLE_SEGMENTO7" VARCHAR2(25)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."FECXP_CTAS_CLASIF_PPTO_ERP03" ON "FECXC"."FECXP_CTAS_CLASIF_PPTO_ERP" ("ORACLE_SEGMENTO1", "ORACLE_SEGMENTO2", "ORACLE_SEGMENTO3", "ORACLE_SEGMENTO4", "ORACLE_SEGMENTO5", "ORACLE_SEGMENTO6", "ORACLE_SEGMENTO7") 
  ;
ALTER TABLE "FECXC"."FECXP_CTAS_CLASIF_PPTO_ERP" ADD CONSTRAINT "IDX_SEGMENTOS_CAR_ERP" PRIMARY KEY ("ORACLE_SEGMENTO1", "ORACLE_SEGMENTO2", "ORACLE_SEGMENTO3", "ORACLE_SEGMENTO4", "ORACLE_SEGMENTO5", "ORACLE_SEGMENTO6", "ORACLE_SEGMENTO7")
  USING INDEX "FECXC"."FECXP_CTAS_CLASIF_PPTO_ERP03"  ENABLE;
