CREATE TABLE "FECXC"."FECXP_REP_PPTO_COM_CTA_ERP" 
   (	"CLA_FE_ID" VARCHAR2(25), 
	"E_CODIGO" NUMBER(*,0), 
	"CODE_COMBINATION_ID" NUMBER NOT NULL ENABLE, 
	"ORACLE_SEGMENTO1" VARCHAR2(25), 
	"ORACLE_SEGMENTO2" VARCHAR2(25), 
	"ORACLE_SEGMENTO3" VARCHAR2(25), 
	"ORACLE_SEGMENTO4" VARCHAR2(25), 
	"ORACLE_SEGMENTO5" VARCHAR2(25), 
	"ORACLE_SEGMENTO6" VARCHAR2(25), 
	"ORACLE_SEGMENTO7" VARCHAR2(25), 
	"MONEDA" VARCHAR2(3), 
	"ID_SESION" VARCHAR2(25)
   ) ;
