CREATE TABLE "FECXC"."FECXC_TIPOS_LINEA" 
   (	"TIPO_LINEA" VARCHAR2(30) NOT NULL ENABLE, 
	"VISIBLE_SIONO" VARCHAR2(2)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXC_TIPOS_LINEA" ON "FECXC"."FECXC_TIPOS_LINEA" ("TIPO_LINEA") 
  ;
ALTER TABLE "FECXC"."FECXC_TIPOS_LINEA" ADD CONSTRAINT "CKC_TIPO_LINEA_FECXC_TI" CHECK (TIPO_LINEA in ('IMPUESTO','BASE','OTROS','DNI','INTERCAMBIOS','COBVIRTUAL','RECLASIFICACIONES','TRASPASOS','OTROS_INGRESOS','INTERESES','FILLER_UNO','FILLER_DOS')) ENABLE;
ALTER TABLE "FECXC"."FECXC_TIPOS_LINEA" ADD CONSTRAINT "CKC_VISIBLE_SIONO_FECXC_TI" CHECK (VISIBLE_SIONO is null or ( VISIBLE_SIONO in ('SI','NO') )) ENABLE;
ALTER TABLE "FECXC"."FECXC_TIPOS_LINEA" ADD CONSTRAINT "PK_FECXC_TIPOS_LINEA" PRIMARY KEY ("TIPO_LINEA")
  USING INDEX "FECXC"."PK_FECXC_TIPOS_LINEA"  ENABLE;
