CREATE TABLE "FECXC"."FECXP_REP_FORECAST" 
   (	"CLA_FE_ID" VARCHAR2(25) NOT NULL ENABLE, 
	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"TIPO_DATO" VARCHAR2(2), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"MONEDA" VARCHAR2(3), 
	"TIPO_CAMBIO" NUMBER(20,11), 
	"IMPORTE_LINEA" NUMBER(20,4), 
	"CLA_FE_DES" VARCHAR2(100), 
	"DES_EMPRESA" VARCHAR2(100), 
	"ID_SESION_RC" VARCHAR2(256), 
	"ESTATUS" VARCHAR2(25) DEFAULT 'E'
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXP_REP_FORECAST" ON "FECXC"."FECXP_REP_FORECAST" ("CLA_FE_ID", "E_CODIGO") 
  ;
ALTER TABLE "FECXC"."FECXP_REP_FORECAST" ADD CONSTRAINT "PK_FECXP_REP_FORECAST" PRIMARY KEY ("CLA_FE_ID", "E_CODIGO")
  USING INDEX "FECXC"."PK_FECXP_REP_FORECAST"  ENABLE;
ALTER TABLE "FECXC"."FECXP_REP_FORECAST" ADD CONSTRAINT "FK_FECXP_RE_FORECAST__FECXP_CL" FOREIGN KEY ("CLA_FE_ID")
	  REFERENCES "FECXC"."FECXP_CLASIFICACION_FE" ("CLA_FE_ID") ENABLE;
