CREATE TABLE "FECXC"."FECXC_INPC" 
   (	"SEC_INPC" NUMBER(*,0) NOT NULL ENABLE, 
	"ANO_INPC" NUMBER(*,0) NOT NULL ENABLE, 
	"MES_INPC" NUMBER(*,0) NOT NULL ENABLE, 
	"INPC_ESTIMADO" NUMBER(20,11) NOT NULL ENABLE, 
	"INPC_ACTUAL" NUMBER(20,11) NOT NULL ENABLE, 
	"INPC_FACTORAC" NUMBER(20,11) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXC_INPC" ON "FECXC"."FECXC_INPC" ("SEC_INPC") 
  ;
ALTER TABLE "FECXC"."FECXC_INPC" ADD CONSTRAINT "PK_FECXC_INPC" PRIMARY KEY ("SEC_INPC")
  USING INDEX "FECXC"."PK_FECXC_INPC"  ENABLE;
