CREATE TABLE "FECXC"."FECXP_ORG_INV_FLUJO" 
   (	"SECUENCIA_ORG_FE" NUMBER(*,0) NOT NULL ENABLE, 
	"ORGANIZATION_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"CLA_FE_ID" VARCHAR2(25) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXP_ORG_INV_FLUJO" ON "FECXC"."FECXP_ORG_INV_FLUJO" ("SECUENCIA_ORG_FE", "ORGANIZATION_ID", "CLA_FE_ID") 
  ;
ALTER TABLE "FECXC"."FECXP_ORG_INV_FLUJO" ADD CONSTRAINT "PK_FECXP_ORG_INV_FLUJO" PRIMARY KEY ("SECUENCIA_ORG_FE", "ORGANIZATION_ID", "CLA_FE_ID")
  USING INDEX "FECXC"."PK_FECXP_ORG_INV_FLUJO"  ENABLE;
ALTER TABLE "FECXC"."FECXP_ORG_INV_FLUJO" ADD CONSTRAINT "FK_FECXP_ORG_INV_FLUJO_FE" FOREIGN KEY ("CLA_FE_ID")
	  REFERENCES "FECXC"."FECXP_CLASIFICACION_FE" ("CLA_FE_ID") ENABLE;
