CREATE TABLE "FECXC"."FECXC_CANINTER_ALAFECH_COB_ANT" 
   (	"E_CODIGO" NUMBER(*,0), 
	"SEGMENTO" NUMBER(*,0), 
	"CANAL" NUMBER(*,0), 
	"CODMONEDA" VARCHAR2(3), 
	"MES" NUMBER(*,0), 
	"COBRANZA_MES" NUMBER(20,4), 
	"COBRANZAREAL_MES" NUMBER(20,4)
   ) ;
ALTER TABLE "FECXC"."FECXC_CANINTER_ALAFECH_COB_ANT" ADD CONSTRAINT "FK_FECXC_CA_CN_COBAFE_FECXC_EM" FOREIGN KEY ("E_CODIGO")
	  REFERENCES "FECXC"."FECXC_EMPRESAS" ("E_CODIGO") ENABLE;
