CREATE TABLE "FECXC"."FECXP_IMPORTACION_DATOS_NS" 
   (	"TIPO_IMPORTACION" VARCHAR2(2), 
	"ID_SEGMENTO" NUMBER, 
	"E_EMPRESA_IMP" VARCHAR2(25), 
	"CLA_FE_ID_IMP" VARCHAR2(25), 
	"IMPORTE_LINEA" NUMBER(20,4), 
	"MONEDA_IMP" VARCHAR2(3), 
	"MES" NUMBER(*,0), 
	"FECHA" DATE, 
	"ATRIBUTO_1" VARCHAR2(256), 
	"ATRIBUTO_2" VARCHAR2(256), 
	"ATRIBUTO_3" VARCHAR2(256), 
	"ATRIBUTO_4" VARCHAR2(256), 
	"ESTATUS_ORIGEN" VARCHAR2(25) DEFAULT 'EN ESPERA', 
	"UTILIZAR_REPORTE" VARCHAR2(1)
   ) ;
