CREATE TABLE "FECXC"."FECXP_BITACORA_HISTORICOS" 
   (	"PROCESO_ID" NUMBER(*,0), 
	"PROCESO_NOMBRE" VARCHAR2(255), 
	"CREATED_BY" VARCHAR2(255), 
	"DATE_CREATED" DATE, 
	"ID_VERSION" NUMBER(*,0) DEFAULT (0), 
	"DESC_VERSION" VARCHAR2(255), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"COMENTARIO" VARCHAR2(255), 
	"TIPO_OPERACION" VARCHAR2(50)
   ) ;
