CREATE TABLE "FECXC"."FECXC_CANINTER_ALAFECHA_PRE" 
   (	"SEGMENTO" NUMBER(*,0), 
	"CANAL" NUMBER(*,0), 
	"CODMONEDA" VARCHAR2(3), 
	"MES" NUMBER(*,0), 
	"PRESUP_MES" NUMBER(20,4), 
	"PRESUPREAL_MES" NUMBER(20,4)
   ) ;
