CREATE TABLE "FECXC"."FECXC_DET_COMM_MON_PDF" 
   (	"ID_FORMATO_PDF" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_USUARIO" VARCHAR2(30) NOT NULL ENABLE, 
	"ID_MONEDA" VARCHAR2(3) NOT NULL ENABLE, 
	"TIPO_EMPRESA" VARCHAR2(2) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXC_DET_COMM_MON_PDF" ON "FECXC"."FECXC_DET_COMM_MON_PDF" ("ID_FORMATO_PDF", "ID_USUARIO", "ID_MONEDA", "TIPO_EMPRESA") 
  ;
ALTER TABLE "FECXC"."FECXC_DET_COMM_MON_PDF" ADD CONSTRAINT "PK_FECXC_DET_COMM_MON_PDF" PRIMARY KEY ("ID_FORMATO_PDF", "ID_USUARIO", "ID_MONEDA", "TIPO_EMPRESA")
  USING INDEX "FECXC"."PK_FECXC_DET_COMM_MON_PDF"  ENABLE;
ALTER TABLE "FECXC"."FECXC_DET_COMM_MON_PDF" ADD CONSTRAINT "CKC_TIPO_EMPRESA_FECXC_DE" CHECK (TIPO_EMPRESA in ('GE','NG')) ENABLE;
ALTER TABLE "FECXC"."FECXC_DET_COMM_MON_PDF" ADD CONSTRAINT "FK_FECXC_DE_FK_COMMMO_FECXC_EN" FOREIGN KEY ("ID_FORMATO_PDF", "ID_USUARIO")
	  REFERENCES "FECXC"."FECXC_ENC_COMMENTS_PDF" ("ID_FORMATO_PDF", "ID_USUARIO") ENABLE;
