CREATE TABLE "FECXC"."FECXP_REGLAS_CONVERSION_PPTO" 
   (	"REGLA_ID_CONVERSION" NUMBER(*,0) NOT NULL ENABLE, 
	"PLATAFORMA" VARCHAR2(25), 
	"REG_SEGMENTO1_INI" VARCHAR2(25), 
	"REG_SEGMENTO1_FIN" VARCHAR2(25), 
	"REG_SEGMENTO2_INI" VARCHAR2(25), 
	"REG_SEGMENTO2_FIN" VARCHAR2(25), 
	"REG_SEGMENTO3_INI" VARCHAR2(25), 
	"REG_SEGMENTO3_FIN" VARCHAR2(25), 
	"REG_SEGMENTO4_INI" VARCHAR2(25), 
	"REG_SEGMENTO4_FIN" VARCHAR2(25), 
	"REG_SEGMENTO5_INI" VARCHAR2(25), 
	"REG_SEGMENTO5_FIN" VARCHAR2(25), 
	"REG_SEGMENTO6_INI" VARCHAR2(25), 
	"REG_SEGMENTO6_FIN" VARCHAR2(25), 
	"REG_SEGMENTO7_INI" VARCHAR2(25), 
	"REG_SEGMENTO7_FIN" VARCHAR2(25), 
	"PERIODO" NUMBER(*,0), 
	"MES_INI" NUMBER(*,0), 
	"MES_FIN" NUMBER(*,0), 
	"REG_SEGMENTO8_INI" VARCHAR2(25), 
	"REG_SEGMENTO8_FIN" VARCHAR2(25), 
	"MES_ACUMULACION" NUMBER(*,0) DEFAULT (0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXP_REGLAS_CONVERSION_PPT" ON "FECXC"."FECXP_REGLAS_CONVERSION_PPTO" ("REGLA_ID_CONVERSION") 
  ;
ALTER TABLE "FECXC"."FECXP_REGLAS_CONVERSION_PPTO" ADD CONSTRAINT "PK_FECXP_REGLAS_CONVERSION_PPT" PRIMARY KEY ("REGLA_ID_CONVERSION")
  USING INDEX "FECXC"."PK_FECXP_REGLAS_CONVERSION_PPT"  ENABLE;
ALTER TABLE "FECXC"."FECXP_REGLAS_CONVERSION_PPTO" ADD CONSTRAINT "CKC_PLATAFORMA_FECXP_RE" CHECK (PLATAFORMA is null or ( PLATAFORMA in ('SOIN','ORACLE') )) ENABLE;
