CREATE TABLE "FECXC"."FECXP_CREAR_MISCELANEOS" 
   (	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"FOLIO_SET" NUMBER(*,0) NOT NULL ENABLE, 
	"SECUENCIA_DEP_ESPECIALES" NUMBER(*,0), 
	"SECUENCIA_APLICADA" NUMBER(*,0), 
	"ESTATUS_DIN_CC_APLI" VARCHAR2(1)
   ) ;
