CREATE TABLE "FECXC"."FECXP_PPTO_CONVERSION_ERP" 
   (	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"SECUENCIA_PTTO_CONVERSION" NUMBER(*,0) NOT NULL ENABLE, 
	"PERIODO" NUMBER(*,0) NOT NULL ENABLE, 
	"MES" NUMBER(*,0) NOT NULL ENABLE, 
	"LIBRO_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"VERSION_ID" NUMBER(15,0) NOT NULL ENABLE, 
	"MONEDA" VARCHAR2(3) NOT NULL ENABLE, 
	"TIPO_CAMBIO" NUMBER(20,11) NOT NULL ENABLE, 
	"CODE_COMBINATION" NUMBER(*,0) NOT NULL ENABLE, 
	"IMPORTE_LINEA" NUMBER(20,4) NOT NULL ENABLE, 
	"ORACLE_SEGMENTO1" VARCHAR2(25) NOT NULL ENABLE, 
	"ORACLE_SEGMENTO2" VARCHAR2(25) NOT NULL ENABLE, 
	"ORACLE_SEGMENTO3" VARCHAR2(25) NOT NULL ENABLE, 
	"ORACLE_SEGMENTO4" VARCHAR2(25) NOT NULL ENABLE, 
	"ORACLE_SEGMENTO5" VARCHAR2(25) NOT NULL ENABLE, 
	"ORACLE_SEGMENTO6" VARCHAR2(25) NOT NULL ENABLE, 
	"ORACLE_SEGMENTO7" VARCHAR2(25) NOT NULL ENABLE, 
	"PERIODO_EXTRACCION" NUMBER(15,0) NOT NULL ENABLE, 
	"MES_EXTRACCION" NUMBER(*,0) NOT NULL ENABLE, 
	"PRESUPUESTO_ESTATUS" VARCHAR2(20) NOT NULL ENABLE, 
	"VERSION_FE" NUMBER(*,0) DEFAULT (0), 
	"MON_FUNC" VARCHAR2(3), 
	"MON_ORIG" VARCHAR2(3)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXP_PPTO_CONVERSION_ERP" ON "FECXC"."FECXP_PPTO_CONVERSION_ERP" ("E_CODIGO", "SECUENCIA_PTTO_CONVERSION", "VERSION_FE") 
  ;
ALTER TABLE "FECXC"."FECXP_PPTO_CONVERSION_ERP" ADD CONSTRAINT "PK_FECXP_PPTO_CONVERSION_ERP" PRIMARY KEY ("E_CODIGO", "SECUENCIA_PTTO_CONVERSION", "VERSION_FE")
  USING INDEX "FECXC"."PK_FECXP_PPTO_CONVERSION_ERP"  ENABLE;
