CREATE TABLE "FECXC"."FECXC_DET_PRES_DIARIO" 
   (	"SEC_PRESUP" NUMBER(*,0) NOT NULL ENABLE, 
	"SEC_PRES_DIA" NUMBER(*,0) NOT NULL ENABLE, 
	"DIARIO" DATE NOT NULL ENABLE, 
	"SEGMENTO1" NUMBER(*,0), 
	"SEGMENTO2" NUMBER(*,0), 
	"SEGMENTO3" NUMBER(*,0), 
	"SEGMENTO4" NUMBER(*,0), 
	"SEGMENTO5" NUMBER(*,0), 
	"SEGMENTO6" NUMBER(*,0), 
	"SEGMENTO7" NUMBER(*,0), 
	"SEGMENTO8" NUMBER(*,0), 
	"SEGMENTO9" NUMBER(*,0), 
	"SEGMENTO10" NUMBER(*,0), 
	"IMPORTE" NUMBER(20,2) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXC_DET_PRES_DIARIO" ON "FECXC"."FECXC_DET_PRES_DIARIO" ("SEC_PRESUP", "SEC_PRES_DIA") 
  ;
ALTER TABLE "FECXC"."FECXC_DET_PRES_DIARIO" ADD CONSTRAINT "PK_FECXC_DET_PRES_DIARIO" PRIMARY KEY ("SEC_PRESUP", "SEC_PRES_DIA")
  USING INDEX "FECXC"."PK_FECXC_DET_PRES_DIARIO"  ENABLE;
ALTER TABLE "FECXC"."FECXC_DET_PRES_DIARIO" ADD CONSTRAINT "FK_DET_PRES_DET_P" FOREIGN KEY ("SEC_PRESUP")
	  REFERENCES "FECXC"."FECXC_ENC_DE_PRESU" ("SEC_PRESUP") ENABLE;
