CREATE TABLE "FECXC"."FECXP_DET_PAGOS_ERP" 
   (	"SECUENCIA_DET_PAGOS_ERP" NUMBER(*,0) NOT NULL ENABLE, 
	"SECUENCIA_PAGOS_ERP" NUMBER(*,0) NOT NULL ENABLE, 
	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"NUMERO_DE_PARTIDA_ERP" NUMBER(*,0) NOT NULL ENABLE, 
	"CODE_COMBINATION" NUMBER(*,0), 
	"IMPORTE_LINEA" NUMBER(20,4), 
	"ORACLE_SEGMENTO1" VARCHAR2(25), 
	"ORACLE_SEGMENTO2" VARCHAR2(25), 
	"ORACLE_SEGMENTO3" VARCHAR2(25), 
	"ORACLE_SEGMENTO4" VARCHAR2(25), 
	"ORACLE_SEGMENTO5" VARCHAR2(25), 
	"ORACLE_SEGMENTO6" VARCHAR2(25), 
	"ORACLE_SEGMENTO7" VARCHAR2(25)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXP_DET_PAGOS_ERP" ON "FECXC"."FECXP_DET_PAGOS_ERP" ("E_CODIGO", "SECUENCIA_PAGOS_ERP", "SECUENCIA_DET_PAGOS_ERP", "NUMERO_DE_PARTIDA_ERP") 
  ;
ALTER TABLE "FECXC"."FECXP_DET_PAGOS_ERP" ADD CONSTRAINT "PK_FECXP_DET_PAGOS_ERP" PRIMARY KEY ("E_CODIGO", "SECUENCIA_PAGOS_ERP", "SECUENCIA_DET_PAGOS_ERP", "NUMERO_DE_PARTIDA_ERP")
  USING INDEX "FECXC"."PK_FECXP_DET_PAGOS_ERP"  ENABLE;
ALTER TABLE "FECXC"."FECXP_DET_PAGOS_ERP" ADD CONSTRAINT "FK_FECXP_DE_PAGOS_ORA_FECXP_EN" FOREIGN KEY ("E_CODIGO", "SECUENCIA_PAGOS_ERP")
	  REFERENCES "FECXC"."FECXP_ENC_PAGOS_ERP" ("E_CODIGO", "SECUENCIA_PAGOS_ERP") ENABLE;
