CREATE TABLE "FECXC"."FECXP_FOLIOS_PROV_ENC" 
   (	"FECXP_E_CODIGO" NUMBER(*,0), 
	"FECXP_NO_FOLIO_DET" VARCHAR2(150), 
	"FECXP_IMPORTE" NUMBER(20,2), 
	"AP_INVOICE_ID" NUMBER(15,0), 
	"AP_INVOICE_AMOUNT" NUMBER
   ) ;
