CREATE TABLE "FECXC"."FECXP_REP_MVCOMP_SOIN" 
   (	"COD_EMPRESA" NUMBER(*,0), 
	"DES_EMPRESA" VARCHAR2(100), 
	"CLA_ID_FE" VARCHAR2(25), 
	"CLA_FE_DES" VARCHAR2(25), 
	"RUBRO" VARCHAR2(25), 
	"ORDEN_ID" NUMBER(*,0), 
	"FECHA_APLICACION" DATE, 
	"MONEDA" VARCHAR2(3), 
	"TIPO_CAMBIO" NUMBER(20,11), 
	"IMPORTE_DEBITO" NUMBER(20,4), 
	"IMPORTE_CREDITO" NUMBER(20,4), 
	"CTAM01" VARCHAR2(3), 
	"CTAM02" VARCHAR2(3), 
	"CTAM03" VARCHAR2(3), 
	"CG13GR" NUMBER(*,0), 
	"CG13RU" NUMBER(*,0), 
	"CTATIP" VARCHAR2(1)
   ) ;
