CREATE TABLE "FECXC"."FECXP_CTAS_CLASIF_REAL_ERP_H" 
   (	"CLA_FE_ID" VARCHAR2(25), 
	"E_CODIGO" NUMBER(*,0), 
	"TIPO_OPERACION" NUMBER(*,0), 
	"ORACLE_SEGMENTO1" VARCHAR2(25), 
	"ORACLE_SEGMENTO2" VARCHAR2(25), 
	"ORACLE_SEGMENTO3" VARCHAR2(25), 
	"ORACLE_SEGMENTO4" VARCHAR2(25), 
	"ORACLE_SEGMENTO5" VARCHAR2(25), 
	"ORACLE_SEGMENTO6" VARCHAR2(25), 
	"ORACLE_SEGMENTO7" VARCHAR2(25), 
	"ID_BANCO" NUMBER(*,0), 
	"ID_CHEQUERA" VARCHAR2(20), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"ID_VERSION" NUMBER(*,0)
   ) ;
