CREATE TABLE "FECXC"."FECXC_MONEDAS" 
   (	"SECMONEDA" NUMBER(*,0) NOT NULL ENABLE, 
	"CODMONEDA" VARCHAR2(3), 
	"DESMONEDA" VARCHAR2(40), 
	"ES_MONEDA_LOCCAL" NUMBER(*,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXC_MONEDAS" ON "FECXC"."FECXC_MONEDAS" ("SECMONEDA") 
  ;
ALTER TABLE "FECXC"."FECXC_MONEDAS" ADD CONSTRAINT "PK_FECXC_MONEDAS" PRIMARY KEY ("SECMONEDA")
  USING INDEX "FECXC"."PK_FECXC_MONEDAS"  ENABLE;
