CREATE TABLE "FECXC"."FECXC_DET_CLASFECXC" 
   (	"COD_SEC_CATCLAS" NUMBER(*,0) NOT NULL ENABLE, 
	"COD_SEC_DET" NUMBER(*,0) NOT NULL ENABLE, 
	"TIPO_LINEA" VARCHAR2(30), 
	"CODCLASIF" VARCHAR2(10) NOT NULL ENABLE, 
	"COD_SUBCLASIF" VARCHAR2(10) NOT NULL ENABLE, 
	"SUB_DESCRIP" VARCHAR2(40) NOT NULL ENABLE, 
	"NOPARA_FLUJO" NUMBER(*,0) NOT NULL ENABLE, 
	"EXCLUIR_ENREPORTES" VARCHAR2(2) DEFAULT 'NO'
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXC_DET_CLASFECXC" ON "FECXC"."FECXC_DET_CLASFECXC" ("COD_SEC_CATCLAS", "COD_SEC_DET") 
  ;
ALTER TABLE "FECXC"."FECXC_DET_CLASFECXC" ADD CONSTRAINT "CKC_TIPLIN" CHECK (TIPO_LINEA is null or ( TIPO_LINEA in ('IMPUESTO','BASE','OTROS','DNI','INTERCAMBIOS','COBVIRTUAL','RECLASIFICACIONES','TRASPASOS','OTROS_INGRESOS','INTERESES','FILLER_UNO','FILLER_DOS') )) ENABLE;
ALTER TABLE "FECXC"."FECXC_DET_CLASFECXC" ADD CONSTRAINT "CKC_EXCLUIR_ENREPORTE_FECXC_DE" CHECK (EXCLUIR_ENREPORTES is null or ( EXCLUIR_ENREPORTES in ('SI','NO') )) ENABLE;
ALTER TABLE "FECXC"."FECXC_DET_CLASFECXC" ADD CONSTRAINT "CKC_NOPARA_FLUJO_FECXC_DE" CHECK (NOPARA_FLUJO in (0,1,2)) ENABLE;
ALTER TABLE "FECXC"."FECXC_DET_CLASFECXC" ADD CONSTRAINT "PK_FECXC_DET_CLASFECXC" PRIMARY KEY ("COD_SEC_CATCLAS", "COD_SEC_DET")
  USING INDEX "FECXC"."PK_FECXC_DET_CLASFECXC"  ENABLE;
ALTER TABLE "FECXC"."FECXC_DET_CLASFECXC" ADD CONSTRAINT "FK_FECXC_DE_ENC_DET_C_FECXC_EN" FOREIGN KEY ("COD_SEC_CATCLAS")
	  REFERENCES "FECXC"."FECXC_ENC_CLASFECXC" ("COD_SEC_CATCLAS") ENABLE;
