CREATE TABLE "FECXC"."FECXP_ENC_PAGOS_SOIN" 
   (	"SECUENCIA_PAGOS_SOIN" NUMBER(*,0) NOT NULL ENABLE, 
	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"SECMONEDA" NUMBER(*,0), 
	"FOLIO_SET" VARCHAR2(150) NOT NULL ENABLE, 
	"PERIODO" NUMBER(*,0), 
	"CVE_OPERACION" NUMBER(*,0), 
	"ESTATUS_MOVIMIENTO" VARCHAR2(1), 
	"NO_CHEQUE" NUMBER(*,0), 
	"ID_CHEQUERA" VARCHAR2(11), 
	"ID_BANCO" NUMBER(*,0), 
	"IMPORTE" NUMBER(20,2), 
	"FORMA_PAGO" NUMBER(*,0), 
	"FECHA_APLICACION" DATE, 
	"MONEDA" VARCHAR2(3), 
	"TIPO_CAMBIO" NUMBER(20,11), 
	"ORIGEN_MOVIMIENTO" VARCHAR2(3), 
	"TIPO_OPERACION" NUMBER(*,0), 
	"NO_CLIENTE" VARCHAR2(15), 
	"ID_BANCO_BENEF" NUMBER(*,0), 
	"ID_CHEQUERA_BENEF" VARCHAR2(11), 
	"LOTE_ENTRADA" NUMBER(*,0), 
	"NO_DOCTO" NUMBER(*,0), 
	"CONCEPTO" VARCHAR2(100), 
	"BENEFICIARIO" VARCHAR2(60), 
	"FECHA_ACTUALIZACION" DATE, 
	"NOM_EMPRESA" VARCHAR2(100), 
	"NO_CUENTA" NUMBER(*,0) DEFAULT (0), 
	"FOLIO_REF" NUMBER(*,0) DEFAULT (0), 
	"NOM_EMPRESA_REL" VARCHAR2(100), 
	"REFERENCIA" VARCHAR2(30) DEFAULT (NULL), 
	"DESCRIPCION" VARCHAR2(30)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXP_ENC_PAGOS_SOIN" ON "FECXC"."FECXP_ENC_PAGOS_SOIN" ("E_CODIGO", "SECUENCIA_PAGOS_SOIN") 
  ;
ALTER TABLE "FECXC"."FECXP_ENC_PAGOS_SOIN" ADD CONSTRAINT "PK_FECXP_ENC_PAGOS_SOIN" PRIMARY KEY ("E_CODIGO", "SECUENCIA_PAGOS_SOIN")
  USING INDEX "FECXC"."PK_FECXP_ENC_PAGOS_SOIN"  ENABLE;
ALTER TABLE "FECXC"."FECXP_ENC_PAGOS_SOIN" ADD CONSTRAINT "FK_FECXP_PAGOS_MONSOIN" FOREIGN KEY ("SECMONEDA")
	  REFERENCES "FECXC"."FECXC_MONEDAS" ("SECMONEDA") ENABLE;
