CREATE TABLE "FECXC"."FECXP_REP_PPTO_COM_VER_ERP" 
   (	"VERSION_ID" NUMBER(*,0), 
	"VERSION_FE" NUMBER(*,0), 
	"E_CODIGO" NUMBER(*,0), 
	"CLA_FE_ID" VARCHAR2(25), 
	"CODE_COMBINATION_ID" NUMBER NOT NULL ENABLE, 
	"ORACLE_SEGMENTO1" VARCHAR2(25), 
	"ORACLE_SEGMENTO2" VARCHAR2(25), 
	"ORACLE_SEGMENTO3" VARCHAR2(25), 
	"ORACLE_SEGMENTO4" VARCHAR2(25), 
	"ORACLE_SEGMENTO5" VARCHAR2(25), 
	"ORACLE_SEGMENTO6" VARCHAR2(25), 
	"ORACLE_SEGMENTO7" VARCHAR2(25), 
	"PERIODO" NUMBER(*,0), 
	"MES" NUMBER(*,0), 
	"MONEDA" VARCHAR2(3), 
	"IMPORTE_LINEA" NUMBER(20,4), 
	"ID_SESION" VARCHAR2(25)
   ) ;
