CREATE TABLE "FECXC"."FECXP_LAYOUT_NOSET_LOG" 
   (	"CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"ID_VERSION" NUMBER(*,0), 
	"NOMBRE_VERSION" VARCHAR2(400), 
	"COMENTARIOS" VARCHAR2(1000)
   ) ;
