CREATE TABLE "FECXC"."FECXC_COB_CANAL_DELDIA" 
   (	"E_CODIGO" NUMBER(*,0), 
	"SEGMENTO" NUMBER(*,0), 
	"CODMONEDA" VARCHAR2(3), 
	"MES" NUMBER(*,0), 
	"COBRANZA_DIA" NUMBER(20,2)
   ) ;
ALTER TABLE "FECXC"."FECXC_COB_CANAL_DELDIA" ADD CONSTRAINT "FK_FECXC_CO_CN_COBDIA_FECXC_EM" FOREIGN KEY ("E_CODIGO")
	  REFERENCES "FECXC"."FECXC_EMPRESAS" ("E_CODIGO") ENABLE;
