CREATE TABLE "FECXC"."FECXP_DET_PAGOS_PROCESADOS" 
   (	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"SECUENCIA_PAGOS_ERP" NUMBER(*,0) NOT NULL ENABLE, 
	"SECUENCIA_DET_PAGOS_ERP" NUMBER(*,0) NOT NULL ENABLE, 
	"NUMERO_DE_PARTIDA_ERP" NUMBER(*,0) NOT NULL ENABLE, 
	"SEC_DET_PAG_PROC" NUMBER(*,0) NOT NULL ENABLE, 
	"CODE_COMBINATION" NUMBER(*,0), 
	"IMPORTE_LINEA" NUMBER(20,4), 
	"ORACLE_SEGMENTO1" VARCHAR2(25), 
	"ORACLE_SEGMENTO2" VARCHAR2(25), 
	"ORACLE_SEGMENTO3" VARCHAR2(25), 
	"ORACLE_SEGMENTO4" VARCHAR2(25), 
	"ORACLE_SEGMENTO5" VARCHAR2(25), 
	"ORACLE_SEGMENTO6" VARCHAR2(25), 
	"ORACLE_SEGMENTO7" VARCHAR2(25)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXCP_DET_PAGOS_PROCESADOS" ON "FECXC"."FECXP_DET_PAGOS_PROCESADOS" ("E_CODIGO", "SECUENCIA_PAGOS_ERP", "SECUENCIA_DET_PAGOS_ERP", "NUMERO_DE_PARTIDA_ERP", "SEC_DET_PAG_PROC") 
  ;
ALTER TABLE "FECXC"."FECXP_DET_PAGOS_PROCESADOS" ADD CONSTRAINT "PK_FECXCP_DET_PAGOS_PROCESADOS" PRIMARY KEY ("E_CODIGO", "SECUENCIA_PAGOS_ERP", "SECUENCIA_DET_PAGOS_ERP", "NUMERO_DE_PARTIDA_ERP", "SEC_DET_PAG_PROC")
  USING INDEX "FECXC"."PK_FECXCP_DET_PAGOS_PROCESADOS"  ENABLE;
