CREATE TABLE "FECXC"."FECXP_APE_DET_TMP" 
   (	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"FOLIO_SET" VARCHAR2(150) NOT NULL ENABLE, 
	"SECUENCIA_PAGOS_ERP" NUMBER(*,0) NOT NULL ENABLE, 
	"SECUENCIA_CONT_DIN_APER_DET" NUMBER(*,0) NOT NULL ENABLE
   ) ;
