CREATE TABLE "FECXC"."FECXC_OPERACIONES_IT" 
   (	"ID_TIPO_OPERACION" NUMBER(*,0) NOT NULL ENABLE, 
	"TIPO_OPERACION" VARCHAR2(30)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXC_OPERACIONES_IT" ON "FECXC"."FECXC_OPERACIONES_IT" ("ID_TIPO_OPERACION") 
  ;
ALTER TABLE "FECXC"."FECXC_OPERACIONES_IT" ADD CONSTRAINT "PK_FECXC_OPERACIONES_IT" PRIMARY KEY ("ID_TIPO_OPERACION")
  USING INDEX "FECXC"."PK_FECXC_OPERACIONES_IT"  ENABLE;
ALTER TABLE "FECXC"."FECXC_OPERACIONES_IT" ADD CONSTRAINT "CKC_TIPO_OPERACION_FECXC_OP" CHECK (TIPO_OPERACION is null or ( TIPO_OPERACION in ('COBRANZA','OTROSINGRE','DNI','INTEREMPRESAS','SBUENCOBRO','EGRESO') )) ENABLE;
