CREATE TABLE "FECXC"."FECXP_FOL_AP_TMP" 
   (	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"FOLIO_SET" VARCHAR2(150) NOT NULL ENABLE, 
	"SECUENCIA_PAGOS_ERP" NUMBER(*,0) NOT NULL ENABLE, 
	"SECUENCIA_CONT_DIN_APER_DET" NUMBER(*,0) NOT NULL ENABLE, 
	"AP_INVOICE_ID" NUMBER(15,0), 
	"AP_INVOICE_AMOUNT" NUMBER
   ) ;
