CREATE TABLE "FECXC"."FECXC_EMP_X_SEGMENTO" 
   (	"ID_SEGMENTO" NUMBER(*,0) NOT NULL ENABLE, 
	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXC_EMP_X_SEGMENTO" ON "FECXC"."FECXC_EMP_X_SEGMENTO" ("ID_SEGMENTO", "E_CODIGO") 
  ;
ALTER TABLE "FECXC"."FECXC_EMP_X_SEGMENTO" ADD CONSTRAINT "PK_FECXC_EMP_X_SEGMENTO" PRIMARY KEY ("ID_SEGMENTO", "E_CODIGO")
  USING INDEX "FECXC"."PK_FECXC_EMP_X_SEGMENTO"  ENABLE;
ALTER TABLE "FECXC"."FECXC_EMP_X_SEGMENTO" ADD CONSTRAINT "FK_FECXC_EM_SEGMENTO__FECXC_SE" FOREIGN KEY ("ID_SEGMENTO")
	  REFERENCES "FECXC"."FECXC_SEGMENTOS_FLUJO" ("ID_SEGMENTO") ENABLE;
ALTER TABLE "FECXC"."FECXC_EMP_X_SEGMENTO" ADD CONSTRAINT "FK_FECXC_EM_EMP_X_SEG_FECXC_EM" FOREIGN KEY ("E_CODIGO")
	  REFERENCES "FECXC"."FECXC_EMPRESAS" ("E_CODIGO") ENABLE;
