CREATE TABLE "FECXC"."FECXP_DEL_CLASIF_REAL_SOIN" 
   (	"E_CODIGO" NUMBER(*,0), 
	"TIPO_OPERACION" NUMBER(*,0), 
	"ID_BANCO" NUMBER(*,0), 
	"ID_CHEQUERA" VARCHAR2(20), 
	"CTAM01" VARCHAR2(3), 
	"CTAM02" VARCHAR2(3), 
	"CTAM03" VARCHAR2(3), 
	"CTACR1" VARCHAR2(3), 
	"CTACR2" VARCHAR2(4)
   ) ;
