CREATE TABLE "FECXC"."FECXP_MONEDAS" 
   (	"MON_SYBASE" VARCHAR2(3) NOT NULL ENABLE, 
	"MON_ORACLE" VARCHAR2(3) NOT NULL ENABLE, 
	"DES_SYBASE" VARCHAR2(40) NOT NULL ENABLE, 
	"DES_ORACLE" VARCHAR2(80) NOT NULL ENABLE, 
	"MON_SET" VARCHAR2(3) NOT NULL ENABLE, 
	"TIPO_CAMBIO" NUMBER(20,11) DEFAULT 1 NOT NULL ENABLE, 
	"FEC_INGRESO" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"MES" NUMBER(*,0) NOT NULL ENABLE, 
	"PERIODO" NUMBER(*,0), 
	"DES_SET" VARCHAR2(20), 
	"ATRIBUTO1" VARCHAR2(255), 
	"FECHA_ACTUALIZACION" DATE
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXP_MONEDAS" ON "FECXC"."FECXP_MONEDAS" ("MON_SET", "MES", "PERIODO") 
  ;
ALTER TABLE "FECXC"."FECXP_MONEDAS" ADD CONSTRAINT "PK_FECXP_MONEDAS" PRIMARY KEY ("MON_SET", "MES", "PERIODO")
  USING INDEX "FECXC"."PK_FECXP_MONEDAS"  ENABLE;
