CREATE TABLE "FECXC"."FECXC_FMT_SEGMENTOS_PDF" 
   (	"ID_SESSION" VARCHAR2(100) NOT NULL ENABLE, 
	"NOMBRE_DEL_FORMATO" VARCHAR2(20) NOT NULL ENABLE, 
	"ID_SEGMENTO_PDF" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_TITULO_1" NUMBER, 
	"ID_TITULO_2" NUMBER, 
	"ID_TITULO_COMBINADO" NUMBER
   ) ;
