CREATE TABLE "FECXC"."FECXP_CTAS_CLASIF_PPTO_SOIN" 
   (	"CLA_FE_ID" VARCHAR2(25), 
	"E_CODIGO" NUMBER(*,0), 
	"CTAM01" VARCHAR2(3), 
	"CTAM02" VARCHAR2(3), 
	"CTAM03" VARCHAR2(3), 
	"TIPO" VARCHAR2(1), 
	"DIVISION" NUMBER(*,0), 
	"RUBRO" NUMBER(*,0), 
	"CTACR1" VARCHAR2(3), 
	"CTACR2" VARCHAR2(4)
   ) ;
