CREATE TABLE "FECXC"."FECXP_POLITICAS_ERP" 
   (	"CLA_FE_ID" VARCHAR2(25) NOT NULL ENABLE, 
	"POLITICA_ERP_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"PRIORIDAD" NUMBER(*,0), 
	"ORACLE_SEGMENTO1_INI" VARCHAR2(25), 
	"ORACLE_SEGMENTO1_FIN" VARCHAR2(25), 
	"ORACLE_SEGMENTO2_INI" VARCHAR2(25), 
	"ORACLE_SEGMENTO2_FIN" VARCHAR2(25), 
	"ORACLE_SEGMENTO3_INI" VARCHAR2(25), 
	"ORACLE_SEGMENTO3_FIN" VARCHAR2(25), 
	"ORACLE_SEGMENTO4_INI" VARCHAR2(25), 
	"ORACLE_SEGMENTO4_FIN" VARCHAR2(25), 
	"ORACLE_SEGMENTO5_INI" VARCHAR2(25), 
	"ORACLE_SEGMENTO5_FIN" VARCHAR2(25), 
	"ORACLE_SEGMENTO6_INI" VARCHAR2(25), 
	"ORACLE_SEGMENTO6_FIN" VARCHAR2(25), 
	"ORACLE_SEGMENTO7_INI" VARCHAR2(25), 
	"ORACLE_SEGMENTO7_FIN" VARCHAR2(25), 
	"ACTIVA_REGLA" NUMBER(*,0) DEFAULT 1 NOT NULL ENABLE, 
	"TIPO_OPERACION_INI" NUMBER(*,0), 
	"TIPO_OPERACION_FIN" NUMBER(*,0), 
	"ID_TIPO_MOVTO" VARCHAR2(1), 
	"ID_BANCO_INI" NUMBER(*,0), 
	"ID_BANCO_FIN" NUMBER(*,0), 
	"ID_CHEQUERA_INI" VARCHAR2(20), 
	"ID_CHEQUERA_FIN" VARCHAR2(20), 
	"VERSION_ID" NUMBER(*,0) DEFAULT (0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXP_POLITICAS_ERP" ON "FECXC"."FECXP_POLITICAS_ERP" ("CLA_FE_ID", "POLITICA_ERP_ID") 
  ;
ALTER TABLE "FECXC"."FECXP_POLITICAS_ERP" ADD CONSTRAINT "PK_FECXP_POLITICAS_ERP" PRIMARY KEY ("CLA_FE_ID", "POLITICA_ERP_ID")
  USING INDEX "FECXC"."PK_FECXP_POLITICAS_ERP"  ENABLE;
ALTER TABLE "FECXC"."FECXP_POLITICAS_ERP" ADD CONSTRAINT "FK_FECXP_POLITICAS_ERP" FOREIGN KEY ("CLA_FE_ID")
	  REFERENCES "FECXC"."FECXP_CLASIFICACION_FE" ("CLA_FE_ID") ENABLE;
