CREATE TABLE "FECXC"."FECXP_B_ENC_CLASIFICACION_FE" 
   (	"VERSION_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"USUARIO_ID" VARCHAR2(30), 
	"FECHA_CREACION" DATE
   ) ;
  CREATE UNIQUE INDEX "FECXC"."FECXP_B_ENC_CLASIFICACION_FE00" ON "FECXC"."FECXP_B_ENC_CLASIFICACION_FE" ("VERSION_ID") 
  ;
ALTER TABLE "FECXC"."FECXP_B_ENC_CLASIFICACION_FE" ADD CONSTRAINT "PKFECXP_B_ENC_CLASIFICACION_FE" PRIMARY KEY ("VERSION_ID")
  USING INDEX "FECXC"."FECXP_B_ENC_CLASIFICACION_FE00"  ENABLE;
