CREATE TABLE "FECXC"."FECXC_VALORES_NIVXEMP" 
   (	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"COD_NIVEL" NUMBER(*,0) NOT NULL ENABLE, 
	"COD_SEC_TIPCAT" NUMBER(*,0) NOT NULL ENABLE, 
	"COD_SEC_LIN" NUMBER(*,0) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXC_VALORES_NIVXEMP" ON "FECXC"."FECXC_VALORES_NIVXEMP" ("COD_SEC_TIPCAT", "E_CODIGO", "COD_NIVEL", "COD_SEC_LIN") 
  ;
ALTER TABLE "FECXC"."FECXC_VALORES_NIVXEMP" ADD CONSTRAINT "PK_FECXC_VALORES_NIVXEMP" PRIMARY KEY ("COD_SEC_TIPCAT", "E_CODIGO", "COD_NIVEL", "COD_SEC_LIN")
  USING INDEX "FECXC"."PK_FECXC_VALORES_NIVXEMP"  ENABLE;
ALTER TABLE "FECXC"."FECXC_VALORES_NIVXEMP" ADD CONSTRAINT "FK_FECXC_VA_VALORES_C_FECXC_DE" FOREIGN KEY ("COD_SEC_TIPCAT", "COD_SEC_LIN")
	  REFERENCES "FECXC"."FECXC_DET_CATALOGOS" ("COD_SEC_TIPCAT", "COD_SEC_LIN") ENABLE;
ALTER TABLE "FECXC"."FECXC_VALORES_NIVXEMP" ADD CONSTRAINT "FK_FECXC_VA_VALORES_N_FECXC_CA" FOREIGN KEY ("E_CODIGO", "COD_NIVEL")
	  REFERENCES "FECXC"."FECXC_CAT_XEMPRESA" ("E_CODIGO", "COD_NIVEL") ENABLE;
