CREATE TABLE "FECXC"."FECXC_DET_CATALOGOS" 
   (	"COD_SEC_TIPCAT" NUMBER(*,0) NOT NULL ENABLE, 
	"COD_SEC_LIN" NUMBER(*,0) NOT NULL ENABLE, 
	"TIPO_CAT" VARCHAR2(10) NOT NULL ENABLE, 
	"COD_VALOR" VARCHAR2(10) NOT NULL ENABLE, 
	"DESC_VALOR" VARCHAR2(100) NOT NULL ENABLE, 
	"REP_EDIT_EXT" NUMBER(2,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXC_DET_CATALOGOS" ON "FECXC"."FECXC_DET_CATALOGOS" ("COD_SEC_TIPCAT", "COD_SEC_LIN") 
  ;
ALTER TABLE "FECXC"."FECXC_DET_CATALOGOS" ADD CONSTRAINT "PK_FECXC_DET_CATALOGOS" PRIMARY KEY ("COD_SEC_TIPCAT", "COD_SEC_LIN")
  USING INDEX "FECXC"."PK_FECXC_DET_CATALOGOS"  ENABLE;
ALTER TABLE "FECXC"."FECXC_DET_CATALOGOS" ADD CONSTRAINT "FK_FECXC_DE_CAT_ENC_D_FECXC_EN" FOREIGN KEY ("COD_SEC_TIPCAT")
	  REFERENCES "FECXC"."FECXC_ENC_CATALOGOS" ("COD_SEC_TIPCAT") ENABLE;
