CREATE TABLE "FECXC"."FECXP_COD_SUB_BITACORA" 
   (	"SECUENCIA_COD_SUB_BIT" NUMBER(*,0), 
	"INS_NO_EMPRESA" NUMBER(*,0), 
	"INS_ID_CODIGO" VARCHAR2(2), 
	"INS_ID_SUBCODIGO" VARCHAR2(3), 
	"INS_DESC_SUBCODIGO" VARCHAR2(40), 
	"DEL_NO_EMPRESA" NUMBER(*,0), 
	"DEL_ID_CODIGO" VARCHAR2(2), 
	"DEL_ID_SUBCODIGO" VARCHAR2(3), 
	"DEL_DESC_SUBCODIGO" VARCHAR2(40), 
	"ACCION" VARCHAR2(40), 
	"USUARIO" VARCHAR2(40), 
	"FECHA_SINCRONIZACION" DATE DEFAULT (SYSDATE), 
	"FECHA_MODIFICACION" DATE DEFAULT (TO_DATE ('19000101', 'YYYYMMDD')), 
	"SINCRONIZADO_FE" VARCHAR2(2) DEFAULT ('NO'), 
	"COMENTARIO_SINCRONIZADO_FE" VARCHAR2(255) DEFAULT ('<SIN COMENTARIO>')
   ) ;
