CREATE TABLE "FECXC"."FECXC_COBRANZA_DELDIA" 
   (	"E_CODIGO" NUMBER(*,0), 
	"SEGMENTO" NUMBER(*,0), 
	"CODMONEDA" VARCHAR2(3), 
	"COBRANZA_DIA" NUMBER(20,4)
   ) ;
ALTER TABLE "FECXC"."FECXC_COBRANZA_DELDIA" ADD CONSTRAINT "FK_FECXC_CO_TV_COBDIA_FECXC_EM" FOREIGN KEY ("E_CODIGO")
	  REFERENCES "FECXC"."FECXC_EMPRESAS" ("E_CODIGO") ENABLE;
