CREATE TABLE "FECXC"."FECXP_B_EJECUCION_PROCESO" 
   (	"ID_PROCESO" NUMBER(*,0) NOT NULL ENABLE, 
	"PROCESO_NOMBRE" VARCHAR2(100) NOT NULL ENABLE, 
	"CATALOGO_NOMBRE" VARCHAR2(100) NOT NULL ENABLE, 
	"VERSION_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"ACCION" VARCHAR2(25) NOT NULL ENABLE, 
	"USUARIO_ID" VARCHAR2(30) NOT NULL ENABLE, 
	"FECHA_CREACION" DATE NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PKFECXP_BIT_EJECUCION_PROCESOS" ON "FECXC"."FECXP_B_EJECUCION_PROCESO" ("ID_PROCESO", "PROCESO_NOMBRE", "CATALOGO_NOMBRE", "VERSION_ID", "ACCION") 
  ;
ALTER TABLE "FECXC"."FECXP_B_EJECUCION_PROCESO" ADD CONSTRAINT "PKFECXP_BIT_EJECUCION_PROCESOS" PRIMARY KEY ("ID_PROCESO", "PROCESO_NOMBRE", "CATALOGO_NOMBRE", "VERSION_ID", "ACCION")
  USING INDEX "FECXC"."PKFECXP_BIT_EJECUCION_PROCESOS"  ENABLE;
