CREATE TABLE "FECXC"."FECXP_SALDOS_FINALES_SET" 
   (	"E_CODIGO" NUMBER(*,0), 
	"IMPORTE" NUMBER(20,4), 
	"MONEDA" VARCHAR2(3), 
	"MES" NUMBER(*,0), 
	"PERIODO" NUMBER(*,0) DEFAULT (TO_NUMBER (TO_CHAR (SYSDATE, 'YYYY')))
   ) ;
