CREATE TABLE "FECXC"."FECXC_CIFRAS_CONTROL" 
   (	"MES" NUMBER, 
	"PERIODO" NUMBER, 
	"SEGMENTO" VARCHAR2(25), 
	"IMPORTE_SEG" NUMBER, 
	"CONCEPTO" VARCHAR2(25), 
	"IMPORTE_CON" NUMBER, 
	"DIVISION" VARCHAR2(25), 
	"IMPORTE_DIV" NUMBER, 
	"CANAL" VARCHAR2(25), 
	"IMPORTE_CAN" NUMBER, 
	"REGION" VARCHAR2(25), 
	"IMPORTE_REG" NUMBER
   ) ;
