CREATE TABLE "FECXC"."FECXP_MONEDAS_NO_SET" 
   (	"MON_SYBASE" VARCHAR2(3), 
	"MON_ORACLE" VARCHAR2(3), 
	"DES_SYBASE" VARCHAR2(40), 
	"DES_ORACLE" VARCHAR2(80), 
	"MON_SET" VARCHAR2(3), 
	"TIPO_CAMBIO" NUMBER(20,11) DEFAULT 1 NOT NULL ENABLE, 
	"FEC_INGRESO" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"MES" NUMBER(*,0) NOT NULL ENABLE, 
	"PERIODO" NUMBER(*,0), 
	"DES_SET" VARCHAR2(20), 
	"ATRIBUTO1" VARCHAR2(255), 
	"FECHA_ACTUALIZACION" DATE, 
	"MON_NO_SET" VARCHAR2(5), 
	"DES_NO_SET" VARCHAR2(255), 
	"TIPO_EMPRESA" VARCHAR2(10)
   ) ;
