CREATE TABLE "FECXC"."FECXC_FMT_TIPO_PDF" 
   (	"ID_SESSION" VARCHAR2(100) NOT NULL ENABLE, 
	"NOMBRE_DEL_FORMATO" VARCHAR2(20) NOT NULL ENABLE, 
	"TIPO_DE_FORMATO" VARCHAR2(30) NOT NULL ENABLE
   ) ;
