CREATE TABLE "FECXC"."FECXC_ENC_CATALOGOS" 
   (	"COD_SEC_TIPCAT" NUMBER(*,0) NOT NULL ENABLE, 
	"TIPO_CAT" VARCHAR2(10) NOT NULL ENABLE, 
	"TIPO_DES" VARCHAR2(15) NOT NULL ENABLE, 
	"ES_NIVEL" CHAR(2)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXC_ENC_CATALOGOS" ON "FECXC"."FECXC_ENC_CATALOGOS" ("COD_SEC_TIPCAT") 
  ;
ALTER TABLE "FECXC"."FECXC_ENC_CATALOGOS" ADD CONSTRAINT "PK_FECXC_ENC_CATALOGOS" PRIMARY KEY ("COD_SEC_TIPCAT")
  USING INDEX "FECXC"."PK_FECXC_ENC_CATALOGOS"  ENABLE;
ALTER TABLE "FECXC"."FECXC_ENC_CATALOGOS" ADD CONSTRAINT "CKC_ES_NIVEL_FECXC_EN" CHECK (ES_NIVEL is null or ( ES_NIVEL in ('SI','NO') )) ENABLE;
