CREATE TABLE "FECXC"."FECXC_ROLES" 
   (	"ID_ROL" NUMBER(*,0) NOT NULL ENABLE, 
	"DESC_ROL" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXC_ROLES" ON "FECXC"."FECXC_ROLES" ("ID_ROL") 
  ;
ALTER TABLE "FECXC"."FECXC_ROLES" ADD CONSTRAINT "PK_FECXC_ROLES" PRIMARY KEY ("ID_ROL")
  USING INDEX "FECXC"."PK_FECXC_ROLES"  ENABLE;
