CREATE TABLE "FECXC"."FECXP_CAT_CUENTAS_SOIN" 
   (	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"CTAM01" VARCHAR2(3), 
	"CTAM02" VARCHAR2(3), 
	"CTAM03" VARCHAR2(3), 
	"CG13DI" NUMBER(*,0), 
	"CG13GR" NUMBER(*,0), 
	"CG13RU" NUMBER(*,0), 
	"CTATIP" VARCHAR2(1)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_FECXP_CAT_CUENTAS_SOIN" ON "FECXC"."FECXP_CAT_CUENTAS_SOIN" ("E_CODIGO", "CTAM01", "CTAM02", "CTAM03") 
  ;
ALTER TABLE "FECXC"."FECXP_CAT_CUENTAS_SOIN" ADD CONSTRAINT "PK_FECXP_CAT_CUENTAS_SOIN" PRIMARY KEY ("E_CODIGO", "CTAM01", "CTAM02", "CTAM03")
  USING INDEX "FECXC"."PK_FECXP_CAT_CUENTAS_SOIN"  ENABLE;
