CREATE TABLE "FECXC"."XXCHK_PARAMETROS_GENERALES" 
   (	"ANTIGUEDAD" NUMBER NOT NULL ENABLE, 
	"RECHAZOS_MAXIMOS" NUMBER NOT NULL ENABLE, 
	"USUARIO_AUTORIZA" VARCHAR2(30) NOT NULL ENABLE, 
	"ESTADO_INICIAL_CHK" NUMBER(*,0) NOT NULL ENABLE, 
	"EDO_ENTREGADO_CLI" NUMBER(*,0) NOT NULL ENABLE, 
	"E_CODIGO" VARCHAR2(10), 
	"E_CODIGO_D" VARCHAR2(75)
   ) ;
