CREATE TABLE "FECXC"."XXCHK_ASOC_FACT_CHEQ" 
   (	"ID_SEC_CHEQUE" NUMBER(*,0) NOT NULL ENABLE, 
	"CUSTOMER_TRX_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"E_CODIGO" NUMBER(*,0), 
	"ID_ESTADO_CHEQUE" NUMBER(*,0), 
	"MONTO" NUMBER(20,2), 
	"MONEDA" VARCHAR2(3), 
	"TIPO_CAMBIO" NUMBER(20,4), 
	"ORG_ID" NUMBER(*,0), 
	"TRX_NUMBER" VARCHAR2(20), 
	"NO_CHEQUE" NUMBER(*,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_XXCHK_ASOC_FACT_CHEQ" ON "FECXC"."XXCHK_ASOC_FACT_CHEQ" ("ID_SEC_CHEQUE", "CUSTOMER_TRX_ID") 
  ;
ALTER TABLE "FECXC"."XXCHK_ASOC_FACT_CHEQ" ADD CONSTRAINT "PK_XXCHK_ASOC_FACT_CHEQ" PRIMARY KEY ("ID_SEC_CHEQUE", "CUSTOMER_TRX_ID")
  USING INDEX "FECXC"."PK_XXCHK_ASOC_FACT_CHEQ"  ENABLE;
ALTER TABLE "FECXC"."XXCHK_ASOC_FACT_CHEQ" ADD CONSTRAINT "FK_XXCHK_AS_FK_CHEORA_XXCHK_CA" FOREIGN KEY ("ID_ESTADO_CHEQUE")
	  REFERENCES "FECXC"."XXCHK_CAT_EDOS" ("ID_ESTADO_CHEQUE") ENABLE;
ALTER TABLE "FECXC"."XXCHK_ASOC_FACT_CHEQ" ADD CONSTRAINT "FK_XXCHK_AS_FK_CHK_FA_FECXC_EM" FOREIGN KEY ("E_CODIGO")
	  REFERENCES "FECXC"."FECXC_EMPRESAS" ("E_CODIGO") ENABLE;
ALTER TABLE "FECXC"."XXCHK_ASOC_FACT_CHEQ" ADD CONSTRAINT "FK_XXCHK_AS_XXCHK_CHE_XXCHK_CA" FOREIGN KEY ("ID_SEC_CHEQUE")
	  REFERENCES "FECXC"."XXCHK_CAPTURA_CHEQUES" ("ID_SEC_CHEQUE") ENABLE;
