CREATE TABLE "FECXC"."XXCHK_ROLES" 
   (	"ID_ROL" NUMBER(*,0) NOT NULL ENABLE, 
	"DESC_ROL" VARCHAR2(100)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_XXCHK_ROLES" ON "FECXC"."XXCHK_ROLES" ("ID_ROL") 
  ;
ALTER TABLE "FECXC"."XXCHK_ROLES" ADD CONSTRAINT "PK_XXCHK_ROLES" PRIMARY KEY ("ID_ROL")
  USING INDEX "FECXC"."PK_XXCHK_ROLES"  ENABLE;
