CREATE TABLE "FECXC"."XXCHK_ROLES_X_USUARIO" 
   (	"ID_ROL" NUMBER(*,0) NOT NULL ENABLE, 
	"CODUSUARIO" VARCHAR2(40) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_XXCHK_ROLES_X_USUARIO" ON "FECXC"."XXCHK_ROLES_X_USUARIO" ("ID_ROL", "CODUSUARIO") 
  ;
ALTER TABLE "FECXC"."XXCHK_ROLES_X_USUARIO" ADD CONSTRAINT "PK_XXCHK_ROLES_X_USUARIO" PRIMARY KEY ("ID_ROL", "CODUSUARIO")
  USING INDEX "FECXC"."PK_XXCHK_ROLES_X_USUARIO"  ENABLE;
ALTER TABLE "FECXC"."XXCHK_ROLES_X_USUARIO" ADD CONSTRAINT "FK_XXCHK_RO_XXCHK_USU_XXCHK_RO" FOREIGN KEY ("ID_ROL")
	  REFERENCES "FECXC"."XXCHK_ROLES" ("ID_ROL") ENABLE;
