CREATE TABLE "FECXC"."XXCHK_ASOC_FACT_CHEQ_SYB" 
   (	"ID_SEC_CHEQUE" NUMBER(*,0) NOT NULL ENABLE, 
	"FAM01COD" VARCHAR2(4) NOT NULL ENABLE, 
	"FAX01NTR" NUMBER(*,0) NOT NULL ENABLE, 
	"FACDOC" VARCHAR2(15) NOT NULL ENABLE, 
	"ID_ESTADO_CHEQUE" NUMBER(*,0), 
	"E_CODIGO" NUMBER(*,0), 
	"CLINOM" VARCHAR2(50), 
	"CLICOD" VARCHAR2(15), 
	"MONTO" NUMBER(20,2), 
	"MONEDA" VARCHAR2(3), 
	"TIPO_CAMBIO" NUMBER(20,4), 
	"DEPREF" VARCHAR2(22) NOT NULL ENABLE, 
	"EMPRESA_SY" VARCHAR2(3) NOT NULL ENABLE, 
	"NO_CHEQUE" NUMBER(*,0), 
	"TTRCOD" VARCHAR2(2)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_XXCHK_ASOC_FACT_CHEQ_SYB" ON "FECXC"."XXCHK_ASOC_FACT_CHEQ_SYB" ("ID_SEC_CHEQUE", "FAM01COD", "FAX01NTR", "FACDOC") 
  ;
ALTER TABLE "FECXC"."XXCHK_ASOC_FACT_CHEQ_SYB" ADD CONSTRAINT "PK_XXCHK_ASOC_FACT_CHEQ_SYB" PRIMARY KEY ("ID_SEC_CHEQUE", "FAM01COD", "FAX01NTR", "FACDOC")
  USING INDEX "FECXC"."PK_XXCHK_ASOC_FACT_CHEQ_SYB"  ENABLE;
ALTER TABLE "FECXC"."XXCHK_ASOC_FACT_CHEQ_SYB" ADD CONSTRAINT "FK_XXCHK_AS_FK_CHEKSY_XXCHK_CA" FOREIGN KEY ("ID_ESTADO_CHEQUE")
	  REFERENCES "FECXC"."XXCHK_CAT_EDOS" ("ID_ESTADO_CHEQUE") ENABLE;
ALTER TABLE "FECXC"."XXCHK_ASOC_FACT_CHEQ_SYB" ADD CONSTRAINT "FK_XXCHK_AS_FK_CHKSYB_FECXC_EM" FOREIGN KEY ("E_CODIGO")
	  REFERENCES "FECXC"."FECXC_EMPRESAS" ("E_CODIGO") ENABLE;
ALTER TABLE "FECXC"."XXCHK_ASOC_FACT_CHEQ_SYB" ADD CONSTRAINT "FK_XXCHK_AS_XXCHK_CHQ_XXCHK_CA" FOREIGN KEY ("ID_SEC_CHEQUE")
	  REFERENCES "FECXC"."XXCHK_CAPTURA_CHEQUES" ("ID_SEC_CHEQUE") ENABLE;
