CREATE TABLE "FECXC"."XXCHK_CHEQ_ALL_HIST" 
   (	"ID_ESTADO_CHEQUE" NUMBER(*,0), 
	"ID_SEC_CHEQUE" NUMBER(*,0), 
	"E_CODIGO" NUMBER(*,0), 
	"NO_FOLIO_DET" NUMBER(*,0), 
	"ID_STATUS_MOV" VARCHAR2(2), 
	"DATE_CREATED" DATE DEFAULT Sysdate NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(30) NOT NULL ENABLE, 
	"TIPO_CHEQ" VARCHAR2(15) NOT NULL ENABLE, 
	"REFERENCIA_CLIENTE" VARCHAR2(50) NOT NULL ENABLE, 
	"ID_TIPO_OPERACION_SET" NUMBER(*,0), 
	"NO_CHEQUE" NUMBER(*,0), 
	"PROCESADO" NUMBER(*,0), 
	"GROUP_ID" NUMBER
   ) ;
ALTER TABLE "FECXC"."XXCHK_CHEQ_ALL_HIST" ADD CONSTRAINT "FK_XXCHK_CH_FK_HISTCH_XXCHK_CH" FOREIGN KEY ("E_CODIGO", "NO_FOLIO_DET", "ID_STATUS_MOV")
	  REFERENCES "FECXC"."XXCHK_CHEQUES_ALL" ("E_CODIGO", "NO_FOLIO_DET", "ID_STATUS_MOV") ENABLE;
ALTER TABLE "FECXC"."XXCHK_CHEQ_ALL_HIST" ADD CONSTRAINT "FK_XXCHK_HISTCHK_ESTACHK" FOREIGN KEY ("ID_ESTADO_CHEQUE")
	  REFERENCES "FECXC"."XXCHK_CAT_EDOS" ("ID_ESTADO_CHEQUE") ENABLE;
ALTER TABLE "FECXC"."XXCHK_CHEQ_ALL_HIST" ADD CONSTRAINT "FK_XXCHK_HISTCHK_CHK" FOREIGN KEY ("ID_SEC_CHEQUE")
	  REFERENCES "FECXC"."XXCHK_CAPTURA_CHEQUES" ("ID_SEC_CHEQUE") ENABLE;
