CREATE TABLE "FECXC"."XXCHK_GL_INTERFACE_CHK" 
   (	"ID_ESTADO_CHEQUE" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_SEC_CHEQUE" NUMBER(*,0) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(50) NOT NULL ENABLE, 
	"SET_OF_BOOKS_ID" NUMBER NOT NULL ENABLE, 
	"ACCOUNTING_DATE" DATE NOT NULL ENABLE, 
	"CURRENCY_CODE" VARCHAR2(3) NOT NULL ENABLE, 
	"CURRENCY_CONVERSION_DATE" DATE, 
	"USER_CURRENCY_CONVERSION_TYPE" VARCHAR2(30), 
	"CURRENCY_CONVERSION_RATE" NUMBER, 
	"ACTUAL_FLAG" VARCHAR2(1) NOT NULL ENABLE, 
	"USER_JE_CATEGORY_NAME" VARCHAR2(25) NOT NULL ENABLE, 
	"USER_JE_SOURCE_NAME" VARCHAR2(25) NOT NULL ENABLE, 
	"SEGMENT1" VARCHAR2(25), 
	"SEGMENT2" VARCHAR2(25), 
	"SEGMENT3" VARCHAR2(25), 
	"SEGMENT4" VARCHAR2(25), 
	"SEGMENT5" VARCHAR2(25), 
	"SEGMENT6" VARCHAR2(25), 
	"SEGMENT7" VARCHAR2(25), 
	"ENTERED_DR" NUMBER, 
	"ENTERED_CR" NUMBER, 
	"ACCOUNTED_DR" NUMBER, 
	"ACCOUNTED_CR" NUMBER, 
	"REFERENCE1" VARCHAR2(100), 
	"PERIOD_NAME" VARCHAR2(25), 
	"CODE_COMBINATION_ID" NUMBER, 
	"GROUP_ID" NUMBER NOT NULL ENABLE, 
	"PROCESADO" NUMBER(*,0), 
	"DATE_CREATED" DATE DEFAULT Sysdate NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(30) NOT NULL ENABLE
   ) ;
ALTER TABLE "FECXC"."XXCHK_GL_INTERFACE_CHK" ADD CONSTRAINT "FK_XXCHK_GL_FK_XXGL_E_XXCHK_CA" FOREIGN KEY ("ID_ESTADO_CHEQUE")
	  REFERENCES "FECXC"."XXCHK_CAT_EDOS" ("ID_ESTADO_CHEQUE") ENABLE;
ALTER TABLE "FECXC"."XXCHK_GL_INTERFACE_CHK" ADD CONSTRAINT "FK_XXCHK_GL_RK_XXGL_C_XXCHK_CA" FOREIGN KEY ("ID_SEC_CHEQUE")
	  REFERENCES "FECXC"."XXCHK_CAPTURA_CHEQUES" ("ID_SEC_CHEQUE") ENABLE;
