CREATE TABLE "FECXC"."XXCHK_CAPTURA_CHEQUES" 
   (	"ID_SEC_CHEQUE" NUMBER(*,0) NOT NULL ENABLE, 
	"E_CODIGO" NUMBER(*,0), 
	"ID_BANCO" NUMBER(*,0), 
	"ID_ESTADO_CHEQUE" NUMBER(*,0), 
	"NO_CHEQUE" NUMBER(*,0) NOT NULL ENABLE, 
	"REFERENCIA_CLIENTE" VARCHAR2(50), 
	"ID_CLIENTE" VARCHAR2(50) NOT NULL ENABLE, 
	"CHEQUE_REPUESTO" NUMBER(*,0), 
	"NO_CHEQUE_REEMPLAZO" NUMBER(*,0), 
	"FECHA_EMISION" DATE NOT NULL ENABLE, 
	"FECHA_COBRO" DATE, 
	"DATE_CREATED" DATE DEFAULT Sysdate NOT NULL ENABLE, 
	"LAST_MODIFIED_DATE" DATE DEFAULT Sysdate, 
	"CREATED_BY" VARCHAR2(30) NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(30), 
	"IMPORTE" NUMBER(20,2) NOT NULL ENABLE, 
	"MONEDA" VARCHAR2(3) NOT NULL ENABLE, 
	"ENTREGADO_POR" VARCHAR2(30) NOT NULL ENABLE, 
	"EXPIDE" VARCHAR2(50) NOT NULL ENABLE, 
	"IMAGEN" VARCHAR2(120) NOT NULL ENABLE, 
	"VENCIDO" NUMBER(*,0), 
	"DESC_CLIENTE" VARCHAR2(80), 
	"PROCESADO" NUMBER(*,0), 
	"ID_BANCO_REP" NUMBER(*,0), 
	"FOLIO" VARCHAR2(30), 
	"EN_RECIBO_AR" VARCHAR2(1)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_XXCHK_CAPTURA_CHEQUES" ON "FECXC"."XXCHK_CAPTURA_CHEQUES" ("ID_SEC_CHEQUE") 
  ;
ALTER TABLE "FECXC"."XXCHK_CAPTURA_CHEQUES" ADD CONSTRAINT "PK_XXCHK_CAPTURA_CHEQUES" PRIMARY KEY ("ID_SEC_CHEQUE")
  USING INDEX "FECXC"."PK_XXCHK_CAPTURA_CHEQUES"  ENABLE;
ALTER TABLE "FECXC"."XXCHK_CAPTURA_CHEQUES" ADD CONSTRAINT "FK_XXCHK_CA_FK_CHEQUE_XXCHK_CA" FOREIGN KEY ("ID_ESTADO_CHEQUE")
	  REFERENCES "FECXC"."XXCHK_CAT_EDOS" ("ID_ESTADO_CHEQUE") ENABLE;
ALTER TABLE "FECXC"."XXCHK_CAPTURA_CHEQUES" ADD CONSTRAINT "FK_XXCHK_CA_XXCHK_BAN_XXCHK_CA" FOREIGN KEY ("ID_BANCO")
	  REFERENCES "FECXC"."XXCHK_CATALOGO_BANCOS" ("ID_BANCO") ENABLE;
ALTER TABLE "FECXC"."XXCHK_CAPTURA_CHEQUES" ADD CONSTRAINT "FK_XXCHK_chek_toempre" FOREIGN KEY ("E_CODIGO")
	  REFERENCES "FECXC"."FECXC_EMPRESAS" ("E_CODIGO") ENABLE;
