CREATE TABLE "FECXC"."XXCHK_CAT_EDO_CHEQUE" 
   (	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_ESTADO_CHEQUE" NUMBER(*,0) NOT NULL ENABLE, 
	"C_CARGO_ERP" NUMBER(*,0), 
	"C_ABONO_ERP" NUMBER(*,0), 
	"C_CARGO_SOIN" VARCHAR2(4), 
	"SC_CARGO_SOIN" VARCHAR2(4), 
	"SSC_CARGO_SOIN" VARCHAR2(4), 
	"CR_CARGO_SOIN" VARCHAR2(3), 
	"CR_CARGO_SOIN2" VARCHAR2(4), 
	"C_ABONO_SOIN" VARCHAR2(4), 
	"SC_ABONO_SOIN" VARCHAR2(4), 
	"SSC_ABONO_SOIN" VARCHAR2(4), 
	"CR_ABONO_SOIN" VARCHAR2(3), 
	"CR_ABONO_SOIN2" VARCHAR2(4), 
	"CONTABILIZA" NUMBER(1,0), 
	"ENVIA_CORREO" NUMBER(1,0)
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_XXCHK_CAT_EDO_CHEQUE" ON "FECXC"."XXCHK_CAT_EDO_CHEQUE" ("E_CODIGO", "ID_ESTADO_CHEQUE") 
  ;
ALTER TABLE "FECXC"."XXCHK_CAT_EDO_CHEQUE" ADD CONSTRAINT "PK_XXCHK_CAT_EDO_CHEQUE" PRIMARY KEY ("E_CODIGO", "ID_ESTADO_CHEQUE")
  USING INDEX "FECXC"."PK_XXCHK_CAT_EDO_CHEQUE"  ENABLE;
ALTER TABLE "FECXC"."XXCHK_CAT_EDO_CHEQUE" ADD CONSTRAINT "FK_XXCHK_CA_FK_CONTAB_XXCHK_CA" FOREIGN KEY ("ID_ESTADO_CHEQUE")
	  REFERENCES "FECXC"."XXCHK_CAT_EDOS" ("ID_ESTADO_CHEQUE") ENABLE;
ALTER TABLE "FECXC"."XXCHK_CAT_EDO_CHEQUE" ADD CONSTRAINT "FK_XXCHK_stachek_toemp" FOREIGN KEY ("E_CODIGO")
	  REFERENCES "FECXC"."FECXC_EMPRESAS" ("E_CODIGO") ENABLE;
