CREATE TABLE "FECXC"."XXCHK_CAT_EDOS" 
   (	"ID_ESTADO_CHEQUE" NUMBER(*,0) NOT NULL ENABLE, 
	"DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	"TIPO_OPERACION" VARCHAR2(20) DEFAULT 'ENFIRME', 
	"DATE_CREATED" DATE DEFAULT Sysdate
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_XXCHK_CAT_EDOS" ON "FECXC"."XXCHK_CAT_EDOS" ("ID_ESTADO_CHEQUE") 
  ;
ALTER TABLE "FECXC"."XXCHK_CAT_EDOS" ADD CONSTRAINT "CKC_TIPO_OPERACION_XXCHK_CA" CHECK (TIPO_OPERACION is null or ( TIPO_OPERACION in ('ENFIRME','SBC','RECHAZADO') )) ENABLE;
ALTER TABLE "FECXC"."XXCHK_CAT_EDOS" ADD CONSTRAINT "PK_XXCHK_CAT_EDOS" PRIMARY KEY ("ID_ESTADO_CHEQUE")
  USING INDEX "FECXC"."PK_XXCHK_CAT_EDOS"  ENABLE;
