CREATE TABLE "FECXC"."XXCHK_ROLES_XEMPRESA" 
   (	"ID_ROL" NUMBER(*,0) NOT NULL ENABLE, 
	"E_CODIGO" NUMBER(*,0) NOT NULL ENABLE
   ) ;
  CREATE UNIQUE INDEX "FECXC"."PK_XXCHK_ROLES_XEMPRESA" ON "FECXC"."XXCHK_ROLES_XEMPRESA" ("ID_ROL", "E_CODIGO") 
  ;
ALTER TABLE "FECXC"."XXCHK_ROLES_XEMPRESA" ADD CONSTRAINT "PK_XXCHK_ROLES_XEMPRESA" PRIMARY KEY ("ID_ROL", "E_CODIGO")
  USING INDEX "FECXC"."PK_XXCHK_ROLES_XEMPRESA"  ENABLE;
ALTER TABLE "FECXC"."XXCHK_ROLES_XEMPRESA" ADD CONSTRAINT "FK_XXCHK_RO_XXCHK_EMP_FECXC_EM" FOREIGN KEY ("E_CODIGO")
	  REFERENCES "FECXC"."FECXC_EMPRESAS" ("E_CODIGO") ENABLE;
ALTER TABLE "FECXC"."XXCHK_ROLES_XEMPRESA" ADD CONSTRAINT "FK_XXCHK_rol_seg" FOREIGN KEY ("ID_ROL")
	  REFERENCES "FECXC"."XXCHK_ROLES" ("ID_ROL") ENABLE;
