CREATE OR REPLACE NONEDITIONABLE TRIGGER "COFIDI"."XXCOFIDI_EMP_SER_USU_TR" 
BEFORE INSERT ON "COFIDI".XXCOFIDI_EMPRESA_SERIE_USU_TAB
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_EMPRESA_SERIE_USU_PK IS NULL THEN
      SELECT "COFIDI".XXCOFIDI_EMP_SER_USU_SQ.NEXTVAL
          INTO :NEW.ID_EMPRESA_SERIE_USU_PK FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "COFIDI"."XXCOFIDI_EMP_SER_USU_TR" ENABLE;
