CREATE OR REPLACE NONEDITIONABLE TRIGGER "COFIDI"."XXCOFIDI_PAC_TR" 
BEFORE INSERT ON "COFIDI".XXCOFIDI_PAC_CT_TAB
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_PAC_PK IS NULL THEN
      SELECT "COFIDI".XXCOFIDI_PAC_SQ.NEXTVAL
          INTO :NEW.ID_PAC_PK FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "COFIDI"."XXCOFIDI_PAC_TR" ENABLE;
