CREATE OR REPLACE NONEDITIONABLE TRIGGER "COFIDI"."XXCOFIDI_ROL_TR" 
BEFORE INSERT ON "COFIDI".XXCOFIDI_ROL_CT_TAB
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_ROL_PK IS NULL THEN
      SELECT "COFIDI".XXCOFIDI_ROL_SQ.NEXTVAL
          INTO :NEW.ID_ROL_PK FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "COFIDI"."XXCOFIDI_ROL_TR" ENABLE;
