CREATE OR REPLACE NONEDITIONABLE TRIGGER "COFIDI"."XXCOFIDI_USUARIO_LOGIN_TR" 
BEFORE INSERT ON "COFIDI".XXCOFIDI_USUARIO_LOGIN_TAB
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_USUARIO_LOGIN_PK IS NULL THEN
      SELECT "COFIDI".XXCOFIDI_USUARIO_LOGIN_SQ.NEXTVAL
          INTO :NEW.ID_USUARIO_LOGIN_PK FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "COFIDI"."XXCOFIDI_USUARIO_LOGIN_TR" ENABLE;
