CREATE OR REPLACE NONEDITIONABLE TRIGGER "COFIDI"."XXCOFIDI_ESTADO_TR" 
BEFORE INSERT ON "COFIDI".XXCOFIDI_ESTADO_CT_TAB
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_ESTADO_PK IS NULL THEN
      SELECT "COFIDI".XXCOFIDI_ESTADO_SQ.NEXTVAL
          INTO :NEW.ID_ESTADO_PK FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "COFIDI"."XXCOFIDI_ESTADO_TR" ENABLE;
