CREATE OR REPLACE NONEDITIONABLE TRIGGER "COFIDI"."XXCOFIDI_HISTORICO_CLAVE_TR" 
BEFORE INSERT ON "COFIDI".XXCOFIDI_HISTORICO_CLAVE_TAB
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_HISTORICO_CLAVE_PK IS NULL THEN
      SELECT "COFIDI".XXCOFIDI_HISTORICO_CLAVE_SQ.NEXTVAL
          INTO :NEW.ID_HISTORICO_CLAVE_PK FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "COFIDI"."XXCOFIDI_HISTORICO_CLAVE_TR" ENABLE;
