CREATE OR REPLACE NONEDITIONABLE TRIGGER "COFIDI"."XXCOFIDI_USUARIO_CORREO_TR" 
BEFORE INSERT ON "COFIDI".XXCOFIDI_USUARIO_CORREO_TAB
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_USUARIO_CORREO_PK IS NULL THEN
      SELECT "COFIDI".XXCOFIDI_USUARIO_CORREO_SQ.NEXTVAL
          INTO :NEW.ID_USUARIO_CORREO_PK FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "COFIDI"."XXCOFIDI_USUARIO_CORREO_TR" ENABLE;
