CREATE OR REPLACE NONEDITIONABLE TRIGGER "COFIDI"."XXCOFIDI_SERIES_EMPRESA_TR" 
BEFORE INSERT ON "COFIDI".XXCOFIDI_SERIES_EMPRESA_TAB
FOR EACH ROW
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_SERIES_EMPRESA_PK IS NULL THEN
      SELECT "COFIDI".XXCOFIDI_SERIES_EMPRESA_SQ.NEXTVAL
          INTO :NEW.ID_SERIES_EMPRESA_PK FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER "COFIDI"."XXCOFIDI_SERIES_EMPRESA_TR" ENABLE;
