CREATE OR REPLACE EDITIONABLE TRIGGER "LABPPTO"."T_PPPAGRALES" BEFORE
  INSERT ON "LABPPTO".pppagrales REFERENCING NEW AS NEW FOR EACH ROW BEGIN
  SELECT s_pppagrales.nextval INTO :NEW.gra_keysec FROM dual;
END;
/
ALTER TRIGGER "LABPPTO"."T_PPPAGRALES" ENABLE;
