CREATE TABLE "XXLM_IBOPE"."XXLMK_BITACORA_PROCESOS_TAB" 
   (	"ID_BITACORA" NUMBER NOT NULL ENABLE, 
	"IND_PROCESO" NUMBER NOT NULL ENABLE, 
	"DES_OBSERVACIONES" VARCHAR2(2000), 
	"IND_ESTATUS" NUMBER, 
	"NOM_ARCHIVO" VARCHAR2(500), 
	"FEC_CREACION" DATE DEFAULT SYSDATE, 
	"CVE_CREADO_POR" VARCHAR2(100) NOT NULL ENABLE, 
	"FEC_ACTUALIZACION" DATE DEFAULT SYSDATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100) NOT NULL ENABLE
   )   NO INMEMORY ;
ALTER TABLE "XXLM_IBOPE"."XXLMK_BITACORA_PROCESOS_TAB" ADD PRIMARY KEY ("ID_BITACORA")
  USING INDEX  ENABLE;
