CREATE TABLE "XXLM_IBOPE"."XXLMK_PROCESOS_TAB" 
   (	"ID_PROCESO" NUMBER NOT NULL ENABLE, 
	"NOM_PROCESO" VARCHAR2(100) NOT NULL ENABLE, 
	"DES_PROCESO" VARCHAR2(1000), 
	"IND_ESTATUS" NUMBER, 
	"IND_TIPO_PROCESO" NUMBER NOT NULL ENABLE, 
	"FEC_CREACION" DATE DEFAULT SYSDATE, 
	"CVE_CREADO_POR" VARCHAR2(100) NOT NULL ENABLE, 
	"FEC_ACTUALIZACION" DATE DEFAULT SYSDATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100) NOT NULL ENABLE, 
	"DES_STARTED_BY_UUID" VARCHAR2(100)
   )   NO INMEMORY ;
ALTER TABLE "XXLM_IBOPE"."XXLMK_PROCESOS_TAB" ADD PRIMARY KEY ("ID_PROCESO")
  USING INDEX  ENABLE;
