CREATE TABLE "XXLM_IBOPE"."XXLMK_ARCHIVOS_GENERADOS_TAB" 
   (	"ID_ARCHIVO_GEN" NUMBER NOT NULL ENABLE, 
	"ID_ARCHIVO_IBOPE" NUMBER NOT NULL ENABLE, 
	"NOM_ARCHIVO" VARCHAR2(256) NOT NULL ENABLE, 
	"DES_ARCHIVO" BLOB, 
	"IND_TIPO" NUMBER NOT NULL ENABLE, 
	"IND_ESTATUS" NUMBER NOT NULL ENABLE, 
	"DES_DESC_ARCHIVO" VARCHAR2(2000), 
	"FEC_CREACION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CVE_CREADO_POR" VARCHAR2(100) NOT NULL ENABLE, 
	"FEC_ACTUALIZACION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100) NOT NULL ENABLE
   )   NO INMEMORY ;
ALTER TABLE "XXLM_IBOPE"."XXLMK_ARCHIVOS_GENERADOS_TAB" ADD PRIMARY KEY ("ID_ARCHIVO_GEN")
  USING INDEX  ENABLE;
ALTER TABLE "XXLM_IBOPE"."XXLMK_ARCHIVOS_GENERADOS_TAB" ADD CONSTRAINT "XXLMK_ARCHIVOS_GEN_TAB_FK01" FOREIGN KEY ("ID_ARCHIVO_IBOPE")
	  REFERENCES "XXLM_IBOPE"."XXLMK_ARCHIVOS_TAB" ("ID_ARCHIVO") ENABLE;
