CREATE TABLE "XXLM_IBOPE"."XXLMK_CONFIG_PROCESOS_TAB" 
   (	"ID_CONFIG" NUMBER NOT NULL ENABLE, 
	"ID_PROCESO" NUMBER NOT NULL ENABLE, 
	"NUM_HORA_EJEC" NUMBER NOT NULL ENABLE, 
	"NUM_MINUNTO_EJEC" NUMBER NOT NULL ENABLE, 
	"NUM_EJEC_CADA" NUMBER NOT NULL ENABLE, 
	"DES_EJEC_DIAS" VARCHAR2(100), 
	"NOM_CONFIG" VARCHAR2(100) NOT NULL ENABLE, 
	"DES_CONFIG" VARCHAR2(1000), 
	"IND_ESTATUS" NUMBER DEFAULT 0, 
	"IND_TIME_UNIT" NUMBER NOT NULL ENABLE, 
	"FEC_CREACION" DATE DEFAULT SYSDATE, 
	"CVE_CREADO_POR" VARCHAR2(100) NOT NULL ENABLE, 
	"FEC_ACTUALIZACION" DATE DEFAULT SYSDATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100) NOT NULL ENABLE
   )   NO INMEMORY ;
ALTER TABLE "XXLM_IBOPE"."XXLMK_CONFIG_PROCESOS_TAB" ADD PRIMARY KEY ("ID_CONFIG")
  USING INDEX  ENABLE;
ALTER TABLE "XXLM_IBOPE"."XXLMK_CONFIG_PROCESOS_TAB" ADD CONSTRAINT "XXLMK_CONFIG_PROCESOS_TAB_FK1" FOREIGN KEY ("ID_PROCESO")
	  REFERENCES "XXLM_IBOPE"."XXLMK_PROCESOS_TAB" ("ID_PROCESO") ENABLE;
