CREATE OR REPLACE EDITIONABLE TRIGGER "FECXC"."FECXP_EMPRESAS_NOSET_DET" AFTER
INSERT OR UPDATE OF ID_EMP ON FECXC.FECXP_EMP_NO_SET
FOR EACH ROW
DECLARE
BEGIN
UPDATE FECXC.FECXP_PPTO_CARATULA_IMPNS
SET E_CODIGO=:NEW.ID_EMP
WHERE E_CODIGO  = :NEW.ID_EMP_OLD;
UPDATE FECXC.FECXP_REAL_CARATULA_IMPNS
SET E_CODIGO=:NEW.ID_EMP
WHERE E_CODIGO  = :OLD.ID_EMP;
UPDATE FECXC.FECXP_EMP_X_SEGMENTO_NO_SET
SET E_CODIGO=:NEW.ID_EMP
WHERE E_CODIGO  = :NEW.ID_EMP_OLD;
END;

/
ALTER TRIGGER "FECXC"."FECXP_EMPRESAS_NOSET_DET" ENABLE;
