CREATE TABLE "LABPPTO"."GLCORECA" 
   (	"REC_KEYMEN" VARCHAR2(4), 
	"REC_KEYTAB" VARCHAR2(18), 
	"REC_KEYCAM" VARCHAR2(18), 
	"REC_ACTUAL" VARCHAR2(1), 
	"REC_DESPLI" VARCHAR2(1), 
	"REC_VALCAM" VARCHAR2(1)
   ) ;
