CREATE TABLE "LABPPTO"."PPLOVAC" 
   (	"VAC_KEYCIA" VARCHAR2(4) NOT NULL ENABLE, 
	"VAC_AANTIG" NUMBER(*,0) NOT NULL ENABLE, 
	"VAC_DIAS" NUMBER(*,0) NOT NULL ENABLE, 
	"VAC_KEYPRO" NUMBER(*,0), 
	"VAC_TIPEMP" VARCHAR2(6)
   ) ;
