CREATE TABLE "LABPPTO"."PPLOCUEN" 
   (	"CUE_KEYCUE" NUMBER(*,0) NOT NULL ENABLE, 
	"CUE_KEYTPO" NUMBER(*,0) NOT NULL ENABLE, 
	"CUE_KEYDES" CHAR(35) NOT NULL ENABLE, 
	"CUE_TIPCUE" NUMBER(*,0) NOT NULL ENABLE
   ) ;
