CREATE TABLE "LABPPTO"."PPORDEJE" 
   (	"EJE_KEYCIA" VARCHAR2(4) NOT NULL ENABLE, 
	"EJE_KEYVER" NUMBER(*,0) NOT NULL ENABLE, 
	"EJE_KEYCON" VARCHAR2(3) NOT NULL ENABLE, 
	"EJE_FECEJE" DATE, 
	"EJE_STATUS" NUMBER(*,0), 
	"EJE_ORDEJE" NUMBER(*,0)
   ) ;
