CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_LOGIN_LOG_BI_TR_01" 
BEFORE INSERT
ON "ADMP".ADMP_LOGIN_LOG_TAB
FOR EACH ROW
BEGIN
	SELECT ADMP_LOGIN_LOG_SQ.NEXTVAL INTO :NEW.ID_LOGIN_LOG FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_LOGIN_LOG_BI_TR_01" ENABLE;
