CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_TIPO_BI_TR_01" 
BEFORE INSERT 
ON "ADMP". ADMP_TIPO_TAB
FOR EACH ROW
BEGIN
    SELECT ADMP_TIPO_SQ.NEXTVAL INTO :NEW.ID_TIPO FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_TIPO_BI_TR_01" ENABLE;
