CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_TARGET_PARR_D_BI_TR_01" 
BEFORE INSERT 
ON "ADMP". ADMP_TARGET_PARR_DET_TAB
FOR EACH ROW
BEGIN 
	SELECT ADMP_TARGET_PARR_DET_SQ.NEXTVAL INTO :NEW.ID_TARGET_PARR_DET FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_TARGET_PARR_D_BI_TR_01" ENABLE;
