CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_USUARIO_CORREO_BI_TR_01" 
BEFORE INSERT
ON "ADMP".ADMP_USUARIO_CORREO_TAB
FOR EACH ROW 
BEGIN 
	SELECT ADMP_USUARIO_CORREO_SQ.NEXTVAL INTO :NEW.ID_USUARIO_CORREO FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_USUARIO_CORREO_BI_TR_01" ENABLE;
