CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_ROL_ELEMENTO_BI_TR_01" 
BEFORE INSERT 
ON "ADMP". ADMP_ROL_ELEMENTO_TAB
FOR EACH ROW
BEGIN 
    SELECT ADMP_ROL_ELEMENTO_SQ.NEXTVAL INTO :NEW.ID_ROL_ELEMENTO FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_ROL_ELEMENTO_BI_TR_01" ENABLE;
