CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_LISTA_DIST_DET_BI_TR_01" 
BEFORE INSERT 
ON "ADMP". ADMP_LISTA_DIST_DET_TAB
FOR EACH ROW
BEGIN
	SELECT ADMP_LISTA_DIST_DET_SQ.NEXTVAL INTO :NEW.ID_LISTA_DIST_DET FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_LISTA_DIST_DET_BI_TR_01" ENABLE;
