CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_RESTRICCION_BI_TR_01" 
BEFORE INSERT
ON "ADMP".ADMP_RESTRICCION_TAB
FOR EACH ROW 
BEGIN 
    SELECT ADMP_RESTRICCION_SQ.NEXTVAL INTO :NEW.ID_RESTRICCION FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_RESTRICCION_BI_TR_01" ENABLE;
