CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_FUENTE_BI_TR_01" 
BEFORE INSERT
ON "ADMP".ADMP_FUENTE_TAB
FOR EACH ROW
BEGIN
    SELECT ADMP.ADMP_FUENTE_SQ.NEXTVAL INTO :NEW.ID_FUENTE FROM DUAL;
END;



/
ALTER TRIGGER "ADMP"."ADMP_FUENTE_BI_TR_01" ENABLE;
