CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_USUARIO_BI_TR_01" 
BEFORE INSERT
ON "ADMP".ADMP_USUARIO_TAB
FOR EACH ROW
BEGIN 
    SELECT ADMP_USUARIO_SQ.NEXTVAL INTO :new.ID_USUARIO FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_USUARIO_BI_TR_01" ENABLE;
