CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_USUARIO_ROL_BI_TR_01" 
BEFORE INSERT 
ON "ADMP". ADMP_USUARIO_ROL_TAB
FOR EACH ROW
BEGIN 
    SELECT ADMP_USUARIO_ROL_SQ.NEXTVAL INTO :NEW.ID_USUARIO_ROL FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_USUARIO_ROL_BI_TR_01" ENABLE;
