CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_CANAL_BI_TR_01" 
BEFORE INSERT
ON "ADMP".ADMP_CANAL_TAB
FOR EACH ROW
BEGIN 
    SELECT ADMP_CANAL_SQ.NEXTVAL INTO :new.ID_CANAL FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_CANAL_BI_TR_01" ENABLE;
