CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_GENERO_BI_TR_01" 
BEFORE INSERT
ON "ADMP".ADMP_GENERO_TAB
FOR EACH ROW
BEGIN 
	SELECT ADMP_GENERO_SQ.NEXTVAL INTO :NEW.ID_GENERO FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_GENERO_BI_TR_01" ENABLE;
