CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_TIPO_ELEMENTO_BI_TR_01" 
BEFORE INSERT 
ON "ADMP". ADMP_TIPO_ELEMENTO_TAB
FOR EACH ROW 
BEGIN 
    SELECT ADMP_TIPO_ELEMENTO_SQ.NEXTVAL INTO :NEW.ID_TIPO_ELEMENTO FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_TIPO_ELEMENTO_BI_TR_01" ENABLE;
