CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_UDN_BI_TR_O1" 
BEFORE INSERT
ON "ADMP".ADMP_UDN_TAB
FOR EACH ROW
BEGIN
    SELECT ADMP_UDN_SQ.NEXTVAL INTO :NEW.ID_UDN FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_UDN_BI_TR_O1" ENABLE;
