CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_LISTA_DIST_BI_TR_01" 
BEFORE INSERT 
ON "ADMP". ADMP_LISTA_DIST_TAB
FOR EACH ROW 
BEGIN 
	SELECT ADMP_LISTA_DIST_SQ.NEXTVAL INTO :NEW.ID_LISTA_DIST FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_LISTA_DIST_BI_TR_01" ENABLE;
