CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_CAMBIO_BI_TR_01" 
BEFORE INSERT 
ON "ADMP". ADMP_CAMBIO_TAB
FOR EACH ROW
BEGIN 
    SELECT ADMP_CAMBIO_SQ.NEXTVAL INTO :NEW.ID_CAMBIO FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_CAMBIO_BI_TR_01" ENABLE;
