CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_CLASE_BI_TR_01" 
BEFORE INSERT
ON "ADMP".ADMP_CLASE_TAB
FOR EACH ROW
BEGIN
	SELECT ADMP_CLASE_SQ.NEXTVAL INTO :NEW.ID_CLASE FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_CLASE_BI_TR_01" ENABLE;
