CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_CONTENEDOR_BI_TR_01" 
BEFORE INSERT 
ON "ADMP". ADMP_CONTENEDOR_TAB
FOR EACH ROW
BEGIN
    SELECT ADMP_CONTENEDOR_SQ.NEXTVAL INTO :NEW.ID_CONTENEDOR FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_CONTENEDOR_BI_TR_01" ENABLE;
