CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_CREDENCIAL_BI_TR_01" 
BEFORE INSERT
ON ADMP.ADMP_CREDENCIAL_TAB
FOR EACH ROW
BEGIN
    SELECT ADMP.ADMP_CREDENCIAL_SQ.NEXTVAL INTO :NEW.ID_CREDENCIAL FROM DUAL;
END;



/
ALTER TRIGGER "ADMP"."ADMP_CREDENCIAL_BI_TR_01" ENABLE;
