CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_CONTRATO_MEMO_BI_TR_01" 
BEFORE INSERT
ON  "ADMP".ADMP_CONTRATO_MEMO_TAB
FOR EACH ROW
BEGIN
	SELECT ADMP_CONTRATO_MEMO_SQ.NEXTVAL INTO :NEW.ID_CONTRATO_MEMO FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_CONTRATO_MEMO_BI_TR_01" ENABLE;
