CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_REPORTE_BI_TR_01" 
BEFORE INSERT
ON "ADMP".ADMP_REPORTE_TAB
FOR EACH ROW
BEGIN
	SELECT ADMP_REPORTE_SQ.NEXTVAL INTO :NEW.ID_REPORTE FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_REPORTE_BI_TR_01" ENABLE;
