CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_CAMBIO_ELE_M_BI_TR_01" 
BEFORE INSERT 
ON "ADMP". ADMP_CAMBIO_ELEMENTO_M_TAB 
FOR EACH ROW
BEGIN
    SELECT ADMP_CAMBIO_ELEMENTO_M_SQ.NEXTVAL INTO :NEW.ID_CAMBIO_ELEMENTO_M FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_CAMBIO_ELE_M_BI_TR_01" ENABLE;
