CREATE OR REPLACE EDITIONABLE TRIGGER "ADMP"."ADMP_REPORTE_CANAL_BI_TR_01" 
BEFORE INSERT
ON "ADMP".ADMP_REPORTE_CANAL_TAB
FOR EACH ROW
BEGIN
	SELECT ADMP_REPORTE_CANAL_SQ.NEXTVAL INTO :NEW.ID_REPORTE_CANAL FROM DUAL;
END;




/
ALTER TRIGGER "ADMP"."ADMP_REPORTE_CANAL_BI_TR_01" ENABLE;
