CREATE TABLE "ADMP"."ADMP_TARGET_PARR_DET_TAB" 
   (	"ID_TARGET_PARR_DET" NUMBER NOT NULL ENABLE, 
	"ID_PARRILLA_DET" NUMBER NOT NULL ENABLE, 
	"ID_TARGET" NUMBER NOT NULL ENABLE, 
	"CAN_RATING" NUMBER NOT NULL ENABLE, 
	"NUM_CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_CREATION_DATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_LAST_UPDATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATRIBUTO1" VARCHAR2(150), 
	"ATRIBUTO2" VARCHAR2(150), 
	"ATRIBUTO3" VARCHAR2(150), 
	"ATRIBUTO4" VARCHAR2(150), 
	"ATRIBUTO5" VARCHAR2(150), 
	"ATRIBUTO6" VARCHAR2(150), 
	"ATRIBUTO7" VARCHAR2(150), 
	"ATRIBUTO8" VARCHAR2(150), 
	"ATRIBUTO9" VARCHAR2(150), 
	"ATRIBUTO10" VARCHAR2(150), 
	"ATRIBUTO11" VARCHAR2(150), 
	"ATRIBUTO12" VARCHAR2(150), 
	"ATRIBUTO13" VARCHAR2(150), 
	"ATRIBUTO14" VARCHAR2(150), 
	"ATRIBUTO15" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150)
   )   NO INMEMORY ;
  CREATE UNIQUE INDEX "ADMP"."ADMP_TARGET_PARR_DET_PK" ON "ADMP"."ADMP_TARGET_PARR_DET_TAB" ("ID_TARGET_PARR_DET") 
  ;
ALTER TABLE "ADMP"."ADMP_TARGET_PARR_DET_TAB" ADD CONSTRAINT "ADMP_TARGET_PARR_DET_PK" PRIMARY KEY ("ID_TARGET_PARR_DET")
  USING INDEX "ADMP"."ADMP_TARGET_PARR_DET_PK"  ENABLE;
ALTER TABLE "ADMP"."ADMP_TARGET_PARR_DET_TAB" ADD CONSTRAINT "ADMP_TARGET_PARR_DET_FK_01" FOREIGN KEY ("ID_PARRILLA_DET")
	  REFERENCES "ADMP"."ADMP_PARRILLA_DET_TAB" ("ID_PARRILLA_DET") ENABLE;
ALTER TABLE "ADMP"."ADMP_TARGET_PARR_DET_TAB" ADD CONSTRAINT "ADMP_TARGET_PARR_DET_FK_02" FOREIGN KEY ("ID_TARGET")
	  REFERENCES "ADMP"."ADMP_TARGET_TAB" ("ID_TARGET") ENABLE;
