CREATE TABLE "ADMP"."ADMP_CAMBIO_ELEMENTO_M_TAB" 
   (	"ID_CAMBIO_ELEMENTO_M" NUMBER NOT NULL ENABLE, 
	"ID_CAMBIO" NUMBER NOT NULL ENABLE, 
	"ID_ELEMENTO_MEMO" NUMBER NOT NULL ENABLE, 
	"NUM_VISIBLE" NUMBER(1,0) NOT NULL ENABLE, 
	"NUM_CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_CREATION_DATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_LAST_UPDATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATRIBUTO1" VARCHAR2(150), 
	"ATRIBUTO2" VARCHAR2(150), 
	"ATRIBUTO3" VARCHAR2(150), 
	"ATRIBUTO4" VARCHAR2(150), 
	"ATRIBUTO5" VARCHAR2(150), 
	"ATRIBUTO6" VARCHAR2(150), 
	"ATRIBUTO7" VARCHAR2(150), 
	"ATRIBUTO8" VARCHAR2(150), 
	"ATRIBUTO9" VARCHAR2(150), 
	"ATRIBUTO10" VARCHAR2(150), 
	"ATRIBUTO11" VARCHAR2(150), 
	"ATRIBUTO12" VARCHAR2(150), 
	"ATRIBUTO13" VARCHAR2(150), 
	"ATRIBUTO14" VARCHAR2(150), 
	"ATRIBUTO15" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150)
   )   NO INMEMORY ;
  CREATE UNIQUE INDEX "ADMP"."ADMP_CAMBIO_ELEMENTO_M_PK" ON "ADMP"."ADMP_CAMBIO_ELEMENTO_M_TAB" ("ID_CAMBIO_ELEMENTO_M") 
  ;
ALTER TABLE "ADMP"."ADMP_CAMBIO_ELEMENTO_M_TAB" ADD CONSTRAINT "ADMP_CAMBIO_ELEMENTO_M_PK" PRIMARY KEY ("ID_CAMBIO_ELEMENTO_M")
  USING INDEX "ADMP"."ADMP_CAMBIO_ELEMENTO_M_PK"  ENABLE;
ALTER TABLE "ADMP"."ADMP_CAMBIO_ELEMENTO_M_TAB" ADD CONSTRAINT "ADMP_CAMBIO_ELEMENTO_M_FK_01" FOREIGN KEY ("ID_CAMBIO")
	  REFERENCES "ADMP"."ADMP_CAMBIO_TAB" ("ID_CAMBIO") ENABLE;
ALTER TABLE "ADMP"."ADMP_CAMBIO_ELEMENTO_M_TAB" ADD CONSTRAINT "ADMP_CAMBIO_ELEMENTO_M_FK_02" FOREIGN KEY ("ID_ELEMENTO_MEMO")
	  REFERENCES "ADMP"."ADMP_ELEMENTO_MEMO_TAB" ("ID_ELEMENTO_MEMO") ENABLE;
