CREATE TABLE "ADMP"."ADMP_CREDENCIAL_TAB" 
   (	"ID_CREDENCIAL" NUMBER NOT NULL ENABLE, 
	"DES_SISTEMA" VARCHAR2(20) NOT NULL ENABLE, 
	"DES_USUARIO" VARCHAR2(250) NOT NULL ENABLE, 
	"DES_CONTRASENA" VARCHAR2(100), 
	"DES_LLAVE" VARCHAR2(50), 
	"DES_DESTINO" VARCHAR2(100), 
	"NUM_PUERTO" NUMBER(*,0), 
	"DES_RUTA" VARCHAR2(100), 
	"NUM_CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_CREATION_DATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_LAST_UPDATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATRIBUTO1" VARCHAR2(150), 
	"ATRIBUTO2" VARCHAR2(150), 
	"ATRIBUTO3" VARCHAR2(150), 
	"ATRIBUTO4" VARCHAR2(150), 
	"ATRIBUTO5" VARCHAR2(150), 
	"ATRIBUTO6" VARCHAR2(150), 
	"ATRIBUTO7" VARCHAR2(150), 
	"ATRIBUTO8" VARCHAR2(150), 
	"ATRIBUTO9" VARCHAR2(150), 
	"ATRIBUTO10" VARCHAR2(150), 
	"ATRIBUTO11" VARCHAR2(150), 
	"ATRIBUTO12" VARCHAR2(150), 
	"ATRIBUTO13" VARCHAR2(150), 
	"ATRIBUTO14" VARCHAR2(150), 
	"ATRIBUTO15" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150)
   )   NO INMEMORY ;
  CREATE UNIQUE INDEX "ADMP"."ADMP_CREDENCIAL_PK" ON "ADMP"."ADMP_CREDENCIAL_TAB" ("ID_CREDENCIAL") 
  ;
ALTER TABLE "ADMP"."ADMP_CREDENCIAL_TAB" ADD CONSTRAINT "ADMP_CREDENCIAL_PK" PRIMARY KEY ("ID_CREDENCIAL")
  USING INDEX "ADMP"."ADMP_CREDENCIAL_PK"  ENABLE;
