CREATE TABLE "ADMP"."ADMP_REPORTE_CANAL_TAB" 
   (	"ID_REPORTE_CANAL" NUMBER NOT NULL ENABLE, 
	"ID_REPORTE" NUMBER NOT NULL ENABLE, 
	"ID_CANAL" NUMBER NOT NULL ENABLE, 
	"NUM_CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_CREATION_DATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_LAST_UPDATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATRIBUTO1" VARCHAR2(150), 
	"ATRIBUTO2" VARCHAR2(150), 
	"ATRIBUTO3" VARCHAR2(150), 
	"ATRIBUTO4" VARCHAR2(150), 
	"ATRIBUTO5" VARCHAR2(150), 
	"ATRIBUTO6" VARCHAR2(150), 
	"ATRIBUTO7" VARCHAR2(150), 
	"ATRIBUTO8" VARCHAR2(150), 
	"ATRIBUTO9" VARCHAR2(150), 
	"ATRIBUTO10" VARCHAR2(150), 
	"ATRIBUTO11" VARCHAR2(150), 
	"ATRIBUTO12" VARCHAR2(150), 
	"ATRIBUTO13" VARCHAR2(150), 
	"ATRIBUTO14" VARCHAR2(150), 
	"ATRIBUTO15" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150)
   )   NO INMEMORY ;
  CREATE UNIQUE INDEX "ADMP"."ADMP_REPORTE_CANAL_PK" ON "ADMP"."ADMP_REPORTE_CANAL_TAB" ("ID_REPORTE_CANAL") 
  ;
ALTER TABLE "ADMP"."ADMP_REPORTE_CANAL_TAB" ADD CONSTRAINT "ADMP_REPORTE_CANAL_PK" PRIMARY KEY ("ID_REPORTE_CANAL")
  USING INDEX "ADMP"."ADMP_REPORTE_CANAL_PK"  ENABLE;
ALTER TABLE "ADMP"."ADMP_REPORTE_CANAL_TAB" ADD CONSTRAINT "ADMP_REPORTE_CANAL_FK_01" FOREIGN KEY ("ID_REPORTE")
	  REFERENCES "ADMP"."ADMP_REPORTE_TAB" ("ID_REPORTE") ENABLE;
ALTER TABLE "ADMP"."ADMP_REPORTE_CANAL_TAB" ADD CONSTRAINT "ADMP_REPORTE_CANAL_FK_02" FOREIGN KEY ("ID_CANAL")
	  REFERENCES "ADMP"."ADMP_CANAL_TAB" ("ID_CANAL") ENABLE;
