CREATE TABLE "ADMP"."ADMP_EVENTO_TAB" 
   (	"ID_EVENTO" NUMBER NOT NULL ENABLE, 
	"DES_EVENTO" VARCHAR2(100) NOT NULL ENABLE, 
	"ID_GENERO" NUMBER NOT NULL ENABLE, 
	"ID_ESTADO" NUMBER NOT NULL ENABLE, 
	"NUM_CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_CREATION_DATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_LAST_UPDATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATRIBUTO1" VARCHAR2(150), 
	"ATRIBUTO2" VARCHAR2(150), 
	"ATRIBUTO3" VARCHAR2(150), 
	"ATRIBUTO4" VARCHAR2(150), 
	"ATRIBUTO5" VARCHAR2(150), 
	"ATRIBUTO6" VARCHAR2(150), 
	"ATRIBUTO7" VARCHAR2(150), 
	"ATRIBUTO8" VARCHAR2(150), 
	"ATRIBUTO9" VARCHAR2(150), 
	"ATRIBUTO10" VARCHAR2(150), 
	"ATRIBUTO11" VARCHAR2(150), 
	"ATRIBUTO12" VARCHAR2(150), 
	"ATRIBUTO13" VARCHAR2(150), 
	"ATRIBUTO14" VARCHAR2(150), 
	"ATRIBUTO15" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150)
   )   NO INMEMORY ;
  CREATE UNIQUE INDEX "ADMP"."ADMP_EVENTO_PK" ON "ADMP"."ADMP_EVENTO_TAB" ("ID_EVENTO") 
  ;
ALTER TABLE "ADMP"."ADMP_EVENTO_TAB" ADD CONSTRAINT "ADMP_EVENTO_PK" PRIMARY KEY ("ID_EVENTO")
  USING INDEX "ADMP"."ADMP_EVENTO_PK"  ENABLE;
ALTER TABLE "ADMP"."ADMP_EVENTO_TAB" ADD CONSTRAINT "ADMP_EVENTO_FK_01" FOREIGN KEY ("ID_GENERO")
	  REFERENCES "ADMP"."ADMP_GENERO_TAB" ("ID_GENERO") ENABLE;
ALTER TABLE "ADMP"."ADMP_EVENTO_TAB" ADD CONSTRAINT "ADMP_EVENTO_FK_02" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "ADMP"."ADMP_ESTADO_TAB" ("ID_ESTADO") ENABLE;
