CREATE TABLE "ADMP"."ADMP_PARRILLA_TAB" 
   (	"ID_PARRILLA" NUMBER NOT NULL ENABLE, 
	"FEC_PARRILLA" DATE NOT NULL ENABLE, 
	"ID_CANAL" NUMBER NOT NULL ENABLE, 
	"NUM_VERSION" NUMBER NOT NULL ENABLE, 
	"ID_ESTADO" NUMBER NOT NULL ENABLE, 
	"NUM_CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_CREATION_DATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_LAST_UPDATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATRIBUTO1" VARCHAR2(150), 
	"ATRIBUTO2" VARCHAR2(150), 
	"ATRIBUTO3" VARCHAR2(150), 
	"ATRIBUTO4" VARCHAR2(150), 
	"ATRIBUTO5" VARCHAR2(150), 
	"ATRIBUTO6" VARCHAR2(150), 
	"ATRIBUTO7" VARCHAR2(150), 
	"ATRIBUTO8" VARCHAR2(150), 
	"ATRIBUTO9" VARCHAR2(150), 
	"ATRIBUTO10" VARCHAR2(150), 
	"ATRIBUTO11" VARCHAR2(150), 
	"ATRIBUTO12" VARCHAR2(150), 
	"ATRIBUTO13" VARCHAR2(150), 
	"ATRIBUTO14" VARCHAR2(150), 
	"ATRIBUTO15" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150), 
	"ID_TIPO_PARRILLA" NUMBER(2,0)
   )   NO INMEMORY ;
  CREATE UNIQUE INDEX "ADMP"."ADMP_PARRILLA_PK" ON "ADMP"."ADMP_PARRILLA_TAB" ("ID_PARRILLA") 
  ;
ALTER TABLE "ADMP"."ADMP_PARRILLA_TAB" ADD CONSTRAINT "ADMP_PARRILLA_PK" PRIMARY KEY ("ID_PARRILLA")
  USING INDEX "ADMP"."ADMP_PARRILLA_PK"  ENABLE;
ALTER TABLE "ADMP"."ADMP_PARRILLA_TAB" ADD CONSTRAINT "ADMP_PARRILLA_FK_01" FOREIGN KEY ("ID_CANAL")
	  REFERENCES "ADMP"."ADMP_CANAL_TAB" ("ID_CANAL") ENABLE;
ALTER TABLE "ADMP"."ADMP_PARRILLA_TAB" ADD CONSTRAINT "ADMP_PARRILLA_FK_02" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "ADMP"."ADMP_ESTADO_TAB" ("ID_ESTADO") ENABLE;
ALTER TABLE "ADMP"."ADMP_PARRILLA_TAB" ADD CONSTRAINT "ADMP_PARRILLA_FK_03" FOREIGN KEY ("ID_TIPO_PARRILLA")
	  REFERENCES "ADMP"."ADMP_TIPO_PARRILLA_TAB" ("ID_TIPO_PARRILLA") ENABLE;
