CREATE TABLE "ADMP"."ADMP_LOGIN_LOG_TAB" 
   (	"ID_LOGIN_LOG" NUMBER NOT NULL ENABLE, 
	"DES_USUARIO" VARCHAR2(50) NOT NULL ENABLE, 
	"FEC_FECHA_EVENTO" DATE NOT NULL ENABLE, 
	"DES_ESTADO" VARCHAR2(50) NOT NULL ENABLE, 
	"DES_DESCRIPCION" VARCHAR2(100) NOT NULL ENABLE, 
	"DES_TIPO" VARCHAR2(10) NOT NULL ENABLE, 
	"NUM_CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_CREATION_DATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_LAST_UPDATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATRIBUTO1" VARCHAR2(150), 
	"ATRIBUTO2" VARCHAR2(150), 
	"ATRIBUTO3" VARCHAR2(150), 
	"ATRIBUTO4" VARCHAR2(150), 
	"ATRIBUTO5" VARCHAR2(150), 
	"ATRIBUTO6" VARCHAR2(150), 
	"ATRIBUTO7" VARCHAR2(150), 
	"ATRIBUTO8" VARCHAR2(150), 
	"ATRIBUTO9" VARCHAR2(150), 
	"ATRIBUTO10" VARCHAR2(150), 
	"ATRIBUTO11" VARCHAR2(150), 
	"ATRIBUTO12" VARCHAR2(150), 
	"ATRIBUTO13" VARCHAR2(150), 
	"ATRIBUTO14" VARCHAR2(150), 
	"ATRIBUTO15" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150)
   )   NO INMEMORY ;
  CREATE UNIQUE INDEX "ADMP"."ADMP_LOGIN_LOG_PK" ON "ADMP"."ADMP_LOGIN_LOG_TAB" ("ID_LOGIN_LOG") 
  ;
ALTER TABLE "ADMP"."ADMP_LOGIN_LOG_TAB" ADD CONSTRAINT "ADMP_LOGIN_LOG_PK" PRIMARY KEY ("ID_LOGIN_LOG")
  USING INDEX "ADMP"."ADMP_LOGIN_LOG_PK"  ENABLE;
