CREATE TABLE "ADMP"."ADMP_ELEMENTO_TAB" 
   (	"ID_ELEMENTO" NUMBER NOT NULL ENABLE, 
	"DES_ELEMENTO" VARCHAR2(50) NOT NULL ENABLE, 
	"ID_CONTENEDOR" NUMBER NOT NULL ENABLE, 
	"ID_ESTADO" NUMBER NOT NULL ENABLE, 
	"NUM_CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_CREATION_DATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_LAST_UPDATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATRIBUTO1" VARCHAR2(150), 
	"ATRIBUTO2" VARCHAR2(150), 
	"ATRIBUTO3" VARCHAR2(150), 
	"ATRIBUTO4" VARCHAR2(150), 
	"ATRIBUTO5" VARCHAR2(150), 
	"ATRIBUTO6" VARCHAR2(150), 
	"ATRIBUTO7" VARCHAR2(150), 
	"ATRIBUTO8" VARCHAR2(150), 
	"ATRIBUTO9" VARCHAR2(150), 
	"ATRIBUTO10" VARCHAR2(150), 
	"ATRIBUTO11" VARCHAR2(150), 
	"ATRIBUTO12" VARCHAR2(150), 
	"ATRIBUTO13" VARCHAR2(150), 
	"ATRIBUTO14" VARCHAR2(150), 
	"ATRIBUTO15" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150), 
	"NOM_PAGINA" VARCHAR2(100)
   )   NO INMEMORY ;
  CREATE UNIQUE INDEX "ADMP"."ADMP_ELEMENTO_PK" ON "ADMP"."ADMP_ELEMENTO_TAB" ("ID_ELEMENTO") 
  ;
ALTER TABLE "ADMP"."ADMP_ELEMENTO_TAB" ADD CONSTRAINT "ADMP_ELEMENTO_PK" PRIMARY KEY ("ID_ELEMENTO")
  USING INDEX "ADMP"."ADMP_ELEMENTO_PK"  ENABLE;
ALTER TABLE "ADMP"."ADMP_ELEMENTO_TAB" ADD CONSTRAINT "ADMP_ELEMENTO_FK_01" FOREIGN KEY ("ID_CONTENEDOR")
	  REFERENCES "ADMP"."ADMP_CONTENEDOR_TAB" ("ID_CONTENEDOR") ENABLE;
ALTER TABLE "ADMP"."ADMP_ELEMENTO_TAB" ADD CONSTRAINT "ADMP_ELEMENTO_FK_02" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "ADMP"."ADMP_ESTADO_TAB" ("ID_ESTADO") ENABLE;
