CREATE TABLE "ADMP"."ADMP_MEMO_DETALLE_TAB" 
   (	"ID_MEMO_DETALLE" NUMBER NOT NULL ENABLE, 
	"ID_MEMO" NUMBER NOT NULL ENABLE, 
	"ID_CAMBIO" NUMBER NOT NULL ENABLE, 
	"DES_CICLO" VARCHAR2(800), 
	"FEC_INICIO" DATE, 
	"FEC_FIN" DATE, 
	"NUM_LUNES" NUMBER(1,0), 
	"NUM_MARTES" NUMBER(1,0), 
	"NUM_MIERCOLES" NUMBER(1,0), 
	"NUM_JUEVES" NUMBER(1,0), 
	"NUM_VIERNES" NUMBER(1,0), 
	"NUM_SABADO" NUMBER(1,0), 
	"NUM_DOMINGO" NUMBER(1,0), 
	"DES_CAMBIO" VARCHAR2(600), 
	"DES_HORA_INI" VARCHAR2(10), 
	"DES_HORA_FIN" VARCHAR2(10), 
	"NUM_DURACION" NUMBER, 
	"DES_REPARTO" VARCHAR2(2000), 
	"ID_TIPO" NUMBER, 
	"ID_SUB_GENERO" NUMBER, 
	"ID_PRODUCCION" NUMBER, 
	"ID_ESTATUS" NUMBER, 
	"ID_ORIGEN" NUMBER, 
	"DES_RESPONSABILIDAD" VARCHAR2(400), 
	"ID_UDN" NUMBER, 
	"ID_CLASIFICACION" NUMBER, 
	"ID_CLASE" NUMBER, 
	"FEC_ULTIMA_TRANS" DATE, 
	"DES_OBSERVACIONES" VARCHAR2(800), 
	"NUM_CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_CREATION_DATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_LAST_UPDATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATRIBUTO1" VARCHAR2(150), 
	"ATRIBUTO2" VARCHAR2(150), 
	"ATRIBUTO3" VARCHAR2(150), 
	"ATRIBUTO4" VARCHAR2(150), 
	"ATRIBUTO5" VARCHAR2(150), 
	"ATRIBUTO6" VARCHAR2(150), 
	"ATRIBUTO7" VARCHAR2(150), 
	"ATRIBUTO8" VARCHAR2(150), 
	"ATRIBUTO9" VARCHAR2(150), 
	"ATRIBUTO10" VARCHAR2(150), 
	"ATRIBUTO11" VARCHAR2(150), 
	"ATRIBUTO12" VARCHAR2(150), 
	"ATRIBUTO13" VARCHAR2(150), 
	"ATRIBUTO14" VARCHAR2(150), 
	"ATRIBUTO15" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150), 
	"ID_RESTRICCION" NUMBER, 
	"ID_GENERO" NUMBER
   )   NO INMEMORY ;
  CREATE UNIQUE INDEX "ADMP"."ADMP_MEMO_DETALLE_PK" ON "ADMP"."ADMP_MEMO_DETALLE_TAB" ("ID_MEMO_DETALLE") 
  ;
ALTER TABLE "ADMP"."ADMP_MEMO_DETALLE_TAB" ADD CONSTRAINT "ADMP_MEMO_DETALLE_PK" PRIMARY KEY ("ID_MEMO_DETALLE")
  USING INDEX "ADMP"."ADMP_MEMO_DETALLE_PK"  ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_DETALLE_TAB" ADD CONSTRAINT "ADMP_MEMO_DETALLE_FK_05" FOREIGN KEY ("ID_PRODUCCION")
	  REFERENCES "ADMP"."ADMP_PRODUCCION_TAB" ("ID_PRODUCCION") ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_DETALLE_TAB" ADD CONSTRAINT "ADMP_MEMO_DETALLE_FK_08" FOREIGN KEY ("ID_UDN")
	  REFERENCES "ADMP"."ADMP_UDN_TAB" ("ID_UDN") ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_DETALLE_TAB" ADD CONSTRAINT "ADMP_MEMO_DETALLE_FK_12" FOREIGN KEY ("ID_GENERO")
	  REFERENCES "ADMP"."ADMP_GENERO_TAB" ("ID_GENERO") ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_DETALLE_TAB" ADD CONSTRAINT "ADMP_MEMO_DETALLE_FK_01" FOREIGN KEY ("ID_MEMO")
	  REFERENCES "ADMP"."ADMP_MEMO_TAB" ("ID_MEMO") ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_DETALLE_TAB" ADD CONSTRAINT "ADMP_MEMO_DETALLE_FK_02" FOREIGN KEY ("ID_CAMBIO")
	  REFERENCES "ADMP"."ADMP_CAMBIO_TAB" ("ID_CAMBIO") ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_DETALLE_TAB" ADD CONSTRAINT "ADMP_MEMO_DETALLE_FK_03" FOREIGN KEY ("ID_TIPO")
	  REFERENCES "ADMP"."ADMP_TIPO_TAB" ("ID_TIPO") ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_DETALLE_TAB" ADD CONSTRAINT "ADMP_MEMO_DETALLE_FK_04" FOREIGN KEY ("ID_SUB_GENERO")
	  REFERENCES "ADMP"."ADMP_SUB_GENERO_TAB" ("ID_SUB_GENERO") ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_DETALLE_TAB" ADD CONSTRAINT "ADMP_MEMO_DETALLE_FK_06" FOREIGN KEY ("ID_ESTATUS")
	  REFERENCES "ADMP"."ADMP_ESTATUS_TAB" ("ID_ESTATUS") ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_DETALLE_TAB" ADD CONSTRAINT "ADMP_MEMO_DETALLE_FK_07" FOREIGN KEY ("ID_ORIGEN")
	  REFERENCES "ADMP"."ADMP_ORIGEN_TAB" ("ID_ORIGEN") ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_DETALLE_TAB" ADD CONSTRAINT "ADMP_MEMO_DETALLE_FK_09" FOREIGN KEY ("ID_CLASIFICACION")
	  REFERENCES "ADMP"."ADMP_CLASIFICACION_TAB" ("ID_CLASIFICACION") ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_DETALLE_TAB" ADD CONSTRAINT "ADMP_MEMO_DETALLE_FK_10" FOREIGN KEY ("ID_CLASE")
	  REFERENCES "ADMP"."ADMP_CLASE_TAB" ("ID_CLASE") ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_DETALLE_TAB" ADD CONSTRAINT "ADMP_MEMO_DETALLE_FK_11" FOREIGN KEY ("ID_RESTRICCION")
	  REFERENCES "ADMP"."ADMP_RESTRICCION_TAB" ("ID_RESTRICCION") ENABLE;
