CREATE TABLE "ADMP"."ADMP_CANAL_TAB" 
   (	"ID_CANAL" NUMBER NOT NULL ENABLE, 
	"DES_CANAL" VARCHAR2(100) NOT NULL ENABLE, 
	"DES_ACRONIMO" VARCHAR2(100), 
	"ID_ESTADO_REP" NUMBER, 
	"DES_DIRECCION1" VARCHAR2(500), 
	"DES_DIRECCION2" VARCHAR2(500), 
	"DES_EMAIL" VARCHAR2(250), 
	"NOM_CONTACTO" VARCHAR2(250), 
	"DES_TELEFONO" VARCHAR2(100), 
	"DES_FTP" VARCHAR2(100), 
	"DES_USUARIO_FTP" VARCHAR2(100), 
	"DES_CONTRASENA_FTP" VARCHAR2(150), 
	"NOM_IMAGEN1" VARCHAR2(250), 
	"NOM_IMAGEN2" VARCHAR2(250), 
	"DES_TITULO1" VARCHAR2(900), 
	"DES_TITULO2" VARCHAR2(900), 
	"ID_PLATAFORMA" NUMBER NOT NULL ENABLE, 
	"ID_ESTADO" NUMBER NOT NULL ENABLE, 
	"NUM_CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_CREATION_DATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_LAST_UPDATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATRIBUTO1" VARCHAR2(150), 
	"ATRIBUTO2" VARCHAR2(150), 
	"ATRIBUTO3" VARCHAR2(150), 
	"ATRIBUTO4" VARCHAR2(150), 
	"ATRIBUTO5" VARCHAR2(150), 
	"ATRIBUTO6" VARCHAR2(150), 
	"ATRIBUTO7" VARCHAR2(150), 
	"ATRIBUTO8" VARCHAR2(150), 
	"ATRIBUTO9" VARCHAR2(150), 
	"ATRIBUTO10" VARCHAR2(150), 
	"ATRIBUTO11" VARCHAR2(150), 
	"ATRIBUTO12" VARCHAR2(150), 
	"ATRIBUTO13" VARCHAR2(150), 
	"ATRIBUTO14" VARCHAR2(150), 
	"ATRIBUTO15" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150), 
	"COD_DELPHI" VARCHAR2(50)
   )   NO INMEMORY ;
  CREATE UNIQUE INDEX "ADMP"."ADMP_CANAL_PK" ON "ADMP"."ADMP_CANAL_TAB" ("ID_CANAL") 
  ;
ALTER TABLE "ADMP"."ADMP_CANAL_TAB" ADD CONSTRAINT "ADMP_CANAL_PK" PRIMARY KEY ("ID_CANAL")
  USING INDEX "ADMP"."ADMP_CANAL_PK"  ENABLE;
ALTER TABLE "ADMP"."ADMP_CANAL_TAB" ADD CONSTRAINT "ADMP_CANAL_FK_01" FOREIGN KEY ("ID_ESTADO_REP")
	  REFERENCES "ADMP"."ADMP_ESTADO_REP_TAB" ("ID_ESTADO_REP") ENABLE;
ALTER TABLE "ADMP"."ADMP_CANAL_TAB" ADD CONSTRAINT "ADMP_CANAL_FK_02" FOREIGN KEY ("ID_PLATAFORMA")
	  REFERENCES "ADMP"."ADMP_PLATAFORMA_TAB" ("ID_PLATAFORMA") ENABLE;
ALTER TABLE "ADMP"."ADMP_CANAL_TAB" ADD CONSTRAINT "ADMP_CANAL_FK_03" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "ADMP"."ADMP_ESTADO_TAB" ("ID_ESTADO") ENABLE;
