CREATE TABLE "ADMP"."ADMP_USUARIO_CANAL_TAB" 
   (	"ID_USUARIO_CANAL" NUMBER NOT NULL ENABLE, 
	"ID_USUARIO" NUMBER NOT NULL ENABLE, 
	"ID_CANAL" NUMBER NOT NULL ENABLE, 
	"ID_MODULO" NUMBER NOT NULL ENABLE, 
	"ID_PERMISO" NUMBER NOT NULL ENABLE, 
	"NUM_CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_CREATION_DATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_LAST_UPDATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATRIBUTO1" VARCHAR2(150), 
	"ATRIBUTO2" VARCHAR2(150), 
	"ATRIBUTO3" VARCHAR2(150), 
	"ATRIBUTO4" VARCHAR2(150), 
	"ATRIBUTO5" VARCHAR2(150), 
	"ATRIBUTO6" VARCHAR2(150), 
	"ATRIBUTO7" VARCHAR2(150), 
	"ATRIBUTO8" VARCHAR2(150), 
	"ATRIBUTO9" VARCHAR2(150), 
	"ATRIBUTO10" VARCHAR2(150), 
	"ATRIBUTO11" VARCHAR2(150), 
	"ATRIBUTO12" VARCHAR2(150), 
	"ATRIBUTO13" VARCHAR2(150), 
	"ATRIBUTO14" VARCHAR2(150), 
	"ATRIBUTO15" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150)
   )   NO INMEMORY ;
  CREATE UNIQUE INDEX "ADMP"."ADMP_USUARIO_CANAL_PK" ON "ADMP"."ADMP_USUARIO_CANAL_TAB" ("ID_USUARIO_CANAL") 
  ;
ALTER TABLE "ADMP"."ADMP_USUARIO_CANAL_TAB" ADD CONSTRAINT "ADMP_USUARIO_CANAL_PK" PRIMARY KEY ("ID_USUARIO_CANAL")
  USING INDEX "ADMP"."ADMP_USUARIO_CANAL_PK"  ENABLE;
ALTER TABLE "ADMP"."ADMP_USUARIO_CANAL_TAB" ADD CONSTRAINT "ADMP_USUARIO_CANAL_FK_01" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ADMP"."ADMP_USUARIO_TAB" ("ID_USUARIO") ENABLE;
ALTER TABLE "ADMP"."ADMP_USUARIO_CANAL_TAB" ADD CONSTRAINT "ADMP_USUARIO_CANAL_FK_02" FOREIGN KEY ("ID_CANAL")
	  REFERENCES "ADMP"."ADMP_CANAL_TAB" ("ID_CANAL") ENABLE;
ALTER TABLE "ADMP"."ADMP_USUARIO_CANAL_TAB" ADD CONSTRAINT "ADMP_USUARIO_CANAL_FK_03" FOREIGN KEY ("ID_MODULO")
	  REFERENCES "ADMP"."ADMP_MODULO_TAB" ("ID_MODULO") ENABLE;
ALTER TABLE "ADMP"."ADMP_USUARIO_CANAL_TAB" ADD CONSTRAINT "ADMP_USUARIO_CANAL_FK_04" FOREIGN KEY ("ID_PERMISO")
	  REFERENCES "ADMP"."ADMP_PERMISO_TAB" ("ID_PERMISO") ENABLE;
