CREATE TABLE "ADMP"."ADMP_MEMO_TAB" 
   (	"ID_MEMO" NUMBER NOT NULL ENABLE, 
	"COD_MEMO" VARCHAR2(50), 
	"ID_CORREO_REMITENTE" NUMBER, 
	"DES_REMITENTE" VARCHAR2(100), 
	"DES_REMITENTE_PUESTO" VARCHAR2(100), 
	"ID_CORREO_DESTINATARIO" NUMBER, 
	"DES_DESTINATARIO" VARCHAR2(100), 
	"DES_DESTINATARIO_PUESTO" VARCHAR2(100), 
	"FEC_FECHA_MEMO" DATE NOT NULL ENABLE, 
	"ID_USUARIO" NUMBER NOT NULL ENABLE, 
	"DES_ASUNTO" VARCHAR2(500), 
	"ID_ESTADO" NUMBER NOT NULL ENABLE, 
	"ID_CANAL" NUMBER NOT NULL ENABLE, 
	"NUM_AGRUPADOR" NUMBER, 
	"FEC_ENVIO" DATE, 
	"NUM_ENVIADO" NUMBER(1,0), 
	"NUM_CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_CREATION_DATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_LAST_UPDATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATRIBUTO1" VARCHAR2(150), 
	"ATRIBUTO2" VARCHAR2(150), 
	"ATRIBUTO3" VARCHAR2(150), 
	"ATRIBUTO4" VARCHAR2(150), 
	"ATRIBUTO5" VARCHAR2(150), 
	"ATRIBUTO6" VARCHAR2(150), 
	"ATRIBUTO7" VARCHAR2(150), 
	"ATRIBUTO8" VARCHAR2(150), 
	"ATRIBUTO9" VARCHAR2(150), 
	"ATRIBUTO10" VARCHAR2(150), 
	"ATRIBUTO11" VARCHAR2(150), 
	"ATRIBUTO12" VARCHAR2(150), 
	"ATRIBUTO13" VARCHAR2(150), 
	"ATRIBUTO14" VARCHAR2(150), 
	"ATRIBUTO15" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150), 
	"BL_MEMO_DETALLE" BLOB, 
	"DES_ARCHIVO" VARCHAR2(50), 
	"DES_CUERPO" CLOB DEFAULT EMPTY_CLOB(), 
	"DES_REFERENCIA" VARCHAR2(50)
   )   NO INMEMORY 
 LOB ("BL_MEMO_DETALLE") STORE AS BASICFILE "SYS_LOB0000110236C00038$$"(ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) 
 LOB ("DES_CUERPO") STORE AS BASICFILE "SYS_LOB0000110236C00040$$"(ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
  CREATE UNIQUE INDEX "ADMP"."ADMP_MEMO_PK" ON "ADMP"."ADMP_MEMO_TAB" ("ID_MEMO") 
  ;
ALTER TABLE "ADMP"."ADMP_MEMO_TAB" ADD CONSTRAINT "ADMP_MEMO_PK" PRIMARY KEY ("ID_MEMO")
  USING INDEX "ADMP"."ADMP_MEMO_PK"  ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_TAB" ADD CONSTRAINT "ADMP_MEMO_FK_01" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "ADMP"."ADMP_USUARIO_TAB" ("ID_USUARIO") ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_TAB" ADD CONSTRAINT "ADMP_MEMO_FK_02" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "ADMP"."ADMP_ESTADO_TAB" ("ID_ESTADO") ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_TAB" ADD CONSTRAINT "ADMP_MEMO_FK_03" FOREIGN KEY ("ID_CANAL")
	  REFERENCES "ADMP"."ADMP_CANAL_TAB" ("ID_CANAL") ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_TAB" ADD CONSTRAINT "ADMP_MEMO_FK_04" FOREIGN KEY ("ID_CORREO_REMITENTE")
	  REFERENCES "ADMP"."ADMP_CORREO_TAB" ("ID_CORREO") ENABLE;
ALTER TABLE "ADMP"."ADMP_MEMO_TAB" ADD CONSTRAINT "ADMP_MEMO_FK_05" FOREIGN KEY ("ID_CORREO_DESTINATARIO")
	  REFERENCES "ADMP"."ADMP_CORREO_TAB" ("ID_CORREO") ENABLE;
