CREATE TABLE "ADMP"."ADMP_ORIGEN_TAB" 
   (	"ID_ORIGEN" NUMBER NOT NULL ENABLE, 
	"DES_ORIGEN" VARCHAR2(100) NOT NULL ENABLE, 
	"ID_ESTADO" NUMBER NOT NULL ENABLE, 
	"NUM_CREATED_BY" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_CREATION_DATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE" NUMBER(15,0) NOT NULL ENABLE, 
	"FEC_LAST_UPDATE" DATE NOT NULL ENABLE, 
	"NUM_LAST_UPDATE_LOGIN" NUMBER(15,0), 
	"ATRIBUTO1" VARCHAR2(150), 
	"ATRIBUTO2" VARCHAR2(150), 
	"ATRIBUTO3" VARCHAR2(150), 
	"ATRIBUTO4" VARCHAR2(150), 
	"ATRIBUTO5" VARCHAR2(150), 
	"ATRIBUTO6" VARCHAR2(150), 
	"ATRIBUTO7" VARCHAR2(150), 
	"ATRIBUTO8" VARCHAR2(150), 
	"ATRIBUTO9" VARCHAR2(150), 
	"ATRIBUTO10" VARCHAR2(150), 
	"ATRIBUTO11" VARCHAR2(150), 
	"ATRIBUTO12" VARCHAR2(150), 
	"ATRIBUTO13" VARCHAR2(150), 
	"ATRIBUTO14" VARCHAR2(150), 
	"ATRIBUTO15" VARCHAR2(150), 
	"ATTRIBUTE_CATEGORY" VARCHAR2(150)
   )   NO INMEMORY ;
  CREATE UNIQUE INDEX "ADMP"."ADMP_ORIGEN_PK" ON "ADMP"."ADMP_ORIGEN_TAB" ("ID_ORIGEN") 
  ;
ALTER TABLE "ADMP"."ADMP_ORIGEN_TAB" ADD CONSTRAINT "ADMP_ORIGEN_PK" PRIMARY KEY ("ID_ORIGEN")
  USING INDEX "ADMP"."ADMP_ORIGEN_PK"  ENABLE;
ALTER TABLE "ADMP"."ADMP_ORIGEN_TAB" ADD CONSTRAINT "ADMP_ORIGEN_FK_01" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "ADMP"."ADMP_ESTADO_TAB" ("ID_ESTADO") ENABLE;
