CREATE TABLE "XXMOR"."PS_TXN" 
   (	"ID" NUMBER(20,0), 
	"PARENTID" NUMBER(20,0), 
	"COLLID" NUMBER(10,0), 
	"CONTENT" BLOB, 
	"CREATION_DATE" DATE DEFAULT sysdate
   ) ;
ALTER TABLE "XXMOR"."PS_TXN" ADD CONSTRAINT "PS_TXN_PK" PRIMARY KEY ("COLLID", "ID")
  USING INDEX (CREATE INDEX "XXMOR"."PS_TXN_IDX" ON "XXMOR"."PS_TXN" ("COLLID", "ID") REVERSE 
  )  ENABLE;
