CREATE TABLE "XXMOR"."XXLMK_AGRUPADOR_SOLICITUD_TAB" 
   (	"ID_SOLICITUD" NUMBER(15,0) NOT NULL ENABLE, 
	"AGRUPADOR" VARCHAR2(10) NOT NULL ENABLE, 
	"CREATED_DATE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(20)
   ) ;
