CREATE TABLE "XXMOR"."XXLMK_RECOL_SPOTS_FILE_TAB" 
   (	"ID_RECOL_SPOTS" NUMBER(38,0) NOT NULL ENABLE, 
	"NOM_FILE" VARCHAR2(500), 
	"TYPE" VARCHAR2(4), 
	"IND_STATUS" VARCHAR2(1), 
	"DES_ERROR" VARCHAR2(500)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_RECOL_SPOTS_FILE_TAB" ADD CONSTRAINT "XXLMK_RECOL_SPOTS_FILE_TAB_PK" PRIMARY KEY ("ID_RECOL_SPOTS")
  USING INDEX  ENABLE;
