CREATE TABLE "XXMOR"."XXLMK_ERRORES_ARCH_TAB" 
   (	"ID_ERROR" NUMBER NOT NULL ENABLE, 
	"ID_ARCHIVO" NUMBER, 
	"COD_TIPO_ARCHIVO" VARCHAR2(10), 
	"NOM_ORDEN" VARCHAR2(50), 
	"CVE_POSICION" VARCHAR2(1), 
	"NUM_LINEA" NUMBER, 
	"DES_ERROR" VARCHAR2(4000), 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(20), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(20)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_ERRORES_ARCH_TAB" ADD CONSTRAINT "XXLMK_ERRORES_ARCH_TAB_PK" PRIMARY KEY ("ID_ERROR")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_ERRORES_ARCH_TAB" ADD CONSTRAINT "XXLMK_ERRORES_ARCH_TAB_FK01" FOREIGN KEY ("ID_ARCHIVO")
	  REFERENCES "XXMOR"."XXLMK_ARCHIVOS_SOL_TAB" ("ID_ARCHIVO_SOL") ENABLE;
