CREATE TABLE "XXMOR"."XXLMK_ERRS_BOOK_SPOTS_TAB" 
   (	"ID_ERROR" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_SPOT" NUMBER(*,0), 
	"NUM_MSG" NUMBER(*,0), 
	"DES_MSG" VARCHAR2(4000), 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_ERRS_BOOK_SPOTS_TAB" ADD PRIMARY KEY ("ID_ERROR")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_ERRS_BOOK_SPOTS_TAB" ADD CONSTRAINT "XXLMKERRSBOOKSPOTSTAB_FK_01" FOREIGN KEY ("ID_SPOT")
	  REFERENCES "XXMOR"."XXLMK_LINEAS_SPOTS_TAB" ("ID_SPOT") ENABLE;
