CREATE TABLE "XXMOR"."XXLMK_PARAMETROS_TAB" 
   (	"ID_PARAMETRO" NUMBER NOT NULL ENABLE, 
	"NOM_PARAMETRO" VARCHAR2(50) NOT NULL ENABLE, 
	"DES_VALOR" VARCHAR2(4000) NOT NULL ENABLE, 
	"DES_PARAMETRO" VARCHAR2(4000), 
	"IND_TIPO" NUMBER, 
	"IND_CIFRADO" NUMBER, 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(50), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(50)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_PARAMETROS_TAB" ADD CONSTRAINT "XXLMK_PARAMETROS_TAB_PK" PRIMARY KEY ("ID_PARAMETRO")
  USING INDEX  ENABLE;
