CREATE TABLE "XXMOR"."XXLMK_CORREOS_NOTIF_TAB" 
   (	"ID_CORREO_NOTIF" NUMBER NOT NULL ENABLE, 
	"ID_GRUPO_NOTIF" NUMBER NOT NULL ENABLE, 
	"DES_CORREO_NOTIF" VARCHAR2(200), 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_CORREOS_NOTIF_TAB" ADD PRIMARY KEY ("ID_CORREO_NOTIF")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_CORREOS_NOTIF_TAB" ADD CONSTRAINT "XXLMK_CORREOS_NOTIF_TAB_FK_01" FOREIGN KEY ("ID_GRUPO_NOTIF")
	  REFERENCES "XXMOR"."XXLMK_GRUPOS_NOTIF_TAB" ("ID_GRUPO_NOTIF") ENABLE;
