CREATE TABLE "XXMOR"."XXLMK_NOTIF_ELEM_TAB" 
   (	"ID_NOTIF_ELEM" NUMBER NOT NULL ENABLE, 
	"ID_GRUPO_NOTIF" NUMBER NOT NULL ENABLE, 
	"NOM_ELEM" VARCHAR2(200), 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_NOTIF_ELEM_TAB" ADD PRIMARY KEY ("ID_NOTIF_ELEM")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_NOTIF_ELEM_TAB" ADD CONSTRAINT "XXLMK_NOTIF_ELEM_TAB_FK_01" FOREIGN KEY ("ID_GRUPO_NOTIF")
	  REFERENCES "XXMOR"."XXLMK_GRUPOS_NOTIF_TAB" ("ID_GRUPO_NOTIF") ENABLE;
