CREATE TABLE "XXMOR"."XXLMK_ERRS_AJUS_CAN_TAB" 
   (	"ID_ERROR" NUMBER(*,0), 
	"ID_AJUSTE_BREAKS" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_CANAL" NUMBER(*,0) NOT NULL ENABLE, 
	"DES_ERROR" VARCHAR2(1000), 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_ERRS_AJUS_CAN_TAB" ADD PRIMARY KEY ("ID_ERROR")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_ERRS_AJUS_CAN_TAB" ADD CONSTRAINT "XXLMKERRSAJUSCANTAB_FK1" FOREIGN KEY ("ID_AJUSTE_BREAKS", "ID_CANAL")
	  REFERENCES "XXMOR"."XXLMK_AJUS_BRKS_CANALES_TAB" ("ID_AJUSTE_BREAKS", "ID_CANAL") ENABLE;
