CREATE TABLE "XXMOR"."XXLMK_CRED_CORP_TAB" 
   (	"ID_SOL_CC" NUMBER NOT NULL ENABLE, 
	"ID_AUT" NUMBER NOT NULL ENABLE, 
	"IND_RECHAZO_GESTOR" NUMBER, 
	"ID_MOTIVO_AR" NUMBER, 
	"DES_COMENT_AR_CC" VARCHAR2(4000)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_CRED_CORP_TAB" ADD CONSTRAINT "XXLMK_CRED_CORP_TAB_PK" PRIMARY KEY ("ID_SOL_CC")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_CRED_CORP_TAB" ADD CONSTRAINT "XXLMK_CRED_CORP_TAB_FK1" FOREIGN KEY ("ID_AUT")
	  REFERENCES "XXMOR"."XXLMK_AUTORIZACIONES_TAB" ("ID_AUT") ENABLE;
