CREATE TABLE "XXMOR"."XXLMK_INCONSISTENT_SPOTS_TAB" 
   (	"ID_INCONSISTENT_SPOT" NUMBER(38,0) NOT NULL ENABLE, 
	"ID_ORDHDR" NUMBER(38,0), 
	"NUM_SPOT" NUMBER(38,0), 
	"IND_CANCELED" NUMBER(1,0)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_INCONSISTENT_SPOTS_TAB" ADD CONSTRAINT "XXLMK_INCONSISTENT_SPOTS_TAB_XXLMK_ORDHDR_TAB_FK" FOREIGN KEY ("ID_ORDHDR")
	  REFERENCES "XXMOR"."XXLMK_ORDHDR_TAB" ("ID_ORDHDR") ENABLE;
