CREATE TABLE "XXMOR"."XXLMK_ERRS_CANCEL_SPOTS_TAB" 
   (	"ID_SPOT_CANCELADO" NUMBER(*,0) NOT NULL ENABLE, 
	"NUM_MSG" NUMBER(*,0), 
	"DES_MSG" VARCHAR2(4000), 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_ERRS_CANCEL_SPOTS_TAB" ADD CONSTRAINT "XXLMKERRSCANCELSPOTSTAB_FK1" FOREIGN KEY ("ID_SPOT_CANCELADO")
	  REFERENCES "XXMOR"."XXLMK_SPOTS_CANCELADOS_TAB" ("ID_SPOT_CANCELADO") ENABLE;
