CREATE TABLE "XXMOR"."XXLMK_CAN_EXCEPT_DUR_TAB" 
   (	"ID_EXCEPT" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_GRUPO" NUMBER(*,0) NOT NULL ENABLE, 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_CAN_EXCEPT_DUR_TAB" ADD PRIMARY KEY ("ID_EXCEPT")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_CAN_EXCEPT_DUR_TAB" ADD CONSTRAINT "XXLMKCANEXCEPTDURTAB_FK1" FOREIGN KEY ("ID_GRUPO")
	  REFERENCES "XXMOR"."XXLMK_GRUPOS_CANALES_TAB" ("ID_GRUPO") ENABLE;
