CREATE TABLE "XXMOR"."XXLMK_ERRS_RECOL_SPOTS_TAB" 
   (	"ID_SPOT" NUMBER(*,0) NOT NULL ENABLE, 
	"NUM_SPOT" NUMBER(*,0) NOT NULL ENABLE, 
	"DES_ERROR" VARCHAR2(1000), 
	"DES_BREAKS" VARCHAR2(1500), 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100), 
	"NUM_MSG_ERR" VARCHAR2(20)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_ERRS_RECOL_SPOTS_TAB" ADD CONSTRAINT "XXLMKERRSRECOLSPOTS_FK1" FOREIGN KEY ("ID_SPOT")
	  REFERENCES "XXMOR"."XXLMK_LINEAS_SPOTS_TAB" ("ID_SPOT") ENABLE;
