CREATE TABLE "XXMOR"."XXLMK_ERRS_CREATE_CAMP_TAB" 
   (	"ID_ERROR" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_ORDHDR" NUMBER(*,0) NOT NULL ENABLE, 
	"NUM_ERROR" NUMBER(*,0), 
	"DES_SEVERITY" VARCHAR2(50), 
	"DES_ERROR" VARCHAR2(1000), 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_ERRS_CREATE_CAMP_TAB" ADD PRIMARY KEY ("ID_ERROR")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_ERRS_CREATE_CAMP_TAB" ADD CONSTRAINT "XXLMKERRSCREATECAMPTAB_FK1" FOREIGN KEY ("ID_ORDHDR")
	  REFERENCES "XXMOR"."XXLMK_ORDHDR_TAB" ("ID_ORDHDR") ENABLE;
