CREATE TABLE "XXMOR"."XXLMK_UNIVERSOS_LMK_TAB" 
   (	"NUM_SARE" NUMBER(*,0), 
	"NUM_DEMO" NUMBER(*,0), 
	"FEC_UNI" DATE, 
	"NUM_UNI" NUMBER, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_CREACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE
   ) ;
