CREATE TABLE "XXMOR"."XXLMK_OSMOD_CONF_CANS_TAB" 
   (	"ID_ORDHDR" NUMBER(*,0) NOT NULL ENABLE, 
	"NUM_GRUPO" NUMBER(*,0) NOT NULL ENABLE, 
	"NOM_CANAL" VARCHAR2(100), 
	"IND_NETWORK" NUMBER(*,0), 
	"IND_SKY" NUMBER(*,0), 
	"IND_IZZI" NUMBER(*,0), 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_OSMOD_CONF_CANS_TAB" ADD PRIMARY KEY ("ID_ORDHDR", "NUM_GRUPO", "NOM_CANAL")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_OSMOD_CONF_CANS_TAB" ADD CONSTRAINT "XXLMKOSMODCONFCANSTAB_FK1" FOREIGN KEY ("ID_ORDHDR", "NUM_GRUPO")
	  REFERENCES "XXMOR"."XXLMK_OSMOD_GRUP_CANS_TAB" ("ID_ORDHDR", "NUM_GRUPO") ENABLE;
