CREATE TABLE "XXMOR"."XXLMK_CAN_EXCEPT_DATE_TAB" 
   (	"ID_EXCEPT" NUMBER(*,0) NOT NULL ENABLE, 
	"FEC_EXCEPT" DATE NOT NULL ENABLE, 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_CAN_EXCEPT_DATE_TAB" ADD PRIMARY KEY ("ID_EXCEPT", "FEC_EXCEPT")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_CAN_EXCEPT_DATE_TAB" ADD CONSTRAINT "XXLMKCANEXCEPTDATETAB_FK1" FOREIGN KEY ("ID_EXCEPT")
	  REFERENCES "XXMOR"."XXLMK_CAN_EXCEPT_DUR_TAB" ("ID_EXCEPT") ENABLE;
