CREATE TABLE "XXMOR"."XXLMK_CANCELACION_SPOTS_TAB" 
   (	"ID_CANCELACION" NUMBER(*,0) NOT NULL ENABLE, 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100), 
	"NOM_ARCHIVO" VARCHAR2(100), 
	"DES_ARCHIVO" BLOB, 
	"IND_ESTATUS" NUMBER(*,0)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_CANCELACION_SPOTS_TAB" ADD PRIMARY KEY ("ID_CANCELACION")
  USING INDEX  ENABLE;
