CREATE TABLE "XXMOR"."XXLMK_AJUS_BRKS_CANALES_TAB" 
   (	"ID_AJUSTE_BREAKS" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_CANAL" NUMBER(*,0) NOT NULL ENABLE, 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100), 
	"DES_ARCHIVO" BLOB, 
	"NOM_ARCHIVO" VARCHAR2(100), 
	"IND_ESTATUS" NUMBER(*,0)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_AJUS_BRKS_CANALES_TAB" ADD PRIMARY KEY ("ID_AJUSTE_BREAKS", "ID_CANAL")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_AJUS_BRKS_CANALES_TAB" ADD CONSTRAINT "XXLMKAJUSBRKSCANALESTAB_FK1" FOREIGN KEY ("ID_AJUSTE_BREAKS")
	  REFERENCES "XXMOR"."XXLMK_AJUSTE_BREAKS_TAB" ("ID_AJUSTE_BREAKS") ENABLE;
ALTER TABLE "XXMOR"."XXLMK_AJUS_BRKS_CANALES_TAB" ADD CONSTRAINT "XXLMKAJUSBRKSCANALESTAB_FK2" FOREIGN KEY ("ID_CANAL")
	  REFERENCES "XXMOR"."XXLMK_CANALES_LMK_TAB" ("ID_CANAL") ENABLE;
