CREATE TABLE "XXMOR"."XXLMK_CANALES_NACIONAL_TAB" 
   (	"ID_CANAL" NUMBER NOT NULL ENABLE, 
	"NOM_CANAL" VARCHAR2(20), 
	"IND_ACTIVO" NUMBER, 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(20)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_CANALES_NACIONAL_TAB" ADD CONSTRAINT "XXLMK_CANALES_NACIONAL_TAB_PK" PRIMARY KEY ("ID_CANAL")
  USING INDEX  ENABLE;
