CREATE TABLE "XXMOR"."XXLMK_CORREOS_FMT_VERS_TAB" 
   (	"ID_CORREO" NUMBER(*,0) NOT NULL ENABLE, 
	"DES_CORREO" VARCHAR2(100), 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_CORREOS_FMT_VERS_TAB" ADD PRIMARY KEY ("ID_CORREO")
  USING INDEX  ENABLE;
