CREATE TABLE "XXMOR"."XXLMK_GRUPOS_CANALES_TAB" 
   (	"ID_GRUPO" NUMBER(*,0) NOT NULL ENABLE, 
	"NUM_DURACION" NUMBER(*,0), 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100), 
	"NOM_GRUPO" VARCHAR2(20)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_GRUPOS_CANALES_TAB" ADD PRIMARY KEY ("ID_GRUPO")
  USING INDEX  ENABLE;
