CREATE TABLE "XXMOR"."XXLMK_CAMP_ENV_TAB" 
   (	"ID_CAMP_ENV" NUMBER NOT NULL ENABLE, 
	"ID_ORDHDR" NUMBER NOT NULL ENABLE, 
	"NUM_CAMP" NUMBER NOT NULL ENABLE, 
	"IND_ESTATUS" VARCHAR2(10), 
	"DES_TIPO_SERVICIO" VARCHAR2(200), 
	"FEC CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100), 
	"NUM_APROV_KEY_ID" NUMBER(*,0), 
	"NUM_DEAL" NUMBER(*,0), 
	"FEC_INI_CAMP" DATE, 
	"FEC_FIN_CAMP" DATE, 
	"NUM_PRODUCT" NUMBER(*,0), 
	"DES_CAMP_REQ" CLOB, 
	"VAL_REV_BUDGET" NUMBER, 
	"VAL_BUDGET_NO_COL" NUMBER(*,0), 
	"NUM_PREEMPTION_STATUS" NUMBER(*,0), 
	"NUM_PREEMPTOR_STATUS" NUMBER(*,0), 
	"NUM_USER_PREEMPTS" NUMBER(*,0), 
	"IND_ACCIONES_ESPECIALES" NUMBER(*,0) DEFAULT 0, 
	"IND_NON_PREEMPTIBLE" NUMBER(*,0) DEFAULT 0
   ) ;
ALTER TABLE "XXMOR"."XXLMK_CAMP_ENV_TAB" ADD PRIMARY KEY ("ID_CAMP_ENV")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_CAMP_ENV_TAB" ADD CONSTRAINT "XXLMK_CAMP_ENV_TAB_IX2" UNIQUE ("NUM_CAMP")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_CAMP_ENV_TAB" ADD CONSTRAINT "XXLMK_CAMP_ENV_TAB_FK_01" FOREIGN KEY ("ID_ORDHDR")
	  REFERENCES "XXMOR"."XXLMK_ORDHDR_TAB" ("ID_ORDHDR") ENABLE;
