CREATE TABLE "XXMOR"."XXLMK_BOOK_RULE_CONFIG_TAB" 
   (	"ID_CONFIG" NUMBER(38,0) NOT NULL ENABLE, 
	"NOM_CONFIG" VARCHAR2(100), 
	"ID_PLATFORM" NUMBER(38,0), 
	"ID_ROUND" VARCHAR2(2), 
	"NUM_PERC_ALEATORY1" NUMBER(38,0) DEFAULT 0, 
	"NUM_PERC_ALEATORY2" NUMBER(38,0) DEFAULT 0
   ) ;
ALTER TABLE "XXMOR"."XXLMK_BOOK_RULE_CONFIG_TAB" ADD CONSTRAINT "XXLMK_BOOK_RULE_CONFIG_TAB_PK" PRIMARY KEY ("ID_CONFIG")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_BOOK_RULE_CONFIG_TAB" ADD CONSTRAINT "XXLMK_BOOK_RULE_CONFIG_TAB_XXLMK_PLATFORMS_TAB_FK" FOREIGN KEY ("ID_PLATFORM")
	  REFERENCES "XXMOR"."XXLMK_PLATFORMS_TAB" ("ID_PLATFORM") ENABLE;
