CREATE TABLE "XXMOR"."XXLMK_CONFIG_RULES_TAB" 
   (	"ID_CONFIG" NUMBER(38,0) NOT NULL ENABLE, 
	"ID_RULE" NUMBER(38,0) NOT NULL ENABLE, 
	"NUM_ORDEN" NUMBER(38,0)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_CONFIG_RULES_TAB" ADD CONSTRAINT "XXLMK_CONFIG_RULES_TAB_PK" PRIMARY KEY ("ID_CONFIG", "ID_RULE")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_CONFIG_RULES_TAB" ADD CONSTRAINT "XXLMK_CONFIG_RULES_TAB_XXLMK_BOOK_RULE_CONFIG_TAB_FK" FOREIGN KEY ("ID_CONFIG")
	  REFERENCES "XXMOR"."XXLMK_BOOK_RULE_CONFIG_TAB" ("ID_CONFIG") ENABLE;
ALTER TABLE "XXMOR"."XXLMK_CONFIG_RULES_TAB" ADD CONSTRAINT "XXLMK_CONFIG_RULES_TAB_XXLMK_BOOK_RULES_TAB_FK" FOREIGN KEY ("ID_RULE")
	  REFERENCES "XXMOR"."XXLMK_BOOK_RULES_TAB" ("ID_RULE") ENABLE;
