CREATE TABLE "XXMOR"."XXLMK_CREDITO_CORPORATIVO_TAB" 
   (	"ID_SOL_CC" NUMBER NOT NULL ENABLE, 
	"ID_ORDEN" NUMBER NOT NULL ENABLE, 
	"IND_ESTATUS" NUMBER, 
	"IND_RECHAZO_GESTOR" NUMBER, 
	"ID_MOTIVO_AR_CC" NUMBER, 
	"DES_COMENT_AR_CC" VARCHAR2(2000), 
	"NUM_CARGA" NUMBER, 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_CREDITO_CORPORATIVO_TAB" ADD CONSTRAINT "XXLMK_CREDITO_CORPORATIVO__PK" PRIMARY KEY ("ID_SOL_CC")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_CREDITO_CORPORATIVO_TAB" ADD CONSTRAINT "XXLMK_CREDITO_CORPORATIVO_FK1" FOREIGN KEY ("ID_ORDEN")
	  REFERENCES "XXMOR"."XXLMK_ORDHDR_TAB" ("ID_ORDHDR") ENABLE;
