CREATE TABLE "XXMOR"."XXLMK_ARCHIVOS_SOL_TAB" 
   (	"ID_ARCHIVO_SOL" NUMBER NOT NULL ENABLE, 
	"NOM_ARCHIVO_SOL" VARCHAR2(100), 
	"DES_ARCHIVO_SOL" BLOB, 
	"IND_TIPO" NUMBER, 
	"NUM_ORDENES" NUMBER, 
	"IND_ESTATUS" NUMBER, 
	"IND_ENVIADO_WS" NUMBER, 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_ARCHIVOS_SOL_TAB" ADD CONSTRAINT "XXLMK_SOLICITUDES_ARCH_TAB_PK" PRIMARY KEY ("ID_ARCHIVO_SOL")
  USING INDEX  ENABLE;
