CREATE TABLE "XXMOR"."XXLMK_SMOD_GRUP_CANS_TAB" 
   (	"ID_GRUPO" NUMBER(*,0) NOT NULL ENABLE, 
	"NOM_GRUPO" VARCHAR2(100) NOT NULL ENABLE, 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_SMOD_GRUP_CANS_TAB" ADD PRIMARY KEY ("ID_GRUPO")
  USING INDEX  ENABLE;
