CREATE TABLE "XXMOR"."XXLMK_TARGETS_PSP_LMK_TAB" 
   (	"ID_TARGET" NUMBER(*,0), 
	"DES_TARGET_SHORT" VARCHAR2(100), 
	"NUM_DEMOG_LMK" NUMBER(*,0), 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_TARGETS_PSP_LMK_TAB" ADD PRIMARY KEY ("ID_TARGET")
  USING INDEX  ENABLE;
