CREATE TABLE "XXMOR"."XXLMK_CLIENTES_VAL_MCONT_TAB" 
   (	"ID_CLIENTE" NUMBER(*,0) NOT NULL ENABLE, 
	"NOM_CLIENTE" VARCHAR2(20), 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100), 
	"NUM_PRODUCT" NUMBER
   ) ;
ALTER TABLE "XXMOR"."XXLMK_CLIENTES_VAL_MCONT_TAB" ADD PRIMARY KEY ("ID_CLIENTE")
  USING INDEX  ENABLE;
