CREATE TABLE "XXMOR"."XXLMK_AGRUPADORES_PSP_TAB" 
   (	"ID_AGRUPADOR_PSP" NUMBER NOT NULL ENABLE, 
	"NOM_AGRUPADOR" VARCHAR2(20) NOT NULL ENABLE, 
	"IND_ACTIVO" NUMBER, 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_AGRUPADORES_PSP_TAB" ADD PRIMARY KEY ("ID_AGRUPADOR_PSP")
  USING INDEX  ENABLE;
