CREATE TABLE "XXMOR"."XXLMK_DIST_COST_DAYP_TAB" 
   (	"ID_ORDHDR" NUMBER(*,0) NOT NULL ENABLE, 
	"DES_CANAL" VARCHAR2(5), 
	"DES_FRANJA" VARCHAR2(3), 
	"DES_DIAS" VARCHAR2(2), 
	"NUM_PORC" NUMBER, 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_DIST_COST_DAYP_TAB" ADD PRIMARY KEY ("ID_ORDHDR", "DES_CANAL", "DES_FRANJA", "DES_DIAS")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_DIST_COST_DAYP_TAB" ADD CONSTRAINT "XXLMKDISTCOSTDAYPTAB_FK1" FOREIGN KEY ("ID_ORDHDR")
	  REFERENCES "XXMOR"."XXLMK_ORDHDR_TAB" ("ID_ORDHDR") ENABLE;
