CREATE TABLE "XXMOR"."XXLMK_GRUPOS_NOTIF_TAB" 
   (	"ID_GRUPO_NOTIF" NUMBER NOT NULL ENABLE, 
	"NOM_GRUPO" VARCHAR2(200), 
	"IND_TIPO" VARCHAR2(20), 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100)
   ) ;
ALTER TABLE "XXMOR"."XXLMK_GRUPOS_NOTIF_TAB" ADD PRIMARY KEY ("ID_GRUPO_NOTIF")
  USING INDEX  ENABLE;
