CREATE TABLE "XXMOR"."XXLMK_ERRORES_ORDS_TAB" 
   (	"ID_ERROR" NUMBER NOT NULL ENABLE, 
	"DES_ERROR" VARCHAR2(2000), 
	"FEC_CREACION" DATE, 
	"CVE_CREADO_POR" VARCHAR2(100), 
	"FEC_ACTUALIZACION" DATE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(100), 
	"ID_ORDHDR" NUMBER
   ) ;
ALTER TABLE "XXMOR"."XXLMK_ERRORES_ORDS_TAB" ADD CONSTRAINT "XXLMK_ERRORES_ORDS_TAB_PK" PRIMARY KEY ("ID_ERROR")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXLMK_ERRORES_ORDS_TAB" ADD CONSTRAINT "XXLMK_ERRORES_ORDS_TAB_FK1" FOREIGN KEY ("ID_ORDHDR")
	  REFERENCES "XXMOR"."XXLMK_ORDHDR_TAB" ("ID_ORDHDR") ENABLE;
