CREATE TABLE "XXMOR"."XXMOR_FZAS_VTAS_MULT_TAB" 
   (	"ID_SEG_NEG" NUMBER NOT NULL ENABLE, 
	"ID_FZA_VENTAS" NUMBER NOT NULL ENABLE, 
	"ID_SEG_NEG_HIJO" NUMBER, 
	"ID_FZA_VENTAS_HIJA" NUMBER
   ) ;
ALTER TABLE "XXMOR"."XXMOR_FZAS_VTAS_MULT_TAB" ADD CONSTRAINT "XXMOR_FZAS_VTAS_MULT_TAB_PK" PRIMARY KEY ("ID_SEG_NEG", "ID_FZA_VENTAS")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXMOR_FZAS_VTAS_MULT_TAB" ADD CONSTRAINT "FK_Fza_Ventas_Mult" FOREIGN KEY ("ID_SEG_NEG", "ID_FZA_VENTAS")
	  REFERENCES "XXMOR"."XXMOR_FZAS_VTAS_TAB" ("ID_SEG_NEG", "ID_FZA_VENTAS") ENABLE;
ALTER TABLE "XXMOR"."XXMOR_FZAS_VTAS_MULT_TAB" ADD CONSTRAINT "FK_Fzas_Ventas_Mult_2" FOREIGN KEY ("ID_SEG_NEG_HIJO", "ID_FZA_VENTAS_HIJA")
	  REFERENCES "XXMOR"."XXMOR_FZAS_VTAS_TAB" ("ID_SEG_NEG", "ID_FZA_VENTAS") ENABLE;
