CREATE TABLE "XXMOR"."XXMOR_CONF_ORDS_URGENTES_TAB" 
   (	"ID_SEG_NEG" NUMBER NOT NULL ENABLE, 
	"ID_FZA_VENTAS" NUMBER NOT NULL ENABLE, 
	"DIA" NUMBER(1,0) NOT NULL ENABLE, 
	"DIA_CIERRE" NUMBER(1,0) NOT NULL ENABLE, 
	"HORA_CIERRE" DATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(20) NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(20)
   ) ;
ALTER TABLE "XXMOR"."XXMOR_CONF_ORDS_URGENTES_TAB" ADD CONSTRAINT "CKC_DIA_XXMOR_CO" CHECK (DIA between 1 and 7) ENABLE;
ALTER TABLE "XXMOR"."XXMOR_CONF_ORDS_URGENTES_TAB" ADD CONSTRAINT "CKC_DIA_CIERRE_XXMOR_CO" CHECK (DIA_CIERRE between 1 and 7) ENABLE;
ALTER TABLE "XXMOR"."XXMOR_CONF_ORDS_URGENTES_TAB" ADD CONSTRAINT "XXMOR_CONF_ORDS_URGENTES_TA_PK" PRIMARY KEY ("ID_SEG_NEG", "ID_FZA_VENTAS", "DIA", "DIA_CIERRE")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXMOR_CONF_ORDS_URGENTES_TAB" ADD CONSTRAINT "fk_fza_vtas_ord_urg" FOREIGN KEY ("ID_SEG_NEG", "ID_FZA_VENTAS")
	  REFERENCES "XXMOR"."XXMOR_FZAS_VTAS_TAB" ("ID_SEG_NEG", "ID_FZA_VENTAS") ENABLE;
