CREATE TABLE "XXMOR"."XXMOR_SEGM_NEG_TAB" 
   (	"ID_SEG_NEG" NUMBER NOT NULL ENABLE, 
	"NOMBRE_SN" VARCHAR2(30) NOT NULL ENABLE, 
	"URL_CONCOM" VARCHAR2(250)
   ) ;
ALTER TABLE "XXMOR"."XXMOR_SEGM_NEG_TAB" ADD CONSTRAINT "XXMOR_SEGM_NEG_TAB_PK" PRIMARY KEY ("ID_SEG_NEG")
  USING INDEX  ENABLE;
