CREATE TABLE "XXMOR"."XXMOR_SOLICITUDES_EST_REP_TAB" 
   (	"ID_SOLICITUD" NUMBER NOT NULL ENABLE, 
	"LINEA" NUMBER NOT NULL ENABLE, 
	"ID_SIST" NUMBER(3,0) NOT NULL ENABLE, 
	"ESTAT_REP" CHAR(2), 
	"ESTAT_ID_FORANEO" VARCHAR2(25), 
	"ESTAT_REINTENTO" NUMBER(2,0) DEFAULT 0, 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"UPDATED_DATE" DATE, 
	"ROTID" VARCHAR2(20), 
	"AUX1" VARCHAR2(15), 
	"AUX2" VARCHAR2(15), 
	"AUX3" VARCHAR2(15), 
	"ESTAT_ERROR_MSG" VARCHAR2(500)
   ) ;
ALTER TABLE "XXMOR"."XXMOR_SOLICITUDES_EST_REP_TAB" ADD CONSTRAINT "XXMOR_SOLICITUDES_EST_REP_T_PK" PRIMARY KEY ("ID_SOLICITUD", "LINEA", "ID_SIST")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXMOR_SOLICITUDES_EST_REP_TAB" ADD CONSTRAINT "FK_Estatus_Detalle" FOREIGN KEY ("ID_SOLICITUD", "LINEA")
	  REFERENCES "XXMOR"."XXMOR_SOLICITUDES_DET_TAB" ("ID_SOLICITUD", "LINEA") DISABLE;
ALTER TABLE "XXMOR"."XXMOR_SOLICITUDES_EST_REP_TAB" ADD CONSTRAINT "FK_Estatus_Enc" FOREIGN KEY ("ID_SOLICITUD")
	  REFERENCES "XXMOR"."XXMOR_SOLICITUDES_ENC_TAB" ("ID_SOLICITUD") ENABLE;
ALTER TABLE "XXMOR"."XXMOR_SOLICITUDES_EST_REP_TAB" ADD CONSTRAINT "FK_Estatus_Fza_Vtas_Rep" FOREIGN KEY ("ID_SIST")
	  REFERENCES "XXMOR"."XXMOR_SISTEMAS_FINALES_TAB" ("ID_SIST") ENABLE;
