CREATE TABLE "XXMOR"."XXMOR_ERRORES_LECTURA_ARCH_TAB" 
   (	"ID_ERROR" NUMBER(15,0) NOT NULL ENABLE, 
	"ID_ARCHIVO" NUMBER(15,0) NOT NULL ENABLE, 
	"COD_TIPO_ARCHIVO" VARCHAR2(10) NOT NULL ENABLE, 
	"NOM_ORDEN" VARCHAR2(35), 
	"CVE_POSICION" VARCHAR2(1) NOT NULL ENABLE, 
	"NUM_LINEA" NUMBER(*,0), 
	"DES_AUX1" VARCHAR2(240), 
	"DES_AUX2" VARCHAR2(240), 
	"DES_AUX3" VARCHAR2(240), 
	"DES_AUX4" VARCHAR2(240), 
	"DES_AUX5" VARCHAR2(240), 
	"FEC_CREACION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CVE_CREADO_POR" VARCHAR2(20), 
	"FEC_ACTUALIZACION" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CVE_ACTUALIZADO_POR" VARCHAR2(20), 
	"DES_ERROR" VARCHAR2(4000) DEFAULT 0 NOT NULL ENABLE
   ) ;
ALTER TABLE "XXMOR"."XXMOR_ERRORES_LECTURA_ARCH_TAB" ADD CONSTRAINT "XXMOR_ERRORES_LECTURA_PK" PRIMARY KEY ("ID_ERROR")
  USING INDEX  ENABLE;
