CREATE TABLE "XXMOR"."XXMOR_SOLICITUDES_ARCH_TAB" 
   (	"ID_SEG_NEG" NUMBER NOT NULL ENABLE, 
	"ID_ARCHIVO_SOL" NUMBER NOT NULL ENABLE, 
	"ARCHIVO_SOL" BLOB NOT NULL ENABLE, 
	"NOM_ARCHIVO_SOL" VARCHAR2(150) NOT NULL ENABLE, 
	"ARCHIVO_PROCESADO" CHAR(1), 
	"ENVIO_WS" CHAR(1), 
	"CREATED_DATE" DATE DEFAULT SYSDATE, 
	"CREATED_BY" VARCHAR2(20), 
	"NUM_ORDENES" NUMBER(15,0), 
	"OBSERVACIONES" VARCHAR2(4000)
   ) ;
ALTER TABLE "XXMOR"."XXMOR_SOLICITUDES_ARCH_TAB" ADD CONSTRAINT "XXMOR_ARCH_SOLICITUDES_TAB_PK" PRIMARY KEY ("ID_SEG_NEG", "ID_ARCHIVO_SOL")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXMOR_SOLICITUDES_ARCH_TAB" ADD CONSTRAINT "FK_Arch_sol_Seg_neg" FOREIGN KEY ("ID_SEG_NEG")
	  REFERENCES "XXMOR"."XXMOR_SEGM_NEG_TAB" ("ID_SEG_NEG") ENABLE;
