CREATE TABLE "XXMOR"."XXMOR_FZAS_VTAS_IDENT_TAB" 
   (	"ID_SEG_NEG" NUMBER NOT NULL ENABLE, 
	"ID_FZA_VENTAS" NUMBER NOT NULL ENABLE, 
	"IDENT_FZA_TIPO" CHAR(1) NOT NULL ENABLE, 
	"IDENT_FZA_VAL" VARCHAR2(10) NOT NULL ENABLE
   ) ;
ALTER TABLE "XXMOR"."XXMOR_FZAS_VTAS_IDENT_TAB" ADD CONSTRAINT "XXMOR_FZAS_VTAS_IDENT_TAB_PK" PRIMARY KEY ("ID_SEG_NEG", "ID_FZA_VENTAS", "IDENT_FZA_TIPO", "IDENT_FZA_VAL")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXMOR_FZAS_VTAS_IDENT_TAB" ADD CONSTRAINT "FK_Identificadores_fza_vtas" FOREIGN KEY ("ID_SEG_NEG", "ID_FZA_VENTAS")
	  REFERENCES "XXMOR"."XXMOR_FZAS_VTAS_TAB" ("ID_SEG_NEG", "ID_FZA_VENTAS") ENABLE;
