CREATE TABLE "XXMOR"."XXMOR_CONCOM_RPTA_TAB" 
   (	"ID_SOLICITUD" NUMBER NOT NULL ENABLE, 
	"ID_RPTA_CONCOM" NUMBER NOT NULL ENABLE, 
	"RESULTADOGENERAL" VARCHAR2(50), 
	"TRACKINGID" VARCHAR2(50), 
	"DESC_CONCOM" VARCHAR2(128), 
	"POSICION_CONCOM" VARCHAR2(15), 
	"ID_CONCOM" VARCHAR2(250), 
	"NUMLINEA_CONCOM" VARCHAR2(20), 
	"ESTATUS_CONCOM" VARCHAR2(20), 
	"CAMPO_CONCOM" VARCHAR2(2000), 
	"DETALLE_CONCOM" VARCHAR2(2000), 
	"ACCION_CONCOM" VARCHAR2(50), 
	"TIPOREGLA_CONCOM" VARCHAR2(50), 
	"ESTATUS_ORDUNI" CHAR(2), 
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(20) NOT NULL ENABLE, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(20), 
	"ID_SEG_NEG" NUMBER
   ) ;
ALTER TABLE "XXMOR"."XXMOR_CONCOM_RPTA_TAB" ADD CONSTRAINT "XXMOR_CONCOM_RPTA_TAB_PK" PRIMARY KEY ("ID_SOLICITUD", "CREATED_DATE", "CREATED_BY", "ID_RPTA_CONCOM")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXMOR_CONCOM_RPTA_TAB" ADD CONSTRAINT "FK_Rpta_ConCom_SolDet" FOREIGN KEY ("ID_SOLICITUD")
	  REFERENCES "XXMOR"."XXMOR_SOLICITUDES_ENC_TAB" ("ID_SOLICITUD") ENABLE;
