CREATE TABLE "XXMOR"."XXMOR_LOG_ERRORES_TAB" 
   (	"ID_ERROR" NUMBER NOT NULL ENABLE, 
	"DESC_ERROR" VARCHAR2(4000), 
	"ARCHIVO_ERROR" VARCHAR2(350), 
	"METODO_ERROR" VARCHAR2(1000), 
	"HORA_ERROR" DATE DEFAULT SYSDATE
   ) ;
ALTER TABLE "XXMOR"."XXMOR_LOG_ERRORES_TAB" ADD CONSTRAINT "XXMOR_LOG_ERRORES_TAB_PK" PRIMARY KEY ("ID_ERROR")
  USING INDEX  ENABLE;
