CREATE TABLE "XXMOR"."XXMOR_MAPEO_CAMPOS_TAB" 
   (	"ID_SEG_NEG" NUMBER NOT NULL ENABLE, 
	"ID_OBJ" NUMBER NOT NULL ENABLE, 
	"DESC_OBJ" VARCHAR2(50), 
	"TEXTO_OBJ" VARCHAR2(50), 
	"VISIBLE_OBJ" CHAR(1), 
	"EDITABLE_OBJ" CHAR(1), 
	"URL_OBJ" VARCHAR2(250), 
	"POSICION_PANTALLA" VARCHAR2(50)
   ) ;
ALTER TABLE "XXMOR"."XXMOR_MAPEO_CAMPOS_TAB" ADD CONSTRAINT "XXMOR_MAPEO_CAMPOS_TAB_PK" PRIMARY KEY ("ID_SEG_NEG", "ID_OBJ")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXMOR_MAPEO_CAMPOS_TAB" ADD CONSTRAINT "FK_Map_Campos_Segm_neg" FOREIGN KEY ("ID_SEG_NEG")
	  REFERENCES "XXMOR"."XXMOR_SEGM_NEG_TAB" ("ID_SEG_NEG") ENABLE;
