CREATE TABLE "XXMOR"."XXMOR_FZAS_VTAS_CANALES_TAB" 
   (	"ID_SEG_NEG" NUMBER NOT NULL ENABLE, 
	"ID_FZA_VENTAS" NUMBER NOT NULL ENABLE, 
	"STNID_PADRE" VARCHAR2(10) NOT NULL ENABLE, 
	"STNID_HIJO" VARCHAR2(10) NOT NULL ENABLE, 
	"STNID_PORCENTAJE" NUMBER(5,2) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(20) NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"UPDATED_DATE" DATE, 
	"UPDATED_BY" VARCHAR2(20)
   ) ;
ALTER TABLE "XXMOR"."XXMOR_FZAS_VTAS_CANALES_TAB" ADD CONSTRAINT "XXMOR_FZAS_VTAS_CANALES_TAB_PK" PRIMARY KEY ("ID_SEG_NEG", "ID_FZA_VENTAS", "STNID_PADRE", "STNID_HIJO")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXMOR_FZAS_VTAS_CANALES_TAB" ADD CONSTRAINT "FK_Fza_vtas_Canales_fza_vtas" FOREIGN KEY ("ID_SEG_NEG", "ID_FZA_VENTAS")
	  REFERENCES "XXMOR"."XXMOR_FZAS_VTAS_TAB" ("ID_SEG_NEG", "ID_FZA_VENTAS") ENABLE;
