CREATE TABLE "XXMOR"."XXMOR_ARCHIVOS_FTP_TAB" 
   (	"NOM_ARCHIVO" VARCHAR2(240) NOT NULL ENABLE, 
	"ESTATUS" VARCHAR2(5) NOT NULL ENABLE, 
	"DESC_ERROR" VARCHAR2(4000), 
	"ID_ARCHIVO" NUMBER(15,0), 
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(20)
   ) ;
