CREATE TABLE "XXMOR"."XXMOR_FZAS_VTAS_TAB" 
   (	"ID_SEG_NEG" NUMBER NOT NULL ENABLE, 
	"ID_FZA_VENTAS" NUMBER NOT NULL ENABLE, 
	"IDENT_FZA_VENTAS" VARCHAR2(6), 
	"NOMBRE_FZA_VENTAS" VARCHAR2(50) NOT NULL ENABLE, 
	"REGION" VARCHAR2(4), 
	"COPYS_X_ORDEN" CHAR(1), 
	"COPYS_X_FECHA" CHAR(1), 
	"MULTIFUERZA" CHAR(1), 
	"RTCRD_AUTH_AUT" CHAR(1), 
	"AUT_X_CORREO" CHAR(1), 
	"MERCADOTECNIA" CHAR(1), 
	"DIV_X_CANAL" CHAR(1), 
	"CONDICIONES_COMERCIALES" VARCHAR2(4000), 
	"ACTIVA" CHAR(1), 
	"NOTIFICACION_EXT_INT" CHAR(1), 
	"CREATED_BY" VARCHAR2(20) NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_DATE" DATE, 
	"MATLOC" CHAR(2), 
	"AUT_TOLERANCIA" NUMBER(10,2), 
	"GET_RATE" CHAR(2), 
	"MATLOC_NULL" CHAR(1), 
	"MATLOC_BUSQUEDA" VARCHAR2(2), 
	"MKT_VERSION_WS" CHAR(1) DEFAULT '0', 
	"ESQUEMA_FACTUR" VARCHAR2(50), 
	"ID_EMPRESA_ERP" NUMBER(15,0), 
	"EMPRESA_ERP" VARCHAR2(240), 
	"SEG_NEG_ERP" VARCHAR2(30), 
	"RESPETA_CANAL" VARCHAR2(1), 
	"COMP_EMPRESA" VARCHAR2(400), 
	"POR_IVA" NUMBER, 
	"USAR_BUYUNIT_MKT" VARCHAR2(1)
   ) ;
ALTER TABLE "XXMOR"."XXMOR_FZAS_VTAS_TAB" ADD CONSTRAINT "XXMOR_FZAS_VTAS_TAB_PK" PRIMARY KEY ("ID_SEG_NEG", "ID_FZA_VENTAS")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXMOR_FZAS_VTAS_TAB" ADD CONSTRAINT "FK_Fzas_vtas_segm_neg" FOREIGN KEY ("ID_SEG_NEG")
	  REFERENCES "XXMOR"."XXMOR_SEGM_NEG_TAB" ("ID_SEG_NEG") ENABLE;
