CREATE TABLE "XXMOR"."XXMOR_SOLICITUDES_ORIG_ENC_TAB" 
   (	"ID_REQUEST" NUMBER NOT NULL ENABLE, 
	"ID_ARCHIVO_SOL" NUMBER, 
	"ID_SEG_NEG" NUMBER, 
	"PROC_POR_LINEA" VARCHAR2(2), 
	"GARANTIZADO" VARCHAR2(2), 
	"ADVID" VARCHAR2(12), 
	"MCONTID" VARCHAR2(20), 
	"MCONTID_CUTIN" VARCHAR2(20), 
	"EMAIL" VARCHAR2(80), 
	"AGYESTNUM" VARCHAR2(25), 
	"ACCTHDRID" VARCHAR2(50), 
	"RTCRDDSCR" VARCHAR2(40), 
	"RTCRDDSCR_CUTIN" VARCHAR2(50), 
	"COMENTARIOS" VARCHAR2(252), 
	"SECNUM" VARCHAR2(3), 
	"PLATAFORMA_CANAL" VARCHAR2(70), 
	"PRDID_DESC" VARCHAR2(50), 
	"TOTAL_SPOTS" VARCHAR2(5), 
	"TOTAL_SIN_DESC" VARCHAR2(15), 
	"TOTAL_CON_DESC" VARCHAR2(15), 
	"TIPO_FACTURACION" VARCHAR2(20), 
	"DESCUENTO" VARCHAR2(20), 
	"TARGET" VARCHAR2(50), 
	"AUX1" VARCHAR2(15), 
	"AUX2" VARCHAR2(15), 
	"AUX3" VARCHAR2(15), 
	"AUX4" VARCHAR2(15), 
	"AUX5" VARCHAR2(15), 
	"CREATED_BY" VARCHAR2(20) NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE
   ) ;
ALTER TABLE "XXMOR"."XXMOR_SOLICITUDES_ORIG_ENC_TAB" ADD CONSTRAINT "XXMOR_SOLICITUDES_ORIG_ENC_PK" PRIMARY KEY ("ID_REQUEST")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXMOR_SOLICITUDES_ORIG_ENC_TAB" ADD CONSTRAINT "FK_XXMOR_SO_FK_FZAS_V_XXMOR_SE" FOREIGN KEY ("ID_SEG_NEG")
	  REFERENCES "XXMOR"."XXMOR_SEGM_NEG_TAB" ("ID_SEG_NEG") ENABLE;
