CREATE TABLE "XXMOR"."XXMOR_CAT_BUYUNIT_MKT_TAB" 
   (	"ID_SEG_NEG" NUMBER(*,0) NOT NULL ENABLE, 
	"ID_FZA_VENTAS" NUMBER(*,0) NOT NULL ENABLE, 
	"BUYUNTID" VARCHAR2(15) NOT NULL ENABLE, 
	"MKT_DIRECTOR" VARCHAR2(50), 
	"MKT_GERENTE" VARCHAR2(50), 
	"MKT_COORDINADOR" VARCHAR2(50), 
	"MKT_EJECUTIVO" VARCHAR2(50), 
	"MKT_MAIL_DIRECTOR" VARCHAR2(50), 
	"MKT_MAIL_GERENTE" VARCHAR2(50), 
	"MKT_MAIL_COORDINADOR" VARCHAR2(50), 
	"MKT_MAIL_EJECUTIVO" VARCHAR2(50), 
	"CREATED_BY" VARCHAR2(20) NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"UPDATED_BY" VARCHAR2(20), 
	"UPDATED_DATE" DATE, 
	"ID_BUYUNIT_MKT" NUMBER(15,0)
   ) ;
ALTER TABLE "XXMOR"."XXMOR_CAT_BUYUNIT_MKT_TAB" ADD CONSTRAINT "XXMOR_CAT_BUYUNIT_MKT_PK" PRIMARY KEY ("ID_SEG_NEG", "ID_FZA_VENTAS", "ID_BUYUNIT_MKT")
  USING INDEX  ENABLE;
