CREATE TABLE "XXMOR"."XXMOR_MAP_CANAL_TSERV_RECH_TAB" 
   (	"ID_MAPEO" NUMBER(15,0) NOT NULL ENABLE, 
	"CANAL" VARCHAR2(15) NOT NULL ENABLE, 
	"TIPO_SERVICIO" VARCHAR2(150) NOT NULL ENABLE, 
	"ACTIVO" VARCHAR2(1) NOT NULL ENABLE, 
	"CREATED_DATE" DATE DEFAULT SYSDATE NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(20)
   ) ;
ALTER TABLE "XXMOR"."XXMOR_MAP_CANAL_TSERV_RECH_TAB" ADD CONSTRAINT "XXMOR_MAP_CAN_TSERV_RECH_PK" PRIMARY KEY ("ID_MAPEO")
  USING INDEX  ENABLE;
