CREATE TABLE "XXMOR"."XXMOR_CONF_TIPO_SRV_TAB" 
   (	"ID_SEG_NEG" NUMBER NOT NULL ENABLE, 
	"ID_FZA_VENTAS" NUMBER NOT NULL ENABLE, 
	"ID_TIPO_SERVICIO" NUMBER NOT NULL ENABLE, 
	"INCLUSION" NUMBER(1,0), 
	"SPTCHR" VARCHAR2(2), 
	"USRCHR" VARCHAR2(2)
   ) ;
ALTER TABLE "XXMOR"."XXMOR_CONF_TIPO_SRV_TAB" ADD CONSTRAINT "XXMOR_CONF_TIPO_SRV_TAB_PK" PRIMARY KEY ("ID_SEG_NEG", "ID_FZA_VENTAS", "ID_TIPO_SERVICIO")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXMOR_CONF_TIPO_SRV_TAB" ADD CONSTRAINT "fk_fza_vtas_tipo_serv" FOREIGN KEY ("ID_SEG_NEG", "ID_FZA_VENTAS")
	  REFERENCES "XXMOR"."XXMOR_FZAS_VTAS_TAB" ("ID_SEG_NEG", "ID_FZA_VENTAS") ENABLE;
