CREATE TABLE "XXMOR"."XXMOR_SISTEMAS_FINALES_TAB" 
   (	"ID_SIST" NUMBER(3,0) NOT NULL ENABLE, 
	"DESC_SIST" CHAR(10) NOT NULL ENABLE, 
	"URL_WS" CHAR(10) NOT NULL ENABLE
   ) ;
ALTER TABLE "XXMOR"."XXMOR_SISTEMAS_FINALES_TAB" ADD CONSTRAINT "XXMOR_SISTEMAS_FINALES_TAB_PK" PRIMARY KEY ("ID_SIST")
  USING INDEX  ENABLE;
