CREATE TABLE "XXMOR"."XXMOR_FZAS_VTAS_SISTEMAS_TAB" 
   (	"ID_SIST" NUMBER(3,0) NOT NULL ENABLE, 
	"ID_SEG_NEG" NUMBER NOT NULL ENABLE, 
	"ID_FZA_VENTAS" NUMBER NOT NULL ENABLE
   ) ;
ALTER TABLE "XXMOR"."XXMOR_FZAS_VTAS_SISTEMAS_TAB" ADD CONSTRAINT "XXMOR_FZAS_VTAS_SISTEMAS_TA_PK" PRIMARY KEY ("ID_SEG_NEG", "ID_SIST", "ID_FZA_VENTAS")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXMOR_FZAS_VTAS_SISTEMAS_TAB" ADD CONSTRAINT "FK_Fza_vtas_Sistemas" FOREIGN KEY ("ID_SEG_NEG", "ID_FZA_VENTAS")
	  REFERENCES "XXMOR"."XXMOR_FZAS_VTAS_TAB" ("ID_SEG_NEG", "ID_FZA_VENTAS") ENABLE;
ALTER TABLE "XXMOR"."XXMOR_FZAS_VTAS_SISTEMAS_TAB" ADD CONSTRAINT "FK_Sistemas_Fza_vtas" FOREIGN KEY ("ID_SIST")
	  REFERENCES "XXMOR"."XXMOR_SISTEMAS_FINALES_TAB" ("ID_SIST") ENABLE;
