CREATE TABLE "XXMOR"."XXMOR_CAT_URLS_TAB" 
   (	"ID_SEG_NEG" NUMBER NOT NULL ENABLE, 
	"ID_URL" NUMBER NOT NULL ENABLE, 
	"URL" VARCHAR2(250) NOT NULL ENABLE, 
	"DESC_URL" VARCHAR2(260), 
	"ORDEN_URL" NUMBER
   ) ;
ALTER TABLE "XXMOR"."XXMOR_CAT_URLS_TAB" ADD CONSTRAINT "XXMOR_CAT_URLS_TAB_PK" PRIMARY KEY ("ID_SEG_NEG", "ID_URL")
  USING INDEX  ENABLE;
ALTER TABLE "XXMOR"."XXMOR_CAT_URLS_TAB" ADD CONSTRAINT "FK_cat_urls_segm_neg" FOREIGN KEY ("ID_SEG_NEG")
	  REFERENCES "XXMOR"."XXMOR_SEGM_NEG_TAB" ("ID_SEG_NEG") ENABLE;
