CREATE OR REPLACE NONEDITIONABLE FUNCTION "LABPROD"."FN_BASEDATOS_EMP" 
(
  KEYEMP IN NUMBER
) RETURN VARCHAR2 AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
RESULTADO VARCHAR2(10);
KEYPRO NUMBER;
STATUS NUMBER;
BASE VARCHAR(10);
BEGIN
  BEGIN
  BASE := 'TELECOM';
  FOR q_empleado IN
  (
    SELECT CASE WHEN PAM_CVESEC IS NULL THEN 'TVNOMINA' ELSE 'TELECOM' END BASE, EMP_KEYPRO,EMP_STATUS
    FROM LABPROD.NMCOEMPL
    LEFT JOIN LABPROD.GLCOPAMS ON PAM_KEYPAR = 'SEPB' AND EMP_KEYPRO = PAM_CVESEC
    WHERE EMP_KEYEMP = KEYEMP
    ORDER BY EMP_STATUS,EMP_FECMOD)
  LOOP
    BASE := q_empleado.BASE;
    KEYPRO := q_empleado.emp_keypro;
    STATUS := q_empleado.emp_status;
    EXIT;
  END LOOP;
  RETURN BASE;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN 'TVNOMINA';
  END;
END FN_BASEDATOS_EMP;
/
--Source_DDLS

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "LABPROD"."FN_BASEDATOS_EMP" 
(
  KEYEMP IN NUMBER
) RETURN VARCHAR2 AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
RESULTADO VARCHAR2(10);
KEYPRO NUMBER;
STATUS NUMBER;
BASE VARCHAR(10);
BEGIN
  BEGIN
  BASE := 'TELECOM';
  FOR q_empleado IN
  (
    SELECT CASE WHEN PAM_CVESEC IS NULL THEN 'TVNOMINA' ELSE 'TELECOM' END BASE, EMP_KEYPRO,EMP_STATUS
    FROM LABPROD.NMCOEMPL
    LEFT JOIN LABPROD.GLCOPAMS ON PAM_KEYPAR = 'SEPB' AND EMP_KEYPRO = PAM_CVESEC
    WHERE EMP_KEYEMP = KEYEMP
    ORDER BY EMP_STATUS,EMP_FECMOD)
  LOOP
    BASE := q_empleado.BASE;
    KEYPRO := q_empleado.emp_keypro;
    STATUS := q_empleado.emp_status;
    EXIT;
  END LOOP;
  RETURN BASE;
  EXCEPTION
    WHEN OTHERS THEN
      RETURN 'TVNOMINA';
  END;
END FN_BASEDATOS_EMP;
/
