CREATE OR REPLACE NONEDITIONABLE FUNCTION "LABPROD"."FN_SEMANA_INC" 
(
  INC_SEMANA IN NUMBER
) RETURN VARCHAR2 AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
STR_SEMANA VARCHAR2(3);
BEGIN
  STR_SEMANA := INC_SEMANA;
  STR_SEMANA := SUBSTR(STR_SEMANA, 1, 2);
  RETURN STR_SEMANA;
END FN_SEMANA_INC;
/
--Source_DDLS

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "LABPROD"."FN_SEMANA_INC" 
(
  INC_SEMANA IN NUMBER
) RETURN VARCHAR2 AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
STR_SEMANA VARCHAR2(3);
BEGIN
  STR_SEMANA := INC_SEMANA;
  STR_SEMANA := SUBSTR(STR_SEMANA, 1, 2);
  RETURN STR_SEMANA;
END FN_SEMANA_INC;
/
