CREATE OR REPLACE NONEDITIONABLE FUNCTION "LABPROD"."FN_VAC_ESTATUS" 
(
  FECINI IN DATE
) RETURN VARCHAR2 AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
ESTATUS VARCHAR2(10);
BEGIN
  IF FECINI > SYSDATE THEN
    ESTATUS := 'ANTICIPADO';
  ELSE
    ESTATUS := 'VIGENTE';
  END IF;
  RETURN ESTATUS;
END FN_VAC_ESTATUS;
/
--Source_DDLS

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "LABPROD"."FN_VAC_ESTATUS" 
(
  FECINI IN DATE
) RETURN VARCHAR2 AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
ESTATUS VARCHAR2(10);
BEGIN
  IF FECINI > SYSDATE THEN
    ESTATUS := 'ANTICIPADO';
  ELSE
    ESTATUS := 'VIGENTE';
  END IF;
  RETURN ESTATUS;
END FN_VAC_ESTATUS;
/
