CREATE OR REPLACE NONEDITIONABLE FUNCTION "LABPROD"."FN_VAC_DIASDERECHO" 
(
  KEYEMP IN NUMBER
, FECING IN DATE
, FECINI IN DATE
, KEYPRO IN INTEGER
, TABDIA IN VARCHAR2
) RETURN DECIMAL AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
DIADER DECIMAL(10,2);
ANTIGUEDAD DECIMAL(10,2);
BEGIN
  ANTIGUEDAD := MONTHS_BETWEEN(FECINI,FECING) / 12;
  DBMS_OUTPUT.PUT_LINE('ANTIGUEDAD = '||ANTIGUEDAD);
  BEGIN
    SELECT TAB_ELETRE INTO DIADER
      FROM LABPROD.NMLOTABN
      WHERE TAB_KEYTAB = TABDIA
        AND TAB_ELEUNO <= ANTIGUEDAD
        AND TAB_ELEDOS >= ANTIGUEDAD
        AND ROWNUM = 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DIADER := 0;
  END;
  DBMS_OUTPUT.PUT_LINE('DIADER = '||DIADER);
  RETURN DIADER;
END FN_VAC_DIASDERECHO;
/
--Source_DDLS

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "LABPROD"."FN_VAC_DIASDERECHO" 
(
  KEYEMP IN NUMBER
, FECING IN DATE
, FECINI IN DATE
, KEYPRO IN INTEGER
, TABDIA IN VARCHAR2
) RETURN DECIMAL AS
-- PGV moved types start

-- PGV moved types end

-- PGV moved types start
-- PGV moved types end
DIADER DECIMAL(10,2);
ANTIGUEDAD DECIMAL(10,2);
BEGIN
  ANTIGUEDAD := MONTHS_BETWEEN(FECINI,FECING) / 12;
  DBMS_OUTPUT.PUT_LINE('ANTIGUEDAD = '||ANTIGUEDAD);
  BEGIN
    SELECT TAB_ELETRE INTO DIADER
      FROM LABPROD.NMLOTABN
      WHERE TAB_KEYTAB = TABDIA
        AND TAB_ELEUNO <= ANTIGUEDAD
        AND TAB_ELEDOS >= ANTIGUEDAD
        AND ROWNUM = 1;
  EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DIADER := 0;
  END;
  DBMS_OUTPUT.PUT_LINE('DIADER = '||DIADER);
  RETURN DIADER;
END FN_VAC_DIASDERECHO;
/
