CREATE OR REPLACE FORCE EDITIONABLE VIEW "USRSIHO"."ERP_HOLOPOLI1" ("POL_KEYPOL", "POL_CTVPOL", "POL_KEYPRO", "POL_KEYAPR", "POL_KEYNOM", "POL_NUMEMI", "POL_KEYREC", "POL_KEYEMP", "POL_REGRFC", "POL_EMIPAG", "POL_TIPPOL", "POL_STSPOL", "POL_CVEPOL", "POL_FECPOL", "POL_PERCON", "POL_NUMREM", "POL_REMREC", "POL_TOTCAR", "POL_TOTABO", "POL_CARPAS", "POL_ABOPAS", "POL_USUGEN", "POL_FECGEN", "POL_USUREM", "POL_FECREM", "POL_USUAUT", "POL_FECAUT", "POL_CONTRA", "POL_SEMANA", "POL_TIPCTA", "POL_KEYMAD", "POL_CTVMAD", "POL_REGFIS", "POL_FORPAG", "POL_TIPCAM", "POL_FPAFIN", "POL_TCAFIN", "POL_AUXNU1", "POL_AUXCA1") AS 
  SELECT
POL_KEYPOL,POL_CTVPOL,POL_KEYPRO,POL_KEYAPR,POL_KEYNOM,POL_NUMEMI,POL_KEYREC,POL_KEYEMP,POL_REGRFC,
POL_EMIPAG,POL_TIPPOL,POL_STSPOL,POL_CVEPOL,POL_FECPOL,POL_PERCON,POL_NUMREM,POL_REMREC,POL_TOTCAR,
POL_TOTABO,POL_CARPAS,POL_ABOPAS,POL_USUGEN,POL_FECGEN,POL_USUREM,POL_FECREM,POL_USUAUT,POL_FECAUT,
POL_CONTRA,POL_SEMANA,POL_TIPCTA,POL_KEYMAD,POL_CTVMAD,POL_REGFIS,POL_FORPAG,POL_TIPCAM,POL_FPAFIN,
POL_TCAFIN,POL_AUXNU1,POL_AUXCA1
FROM holopoli1;
