CREATE OR REPLACE FORCE EDITIONABLE VIEW "USRSIHO"."ERP_RECI_ERP_C" ("REC_CVEPOL", "REC_FECPAG", "REC_NUMERR", "REC_STSREC", "REC_STATUS", "REC_TIPCAM", "REC_FECGEN", "REC_FORPAG", "REC_FPAFIN", "REC_TCAFIN", "REC_TIPPAG", "REC_REFERE", "REC_FECREC", "REC_CVEBAN", "REC_CTABAN") AS 
  SELECT
REC_CVEPOL,REC_FECPAG,REC_NUMERR,REC_STSREC,REC_STATUS,REC_TIPCAM,REC_FECGEN,REC_FORPAG,REC_FPAFIN,
REC_TCAFIN,REC_TIPPAG,REC_REFERE,REC_FECREC,REC_CVEBAN,REC_CTABAN
FROM reci_erp_c;
