CREATE OR REPLACE FORCE EDITIONABLE VIEW "USRSIHO"."ERP_HOLODETP1" ("DET_KEYPOL", "DET_KEYFOL", "DET_CUENTA", "DET_CARGOS", "DET_ABONOS", "DET_SEC_SINDICAL") AS 
  SELECT
DET_KEYPOL,DET_KEYFOL,DET_CUENTA,DET_CARGOS,DET_ABONOS,DET_SEC_SINDICAL
FROM  holodetp1;
