CREATE OR REPLACE FORCE EDITIONABLE VIEW "USRSIHO"."ERP_TMP_CONT_EXCLU" ("CON_KEYFOL", "CON_KEYDEP", "CON_KEYPUE", "CON_KEYEMP", "CON_NUMCAP", "CON_FECPAG", "CON_FECPRO", "CON_COSUNI", "CON_NUMERR", "CON_STSCON", "CON_TIPFOL", "CON_NUMLIN", "CON_KEYNOM", "CON_FORPAG", "CON_TIPCAM", "CON_TIPTRA", "CON_KEYPRO", "CON_AREFIS", "CON_DESCAP", "CON_FPAFIN", "CON_TCAFIN", "CON_KEYRPH", "CON_KEYUSU", "CON_FECMOD", "CON_ODCORI") AS 
  SELECT
CON_KEYFOL,CON_KEYDEP,CON_KEYPUE,CON_KEYEMP,CON_NUMCAP,CON_FECPAG,CON_FECPRO,CON_COSUNI,CON_NUMERR,
CON_STSCON,CON_TIPFOL,CON_NUMLIN,CON_KEYNOM,CON_FORPAG,CON_TIPCAM,CON_TIPTRA,CON_KEYPRO,CON_AREFIS,
CON_DESCAP,CON_FPAFIN,CON_TCAFIN,CON_KEYRPH,CON_KEYUSU,CON_FECMOD,CON_ODCORI
FROM tmp_cont_exclu;
