CREATE OR REPLACE NONEDITIONABLE TRIGGER "XX_BLOQUEOBAJAS"."DESTINATARIOS_INSERT" 
  BEFORE INSERT ON XX_BLOQUEOBAJAS.DESTINATARIOS
  FOR EACH ROW
BEGIN
  SELECT XX_BLOQUEOBAJAS.DESTINATARIOS_SEQ.nextval
  INTO :new.IDDESTINATARIO
  FROM dual;
END;


/
ALTER TRIGGER "XX_BLOQUEOBAJAS"."DESTINATARIOS_INSERT" ENABLE;
