CREATE OR REPLACE NONEDITIONABLE TRIGGER "XX_BLOQUEOBAJAS"."SOLICITUDES_INSERT" 
  BEFORE INSERT ON XX_BLOQUEOBAJAS.SOLICITUDES
  FOR EACH ROW
BEGIN
  SELECT XX_BLOQUEOBAJAS.SOLICITUDES_SEQ.nextval
  INTO :new.IDSOLICITUD
  FROM dual;
END;


/
ALTER TRIGGER "XX_BLOQUEOBAJAS"."SOLICITUDES_INSERT" ENABLE;
