CREATE OR REPLACE FORCE EDITIONABLE VIEW "FECXC"."FECI_RECIBOS_VW" ("FOLIO_RECIBO", "TIPO_RECIBO", "FEC_CONTABILIDAD", "FEC_OPERATIVA", "IMPORTE", "COD_MONEDA", "DES_MONEDA", "COD_EMPRESA", "DES_EMPRESA", "COD_CLIENTE", "REF_CLIENTE", "NOM_CLIENTE", "CLASE_CLIENTE", "METODO_PAGO", "NOM_BANCO_EMISOR", "NUM_CHEQUERA", "NUM_CHEQUE", "NUM_OPERACION", "TIPO_CAMBIO_ORIGEN", "FEC_TC_ORIGEN", "TIPO_CAMBIO_DOLAR", "FEC_TC_DOLAR", "ID_USUARIO_CLASIFICACION", "FEC_CLASIFICACION", "ID_USUARIO_APLICACION", "FEC_APLICACION", "COD_ESTADO_RECIBO", "FEC_CREACION", "FEC_ULT_MODIFICACION", "ID_USUARIO_CREACION", "ID_USUARIO_ULT_MODIF", "IND_ESTADO") AS 
  SELECT
        --CONCAT('-M', LPAD(REC.FOLIO_RECIBO_MANUAL, 5, '0')) AS FOLIO_RECIBO
        REC.FOLIO_RECIBO_MANUAL   AS FOLIO_RECIBO
        ,'MANUAL'                 AS TIPO_RECIBO
        ,REC.FEC_CONTABILIDAD     AS FEC_CONTABILIDAD
        ,REC.FEC_OPERATIVA        AS FEC_OPERATIVA
        ,REC.IMPORTE              AS IMPORTE
        ,REC.COD_MONEDA           AS COD_MONEDA
        ,MON.DES_MONEDA           AS DES_MONEDA
        ,REC.COD_EMPRESA          AS COD_EMPRESA
        ,EMP.DES_EMPRESA          AS DES_EMPRESA
        ,REC.COD_CLIENTE          AS COD_CLIENTE
        ,REC.REF_CLIENTE          AS REF_CLIENTE
        ,REC.NOM_CLIENTE          AS NOM_CLIENTE
        ,REC.CLASE_CLIENTE        AS CLASE_CLIENTE
        ,REC.METODO_PAGO          AS METODO_PAGO
        ,REC.NOM_BANCO_EMISOR     AS NOM_BANCO_EMISOR
        ,REC.NUM_CHEQUERA         AS NUM_CHEQUERA
        ,REC.NUM_CHEQUE           AS NUM_CHEQUE
        ,REC.NUM_OPERACION        AS NUM_OPERACION
        ,REC.TIPO_CAMBIO_ORIGEN   AS TIPO_CAMBIO_ORIGEN
        ,REC.FEC_TC_ORIGEN        AS FEC_TC_ORIGEN
        ,REC.TIPO_CAMBIO_DOLAR    AS TIPO_CAMBIO_DOLAR
        ,REC.FEC_TC_DOLAR         AS FEC_TC_DOLAR
        ,REC.ID_USUARIO_CLASIFICACION  AS ID_USUARIO_CLASIFICACION
        ,REC.FEC_CLASIFICACION	  AS FEC_CLASIFICACION
        ,REC.ID_USUARIO_APLICACION     AS ID_USUARIO_APLICACION
        ,REC.FEC_APLICACION       AS FEC_APLICACION
        ,REC.COD_ESTADO_RECIBO    AS COD_ESTADO_RECIBO
        ,REC.FEC_CREACION         AS FEC_CREACION
        ,REC.FEC_ULT_MODIFICACION AS FEC_ULT_MODIFICACION
        ,REC.ID_USUARIO_CREACION  AS ID_USUARIO_CREACION
        ,REC.ID_USUARIO_ULT_MODIF AS ID_USUARIO_ULT_MODIF
        ,REC.IND_ESTADO           AS IND_ESTADO
    FROM FECXC.FECI_RECIBO_MANUAL_TAB REC
    INNER JOIN FECXC.FECI_MONEDA_CAT MON ON REC.COD_MONEDA = MON.COD_MONEDA
    INNER JOIN FECXC.FECI_EMPRESA_CAT EMP ON REC.COD_EMPRESA = EMP.COD_EMPRESA
    WHERE REC.IND_ESTADO = 1 AND MON.IND_ESTADO = 1 AND EMP.IND_ESTADO = 1
    UNION
    SELECT
        --TO_CHAR(REC.FOLIO_RECIBO)   AS FOLIO_RECIBO
        REC.FOLIO_RECIBO          AS FOLIO_RECIBO
        ,'BATCH'                  AS TIPO_RECIBO
        ,REC.FEC_CONTABILIDAD     AS FEC_CONTABILIDAD
        ,REC.FEC_OPERATIVA        AS FEC_OPERATIVA
        ,REC.IMPORTE              AS IMPORTE
        ,REC.COD_MONEDA           AS COD_MONEDA
        ,MON.DES_MONEDA           AS DES_MONEDA
        ,REC.COD_EMPRESA          AS COD_EMPRESA
        ,EMP.DES_EMPRESA          AS DES_EMPRESA
        ,REC.COD_CLIENTE          AS COD_CLIENTE
        ,REC.REF_CLIENTE          AS REF_CLIENTE
        ,REC.NOM_CLIENTE          AS NOM_CLIENTE
        ,REC.CLASE_CLIENTE        AS CLASE_CLIENTE
        ,REC.METODO_PAGO          AS METODO_PAGO
        ,REC.NOM_BANCO_EMISOR     AS NOM_BANCO_EMISOR
        ,REC.NUM_CHEQUERA         AS NUM_CHEQUERA
        ,REC.NUM_CHEQUE           AS NUM_CHEQUE
        ,REC.NUM_OPERACION        AS NUM_OPERACION
        ,REC.TIPO_CAMBIO_ORIGEN   AS TIPO_CAMBIO_ORIGEN
        ,REC.FEC_TC_ORIGEN        AS FEC_TC_ORIGEN
        ,REC.TIPO_CAMBIO_DOLAR    AS TIPO_CAMBIO_DOLAR
        ,REC.FEC_TC_DOLAR         AS FEC_TC_DOLAR
        ,REC.ID_USUARIO_CLASIFICACION  AS ID_USUARIO_CLASIFICACION
        ,REC.FEC_CLASIFICACION	  AS FEC_CLASIFICACION
        ,REC.ID_USUARIO_APLICACION     AS ID_USUARIO_APLICACION
        ,REC.FEC_APLICACION       AS FEC_APLICACION
        ,REC.COD_ESTADO_RECIBO    AS COD_ESTADO_RECIBO
        ,REC.FEC_CREACION         AS FEC_CREACION
        ,REC.FEC_ULT_MODIFICACION AS FEC_ULT_MODIFICACION
        ,REC.ID_USUARIO_CREACION  AS ID_USUARIO_CREACION
        ,REC.ID_USUARIO_ULT_MODIF AS ID_USUARIO_ULT_MODIF
        ,REC.IND_ESTADO           AS IND_ESTADO
    FROM FECXC.FECI_RECIBO_TAB REC
    INNER JOIN FECXC.FECI_MONEDA_CAT MON ON REC.COD_MONEDA = MON.COD_MONEDA
    INNER JOIN FECXC.FECI_EMPRESA_CAT EMP ON REC.COD_EMPRESA = EMP.COD_EMPRESA
    WHERE REC.IND_ESTADO = 1 AND MON.IND_ESTADO = 1 AND EMP.IND_ESTADO = 1;
