CREATE OR REPLACE FORCE EDITIONABLE VIEW "FECXC"."FECXC_COBRANZA_INTERMEX_V" ("ORDEN", "TIPO", "SUBTIPO", "SEGMENTO", "CANAL", "IMPORTE", "IMPORTENOM", "COD_VALOR", "DESSEGMENTO", "DESCANAL") AS 
  SELECT ORDEN, TIPO, SUBTIPO, SEGMENTO, CANAL, IMPORTE, IMPORTENOM, B.COD_VALOR, B.DESC_VALOR  "DESSEGMENTO", C.DESC_VALOR  "DESCANAL"
  FROM (
         	(
          		SELECT 0 AS ORDEN, 'DEL DIA' AS TIPO, 'REAL' AS SUBTIPO, SEGMENTO, CANAL, SUM(A.COBRANZA_DIA) AS IMPORTE,
                SUM(A.COBRANZA_DIA) AS IMPORTENOM
          		FROM FECXC_CANINTER_DELDIA A
          		GROUP BY SEGMENTO, CANAL
         	)
    	UNION
        	SELECT A.ORDEN, A.TIPO, A.SUBTIPO, A.SEGMENTO, A.CANAL, A.IMPORTE, A.IMPORTENOM
        	FROM (
            		/*Se agrega columna de importe nominal*/
   					SELECT 1 AS ORDEN, 'DEL MES' AS TIPO, 'A?O ANTERIOR' AS SUBTIPO, SEGMENTO, CANAL, SUM(A.COBRANZA_MES) AS IMPORTE,
                    SUM(A.COBRANZAREAL_MES) AS IMPORTENOM
   					FROM FECXC_CANINTER_XMES_COB_ANT A
   					GROUP BY  SEGMENTO, CANAL
   					UNION
   					SELECT 1 AS ORDEN,'DEL MES' AS TIPO, 'REAL' AS SUBTIPO, SEGMENTO, CANAL, SUM(A.COBRANZA_MES) AS IMPORTE,
                    SUM(A.COBRANZA_MES) AS IMPORTENOM
   					FROM FECXC_CANINTER_XMES_COB_ACT A
   					GROUP BY SEGMENTO, CANAL
   					UNION
   					SELECT 1 AS ORDEN,'DEL MES' AS TIPO, 'PRESUPUESTO' AS SUBTIPO, SEGMENTO, CANAL, SUM(A.PRESUP_MES) AS IMPORTE,
                    SUM(A.PRESUP_MES) AS IMPORTENOM
   					FROM FECXC_CANINTER_XMES_PRE A
   					GROUP BY SEGMENTO, CANAL
                  )  A
       UNION
       		/*Se agrega columna de importe NOMINAL*/
       		SELECT 1 AS ORDEN,'DEL MES' AS TIPO, 'VAR REAL VS PPTO' AS SUBTIPO,A.SEGMENTO,A.CANAL,
            ( A.IMPORTE - NVL (B.IMPORTE,0.00) ) AS IMPORTE, ( A.IMPORTENOM - NVL (B.IMPORTE,0.00) ) AS IMPORTENOM
       		FROM (
                  SELECT SEGMENTO, CANAL, SUM(A.COBRANZA_MES) AS IMPORTE, SUM(A.COBRANZA_MES) AS IMPORTENOM
                  FROM FECXC_CANINTER_XMES_COB_ACT A
                  GROUP BY SEGMENTO, CANAL
        	 	 ) A,
         		 (
                  SELECT SEGMENTO, CANAL, SUM(A.PRESUP_MES) AS IMPORTE
                  FROM FECXC_CANINTER_XMES_PRE A
                  GROUP BY SEGMENTO, CANAL
         		 ) B
           WHERE A.SEGMENTO = B.SEGMENTO (+)
           AND  A.CANAL = B.CANAL (+)
       UNION
       		/*Se agrega columna de importe real o actualizado*/
       		SELECT 1 AS ORDEN,'DEL MES' AS TIPO, 'VARIACION REAL VS A?O ANTERIOR' AS SUBTIPO,A.SEGMENTO,A.CANAL,
            ( A.IMPORTE - NVL (B.IMPORTE,0.00) ) AS IMPORTE, ( A.IMPORTENOM - NVL (B.IMPORTENOM,0.00) ) AS IMPORTENOM
       		FROM (
          			SELECT SEGMENTO, CANAL, SUM(A.COBRANZA_MES) AS IMPORTE,SUM(A.COBRANZA_MES) AS IMPORTENOM
          			FROM FECXC_CANINTER_XMES_COB_ACT A
          			GROUP BY  SEGMENTO, CANAL
         		) A,
         		(
            		/*se sumariza columna adicional*/
                  SELECT SEGMENTO, CANAL, SUM(A.COBRANZA_MES) AS IMPORTE, SUM(A.COBRANZAREAL_MES) AS IMPORTENOM
                  FROM FECXC_CANINTER_XMES_COB_ANT A
                  GROUP BY SEGMENTO, CANAL
                 ) B
           WHERE A.SEGMENTO = B.SEGMENTO (+)
           AND  A.CANAL = B.CANAL (+)
       UNION
           SELECT A.ORDEN, A.TIPO, A.SUBTIPO, A.SEGMENTO, A.CANAL, A.IMPORTE, A.IMPORTENOM
           FROM (
                  SELECT 2 AS ORDEN,'A LA FECHA' AS TIPO, 'A?O ANTERIOR' AS SUBTIPO, SEGMENTO, CANAL, SUM(A.COBRANZA_MES) AS IMPORTE,
                  SUM(A.COBRANZAREAL_MES) AS IMPORTENOM
                  FROM FECXC_CANINTER_ALAFECH_COB_ANT A
                  GROUP BY  SEGMENTO, CANAL
              UNION
                  SELECT 2 AS ORDEN,'A LA FECHA' AS TIPO, 'REAL' AS SUBTIPO, SEGMENTO, CANAL, SUM(A.COBRANZA_MES) AS IMPORTE,
                  SUM(A.COBRANZAREAL_MES) AS IMPORTENOM
                  FROM FECXC_CANINTER_ALAFECH_COB_ACT A
                  GROUP BY SEGMENTO, CANAL
              UNION
                  SELECT 2 AS ORDEN,'A LA FECHA' AS TIPO, 'PRESUPUESTO' AS SUBTIPO, SEGMENTO, CANAL, SUM(A.PRESUP_MES) AS IMPORTE,
                  SUM(A.PRESUPREAL_MES) AS IMPORTENOM
                  FROM FECXC_CANINTER_ALAFECHA_PRE A
                  GROUP BY SEGMENTO, CANAL
              UNION
                  SELECT 2 AS ORDEN,'A LA FECHA' AS TIPO, 'VAR REAL VS PPTO' AS SUBTIPO,A.SEGMENTO,A.CANAL,
                  ( A.IMPORTE - NVL(B.IMPORTE,0.00) ) AS IMPORTE,
                  ( A.IMPORTENOM - NVL(B.IMPORTENOM,0.00) ) AS IMPORTENOM
                  FROM (
                     SELECT SEGMENTO, CANAL, SUM(A.COBRANZA_MES) AS IMPORTE, SUM(A.COBRANZAREAL_MES) AS IMPORTENOM
                     FROM FECXC_CANINTER_ALAFECH_COB_ACT A
                     GROUP BY SEGMENTO, CANAL
                    ) A,
                    (
                     SELECT SEGMENTO, CANAL, SUM(A.PRESUP_MES) AS IMPORTE, SUM(A.PRESUPREAL_MES) AS IMPORTENOM
                     FROM FECXC_CANINTER_ALAFECHA_PRE A
                     GROUP BY SEGMENTO, CANAL
                    ) B
                  WHERE A.SEGMENTO = B.SEGMENTO (+)
                  AND  A.CANAL = B.CANAL     (+)
          UNION
              SELECT 2 AS ORDEN,'A LA FECHA' AS TIPO, 'VARIACION REAL VS A?O ANTERIOR' AS SUBTIPO,A.SEGMENTO,A.CANAL,
              ( A.IMPORTE - NVL(B.IMPORTE,0.00) ) AS IMPORTE, ( A.IMPORTENOM - NVL(B.IMPORTENOM,0.00) ) AS IMPORTENOM
              FROM (
                 SELECT SEGMENTO, CANAL, SUM(A.COBRANZA_MES) AS IMPORTE, SUM(A.COBRANZAREAL_MES) AS IMPORTENOM
                 FROM FECXC_CANINTER_ALAFECH_COB_ACT A
                 GROUP BY  SEGMENTO, CANAL
                ) A,
                (
                 SELECT SEGMENTO, CANAL, SUM(A.COBRANZA_MES) AS IMPORTE, SUM(A.COBRANZAREAL_MES) AS IMPORTENOM
                 FROM FECXC_CANINTER_ALAFECH_COB_ANT A
                 GROUP BY SEGMENTO, CANAL
                ) B
              WHERE A.SEGMENTO = B.SEGMENTO (+)
              AND  A.CANAL = B.CANAL       (+)
      	) A
    ) A,
    FECXC_DET_CATALOGOS B,
    FECXC_DET_CATALOGOS C
  WHERE A.SEGMENTO = B.COD_SEC_LIN
  AND  B.TIPO_CAT = 'SEGMENTO'
  AND  A.CANAL = C.COD_SEC_LIN
  AND  (
     C.TIPO_CAT = 'CANAL'
    OR C.TIPO_CAT = 'REGION'
    OR C.TIPO_CAT = 'DIVISION'
    );
