CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "USRDRC"."DERCORP_HIST_CORPORATIVO_VW" ("ID_EMPRESA", "ID_META_ROW", "ID_FLEX_TBL", "NOM_FLEX", "VAL_C1", "VAL_C2", "VAL_C3", "VAL_C4", "VAL_C5", "VAL_C6", "VAL_C7", "VAL_C8", "VAL_C9") AS 
  SELECT
  META.ID_EMPRESA,
  META.ID_META_ROW,
  FLEX.ID_FLEX_TBL,
  FLEX.NOM_FLEX,
  CASE FLEX.ID_FLEX_TBL
      WHEN 30 THEN META.VAL_C4
      WHEN 27 THEN META.VAL_C18
      ELSE META.VAL_C3 END          AS VAL_C1,    --FECHA
  CASE FLEX.ID_FLEX_TBL
      WHEN 17 THEN DERCORP_CATALOGS_PKG.GET_ELEMENT_DESCRIP_FN(META.VAL_C1)
      WHEN 18 THEN DERCORP_CATALOGS_PKG.GET_ELEMENT_DESCRIP_FN(META.VAL_C1)
      WHEN 30 THEN DERCORP_CATALOGS_PKG.GET_ELEMENT_DESCRIP_FN(META.VAL_C3)
      ELSE DERCORP_CATALOGS_PKG.GET_ELEMENT_DESCRIP_FN(META.VAL_C2) END          AS VAL_C2,    -- TIPO de REUNION (TIPO CONTRATO)
    META.VAL_C149                   AS VAL_C3,                      --ASUNTO
  CASE FLEX.ID_FLEX_TBL
      WHEN 17 THEN META.VAL_C16
      WHEN 18 THEN META.VAL_C16
      ELSE META.VAL_C150 END         AS VAL_C4,    -- SEMAFORO
  CASE FLEX.ID_FLEX_TBL
      WHEN 17 THEN META.VAL_C8
      WHEN 18 THEN META.VAL_C8
      WHEN 23 THEN META.VAL_C106
      ELSE META.VAL_C86 END         AS VAL_C5,    -- ESCRITURA
  CASE FLEX.ID_FLEX_TBL
      WHEN 17 THEN META.VAL_C9
      WHEN 18 THEN META.VAL_C9
      WHEN 23 THEN META.VAL_C107
      ELSE META.VAL_C87 END         AS VAL_C6,    -- FECHA ESCRITURA
  CASE FLEX.ID_FLEX_TBL
      WHEN 17 THEN META.VAL_C5
      WHEN 18 THEN META.VAL_C5
      WHEN 23 THEN META.VAL_C107
      ELSE META.VAL_C82 END         AS VAL_C7,    -- RPPC
  CASE FLEX.ID_FLEX_TBL
      WHEN 17 THEN META.VAL_C19
      WHEN 18 THEN META.VAL_C19
      WHEN 23 THEN META.VAL_C115
      ELSE META.VAL_C95 END         AS VAL_C8,    -- FECHA RPPC
  CASE FLEX.ID_FLEX_TBL
      WHEN 17 THEN META.VAL_C150
      WHEN 18 THEN META.VAL_C150
      WHEN 23 THEN META.VAL_C103
      ELSE META.VAL_C83 END         AS VAL_C9    -- SEMAFORO
FROM
  DERCORP_METATBL_TAB META
  LEFT JOIN DERCORP_ADD_CAMPO_CAT_VAL_TAB CAT ON CAT.ID_CATALOGO_VALOR = META.VAL_C2
  LEFT JOIN DERCORP_FLEX_TBLS_TAB FLEX ON FLEX.ID_FLEX_TBL = META.ID_FLEX_TBL
WHERE
  --META.ID_FLEX_TBL IN (17,18, 20, 21, 22, 23, 28, 29, 31, 32, 33, 34, 35, 30, 27)
  FLEX.ATRIBUTO15 LIKE '%HIST_CORP%';
