CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "USRDRC"."DERCORP_REP_EST_COLUMNS_VW" ("ID_EMPRESA", "GRUPO", "ACCIONISTA", "RFC", "PAIS_RESIDENCIA", "CF", "CV", "PORCENTAJE", "TOTAL") AS 
  SELECT CS2.ID_EMPRESA,
       'Grupo' AS GRUPO,
       SUBSTR(CS2.CADENA, 1 ,INSTR(CS2.CADENA, '|', 1, 1)-1) AS ACCIONISTA,
       'RFC' AS RFC,
       'Pais de Residencia' AS PAIS_RESIDENCIA,
       SUBSTR(CS2.CADENA, INSTR(CS2.CADENA,'|', 1, 1)+1, INSTR(CS2.CADENA,'|',1,2)-INSTR(CS2.CADENA,'|',1,1)-1) AS CF,
       SUBSTR(CS2.CADENA, INSTR(CS2.CADENA,'|', 1, 2)+1, INSTR(CS2.CADENA,'|',1,3)-INSTR(CS2.CADENA,'|',1,2)-1) AS CV,
       'Porcentaje' AS PORCENTAJE,
       SUBSTR(CS2.CADENA, INSTR(CS2.CADENA,'|', -1, 1)+1) AS TOTAL
FROM (
SELECT
  CS.ID_EMPRESA,
  XXTV_CAPITAL_SOC_PKG.GET_COLUMNS_FN(CS.ID_EMPRESA) AS CADENA
FROM DERCORP_REP_ESTCAPSOC_VW CS) CS2;
