CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "USRDRC"."DERCORP_CONTROL_VW" ("ID_EMPRESA", "ID_META_ROW", "ID_FLEX_TBL", "NOM_FLEX", "VAL_C1", "VAL_C2", "VAL_C3", "VAL_C4", "VAL_C5", "VAL_C6", "VAL_C7", "VAL_C8", "VAL_C9", "ID_ESCRITURA", "IND_TIPO_ESCRITURA") AS 
  SELECT
  META.ID_EMPRESA,
  META.ID_META_ROW,
  FLEX.ID_FLEX_TBL,
  FLEX.NOM_FLEX,
  CASE FLEX.ID_FLEX_TBL
      WHEN 30 THEN META.VAL_C4
      WHEN 27 THEN META.VAL_C18
      ELSE META.VAL_C3 END          AS VAL_C1,    --FECHA
  CASE FLEX.ID_FLEX_TBL
      WHEN 17 THEN DERCORP_CATALOGS_PKG.GET_ELEMENT_DESCRIP_FN(META.VAL_C1)
      WHEN 18 THEN DERCORP_CATALOGS_PKG.GET_ELEMENT_DESCRIP_FN(META.VAL_C1)
      WHEN 30 THEN DERCORP_CATALOGS_PKG.GET_ELEMENT_DESCRIP_FN(META.VAL_C3)
      WHEN 27 THEN META.VAL_C2
      ELSE DERCORP_CATALOGS_PKG.GET_ELEMENT_DESCRIP_FN(META.VAL_C2) END          AS VAL_C2,    -- TIPO de REUNION (TIPO CONTRATO)
    META.VAL_C149                   AS VAL_C3,                      --ASUNTO
  CASE FLEX.ID_FLEX_TBL
      WHEN 17 THEN META.VAL_C16
      WHEN 18 THEN META.VAL_C16
      ELSE META.VAL_C150 END         AS VAL_C4,    -- SEMAFORO
  CASE FLEX.ID_FLEX_TBL
      WHEN 17 THEN META.VAL_C8
      WHEN 18 THEN META.VAL_C8
      WHEN 23 THEN META.VAL_C106
      ELSE META.VAL_C86 END         AS VAL_C5,    -- ESCRITURA
  CASE FLEX.ID_FLEX_TBL
      WHEN 17 THEN META.VAL_C9
      WHEN 18 THEN META.VAL_C9
      WHEN 23 THEN META.VAL_C107
      ELSE META.VAL_C87 END         AS VAL_C6,    -- FECHA ESCRITURA
  CASE FLEX.ID_FLEX_TBL
      WHEN 17 THEN META.VAL_C5
      WHEN 18 THEN META.VAL_C5
      WHEN 23 THEN META.VAL_C107
      ELSE META.VAL_C82 END         AS VAL_C7,    -- RPPC
  CASE FLEX.ID_FLEX_TBL
      WHEN 17 THEN META.VAL_C19
      WHEN 18 THEN META.VAL_C19
      WHEN 23 THEN META.VAL_C115
      ELSE META.VAL_C95 END         AS VAL_C8,    -- FECHA RPPC
  CASE FLEX.ID_FLEX_TBL
      WHEN 17 THEN META.VAL_C150
      WHEN 18 THEN META.VAL_C150
      WHEN 23 THEN META.VAL_C103
      ELSE META.VAL_C83 END         AS VAL_C9,    -- SEMAFORO
  NULL AS ID_ESCRITURA,
  NULL AS IND_TIPO_ESCRITURA
FROM
  DERCORP_METATBL_TAB META
  LEFT JOIN DERCORP_ADD_CAMPO_CAT_VAL_TAB CAT ON CAT.ID_CATALOGO_VALOR = META.VAL_C2
  LEFT JOIN DERCORP_FLEX_TBLS_TAB FLEX ON FLEX.ID_FLEX_TBL = META.ID_FLEX_TBL
WHERE
  --META.ID_FLEX_TBL IN (17,18, 20, 21, 22, 23, 28, 29, 31, 32, 33, 34, 35, 30, 27)
  FLEX.ATRIBUTO15 LIKE '%CONTROL%'
  UNION ALL
SELECT ESC.ID_EMPRESA,
   99999 AS ID_META_ROW,
   100 AS ID_FLEX_TBL,
   'Poderes' AS NOM_FLEX,
   ESC.FEC_FECHA AS VAL_C1,
   (SELECT VAL_CAT_VAL FROM DERCORP_ADD_CAMPO_CAT_VAL_TAB
    WHERE ID_CATALOGO=49 AND ID_CATALOGO_VALOR=ESC.IND_DELEGADO_POR) AS VAL_C2,
   CASE ESC.IND_TIPO_ESCRITURA
    WHEN 'ER' THEN 'Revocacion de Poderes'
    WHEN 'PG' THEN
      CASE (SELECT COUNT(DISTINCT ESC_TEMP.IND_TIPO_ESCRITURA) FROM PENDIUM_ESCRITURA_PODER_TAB ESC_TEMP INNER JOIN PENDIUM_OTORGAPODER_EP_TAB POD_TEMP
                ON ESC_TEMP.ID_EP_PK = POD_TEMP.ID_EP_FK
                WHERE ESC_TEMP.DES_ESCRITURA = ESC.DES_ESCRITURA
                AND ESC_TEMP.ID_EMPRESA=ESC.ID_EMPRESA GROUP BY ESC_TEMP.ID_EMPRESA)
      WHEN 1 THEN 'Otorgamiento de Poderes Generales'
      ELSE 'Otorgamiento de Poderes Generales y Especiales' END
    WHEN 'PE' THEN 'Otorgamiento de Poderes Especiales'
    END  AS VAL_C3,
   (CASE NVL(ind_aplica_status,0) WHEN 1 THEN
      CASE ind_status_ac WHEN '6' THEN
        CASE WHEN id_ent_resp IS NOT NULL THEN
          CASE WHEN fec_ent IS NOT NULL THEN 'semaforo_green.png'
          ELSE 'semaforo_red.png' END
        ELSE 'semaforo_red.png' END
      ELSE 'semaforo_red.png' END
    ELSE 'semaforo_gray.png' END) AS VAL_C4,
   ESC.DES_ESCRITURA AS VAL_C5,
   ESC.FEC_OTORGAMIENTO_INSTR AS VAL_C6,
   (CASE ESC.IND_REQUIERE_INSCR_RPPC
    WHEN '1' THEN 'Si'
    ELSE 'No' END) AS VAL_C7,
   ESC.FEC_REGISTRO AS VAL_C8,
   (CASE (CASE NVL(ind_requiere_proto,0) WHEN 1 THEN
            CASE WHEN des_escritura IS NOT NULL THEN
              CASE WHEN num_documentum_instr IS NOT NULL THEN
                CASE WHEN fec_otorgamiento_instr IS NOT NULL THEN
                  CASE WHEN num_licenciado IS NOT NULL THEN 1
                  ELSE 0 END
                ELSE 0 END
              ELSE 0 END
            ELSE 0 END
          ELSE 1 END) WHEN 1 THEN
    CASE (CASE NVL(ind_requiere_inscr_rppc,'0') WHEN '1' THEN
            CASE WHEN fec_registro IS NOT NULL THEN
              CASE WHEN num_folio_merc IS NOT NULL THEN 1
              ELSE 0 END
            ELSE 0 END
          ELSE 1 END) WHEN 1 THEN 'semaforo_green.png'
    ELSE 'semaforo_red.png' END
    ELSE 'semaforo_red.png' END) AS VAL_C9,
    ESC.ID_EP_PK,
    ESC.IND_TIPO_ESCRITURA AS IND_TIPO_ESCRITURA
FROM (
      SELECT PENDIUM_ESCRITURA_PODER_TAB.*
      FROM PENDIUM_ESCRITURA_PODER_TAB INNER JOIN DERCORP_ADD_CAMPO_CAT_VAL_TAB
      ON IND_DELEGADO_POR=ID_CATALOGO_VALOR
      WHERE 1=1
      AND VAL_CAT_VAL!='Apoderado'
      AND IND_TIPO_ESCRITURA IN ('PG')
      AND IND_STATUS=1
      AND (CASE PENDIUM_ESCRITURA_PODER_TAB.IND_TIPO_ESCRITURA WHEN 'ER' THEN 1
      ELSE (SELECT COUNT(DISTINCT ESC.IND_TIPO_ESCRITURA) FROM PENDIUM_ESCRITURA_PODER_TAB ESC INNER JOIN PENDIUM_OTORGAPODER_EP_TAB POD
                      ON ESC.ID_EP_PK = POD.ID_EP_FK
                      WHERE ESC.DES_ESCRITURA = PENDIUM_ESCRITURA_PODER_TAB.DES_ESCRITURA
                      AND ESC.ID_EMPRESA=PENDIUM_ESCRITURA_PODER_TAB.ID_EMPRESA GROUP BY ESC.ID_EMPRESA)END)=2
      UNION ALL
      SELECT PENDIUM_ESCRITURA_PODER_TAB.*
      FROM PENDIUM_ESCRITURA_PODER_TAB INNER JOIN DERCORP_ADD_CAMPO_CAT_VAL_TAB
      ON IND_DELEGADO_POR=ID_CATALOGO_VALOR
      WHERE 1=1
      AND VAL_CAT_VAL!='Apoderado'
      AND IND_TIPO_ESCRITURA IN ('PG','PE','ER')
      AND IND_STATUS=1
      AND (CASE PENDIUM_ESCRITURA_PODER_TAB.IND_TIPO_ESCRITURA WHEN 'ER' THEN 1
      ELSE (SELECT COUNT(DISTINCT ESC.IND_TIPO_ESCRITURA) FROM PENDIUM_ESCRITURA_PODER_TAB ESC INNER JOIN PENDIUM_OTORGAPODER_EP_TAB POD
                      ON ESC.ID_EP_PK = POD.ID_EP_FK
                      WHERE ESC.DES_ESCRITURA = PENDIUM_ESCRITURA_PODER_TAB.DES_ESCRITURA
                      AND ESC.ID_EMPRESA=PENDIUM_ESCRITURA_PODER_TAB.ID_EMPRESA GROUP BY ESC.ID_EMPRESA)END)=1
) ESC;
