CREATE OR REPLACE FORCE NONEDITIONABLE VIEW "COFIDI"."XXCOFIDI_USUARIOS_CONSULTA_VW" ("USUARIO", "NOMBRE_COMPLETO", "PUESTO", "CORREO_ELECTRONICO", "FEC_CREACION", "FEC_ULTIMA_MODIFICACION", "FEC_ULTIMO_LOGEO", "FEC_VIGENCIA", "COMENTARIOS", "ROL", "STATUS", "ORIGEN_ASIGNADO", "CAMBIAR_CONTRASENIA", "ELIMINAR_REG", "CONSULTA_USUARIOS", "GENERAR_REPORTE_USUARIOS", "ADMINISTRAR_USUARIOS", "CONSULTAR_BITACORA", "CONSULTAR_DOCUMENTOS", "ADMINISTRAR_CATALOGOS", "NOM_EMPRESA", "RFC", "COD_CIA", "TIPO_USUARIO") AS 
  SELECT XUT.USER_NAME USUARIO,
            XUT.AP_PATERNO || ' ' || XUT.AP_MATERNO || ' ' || XUT.NOM_USUARIO
               NOMBRE_COMPLETO,
            XUT.PUESTO PUESTO,
            XUT.CORREO_ELECTRONICO CORREO_ELECTRONICO,
            XUT.FEC_CREACION FEC_CREACION,
            XUT.FEC_ULTIMA_MODIFICACION FEC_ULTIMA_MODIFICACION,
            XULT.FEC_ULTIMO_LOGEO FEC_ULTIMO_LOGEO,
            XUT.FEC_VIGENCIA FEC_VIGENCIA,
            XUT.COMENTARIOS COMENTARIOS,
            XRCT.ROL ROL,
            XECT.ESTADO STATUS,
            XOCT.ORIGEN ORIGEN_ASIGNADO,
            DECODE (XUT.CAMBIAR_CONTRASENIA, 1, 'SI', 'NO') CAMBIAR_CONTRASENIA,
            DECODE (XUT.ELIMINAR_REG, 1, 'SI', 'NO') ELIMINAR_REG,
            DECODE (XUT.CONSULTAR_USUARIOS, 1, 'SI', 'NO') CONSULTA_USUARIOS,
            DECODE (XUT.GENERAR_REPORTE_USUARIOS, 1, 'SI', 'NO')
               GENERAR_REPORTE_USUARIOS,
            DECODE (XUT.ADMINISTRAR_USUARIOS, 1, 'SI', 'NO')
               ADMINISTRAR_USUARIOS,
            DECODE (XUT.CONSULTAR_BITACORA, 1, 'SI', 'NO') CONSULTAR_BITACORA,
            DECODE (XUT.CONSULTAR_DOCUMENTOS, 1, 'SI', 'NO')
               CONSULTAR_DOCUMENTOS,
            DECODE (XUT.ADMINISTRAR_CATALOGOS, 1, 'SI', 'NO')
               ADMINISTRAR_CATALOGOS,
            ---------------------------------------------------------------
            XECT.NOM_EMPRESA NOM_EMPRESA,
            XECT.RFC RFC,
            XECT.COD_CIA COD_CIA,
            DECODE (XUT.TIPO_USUARIO, 1, 'COFIDI', 'LDAP') TIPO_USUARIO
       FROM XXCOFIDI_USUARIO_TAB XUT,
            XXCOFIDI_USUARIO_LOGIN_TAB XULT,
            XXCOFIDI_ROL_CT_TAB XRCT,
            XXCOFIDI_ESTADO_CT_TAB XECT,
            XXCOFIDI_ORIGEN_CT_TAB XOCT,
            ---------------------------
            XXCOFIDI_USU_ORI_EMP_TAB XUOET,
            XXCOFIDI_EMPRESA_CT_TAB XECT
      WHERE     1 = 1
            AND XUT.ID_USUARIO_PK = XULT.ID_USUARIO_FK(+)
            AND XRCT.ID_ROL_PK = XUT.ID_ROL_FK(+)
            AND XECT.ID_ESTADO_PK = XUT.ID_ESTADO_FK
            AND XUT.ID_ORIGEN_FK = XOCT.ID_ORIGEN_PK(+)
            ------------------------------------------
            AND XUT.ID_USUARIO_PK = XUOET.ID_USUARIO_FK(+)
            AND XECT.ID_EMPRESA_PK(+) = XUOET.ID_EMPRESA_FK
   ORDER BY XUT.AP_PATERNO;
